services:
  wiremock:
    image: wiremock/wiremock:3
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    environment:
      WIREMOCK_OPTIONS: "--disable-request-logging"
