//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen C:\Users\tbuese\Desktop\Symxchange\ParameterService/*.xsd --sf --un --uc --order --cn -0 --collectionSettersMode=Public -o C:\Users\tbuese\Desktop\Symxchange\ParameterService\generated-output -n ParameterService
namespace ParameterService
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AcsGlobalFields", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("AcsGlobalFields", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    public partial class AcsGlobalFields
    {
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("AcsAccountManagerEnable", Order=0, Form=XmlSchemaForm.Unqualified)]
        public bool AcsAccountManagerEnableValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AcsAccountManagerEnable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool AcsAccountManagerEnableValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<bool> AcsAccountManagerEnable
        {
            get
            {
                if (this.AcsAccountManagerEnableValueSpecified)
                {
                    return this.AcsAccountManagerEnableValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AcsAccountManagerEnableValue = value.GetValueOrDefault();
                this.AcsAccountManagerEnableValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("AcsTellerTranEnable", Order=1, Form=XmlSchemaForm.Unqualified)]
        public bool AcsTellerTranEnableValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AcsTellerTranEnable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool AcsTellerTranEnableValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<bool> AcsTellerTranEnable
        {
            get
            {
                if (this.AcsTellerTranEnableValueSpecified)
                {
                    return this.AcsTellerTranEnableValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AcsTellerTranEnableValue = value.GetValueOrDefault();
                this.AcsTellerTranEnableValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("CreditReportExpireDays", Order=2, Form=XmlSchemaForm.Unqualified)]
        public bool CreditReportExpireDaysValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CreditReportExpireDays property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool CreditReportExpireDaysValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<bool> CreditReportExpireDays
        {
            get
            {
                if (this.CreditReportExpireDaysValueSpecified)
                {
                    return this.CreditReportExpireDaysValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreditReportExpireDaysValue = value.GetValueOrDefault();
                this.CreditReportExpireDaysValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("SecuredLoanTypeList", Order=3, Form=XmlSchemaForm.Unqualified)]
        public bool SecuredLoanTypeListValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SecuredLoanTypeList property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool SecuredLoanTypeListValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<bool> SecuredLoanTypeList
        {
            get
            {
                if (this.SecuredLoanTypeListValueSpecified)
                {
                    return this.SecuredLoanTypeListValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SecuredLoanTypeListValue = value.GetValueOrDefault();
                this.SecuredLoanTypeListValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("UnsecuredLoanTypeList", Order=4, Form=XmlSchemaForm.Unqualified)]
        public bool UnsecuredLoanTypeListValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UnsecuredLoanTypeList property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool UnsecuredLoanTypeListValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<bool> UnsecuredLoanTypeList
        {
            get
            {
                if (this.UnsecuredLoanTypeListValueSpecified)
                {
                    return this.UnsecuredLoanTypeListValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnsecuredLoanTypeListValue = value.GetValueOrDefault();
                this.UnsecuredLoanTypeListValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("Version_1", Order=5, Form=XmlSchemaForm.Unqualified)]
        public ParameterService.VersionType Version1 { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElementAttribute(Order=6)]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AcsGlobalFields" /> class.</para>
        /// </summary>
        public AcsGlobalFields()
        {
            this._any = new Collection<XmlElement>();
        }
    }
}
