//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen C:\Users\tbuese\Desktop\Symxchange\ParameterService/*.xsd --sf --un --uc --order --cn -0 --collectionSettersMode=Public -o C:\Users\tbuese\Desktop\Symxchange\ParameterService\generated-output -n ParameterService
namespace ParameterService
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocTypeDefault", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("DocTypeDefault", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    public partial class DocTypeDefault
    {
        
        [XmlElementAttribute("Description", Order=0, Form=XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("DocumentType", Order=1, Form=XmlSchemaForm.Unqualified)]
        public short DocumentTypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DocumentType property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool DocumentTypeValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> DocumentType
        {
            get
            {
                if (this.DocumentTypeValueSpecified)
                {
                    return this.DocumentTypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DocumentTypeValue = value.GetValueOrDefault();
                this.DocumentTypeValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("ExcpNoticeCountCpWork", Order=2, Form=XmlSchemaForm.Unqualified)]
        public short ExcpNoticeCountCpWorkValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExcpNoticeCountCpWork property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ExcpNoticeCountCpWorkValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> ExcpNoticeCountCpWork
        {
            get
            {
                if (this.ExcpNoticeCountCpWorkValueSpecified)
                {
                    return this.ExcpNoticeCountCpWorkValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExcpNoticeCountCpWorkValue = value.GetValueOrDefault();
                this.ExcpNoticeCountCpWorkValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("ExcpNoticeOption", Order=3, Form=XmlSchemaForm.Unqualified)]
        public short ExcpNoticeOptionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExcpNoticeOption property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ExcpNoticeOptionValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> ExcpNoticeOption
        {
            get
            {
                if (this.ExcpNoticeOptionValueSpecified)
                {
                    return this.ExcpNoticeOptionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExcpNoticeOptionValue = value.GetValueOrDefault();
                this.ExcpNoticeOptionValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("ExpireDate", Order=4, Form=XmlSchemaForm.Unqualified, DataType="date")]
        public DateTime ExpireDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExpireDate property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ExpireDateValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<DateTime> ExpireDate
        {
            get
            {
                if (this.ExpireDateValueSpecified)
                {
                    return this.ExpireDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExpireDateValue = value.GetValueOrDefault();
                this.ExpireDateValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("Type", Order=5, Form=XmlSchemaForm.Unqualified)]
        public short TypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> Type
        {
            get
            {
                if (this.TypeValueSpecified)
                {
                    return this.TypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeValue = value.GetValueOrDefault();
                this.TypeValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("UserChar1", Order=6, Form=XmlSchemaForm.Unqualified)]
        public string UserChar1 { get; set; }
        
        [XmlElementAttribute("UserChar2", Order=7, Form=XmlSchemaForm.Unqualified)]
        public string UserChar2 { get; set; }
        
        [XmlElementAttribute("UserChar3", Order=8, Form=XmlSchemaForm.Unqualified)]
        public string UserChar3 { get; set; }
        
        [XmlElementAttribute("UserChar4", Order=9, Form=XmlSchemaForm.Unqualified)]
        public string UserChar4 { get; set; }
        
        [XmlElementAttribute("UserChar5", Order=10, Form=XmlSchemaForm.Unqualified)]
        public string UserChar5 { get; set; }
        
        [XmlElementAttribute("UserChar6", Order=11, Form=XmlSchemaForm.Unqualified)]
        public string UserChar6 { get; set; }
        
        [XmlElementAttribute("Version_1", Order=12, Form=XmlSchemaForm.Unqualified)]
        public ParameterService.VersionType Version1 { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElementAttribute(Order=13)]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DocTypeDefault" /> class.</para>
        /// </summary>
        public DocTypeDefault()
        {
            this._any = new Collection<XmlElement>();
        }
    }
}
