//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen C:\Users\tbuese\Desktop\Symxchange\ParameterService/*.xsd --sf --un --uc --order --cn -0 --collectionSettersMode=Public -o C:\Users\tbuese\Desktop\Symxchange\ParameterService\generated-output -n ParameterService
namespace ParameterService
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Stock", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Stock", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/retrieve")]
    public partial class Stock
    {
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("Type", Order=0, Form=XmlSchemaForm.Unqualified)]
        public short TypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> Type
        {
            get
            {
                if (this.TypeValueSpecified)
                {
                    return this.TypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeValue = value.GetValueOrDefault();
                this.TypeValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TypeCollateralPercent", Order=1, Form=XmlSchemaForm.Unqualified)]
        public decimal TypeCollateralPercentValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TypeCollateralPercent property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeCollateralPercentValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TypeCollateralPercent
        {
            get
            {
                if (this.TypeCollateralPercentValueSpecified)
                {
                    return this.TypeCollateralPercentValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeCollateralPercentValue = value.GetValueOrDefault();
                this.TypeCollateralPercentValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TypeDecimalPrice", Order=2, Form=XmlSchemaForm.Unqualified)]
        public decimal TypeDecimalPriceValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TypeDecimalPrice property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeDecimalPriceValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TypeDecimalPrice
        {
            get
            {
                if (this.TypeDecimalPriceValueSpecified)
                {
                    return this.TypeDecimalPriceValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeDecimalPriceValue = value.GetValueOrDefault();
                this.TypeDecimalPriceValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("TypeDescription", Order=3, Form=XmlSchemaForm.Unqualified)]
        public string TypeDescription { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<StockTypeFractionPrice> _typeFractionPrice;
        
        [XmlElementAttribute("TypeFractionPrice", Order=4, Form=XmlSchemaForm.Unqualified)]
        public Collection<StockTypeFractionPrice> TypeFractionPrice
        {
            get
            {
                return _typeFractionPrice;
            }
            set
            {
                _typeFractionPrice = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TypeFractionPrice collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TypeFractionPriceSpecified
        {
            get
            {
                return ((this.TypeFractionPrice != null) 
                            && (this.TypeFractionPrice.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Stock" /> class.</para>
        /// </summary>
        public Stock()
        {
            this._typeFractionPrice = new Collection<StockTypeFractionPrice>();
            this._any = new Collection<XmlElement>();
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TypeStockDollars", Order=5, Form=XmlSchemaForm.Unqualified)]
        public short TypeStockDollarsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TypeStockDollars property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeStockDollarsValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> TypeStockDollars
        {
            get
            {
                if (this.TypeStockDollarsValueSpecified)
                {
                    return this.TypeStockDollarsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeStockDollarsValue = value.GetValueOrDefault();
                this.TypeStockDollarsValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TypeStockEighths", Order=6, Form=XmlSchemaForm.Unqualified)]
        public short TypeStockEighthsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TypeStockEighths property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TypeStockEighthsValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> TypeStockEighths
        {
            get
            {
                if (this.TypeStockEighthsValueSpecified)
                {
                    return this.TypeStockEighthsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeStockEighthsValue = value.GetValueOrDefault();
                this.TypeStockEighthsValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("TypeTickerSymbol", Order=7, Form=XmlSchemaForm.Unqualified)]
        public string TypeTickerSymbol { get; set; }
        
        [XmlElementAttribute("Version_1", Order=8, Form=XmlSchemaForm.Unqualified)]
        public ParameterService.VersionType Version1 { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElementAttribute(Order=9)]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
    }
}
