//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen C:\Users\tbuese\Desktop\Symxchange\PoweronService/*.xsd --sf --un --uc --order --cn -0 --collectionSettersMode=Public -o C:\Users\tbuese\Desktop\Symxchange\PoweronService\generated-output -n PowerOnService
namespace PowerOnService
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ExecutionRequestBody", Namespace="http://www.symxchange.generated.symitar.com/noncrud/poweron/dto")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ExecutionRequestBody
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [MaxLengthAttribute(32)]
        [XmlElementAttribute("File", Order=0, Form=XmlSchemaForm.Unqualified)]
        public string File { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 128.</para>
        /// </summary>
        [RangeAttribute(typeof(int), "1", "128")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("RGSession", Order=1, Form=XmlSchemaForm.Unqualified)]
        public int RgSessionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RgSession property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool RgSessionValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 128.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> RgSession
        {
            get
            {
                if (this.RgSessionValueSpecified)
                {
                    return this.RgSessionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RgSessionValue = value.GetValueOrDefault();
                this.RgSessionValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("UserDefinedParameters", Order=2, Form=XmlSchemaForm.Unqualified)]
        public UserDefinedParameters UserDefinedParameters { get; set; }
        
        [XmlElementAttribute("PromptResponse", Order=3, Form=XmlSchemaForm.Unqualified)]
        public PromptResponse PromptResponse { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum inclusive value: 32767.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [RangeAttribute(typeof(short), "0", "32767")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("User", Order=4, Form=XmlSchemaForm.Unqualified)]
        public short UserValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the User property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool UserValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum inclusive value: 32767.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<short> User
        {
            get
            {
                if (this.UserValueSpecified)
                {
                    return this.UserValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UserValue = value.GetValueOrDefault();
                this.UserValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("Version_1", Order=5, Form=XmlSchemaForm.Unqualified)]
        public PowerOnService.VersionType Version1 { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElementAttribute(Order=6)]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ExecutionRequestBody" /> class.</para>
        /// </summary>
        public ExecutionRequestBody()
        {
            this._any = new Collection<XmlElement>();
        }
    }
}
