//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen C:\Users\tbuese\Desktop\Symxchange\ParameterService/*.xsd --sf --un --uc --order --cn -0 --collectionSettersMode=Public -o C:\Users\tbuese\Desktop\Symxchange\ParameterService\generated-output -n ParameterService
namespace ParameterService
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("OnlineSba", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/update")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("OnlineSba", Namespace="http://www.symxchange.generated.symitar.com/crud/parameter/dto/update")]
    [XmlIncludeAttribute(typeof(OnlineSbaFields_2))]
    public partial class OnlineSba_2
    {
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("AcctToAcctTransferGlCode", Order=0, Form=XmlSchemaForm.Unqualified)]
        public short AcctToAcctTransferGlCodeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AcctToAcctTransferGlCode property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool AcctToAcctTransferGlCodeValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> AcctToAcctTransferGlCode
        {
            get
            {
                if (this.AcctToAcctTransferGlCodeValueSpecified)
                {
                    return this.AcctToAcctTransferGlCodeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AcctToAcctTransferGlCodeValue = value.GetValueOrDefault();
                this.AcctToAcctTransferGlCodeValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("BranchAddressFormat", Order=1, Form=XmlSchemaForm.Unqualified)]
        public short BranchAddressFormatValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BranchAddressFormat property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool BranchAddressFormatValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> BranchAddressFormat
        {
            get
            {
                if (this.BranchAddressFormatValueSpecified)
                {
                    return this.BranchAddressFormatValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BranchAddressFormatValue = value.GetValueOrDefault();
                this.BranchAddressFormatValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("ItcHoldTypeDefault", Order=2, Form=XmlSchemaForm.Unqualified)]
        public short ItcHoldTypeDefaultValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ItcHoldTypeDefault property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ItcHoldTypeDefaultValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> ItcHoldTypeDefault
        {
            get
            {
                if (this.ItcHoldTypeDefaultValueSpecified)
                {
                    return this.ItcHoldTypeDefaultValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ItcHoldTypeDefaultValue = value.GetValueOrDefault();
                this.ItcHoldTypeDefaultValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TransactionLimit", Order=3, Form=XmlSchemaForm.Unqualified)]
        public short TransactionLimitValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TransactionLimit property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TransactionLimitValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> TransactionLimit
        {
            get
            {
                if (this.TransactionLimitValueSpecified)
                {
                    return this.TransactionLimitValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TransactionLimitValue = value.GetValueOrDefault();
                this.TransactionLimitValueSpecified = value.HasValue;
            }
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlElementAttribute("TrnsonOwnInstitution", Order=4, Form=XmlSchemaForm.Unqualified)]
        public short TrnsonOwnInstitutionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TrnsonOwnInstitution property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TrnsonOwnInstitutionValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public Nullable<short> TrnsonOwnInstitution
        {
            get
            {
                if (this.TrnsonOwnInstitutionValueSpecified)
                {
                    return this.TrnsonOwnInstitutionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TrnsonOwnInstitutionValue = value.GetValueOrDefault();
                this.TrnsonOwnInstitutionValueSpecified = value.HasValue;
            }
        }
        
        [XmlElementAttribute("Version_1", Order=5, Form=XmlSchemaForm.Unqualified)]
        public ParameterService.VersionType Version1 { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElementAttribute(Order=6)]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="OnlineSba_2" /> class.</para>
        /// </summary>
        public OnlineSba_2()
        {
            this._any = new Collection<XmlElement>();
        }
    }
}
