import { VersionType } from "./versionType";

export interface AccountDefaultFields {
    acctType: boolean | null;
    cappedFeesAmountCap: boolean | null;
    cappedFeesCountCap: boolean | null;
    closeDate: boolean | null;
    commercialCode: boolean | null;
    countLimit: number[];
    eStmtEnable: boolean | null;
    eStmtNotify: boolean | null;
    enableFloat: boolean | null;
    headOfHousehold: boolean | null;
    krHoldBaseAmount: boolean | null;
    limit: number[];
    memberGroup: boolean | null;
    memberStatus: boolean | null;
    nonRegCcCheckHoldBaseAmt: boolean | null;
    perItemLimit: number[];
    proxyDate: boolean | null;
    reference: boolean | null;
    relationshipCode: boolean | null;
    relationshipOverride: boolean | null;
    relationshipOverrideEffDate: boolean | null;
    relationshipOverrideExpDate: boolean | null;
    restrict: boolean | null;
    stateReporting: boolean | null;
    statementMailCode: boolean | null;
    type: boolean | null;
    userAmount1: boolean | null;
    userAmount2: boolean | null;
    userChar1: boolean | null;
    userChar2: boolean | null;
    userChar3: boolean | null;
    userChar4: boolean | null;
    userDate1: boolean | null;
    userDate2: boolean | null;
    warningCode: number[];
    version1: VersionType;
}