import { AccountAlternateAddress_2 } from "./accountAlternateAddress_2";
import { AccountAlternatePhone_2 } from "./accountAlternatePhone_2";
import { AccountCountLimit_2 } from "./accountCountLimit_2";
import { AccountLimit_2 } from "./accountLimit_2";
import { AccountLimitAmount_2 } from "./accountLimitAmount_2";
import { AccountLimitCount_2 } from "./accountLimitCount_2";
import { AccountLimitDescription_2 } from "./accountLimitDescription_2";
import { AccountNsfMonthlyCount_2 } from "./accountNsfMonthlyCount_2";
import { AccountPayeeLine_2 } from "./accountPayeeLine_2";
import { AccountPayeePhone_2 } from "./accountPayeePhone_2";
import { AccountPaymentHistory_2 } from "./accountPaymentHistory_2";
import { AccountPerItemLimit_2 } from "./accountPerItemLimit_2";
import { AccountWarningCode_2 } from "./accountWarningCode_2";
import { AccountWarningExpiration_2 } from "./accountWarningExpiration_2";
import { VersionType } from "./versionType";

export interface Account_2 {
    activityDate: string | null;
    alternateAddress: AccountAlternateAddress_2[];
    alternateNameLocator: number | null;
    alternateNameType: number | null;
    alternatePhone: AccountAlternatePhone_2[];
    bondIntLastYear: number | null;
    bondIntYtd: number | null;
    branch: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesAmtPeriod: number | null;
    cappedFeesCntPeriod: number | null;
    cappedFeesCountCap: number | null;
    cdTotalAmount: number | null;
    closeDate: string | null;
    commercialCode: number | null;
    correspondDate: string | null;
    countLimit: AccountCountLimit_2[];
    crTotalAmount: number | null;
    createdAtBranch: number | null;
    createdByUser: number | null;
    currentRelationshipCode: number | null;
    divLastYearNonTax: number | null;
    divLastYearTax: number | null;
    divYtdNontax: number | null;
    divYtdTax: number | null;
    eStmtEnable: number | null;
    eStmtNotify: number | null;
    enableFloat: number | null;
    fmLastPurgeDate: string | null;
    frCdTotalAmount: number | null;
    frCdUnits: number | null;
    frCrTotalAmount: number | null;
    frCrUnits: number | null;
    frozenMode: number | null;
    headOfHousehold: number | null;
    householdAccount: string;
    householdStatement: number | null;
    interestLastYear: number | null;
    interestYtd: number | null;
    invalidAttemptCount: number | null;
    invalidAttemptDate: string | null;
    invalidAttemptTime: number | null;
    krHoldBaseAmount: number | null;
    krTotalAmount: number | null;
    krTotalDate: string | null;
    lastFmDate: string | null;
    limit: AccountLimit_2[];
    limitAmount: AccountLimitAmount_2[];
    limitCount: AccountLimitCount_2[];
    limitDescription: AccountLimitDescription_2[];
    limitUsageDate: string | null;
    memberGroup: number | null;
    memberStatus: number | null;
    nonRegCcCheckHoldBaseAmt: number | null;
    nonRegCcCheckTotalAmt: number | null;
    nsfMonthlyCount: AccountNsfMonthlyCount_2[];
    nsfToday: number | null;
    number: string;
    openDate: string | null;
    payeeLine: AccountPayeeLine_2[];
    payeeNameLocator: number | null;
    payeeNameType: number | null;
    payeePhone: AccountPayeePhone_2[];
    paymentHistory: AccountPaymentHistory_2[];
    perItemLimit: AccountPerItemLimit_2[];
    prgdRecActivityDt: string | null;
    proxyDate: string | null;
    recordChangeDate: string | null;
    reference: string;
    relationshipCode: number | null;
    relationshipOverride: number | null;
    relationshipOverrideEffDate: string | null;
    relationshipOverrideExpDate: string | null;
    restrict: number | null;
    stateReporting: string;
    statementMailCode: number | null;
    type: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    warningCode: AccountWarningCode_2[];
    warningExpiration: AccountWarningExpiration_2[];
    wdTotalAmount: number | null;
    wrTotalAmount: number | null;
    version1: VersionType;
}