import { VersionType } from "./versionType";

export interface AccountFields {
    activityDate: boolean | null;
    alternateAddress: number[];
    alternateNameLocator: boolean | null;
    alternateNameType: boolean | null;
    alternatePhone: number[];
    bondIntLastYear: boolean | null;
    bondIntYtd: boolean | null;
    branch: boolean | null;
    cappedFeesAmountCap: boolean | null;
    cappedFeesAmtPeriod: boolean | null;
    cappedFeesCntPeriod: boolean | null;
    cappedFeesCountCap: boolean | null;
    cdTotalAmount: boolean | null;
    closeDate: boolean | null;
    commercialCode: boolean | null;
    correspondDate: boolean | null;
    countLimit: number[];
    crTotalAmount: boolean | null;
    createdAtBranch: boolean | null;
    createdByUser: boolean | null;
    currentRelationshipCode: boolean | null;
    divLastYearNonTax: boolean | null;
    divLastYearTax: boolean | null;
    divYtdNontax: boolean | null;
    divYtdTax: boolean | null;
    eStmtEnable: boolean | null;
    eStmtNotify: boolean | null;
    enableFloat: boolean | null;
    fmLastPurgeDate: boolean | null;
    frCdTotalAmount: boolean | null;
    frCdUnits: boolean | null;
    frCrTotalAmount: boolean | null;
    frCrUnits: boolean | null;
    frozenMode: boolean | null;
    headOfHousehold: boolean | null;
    householdAccount: boolean | null;
    householdStatement: boolean | null;
    interestLastYear: boolean | null;
    interestYtd: boolean | null;
    invalidAttemptCount: boolean | null;
    invalidAttemptDate: boolean | null;
    invalidAttemptTime: boolean | null;
    krHoldBaseAmount: boolean | null;
    krTotalAmount: boolean | null;
    krTotalDate: boolean | null;
    lastFmDate: boolean | null;
    limit: number[];
    limitAmount: number[];
    limitCount: number[];
    limitDescription: number[];
    limitUsageDate: boolean | null;
    memberGroup: boolean | null;
    memberStatus: boolean | null;
    nonRegCcCheckHoldBaseAmt: boolean | null;
    nonRegCcCheckTotalAmt: boolean | null;
    nsfMonthlyCount: number[];
    nsfToday: boolean | null;
    number: boolean | null;
    openDate: boolean | null;
    payeeLine: number[];
    payeeNameLocator: boolean | null;
    payeeNameType: boolean | null;
    payeePhone: number[];
    paymentHistory: number[];
    perItemLimit: number[];
    prgdRecActivityDt: boolean | null;
    proxyDate: boolean | null;
    recordChangeDate: boolean | null;
    reference: boolean | null;
    relationshipCode: boolean | null;
    relationshipOverride: boolean | null;
    relationshipOverrideEffDate: boolean | null;
    relationshipOverrideExpDate: boolean | null;
    restrict: boolean | null;
    stateReporting: boolean | null;
    statementMailCode: boolean | null;
    type: boolean | null;
    userAmount1: boolean | null;
    userAmount2: boolean | null;
    userChar1: boolean | null;
    userChar2: boolean | null;
    userChar3: boolean | null;
    userChar4: boolean | null;
    userDate1: boolean | null;
    userDate2: boolean | null;
    warningCode: number[];
    warningExpiration: number[];
    wdTotalAmount: boolean | null;
    wrTotalAmount: boolean | null;
    version1: VersionType;
}