import { BatchAchOrigFilter } from "./batchAchOrigFilter";
import { CardFilter } from "./cardFilter";
import { CommentFilter } from "./commentFilter";
import { CpWorkCardFilter } from "./cpWorkCardFilter";
import { CredRepFilter } from "./credRepFilter";
import { EftFilter } from "./eftFilter";
import { ExternalAccountFilter } from "./externalAccountFilter";
import { ExternalLoanFilter } from "./externalLoanFilter";
import { FmHistoryFilter } from "./fmHistoryFilter";
import { HouseholdFilter } from "./householdFilter";
import { IrsFilter } from "./irsFilter";
import { LoanFilter } from "./loanFilter";
import { LoanAppFilter } from "./loanAppFilter";
import { LookupFilter } from "./lookupFilter";
import { NameFilter } from "./nameFilter";
import { NoteFilter } from "./noteFilter";
import { PledgeFilter } from "./pledgeFilter";
import { PortfolioFilter } from "./portfolioFilter";
import { PreferenceFilter } from "./preferenceFilter";
import { ShareFilter } from "./shareFilter";
import { SiteFilter } from "./siteFilter";
import { TrackingFilter } from "./trackingFilter";
import { VersionType } from "./versionType";

export interface AccountChildrenFilter {
    batchAchOrigFilter: BatchAchOrigFilter;
    cardFilter: CardFilter;
    commentFilter: CommentFilter;
    cpWorkCardFilter: CpWorkCardFilter;
    credRepFilter: CredRepFilter;
    eftFilter: EftFilter;
    externalAccountFilter: ExternalAccountFilter;
    externalLoanFilter: ExternalLoanFilter;
    fmHistoryFilter: FmHistoryFilter;
    householdFilter: HouseholdFilter;
    irsFilter: IrsFilter;
    loanFilter: LoanFilter;
    loanAppFilter: LoanAppFilter;
    lookupFilter: LookupFilter;
    nameFilter: NameFilter;
    noteFilter: NoteFilter;
    pledgeFilter: PledgeFilter;
    portfolioFilter: PortfolioFilter;
    preferenceFilter: PreferenceFilter;
    shareFilter: ShareFilter;
    siteFilter: SiteFilter;
    trackingFilter: TrackingFilter;
    version1: VersionType;
}