import { AccountAlternateAddress_2 } from "./accountAlternateAddress_2";
import { AccountAlternatePhone_2 } from "./accountAlternatePhone_2";
import { AccountCountLimit_2 } from "./accountCountLimit_2";
import { AccountLimit_2 } from "./accountLimit_2";
import { AccountLimitAmount_2 } from "./accountLimitAmount_2";
import { AccountLimitCount_2 } from "./accountLimitCount_2";
import { AccountLimitDescription_2 } from "./accountLimitDescription_2";
import { AccountNsfMonthlyCount_2 } from "./accountNsfMonthlyCount_2";
import { AccountPayeeLine_2 } from "./accountPayeeLine_2";
import { AccountPayeePhone_2 } from "./accountPayeePhone_2";
import { AccountPaymentHistory_2 } from "./accountPaymentHistory_2";
import { AccountPerItemLimit_2 } from "./accountPerItemLimit_2";
import { AccountWarningCode_2 } from "./accountWarningCode_2";
import { AccountWarningExpiration_2 } from "./accountWarningExpiration_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Account_2 {
    activityDateValue: string | null;
    activityDateValueSpecified: boolean;
    activityDate: string | null;
    alternateAddress: AccountAlternateAddress_2[];
    alternateAddressSpecified: boolean;
    alternateNameLocatorValue: number;
    alternateNameLocatorValueSpecified: boolean;
    alternateNameLocator: number | null;
    alternateNameTypeValue: number;
    alternateNameTypeValueSpecified: boolean;
    alternateNameType: number | null;
    alternatePhone: AccountAlternatePhone_2[];
    alternatePhoneSpecified: boolean;
    bondIntLastYearValue: number;
    bondIntLastYearValueSpecified: boolean;
    bondIntLastYear: number | null;
    bondIntYtdValue: number;
    bondIntYtdValueSpecified: boolean;
    bondIntYtd: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    cappedFeesAmountCapValue: number;
    cappedFeesAmountCapValueSpecified: boolean;
    cappedFeesAmountCap: number | null;
    cappedFeesAmtPeriodValue: number;
    cappedFeesAmtPeriodValueSpecified: boolean;
    cappedFeesAmtPeriod: number | null;
    cappedFeesCntPeriodValue: number;
    cappedFeesCntPeriodValueSpecified: boolean;
    cappedFeesCntPeriod: number | null;
    cappedFeesCountCapValue: number;
    cappedFeesCountCapValueSpecified: boolean;
    cappedFeesCountCap: number | null;
    cdTotalAmountValue: number;
    cdTotalAmountValueSpecified: boolean;
    cdTotalAmount: number | null;
    closeDateValue: string | null;
    closeDateValueSpecified: boolean;
    closeDate: string | null;
    commercialCodeValue: number;
    commercialCodeValueSpecified: boolean;
    commercialCode: number | null;
    correspondDateValue: string | null;
    correspondDateValueSpecified: boolean;
    correspondDate: string | null;
    countLimit: AccountCountLimit_2[];
    countLimitSpecified: boolean;
    crTotalAmountValue: number;
    crTotalAmountValueSpecified: boolean;
    crTotalAmount: number | null;
    createdAtBranchValue: number;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: number | null;
    createdByUserValue: number;
    createdByUserValueSpecified: boolean;
    createdByUser: number | null;
    currentRelationshipCodeValue: number;
    currentRelationshipCodeValueSpecified: boolean;
    currentRelationshipCode: number | null;
    divLastYearNonTaxValue: number;
    divLastYearNonTaxValueSpecified: boolean;
    divLastYearNonTax: number | null;
    divLastYearTaxValue: number;
    divLastYearTaxValueSpecified: boolean;
    divLastYearTax: number | null;
    divYtdNontaxValue: number;
    divYtdNontaxValueSpecified: boolean;
    divYtdNontax: number | null;
    divYtdTaxValue: number;
    divYtdTaxValueSpecified: boolean;
    divYtdTax: number | null;
    eStmtEnableValue: number;
    eStmtEnableValueSpecified: boolean;
    eStmtEnable: number | null;
    eStmtNotifyValue: number;
    eStmtNotifyValueSpecified: boolean;
    eStmtNotify: number | null;
    enableFloatValue: number;
    enableFloatValueSpecified: boolean;
    enableFloat: number | null;
    fmLastPurgeDateValue: string | null;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: string | null;
    frCdTotalAmountValue: number;
    frCdTotalAmountValueSpecified: boolean;
    frCdTotalAmount: number | null;
    frCdUnitsValue: number;
    frCdUnitsValueSpecified: boolean;
    frCdUnits: number | null;
    frCrTotalAmountValue: number;
    frCrTotalAmountValueSpecified: boolean;
    frCrTotalAmount: number | null;
    frCrUnitsValue: number;
    frCrUnitsValueSpecified: boolean;
    frCrUnits: number | null;
    frozenModeValue: number;
    frozenModeValueSpecified: boolean;
    frozenMode: number | null;
    headOfHouseholdValue: number;
    headOfHouseholdValueSpecified: boolean;
    headOfHousehold: number | null;
    householdAccount: string;
    householdStatementValue: number;
    householdStatementValueSpecified: boolean;
    householdStatement: number | null;
    interestLastYearValue: number;
    interestLastYearValueSpecified: boolean;
    interestLastYear: number | null;
    interestYtdValue: number;
    interestYtdValueSpecified: boolean;
    interestYtd: number | null;
    invalidAttemptCountValue: number;
    invalidAttemptCountValueSpecified: boolean;
    invalidAttemptCount: number | null;
    invalidAttemptDateValue: string | null;
    invalidAttemptDateValueSpecified: boolean;
    invalidAttemptDate: string | null;
    invalidAttemptTimeValue: number;
    invalidAttemptTimeValueSpecified: boolean;
    invalidAttemptTime: number | null;
    krHoldBaseAmountValue: number;
    krHoldBaseAmountValueSpecified: boolean;
    krHoldBaseAmount: number | null;
    krTotalAmountValue: number;
    krTotalAmountValueSpecified: boolean;
    krTotalAmount: number | null;
    krTotalDateValue: string | null;
    krTotalDateValueSpecified: boolean;
    krTotalDate: string | null;
    lastFmDateValue: string | null;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    limit: AccountLimit_2[];
    limitSpecified: boolean;
    limitAmount: AccountLimitAmount_2[];
    limitAmountSpecified: boolean;
    limitCount: AccountLimitCount_2[];
    limitCountSpecified: boolean;
    limitDescription: AccountLimitDescription_2[];
    limitDescriptionSpecified: boolean;
    limitUsageDateValue: string | null;
    limitUsageDateValueSpecified: boolean;
    limitUsageDate: string | null;
    memberGroupValue: number;
    memberGroupValueSpecified: boolean;
    memberGroup: number | null;
    memberStatusValue: number;
    memberStatusValueSpecified: boolean;
    memberStatus: number | null;
    nonRegCcCheckHoldBaseAmtValue: number;
    nonRegCcCheckHoldBaseAmtValueSpecified: boolean;
    nonRegCcCheckHoldBaseAmt: number | null;
    nonRegCcCheckTotalAmtValue: number;
    nonRegCcCheckTotalAmtValueSpecified: boolean;
    nonRegCcCheckTotalAmt: number | null;
    nsfMonthlyCount: AccountNsfMonthlyCount_2[];
    nsfMonthlyCountSpecified: boolean;
    nsfTodayValue: number;
    nsfTodayValueSpecified: boolean;
    nsfToday: number | null;
    number: string;
    openDateValue: string | null;
    openDateValueSpecified: boolean;
    openDate: string | null;
    payeeLine: AccountPayeeLine_2[];
    payeeLineSpecified: boolean;
    payeeNameLocatorValue: number;
    payeeNameLocatorValueSpecified: boolean;
    payeeNameLocator: number | null;
    payeeNameTypeValue: number;
    payeeNameTypeValueSpecified: boolean;
    payeeNameType: number | null;
    payeePhone: AccountPayeePhone_2[];
    payeePhoneSpecified: boolean;
    paymentHistory: AccountPaymentHistory_2[];
    paymentHistorySpecified: boolean;
    perItemLimit: AccountPerItemLimit_2[];
    perItemLimitSpecified: boolean;
    prgdRecActivityDtValue: string | null;
    prgdRecActivityDtValueSpecified: boolean;
    prgdRecActivityDt: string | null;
    proxyDateValue: string | null;
    proxyDateValueSpecified: boolean;
    proxyDate: string | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    reference: string;
    relationshipCodeValue: number;
    relationshipCodeValueSpecified: boolean;
    relationshipCode: number | null;
    relationshipOverrideValue: number;
    relationshipOverrideValueSpecified: boolean;
    relationshipOverride: number | null;
    relationshipOverrideEffDateValue: string | null;
    relationshipOverrideEffDateValueSpecified: boolean;
    relationshipOverrideEffDate: string | null;
    relationshipOverrideExpDateValue: string | null;
    relationshipOverrideExpDateValueSpecified: boolean;
    relationshipOverrideExpDate: string | null;
    restrictValue: number;
    restrictValueSpecified: boolean;
    restrict: number | null;
    stateReporting: string;
    statementMailCodeValue: number;
    statementMailCodeValueSpecified: boolean;
    statementMailCode: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userAmount1Value: number;
    userAmount1ValueSpecified: boolean;
    userAmount1: number | null;
    userAmount2Value: number;
    userAmount2ValueSpecified: boolean;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1Value: string | null;
    userDate1ValueSpecified: boolean;
    userDate1: string | null;
    userDate2Value: string | null;
    userDate2ValueSpecified: boolean;
    userDate2: string | null;
    warningCode: AccountWarningCode_2[];
    warningCodeSpecified: boolean;
    warningExpiration: AccountWarningExpiration_2[];
    warningExpirationSpecified: boolean;
    wdTotalAmountValue: number;
    wdTotalAmountValueSpecified: boolean;
    wdTotalAmount: number | null;
    wrTotalAmountValue: number;
    wrTotalAmountValueSpecified: boolean;
    wrTotalAmount: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}