import { AccountDefaultCountLimit_2 } from "./accountDefaultCountLimit_2";
import { AccountDefaultLimit_2 } from "./accountDefaultLimit_2";
import { AccountDefaultPerItemLimit_2 } from "./accountDefaultPerItemLimit_2";
import { AccountDefaultWarningCode_2 } from "./accountDefaultWarningCode_2";
import { VersionType } from "./versionType";

export interface AccountDefault_2 {
    acctType: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesCountCap: number | null;
    closeDate: string | null;
    commercialCode: number | null;
    countLimit: AccountDefaultCountLimit_2[];
    eStmtEnable: number | null;
    eStmtNotify: number | null;
    enableFloat: number | null;
    headOfHousehold: number | null;
    krHoldBaseAmount: number | null;
    limit: AccountDefaultLimit_2[];
    memberGroup: number | null;
    memberStatus: number | null;
    nonRegCcCheckHoldBaseAmt: number | null;
    perItemLimit: AccountDefaultPerItemLimit_2[];
    proxyDate: string | null;
    reference: string;
    relationshipCode: number | null;
    relationshipOverride: number | null;
    relationshipOverrideEffDate: string | null;
    relationshipOverrideExpDate: string | null;
    restrict: number | null;
    stateReporting: string;
    statementMailCode: number | null;
    type: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    warningCode: AccountDefaultWarningCode_2[];
    version1: VersionType;
}