import { AccountAlternateAddress } from "./accountAlternateAddress";
import { AccountAlternatePhone } from "./accountAlternatePhone";
import { BatchAchOrigList } from "./batchAchOrigList";
import { CardList } from "./cardList";
import { CommentList } from "./commentList";
import { AccountCountLimit } from "./accountCountLimit";
import { CpWorkCardList } from "./cpWorkCardList";
import { CredRepList } from "./credRepList";
import { EftList } from "./eftList";
import { ExternalAccountList } from "./externalAccountList";
import { ExternalLoanList } from "./externalLoanList";
import { FmHistoryList } from "./fmHistoryList";
import { HouseholdList } from "./householdList";
import { IrsList } from "./irsList";
import { AccountLimit } from "./accountLimit";
import { AccountLimitAmount } from "./accountLimitAmount";
import { AccountLimitCount } from "./accountLimitCount";
import { AccountLimitDescription } from "./accountLimitDescription";
import { LoanList } from "./loanList";
import { LoanAppList } from "./loanAppList";
import { LookupList } from "./lookupList";
import { NameList } from "./nameList";
import { NoteList } from "./noteList";
import { AccountNsfMonthlyCount } from "./accountNsfMonthlyCount";
import { AccountPayeeLine } from "./accountPayeeLine";
import { AccountPayeePhone } from "./accountPayeePhone";
import { AccountPaymentHistory } from "./accountPaymentHistory";
import { AccountPerItemLimit } from "./accountPerItemLimit";
import { PledgeList } from "./pledgeList";
import { PortfolioList } from "./portfolioList";
import { PreferenceList } from "./preferenceList";
import { ShareList } from "./shareList";
import { SiteList } from "./siteList";
import { TrackingList } from "./trackingList";
import { AccountWarningCode } from "./accountWarningCode";
import { AccountWarningExpiration } from "./accountWarningExpiration";
import { VersionType } from "./versionType";

export interface Account {
    activityDate: string | null;
    alternateAddress: AccountAlternateAddress[];
    alternateNameLocator: number | null;
    alternateNameType: number | null;
    alternatePhone: AccountAlternatePhone[];
    batchAchOrigList: BatchAchOrigList;
    bondIntLastYear: number | null;
    bondIntYtd: number | null;
    branch: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesAmtPeriod: number | null;
    cappedFeesCntPeriod: number | null;
    cappedFeesCountCap: number | null;
    cardList: CardList;
    cdTotalAmount: number | null;
    closeDate: string | null;
    commentList: CommentList;
    commercialCode: number | null;
    correspondDate: string | null;
    countLimit: AccountCountLimit[];
    cpWorkCardList: CpWorkCardList;
    crTotalAmount: number | null;
    createdAtBranch: number | null;
    createdByUser: number | null;
    credRepList: CredRepList;
    currentRelationshipCode: number | null;
    divLastYearNonTax: number | null;
    divLastYearTax: number | null;
    divYtdNontax: number | null;
    divYtdTax: number | null;
    eStmtEnable: number | null;
    eStmtNotify: number | null;
    eftList: EftList;
    enableFloat: number | null;
    externalAccountList: ExternalAccountList;
    externalLoanList: ExternalLoanList;
    fmHistoryList: FmHistoryList;
    fmLastPurgeDate: string | null;
    frCdTotalAmount: number | null;
    frCdUnits: number | null;
    frCrTotalAmount: number | null;
    frCrUnits: number | null;
    frozenMode: number | null;
    headOfHousehold: number | null;
    householdList: HouseholdList;
    householdAccount: string;
    householdStatement: number | null;
    interestLastYear: number | null;
    interestYtd: number | null;
    invalidAttemptCount: number | null;
    invalidAttemptDate: string | null;
    invalidAttemptTime: number | null;
    irsList: IrsList;
    krHoldBaseAmount: number | null;
    krTotalAmount: number | null;
    krTotalDate: string | null;
    lastFmDate: string | null;
    limit: AccountLimit[];
    limitAmount: AccountLimitAmount[];
    limitCount: AccountLimitCount[];
    limitDescription: AccountLimitDescription[];
    limitUsageDate: string | null;
    loanList: LoanList;
    loanAppList: LoanAppList;
    lookupList: LookupList;
    memberGroup: number | null;
    memberStatus: number | null;
    nameList: NameList;
    nonRegCcCheckHoldBaseAmt: number | null;
    nonRegCcCheckTotalAmt: number | null;
    noteList: NoteList;
    nsfMonthlyCount: AccountNsfMonthlyCount[];
    nsfToday: number | null;
    number: string;
    openDate: string | null;
    payeeLine: AccountPayeeLine[];
    payeeNameLocator: number | null;
    payeeNameType: number | null;
    payeePhone: AccountPayeePhone[];
    paymentHistory: AccountPaymentHistory[];
    perItemLimit: AccountPerItemLimit[];
    pledgeList: PledgeList;
    portfolioList: PortfolioList;
    preferenceList: PreferenceList;
    prgdRecActivityDt: string | null;
    proxyDate: string | null;
    recordChangeDate: string | null;
    reference: string;
    relationshipCode: number | null;
    relationshipOverride: number | null;
    relationshipOverrideEffDate: string | null;
    relationshipOverrideExpDate: string | null;
    restrict: number | null;
    shareList: ShareList;
    siteList: SiteList;
    stateReporting: string;
    statementMailCode: number | null;
    trackingList: TrackingList;
    type: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    warningCode: AccountWarningCode[];
    warningExpiration: AccountWarningExpiration[];
    wdTotalAmount: number | null;
    wrTotalAmount: number | null;
    version1: VersionType;
}