import { AcsServiceAction_2 } from "./acsServiceAction_2";
import { AcsServiceActionCreateRecord_2 } from "./acsServiceActionCreateRecord_2";
import { AcsServiceActionCreateText_2 } from "./acsServiceActionCreateText_2";
import { AcsServiceActionCreateType_2 } from "./acsServiceActionCreateType_2";
import { AcsServiceCompDataType_2 } from "./acsServiceCompDataType_2";
import { AcsServiceCompareNum_2 } from "./acsServiceCompareNum_2";
import { AcsServiceComparisonMethod_2 } from "./acsServiceComparisonMethod_2";
import { AcsServiceComparisonValue_2 } from "./acsServiceComparisonValue_2";
import { AcsServiceCriteria12_2 } from "./acsServiceCriteria12_2";
import { AcsServiceCriteriaOperator_2 } from "./acsServiceCriteriaOperator_2";
import { AcsServiceMenuOption_2 } from "./acsServiceMenuOption_2";
import { AcsServiceScript_2 } from "./acsServiceScript_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface AcsService_2 {
    acquireItems: string;
    acquireOptionValue: number;
    acquireOptionValueSpecified: boolean;
    acquireOption: number | null;
    acsServiceTypeValue: number;
    acsServiceTypeValueSpecified: boolean;
    acsServiceType: number | null;
    action: AcsServiceAction_2[];
    actionSpecified: boolean;
    actionCreateRecord: AcsServiceActionCreateRecord_2[];
    actionCreateRecordSpecified: boolean;
    actionCreateText: AcsServiceActionCreateText_2[];
    actionCreateTextSpecified: boolean;
    actionCreateType: AcsServiceActionCreateType_2[];
    actionCreateTypeSpecified: boolean;
    compDataType: AcsServiceCompDataType_2[];
    compDataTypeSpecified: boolean;
    compareNum: AcsServiceCompareNum_2[];
    compareNumSpecified: boolean;
    comparisonMethod: AcsServiceComparisonMethod_2[];
    comparisonMethodSpecified: boolean;
    comparisonValue: AcsServiceComparisonValue_2[];
    comparisonValueSpecified: boolean;
    consolidateMaxValue: number;
    consolidateMaxValueSpecified: boolean;
    consolidateMax: number | null;
    criteria12: AcsServiceCriteria12_2[];
    criteria12Specified: boolean;
    criteriaOperator: AcsServiceCriteriaOperator_2[];
    criteriaOperatorSpecified: boolean;
    description: string;
    excludeMatchValue: boolean;
    excludeMatchValueSpecified: boolean;
    excludeMatch: boolean | null;
    factsLetterfile: string;
    menuOption: AcsServiceMenuOption_2[];
    menuOptionSpecified: boolean;
    newLoanTypeValue: number;
    newLoanTypeValueSpecified: boolean;
    newLoanType: number | null;
    pointsValue: number;
    pointsValueSpecified: boolean;
    points: number | null;
    script: AcsServiceScript_2[];
    scriptSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}