import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface AcsServiceFields {
    acquireItemsValue: boolean;
    acquireItemsValueSpecified: boolean;
    acquireItems: boolean | null;
    acquireOptionValue: boolean;
    acquireOptionValueSpecified: boolean;
    acquireOption: boolean | null;
    acsServiceTypeValue: boolean;
    acsServiceTypeValueSpecified: boolean;
    acsServiceType: boolean | null;
    action: number[];
    actionSpecified: boolean;
    actionCreateRecord: number[];
    actionCreateRecordSpecified: boolean;
    actionCreateText: number[];
    actionCreateTextSpecified: boolean;
    actionCreateType: number[];
    actionCreateTypeSpecified: boolean;
    compDataType: number[];
    compDataTypeSpecified: boolean;
    compareNum: number[];
    compareNumSpecified: boolean;
    comparisonMethod: number[];
    comparisonMethodSpecified: boolean;
    comparisonValue: number[];
    comparisonValueSpecified: boolean;
    consolidateMaxValue: boolean;
    consolidateMaxValueSpecified: boolean;
    consolidateMax: boolean | null;
    criteria12: number[];
    criteria12Specified: boolean;
    criteriaOperator: number[];
    criteriaOperatorSpecified: boolean;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    excludeMatchValue: boolean;
    excludeMatchValueSpecified: boolean;
    excludeMatch: boolean | null;
    factsLetterfileValue: boolean;
    factsLetterfileValueSpecified: boolean;
    factsLetterfile: boolean | null;
    menuOption: number[];
    menuOptionSpecified: boolean;
    newLoanTypeValue: boolean;
    newLoanTypeValueSpecified: boolean;
    newLoanType: boolean | null;
    pointsValue: boolean;
    pointsValueSpecified: boolean;
    points: boolean | null;
    script: number[];
    scriptSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}