import { BitMap } from "./bitMap";
import { AtmRelAdvFee } from "./atmRelAdvFee";
import { AtmRelAltCourtesyPayFee1 } from "./atmRelAltCourtesyPayFee1";
import { AtmRelAltCourtesyPayFee2 } from "./atmRelAltCourtesyPayFee2";
import { AtmRelAltCourtesyPayFee3 } from "./atmRelAltCourtesyPayFee3";
import { AtmRelAltCourtesyPayFee4 } from "./atmRelAltCourtesyPayFee4";
import { AtmRelAltCourtesyPayFee5 } from "./atmRelAltCourtesyPayFee5";
import { AtmRelAltCourtesyPayFee6 } from "./atmRelAltCourtesyPayFee6";
import { AtmRelAltCourtesyPayTier1 } from "./atmRelAltCourtesyPayTier1";
import { AtmRelAltCourtesyPayTier2 } from "./atmRelAltCourtesyPayTier2";
import { AtmRelAltCourtesyPayTier3 } from "./atmRelAltCourtesyPayTier3";
import { AtmRelAltCourtesyPayTier4 } from "./atmRelAltCourtesyPayTier4";
import { AtmRelAltCourtesyPayTier5 } from "./atmRelAltCourtesyPayTier5";
import { AtmRelAltCourtesyPayTier6 } from "./atmRelAltCourtesyPayTier6";
import { AtmRelCodes } from "./atmRelCodes";
import { AtmRelCourtesyPayFee1 } from "./atmRelCourtesyPayFee1";
import { AtmRelCourtesyPayFee2 } from "./atmRelCourtesyPayFee2";
import { AtmRelCourtesyPayFee3 } from "./atmRelCourtesyPayFee3";
import { AtmRelCourtesyPayFee4 } from "./atmRelCourtesyPayFee4";
import { AtmRelCourtesyPayFee5 } from "./atmRelCourtesyPayFee5";
import { AtmRelCourtesyPayFee6 } from "./atmRelCourtesyPayFee6";
import { AtmRelCourtesyPayTier1 } from "./atmRelCourtesyPayTier1";
import { AtmRelCourtesyPayTier2 } from "./atmRelCourtesyPayTier2";
import { AtmRelCourtesyPayTier3 } from "./atmRelCourtesyPayTier3";
import { AtmRelCourtesyPayTier4 } from "./atmRelCourtesyPayTier4";
import { AtmRelCourtesyPayTier5 } from "./atmRelCourtesyPayTier5";
import { AtmRelCourtesyPayTier6 } from "./atmRelCourtesyPayTier6";
import { AtmRelDepFee } from "./atmRelDepFee";
import { AtmRelNsfFee } from "./atmRelNsfFee";
import { AtmRelOverdrawAddonXfrFee } from "./atmRelOverdrawAddonXfrFee";
import { AtmRelOverdrawComboXfrFee } from "./atmRelOverdrawComboXfrFee";
import { AtmRelOverdrawWdXfrFee } from "./atmRelOverdrawWdXfrFee";
import { AtmRelOvlFee } from "./atmRelOvlFee";
import { AtmRelPmtFee } from "./atmRelPmtFee";
import { AtmRelWdFee } from "./atmRelWdFee";
import { AtmRelXfrFee } from "./atmRelXfrFee";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Atm {
    acceptLoanThresholdPaymentValue: boolean;
    acceptLoanThresholdPaymentValueSpecified: boolean;
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmtValue: boolean;
    acceptUnappliedPartialPmtValueSpecified: boolean;
    acceptUnappliedPartialPmt: boolean | null;
    advFeeDescription: string;
    advFeeGlCodeValue: number;
    advFeeGlCodeValueSpecified: boolean;
    advFeeGlCode: number | null;
    atmAvailBalApprExclList: BitMap;
    atmAvailBalPostExclList: BitMap;
    atmFeeDescription: string;
    billPayFeeDescription: string;
    bpAvailBalApprExclList: BitMap;
    bpAvailBalPostExclList: BitMap;
    cardinHistoryCardTypes: BitMap;
    cardinHistoryDigitCountValue: number;
    cardinHistoryDigitCountValueSpecified: boolean;
    cardinHistoryDigitCount: number | null;
    chargePartialCapFeeValue: boolean;
    chargePartialCapFeeValueSpecified: boolean;
    chargePartialCapFee: boolean | null;
    clearingGlCodeValue: number;
    clearingGlCodeValueSpecified: boolean;
    clearingGlCode: number | null;
    courtesyNoticesValue: number;
    courtesyNoticesValueSpecified: boolean;
    courtesyNotices: number | null;
    courtesyPayCommentCodeValue: number;
    courtesyPayCommentCodeValueSpecified: boolean;
    courtesyPayCommentCode: number | null;
    courtesyPayFeeDescription: string;
    courtesyPayFeeGlCodeValue: number;
    courtesyPayFeeGlCodeValueSpecified: boolean;
    courtesyPayFeeGlCode: number | null;
    createExceptionItemsValue: boolean;
    createExceptionItemsValueSpecified: boolean;
    createExceptionItems: boolean | null;
    creditCardFeeDescription: string;
    debitCardFeeDescription: string;
    depFeeDescription: string;
    depFeeGlCodeValue: number;
    depFeeGlCodeValueSpecified: boolean;
    depFeeGlCode: number | null;
    dqGraceDaysForAddonValue: number;
    dqGraceDaysForAddonValueSpecified: boolean;
    dqGraceDaysForAddon: number | null;
    dqGraceDaysForWdValue: number;
    dqGraceDaysForWdValueSpecified: boolean;
    dqGraceDaysForWd: number | null;
    duplicateKeyPurgeTimeValue: number;
    duplicateKeyPurgeTimeValueSpecified: boolean;
    duplicateKeyPurgeTime: number | null;
    duplicateKeyRetentionDaysValue: number;
    duplicateKeyRetentionDaysValueSpecified: boolean;
    duplicateKeyRetentionDays: number | null;
    feeTypesToCap: BitMap;
    glCategoryValue: number;
    glCategoryValueSpecified: boolean;
    glCategory: number | null;
    graceAmountforCashPaymentsValue: number;
    graceAmountforCashPaymentsValueSpecified: boolean;
    graceAmountforCashPayments: number | null;
    holdDaysforCashPaymentsValue: number;
    holdDaysforCashPaymentsValueSpecified: boolean;
    holdDaysforCashPayments: number | null;
    maximumAddonOverLocValue: number;
    maximumAddonOverLocValueSpecified: boolean;
    maximumAddonOverLoc: number | null;
    maximumWdBelowAvailableValue: number;
    maximumWdBelowAvailableValueSpecified: boolean;
    maximumWdBelowAvailable: number | null;
    mccInHistoryCardTypes: BitMap;
    minimumLineofCreditAddonValue: number;
    minimumLineofCreditAddonValueSpecified: boolean;
    minimumLineofCreditAddon: number | null;
    noticesPrinterTypeValue: number;
    noticesPrinterTypeValueSpecified: boolean;
    noticesPrinterType: number | null;
    nsfFeeDescrIfNotPaid: string;
    nsfFeeDescriptionIfPaid: string;
    nsfFeeForUncollectedFundsValue: boolean;
    nsfFeeForUncollectedFundsValueSpecified: boolean;
    nsfFeeForUncollectedFunds: boolean | null;
    nsfFeeGlCodeValue: number;
    nsfFeeGlCodeValueSpecified: boolean;
    nsfFeeGlCode: number | null;
    nsfNoticesValue: boolean;
    nsfNoticesValueSpecified: boolean;
    nsfNotices: boolean | null;
    odtAuthFeeOvrSrcCodes: string;
    odtAuthFeeRecurSrcCodes: string;
    onlyLoanTransferNoticesValue: boolean;
    onlyLoanTransferNoticesValueSpecified: boolean;
    onlyLoanTransferNotices: boolean | null;
    overdrawAddonDqGraceDaysValue: number;
    overdrawAddonDqGraceDaysValueSpecified: boolean;
    overdrawAddonDqGraceDays: number | null;
    overdrawAddonIncrementValue: number;
    overdrawAddonIncrementValueSpecified: boolean;
    overdrawAddonIncrement: number | null;
    overdrawAddonMaxOverLocValue: number;
    overdrawAddonMaxOverLocValueSpecified: boolean;
    overdrawAddonMaxOverLoc: number | null;
    overdrawAddonPctOverLocValue: number;
    overdrawAddonPctOverLocValueSpecified: boolean;
    overdrawAddonPctOverLoc: number | null;
    overdrawFeeOptionValue: number;
    overdrawFeeOptionValueSpecified: boolean;
    overdrawFeeOption: number | null;
    overdrawIncrementOverrideValue: number;
    overdrawIncrementOverrideValueSpecified: boolean;
    overdrawIncrementOverride: number | null;
    overdrawNoticesfor2NdAcctValue: boolean;
    overdrawNoticesfor2NdAcctValueSpecified: boolean;
    overdrawNoticesfor2NdAcct: boolean | null;
    overdrawOptionValue: number;
    overdrawOptionValueSpecified: boolean;
    overdrawOption: number | null;
    overdrawRegDLimitingValue: boolean;
    overdrawRegDLimitingValueSpecified: boolean;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOptionValue: number;
    overdrawTierOptionValueSpecified: boolean;
    overdrawTierOption: number | null;
    overdrawTransferFeeGlCodeValue: number;
    overdrawTransferFeeGlCodeValueSpecified: boolean;
    overdrawTransferFeeGlCode: number | null;
    overdrawTransferNoticesValue: number;
    overdrawTransferNoticesValueSpecified: boolean;
    overdrawTransferNotices: number | null;
    overdrawWithdrawalIncrementValue: number;
    overdrawWithdrawalIncrementValueSpecified: boolean;
    overdrawWithdrawalIncrement: number | null;
    ovlFeeDescrIfNotPaid: string;
    ovlFeeDescriptionIfPaid: string;
    ovlFeeForUncollectedFundsValue: boolean;
    ovlFeeForUncollectedFundsValueSpecified: boolean;
    ovlFeeForUncollectedFunds: boolean | null;
    ovlFeeGlCodeValue: number;
    ovlFeeGlCodeValueSpecified: boolean;
    ovlFeeGlCode: number | null;
    ovlNoticesValue: boolean;
    ovlNoticesValueSpecified: boolean;
    ovlNotices: boolean | null;
    pmtFeeDescription: string;
    pmtFeeGlCodeValue: number;
    pmtFeeGlCodeValueSpecified: boolean;
    pmtFeeGlCode: number | null;
    posAvailBalAuthExclList: BitMap;
    posAvailBalPostExclList: BitMap;
    posFeeDescription: string;
    relAdvFee: AtmRelAdvFee[];
    relAdvFeeSpecified: boolean;
    relAltCourtesyPayFee1: AtmRelAltCourtesyPayFee1[];
    relAltCourtesyPayFee1Specified: boolean;
    relAltCourtesyPayFee2: AtmRelAltCourtesyPayFee2[];
    relAltCourtesyPayFee2Specified: boolean;
    relAltCourtesyPayFee3: AtmRelAltCourtesyPayFee3[];
    relAltCourtesyPayFee3Specified: boolean;
    relAltCourtesyPayFee4: AtmRelAltCourtesyPayFee4[];
    relAltCourtesyPayFee4Specified: boolean;
    relAltCourtesyPayFee5: AtmRelAltCourtesyPayFee5[];
    relAltCourtesyPayFee5Specified: boolean;
    relAltCourtesyPayFee6: AtmRelAltCourtesyPayFee6[];
    relAltCourtesyPayFee6Specified: boolean;
    relAltCourtesyPayTier1: AtmRelAltCourtesyPayTier1[];
    relAltCourtesyPayTier1Specified: boolean;
    relAltCourtesyPayTier2: AtmRelAltCourtesyPayTier2[];
    relAltCourtesyPayTier2Specified: boolean;
    relAltCourtesyPayTier3: AtmRelAltCourtesyPayTier3[];
    relAltCourtesyPayTier3Specified: boolean;
    relAltCourtesyPayTier4: AtmRelAltCourtesyPayTier4[];
    relAltCourtesyPayTier4Specified: boolean;
    relAltCourtesyPayTier5: AtmRelAltCourtesyPayTier5[];
    relAltCourtesyPayTier5Specified: boolean;
    relAltCourtesyPayTier6: AtmRelAltCourtesyPayTier6[];
    relAltCourtesyPayTier6Specified: boolean;
    relCodes: AtmRelCodes[];
    relCodesSpecified: boolean;
    relCourtesyPayFee1: AtmRelCourtesyPayFee1[];
    relCourtesyPayFee1Specified: boolean;
    relCourtesyPayFee2: AtmRelCourtesyPayFee2[];
    relCourtesyPayFee2Specified: boolean;
    relCourtesyPayFee3: AtmRelCourtesyPayFee3[];
    relCourtesyPayFee3Specified: boolean;
    relCourtesyPayFee4: AtmRelCourtesyPayFee4[];
    relCourtesyPayFee4Specified: boolean;
    relCourtesyPayFee5: AtmRelCourtesyPayFee5[];
    relCourtesyPayFee5Specified: boolean;
    relCourtesyPayFee6: AtmRelCourtesyPayFee6[];
    relCourtesyPayFee6Specified: boolean;
    relCourtesyPayTier1: AtmRelCourtesyPayTier1[];
    relCourtesyPayTier1Specified: boolean;
    relCourtesyPayTier2: AtmRelCourtesyPayTier2[];
    relCourtesyPayTier2Specified: boolean;
    relCourtesyPayTier3: AtmRelCourtesyPayTier3[];
    relCourtesyPayTier3Specified: boolean;
    relCourtesyPayTier4: AtmRelCourtesyPayTier4[];
    relCourtesyPayTier4Specified: boolean;
    relCourtesyPayTier5: AtmRelCourtesyPayTier5[];
    relCourtesyPayTier5Specified: boolean;
    relCourtesyPayTier6: AtmRelCourtesyPayTier6[];
    relCourtesyPayTier6Specified: boolean;
    relDepFee: AtmRelDepFee[];
    relDepFeeSpecified: boolean;
    relNsfFee: AtmRelNsfFee[];
    relNsfFeeSpecified: boolean;
    relOverdrawAddonXfrFee: AtmRelOverdrawAddonXfrFee[];
    relOverdrawAddonXfrFeeSpecified: boolean;
    relOverdrawComboXfrFee: AtmRelOverdrawComboXfrFee[];
    relOverdrawComboXfrFeeSpecified: boolean;
    relOverdrawWdXfrFee: AtmRelOverdrawWdXfrFee[];
    relOverdrawWdXfrFeeSpecified: boolean;
    relOvlFee: AtmRelOvlFee[];
    relOvlFeeSpecified: boolean;
    relPmtFee: AtmRelPmtFee[];
    relPmtFeeSpecified: boolean;
    relWdFee: AtmRelWdFee[];
    relWdFeeSpecified: boolean;
    relXfrFee: AtmRelXfrFee[];
    relXfrFeeSpecified: boolean;
    reportTitle: string;
    sbAvailBalApprExclList: BitMap;
    sbAvailBalPostExclList: BitMap;
    sharedBranchFeeDescription: string;
    sigAvailBalAuthExclList: BitMap;
    sigAvailBalPostExclList: BitMap;
    wdBelowAvailableOptionValue: number;
    wdBelowAvailableOptionValueSpecified: boolean;
    wdBelowAvailableOption: number | null;
    wdFeeDescription: string;
    wdFeeGlCodeValue: number;
    wdFeeGlCodeValueSpecified: boolean;
    wdFeeGlCode: number | null;
    xfrFeeDescription: string;
    xfrFeeGlCodeValue: number;
    xfrFeeGlCodeValueSpecified: boolean;
    xfrFeeGlCode: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}