import { VersionType } from "./versionType";

export interface AtmFields {
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmt: boolean | null;
    advFeeDescription: boolean | null;
    advFeeGlCode: boolean | null;
    atmAvailBalApprExclList: boolean | null;
    atmAvailBalPostExclList: boolean | null;
    atmFeeDescription: boolean | null;
    billPayFeeDescription: boolean | null;
    bpAvailBalApprExclList: boolean | null;
    bpAvailBalPostExclList: boolean | null;
    cardinHistoryCardTypes: boolean | null;
    cardinHistoryDigitCount: boolean | null;
    chargePartialCapFee: boolean | null;
    clearingGlCode: boolean | null;
    courtesyNotices: boolean | null;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCode: boolean | null;
    createExceptionItems: boolean | null;
    creditCardFeeDescription: boolean | null;
    debitCardFeeDescription: boolean | null;
    depFeeDescription: boolean | null;
    depFeeGlCode: boolean | null;
    dqGraceDaysForAddon: boolean | null;
    dqGraceDaysForWd: boolean | null;
    duplicateKeyPurgeTime: boolean | null;
    duplicateKeyRetentionDays: boolean | null;
    feeTypesToCap: boolean | null;
    glCategory: boolean | null;
    graceAmountforCashPayments: boolean | null;
    holdDaysforCashPayments: boolean | null;
    maximumAddonOverLoc: boolean | null;
    maximumWdBelowAvailable: boolean | null;
    mccInHistoryCardTypes: boolean | null;
    minimumLineofCreditAddon: boolean | null;
    noticesPrinterType: boolean | null;
    nsfFeeDescrIfNotPaid: boolean | null;
    nsfFeeDescriptionIfPaid: boolean | null;
    nsfFeeForUncollectedFunds: boolean | null;
    nsfFeeGlCode: boolean | null;
    nsfNotices: boolean | null;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodes: boolean | null;
    onlyLoanTransferNotices: boolean | null;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverride: boolean | null;
    overdrawNoticesfor2NdAcct: boolean | null;
    overdrawOption: boolean | null;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOption: boolean | null;
    overdrawTransferFeeGlCode: boolean | null;
    overdrawTransferNotices: boolean | null;
    overdrawWithdrawalIncrement: boolean | null;
    ovlFeeDescrIfNotPaid: boolean | null;
    ovlFeeDescriptionIfPaid: boolean | null;
    ovlFeeForUncollectedFunds: boolean | null;
    ovlFeeGlCode: boolean | null;
    ovlNotices: boolean | null;
    pmtFeeDescription: boolean | null;
    pmtFeeGlCode: boolean | null;
    posAvailBalAuthExclList: boolean | null;
    posAvailBalPostExclList: boolean | null;
    posFeeDescription: boolean | null;
    relAdvFee: number[];
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier6: number[];
    relCodes: number[];
    relCourtesyPayFee1: number[];
    relCourtesyPayFee2: number[];
    relCourtesyPayFee3: number[];
    relCourtesyPayFee4: number[];
    relCourtesyPayFee5: number[];
    relCourtesyPayFee6: number[];
    relCourtesyPayTier1: number[];
    relCourtesyPayTier2: number[];
    relCourtesyPayTier3: number[];
    relCourtesyPayTier4: number[];
    relCourtesyPayTier5: number[];
    relCourtesyPayTier6: number[];
    relDepFee: number[];
    relNsfFee: number[];
    relOverdrawAddonXfrFee: number[];
    relOverdrawComboXfrFee: number[];
    relOverdrawWdXfrFee: number[];
    relOvlFee: number[];
    relPmtFee: number[];
    relWdFee: number[];
    relXfrFee: number[];
    reportTitle: boolean | null;
    sbAvailBalApprExclList: boolean | null;
    sbAvailBalPostExclList: boolean | null;
    sharedBranchFeeDescription: boolean | null;
    sigAvailBalAuthExclList: boolean | null;
    sigAvailBalPostExclList: boolean | null;
    wdBelowAvailableOption: boolean | null;
    wdFeeDescription: boolean | null;
    wdFeeGlCode: boolean | null;
    xfrFeeDescription: boolean | null;
    xfrFeeGlCode: boolean | null;
    version1: VersionType;
}