import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface AtmFields {
    acceptLoanThresholdPaymentValue: boolean;
    acceptLoanThresholdPaymentValueSpecified: boolean;
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmtValue: boolean;
    acceptUnappliedPartialPmtValueSpecified: boolean;
    acceptUnappliedPartialPmt: boolean | null;
    advFeeDescriptionValue: boolean;
    advFeeDescriptionValueSpecified: boolean;
    advFeeDescription: boolean | null;
    advFeeGlCodeValue: boolean;
    advFeeGlCodeValueSpecified: boolean;
    advFeeGlCode: boolean | null;
    atmAvailBalApprExclListValue: boolean;
    atmAvailBalApprExclListValueSpecified: boolean;
    atmAvailBalApprExclList: boolean | null;
    atmAvailBalPostExclListValue: boolean;
    atmAvailBalPostExclListValueSpecified: boolean;
    atmAvailBalPostExclList: boolean | null;
    atmFeeDescriptionValue: boolean;
    atmFeeDescriptionValueSpecified: boolean;
    atmFeeDescription: boolean | null;
    billPayFeeDescriptionValue: boolean;
    billPayFeeDescriptionValueSpecified: boolean;
    billPayFeeDescription: boolean | null;
    bpAvailBalApprExclListValue: boolean;
    bpAvailBalApprExclListValueSpecified: boolean;
    bpAvailBalApprExclList: boolean | null;
    bpAvailBalPostExclListValue: boolean;
    bpAvailBalPostExclListValueSpecified: boolean;
    bpAvailBalPostExclList: boolean | null;
    cardinHistoryCardTypesValue: boolean;
    cardinHistoryCardTypesValueSpecified: boolean;
    cardinHistoryCardTypes: boolean | null;
    cardinHistoryDigitCountValue: boolean;
    cardinHistoryDigitCountValueSpecified: boolean;
    cardinHistoryDigitCount: boolean | null;
    chargePartialCapFeeValue: boolean;
    chargePartialCapFeeValueSpecified: boolean;
    chargePartialCapFee: boolean | null;
    clearingGlCodeValue: boolean;
    clearingGlCodeValueSpecified: boolean;
    clearingGlCode: boolean | null;
    courtesyNoticesValue: boolean;
    courtesyNoticesValueSpecified: boolean;
    courtesyNotices: boolean | null;
    courtesyPayCommentCodeValue: boolean;
    courtesyPayCommentCodeValueSpecified: boolean;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescriptionValue: boolean;
    courtesyPayFeeDescriptionValueSpecified: boolean;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCodeValue: boolean;
    courtesyPayFeeGlCodeValueSpecified: boolean;
    courtesyPayFeeGlCode: boolean | null;
    createExceptionItemsValue: boolean;
    createExceptionItemsValueSpecified: boolean;
    createExceptionItems: boolean | null;
    creditCardFeeDescriptionValue: boolean;
    creditCardFeeDescriptionValueSpecified: boolean;
    creditCardFeeDescription: boolean | null;
    debitCardFeeDescriptionValue: boolean;
    debitCardFeeDescriptionValueSpecified: boolean;
    debitCardFeeDescription: boolean | null;
    depFeeDescriptionValue: boolean;
    depFeeDescriptionValueSpecified: boolean;
    depFeeDescription: boolean | null;
    depFeeGlCodeValue: boolean;
    depFeeGlCodeValueSpecified: boolean;
    depFeeGlCode: boolean | null;
    dqGraceDaysForAddonValue: boolean;
    dqGraceDaysForAddonValueSpecified: boolean;
    dqGraceDaysForAddon: boolean | null;
    dqGraceDaysForWdValue: boolean;
    dqGraceDaysForWdValueSpecified: boolean;
    dqGraceDaysForWd: boolean | null;
    duplicateKeyPurgeTimeValue: boolean;
    duplicateKeyPurgeTimeValueSpecified: boolean;
    duplicateKeyPurgeTime: boolean | null;
    duplicateKeyRetentionDaysValue: boolean;
    duplicateKeyRetentionDaysValueSpecified: boolean;
    duplicateKeyRetentionDays: boolean | null;
    feeTypesToCapValue: boolean;
    feeTypesToCapValueSpecified: boolean;
    feeTypesToCap: boolean | null;
    glCategoryValue: boolean;
    glCategoryValueSpecified: boolean;
    glCategory: boolean | null;
    graceAmountforCashPaymentsValue: boolean;
    graceAmountforCashPaymentsValueSpecified: boolean;
    graceAmountforCashPayments: boolean | null;
    holdDaysforCashPaymentsValue: boolean;
    holdDaysforCashPaymentsValueSpecified: boolean;
    holdDaysforCashPayments: boolean | null;
    maximumAddonOverLocValue: boolean;
    maximumAddonOverLocValueSpecified: boolean;
    maximumAddonOverLoc: boolean | null;
    maximumWdBelowAvailableValue: boolean;
    maximumWdBelowAvailableValueSpecified: boolean;
    maximumWdBelowAvailable: boolean | null;
    mccInHistoryCardTypesValue: boolean;
    mccInHistoryCardTypesValueSpecified: boolean;
    mccInHistoryCardTypes: boolean | null;
    minimumLineofCreditAddonValue: boolean;
    minimumLineofCreditAddonValueSpecified: boolean;
    minimumLineofCreditAddon: boolean | null;
    noticesPrinterTypeValue: boolean;
    noticesPrinterTypeValueSpecified: boolean;
    noticesPrinterType: boolean | null;
    nsfFeeDescrIfNotPaidValue: boolean;
    nsfFeeDescrIfNotPaidValueSpecified: boolean;
    nsfFeeDescrIfNotPaid: boolean | null;
    nsfFeeDescriptionIfPaidValue: boolean;
    nsfFeeDescriptionIfPaidValueSpecified: boolean;
    nsfFeeDescriptionIfPaid: boolean | null;
    nsfFeeForUncollectedFundsValue: boolean;
    nsfFeeForUncollectedFundsValueSpecified: boolean;
    nsfFeeForUncollectedFunds: boolean | null;
    nsfFeeGlCodeValue: boolean;
    nsfFeeGlCodeValueSpecified: boolean;
    nsfFeeGlCode: boolean | null;
    nsfNoticesValue: boolean;
    nsfNoticesValueSpecified: boolean;
    nsfNotices: boolean | null;
    odtAuthFeeOvrSrcCodesValue: boolean;
    odtAuthFeeOvrSrcCodesValueSpecified: boolean;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodesValue: boolean;
    odtAuthFeeRecurSrcCodesValueSpecified: boolean;
    odtAuthFeeRecurSrcCodes: boolean | null;
    onlyLoanTransferNoticesValue: boolean;
    onlyLoanTransferNoticesValueSpecified: boolean;
    onlyLoanTransferNotices: boolean | null;
    overdrawAddonDqGraceDaysValue: boolean;
    overdrawAddonDqGraceDaysValueSpecified: boolean;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrementValue: boolean;
    overdrawAddonIncrementValueSpecified: boolean;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLocValue: boolean;
    overdrawAddonMaxOverLocValueSpecified: boolean;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLocValue: boolean;
    overdrawAddonPctOverLocValueSpecified: boolean;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOptionValue: boolean;
    overdrawFeeOptionValueSpecified: boolean;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverrideValue: boolean;
    overdrawIncrementOverrideValueSpecified: boolean;
    overdrawIncrementOverride: boolean | null;
    overdrawNoticesfor2NdAcctValue: boolean;
    overdrawNoticesfor2NdAcctValueSpecified: boolean;
    overdrawNoticesfor2NdAcct: boolean | null;
    overdrawOptionValue: boolean;
    overdrawOptionValueSpecified: boolean;
    overdrawOption: boolean | null;
    overdrawRegDLimitingValue: boolean;
    overdrawRegDLimitingValueSpecified: boolean;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOptionValue: boolean;
    overdrawTierOptionValueSpecified: boolean;
    overdrawTierOption: boolean | null;
    overdrawTransferFeeGlCodeValue: boolean;
    overdrawTransferFeeGlCodeValueSpecified: boolean;
    overdrawTransferFeeGlCode: boolean | null;
    overdrawTransferNoticesValue: boolean;
    overdrawTransferNoticesValueSpecified: boolean;
    overdrawTransferNotices: boolean | null;
    overdrawWithdrawalIncrementValue: boolean;
    overdrawWithdrawalIncrementValueSpecified: boolean;
    overdrawWithdrawalIncrement: boolean | null;
    ovlFeeDescrIfNotPaidValue: boolean;
    ovlFeeDescrIfNotPaidValueSpecified: boolean;
    ovlFeeDescrIfNotPaid: boolean | null;
    ovlFeeDescriptionIfPaidValue: boolean;
    ovlFeeDescriptionIfPaidValueSpecified: boolean;
    ovlFeeDescriptionIfPaid: boolean | null;
    ovlFeeForUncollectedFundsValue: boolean;
    ovlFeeForUncollectedFundsValueSpecified: boolean;
    ovlFeeForUncollectedFunds: boolean | null;
    ovlFeeGlCodeValue: boolean;
    ovlFeeGlCodeValueSpecified: boolean;
    ovlFeeGlCode: boolean | null;
    ovlNoticesValue: boolean;
    ovlNoticesValueSpecified: boolean;
    ovlNotices: boolean | null;
    pmtFeeDescriptionValue: boolean;
    pmtFeeDescriptionValueSpecified: boolean;
    pmtFeeDescription: boolean | null;
    pmtFeeGlCodeValue: boolean;
    pmtFeeGlCodeValueSpecified: boolean;
    pmtFeeGlCode: boolean | null;
    posAvailBalAuthExclListValue: boolean;
    posAvailBalAuthExclListValueSpecified: boolean;
    posAvailBalAuthExclList: boolean | null;
    posAvailBalPostExclListValue: boolean;
    posAvailBalPostExclListValueSpecified: boolean;
    posAvailBalPostExclList: boolean | null;
    posFeeDescriptionValue: boolean;
    posFeeDescriptionValueSpecified: boolean;
    posFeeDescription: boolean | null;
    relAdvFee: number[];
    relAdvFeeSpecified: boolean;
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee1Specified: boolean;
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee2Specified: boolean;
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee3Specified: boolean;
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee4Specified: boolean;
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee5Specified: boolean;
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayFee6Specified: boolean;
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier1Specified: boolean;
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier2Specified: boolean;
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier3Specified: boolean;
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier4Specified: boolean;
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier5Specified: boolean;
    relAltCourtesyPayTier6: number[];
    relAltCourtesyPayTier6Specified: boolean;
    relCodes: number[];
    relCodesSpecified: boolean;
    relCourtesyPayFee1: number[];
    relCourtesyPayFee1Specified: boolean;
    relCourtesyPayFee2: number[];
    relCourtesyPayFee2Specified: boolean;
    relCourtesyPayFee3: number[];
    relCourtesyPayFee3Specified: boolean;
    relCourtesyPayFee4: number[];
    relCourtesyPayFee4Specified: boolean;
    relCourtesyPayFee5: number[];
    relCourtesyPayFee5Specified: boolean;
    relCourtesyPayFee6: number[];
    relCourtesyPayFee6Specified: boolean;
    relCourtesyPayTier1: number[];
    relCourtesyPayTier1Specified: boolean;
    relCourtesyPayTier2: number[];
    relCourtesyPayTier2Specified: boolean;
    relCourtesyPayTier3: number[];
    relCourtesyPayTier3Specified: boolean;
    relCourtesyPayTier4: number[];
    relCourtesyPayTier4Specified: boolean;
    relCourtesyPayTier5: number[];
    relCourtesyPayTier5Specified: boolean;
    relCourtesyPayTier6: number[];
    relCourtesyPayTier6Specified: boolean;
    relDepFee: number[];
    relDepFeeSpecified: boolean;
    relNsfFee: number[];
    relNsfFeeSpecified: boolean;
    relOverdrawAddonXfrFee: number[];
    relOverdrawAddonXfrFeeSpecified: boolean;
    relOverdrawComboXfrFee: number[];
    relOverdrawComboXfrFeeSpecified: boolean;
    relOverdrawWdXfrFee: number[];
    relOverdrawWdXfrFeeSpecified: boolean;
    relOvlFee: number[];
    relOvlFeeSpecified: boolean;
    relPmtFee: number[];
    relPmtFeeSpecified: boolean;
    relWdFee: number[];
    relWdFeeSpecified: boolean;
    relXfrFee: number[];
    relXfrFeeSpecified: boolean;
    reportTitleValue: boolean;
    reportTitleValueSpecified: boolean;
    reportTitle: boolean | null;
    sbAvailBalApprExclListValue: boolean;
    sbAvailBalApprExclListValueSpecified: boolean;
    sbAvailBalApprExclList: boolean | null;
    sbAvailBalPostExclListValue: boolean;
    sbAvailBalPostExclListValueSpecified: boolean;
    sbAvailBalPostExclList: boolean | null;
    sharedBranchFeeDescriptionValue: boolean;
    sharedBranchFeeDescriptionValueSpecified: boolean;
    sharedBranchFeeDescription: boolean | null;
    sigAvailBalAuthExclListValue: boolean;
    sigAvailBalAuthExclListValueSpecified: boolean;
    sigAvailBalAuthExclList: boolean | null;
    sigAvailBalPostExclListValue: boolean;
    sigAvailBalPostExclListValueSpecified: boolean;
    sigAvailBalPostExclList: boolean | null;
    wdBelowAvailableOptionValue: boolean;
    wdBelowAvailableOptionValueSpecified: boolean;
    wdBelowAvailableOption: boolean | null;
    wdFeeDescriptionValue: boolean;
    wdFeeDescriptionValueSpecified: boolean;
    wdFeeDescription: boolean | null;
    wdFeeGlCodeValue: boolean;
    wdFeeGlCodeValueSpecified: boolean;
    wdFeeGlCode: boolean | null;
    xfrFeeDescriptionValue: boolean;
    xfrFeeDescriptionValueSpecified: boolean;
    xfrFeeDescription: boolean | null;
    xfrFeeGlCodeValue: boolean;
    xfrFeeGlCodeValueSpecified: boolean;
    xfrFeeGlCode: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}