import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface BalancePrinterType {
    printerIdValue: number;
    printerIdValueSpecified: boolean;
    printerId: number | null;
    tranGlCodeValue: number;
    tranGlCodeValueSpecified: boolean;
    tranGlCode: number | null;
    checkAcctNumber: string;
    beginCountValue: number;
    beginCountValueSpecified: boolean;
    beginCount: number | null;
    dispenseCountValue: number;
    dispenseCountValueSpecified: boolean;
    dispenseCount: number | null;
    dispenseAmountValue: number;
    dispenseAmountValueSpecified: boolean;
    dispenseAmount: number | null;
    reverseCountValue: number;
    reverseCountValueSpecified: boolean;
    reverseCount: number | null;
    reverseAmountValue: number;
    reverseAmountValueSpecified: boolean;
    reverseAmount: number | null;
    adjustCountValue: number;
    adjustCountValueSpecified: boolean;
    adjustCount: number | null;
    replenishCountValue: number;
    replenishCountValueSpecified: boolean;
    replenishCount: number | null;
    currentCountValue: number;
    currentCountValueSpecified: boolean;
    currentCount: number | null;
    revTotalCountValue: number;
    revTotalCountValueSpecified: boolean;
    revTotalCount: number | null;
    warnCountValue: number;
    warnCountValueSpecified: boolean;
    warnCount: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}