import { DonorIdType } from "./donorIdType";
import { CheckIssuerType } from "./checkIssuerType";
import { GlAccounts } from "./glAccounts";
import { GlCodes } from "./glCodes";
import { AuthorizationType } from "./authorizationType";
import { TransactionsBaseRequest } from "./transactionsBaseRequest";

export interface BillPaymentRequest extends TransactionsBaseRequest {
    accountNumber: string;
    id: string;
    idTypeValue: DonorIdType;
    idTypeValueSpecified: boolean;
    idType: DonorIdType | null;
    paymentAmountValue: number;
    paymentAmountValueSpecified: boolean;
    paymentAmount: number | null;
    checkIssuerValue: CheckIssuerType;
    checkIssuerValueSpecified: boolean;
    checkIssuer: CheckIssuerType | null;
    comment: string;
    glAccounts: GlAccounts;
    glCodes: GlCodes;
    authorizationTypeValue: AuthorizationType;
    authorizationTypeValueSpecified: boolean;
    authorizationType: AuthorizationType | null;
    forcePostRequestedValue: boolean;
    forcePostRequestedValueSpecified: boolean;
    forcePostRequested: boolean | null;
    sourceCode: string;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    commentCodeValue: number;
    commentCodeValueSpecified: boolean;
    commentCode: number | null;
    regulationDLimitedValue: boolean | null;
    regulationDLimitedValueSpecified: boolean;
    regulationDLimited: boolean | null;
    recurrenceRequestedValue: boolean;
    recurrenceRequestedValueSpecified: boolean;
    recurrenceRequested: boolean | null;
    glComment: string;
}