import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CardDefaultFields {
    atmCountLimitValue: boolean;
    atmCountLimitValueSpecified: boolean;
    atmCountLimit: boolean | null;
    authCountLimitValue: boolean;
    authCountLimitValueSpecified: boolean;
    authCountLimit: boolean | null;
    authLimitValue: boolean;
    authLimitValueSpecified: boolean;
    authLimit: boolean | null;
    billPayCountLimitValue: boolean;
    billPayCountLimitValueSpecified: boolean;
    billPayCountLimit: boolean | null;
    billPayLimitValue: boolean;
    billPayLimitValueSpecified: boolean;
    billPayLimit: boolean | null;
    billPayMaxValue: boolean;
    billPayMaxValueSpecified: boolean;
    billPayMax: boolean | null;
    blockCodeValue: boolean;
    blockCodeValueSpecified: boolean;
    blockCode: boolean | null;
    cardTypeValue: boolean;
    cardTypeValueSpecified: boolean;
    cardType: boolean | null;
    chkIdValue: boolean;
    chkIdValueSpecified: boolean;
    chkId: boolean | null;
    countLimit: number[];
    countLimitSpecified: boolean;
    credDebCountLimitValue: boolean;
    credDebCountLimitValueSpecified: boolean;
    credDebCountLimit: boolean | null;
    credDebLimitValue: boolean;
    credDebLimitValueSpecified: boolean;
    credDebLimit: boolean | null;
    creditCardIdValue: boolean;
    creditCardIdValueSpecified: boolean;
    creditCardId: boolean | null;
    depCountLimitValue: boolean;
    depCountLimitValueSpecified: boolean;
    depCountLimit: boolean | null;
    depLimitValue: boolean;
    depLimitValueSpecified: boolean;
    depLimit: boolean | null;
    depMaxValue: boolean;
    depMaxValueSpecified: boolean;
    depMax: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    digitalIssueExceptValue: boolean;
    digitalIssueExceptValueSpecified: boolean;
    digitalIssueExcept: boolean | null;
    digitalIssueStatusValue: boolean;
    digitalIssueStatusValueSpecified: boolean;
    digitalIssueStatus: boolean | null;
    effectiveDateValue: boolean;
    effectiveDateValueSpecified: boolean;
    effectiveDate: boolean | null;
    emvChipProfileValue: boolean;
    emvChipProfileValueSpecified: boolean;
    emvChipProfile: boolean | null;
    expirationDateValue: boolean;
    expirationDateValueSpecified: boolean;
    expirationDate: boolean | null;
    instantIssueValue: boolean;
    instantIssueValueSpecified: boolean;
    instantIssue: boolean | null;
    issueCodeValue: boolean;
    issueCodeValueSpecified: boolean;
    issueCode: boolean | null;
    issueDateValue: boolean;
    issueDateValueSpecified: boolean;
    issueDate: boolean | null;
    limit: number[];
    limitSpecified: boolean;
    limitAmountValue: boolean;
    limitAmountValueSpecified: boolean;
    limitAmount: boolean | null;
    limitDaysValue: boolean;
    limitDaysValueSpecified: boolean;
    limitDays: boolean | null;
    locIdValue: boolean;
    locIdValueSpecified: boolean;
    locId: boolean | null;
    miscCountLimitValue: boolean;
    miscCountLimitValueSpecified: boolean;
    miscCountLimit: boolean | null;
    miscId: number[];
    miscIdSpecified: boolean;
    miscLimitValue: boolean;
    miscLimitValueSpecified: boolean;
    miscLimit: boolean | null;
    nameTypeValue: boolean;
    nameTypeValueSpecified: boolean;
    nameType: boolean | null;
    onlineCardIssueValue: boolean;
    onlineCardIssueValueSpecified: boolean;
    onlineCardIssue: boolean | null;
    onlineRushIssueValue: boolean;
    onlineRushIssueValueSpecified: boolean;
    onlineRushIssue: boolean | null;
    perItemLimit: number[];
    perItemLimitSpecified: boolean;
    pinActualValue: boolean;
    pinActualValueSpecified: boolean;
    pinActual: boolean | null;
    pinEncryptedValue: boolean;
    pinEncryptedValueSpecified: boolean;
    pinEncrypted: boolean | null;
    pinOffsetValue: boolean;
    pinOffsetValueSpecified: boolean;
    pinOffset: boolean | null;
    posCountLimitValue: boolean;
    posCountLimitValueSpecified: boolean;
    posCountLimit: boolean | null;
    posLimitValue: boolean;
    posLimitValueSpecified: boolean;
    posLimit: boolean | null;
    reclassCodeValue: boolean;
    reclassCodeValueSpecified: boolean;
    reclassCode: boolean | null;
    reissueCodeValue: boolean;
    reissueCodeValueSpecified: boolean;
    reissueCode: boolean | null;
    reissueMonthsValue: boolean;
    reissueMonthsValueSpecified: boolean;
    reissueMonths: boolean | null;
    savIdValue: boolean;
    savIdValueSpecified: boolean;
    savId: boolean | null;
    service: number[];
    serviceSpecified: boolean;
    singleUsageMaxValue: boolean;
    singleUsageMaxValueSpecified: boolean;
    singleUsageMax: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    suffixValue: boolean;
    suffixValueSpecified: boolean;
    suffix: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    usageLimitValue: boolean;
    usageLimitValueSpecified: boolean;
    usageLimit: boolean | null;
    warningCode: number[];
    warningCodeSpecified: boolean;
    wdCheckCountLimitValue: boolean;
    wdCheckCountLimitValueSpecified: boolean;
    wdCheckCountLimit: boolean | null;
    wdCheckLimitValue: boolean;
    wdCheckLimitValueSpecified: boolean;
    wdCheckLimit: boolean | null;
    wdCheckMaxValue: boolean;
    wdCheckMaxValueSpecified: boolean;
    wdCheckMax: boolean | null;
    xferCountLimitValue: boolean;
    xferCountLimitValueSpecified: boolean;
    xferCountLimit: boolean | null;
    xferLimitValue: boolean;
    xferLimitValueSpecified: boolean;
    xferLimit: boolean | null;
    xferMaxValue: boolean;
    xferMaxValueSpecified: boolean;
    xferMax: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}