import { CardCountLimit_2 } from "./cardCountLimit_2";
import { CardFeeCount_2 } from "./cardFeeCount_2";
import { CardLimit_2 } from "./cardLimit_2";
import { CardLimitCount_2 } from "./cardLimitCount_2";
import { CardLimitDescription_2 } from "./cardLimitDescription_2";
import { CardLimitUsageAmount_2 } from "./cardLimitUsageAmount_2";
import { CardMiscId_2 } from "./cardMiscId_2";
import { CardPerItemLimit_2 } from "./cardPerItemLimit_2";
import { CardService_2 } from "./cardService_2";
import { CardWarningCode_2 } from "./cardWarningCode_2";
import { CardWarningExpiration_2 } from "./cardWarningExpiration_2";
import { VersionType } from "./versionType";

export interface Card_2 {
    activeDate: string | null;
    atmCount: number | null;
    atmCountLimit: number | null;
    atmTempLimit: number | null;
    authAmount: number | null;
    authCount: number | null;
    authCountLimit: number | null;
    authLimit: number | null;
    authTempLimit: number | null;
    billPayAmount: number | null;
    billPayCount: number | null;
    billPayCountLimit: number | null;
    billPayLimit: number | null;
    billPayMax: number | null;
    blockCode: string;
    chkId: string;
    closeDate: string | null;
    countLimit: CardCountLimit_2[];
    createdAtBranch: number | null;
    createdByUser: number | null;
    credDebAmount: number | null;
    credDebCount: number | null;
    credDebCountLimit: number | null;
    credDebLimit: number | null;
    creditCardId: string;
    depAmount: number | null;
    depCount: number | null;
    depCountLimit: number | null;
    depLimit: number | null;
    depMax: number | null;
    description: string;
    digitalIssueExcept: string;
    digitalIssueStatus: number | null;
    effectiveDate: string | null;
    emvChipProfile: string;
    expirationDate: string | null;
    extraEmboss: string;
    feeCount: CardFeeCount_2[];
    fileUpdateManagerException: number | null;
    imageRefDate: string | null;
    imageRefIssueCount: number | null;
    imageRefNumber: string;
    instantIssue: number | null;
    issueCode: number | null;
    issueDate: string | null;
    lastAddrChgDate: string | null;
    limit: CardLimit_2[];
    limitAmount: number | null;
    limitCount: CardLimitCount_2[];
    limitDays: number | null;
    limitDescription: CardLimitDescription_2[];
    limitUsageAmount: CardLimitUsageAmount_2[];
    locId: string;
    locator: number | null;
    miscAmount: number | null;
    miscCount: number | null;
    miscCountLimit: number | null;
    miscId: CardMiscId_2[];
    miscLimit: number | null;
    nameType: number | null;
    number: string;
    onlineCardIssue: number | null;
    onlineRushIssue: number | null;
    perItemLimit: CardPerItemLimit_2[];
    pinActual: number | null;
    pinEncrypted: string;
    pinOffset: number | null;
    pinOrderDate: string | null;
    pinRetries: number | null;
    posAmount: number | null;
    posCount: number | null;
    posCountLimit: number | null;
    posLimit: number | null;
    posTempLimit: number | null;
    prevActivationDate: string | null;
    prevExpirationDate: string | null;
    prevNumber: string;
    prevPinActual: number | null;
    prevPinOffset: number | null;
    prevSuffix: string;
    reclassCode: string;
    recordChangeDate: string | null;
    reissueCode: number | null;
    reissueMonths: number | null;
    savId: string;
    service: CardService_2[];
    singleUsageMax: number | null;
    status: number | null;
    statusReason: number | null;
    suffix: string;
    tempLimitEndDate: string | null;
    tempLimitStartDate: string | null;
    type: number | null;
    usageAmount: number | null;
    usageDate: string | null;
    usageLimit: number | null;
    warningCode: CardWarningCode_2[];
    warningExpiration: CardWarningExpiration_2[];
    wdCheckAmount: number | null;
    wdCheckCount: number | null;
    wdCheckCountLimit: number | null;
    wdCheckLimit: number | null;
    wdCheckMax: number | null;
    xferAmount: number | null;
    xferCount: number | null;
    xferCountLimit: number | null;
    xferLimit: number | null;
    xferMax: number | null;
    version1: VersionType;
}