import { CardCountLimit_2 } from "./cardCountLimit_2";
import { CardFeeCount_2 } from "./cardFeeCount_2";
import { CardLimit_2 } from "./cardLimit_2";
import { CardLimitCount_2 } from "./cardLimitCount_2";
import { CardLimitDescription_2 } from "./cardLimitDescription_2";
import { CardLimitUsageAmount_2 } from "./cardLimitUsageAmount_2";
import { CardMiscId_2 } from "./cardMiscId_2";
import { CardPerItemLimit_2 } from "./cardPerItemLimit_2";
import { CardService_2 } from "./cardService_2";
import { CardWarningCode_2 } from "./cardWarningCode_2";
import { CardWarningExpiration_2 } from "./cardWarningExpiration_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Card_2 {
    activeDateValue: string | null;
    activeDateValueSpecified: boolean;
    activeDate: string | null;
    atmCountValue: number;
    atmCountValueSpecified: boolean;
    atmCount: number | null;
    atmCountLimitValue: number;
    atmCountLimitValueSpecified: boolean;
    atmCountLimit: number | null;
    atmTempLimitValue: number;
    atmTempLimitValueSpecified: boolean;
    atmTempLimit: number | null;
    authAmountValue: number;
    authAmountValueSpecified: boolean;
    authAmount: number | null;
    authCountValue: number;
    authCountValueSpecified: boolean;
    authCount: number | null;
    authCountLimitValue: number;
    authCountLimitValueSpecified: boolean;
    authCountLimit: number | null;
    authLimitValue: number;
    authLimitValueSpecified: boolean;
    authLimit: number | null;
    authTempLimitValue: number;
    authTempLimitValueSpecified: boolean;
    authTempLimit: number | null;
    billPayAmountValue: number;
    billPayAmountValueSpecified: boolean;
    billPayAmount: number | null;
    billPayCountValue: number;
    billPayCountValueSpecified: boolean;
    billPayCount: number | null;
    billPayCountLimitValue: number;
    billPayCountLimitValueSpecified: boolean;
    billPayCountLimit: number | null;
    billPayLimitValue: number;
    billPayLimitValueSpecified: boolean;
    billPayLimit: number | null;
    billPayMaxValue: number;
    billPayMaxValueSpecified: boolean;
    billPayMax: number | null;
    blockCode: string;
    chkId: string;
    closeDateValue: string | null;
    closeDateValueSpecified: boolean;
    closeDate: string | null;
    countLimit: CardCountLimit_2[];
    countLimitSpecified: boolean;
    createdAtBranchValue: number;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: number | null;
    createdByUserValue: number;
    createdByUserValueSpecified: boolean;
    createdByUser: number | null;
    credDebAmountValue: number;
    credDebAmountValueSpecified: boolean;
    credDebAmount: number | null;
    credDebCountValue: number;
    credDebCountValueSpecified: boolean;
    credDebCount: number | null;
    credDebCountLimitValue: number;
    credDebCountLimitValueSpecified: boolean;
    credDebCountLimit: number | null;
    credDebLimitValue: number;
    credDebLimitValueSpecified: boolean;
    credDebLimit: number | null;
    creditCardId: string;
    depAmountValue: number;
    depAmountValueSpecified: boolean;
    depAmount: number | null;
    depCountValue: number;
    depCountValueSpecified: boolean;
    depCount: number | null;
    depCountLimitValue: number;
    depCountLimitValueSpecified: boolean;
    depCountLimit: number | null;
    depLimitValue: number;
    depLimitValueSpecified: boolean;
    depLimit: number | null;
    depMaxValue: number;
    depMaxValueSpecified: boolean;
    depMax: number | null;
    description: string;
    digitalIssueExcept: string;
    digitalIssueStatusValue: number;
    digitalIssueStatusValueSpecified: boolean;
    digitalIssueStatus: number | null;
    effectiveDateValue: string | null;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    emvChipProfile: string;
    expirationDateValue: string | null;
    expirationDateValueSpecified: boolean;
    expirationDate: string | null;
    extraEmboss: string;
    feeCount: CardFeeCount_2[];
    feeCountSpecified: boolean;
    fileUpdateManagerExceptionValue: number;
    fileUpdateManagerExceptionValueSpecified: boolean;
    fileUpdateManagerException: number | null;
    imageRefDateValue: string | null;
    imageRefDateValueSpecified: boolean;
    imageRefDate: string | null;
    imageRefIssueCountValue: number;
    imageRefIssueCountValueSpecified: boolean;
    imageRefIssueCount: number | null;
    imageRefNumber: string;
    instantIssueValue: number;
    instantIssueValueSpecified: boolean;
    instantIssue: number | null;
    issueCodeValue: number;
    issueCodeValueSpecified: boolean;
    issueCode: number | null;
    issueDateValue: string | null;
    issueDateValueSpecified: boolean;
    issueDate: string | null;
    lastAddrChgDateValue: string | null;
    lastAddrChgDateValueSpecified: boolean;
    lastAddrChgDate: string | null;
    limit: CardLimit_2[];
    limitSpecified: boolean;
    limitAmountValue: number;
    limitAmountValueSpecified: boolean;
    limitAmount: number | null;
    limitCount: CardLimitCount_2[];
    limitCountSpecified: boolean;
    limitDaysValue: number;
    limitDaysValueSpecified: boolean;
    limitDays: number | null;
    limitDescription: CardLimitDescription_2[];
    limitDescriptionSpecified: boolean;
    limitUsageAmount: CardLimitUsageAmount_2[];
    limitUsageAmountSpecified: boolean;
    locId: string;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    miscAmountValue: number;
    miscAmountValueSpecified: boolean;
    miscAmount: number | null;
    miscCountValue: number;
    miscCountValueSpecified: boolean;
    miscCount: number | null;
    miscCountLimitValue: number;
    miscCountLimitValueSpecified: boolean;
    miscCountLimit: number | null;
    miscId: CardMiscId_2[];
    miscIdSpecified: boolean;
    miscLimitValue: number;
    miscLimitValueSpecified: boolean;
    miscLimit: number | null;
    nameTypeValue: number;
    nameTypeValueSpecified: boolean;
    nameType: number | null;
    number: string;
    onlineCardIssueValue: number;
    onlineCardIssueValueSpecified: boolean;
    onlineCardIssue: number | null;
    onlineRushIssueValue: number;
    onlineRushIssueValueSpecified: boolean;
    onlineRushIssue: number | null;
    perItemLimit: CardPerItemLimit_2[];
    perItemLimitSpecified: boolean;
    pinActualValue: number;
    pinActualValueSpecified: boolean;
    pinActual: number | null;
    pinEncrypted: string;
    pinOffsetValue: number;
    pinOffsetValueSpecified: boolean;
    pinOffset: number | null;
    pinOrderDateValue: string | null;
    pinOrderDateValueSpecified: boolean;
    pinOrderDate: string | null;
    pinRetriesValue: number;
    pinRetriesValueSpecified: boolean;
    pinRetries: number | null;
    posAmountValue: number;
    posAmountValueSpecified: boolean;
    posAmount: number | null;
    posCountValue: number;
    posCountValueSpecified: boolean;
    posCount: number | null;
    posCountLimitValue: number;
    posCountLimitValueSpecified: boolean;
    posCountLimit: number | null;
    posLimitValue: number;
    posLimitValueSpecified: boolean;
    posLimit: number | null;
    posTempLimitValue: number;
    posTempLimitValueSpecified: boolean;
    posTempLimit: number | null;
    prevActivationDateValue: string | null;
    prevActivationDateValueSpecified: boolean;
    prevActivationDate: string | null;
    prevExpirationDateValue: string | null;
    prevExpirationDateValueSpecified: boolean;
    prevExpirationDate: string | null;
    prevNumber: string;
    prevPinActualValue: number;
    prevPinActualValueSpecified: boolean;
    prevPinActual: number | null;
    prevPinOffsetValue: number;
    prevPinOffsetValueSpecified: boolean;
    prevPinOffset: number | null;
    prevSuffix: string;
    reclassCode: string;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    reissueCodeValue: number;
    reissueCodeValueSpecified: boolean;
    reissueCode: number | null;
    reissueMonthsValue: number;
    reissueMonthsValueSpecified: boolean;
    reissueMonths: number | null;
    savId: string;
    service: CardService_2[];
    serviceSpecified: boolean;
    singleUsageMaxValue: number;
    singleUsageMaxValueSpecified: boolean;
    singleUsageMax: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    statusReasonValue: number;
    statusReasonValueSpecified: boolean;
    statusReason: number | null;
    suffix: string;
    tempLimitEndDateValue: string | null;
    tempLimitEndDateValueSpecified: boolean;
    tempLimitEndDate: string | null;
    tempLimitStartDateValue: string | null;
    tempLimitStartDateValueSpecified: boolean;
    tempLimitStartDate: string | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    usageAmountValue: number;
    usageAmountValueSpecified: boolean;
    usageAmount: number | null;
    usageDateValue: string | null;
    usageDateValueSpecified: boolean;
    usageDate: string | null;
    usageLimitValue: number;
    usageLimitValueSpecified: boolean;
    usageLimit: number | null;
    warningCode: CardWarningCode_2[];
    warningCodeSpecified: boolean;
    warningExpiration: CardWarningExpiration_2[];
    warningExpirationSpecified: boolean;
    wdCheckAmountValue: number;
    wdCheckAmountValueSpecified: boolean;
    wdCheckAmount: number | null;
    wdCheckCountValue: number;
    wdCheckCountValueSpecified: boolean;
    wdCheckCount: number | null;
    wdCheckCountLimitValue: number;
    wdCheckCountLimitValueSpecified: boolean;
    wdCheckCountLimit: number | null;
    wdCheckLimitValue: number;
    wdCheckLimitValueSpecified: boolean;
    wdCheckLimit: number | null;
    wdCheckMaxValue: number;
    wdCheckMaxValueSpecified: boolean;
    wdCheckMax: number | null;
    xferAmountValue: number;
    xferAmountValueSpecified: boolean;
    xferAmount: number | null;
    xferCountValue: number;
    xferCountValueSpecified: boolean;
    xferCount: number | null;
    xferCountLimitValue: number;
    xferCountLimitValueSpecified: boolean;
    xferCountLimit: number | null;
    xferLimitValue: number;
    xferLimitValueSpecified: boolean;
    xferLimit: number | null;
    xferMaxValue: number;
    xferMaxValueSpecified: boolean;
    xferMax: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}