import { BitMap } from "./bitMap";
import { CardWizJointNameFields_2 } from "./cardWizJointNameFields_2";
import { CardWizMaxAllowedUserDef_2 } from "./cardWizMaxAllowedUserDef_2";
import { CardWizUserDefAccessType_2 } from "./cardWizUserDefAccessType_2";
import { CardWizUserDefAllowedTypes_2 } from "./cardWizUserDefAllowedTypes_2";
import { CardWizUserDefIdType_2 } from "./cardWizUserDefIdType_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CardWiz_2 {
    activateCardNoteCodeValue: number;
    activateCardNoteCodeValueSpecified: boolean;
    activateCardNoteCode: number | null;
    activateCardRestrctnLvlValue: number;
    activateCardRestrctnLvlValueSpecified: boolean;
    activateCardRestrctnLvl: number | null;
    allowCardActivationValue: boolean;
    allowCardActivationValueSpecified: boolean;
    allowCardActivation: boolean | null;
    allowCardCreationValue: boolean;
    allowCardCreationValueSpecified: boolean;
    allowCardCreation: boolean | null;
    allowCrossAccountAccessValue: boolean;
    allowCrossAccountAccessValueSpecified: boolean;
    allowCrossAccountAccess: boolean | null;
    allowNewNameValue: boolean;
    allowNewNameValueSpecified: boolean;
    allowNewName: boolean | null;
    allowNonIndividualNameValue: boolean;
    allowNonIndividualNameValueSpecified: boolean;
    allowNonIndividualName: boolean | null;
    automaticallySetAccessValue: boolean;
    automaticallySetAccessValueSpecified: boolean;
    automaticallySetAccess: boolean | null;
    captureBlockCardNoteCodeValue: number;
    captureBlockCardNoteCodeValueSpecified: boolean;
    captureBlockCardNoteCode: number | null;
    captureBlockCardOptionsValue: number;
    captureBlockCardOptionsValueSpecified: boolean;
    captureBlockCardOptions: number | null;
    cardBlockCodes: string;
    cardBlockRestrctnLvlValue: number;
    cardBlockRestrctnLvlValueSpecified: boolean;
    cardBlockRestrctnLvl: number | null;
    cardCreateRestrctnLvlValue: number;
    cardCreateRestrctnLvlValueSpecified: boolean;
    cardCreateRestrctnLvl: number | null;
    cardCreateRestrictWarnList: BitMap;
    cardCreationNoteCodeValue: number;
    cardCreationNoteCodeValueSpecified: boolean;
    cardCreationNoteCode: number | null;
    cardNumberFormat: string;
    cardStatusReasonCodes: BitMap;
    cardSuffixHighValue: number;
    cardSuffixHighValueSpecified: boolean;
    cardSuffixHigh: number | null;
    cardSuffixLowValue: number;
    cardSuffixLowValueSpecified: boolean;
    cardSuffixLow: number | null;
    cardTypeValue: number;
    cardTypeValueSpecified: boolean;
    cardType: number | null;
    chkTypes: BitMap;
    copyShareLoanAccessValue: number;
    copyShareLoanAccessValueSpecified: boolean;
    copyShareLoanAccess: number | null;
    creditCardTypes: BitMap;
    definedValue: boolean;
    definedValueSpecified: boolean;
    defined: boolean | null;
    digitalIssueValue: number;
    digitalIssueValueSpecified: boolean;
    digitalIssue: number | null;
    displayCardFieldsValue: boolean;
    displayCardFieldsValueSpecified: boolean;
    displayCardFields: boolean | null;
    displayIssueCodeValue: boolean;
    displayIssueCodeValueSpecified: boolean;
    displayIssueCode: boolean | null;
    displayNameFieldsValue: number;
    displayNameFieldsValueSpecified: boolean;
    displayNameFields: number | null;
    displayNewCardNumberValue: boolean;
    displayNewCardNumberValueSpecified: boolean;
    displayNewCardNumber: boolean | null;
    expirationMonthsValue: number;
    expirationMonthsValueSpecified: boolean;
    expirationMonths: number | null;
    expirationMonthsHighValue: number;
    expirationMonthsHighValueSpecified: boolean;
    expirationMonthsHigh: number | null;
    expirationMonthsLowValue: number;
    expirationMonthsLowValueSpecified: boolean;
    expirationMonthsLow: number | null;
    fmLoanReferenceFieldValue: boolean;
    fmLoanReferenceFieldValueSpecified: boolean;
    fmLoanReferenceField: boolean | null;
    forceReissRestrictWarnList: BitMap;
    forceReissueCardNoteCodeValue: number;
    forceReissueCardNoteCodeValueSpecified: boolean;
    forceReissueCardNoteCode: number | null;
    forceReissueOptionsValue: number;
    forceReissueOptionsValueSpecified: boolean;
    forceReissueOptions: number | null;
    forceReissueRestrctnLvlValue: number;
    forceReissueRestrctnLvlValueSpecified: boolean;
    forceReissueRestrctnLvl: number | null;
    instantIssueValue: number;
    instantIssueValueSpecified: boolean;
    instantIssue: number | null;
    instantIssueExpMonthsValue: number;
    instantIssueExpMonthsValueSpecified: boolean;
    instantIssueExpMonths: number | null;
    jointNameFields: CardWizJointNameFields_2[];
    jointNameFieldsSpecified: boolean;
    jointNameTypes: BitMap;
    linkSharesLoansValue: number;
    linkSharesLoansValueSpecified: boolean;
    linkSharesLoans: number | null;
    loanTypes: BitMap;
    locTypes: BitMap;
    maxAllowableChkIdsValue: number;
    maxAllowableChkIdsValueSpecified: boolean;
    maxAllowableChkIds: number | null;
    maxAllowableCreditCardIdsValue: number;
    maxAllowableCreditCardIdsValueSpecified: boolean;
    maxAllowableCreditCardIds: number | null;
    maxAllowableLoanIdsValue: number;
    maxAllowableLoanIdsValueSpecified: boolean;
    maxAllowableLoanIds: number | null;
    maxAllowableLocIdsValue: number;
    maxAllowableLocIdsValueSpecified: boolean;
    maxAllowableLocIds: number | null;
    maxAllowableSavIdsValue: number;
    maxAllowableSavIdsValueSpecified: boolean;
    maxAllowableSavIds: number | null;
    maxAllowedUserDef: CardWizMaxAllowedUserDef_2[];
    maxAllowedUserDefSpecified: boolean;
    maxExtraEmbossLineLengthValue: number;
    maxExtraEmbossLineLengthValueSpecified: boolean;
    maxExtraEmbossLineLength: number | null;
    maxNameLengthValue: number;
    maxNameLengthValueSpecified: boolean;
    maxNameLength: number | null;
    miscId1AccessValue: number;
    miscId1AccessValueSpecified: boolean;
    miscId1Access: number | null;
    miscId1Types: BitMap;
    miscId2AccessValue: number;
    miscId2AccessValueSpecified: boolean;
    miscId2Access: number | null;
    miscId2Types: BitMap;
    miscId3AccessValue: number;
    miscId3AccessValueSpecified: boolean;
    miscId3Access: number | null;
    miscId3Types: BitMap;
    nameRecordCopyOptionValue: number;
    nameRecordCopyOptionValueSpecified: boolean;
    nameRecordCopyOption: number | null;
    nextSequentialNumberValue: number;
    nextSequentialNumberValueSpecified: boolean;
    nextSequentialNumber: number | null;
    nextSequentialStepValue: number;
    nextSequentialStepValueSpecified: boolean;
    nextSequentialStep: number | null;
    nextSuffixStepValue: number;
    nextSuffixStepValueSpecified: boolean;
    nextSuffixStep: number | null;
    nextSuffixinCardNumStepValue: number;
    nextSuffixinCardNumStepValueSpecified: boolean;
    nextSuffixinCardNumStep: number | null;
    onlExpDaysforForceReissueValue: number;
    onlExpDaysforForceReissueValueSpecified: boolean;
    onlExpDaysforForceReissue: number | null;
    onlineCardIssueValue: number;
    onlineCardIssueValueSpecified: boolean;
    onlineCardIssue: number | null;
    onlineReissueExpDateHighValue: number;
    onlineReissueExpDateHighValueSpecified: boolean;
    onlineReissueExpDateHigh: number | null;
    onlineReissueExpDateLowValue: number;
    onlineReissueExpDateLowValueSpecified: boolean;
    onlineReissueExpDateLow: number | null;
    onlineReissueMonthsValue: number;
    onlineReissueMonthsValueSpecified: boolean;
    onlineReissueMonths: number | null;
    onlineRushCardOptions: BitMap;
    optionalSpecfile: string;
    pinOffsetRandomGenerationValue: boolean;
    pinOffsetRandomGenerationValueSpecified: boolean;
    pinOffsetRandomGeneration: boolean | null;
    randomNumberHighValue: number;
    randomNumberHighValueSpecified: boolean;
    randomNumberHigh: number | null;
    randomNumberLowValue: number;
    randomNumberLowValueSpecified: boolean;
    randomNumberLow: number | null;
    reissueCardsWithSameNbrValue: number;
    reissueCardsWithSameNbrValueSpecified: boolean;
    reissueCardsWithSameNbr: number | null;
    requiredFundingTypeValue: number;
    requiredFundingTypeValueSpecified: boolean;
    requiredFundingType: number | null;
    restorePrevExpActiveDateValue: number;
    restorePrevExpActiveDateValueSpecified: boolean;
    restorePrevExpActiveDate: number | null;
    savTypes: BitMap;
    selectNamesFrom: BitMap;
    serviceCodeValue: number;
    serviceCodeValueSpecified: boolean;
    serviceCode: number | null;
    setActivationDateValue: boolean;
    setActivationDateValueSpecified: boolean;
    setActivationDate: boolean | null;
    setCardStatustoIssuedValue: boolean;
    setCardStatustoIssuedValueSpecified: boolean;
    setCardStatustoIssued: boolean | null;
    setCloseDateValue: boolean;
    setCloseDateValueSpecified: boolean;
    setCloseDate: boolean | null;
    setEffectiveDateValue: boolean;
    setEffectiveDateValueSpecified: boolean;
    setEffectiveDate: boolean | null;
    setEffectiveDateFieldValue: boolean;
    setEffectiveDateFieldValueSpecified: boolean;
    setEffectiveDateField: boolean | null;
    setInstantIssueFieldValue: boolean;
    setInstantIssueFieldValueSpecified: boolean;
    setInstantIssueField: boolean | null;
    suffixinCardNumberHighValue: number;
    suffixinCardNumberHighValueSpecified: boolean;
    suffixinCardNumberHigh: number | null;
    suffixinCardNumberLowValue: number;
    suffixinCardNumberLowValueSpecified: boolean;
    suffixinCardNumberLow: number | null;
    uniqueCardNumberValue: boolean;
    uniqueCardNumberValueSpecified: boolean;
    uniqueCardNumber: boolean | null;
    useCardSuffixFieldValue: boolean;
    useCardSuffixFieldValueSpecified: boolean;
    useCardSuffixField: boolean | null;
    userDefAccessType: CardWizUserDefAccessType_2[];
    userDefAccessTypeSpecified: boolean;
    userDefAllowedTypes: CardWizUserDefAllowedTypes_2[];
    userDefAllowedTypesSpecified: boolean;
    userDefIdType: CardWizUserDefIdType_2[];
    userDefIdTypeSpecified: boolean;
    validateShareLoanAccessValue: boolean;
    validateShareLoanAccessValueSpecified: boolean;
    validateShareLoanAccess: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}