import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CardFields {
    activeDateValue: boolean;
    activeDateValueSpecified: boolean;
    activeDate: boolean | null;
    atmCountValue: boolean;
    atmCountValueSpecified: boolean;
    atmCount: boolean | null;
    atmCountLimitValue: boolean;
    atmCountLimitValueSpecified: boolean;
    atmCountLimit: boolean | null;
    atmTempLimitValue: boolean;
    atmTempLimitValueSpecified: boolean;
    atmTempLimit: boolean | null;
    authAmountValue: boolean;
    authAmountValueSpecified: boolean;
    authAmount: boolean | null;
    authCountValue: boolean;
    authCountValueSpecified: boolean;
    authCount: boolean | null;
    authCountLimitValue: boolean;
    authCountLimitValueSpecified: boolean;
    authCountLimit: boolean | null;
    authLimitValue: boolean;
    authLimitValueSpecified: boolean;
    authLimit: boolean | null;
    authTempLimitValue: boolean;
    authTempLimitValueSpecified: boolean;
    authTempLimit: boolean | null;
    billPayAmountValue: boolean;
    billPayAmountValueSpecified: boolean;
    billPayAmount: boolean | null;
    billPayCountValue: boolean;
    billPayCountValueSpecified: boolean;
    billPayCount: boolean | null;
    billPayCountLimitValue: boolean;
    billPayCountLimitValueSpecified: boolean;
    billPayCountLimit: boolean | null;
    billPayLimitValue: boolean;
    billPayLimitValueSpecified: boolean;
    billPayLimit: boolean | null;
    billPayMaxValue: boolean;
    billPayMaxValueSpecified: boolean;
    billPayMax: boolean | null;
    blockCodeValue: boolean;
    blockCodeValueSpecified: boolean;
    blockCode: boolean | null;
    chkIdValue: boolean;
    chkIdValueSpecified: boolean;
    chkId: boolean | null;
    closeDateValue: boolean;
    closeDateValueSpecified: boolean;
    closeDate: boolean | null;
    countLimit: number[];
    countLimitSpecified: boolean;
    createdAtBranchValue: boolean;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: boolean | null;
    createdByUserValue: boolean;
    createdByUserValueSpecified: boolean;
    createdByUser: boolean | null;
    credDebAmountValue: boolean;
    credDebAmountValueSpecified: boolean;
    credDebAmount: boolean | null;
    credDebCountValue: boolean;
    credDebCountValueSpecified: boolean;
    credDebCount: boolean | null;
    credDebCountLimitValue: boolean;
    credDebCountLimitValueSpecified: boolean;
    credDebCountLimit: boolean | null;
    credDebLimitValue: boolean;
    credDebLimitValueSpecified: boolean;
    credDebLimit: boolean | null;
    creditCardIdValue: boolean;
    creditCardIdValueSpecified: boolean;
    creditCardId: boolean | null;
    depAmountValue: boolean;
    depAmountValueSpecified: boolean;
    depAmount: boolean | null;
    depCountValue: boolean;
    depCountValueSpecified: boolean;
    depCount: boolean | null;
    depCountLimitValue: boolean;
    depCountLimitValueSpecified: boolean;
    depCountLimit: boolean | null;
    depLimitValue: boolean;
    depLimitValueSpecified: boolean;
    depLimit: boolean | null;
    depMaxValue: boolean;
    depMaxValueSpecified: boolean;
    depMax: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    digitalIssueExceptValue: boolean;
    digitalIssueExceptValueSpecified: boolean;
    digitalIssueExcept: boolean | null;
    digitalIssueStatusValue: boolean;
    digitalIssueStatusValueSpecified: boolean;
    digitalIssueStatus: boolean | null;
    effectiveDateValue: boolean;
    effectiveDateValueSpecified: boolean;
    effectiveDate: boolean | null;
    emvChipProfileValue: boolean;
    emvChipProfileValueSpecified: boolean;
    emvChipProfile: boolean | null;
    expirationDateValue: boolean;
    expirationDateValueSpecified: boolean;
    expirationDate: boolean | null;
    extraEmbossValue: boolean;
    extraEmbossValueSpecified: boolean;
    extraEmboss: boolean | null;
    feeCount: number[];
    feeCountSpecified: boolean;
    fileUpdateManagerExceptionValue: boolean;
    fileUpdateManagerExceptionValueSpecified: boolean;
    fileUpdateManagerException: boolean | null;
    imageRefDateValue: boolean;
    imageRefDateValueSpecified: boolean;
    imageRefDate: boolean | null;
    imageRefIssueCountValue: boolean;
    imageRefIssueCountValueSpecified: boolean;
    imageRefIssueCount: boolean | null;
    imageRefNumberValue: boolean;
    imageRefNumberValueSpecified: boolean;
    imageRefNumber: boolean | null;
    instantIssueValue: boolean;
    instantIssueValueSpecified: boolean;
    instantIssue: boolean | null;
    issueCodeValue: boolean;
    issueCodeValueSpecified: boolean;
    issueCode: boolean | null;
    issueDateValue: boolean;
    issueDateValueSpecified: boolean;
    issueDate: boolean | null;
    lastAddrChgDateValue: boolean;
    lastAddrChgDateValueSpecified: boolean;
    lastAddrChgDate: boolean | null;
    limit: number[];
    limitSpecified: boolean;
    limitAmountValue: boolean;
    limitAmountValueSpecified: boolean;
    limitAmount: boolean | null;
    limitCount: number[];
    limitCountSpecified: boolean;
    limitDaysValue: boolean;
    limitDaysValueSpecified: boolean;
    limitDays: boolean | null;
    limitDescription: number[];
    limitDescriptionSpecified: boolean;
    limitUsageAmount: number[];
    limitUsageAmountSpecified: boolean;
    locIdValue: boolean;
    locIdValueSpecified: boolean;
    locId: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    miscAmountValue: boolean;
    miscAmountValueSpecified: boolean;
    miscAmount: boolean | null;
    miscCountValue: boolean;
    miscCountValueSpecified: boolean;
    miscCount: boolean | null;
    miscCountLimitValue: boolean;
    miscCountLimitValueSpecified: boolean;
    miscCountLimit: boolean | null;
    miscId: number[];
    miscIdSpecified: boolean;
    miscLimitValue: boolean;
    miscLimitValueSpecified: boolean;
    miscLimit: boolean | null;
    nameTypeValue: boolean;
    nameTypeValueSpecified: boolean;
    nameType: boolean | null;
    numberValue: boolean;
    numberValueSpecified: boolean;
    number: boolean | null;
    onlineCardIssueValue: boolean;
    onlineCardIssueValueSpecified: boolean;
    onlineCardIssue: boolean | null;
    onlineRushIssueValue: boolean;
    onlineRushIssueValueSpecified: boolean;
    onlineRushIssue: boolean | null;
    perItemLimit: number[];
    perItemLimitSpecified: boolean;
    pinActualValue: boolean;
    pinActualValueSpecified: boolean;
    pinActual: boolean | null;
    pinEncryptedValue: boolean;
    pinEncryptedValueSpecified: boolean;
    pinEncrypted: boolean | null;
    pinOffsetValue: boolean;
    pinOffsetValueSpecified: boolean;
    pinOffset: boolean | null;
    pinOrderDateValue: boolean;
    pinOrderDateValueSpecified: boolean;
    pinOrderDate: boolean | null;
    pinRetriesValue: boolean;
    pinRetriesValueSpecified: boolean;
    pinRetries: boolean | null;
    posAmountValue: boolean;
    posAmountValueSpecified: boolean;
    posAmount: boolean | null;
    posCountValue: boolean;
    posCountValueSpecified: boolean;
    posCount: boolean | null;
    posCountLimitValue: boolean;
    posCountLimitValueSpecified: boolean;
    posCountLimit: boolean | null;
    posLimitValue: boolean;
    posLimitValueSpecified: boolean;
    posLimit: boolean | null;
    posTempLimitValue: boolean;
    posTempLimitValueSpecified: boolean;
    posTempLimit: boolean | null;
    prevActivationDateValue: boolean;
    prevActivationDateValueSpecified: boolean;
    prevActivationDate: boolean | null;
    prevExpirationDateValue: boolean;
    prevExpirationDateValueSpecified: boolean;
    prevExpirationDate: boolean | null;
    prevNumberValue: boolean;
    prevNumberValueSpecified: boolean;
    prevNumber: boolean | null;
    prevPinActualValue: boolean;
    prevPinActualValueSpecified: boolean;
    prevPinActual: boolean | null;
    prevPinOffsetValue: boolean;
    prevPinOffsetValueSpecified: boolean;
    prevPinOffset: boolean | null;
    prevSuffixValue: boolean;
    prevSuffixValueSpecified: boolean;
    prevSuffix: boolean | null;
    reclassCodeValue: boolean;
    reclassCodeValueSpecified: boolean;
    reclassCode: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    reissueCodeValue: boolean;
    reissueCodeValueSpecified: boolean;
    reissueCode: boolean | null;
    reissueMonthsValue: boolean;
    reissueMonthsValueSpecified: boolean;
    reissueMonths: boolean | null;
    savIdValue: boolean;
    savIdValueSpecified: boolean;
    savId: boolean | null;
    service: number[];
    serviceSpecified: boolean;
    singleUsageMaxValue: boolean;
    singleUsageMaxValueSpecified: boolean;
    singleUsageMax: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    statusReasonValue: boolean;
    statusReasonValueSpecified: boolean;
    statusReason: boolean | null;
    suffixValue: boolean;
    suffixValueSpecified: boolean;
    suffix: boolean | null;
    tempLimitEndDateValue: boolean;
    tempLimitEndDateValueSpecified: boolean;
    tempLimitEndDate: boolean | null;
    tempLimitStartDateValue: boolean;
    tempLimitStartDateValueSpecified: boolean;
    tempLimitStartDate: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    usageAmountValue: boolean;
    usageAmountValueSpecified: boolean;
    usageAmount: boolean | null;
    usageDateValue: boolean;
    usageDateValueSpecified: boolean;
    usageDate: boolean | null;
    usageLimitValue: boolean;
    usageLimitValueSpecified: boolean;
    usageLimit: boolean | null;
    warningCode: number[];
    warningCodeSpecified: boolean;
    warningExpiration: number[];
    warningExpirationSpecified: boolean;
    wdCheckAmountValue: boolean;
    wdCheckAmountValueSpecified: boolean;
    wdCheckAmount: boolean | null;
    wdCheckCountValue: boolean;
    wdCheckCountValueSpecified: boolean;
    wdCheckCount: boolean | null;
    wdCheckCountLimitValue: boolean;
    wdCheckCountLimitValueSpecified: boolean;
    wdCheckCountLimit: boolean | null;
    wdCheckLimitValue: boolean;
    wdCheckLimitValueSpecified: boolean;
    wdCheckLimit: boolean | null;
    wdCheckMaxValue: boolean;
    wdCheckMaxValueSpecified: boolean;
    wdCheckMax: boolean | null;
    xferAmountValue: boolean;
    xferAmountValueSpecified: boolean;
    xferAmount: boolean | null;
    xferCountValue: boolean;
    xferCountValueSpecified: boolean;
    xferCount: boolean | null;
    xferCountLimitValue: boolean;
    xferCountLimitValueSpecified: boolean;
    xferCountLimit: boolean | null;
    xferLimitValue: boolean;
    xferLimitValueSpecified: boolean;
    xferLimit: boolean | null;
    xferMaxValue: boolean;
    xferMaxValueSpecified: boolean;
    xferMax: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}