import { BitMap } from "./bitMap";
import { CardWizJointNameFields } from "./cardWizJointNameFields";
import { CardWizMaxAllowedUserDef } from "./cardWizMaxAllowedUserDef";
import { CardWizUserDefAccessType } from "./cardWizUserDefAccessType";
import { CardWizUserDefAllowedTypes } from "./cardWizUserDefAllowedTypes";
import { CardWizUserDefIdType } from "./cardWizUserDefIdType";
import { VersionType } from "./versionType";

export interface CardWiz {
    activateCardNoteCode: number | null;
    activateCardRestrctnLvl: number | null;
    allowCardActivation: boolean | null;
    allowCardCreation: boolean | null;
    allowCrossAccountAccess: boolean | null;
    allowNewName: boolean | null;
    allowNonIndividualName: boolean | null;
    automaticallySetAccess: boolean | null;
    captureBlockCardNoteCode: number | null;
    captureBlockCardOptions: number | null;
    cardBlockCodes: string;
    cardBlockRestrctnLvl: number | null;
    cardCreateRestrctnLvl: number | null;
    cardCreateRestrictWarnList: BitMap;
    cardCreationNoteCode: number | null;
    cardNumberFormat: string;
    cardStatusReasonCodes: BitMap;
    cardSuffixHigh: number | null;
    cardSuffixLow: number | null;
    cardType: number | null;
    chkTypes: BitMap;
    copyShareLoanAccess: number | null;
    creditCardTypes: BitMap;
    defined: boolean | null;
    digitalIssue: number | null;
    displayCardFields: boolean | null;
    displayIssueCode: boolean | null;
    displayNameFields: number | null;
    displayNewCardNumber: boolean | null;
    expirationMonths: number | null;
    expirationMonthsHigh: number | null;
    expirationMonthsLow: number | null;
    fmLoanReferenceField: boolean | null;
    forceReissRestrictWarnList: BitMap;
    forceReissueCardNoteCode: number | null;
    forceReissueOptions: number | null;
    forceReissueRestrctnLvl: number | null;
    instantIssue: number | null;
    instantIssueExpMonths: number | null;
    jointNameFields: CardWizJointNameFields[];
    jointNameTypes: BitMap;
    linkSharesLoans: number | null;
    loanTypes: BitMap;
    locTypes: BitMap;
    maxAllowableChkIds: number | null;
    maxAllowableCreditCardIds: number | null;
    maxAllowableLoanIds: number | null;
    maxAllowableLocIds: number | null;
    maxAllowableSavIds: number | null;
    maxAllowedUserDef: CardWizMaxAllowedUserDef[];
    maxExtraEmbossLineLength: number | null;
    maxNameLength: number | null;
    miscId1Access: number | null;
    miscId1Types: BitMap;
    miscId2Access: number | null;
    miscId2Types: BitMap;
    miscId3Access: number | null;
    miscId3Types: BitMap;
    nameRecordCopyOption: number | null;
    nextSequentialNumber: number | null;
    nextSequentialStep: number | null;
    nextSuffixStep: number | null;
    nextSuffixinCardNumStep: number | null;
    onlExpDaysforForceReissue: number | null;
    onlineCardIssue: number | null;
    onlineReissueExpDateHigh: number | null;
    onlineReissueExpDateLow: number | null;
    onlineReissueMonths: number | null;
    onlineRushCardOptions: BitMap;
    optionalSpecfile: string;
    pinOffsetRandomGeneration: boolean | null;
    randomNumberHigh: number | null;
    randomNumberLow: number | null;
    reissueCardsWithSameNbr: number | null;
    requiredFundingType: number | null;
    restorePrevExpActiveDate: number | null;
    savTypes: BitMap;
    selectNamesFrom: BitMap;
    serviceCode: number | null;
    setActivationDate: boolean | null;
    setCardStatustoIssued: boolean | null;
    setCloseDate: boolean | null;
    setEffectiveDate: boolean | null;
    setEffectiveDateField: boolean | null;
    setInstantIssueField: boolean | null;
    suffixinCardNumberHigh: number | null;
    suffixinCardNumberLow: number | null;
    uniqueCardNumber: boolean | null;
    useCardSuffixField: boolean | null;
    userDefAccessType: CardWizUserDefAccessType[];
    userDefAllowedTypes: CardWizUserDefAllowedTypes[];
    userDefIdType: CardWizUserDefIdType[];
    validateShareLoanAccess: boolean | null;
    version1: VersionType;
}