import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CashLetterFields {
    accountInformationValue: boolean;
    accountInformationValueSpecified: boolean;
    accountInformation: boolean | null;
    accountNumberValue: boolean;
    accountNumberValueSpecified: boolean;
    accountNumber: boolean | null;
    adjustedTotalAmountValue: boolean;
    adjustedTotalAmountValueSpecified: boolean;
    adjustedTotalAmount: boolean | null;
    adjustmentAmountValue: boolean;
    adjustmentAmountValueSpecified: boolean;
    adjustmentAmount: boolean | null;
    adjustmentDateValue: boolean;
    adjustmentDateValueSpecified: boolean;
    adjustmentDate: boolean | null;
    availableAmount: number[];
    availableAmountSpecified: boolean;
    availableDate: number[];
    availableDateSpecified: boolean;
    batchIdValue: boolean;
    batchIdValueSpecified: boolean;
    batchId: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    calculatedAmountValue: boolean;
    calculatedAmountValueSpecified: boolean;
    calculatedAmount: boolean | null;
    calculatedDateValue: boolean;
    calculatedDateValueSpecified: boolean;
    calculatedDate: boolean | null;
    cashLetterAmountValue: boolean;
    cashLetterAmountValueSpecified: boolean;
    cashLetterAmount: boolean | null;
    cashLetterDateValue: boolean;
    cashLetterDateValueSpecified: boolean;
    cashLetterDate: boolean | null;
    corporateIdValue: boolean;
    corporateIdValueSpecified: boolean;
    corporateId: boolean | null;
    creationDateValue: boolean;
    creationDateValueSpecified: boolean;
    creationDate: boolean | null;
    creationTimeValue: boolean;
    creationTimeValueSpecified: boolean;
    creationTime: boolean | null;
    creditAmountValue: boolean;
    creditAmountValueSpecified: boolean;
    creditAmount: boolean | null;
    dayDeferredAmount: number[];
    dayDeferredAmountSpecified: boolean;
    debitAmountValue: boolean;
    debitAmountValueSpecified: boolean;
    debitAmount: boolean | null;
    debitCreditValue: boolean;
    debitCreditValueSpecified: boolean;
    debitCredit: boolean | null;
    depositDateValue: boolean;
    depositDateValueSpecified: boolean;
    depositDate: boolean | null;
    fedCodeValue: boolean;
    fedCodeValueSpecified: boolean;
    fedCode: boolean | null;
    fedReferenceValue: boolean;
    fedReferenceValueSpecified: boolean;
    fedReference: boolean | null;
    globalSequenceValue: boolean;
    globalSequenceValueSpecified: boolean;
    globalSequence: boolean | null;
    globalSequenceDateValue: boolean;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: boolean | null;
    immediateAmountValue: boolean;
    immediateAmountValueSpecified: boolean;
    immediateAmount: boolean | null;
    itemCountValue: boolean;
    itemCountValueSpecified: boolean;
    itemCount: boolean | null;
    memberIdValue: boolean;
    memberIdValueSpecified: boolean;
    memberId: boolean | null;
    originalAmountValue: boolean;
    originalAmountValueSpecified: boolean;
    originalAmount: boolean | null;
    originalDepositDateValue: boolean;
    originalDepositDateValueSpecified: boolean;
    originalDepositDate: boolean | null;
    originatorRtValue: boolean;
    originatorRtValueSpecified: boolean;
    originatorRt: boolean | null;
    payeeValue: boolean;
    payeeValueSpecified: boolean;
    payee: boolean | null;
    priorAmountValue: boolean;
    priorAmountValueSpecified: boolean;
    priorAmount: boolean | null;
    processDateValue: boolean;
    processDateValueSpecified: boolean;
    processDate: boolean | null;
    referenceValue: boolean;
    referenceValueSpecified: boolean;
    reference: boolean | null;
    resubmitAmountValue: boolean;
    resubmitAmountValueSpecified: boolean;
    resubmitAmount: boolean | null;
    returnReasonValue: boolean;
    returnReasonValueSpecified: boolean;
    returnReason: boolean | null;
    returnTypeValue: boolean;
    returnTypeValueSpecified: boolean;
    returnType: boolean | null;
    reversalDateValue: boolean;
    reversalDateValueSpecified: boolean;
    reversalDate: boolean | null;
    reversalFlagValue: boolean;
    reversalFlagValueSpecified: boolean;
    reversalFlag: boolean | null;
    shareIdValue: boolean;
    shareIdValueSpecified: boolean;
    shareId: boolean | null;
    statementCodeValue: boolean;
    statementCodeValueSpecified: boolean;
    statementCode: boolean | null;
    thirdPartyInformationValue: boolean;
    thirdPartyInformationValueSpecified: boolean;
    thirdPartyInformation: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    usCentralRtValue: boolean;
    usCentralRtValueSpecified: boolean;
    usCentralRt: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}