import { CdmCassDenom6DuressAuto1Notes } from "./cdmCassDenom6DuressAuto1Notes";
import { CdmCassDenom6DuressAuto2Notes } from "./cdmCassDenom6DuressAuto2Notes";
import { CdmCassDenom6DuressAuto3Notes } from "./cdmCassDenom6DuressAuto3Notes";
import { CdmCassetteDenomAutomixNotes } from "./cdmCassetteDenomAutomixNotes";
import { CdmCassetteDenomination } from "./cdmCassetteDenomination";
import { BitMap } from "./bitMap";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Cdm {
    cassDenom6DuressAuto1Notes: CdmCassDenom6DuressAuto1Notes[];
    cassDenom6DuressAuto1NotesSpecified: boolean;
    cassDenom6DuressAuto2Notes: CdmCassDenom6DuressAuto2Notes[];
    cassDenom6DuressAuto2NotesSpecified: boolean;
    cassDenom6DuressAuto3Notes: CdmCassDenom6DuressAuto3Notes[];
    cassDenom6DuressAuto3NotesSpecified: boolean;
    cassetteDenomAutomixNotes: CdmCassetteDenomAutomixNotes[];
    cassetteDenomAutomixNotesSpecified: boolean;
    cassetteDenomination: CdmCassetteDenomination[];
    cassetteDenominationSpecified: boolean;
    cdmPropertyValue: number;
    cdmPropertyValueSpecified: boolean;
    cdmProperty: number | null;
    cdmDuressDispAmtValue: number;
    cdmDuressDispAmtValueSpecified: boolean;
    cdmDuressDispAmt: number | null;
    cdmDuressSilentAlarmValue: boolean;
    cdmDuressSilentAlarmValueSpecified: boolean;
    cdmDuressSilentAlarm: boolean | null;
    consoleFileName: string;
    consoleFileNameExt: string;
    leftCoinDispenserValue: boolean;
    leftCoinDispenserValueSpecified: boolean;
    leftCoinDispenser: boolean | null;
    machineTypeValue: number;
    machineTypeValueSpecified: boolean;
    machineType: number | null;
    recyclerValue: boolean;
    recyclerValueSpecified: boolean;
    recycler: boolean | null;
    remoteDeviceValue: boolean;
    remoteDeviceValueSpecified: boolean;
    remoteDevice: boolean | null;
    rightCoinDispenserValue: boolean;
    rightCoinDispenserValueSpecified: boolean;
    rightCoinDispenser: boolean | null;
    userIds: BitMap;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}