import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CheckFmHistory {
    accountNumber: string;
    batchSequenceValue: number;
    batchSequenceValueSpecified: boolean;
    batchSequence: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    confirmationNumber: string;
    confirmationSeqValue: number;
    confirmationSeqValueSpecified: boolean;
    confirmationSeq: number | null;
    consoleNumberValue: number;
    consoleNumberValueSpecified: boolean;
    consoleNumber: number | null;
    dataTypeValue: number;
    dataTypeValueSpecified: boolean;
    dataType: number | null;
    fieldName: string;
    fieldNumberValue: number;
    fieldNumberValueSpecified: boolean;
    fieldNumber: number | null;
    fmTypeValue: number;
    fmTypeValueSpecified: boolean;
    fmType: number | null;
    id: string;
    idTypeValue: number;
    idTypeValueSpecified: boolean;
    idType: number | null;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    newCharacter: string;
    newDateValue: string;
    newDateValueSpecified: boolean;
    newDate: string | null;
    newMoneyValue: number;
    newMoneyValueSpecified: boolean;
    newMoney: number | null;
    newNumberValue: number;
    newNumberValueSpecified: boolean;
    newNumber: number | null;
    newRateValue: number;
    newRateValueSpecified: boolean;
    newRate: number | null;
    oldCharacter: string;
    oldDateValue: string;
    oldDateValueSpecified: boolean;
    oldDate: string | null;
    oldMoneyValue: number;
    oldMoneyValueSpecified: boolean;
    oldMoney: number | null;
    oldNumberValue: number;
    oldNumberValueSpecified: boolean;
    oldNumber: number | null;
    oldRateValue: number;
    oldRateValueSpecified: boolean;
    oldRate: number | null;
    postDateValue: string;
    postDateValueSpecified: boolean;
    postDate: string | null;
    postTimeValue: number;
    postTimeValueSpecified: boolean;
    postTime: number | null;
    processorUserValue: number;
    processorUserValueSpecified: boolean;
    processorUser: number | null;
    recordName: string;
    recordTypeValue: number;
    recordTypeValueSpecified: boolean;
    recordType: number | null;
    securityLevelsValue: number;
    securityLevelsValueSpecified: boolean;
    securityLevels: number | null;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    subFieldNumberValue: number;
    subFieldNumberValueSpecified: boolean;
    subFieldNumber: number | null;
    userNumberValue: number;
    userNumberValueSpecified: boolean;
    userNumber: number | null;
    userOverrideValue: number;
    userOverrideValueSpecified: boolean;
    userOverride: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}