import { CheckOrderDefaultBusCaptions } from "./checkOrderDefaultBusCaptions";
import { VersionType } from "./versionType";

export interface CheckOrderDefault {
    accent: string;
    acctAddrInkColor: number | null;
    billingCode: number | null;
    branch: number | null;
    busBindingStyle: number | null;
    busCaptions: CheckOrderDefaultBusCaptions[];
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShipping: number | null;
    checkOrderProcessor: number | null;
    checkStyle: string;
    checkType: number | null;
    coverStyle: string;
    cutInkColor: number | null;
    cutNumber: string;
    imprintFont: number | null;
    imprintJustify: number | null;
    lastOrderDate: string | null;
    numberSigLines: number | null;
    overSigFont: number | null;
    overSigJustify: number | null;
    phantom: string;
    poNumber: string;
    processor: number | null;
    promoNumber: string;
    quantity: number | null;
    rerunReason: number | null;
    shipMethod: number | null;
    shipTo: number | null;
    sigFigure: string;
    startNumber: number | null;
    taxExemptCode: number | null;
    titleInkColor: number | null;
    version1: VersionType;
}