import { CheckOrderDefaultBusCaptions_2 } from "./checkOrderDefaultBusCaptions_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CheckOrderDefault_2 {
    accent: string;
    acctAddrInkColorValue: number;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: number | null;
    billingCodeValue: number;
    billingCodeValueSpecified: boolean;
    billingCode: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    busBindingStyleValue: number;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: number | null;
    busCaptions: CheckOrderDefaultBusCaptions_2[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: number;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShippingValue: number;
    chargeShippingValueSpecified: boolean;
    chargeShipping: number | null;
    checkOrderProcessorValue: number;
    checkOrderProcessorValueSpecified: boolean;
    checkOrderProcessor: number | null;
    checkStyle: string;
    checkTypeValue: number;
    checkTypeValueSpecified: boolean;
    checkType: number | null;
    coverStyle: string;
    cutInkColorValue: number;
    cutInkColorValueSpecified: boolean;
    cutInkColor: number | null;
    cutNumber: string;
    imprintFontValue: number;
    imprintFontValueSpecified: boolean;
    imprintFont: number | null;
    imprintJustifyValue: number;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: number | null;
    lastOrderDateValue: string | null;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: string | null;
    numberSigLinesValue: number;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: number | null;
    overSigFontValue: number;
    overSigFontValueSpecified: boolean;
    overSigFont: number | null;
    overSigJustifyValue: number;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: number | null;
    phantom: string;
    poNumber: string;
    processorValue: number;
    processorValueSpecified: boolean;
    processor: number | null;
    promoNumber: string;
    quantityValue: number;
    quantityValueSpecified: boolean;
    quantity: number | null;
    rerunReasonValue: number;
    rerunReasonValueSpecified: boolean;
    rerunReason: number | null;
    shipMethodValue: number;
    shipMethodValueSpecified: boolean;
    shipMethod: number | null;
    shipToValue: number;
    shipToValueSpecified: boolean;
    shipTo: number | null;
    sigFigure: string;
    startNumberValue: number;
    startNumberValueSpecified: boolean;
    startNumber: number | null;
    taxExemptCodeValue: number;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: number | null;
    titleInkColorValue: number;
    titleInkColorValueSpecified: boolean;
    titleInkColor: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}