import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CheckOrderDefaultFields {
    accentValue: boolean;
    accentValueSpecified: boolean;
    accent: boolean | null;
    acctAddrInkColorValue: boolean;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: boolean | null;
    billingCodeValue: boolean;
    billingCodeValueSpecified: boolean;
    billingCode: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    busBindingStyleValue: boolean;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: boolean | null;
    busCaptions: number[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: boolean;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: boolean | null;
    busVoucherNumberValue: boolean;
    busVoucherNumberValueSpecified: boolean;
    busVoucherNumber: boolean | null;
    businessSerialValue: boolean;
    businessSerialValueSpecified: boolean;
    businessSerial: boolean | null;
    chargeShippingValue: boolean;
    chargeShippingValueSpecified: boolean;
    chargeShipping: boolean | null;
    checkOrderProcessorValue: boolean;
    checkOrderProcessorValueSpecified: boolean;
    checkOrderProcessor: boolean | null;
    checkStyleValue: boolean;
    checkStyleValueSpecified: boolean;
    checkStyle: boolean | null;
    checkTypeValue: boolean;
    checkTypeValueSpecified: boolean;
    checkType: boolean | null;
    coverStyleValue: boolean;
    coverStyleValueSpecified: boolean;
    coverStyle: boolean | null;
    cutInkColorValue: boolean;
    cutInkColorValueSpecified: boolean;
    cutInkColor: boolean | null;
    cutNumberValue: boolean;
    cutNumberValueSpecified: boolean;
    cutNumber: boolean | null;
    imprintFontValue: boolean;
    imprintFontValueSpecified: boolean;
    imprintFont: boolean | null;
    imprintJustifyValue: boolean;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: boolean | null;
    lastOrderDateValue: boolean;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: boolean | null;
    numberSigLinesValue: boolean;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: boolean | null;
    overSigFontValue: boolean;
    overSigFontValueSpecified: boolean;
    overSigFont: boolean | null;
    overSigJustifyValue: boolean;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: boolean | null;
    phantomValue: boolean;
    phantomValueSpecified: boolean;
    phantom: boolean | null;
    poNumberValue: boolean;
    poNumberValueSpecified: boolean;
    poNumber: boolean | null;
    processorValue: boolean;
    processorValueSpecified: boolean;
    processor: boolean | null;
    promoNumberValue: boolean;
    promoNumberValueSpecified: boolean;
    promoNumber: boolean | null;
    quantityValue: boolean;
    quantityValueSpecified: boolean;
    quantity: boolean | null;
    rerunReasonValue: boolean;
    rerunReasonValueSpecified: boolean;
    rerunReason: boolean | null;
    shipMethodValue: boolean;
    shipMethodValueSpecified: boolean;
    shipMethod: boolean | null;
    shipToValue: boolean;
    shipToValueSpecified: boolean;
    shipTo: boolean | null;
    sigFigureValue: boolean;
    sigFigureValueSpecified: boolean;
    sigFigure: boolean | null;
    startNumberValue: boolean;
    startNumberValueSpecified: boolean;
    startNumber: boolean | null;
    taxExemptCodeValue: boolean;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: boolean | null;
    titleInkColorValue: boolean;
    titleInkColorValueSpecified: boolean;
    titleInkColor: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}