import { CheckPayee_2 } from "./checkPayee_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Check_2 {
    accountCode: string;
    accountNumber: string;
    amountValue: number;
    amountValueSpecified: boolean;
    amount: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    checkNumberAssignedValue: number;
    checkNumberAssignedValueSpecified: boolean;
    checkNumberAssigned: number | null;
    escheatDateValue: string | null;
    escheatDateValueSpecified: boolean;
    escheatDate: string | null;
    fmLastPurgeDateValue: string | null;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: string | null;
    globalSequenceValue: number;
    globalSequenceValueSpecified: boolean;
    globalSequence: number | null;
    globalSequenceDateValue: string | null;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: string | null;
    id: string;
    idTypeValue: number;
    idTypeValueSpecified: boolean;
    idType: number | null;
    issueDateValue: string | null;
    issueDateValueSpecified: boolean;
    issueDate: string | null;
    number: string;
    payee: CheckPayee_2[];
    payeeSpecified: boolean;
    postDateValue: string | null;
    postDateValueSpecified: boolean;
    postDate: string | null;
    reconciliationDateValue: string | null;
    reconciliationDateValueSpecified: boolean;
    reconciliationDate: string | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    reference: string;
    reference2: string;
    reference3: string;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    sourceValue: number;
    sourceValueSpecified: boolean;
    source: number | null;
    sourceGlCodeValue: number;
    sourceGlCodeValueSpecified: boolean;
    sourceGlCode: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    stopPmtDateValue: string | null;
    stopPmtDateValueSpecified: boolean;
    stopPmtDate: string | null;
    tracerNumber: string;
    voidDateValue: string | null;
    voidDateValueSpecified: boolean;
    voidDate: string | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}