import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CollateralFields {
    collateralAppStatusValue: boolean;
    collateralAppStatusValueSpecified: boolean;
    collateralAppStatus: boolean | null;
    collateralOwnerValue: boolean;
    collateralOwnerValueSpecified: boolean;
    collateralOwner: boolean | null;
    createDateValue: boolean;
    createDateValueSpecified: boolean;
    createDate: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    expireDateValue: boolean;
    expireDateValueSpecified: boolean;
    expireDate: boolean | null;
    fmLastPurgeDateValue: boolean;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    numberValue: boolean;
    numberValueSpecified: boolean;
    number: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    requiredDocumentListValue: boolean;
    requiredDocumentListValueSpecified: boolean;
    requiredDocumentList: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    userChar1Value: boolean;
    userChar1ValueSpecified: boolean;
    userChar1: boolean | null;
    userChar2Value: boolean;
    userChar2ValueSpecified: boolean;
    userChar2: boolean | null;
    userChar3Value: boolean;
    userChar3ValueSpecified: boolean;
    userChar3: boolean | null;
    userChar4Value: boolean;
    userChar4ValueSpecified: boolean;
    userChar4: boolean | null;
    userChar5Value: boolean;
    userChar5ValueSpecified: boolean;
    userChar5: boolean | null;
    userChar6Value: boolean;
    userChar6ValueSpecified: boolean;
    userChar6: boolean | null;
    valueValue: boolean;
    valueValueSpecified: boolean;
    value: boolean | null;
    valueDateValue: boolean;
    valueDateValueSpecified: boolean;
    valueDate: boolean | null;
    valueSourceValue: boolean;
    valueSourceValueSpecified: boolean;
    valueSource: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}