import { CollateralCollHoldList } from "./collateralCollHoldList";
import { CollateralDocumentList } from "./collateralDocumentList";
import { CollateralFmHistoryList } from "./collateralFmHistoryList";
import { CollateralTrackingList } from "./collateralTrackingList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Collateral {
    collateralAppStatusValue: number;
    collateralAppStatusValueSpecified: boolean;
    collateralAppStatus: number | null;
    collateralCollHoldList: CollateralCollHoldList;
    collateralDocumentList: CollateralDocumentList;
    collateralFmHistoryList: CollateralFmHistoryList;
    collateralOwner: string;
    collateralTrackingList: CollateralTrackingList;
    createDateValue: string;
    createDateValueSpecified: boolean;
    createDate: string | null;
    description: string;
    expireDateValue: string;
    expireDateValueSpecified: boolean;
    expireDate: string | null;
    fmLastPurgeDateValue: string;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: string | null;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    number: string;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    requiredDocumentList: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userChar5: string;
    userChar6: string;
    valueValue: number;
    valueValueSpecified: boolean;
    value: number | null;
    valueDateValue: string;
    valueDateValueSpecified: boolean;
    valueDate: string | null;
    valueSource: string;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}