import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CollateralDocument_2 {
    accountNumber: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    description: string;
    documentDateValue: string | null;
    documentDateValueSpecified: boolean;
    documentDate: string | null;
    excpDaysValue: number;
    excpDaysValueSpecified: boolean;
    excpDays: number | null;
    excpNoticeCountValue: number;
    excpNoticeCountValueSpecified: boolean;
    excpNoticeCount: number | null;
    excpNoticeCountCpWorkValue: number;
    excpNoticeCountCpWorkValueSpecified: boolean;
    excpNoticeCountCpWork: number | null;
    excpNoticeDateValue: string | null;
    excpNoticeDateValueSpecified: boolean;
    excpNoticeDate: string | null;
    excpNoticeOptionValue: number;
    excpNoticeOptionValueSpecified: boolean;
    excpNoticeOption: number | null;
    expireDateValue: string | null;
    expireDateValueSpecified: boolean;
    expireDate: string | null;
    lastFmDateValue: string | null;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    location: string;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    number: string;
    officerCodeValue: number;
    officerCodeValueSpecified: boolean;
    officerCode: number | null;
    receivedDateValue: string | null;
    receivedDateValueSpecified: boolean;
    receivedDate: string | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    slId: string;
    slIdTypeValue: number;
    slIdTypeValueSpecified: boolean;
    slIdType: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    statusDateValue: string | null;
    statusDateValueSpecified: boolean;
    statusDate: string | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userChar5: string;
    userChar6: string;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}