import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ConsoleFmFields {
    automaticLogoffTimeValue: boolean;
    automaticLogoffTimeValueSpecified: boolean;
    automaticLogoffTime: boolean | null;
    bellEnabledValue: boolean;
    bellEnabledValueSpecified: boolean;
    bellEnabled: boolean | null;
    blinkEnabledValue: boolean;
    blinkEnabledValueSpecified: boolean;
    blinkEnabled: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    cashDispenseMachineValue: boolean;
    cashDispenseMachineValueSpecified: boolean;
    cashDispenseMachine: boolean | null;
    cashMachineOrientationValue: boolean;
    cashMachineOrientationValueSpecified: boolean;
    cashMachineOrientation: boolean | null;
    checkValidatorTypeValue: boolean;
    checkValidatorTypeValueSpecified: boolean;
    checkValidatorType: boolean | null;
    checkValidatorUseValue: boolean;
    checkValidatorUseValueSpecified: boolean;
    checkValidatorUse: boolean | null;
    consoleNumberValue: boolean;
    consoleNumberValueSpecified: boolean;
    consoleNumber: boolean | null;
    consoleSystemFailureValue: boolean;
    consoleSystemFailureValueSpecified: boolean;
    consoleSystemFailure: boolean | null;
    dimEnabledValue: boolean;
    dimEnabledValueSpecified: boolean;
    dimEnabled: boolean | null;
    hostCufxPosterOffHost: number[];
    hostCufxPosterOffHostSpecified: boolean;
    itcPortValue: boolean;
    itcPortValueSpecified: boolean;
    itcPort: boolean | null;
    itcScannerValue: boolean;
    itcScannerValueSpecified: boolean;
    itcScanner: boolean | null;
    logonPreventionValue: boolean;
    logonPreventionValueSpecified: boolean;
    logonPrevention: boolean | null;
    micrReaderValue: boolean;
    micrReaderValueSpecified: boolean;
    micrReader: boolean | null;
    moneyOrderPrinter9: number[];
    moneyOrderPrinter9Specified: boolean;
    purposeCodeValue: boolean;
    purposeCodeValueSpecified: boolean;
    purposeCode: boolean | null;
    screenTypeValue: boolean;
    screenTypeValueSpecified: boolean;
    screenType: boolean | null;
    screenWidthValue: boolean;
    screenWidthValueSpecified: boolean;
    screenWidth: boolean | null;
    telephoneTransferDefaultValue: boolean;
    telephoneTransferDefaultValueSpecified: boolean;
    telephoneTransferDefault: boolean | null;
    totalLoanAdjustmentLimit: number[];
    totalLoanAdjustmentLimitSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}