import { CorpTransferMemo } from "./corpTransferMemo";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CorpTransfer {
    amountValue: number;
    amountValueSpecified: boolean;
    amount: number | null;
    completedByUserValue: number;
    completedByUserValueSpecified: boolean;
    completedByUser: number | null;
    completedDateValue: string;
    completedDateValueSpecified: boolean;
    completedDate: string | null;
    completedReason: string;
    completedTimeValue: number;
    completedTimeValueSpecified: boolean;
    completedTime: number | null;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    enteredByCorporateUserValue: number;
    enteredByCorporateUserValueSpecified: boolean;
    enteredByCorporateUser: number | null;
    enteredByMemberUserValue: number;
    enteredByMemberUserValueSpecified: boolean;
    enteredByMemberUser: number | null;
    enteredDateValue: string;
    enteredDateValueSpecified: boolean;
    enteredDate: string | null;
    enteredTimeValue: number;
    enteredTimeValueSpecified: boolean;
    enteredTime: number | null;
    enteredValidationMethod: string;
    fromAccount: string;
    fromGlAccount: string;
    fromId: string;
    fromIdTypeValue: number;
    fromIdTypeValueSpecified: boolean;
    fromIdType: number | null;
    globalSequenceValue: number;
    globalSequenceValueSpecified: boolean;
    globalSequence: number | null;
    globalSequenceDateValue: string;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: string | null;
    interestAmountValue: number;
    interestAmountValueSpecified: boolean;
    interestAmount: number | null;
    memo: CorpTransferMemo[];
    memoSpecified: boolean;
    noticeDateValue: string;
    noticeDateValueSpecified: boolean;
    noticeDate: string | null;
    notificationDateValue: string;
    notificationDateValueSpecified: boolean;
    notificationDate: string | null;
    notificationMethodValue: number;
    notificationMethodValueSpecified: boolean;
    notificationMethod: number | null;
    notificationStatusValue: number;
    notificationStatusValueSpecified: boolean;
    notificationStatus: number | null;
    notificationTimeValue: number;
    notificationTimeValueSpecified: boolean;
    notificationTime: number | null;
    notificationUser: string;
    originatorStatementDesc: string;
    originatorTransactionSeqValue: number;
    originatorTransactionSeqValueSpecified: boolean;
    originatorTransactionSeq: number | null;
    postDateValue: string;
    postDateValueSpecified: boolean;
    postDate: string | null;
    principalAmountValue: number;
    principalAmountValueSpecified: boolean;
    principalAmount: number | null;
    receiverStatementDesc: string;
    receiverTransactionSeqValue: number;
    receiverTransactionSeqValueSpecified: boolean;
    receiverTransactionSeq: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    toAccount: string;
    toGlAccount: string;
    toId: string;
    toIdTypeValue: number;
    toIdTypeValueSpecified: boolean;
    toIdType: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}