import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CorpTransferFields {
    amountValue: boolean;
    amountValueSpecified: boolean;
    amount: boolean | null;
    completedByUserValue: boolean;
    completedByUserValueSpecified: boolean;
    completedByUser: boolean | null;
    completedDateValue: boolean;
    completedDateValueSpecified: boolean;
    completedDate: boolean | null;
    completedReasonValue: boolean;
    completedReasonValueSpecified: boolean;
    completedReason: boolean | null;
    completedTimeValue: boolean;
    completedTimeValueSpecified: boolean;
    completedTime: boolean | null;
    effectiveDateValue: boolean;
    effectiveDateValueSpecified: boolean;
    effectiveDate: boolean | null;
    enteredByCorporateUserValue: boolean;
    enteredByCorporateUserValueSpecified: boolean;
    enteredByCorporateUser: boolean | null;
    enteredByMemberUserValue: boolean;
    enteredByMemberUserValueSpecified: boolean;
    enteredByMemberUser: boolean | null;
    enteredDateValue: boolean;
    enteredDateValueSpecified: boolean;
    enteredDate: boolean | null;
    enteredTimeValue: boolean;
    enteredTimeValueSpecified: boolean;
    enteredTime: boolean | null;
    enteredValidationMethodValue: boolean;
    enteredValidationMethodValueSpecified: boolean;
    enteredValidationMethod: boolean | null;
    fromAccountValue: boolean;
    fromAccountValueSpecified: boolean;
    fromAccount: boolean | null;
    fromGlAccountValue: boolean;
    fromGlAccountValueSpecified: boolean;
    fromGlAccount: boolean | null;
    fromIdValue: boolean;
    fromIdValueSpecified: boolean;
    fromId: boolean | null;
    fromIdTypeValue: boolean;
    fromIdTypeValueSpecified: boolean;
    fromIdType: boolean | null;
    globalSequenceValue: boolean;
    globalSequenceValueSpecified: boolean;
    globalSequence: boolean | null;
    globalSequenceDateValue: boolean;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: boolean | null;
    interestAmountValue: boolean;
    interestAmountValueSpecified: boolean;
    interestAmount: boolean | null;
    memo: number[];
    memoSpecified: boolean;
    noticeDateValue: boolean;
    noticeDateValueSpecified: boolean;
    noticeDate: boolean | null;
    notificationDateValue: boolean;
    notificationDateValueSpecified: boolean;
    notificationDate: boolean | null;
    notificationMethodValue: boolean;
    notificationMethodValueSpecified: boolean;
    notificationMethod: boolean | null;
    notificationStatusValue: boolean;
    notificationStatusValueSpecified: boolean;
    notificationStatus: boolean | null;
    notificationTimeValue: boolean;
    notificationTimeValueSpecified: boolean;
    notificationTime: boolean | null;
    notificationUserValue: boolean;
    notificationUserValueSpecified: boolean;
    notificationUser: boolean | null;
    originatorStatementDescValue: boolean;
    originatorStatementDescValueSpecified: boolean;
    originatorStatementDesc: boolean | null;
    originatorTransactionSeqValue: boolean;
    originatorTransactionSeqValueSpecified: boolean;
    originatorTransactionSeq: boolean | null;
    postDateValue: boolean;
    postDateValueSpecified: boolean;
    postDate: boolean | null;
    principalAmountValue: boolean;
    principalAmountValueSpecified: boolean;
    principalAmount: boolean | null;
    receiverStatementDescValue: boolean;
    receiverStatementDescValueSpecified: boolean;
    receiverStatementDesc: boolean | null;
    receiverTransactionSeqValue: boolean;
    receiverTransactionSeqValueSpecified: boolean;
    receiverTransactionSeq: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    toAccountValue: boolean;
    toAccountValueSpecified: boolean;
    toAccount: boolean | null;
    toGlAccountValue: boolean;
    toGlAccountValueSpecified: boolean;
    toGlAccount: boolean | null;
    toIdValue: boolean;
    toIdValueSpecified: boolean;
    toId: boolean | null;
    toIdTypeValue: boolean;
    toIdTypeValueSpecified: boolean;
    toIdType: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}