import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CredRepFields {
    accessPinValue: boolean;
    accessPinValueSpecified: boolean;
    accessPin: boolean | null;
    actionTextValue: boolean;
    actionTextValueSpecified: boolean;
    actionText: boolean | null;
    actualPaymentAmtValue: boolean;
    actualPaymentAmtValueSpecified: boolean;
    actualPaymentAmt: boolean | null;
    addrAnalysisOidValue: boolean;
    addrAnalysisOidValueSpecified: boolean;
    addrAnalysisOid: boolean | null;
    addrVerifyAcctValue: boolean;
    addrVerifyAcctValueSpecified: boolean;
    addrVerifyAcct: boolean | null;
    alias: number[];
    aliasSpecified: boolean;
    appAlteredForgedValue: boolean;
    appAlteredForgedValueSpecified: boolean;
    appAlteredForged: boolean | null;
    appearanceInconsistentValue: boolean;
    appearanceInconsistentValueSpecified: boolean;
    appearanceInconsistent: boolean | null;
    armAlertValue: boolean;
    armAlertValueSpecified: boolean;
    armAlert: boolean | null;
    associationCodeValue: boolean;
    associationCodeValueSpecified: boolean;
    associationCode: boolean | null;
    autoCapCostValue: boolean;
    autoCapCostValueSpecified: boolean;
    autoCapCost: boolean | null;
    autoDownPaymentValue: boolean;
    autoDownPaymentValueSpecified: boolean;
    autoDownPayment: boolean | null;
    autoLeaseTermValue: boolean;
    autoLeaseTermValueSpecified: boolean;
    autoLeaseTerm: boolean | null;
    autoLoanTypeValue: boolean;
    autoLoanTypeValueSpecified: boolean;
    autoLoanType: boolean | null;
    autoMakeValue: boolean;
    autoMakeValueSpecified: boolean;
    autoMake: boolean | null;
    autoModelValue: boolean;
    autoModelValueSpecified: boolean;
    autoModel: boolean | null;
    autoMoneyFactorValue: boolean;
    autoMoneyFactorValueSpecified: boolean;
    autoMoneyFactor: boolean | null;
    autoMsrpValue: boolean;
    autoMsrpValueSpecified: boolean;
    autoMsrp: boolean | null;
    autoRebateValue: boolean;
    autoRebateValueSpecified: boolean;
    autoRebate: boolean | null;
    autoResidualFactorValue: boolean;
    autoResidualFactorValueSpecified: boolean;
    autoResidualFactor: boolean | null;
    autoResidualValueValue: boolean;
    autoResidualValueValueSpecified: boolean;
    autoResidualValue: boolean | null;
    autoSalePriceValue: boolean;
    autoSalePriceValueSpecified: boolean;
    autoSalePrice: boolean | null;
    autoStatusValue: boolean;
    autoStatusValueSpecified: boolean;
    autoStatus: boolean | null;
    autoTradeAllowanceValue: boolean;
    autoTradeAllowanceValueSpecified: boolean;
    autoTradeAllowance: boolean | null;
    autoTradeBalanceValue: boolean;
    autoTradeBalanceValueSpecified: boolean;
    autoTradeBalance: boolean | null;
    autoYearValue: boolean;
    autoYearValueSpecified: boolean;
    autoYear: boolean | null;
    birthDateValue: boolean;
    birthDateValueSpecified: boolean;
    birthDate: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    bre2Relation: number[];
    bre2RelationSpecified: boolean;
    bullseyeAcctValue: boolean;
    bullseyeAcctValueSpecified: boolean;
    bullseyeAcct: boolean | null;
    bureauValue: boolean;
    bureauValueSpecified: boolean;
    bureau: boolean | null;
    bureauInfoValue: boolean;
    bureauInfoValueSpecified: boolean;
    bureauInfo: boolean | null;
    busMonthsCurrAddressValue: boolean;
    busMonthsCurrAddressValueSpecified: boolean;
    busMonthsCurrAddress: boolean | null;
    busYearsCurrAddressValue: boolean;
    busYearsCurrAddressValueSpecified: boolean;
    busYearsCurrAddress: boolean | null;
    businessCityValue: boolean;
    businessCityValueSpecified: boolean;
    businessCity: boolean | null;
    businessNameValue: boolean;
    businessNameValueSpecified: boolean;
    businessName: boolean | null;
    businessPhoneValue: boolean;
    businessPhoneValueSpecified: boolean;
    businessPhone: boolean | null;
    businessPrevCityValue: boolean;
    businessPrevCityValueSpecified: boolean;
    businessPrevCity: boolean | null;
    businessPrevStateValue: boolean;
    businessPrevStateValueSpecified: boolean;
    businessPrevState: boolean | null;
    businessPrevStreetValue: boolean;
    businessPrevStreetValueSpecified: boolean;
    businessPrevStreet: boolean | null;
    businessPrevZipValue: boolean;
    businessPrevZipValueSpecified: boolean;
    businessPrevZip: boolean | null;
    businessStateValue: boolean;
    businessStateValueSpecified: boolean;
    businessState: boolean | null;
    businessStreetValue: boolean;
    businessStreetValueSpecified: boolean;
    businessStreet: boolean | null;
    businessTypeCodeValue: boolean;
    businessTypeCodeValueSpecified: boolean;
    businessTypeCode: boolean | null;
    businessZipValue: boolean;
    businessZipValueSpecified: boolean;
    businessZip: boolean | null;
    chexAcctNumberValue: boolean;
    chexAcctNumberValueSpecified: boolean;
    chexAcctNumber: boolean | null;
    chexTransId: number[];
    chexTransIdSpecified: boolean;
    commercialCodeValue: boolean;
    commercialCodeValueSpecified: boolean;
    commercialCode: boolean | null;
    completionCodeValue: boolean;
    completionCodeValueSpecified: boolean;
    completionCode: boolean | null;
    completionDateValue: boolean;
    completionDateValueSpecified: boolean;
    completionDate: boolean | null;
    completionTimeValue: boolean;
    completionTimeValueSpecified: boolean;
    completionTime: boolean | null;
    currAddrCityValue: boolean;
    currAddrCityValueSpecified: boolean;
    currAddrCity: boolean | null;
    currAddrDirectionalValue: boolean;
    currAddrDirectionalValueSpecified: boolean;
    currAddrDirectional: boolean | null;
    currAddrHomePhoneValue: boolean;
    currAddrHomePhoneValueSpecified: boolean;
    currAddrHomePhone: boolean | null;
    currAddrHouseNumberValue: boolean;
    currAddrHouseNumberValueSpecified: boolean;
    currAddrHouseNumber: boolean | null;
    currAddrQuadrantValue: boolean;
    currAddrQuadrantValueSpecified: boolean;
    currAddrQuadrant: boolean | null;
    currAddrStateValue: boolean;
    currAddrStateValueSpecified: boolean;
    currAddrState: boolean | null;
    currAddrStreetNameValue: boolean;
    currAddrStreetNameValueSpecified: boolean;
    currAddrStreetName: boolean | null;
    currAddrStreetTypeValue: boolean;
    currAddrStreetTypeValueSpecified: boolean;
    currAddrStreetType: boolean | null;
    currAddrUnitNumberValue: boolean;
    currAddrUnitNumberValueSpecified: boolean;
    currAddrUnitNumber: boolean | null;
    currAddrUnitTypeValue: boolean;
    currAddrUnitTypeValueSpecified: boolean;
    currAddrUnitType: boolean | null;
    currAddrZipCodeValue: boolean;
    currAddrZipCodeValueSpecified: boolean;
    currAddrZipCode: boolean | null;
    dPower: number[];
    dPowerSpecified: boolean;
    dateHiredValue: boolean;
    dateHiredValueSpecified: boolean;
    dateHired: boolean | null;
    dateOccurrenceValue: boolean;
    dateOccurrenceValueSpecified: boolean;
    dateOccurrence: boolean | null;
    dateOpenedValue: boolean;
    dateOpenedValueSpecified: boolean;
    dateOpened: boolean | null;
    dateSeparatedValue: boolean;
    dateSeparatedValueSpecified: boolean;
    dateSeparated: boolean | null;
    deAppIdValue: boolean;
    deAppIdValueSpecified: boolean;
    deAppId: boolean | null;
    deProductCodeValue: boolean;
    deProductCodeValueSpecified: boolean;
    deProductCode: boolean | null;
    deRateRequestedValue: boolean;
    deRateRequestedValueSpecified: boolean;
    deRateRequested: boolean | null;
    deVehAgeValue: boolean;
    deVehAgeValueSpecified: boolean;
    deVehAge: boolean | null;
    deVehCashPriceValue: boolean;
    deVehCashPriceValueSpecified: boolean;
    deVehCashPrice: boolean | null;
    deVehDownPmtValue: boolean;
    deVehDownPmtValueSpecified: boolean;
    deVehDownPmt: boolean | null;
    deVehNewPaymentAmtValue: boolean;
    deVehNewPaymentAmtValueSpecified: boolean;
    deVehNewPaymentAmt: boolean | null;
    deVehOldPaymentAmtValue: boolean;
    deVehOldPaymentAmtValueSpecified: boolean;
    deVehOldPaymentAmt: boolean | null;
    deVehStatusValue: boolean;
    deVehStatusValueSpecified: boolean;
    deVehStatus: boolean | null;
    deVehTradeInValue: boolean;
    deVehTradeInValueSpecified: boolean;
    deVehTradeIn: boolean | null;
    decisionOverrideValue: boolean;
    decisionOverrideValueSpecified: boolean;
    decisionOverride: boolean | null;
    decode: number[];
    decodeSpecified: boolean;
    dep2Dependants: number[];
    dep2DependantsSpecified: boolean;
    depositAmtValue: boolean;
    depositAmtValueSpecified: boolean;
    depositAmt: boolean | null;
    docAlteredForgedValue: boolean;
    docAlteredForgedValueSpecified: boolean;
    docAlteredForged: boolean | null;
    ecoaInqTypeValue: boolean;
    ecoaInqTypeValueSpecified: boolean;
    ecoaInqType: boolean | null;
    empCityValue: boolean;
    empCityValueSpecified: boolean;
    empCity: boolean | null;
    empCopyValue: boolean;
    empCopyValueSpecified: boolean;
    empCopy: boolean | null;
    empHouseNumberValue: boolean;
    empHouseNumberValueSpecified: boolean;
    empHouseNumber: boolean | null;
    empNameValue: boolean;
    empNameValueSpecified: boolean;
    empName: boolean | null;
    empStateValue: boolean;
    empStateValueSpecified: boolean;
    empState: boolean | null;
    empStreetValue: boolean;
    empStreetValueSpecified: boolean;
    empStreet: boolean | null;
    empZipCodeValue: boolean;
    empZipCodeValueSpecified: boolean;
    empZipCode: boolean | null;
    endEmpDateValue: boolean;
    endEmpDateValueSpecified: boolean;
    endEmpDate: boolean | null;
    eqDecode: number[];
    eqDecodeSpecified: boolean;
    exp2Amount: number[];
    exp2AmountSpecified: boolean;
    exp2Freq: number[];
    exp2FreqSpecified: boolean;
    exp2OtherAmount: number[];
    exp2OtherAmountSpecified: boolean;
    exp2OtherFreq: number[];
    exp2OtherFreqSpecified: boolean;
    exp2ResidenceAmount: number[];
    exp2ResidenceAmountSpecified: boolean;
    exp2ResidenceFreq: number[];
    exp2ResidenceFreqSpecified: boolean;
    exp2ResidenceType: number[];
    exp2ResidenceTypeSpecified: boolean;
    expandedHistoryValue: boolean;
    expandedHistoryValueSpecified: boolean;
    expandedHistory: boolean | null;
    firstNameValue: boolean;
    firstNameValueSpecified: boolean;
    firstName: boolean | null;
    hawkIndicatorValue: boolean;
    hawkIndicatorValueSpecified: boolean;
    hawkIndicator: boolean | null;
    idNumber: number[];
    idNumberSpecified: boolean;
    idState: number[];
    idStateSpecified: boolean;
    idVerificationOidValue: boolean;
    idVerificationOidValueSpecified: boolean;
    idVerificationOid: boolean | null;
    inc2OtherAmount: number[];
    inc2OtherAmountSpecified: boolean;
    inc2OtherFreq: number[];
    inc2OtherFreqSpecified: boolean;
    inc2SalaryAmount: number[];
    inc2SalaryAmountSpecified: boolean;
    inc2SalaryFreq: number[];
    inc2SalaryFreqSpecified: boolean;
    inc2TotalAmount: number[];
    inc2TotalAmountSpecified: boolean;
    inc2TotalFreq: number[];
    inc2TotalFreqSpecified: boolean;
    includeIdVerificationValue: boolean;
    includeIdVerificationValueSpecified: boolean;
    includeIdVerification: boolean | null;
    includeNewAccountChexValue: boolean;
    includeNewAccountChexValueSpecified: boolean;
    includeNewAccountChex: boolean | null;
    includeOfacValue: boolean;
    includeOfacValueSpecified: boolean;
    includeOfac: boolean | null;
    includeQualiFileValue: boolean;
    includeQualiFileValueSpecified: boolean;
    includeQualiFile: boolean | null;
    incomeValue: boolean;
    incomeValueSpecified: boolean;
    income: boolean | null;
    infoInconsistentValue: boolean;
    infoInconsistentValueSpecified: boolean;
    infoInconsistent: boolean | null;
    inquiryIdValue: boolean;
    inquiryIdValueSpecified: boolean;
    inquiryId: boolean | null;
    inquiryTypeValue: boolean;
    inquiryTypeValueSpecified: boolean;
    inquiryType: boolean | null;
    instantUpdateAcctValue: boolean;
    instantUpdateAcctValueSpecified: boolean;
    instantUpdateAcct: boolean | null;
    internetPasswdValue: boolean;
    internetPasswdValueSpecified: boolean;
    internetPasswd: boolean | null;
    internetUserIdValue: boolean;
    internetUserIdValueSpecified: boolean;
    internetUserId: boolean | null;
    ipAddressValue: boolean;
    ipAddressValueSpecified: boolean;
    ipAddress: boolean | null;
    job2EmpPrevType: number[];
    job2EmpPrevTypeSpecified: boolean;
    job2EmpType: number[];
    job2EmpTypeSpecified: boolean;
    job2Months: number[];
    job2MonthsSpecified: boolean;
    job2PrevMonths: number[];
    job2PrevMonthsSpecified: boolean;
    job2PrevYears: number[];
    job2PrevYearsSpecified: boolean;
    job2Years: number[];
    job2YearsSpecified: boolean;
    jointFileAccessValue: boolean;
    jointFileAccessValueSpecified: boolean;
    jointFileAccess: boolean | null;
    lastNameValue: boolean;
    lastNameValueSpecified: boolean;
    lastName: boolean | null;
    loanAmountValue: boolean;
    loanAmountValueSpecified: boolean;
    loanAmount: boolean | null;
    loanAppIdValue: boolean;
    loanAppIdValueSpecified: boolean;
    loanAppId: boolean | null;
    loanTermsValue: boolean;
    loanTermsValueSpecified: boolean;
    loanTerms: boolean | null;
    loanTypeChrValue: boolean;
    loanTypeChrValueSpecified: boolean;
    loanTypeChr: boolean | null;
    loanUseValue: boolean;
    loanUseValueSpecified: boolean;
    loanUse: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    lookTypeValue: boolean;
    lookTypeValueSpecified: boolean;
    lookType: boolean | null;
    lookupBmValue: boolean;
    lookupBmValueSpecified: boolean;
    lookupBm: boolean | null;
    lookupBsmValue: boolean;
    lookupBsmValueSpecified: boolean;
    lookupBsm: boolean | null;
    lookupIndCodeValue: boolean;
    lookupIndCodeValueSpecified: boolean;
    lookupIndCode: boolean | null;
    lookupMemberCodeValue: boolean;
    lookupMemberCodeValueSpecified: boolean;
    lookupMemberCode: boolean | null;
    lookupSegmentIndValue: boolean;
    lookupSegmentIndValueSpecified: boolean;
    lookupSegmentInd: boolean | null;
    memNumPlainDescValue: boolean;
    memNumPlainDescValueSpecified: boolean;
    memNumPlainDesc: boolean | null;
    middleNameValue: boolean;
    middleNameValueSpecified: boolean;
    middleName: boolean | null;
    monthsCountInqValue: boolean;
    monthsCountInqValueSpecified: boolean;
    monthsCountInq: boolean | null;
    monthsCountMaxDqValue: boolean;
    monthsCountMaxDqValueSpecified: boolean;
    monthsCountMaxDq: boolean | null;
    multipleFileValue: boolean;
    multipleFileValueSpecified: boolean;
    multipleFile: boolean | null;
    nameSuffixValue: boolean;
    nameSuffixValueSpecified: boolean;
    nameSuffix: boolean | null;
    newMnthlyPmtValue: boolean;
    newMnthlyPmtValueSpecified: boolean;
    newMnthlyPmt: boolean | null;
    occupationValue: boolean;
    occupationValueSpecified: boolean;
    occupation: boolean | null;
    ofacInquiryValue: boolean;
    ofacInquiryValueSpecified: boolean;
    ofacInquiry: boolean | null;
    ofacOidValue: boolean;
    ofacOidValueSpecified: boolean;
    ofacOid: boolean | null;
    oldMnthlyPmtValue: boolean;
    oldMnthlyPmtValueSpecified: boolean;
    oldMnthlyPmt: boolean | null;
    operatorCodeValue: boolean;
    operatorCodeValueSpecified: boolean;
    operatorCode: boolean | null;
    optFeatureCodeValue: boolean;
    optFeatureCodeValueSpecified: boolean;
    optFeatureCode: boolean | null;
    originalCreditorValue: boolean;
    originalCreditorValueSpecified: boolean;
    originalCreditor: boolean | null;
    originatingSymValue: boolean;
    originatingSymValueSpecified: boolean;
    originatingSym: boolean | null;
    overrideValue: boolean;
    overrideValueSpecified: boolean;
    override: boolean | null;
    overrideAmountValue: boolean;
    overrideAmountValueSpecified: boolean;
    overrideAmount: boolean | null;
    overrideCatValue: boolean;
    overrideCatValueSpecified: boolean;
    overrideCat: boolean | null;
    overrideTextValue: boolean;
    overrideTextValueSpecified: boolean;
    overrideText: boolean | null;
    passwordValue: boolean;
    passwordValueSpecified: boolean;
    password: boolean | null;
    payBasisValue: boolean;
    payBasisValueSpecified: boolean;
    payBasis: boolean | null;
    phoneAppendValue: boolean;
    phoneAppendValueSpecified: boolean;
    phoneAppend: boolean | null;
    prdDecType10: number[];
    prdDecType10Specified: boolean;
    prdProductCode10: number[];
    prdProductCode10Specified: boolean;
    prevAddr1CityValue: boolean;
    prevAddr1CityValueSpecified: boolean;
    prevAddr1City: boolean | null;
    prevAddr1DirectionalValue: boolean;
    prevAddr1DirectionalValueSpecified: boolean;
    prevAddr1Directional: boolean | null;
    prevAddr1HouseNumberValue: boolean;
    prevAddr1HouseNumberValueSpecified: boolean;
    prevAddr1HouseNumber: boolean | null;
    prevAddr1QuadrantValue: boolean;
    prevAddr1QuadrantValueSpecified: boolean;
    prevAddr1Quadrant: boolean | null;
    prevAddr1StateValue: boolean;
    prevAddr1StateValueSpecified: boolean;
    prevAddr1State: boolean | null;
    prevAddr1StreetNameValue: boolean;
    prevAddr1StreetNameValueSpecified: boolean;
    prevAddr1StreetName: boolean | null;
    prevAddr1StreetTypeValue: boolean;
    prevAddr1StreetTypeValueSpecified: boolean;
    prevAddr1StreetType: boolean | null;
    prevAddr1UnitNumberValue: boolean;
    prevAddr1UnitNumberValueSpecified: boolean;
    prevAddr1UnitNumber: boolean | null;
    prevAddr1UnitTypeValue: boolean;
    prevAddr1UnitTypeValueSpecified: boolean;
    prevAddr1UnitType: boolean | null;
    prevAddr1ZipCodeValue: boolean;
    prevAddr1ZipCodeValueSpecified: boolean;
    prevAddr1ZipCode: boolean | null;
    prevAddr2CityValue: boolean;
    prevAddr2CityValueSpecified: boolean;
    prevAddr2City: boolean | null;
    prevAddr2DirectionalValue: boolean;
    prevAddr2DirectionalValueSpecified: boolean;
    prevAddr2Directional: boolean | null;
    prevAddr2HouseNumberValue: boolean;
    prevAddr2HouseNumberValueSpecified: boolean;
    prevAddr2HouseNumber: boolean | null;
    prevAddr2QuadrantValue: boolean;
    prevAddr2QuadrantValueSpecified: boolean;
    prevAddr2Quadrant: boolean | null;
    prevAddr2StateValue: boolean;
    prevAddr2StateValueSpecified: boolean;
    prevAddr2State: boolean | null;
    prevAddr2StreetNameValue: boolean;
    prevAddr2StreetNameValueSpecified: boolean;
    prevAddr2StreetName: boolean | null;
    prevAddr2StreetTypeValue: boolean;
    prevAddr2StreetTypeValueSpecified: boolean;
    prevAddr2StreetType: boolean | null;
    prevAddr2UnitNumberValue: boolean;
    prevAddr2UnitNumberValueSpecified: boolean;
    prevAddr2UnitNumber: boolean | null;
    prevAddr2UnitTypeValue: boolean;
    prevAddr2UnitTypeValueSpecified: boolean;
    prevAddr2UnitType: boolean | null;
    prevAddr2ZipCodeValue: boolean;
    prevAddr2ZipCodeValueSpecified: boolean;
    prevAddr2ZipCode: boolean | null;
    queueAfterDateValue: boolean;
    queueAfterDateValueSpecified: boolean;
    queueAfterDate: boolean | null;
    queueAfterTimeValue: boolean;
    queueAfterTimeValueSpecified: boolean;
    queueAfterTime: boolean | null;
    queueCodeValue: boolean;
    queueCodeValueSpecified: boolean;
    queueCode: boolean | null;
    recommendedActionTypeIdValue: boolean;
    recommendedActionTypeIdValueSpecified: boolean;
    recommendedActionTypeId: boolean | null;
    recordTextValue: boolean;
    recordTextValueSpecified: boolean;
    recordText: boolean | null;
    redFlagActionTypeIdValue: boolean;
    redFlagActionTypeIdValueSpecified: boolean;
    redFlagActionTypeId: boolean | null;
    redFlagAlertLogIdValue: boolean;
    redFlagAlertLogIdValueSpecified: boolean;
    redFlagAlertLogId: boolean | null;
    redFlagComments: number[];
    redFlagCommentsSpecified: boolean;
    redFlagFactIdValue: boolean;
    redFlagFactIdValueSpecified: boolean;
    redFlagFactId: boolean | null;
    redFlagStatusValue: boolean;
    redFlagStatusValueSpecified: boolean;
    redFlagStatus: boolean | null;
    refNumber3: number[];
    refNumber3Specified: boolean;
    referenceIdValue: boolean;
    referenceIdValueSpecified: boolean;
    referenceId: boolean | null;
    requestDateValue: boolean;
    requestDateValueSpecified: boolean;
    requestDate: boolean | null;
    requestNumberValue: boolean;
    requestNumberValueSpecified: boolean;
    requestNumber: boolean | null;
    requestTimeValue: boolean;
    requestTimeValueSpecified: boolean;
    requestTime: boolean | null;
    res2Months: number[];
    res2MonthsSpecified: boolean;
    res2PrevMonths: number[];
    res2PrevMonthsSpecified: boolean;
    res2PrevType: number[];
    res2PrevTypeSpecified: boolean;
    res2PrevYears: number[];
    res2PrevYearsSpecified: boolean;
    res2Type: number[];
    res2TypeSpecified: boolean;
    res2Years: number[];
    res2YearsSpecified: boolean;
    responseFormatValue: boolean;
    responseFormatValueSpecified: boolean;
    responseFormat: boolean | null;
    riskModel: number[];
    riskModelSpecified: boolean;
    rtNumberValue: boolean;
    rtNumberValueSpecified: boolean;
    rtNumber: boolean | null;
    scoreModel: number[];
    scoreModelSpecified: boolean;
    secondaryNameValue: boolean;
    secondaryNameValueSpecified: boolean;
    secondaryName: boolean | null;
    selectCheckCodeValue: boolean;
    selectCheckCodeValueSpecified: boolean;
    selectCheckCode: boolean | null;
    serviceBureauValue: boolean;
    serviceBureauValueSpecified: boolean;
    serviceBureau: boolean | null;
    sigInconsistentValue: boolean;
    sigInconsistentValueSpecified: boolean;
    sigInconsistent: boolean | null;
    sourceValue: boolean;
    sourceValueSpecified: boolean;
    source: boolean | null;
    specialCommentValue: boolean;
    specialCommentValueSpecified: boolean;
    specialComment: boolean | null;
    spouseAccessPinValue: boolean;
    spouseAccessPinValueSpecified: boolean;
    spouseAccessPin: boolean | null;
    spouseBirthDateValue: boolean;
    spouseBirthDateValueSpecified: boolean;
    spouseBirthDate: boolean | null;
    spouseEmpCityValue: boolean;
    spouseEmpCityValueSpecified: boolean;
    spouseEmpCity: boolean | null;
    spouseEmpNameValue: boolean;
    spouseEmpNameValueSpecified: boolean;
    spouseEmpName: boolean | null;
    spouseEmpStateValue: boolean;
    spouseEmpStateValueSpecified: boolean;
    spouseEmpState: boolean | null;
    spouseEmpStreetValue: boolean;
    spouseEmpStreetValueSpecified: boolean;
    spouseEmpStreet: boolean | null;
    spouseEmpZipCodeValue: boolean;
    spouseEmpZipCodeValueSpecified: boolean;
    spouseEmpZipCode: boolean | null;
    spouseEndEmpDateValue: boolean;
    spouseEndEmpDateValueSpecified: boolean;
    spouseEndEmpDate: boolean | null;
    spouseFirstValue: boolean;
    spouseFirstValueSpecified: boolean;
    spouseFirst: boolean | null;
    spouseIncomeValue: boolean;
    spouseIncomeValueSpecified: boolean;
    spouseIncome: boolean | null;
    spouseLastValue: boolean;
    spouseLastValueSpecified: boolean;
    spouseLast: boolean | null;
    spouseMiddleValue: boolean;
    spouseMiddleValueSpecified: boolean;
    spouseMiddle: boolean | null;
    spouseOccupationValue: boolean;
    spouseOccupationValueSpecified: boolean;
    spouseOccupation: boolean | null;
    spousePayBasisValue: boolean;
    spousePayBasisValueSpecified: boolean;
    spousePayBasis: boolean | null;
    spouseSecondaryNmValue: boolean;
    spouseSecondaryNmValueSpecified: boolean;
    spouseSecondaryNm: boolean | null;
    spouseSsnValue: boolean;
    spouseSsnValueSpecified: boolean;
    spouseSsn: boolean | null;
    spouseStartEmpDateValue: boolean;
    spouseStartEmpDateValueSpecified: boolean;
    spouseStartEmpDate: boolean | null;
    spouseSuffixValue: boolean;
    spouseSuffixValueSpecified: boolean;
    spouseSuffix: boolean | null;
    ssnValue: boolean;
    ssnValueSpecified: boolean;
    ssn: boolean | null;
    ssnSearch: number[];
    ssnSearchSpecified: boolean;
    ssnSearchFacsValue: boolean;
    ssnSearchFacsValueSpecified: boolean;
    ssnSearchFacs: boolean | null;
    startEmpDateValue: boolean;
    startEmpDateValueSpecified: boolean;
    startEmpDate: boolean | null;
    statusCodeValue: boolean;
    statusCodeValueSpecified: boolean;
    statusCode: boolean | null;
    strategyTypeValue: boolean;
    strategyTypeValueSpecified: boolean;
    strategyType: boolean | null;
    subscriberCodeValue: boolean;
    subscriberCodeValueSpecified: boolean;
    subscriberCode: boolean | null;
    testEnvironmentValue: boolean;
    testEnvironmentValueSpecified: boolean;
    testEnvironment: boolean | null;
    useTypeValue: boolean;
    useTypeValueSpecified: boolean;
    useType: boolean | null;
    userValue: boolean;
    userValueSpecified: boolean;
    user: boolean | null;
    userIdValue: boolean;
    userIdValueSpecified: boolean;
    userId: boolean | null;
    versionValue: boolean;
    versionValueSpecified: boolean;
    version: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}