import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CreditReportFields {
    collateralAccountType: number[];
    collateralAccountTypeSpecified: boolean;
    collateralPortfolioType: number[];
    collateralPortfolioTypeSpecified: boolean;
    creditCardBalOptionValue: boolean;
    creditCardBalOptionValueSpecified: boolean;
    creditCardBalOption: boolean | null;
    equifaxProgramIdValue: boolean;
    equifaxProgramIdValueSpecified: boolean;
    equifaxProgramId: boolean | null;
    experianProgramIdValue: boolean;
    experianProgramIdValueSpecified: boolean;
    experianProgramId: boolean | null;
    innovisProgramIdValue: boolean;
    innovisProgramIdValueSpecified: boolean;
    innovisProgramId: boolean | null;
    lastReportDateValue: boolean;
    lastReportDateValueSpecified: boolean;
    lastReportDate: boolean | null;
    nameLogicValue: boolean;
    nameLogicValueSpecified: boolean;
    nameLogic: boolean | null;
    paymentHistoryLogicValue: boolean;
    paymentHistoryLogicValueSpecified: boolean;
    paymentHistoryLogic: boolean | null;
    reportTapeFormatValue: boolean;
    reportTapeFormatValueSpecified: boolean;
    reportTapeFormat: boolean | null;
    shareAccountTypeValue: boolean;
    shareAccountTypeValueSpecified: boolean;
    shareAccountType: boolean | null;
    subscriberCodeValue: boolean;
    subscriberCodeValueSpecified: boolean;
    subscriberCode: boolean | null;
    transUnionProgramIdValue: boolean;
    transUnionProgramIdValueSpecified: boolean;
    transUnionProgramId: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}