import { CrsBureauInfo_2 } from "./crsBureauInfo_2";
import { CrsChexSystemsVersion_2 } from "./crsChexSystemsVersion_2";
import { CrsDpBureauInfo_2 } from "./crsDpBureauInfo_2";
import { CrsDpPassword_2 } from "./crsDpPassword_2";
import { CrsDpPasswordExpiration_2 } from "./crsDpPasswordExpiration_2";
import { CrsDpSubscriberCode_2 } from "./crsDpSubscriberCode_2";
import { CrsOptionalFeatureCode_2 } from "./crsOptionalFeatureCode_2";
import { CrsPassword_2 } from "./crsPassword_2";
import { CrsPasswordExpiration_2 } from "./crsPasswordExpiration_2";
import { CrsResponseFormat_2 } from "./crsResponseFormat_2";
import { CrsRiskModel_2 } from "./crsRiskModel_2";
import { CrsScoreModel_2 } from "./crsScoreModel_2";
import { CrsSubscriberCode_2 } from "./crsSubscriberCode_2";
import { CrsTestEnvironment_2 } from "./crsTestEnvironment_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Crs_2 {
    bureauInfo: CrsBureauInfo_2[];
    bureauInfoSpecified: boolean;
    chexSystemsVersion: CrsChexSystemsVersion_2[];
    chexSystemsVersionSpecified: boolean;
    defaultBureauValue: number;
    defaultBureauValueSpecified: boolean;
    defaultBureau: number | null;
    dpBureauInfo: CrsDpBureauInfo_2[];
    dpBureauInfoSpecified: boolean;
    dpPassword: CrsDpPassword_2[];
    dpPasswordSpecified: boolean;
    dpPasswordExpiration: CrsDpPasswordExpiration_2[];
    dpPasswordExpirationSpecified: boolean;
    dpSubscriberCode: CrsDpSubscriberCode_2[];
    dpSubscriberCodeSpecified: boolean;
    hawkIndicator: string;
    includeIdvReportValue: boolean;
    includeIdvReportValueSpecified: boolean;
    includeIdvReport: boolean | null;
    includeNewAccountChexReportValue: boolean;
    includeNewAccountChexReportValueSpecified: boolean;
    includeNewAccountChexReport: boolean | null;
    includeOfacReportValue: boolean;
    includeOfacReportValueSpecified: boolean;
    includeOfacReport: boolean | null;
    includeQualiFileReportValue: boolean;
    includeQualiFileReportValueSpecified: boolean;
    includeQualiFileReport: boolean | null;
    internetPassword: string;
    internetPasswordExpirationValue: string | null;
    internetPasswordExpirationValueSpecified: boolean;
    internetPasswordExpiration: string | null;
    internetUserId: string;
    ipAddress: string;
    lookType: string;
    operatorCode: string;
    optionalFeatureCode: CrsOptionalFeatureCode_2[];
    optionalFeatureCodeSpecified: boolean;
    password: CrsPassword_2[];
    passwordSpecified: boolean;
    passwordExpiration: CrsPasswordExpiration_2[];
    passwordExpirationSpecified: boolean;
    responseFormat: CrsResponseFormat_2[];
    responseFormatSpecified: boolean;
    riskModel: CrsRiskModel_2[];
    riskModelSpecified: boolean;
    scoreModel: CrsScoreModel_2[];
    scoreModelSpecified: boolean;
    serviceBureauIndicatorValue: boolean;
    serviceBureauIndicatorValueSpecified: boolean;
    serviceBureauIndicator: boolean | null;
    strategyType: string;
    subscriberCode: CrsSubscriberCode_2[];
    subscriberCodeSpecified: boolean;
    testEnvironment: CrsTestEnvironment_2[];
    testEnvironmentSpecified: boolean;
    useCrsParametersValue: boolean;
    useCrsParametersValueSpecified: boolean;
    useCrsParameters: boolean | null;
    useType: string;
    userId: string;
    xpnSelectCheckCode: string;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}