import { CrsBureauInfo_2 } from "./crsBureauInfo_2";
import { CrsChexSystemsVersion_2 } from "./crsChexSystemsVersion_2";
import { CrsDpBureauInfo_2 } from "./crsDpBureauInfo_2";
import { CrsDpPassword_2 } from "./crsDpPassword_2";
import { CrsDpPasswordExpiration_2 } from "./crsDpPasswordExpiration_2";
import { CrsDpSubscriberCode_2 } from "./crsDpSubscriberCode_2";
import { CrsOptionalFeatureCode_2 } from "./crsOptionalFeatureCode_2";
import { CrsPassword_2 } from "./crsPassword_2";
import { CrsPasswordExpiration_2 } from "./crsPasswordExpiration_2";
import { CrsResponseFormat_2 } from "./crsResponseFormat_2";
import { CrsRiskModel_2 } from "./crsRiskModel_2";
import { CrsScoreModel_2 } from "./crsScoreModel_2";
import { CrsSubscriberCode_2 } from "./crsSubscriberCode_2";
import { CrsTestEnvironment_2 } from "./crsTestEnvironment_2";
import { VersionType } from "./versionType";

export interface Crs_2 {
    bureauInfo: CrsBureauInfo_2[];
    chexSystemsVersion: CrsChexSystemsVersion_2[];
    defaultBureau: number | null;
    dpBureauInfo: CrsDpBureauInfo_2[];
    dpPassword: CrsDpPassword_2[];
    dpPasswordExpiration: CrsDpPasswordExpiration_2[];
    dpSubscriberCode: CrsDpSubscriberCode_2[];
    hawkIndicator: string;
    includeIdvReport: boolean | null;
    includeNewAccountChexReport: boolean | null;
    includeOfacReport: boolean | null;
    includeQualiFileReport: boolean | null;
    internetPassword: string;
    internetPasswordExpiration: string | null;
    internetUserId: string;
    ipAddress: string;
    lookType: string;
    operatorCode: string;
    optionalFeatureCode: CrsOptionalFeatureCode_2[];
    password: CrsPassword_2[];
    passwordExpiration: CrsPasswordExpiration_2[];
    responseFormat: CrsResponseFormat_2[];
    riskModel: CrsRiskModel_2[];
    scoreModel: CrsScoreModel_2[];
    serviceBureauIndicator: boolean | null;
    strategyType: string;
    subscriberCode: CrsSubscriberCode_2[];
    testEnvironment: CrsTestEnvironment_2[];
    useCrsParameters: boolean | null;
    useType: string;
    userId: string;
    xpnSelectCheckCode: string;
    version1: VersionType;
}