import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface CtrFields {
    ackByUserValue: boolean;
    ackByUserValueSpecified: boolean;
    ackByUser: boolean | null;
    ackDateValue: boolean;
    ackDateValueSpecified: boolean;
    ackDate: boolean | null;
    ackErrorByUserValue: boolean;
    ackErrorByUserValueSpecified: boolean;
    ackErrorByUser: boolean | null;
    ackErrorDateValue: boolean;
    ackErrorDateValueSpecified: boolean;
    ackErrorDate: boolean | null;
    approveAmendByUserValue: boolean;
    approveAmendByUserValueSpecified: boolean;
    approveAmendByUser: boolean | null;
    approveAmendDateValue: boolean;
    approveAmendDateValueSpecified: boolean;
    approveAmendDate: boolean | null;
    approveByUserValue: boolean;
    approveByUserValueSpecified: boolean;
    approveByUser: boolean | null;
    approveDateValue: boolean;
    approveDateValueSpecified: boolean;
    approveDate: boolean | null;
    approverValue: boolean;
    approverValueSpecified: boolean;
    approver: boolean | null;
    approverTitleValue: boolean;
    approverTitleValueSpecified: boolean;
    approverTitle: boolean | null;
    backFileFlagValue: boolean;
    backFileFlagValueSpecified: boolean;
    backFileFlag: boolean | null;
    batchSequenceValue: boolean;
    batchSequenceValueSpecified: boolean;
    batchSequence: boolean | null;
    branchRoutingValue: boolean;
    branchRoutingValueSpecified: boolean;
    branchRouting: boolean | null;
    cashinBillsInsertValue: boolean;
    cashinBillsInsertValueSpecified: boolean;
    cashinBillsInsert: boolean | null;
    cashinCurrWagerValue: boolean;
    cashinCurrWagerValueSpecified: boolean;
    cashinCurrWager: boolean | null;
    cashinCurrXchngValue: boolean;
    cashinCurrXchngValueSpecified: boolean;
    cashinCurrXchng: boolean | null;
    cashinDepositValue: boolean;
    cashinDepositValueSpecified: boolean;
    cashinDeposit: boolean | null;
    cashinFundsXferValue: boolean;
    cashinFundsXferValueSpecified: boolean;
    cashinFundsXfer: boolean | null;
    cashinGamingInsValue: boolean;
    cashinGamingInsValueSpecified: boolean;
    cashinGamingIns: boolean | null;
    cashinNegInsValue: boolean;
    cashinNegInsValueSpecified: boolean;
    cashinNegIns: boolean | null;
    cashinOtherValue: boolean;
    cashinOtherValueSpecified: boolean;
    cashinOther: boolean | null;
    cashinOtherDescValue: boolean;
    cashinOtherDescValueSpecified: boolean;
    cashinOtherDesc: boolean | null;
    cashinPaymentValue: boolean;
    cashinPaymentValueSpecified: boolean;
    cashinPayment: boolean | null;
    cashinPrepaidValue: boolean;
    cashinPrepaidValueSpecified: boolean;
    cashinPrepaid: boolean | null;
    cashinTotalValue: boolean;
    cashinTotalValueSpecified: boolean;
    cashinTotal: boolean | null;
    cashoutAdvOnCredValue: boolean;
    cashoutAdvOnCredValueSpecified: boolean;
    cashoutAdvOnCred: boolean | null;
    cashoutCurrXchngValue: boolean;
    cashoutCurrXchngValueSpecified: boolean;
    cashoutCurrXchng: boolean | null;
    cashoutFundsXferValue: boolean;
    cashoutFundsXferValueSpecified: boolean;
    cashoutFundsXfer: boolean | null;
    cashoutGamingInsValue: boolean;
    cashoutGamingInsValueSpecified: boolean;
    cashoutGamingIns: boolean | null;
    cashoutNegInsValue: boolean;
    cashoutNegInsValueSpecified: boolean;
    cashoutNegIns: boolean | null;
    cashoutOtherValue: boolean;
    cashoutOtherValueSpecified: boolean;
    cashoutOther: boolean | null;
    cashoutOtherDescValue: boolean;
    cashoutOtherDescValueSpecified: boolean;
    cashoutOtherDesc: boolean | null;
    cashoutPayOnWagersValue: boolean;
    cashoutPayOnWagersValueSpecified: boolean;
    cashoutPayOnWagers: boolean | null;
    cashoutPrepaidValue: boolean;
    cashoutPrepaidValueSpecified: boolean;
    cashoutPrepaid: boolean | null;
    cashoutPromoValue: boolean;
    cashoutPromoValueSpecified: boolean;
    cashoutPromo: boolean | null;
    cashoutTotalValue: boolean;
    cashoutTotalValueSpecified: boolean;
    cashoutTotal: boolean | null;
    cashoutTravelValue: boolean;
    cashoutTravelValueSpecified: boolean;
    cashoutTravel: boolean | null;
    cashoutWithdrawValue: boolean;
    cashoutWithdrawValueSpecified: boolean;
    cashoutWithdraw: boolean | null;
    contactOfficeValue: boolean;
    contactOfficeValueSpecified: boolean;
    contactOffice: boolean | null;
    contactPhoneValue: boolean;
    contactPhoneValueSpecified: boolean;
    contactPhone: boolean | null;
    contactPhoneExtValue: boolean;
    contactPhoneExtValueSpecified: boolean;
    contactPhoneExt: boolean | null;
    createByUserValue: boolean;
    createByUserValueSpecified: boolean;
    createByUser: boolean | null;
    createDateValue: boolean;
    createDateValueSpecified: boolean;
    createDate: boolean | null;
    dcNumberValue: boolean;
    dcNumberValueSpecified: boolean;
    dcNumber: boolean | null;
    exemptByUserValue: boolean;
    exemptByUserValueSpecified: boolean;
    exemptByUser: boolean | null;
    exemptDateValue: boolean;
    exemptDateValueSpecified: boolean;
    exemptDate: boolean | null;
    federalRegulatorValue: boolean;
    federalRegulatorValueSpecified: boolean;
    federalRegulator: boolean | null;
    fiIdNumberValue: boolean;
    fiIdNumberValueSpecified: boolean;
    fiIdNumber: boolean | null;
    fiIdNumberTypeValue: boolean;
    fiIdNumberTypeValueSpecified: boolean;
    fiIdNumberType: boolean | null;
    fiOtherTypeValue: boolean;
    fiOtherTypeValueSpecified: boolean;
    fiOtherType: boolean | null;
    fiTypeValue: boolean;
    fiTypeValueSpecified: boolean;
    fiType: boolean | null;
    filingDateValue: boolean;
    filingDateValueSpecified: boolean;
    filingDate: boolean | null;
    filingTypeValue: boolean;
    filingTypeValueSpecified: boolean;
    filingType: boolean | null;
    fmPurgeDateValue: boolean;
    fmPurgeDateValueSpecified: boolean;
    fmPurgeDate: boolean | null;
    incompleteByUserValue: boolean;
    incompleteByUserValueSpecified: boolean;
    incompleteByUser: boolean | null;
    incompleteDateValue: boolean;
    incompleteDateValueSpecified: boolean;
    incompleteDate: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    lastSubmitDateValue: boolean;
    lastSubmitDateValueSpecified: boolean;
    lastSubmitDate: boolean | null;
    nonReportByUserValue: boolean;
    nonReportByUserValueSpecified: boolean;
    nonReportByUser: boolean | null;
    nonReportDateValue: boolean;
    nonReportDateValueSpecified: boolean;
    nonReportDate: boolean | null;
    numberValue: boolean;
    numberValueSpecified: boolean;
    number: boolean | null;
    preparerValue: boolean;
    preparerValueSpecified: boolean;
    preparer: boolean | null;
    reSubAmendByUserValue: boolean;
    reSubAmendByUserValueSpecified: boolean;
    reSubAmendByUser: boolean | null;
    reSubAmendDateValue: boolean;
    reSubAmendDateValueSpecified: boolean;
    reSubAmendDate: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    rsnAggregateFlagValue: boolean;
    rsnAggregateFlagValueSpecified: boolean;
    rsnAggregateFlag: boolean | null;
    rsnArmCarFlagValue: boolean;
    rsnArmCarFlagValueSpecified: boolean;
    rsnArmCarFlag: boolean | null;
    rsnAtmFlagValue: boolean;
    rsnAtmFlagValueSpecified: boolean;
    rsnAtmFlag: boolean | null;
    rsnMailShipFlagValue: boolean;
    rsnMailShipFlagValueSpecified: boolean;
    rsnMailShipFlag: boolean | null;
    rsnNgtDepFlagValue: boolean;
    rsnNgtDepFlagValueSpecified: boolean;
    rsnNgtDepFlag: boolean | null;
    rsnShBrFlagValue: boolean;
    rsnShBrFlagValueSpecified: boolean;
    rsnShBrFlag: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    statusDateValue: boolean;
    statusDateValueSpecified: boolean;
    statusDate: boolean | null;
    submitByUserValue: boolean;
    submitByUserValueSpecified: boolean;
    submitByUser: boolean | null;
    submitDateValue: boolean;
    submitDateValueSpecified: boolean;
    submitDate: boolean | null;
    tccValue: boolean;
    tccValueSpecified: boolean;
    tcc: boolean | null;
    tranDateValue: boolean;
    tranDateValueSpecified: boolean;
    tranDate: boolean | null;
    tranSeqValue: boolean;
    tranSeqValueSpecified: boolean;
    tranSeq: boolean | null;
    verifyAmendByUserValue: boolean;
    verifyAmendByUserValueSpecified: boolean;
    verifyAmendByUser: boolean | null;
    verifyAmendDateValue: boolean;
    verifyAmendDateValueSpecified: boolean;
    verifyAmendDate: boolean | null;
    verifyByUserValue: boolean;
    verifyByUserValueSpecified: boolean;
    verifyByUser: boolean | null;
    verifyDateValue: boolean;
    verifyDateValueSpecified: boolean;
    verifyDate: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}