import { DealerStatementClosedDealerMessage1_2 } from "./dealerStatementClosedDealerMessage1_2";
import { DealerStatementClosedDealerMessage2_2 } from "./dealerStatementClosedDealerMessage2_2";
import { DealerStatementInstitutionAddressLine_2 } from "./dealerStatementInstitutionAddressLine_2";
import { DealerStatementMessageLine1_2 } from "./dealerStatementMessageLine1_2";
import { DealerStatementMessageLine2_2 } from "./dealerStatementMessageLine2_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface DealerStatement_2 {
    adjustments: string;
    chargebackAmount: string;
    closedDealerMessage1: DealerStatementClosedDealerMessage1_2[];
    closedDealerMessage1Specified: boolean;
    closedDealerMessage2: DealerStatementClosedDealerMessage2_2[];
    closedDealerMessage2Specified: boolean;
    dealerDormantValue: number;
    dealerDormantValueSpecified: boolean;
    dealerDormant: number | null;
    fees: string;
    formatValue: number;
    formatValueSpecified: boolean;
    format: number | null;
    holdbackAmount: string;
    inquiryLine: string;
    institutionAddressLine: DealerStatementInstitutionAddressLine_2[];
    institutionAddressLineSpecified: boolean;
    messageLine1: DealerStatementMessageLine1_2[];
    messageLine1Specified: boolean;
    messageLine2: DealerStatementMessageLine2_2[];
    messageLine2Specified: boolean;
    negativeSignOptionValue: number;
    negativeSignOptionValueSpecified: boolean;
    negativeSignOption: number | null;
    numberoftimesGeneratedValue: number;
    numberoftimesGeneratedValueSpecified: boolean;
    numberoftimesGenerated: number | null;
    printDatesinHeaderValue: boolean;
    printDatesinHeaderValueSpecified: boolean;
    printDatesinHeader: boolean | null;
    printTransactionDatesValue: boolean;
    printTransactionDatesValueSpecified: boolean;
    printTransactionDates: boolean | null;
    printTransactionDetailValue: boolean;
    printTransactionDetailValueSpecified: boolean;
    printTransactionDetail: boolean | null;
    separateClosedDealerValue: boolean;
    separateClosedDealerValueSpecified: boolean;
    separateClosedDealer: boolean | null;
    statementCutoffDateValue: string | null;
    statementCutoffDateValueSpecified: boolean;
    statementCutoffDate: string | null;
    statementDates: string;
    statementGroupList: string;
    suppressDealerNumberZerosValue: boolean;
    suppressDealerNumberZerosValueSpecified: boolean;
    suppressDealerNumberZeros: boolean | null;
    totalDealerReserve: string;
    upfrontReserve: string;
    useCommasValue: boolean;
    useCommasValueSpecified: boolean;
    useCommas: boolean | null;
    useContactNameValue: boolean;
    useContactNameValueSpecified: boolean;
    useContactName: boolean | null;
    ytdTotalPrintingValue: boolean;
    ytdTotalPrintingValueSpecified: boolean;
    ytdTotalPrinting: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}