import { DealerStatementClosedDealerMessage1 } from "./dealerStatementClosedDealerMessage1";
import { DealerStatementClosedDealerMessage2 } from "./dealerStatementClosedDealerMessage2";
import { DealerStatementInstitutionAddressLine } from "./dealerStatementInstitutionAddressLine";
import { DealerStatementMessageLine1 } from "./dealerStatementMessageLine1";
import { DealerStatementMessageLine2 } from "./dealerStatementMessageLine2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface DealerStatement {
    adjustments: string;
    chargebackAmount: string;
    closedDealerMessage1: DealerStatementClosedDealerMessage1[];
    closedDealerMessage1Specified: boolean;
    closedDealerMessage2: DealerStatementClosedDealerMessage2[];
    closedDealerMessage2Specified: boolean;
    dealerDormantValue: number;
    dealerDormantValueSpecified: boolean;
    dealerDormant: number | null;
    fees: string;
    formatValue: number;
    formatValueSpecified: boolean;
    format: number | null;
    holdbackAmount: string;
    inquiryLine: string;
    institutionAddressLine: DealerStatementInstitutionAddressLine[];
    institutionAddressLineSpecified: boolean;
    messageLine1: DealerStatementMessageLine1[];
    messageLine1Specified: boolean;
    messageLine2: DealerStatementMessageLine2[];
    messageLine2Specified: boolean;
    negativeSignOptionValue: number;
    negativeSignOptionValueSpecified: boolean;
    negativeSignOption: number | null;
    numberoftimesGeneratedValue: number;
    numberoftimesGeneratedValueSpecified: boolean;
    numberoftimesGenerated: number | null;
    printDatesinHeaderValue: boolean;
    printDatesinHeaderValueSpecified: boolean;
    printDatesinHeader: boolean | null;
    printTransactionDatesValue: boolean;
    printTransactionDatesValueSpecified: boolean;
    printTransactionDates: boolean | null;
    printTransactionDetailValue: boolean;
    printTransactionDetailValueSpecified: boolean;
    printTransactionDetail: boolean | null;
    separateClosedDealerValue: boolean;
    separateClosedDealerValueSpecified: boolean;
    separateClosedDealer: boolean | null;
    statementCutoffDateValue: string;
    statementCutoffDateValueSpecified: boolean;
    statementCutoffDate: string | null;
    statementDates: string;
    statementGroupList: string;
    suppressDealerNumberZerosValue: boolean;
    suppressDealerNumberZerosValueSpecified: boolean;
    suppressDealerNumberZeros: boolean | null;
    totalDealerReserve: string;
    upfrontReserve: string;
    useCommasValue: boolean;
    useCommasValueSpecified: boolean;
    useCommas: boolean | null;
    useContactNameValue: boolean;
    useContactNameValueSpecified: boolean;
    useContactName: boolean | null;
    ytdTotalPrintingValue: boolean;
    ytdTotalPrintingValueSpecified: boolean;
    ytdTotalPrinting: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}