import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface DivTableFields {
    balanceCutoff: number[];
    balanceCutoffSpecified: boolean;
    collectedBalMaxHoldDaysValue: boolean;
    collectedBalMaxHoldDaysValueSpecified: boolean;
    collectedBalMaxHoldDays: boolean | null;
    compoundingValue: boolean;
    compoundingValueSpecified: boolean;
    compounding: boolean | null;
    definedCodeValue: boolean;
    definedCodeValueSpecified: boolean;
    definedCode: boolean | null;
    divIndexTableOptionValue: boolean;
    divIndexTableOptionValueSpecified: boolean;
    divIndexTableOption: boolean | null;
    fillInRateMethodValue: boolean;
    fillInRateMethodValueSpecified: boolean;
    fillInRateMethod: boolean | null;
    frequencyValue: boolean;
    frequencyValueSpecified: boolean;
    frequency: boolean | null;
    incrementValue: boolean;
    incrementValueSpecified: boolean;
    increment: boolean | null;
    lrbGraceDays: number[];
    lrbGraceDaysSpecified: boolean;
    marginRate: number[];
    marginRateSpecified: boolean;
    methodValue: boolean;
    methodValueSpecified: boolean;
    method: boolean | null;
    minDailyBalanceValue: boolean;
    minDailyBalanceValueSpecified: boolean;
    minDailyBalance: boolean | null;
    minimumBalanceValue: boolean;
    minimumBalanceValueSpecified: boolean;
    minimumBalance: boolean | null;
    newAccountCodeValue: boolean;
    newAccountCodeValueSpecified: boolean;
    newAccountCode: boolean | null;
    paymentCodeValue: boolean;
    paymentCodeValueSpecified: boolean;
    paymentCode: boolean | null;
    postAverageBalanceCommentValue: boolean;
    postAverageBalanceCommentValueSpecified: boolean;
    postAverageBalanceComment: boolean | null;
    rate: number[];
    rateSpecified: boolean;
    rateSelectionValue: boolean;
    rateSelectionValueSpecified: boolean;
    rateSelection: boolean | null;
    relCodeList: number[];
    relCodeListSpecified: boolean;
    scheduleTypeValue: boolean;
    scheduleTypeValueSpecified: boolean;
    scheduleType: boolean | null;
    table: number[];
    tableSpecified: boolean;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}