import { VersionType } from "./versionType";

export interface Eft_2 {
    amountCode: number | null;
    amountYtd: number | null;
    audioId: string;
    balance: number | null;
    batchAchOrigNum: number | null;
    countYtd: number | null;
    creditLimit: number | null;
    day1: number | null;
    day2: number | null;
    deferDate: string | null;
    distributionRatio: number | null;
    dqCount: number | null;
    effectiveDate: string | null;
    expirationDate: string | null;
    federalWithholding: number | null;
    frequency: number | null;
    glCode: number | null;
    groupNumber: string;
    id: string;
    idType: number | null;
    lastTranAmount: number | null;
    lastTranDate: string | null;
    locator: number | null;
    matchCode1: number | null;
    matchCode2: number | null;
    matchCode3: number | null;
    matchCode4: number | null;
    matchCode5: number | null;
    matchCode6: number | null;
    matchId1: string;
    matchId2: string;
    matchId3: string;
    matchId4: string;
    matchId5: string;
    matchId6: string;
    nextDate: string | null;
    payee: string;
    payeeCity: string;
    payeeExtraAddress: string;
    payeeName: string;
    payeeState: string;
    payeeStreet: string;
    payeeZipCode: string;
    postAmount: number | null;
    postFreq: number | null;
    preNoteSentDate: string | null;
    recordChangeDate: string | null;
    reference: string;
    reference2: string;
    regDCode: number | null;
    specificAmount: number | null;
    standardAmount: number | null;
    stateWithholding: number | null;
    status: string;
    type: number | null;
    version1: VersionType;
}