import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface EftFields {
    amountCodeValue: boolean;
    amountCodeValueSpecified: boolean;
    amountCode: boolean | null;
    amountYtdValue: boolean;
    amountYtdValueSpecified: boolean;
    amountYtd: boolean | null;
    audioIdValue: boolean;
    audioIdValueSpecified: boolean;
    audioId: boolean | null;
    balanceValue: boolean;
    balanceValueSpecified: boolean;
    balance: boolean | null;
    batchAchOrigNumValue: boolean;
    batchAchOrigNumValueSpecified: boolean;
    batchAchOrigNum: boolean | null;
    countYtdValue: boolean;
    countYtdValueSpecified: boolean;
    countYtd: boolean | null;
    creditLimitValue: boolean;
    creditLimitValueSpecified: boolean;
    creditLimit: boolean | null;
    day1Value: boolean;
    day1ValueSpecified: boolean;
    day1: boolean | null;
    day2Value: boolean;
    day2ValueSpecified: boolean;
    day2: boolean | null;
    deferDateValue: boolean;
    deferDateValueSpecified: boolean;
    deferDate: boolean | null;
    distributionRatioValue: boolean;
    distributionRatioValueSpecified: boolean;
    distributionRatio: boolean | null;
    dqCountValue: boolean;
    dqCountValueSpecified: boolean;
    dqCount: boolean | null;
    effectiveDateValue: boolean;
    effectiveDateValueSpecified: boolean;
    effectiveDate: boolean | null;
    expirationDateValue: boolean;
    expirationDateValueSpecified: boolean;
    expirationDate: boolean | null;
    federalWithholdingValue: boolean;
    federalWithholdingValueSpecified: boolean;
    federalWithholding: boolean | null;
    frequencyValue: boolean;
    frequencyValueSpecified: boolean;
    frequency: boolean | null;
    glCodeValue: boolean;
    glCodeValueSpecified: boolean;
    glCode: boolean | null;
    groupNumberValue: boolean;
    groupNumberValueSpecified: boolean;
    groupNumber: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    idTypeValue: boolean;
    idTypeValueSpecified: boolean;
    idType: boolean | null;
    lastTranAmountValue: boolean;
    lastTranAmountValueSpecified: boolean;
    lastTranAmount: boolean | null;
    lastTranDateValue: boolean;
    lastTranDateValueSpecified: boolean;
    lastTranDate: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    matchCode1Value: boolean;
    matchCode1ValueSpecified: boolean;
    matchCode1: boolean | null;
    matchCode2Value: boolean;
    matchCode2ValueSpecified: boolean;
    matchCode2: boolean | null;
    matchCode3Value: boolean;
    matchCode3ValueSpecified: boolean;
    matchCode3: boolean | null;
    matchCode4Value: boolean;
    matchCode4ValueSpecified: boolean;
    matchCode4: boolean | null;
    matchCode5Value: boolean;
    matchCode5ValueSpecified: boolean;
    matchCode5: boolean | null;
    matchCode6Value: boolean;
    matchCode6ValueSpecified: boolean;
    matchCode6: boolean | null;
    matchId1Value: boolean;
    matchId1ValueSpecified: boolean;
    matchId1: boolean | null;
    matchId2Value: boolean;
    matchId2ValueSpecified: boolean;
    matchId2: boolean | null;
    matchId3Value: boolean;
    matchId3ValueSpecified: boolean;
    matchId3: boolean | null;
    matchId4Value: boolean;
    matchId4ValueSpecified: boolean;
    matchId4: boolean | null;
    matchId5Value: boolean;
    matchId5ValueSpecified: boolean;
    matchId5: boolean | null;
    matchId6Value: boolean;
    matchId6ValueSpecified: boolean;
    matchId6: boolean | null;
    nextDateValue: boolean;
    nextDateValueSpecified: boolean;
    nextDate: boolean | null;
    payeeValue: boolean;
    payeeValueSpecified: boolean;
    payee: boolean | null;
    payeeCityValue: boolean;
    payeeCityValueSpecified: boolean;
    payeeCity: boolean | null;
    payeeExtraAddressValue: boolean;
    payeeExtraAddressValueSpecified: boolean;
    payeeExtraAddress: boolean | null;
    payeeNameValue: boolean;
    payeeNameValueSpecified: boolean;
    payeeName: boolean | null;
    payeeStateValue: boolean;
    payeeStateValueSpecified: boolean;
    payeeState: boolean | null;
    payeeStreetValue: boolean;
    payeeStreetValueSpecified: boolean;
    payeeStreet: boolean | null;
    payeeZipCodeValue: boolean;
    payeeZipCodeValueSpecified: boolean;
    payeeZipCode: boolean | null;
    postAmountValue: boolean;
    postAmountValueSpecified: boolean;
    postAmount: boolean | null;
    postFreqValue: boolean;
    postFreqValueSpecified: boolean;
    postFreq: boolean | null;
    preNoteSentDateValue: boolean;
    preNoteSentDateValueSpecified: boolean;
    preNoteSentDate: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    referenceValue: boolean;
    referenceValueSpecified: boolean;
    reference: boolean | null;
    reference2Value: boolean;
    reference2ValueSpecified: boolean;
    reference2: boolean | null;
    regDCodeValue: boolean;
    regDCodeValueSpecified: boolean;
    regDCode: boolean | null;
    specificAmountValue: boolean;
    specificAmountValueSpecified: boolean;
    specificAmount: boolean | null;
    standardAmountValue: boolean;
    standardAmountValueSpecified: boolean;
    standardAmount: boolean | null;
    stateWithholdingValue: boolean;
    stateWithholdingValueSpecified: boolean;
    stateWithholding: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}