import { EscrowAnalysisDeficiencyGeAmount_2 } from "./escrowAnalysisDeficiencyGeAmount_2";
import { EscrowAnalysisDeficiencyGeNbrOfMonths_2 } from "./escrowAnalysisDeficiencyGeNbrOfMonths_2";
import { EscrowAnalysisDeficiencyLtAmount_2 } from "./escrowAnalysisDeficiencyLtAmount_2";
import { EscrowAnalysisDeficiencyLtNbrOfMonths_2 } from "./escrowAnalysisDeficiencyLtNbrOfMonths_2";
import { EscrowAnalysisShortageGeAmount_2 } from "./escrowAnalysisShortageGeAmount_2";
import { EscrowAnalysisShortageGeNbrOfMonths_2 } from "./escrowAnalysisShortageGeNbrOfMonths_2";
import { EscrowAnalysisShortageLtAmount_2 } from "./escrowAnalysisShortageLtAmount_2";
import { EscrowAnalysisShortageLtNbrOfMonths_2 } from "./escrowAnalysisShortageLtNbrOfMonths_2";
import { BitMap } from "./bitMap";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface EscrowAnalysis_2 {
    analysisPastDueExceptionsValue: number;
    analysisPastDueExceptionsValueSpecified: boolean;
    analysisPastDueExceptions: number | null;
    deficiencyGe1EscrwPayMthdValue: number;
    deficiencyGe1EscrwPayMthdValueSpecified: boolean;
    deficiencyGe1EscrwPayMthd: number | null;
    deficiencyGeAmount: EscrowAnalysisDeficiencyGeAmount_2[];
    deficiencyGeAmountSpecified: boolean;
    deficiencyGeNbrOfMonths: EscrowAnalysisDeficiencyGeNbrOfMonths_2[];
    deficiencyGeNbrOfMonthsSpecified: boolean;
    deficiencyLt1EscrwPayMthdValue: number;
    deficiencyLt1EscrwPayMthdValueSpecified: boolean;
    deficiencyLt1EscrwPayMthd: number | null;
    deficiencyLtAmount: EscrowAnalysisDeficiencyLtAmount_2[];
    deficiencyLtAmountSpecified: boolean;
    deficiencyLtNbrOfMonths: EscrowAnalysisDeficiencyLtNbrOfMonths_2[];
    deficiencyLtNbrOfMonthsSpecified: boolean;
    escrowOverageMinDollarAmtValue: number;
    escrowOverageMinDollarAmtValueSpecified: boolean;
    escrowOverageMinDollarAmt: number | null;
    escrowOverageMinPercentageValue: number;
    escrowOverageMinPercentageValueSpecified: boolean;
    escrowOverageMinPercentage: number | null;
    escrowOverageProcessingMthdValue: number;
    escrowOverageProcessingMthdValueSpecified: boolean;
    escrowOverageProcessingMthd: number | null;
    newPaymentRoundingValue: number;
    newPaymentRoundingValueSpecified: boolean;
    newPaymentRounding: number | null;
    paymentChangeThresholdValue: number;
    paymentChangeThresholdValueSpecified: boolean;
    paymentChangeThreshold: number | null;
    shortageGe1EscrowPayMethdValue: number;
    shortageGe1EscrowPayMethdValueSpecified: boolean;
    shortageGe1EscrowPayMethd: number | null;
    shortageGeAmount: EscrowAnalysisShortageGeAmount_2[];
    shortageGeAmountSpecified: boolean;
    shortageGeNbrOfMonths: EscrowAnalysisShortageGeNbrOfMonths_2[];
    shortageGeNbrOfMonthsSpecified: boolean;
    shortageLt1EscrowPayMethdValue: number;
    shortageLt1EscrowPayMethdValueSpecified: boolean;
    shortageLt1EscrowPayMethd: number | null;
    shortageLtAmount: EscrowAnalysisShortageLtAmount_2[];
    shortageLtAmountSpecified: boolean;
    shortageLtNbrOfMonths: EscrowAnalysisShortageLtNbrOfMonths_2[];
    shortageLtNbrOfMonthsSpecified: boolean;
    warningCodeList: BitMap;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}