import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ExcpAddendaFields {
    addendaInfo: number[];
    addendaInfoSpecified: boolean;
    addendaSeqNumValue: boolean;
    addendaSeqNumValueSpecified: boolean;
    addendaSeqNum: boolean | null;
    addendaStd: number[];
    addendaStdSpecified: boolean;
    addendaTypeValue: boolean;
    addendaTypeValueSpecified: boolean;
    addendaType: boolean | null;
    cbrAddendaInfoValue: boolean;
    cbrAddendaInfoValueSpecified: boolean;
    cbrAddendaInfo: boolean | null;
    changeCodeValue: boolean;
    changeCodeValueSpecified: boolean;
    changeCode: boolean | null;
    cityStateValue: boolean;
    cityStateValueSpecified: boolean;
    cityState: boolean | null;
    corTraceSeqValue: boolean;
    corTraceSeqValueSpecified: boolean;
    corTraceSeq: boolean | null;
    correctedDataValue: boolean;
    correctedDataValueSpecified: boolean;
    correctedData: boolean | null;
    correctedDataIatValue: boolean;
    correctedDataIatValueSpecified: boolean;
    correctedDataIat: boolean | null;
    countryPostalCodeValue: boolean;
    countryPostalCodeValueSpecified: boolean;
    countryPostalCode: boolean | null;
    dateOfBirthValue: boolean;
    dateOfBirthValueSpecified: boolean;
    dateOfBirth: boolean | null;
    dateOfDeathValue: boolean;
    dateOfDeathValueSpecified: boolean;
    dateOfDeath: boolean | null;
    detailSeqNumValue: boolean;
    detailSeqNumValueSpecified: boolean;
    detailSeqNum: boolean | null;
    dfiBranchCntryCodeValue: boolean;
    dfiBranchCntryCodeValueSpecified: boolean;
    dfiBranchCntryCode: boolean | null;
    dfiIdNumQualifierValue: boolean;
    dfiIdNumQualifierValueSpecified: boolean;
    dfiIdNumQualifier: boolean | null;
    dfiIdentValue: boolean;
    dfiIdentValueSpecified: boolean;
    dfiIdent: boolean | null;
    dfiNameValue: boolean;
    dfiNameValueSpecified: boolean;
    dfiName: boolean | null;
    dishonorAddendaInfoValue: boolean;
    dishonorAddendaInfoValueSpecified: boolean;
    dishonorAddendaInfo: boolean | null;
    dishonorReasonValue: boolean;
    dishonorReasonValueSpecified: boolean;
    dishonorReason: boolean | null;
    dishonorSettlDateValue: boolean;
    dishonorSettlDateValueSpecified: boolean;
    dishonorSettlDate: boolean | null;
    dishonorTraceValue: boolean;
    dishonorTraceValueSpecified: boolean;
    dishonorTrace: boolean | null;
    excpReasonValue: boolean;
    excpReasonValueSpecified: boolean;
    excpReason: boolean | null;
    foreignAcctNumValue: boolean;
    foreignAcctNumValueSpecified: boolean;
    foreignAcctNum: boolean | null;
    foreignPaymentValue: boolean;
    foreignPaymentValueSpecified: boolean;
    foreignPayment: boolean | null;
    foreignPaymentIatValue: boolean;
    foreignPaymentIatValueSpecified: boolean;
    foreignPaymentIat: boolean | null;
    foreignRecDfiValue: boolean;
    foreignRecDfiValueSpecified: boolean;
    foreignRecDfi: boolean | null;
    foreignTraceValue: boolean;
    foreignTraceValueSpecified: boolean;
    foreignTrace: boolean | null;
    foreignTraceIatValue: boolean;
    foreignTraceIatValueSpecified: boolean;
    foreignTraceIat: boolean | null;
    iatRetAddendaInfoValue: boolean;
    iatRetAddendaInfoValueSpecified: boolean;
    iatRetAddendaInfo: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    networkIdCodeValue: boolean;
    networkIdCodeValueSpecified: boolean;
    networkIdCode: boolean | null;
    origEntryPmtValue: boolean;
    origEntryPmtValueSpecified: boolean;
    origEntryPmt: boolean | null;
    origEntryPmtIatValue: boolean;
    origEntryPmtIatValueSpecified: boolean;
    origEntryPmtIat: boolean | null;
    origForeignPmtValue: boolean;
    origForeignPmtValueSpecified: boolean;
    origForeignPmt: boolean | null;
    origForeignRdfiValue: boolean;
    origForeignRdfiValueSpecified: boolean;
    origForeignRdfi: boolean | null;
    origSettlDateValue: boolean;
    origSettlDateValueSpecified: boolean;
    origSettlDate: boolean | null;
    originalRecDfiValue: boolean;
    originalRecDfiValueSpecified: boolean;
    originalRecDfi: boolean | null;
    originalTraceValue: boolean;
    originalTraceValueSpecified: boolean;
    originalTrace: boolean | null;
    originatorAddrValue: boolean;
    originatorAddrValueSpecified: boolean;
    originatorAddr: boolean | null;
    originatorNameValue: boolean;
    originatorNameValueSpecified: boolean;
    originatorName: boolean | null;
    pmtRelatedInfo: number[];
    pmtRelatedInfoSpecified: boolean;
    receiverAddrValue: boolean;
    receiverAddrValueSpecified: boolean;
    receiverAddr: boolean | null;
    receiverIdentValue: boolean;
    receiverIdentValueSpecified: boolean;
    receiverIdent: boolean | null;
    receivingNameValue: boolean;
    receivingNameValueSpecified: boolean;
    receivingName: boolean | null;
    recordTypeValue: boolean;
    recordTypeValueSpecified: boolean;
    recordType: boolean | null;
    returnReasonValue: boolean;
    returnReasonValueSpecified: boolean;
    returnReason: boolean | null;
    returnSettlDateValue: boolean;
    returnSettlDateValueSpecified: boolean;
    returnSettlDate: boolean | null;
    returnTraceValue: boolean;
    returnTraceValueSpecified: boolean;
    returnTrace: boolean | null;
    terminalCityValue: boolean;
    terminalCityValueSpecified: boolean;
    terminalCity: boolean | null;
    terminalIdCodeValue: boolean;
    terminalIdCodeValueSpecified: boolean;
    terminalIdCode: boolean | null;
    terminalLocationValue: boolean;
    terminalLocationValueSpecified: boolean;
    terminalLocation: boolean | null;
    terminalStateValue: boolean;
    terminalStateValueSpecified: boolean;
    terminalState: boolean | null;
    traceNumberValue: boolean;
    traceNumberValueSpecified: boolean;
    traceNumber: boolean | null;
    tranDateMmDdValue: boolean;
    tranDateMmDdValueSpecified: boolean;
    tranDateMmDd: boolean | null;
    tranDescValue: boolean;
    tranDescValueSpecified: boolean;
    tranDesc: boolean | null;
    tranSerialValue: boolean;
    tranSerialValueSpecified: boolean;
    tranSerial: boolean | null;
    tranTimeValue: boolean;
    tranTimeValueSpecified: boolean;
    tranTime: boolean | null;
    tranTypeValue: boolean;
    tranTypeValueSpecified: boolean;
    tranType: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}