import { VersionType } from "./versionType";

export interface ExcpAddendaFields {
    addendaInfo: number[];
    addendaSeqNum: boolean | null;
    addendaStd: number[];
    addendaType: boolean | null;
    cbrAddendaInfo: boolean | null;
    changeCode: boolean | null;
    cityState: boolean | null;
    corTraceSeq: boolean | null;
    correctedData: boolean | null;
    correctedDataIat: boolean | null;
    countryPostalCode: boolean | null;
    dateOfBirth: boolean | null;
    dateOfDeath: boolean | null;
    detailSeqNum: boolean | null;
    dfiBranchCntryCode: boolean | null;
    dfiIdNumQualifier: boolean | null;
    dfiIdent: boolean | null;
    dfiName: boolean | null;
    dishonorAddendaInfo: boolean | null;
    dishonorReason: boolean | null;
    dishonorSettlDate: boolean | null;
    dishonorTrace: boolean | null;
    excpReason: boolean | null;
    foreignAcctNum: boolean | null;
    foreignPayment: boolean | null;
    foreignPaymentIat: boolean | null;
    foreignRecDfi: boolean | null;
    foreignTrace: boolean | null;
    foreignTraceIat: boolean | null;
    iatRetAddendaInfo: boolean | null;
    locator: boolean | null;
    networkIdCode: boolean | null;
    origEntryPmt: boolean | null;
    origEntryPmtIat: boolean | null;
    origForeignPmt: boolean | null;
    origForeignRdfi: boolean | null;
    origSettlDate: boolean | null;
    originalRecDfi: boolean | null;
    originalTrace: boolean | null;
    originatorAddr: boolean | null;
    originatorName: boolean | null;
    pmtRelatedInfo: number[];
    receiverAddr: boolean | null;
    receiverIdent: boolean | null;
    receivingName: boolean | null;
    recordType: boolean | null;
    returnReason: boolean | null;
    returnSettlDate: boolean | null;
    returnTrace: boolean | null;
    terminalCity: boolean | null;
    terminalIdCode: boolean | null;
    terminalLocation: boolean | null;
    terminalState: boolean | null;
    traceNumber: boolean | null;
    tranDateMmDd: boolean | null;
    tranDesc: boolean | null;
    tranSerial: boolean | null;
    tranTime: boolean | null;
    tranType: boolean | null;
    type: boolean | null;
    version1: VersionType;
}