import { ExcpItemAmount } from "./excpItemAmount";
import { ExcpItemCh1 } from "./excpItemCh1";
import { ExcpItemCh10 } from "./excpItemCh10";
import { ExcpItemCh15 } from "./excpItemCh15";
import { ExcpItemCh2 } from "./excpItemCh2";
import { ExcpItemCh20 } from "./excpItemCh20";
import { ExcpItemCh3 } from "./excpItemCh3";
import { ExcpItemCh35 } from "./excpItemCh35";
import { ExcpItemCh6 } from "./excpItemCh6";
import { ExcpItemCh8 } from "./excpItemCh8";
import { ExcpItemCode } from "./excpItemCode";
import { ExcpItemDate } from "./excpItemDate";
import { ExcpItemEditRecord } from "./excpItemEditRecord";
import { ExcpAddInfoList } from "./excpAddInfoList";
import { ExcpAddendaList } from "./excpAddendaList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ExcpItem {
    achExcpReason: string;
    adjustmentCodeValue: number;
    adjustmentCodeValueSpecified: boolean;
    adjustmentCode: number | null;
    amount: ExcpItemAmount[];
    amountSpecified: boolean;
    batchAchOrigNumValue: number;
    batchAchOrigNumValueSpecified: boolean;
    batchAchOrigNum: number | null;
    batchId: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    ch1: ExcpItemCh1[];
    ch1Specified: boolean;
    ch10: ExcpItemCh10[];
    ch10Specified: boolean;
    ch15: ExcpItemCh15[];
    ch15Specified: boolean;
    ch16: string;
    ch2: ExcpItemCh2[];
    ch2Specified: boolean;
    ch20: ExcpItemCh20[];
    ch20Specified: boolean;
    ch22: string;
    ch3: ExcpItemCh3[];
    ch3Specified: boolean;
    ch30: string;
    ch35: ExcpItemCh35[];
    ch35Specified: boolean;
    ch40: string;
    ch6: ExcpItemCh6[];
    ch6Specified: boolean;
    ch8: ExcpItemCh8[];
    ch8Specified: boolean;
    code: ExcpItemCode[];
    codeSpecified: boolean;
    commentCodeValue: number;
    commentCodeValueSpecified: boolean;
    commentCode: number | null;
    date: ExcpItemDate[];
    dateSpecified: boolean;
    deathDateValue: string;
    deathDateValueSpecified: boolean;
    deathDate: string | null;
    draftNumber: string;
    editRecord: ExcpItemEditRecord[];
    editRecordSpecified: boolean;
    exceptionCodeValue: number;
    exceptionCodeValueSpecified: boolean;
    exceptionCode: number | null;
    excpAddInfoList: ExcpAddInfoList;
    excpAddendaList: ExcpAddendaList;
    excpItemAccount: string;
    excpTypeValue: number;
    excpTypeValueSpecified: boolean;
    excpType: number | null;
    extLoanAccount: string;
    foreignExcgInd: string;
    foreignExcgRef: string;
    foreignExcgRefInd: string;
    glAccount: string;
    glCategoryValue: number;
    glCategoryValueSpecified: boolean;
    glCategory: number | null;
    glCodeValue: number;
    glCodeValueSpecified: boolean;
    glCode: number | null;
    glCode1Value: number;
    glCode1ValueSpecified: boolean;
    glCode1: number | null;
    glComment: string;
    glReference: string;
    glReference1: string;
    globalSequenceValue: number;
    globalSequenceValueSpecified: boolean;
    globalSequence: number | null;
    globalSequenceDateValue: string;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: string | null;
    id: string;
    idTypeValue: number;
    idTypeValueSpecified: boolean;
    idType: number | null;
    isoDestCountry: string;
    isoDestCurrency: string;
    isoOrigCurrency: string;
    memberBranch: string;
    originatorStatus: string;
    otherActionValue: number;
    otherActionValueSpecified: boolean;
    otherAction: number | null;
    otherId: string;
    otherIdTypeValue: number;
    otherIdTypeValueSpecified: boolean;
    otherIdType: number | null;
    postExcpDescr: string;
    processorAccount: string;
    rangeNumber: string;
    reasonCodeValue: number;
    reasonCodeValueSpecified: boolean;
    reasonCode: number | null;
    regCodeValue: number;
    regCodeValueSpecified: boolean;
    regCode: number | null;
    reviewStatusValue: number;
    reviewStatusValueSpecified: boolean;
    reviewStatus: number | null;
    subTranCodeValue: number;
    subTranCodeValueSpecified: boolean;
    subTranCode: number | null;
    subTranDescr: string;
    transactionCodeValue: number;
    transactionCodeValueSpecified: boolean;
    transactionCode: number | null;
    transferAccount: string;
    transferId: string;
    transferIdTypeValue: number;
    transferIdTypeValueSpecified: boolean;
    transferIdType: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}