import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ExcpItemFields {
    achExcpReasonValue: boolean;
    achExcpReasonValueSpecified: boolean;
    achExcpReason: boolean | null;
    adjustmentCodeValue: boolean;
    adjustmentCodeValueSpecified: boolean;
    adjustmentCode: boolean | null;
    amount: number[];
    amountSpecified: boolean;
    batchAchOrigNumValue: boolean;
    batchAchOrigNumValueSpecified: boolean;
    batchAchOrigNum: boolean | null;
    batchIdValue: boolean;
    batchIdValueSpecified: boolean;
    batchId: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    ch1: number[];
    ch1Specified: boolean;
    ch10: number[];
    ch10Specified: boolean;
    ch15: number[];
    ch15Specified: boolean;
    ch16Value: boolean;
    ch16ValueSpecified: boolean;
    ch16: boolean | null;
    ch2: number[];
    ch2Specified: boolean;
    ch20: number[];
    ch20Specified: boolean;
    ch22Value: boolean;
    ch22ValueSpecified: boolean;
    ch22: boolean | null;
    ch3: number[];
    ch3Specified: boolean;
    ch30Value: boolean;
    ch30ValueSpecified: boolean;
    ch30: boolean | null;
    ch35: number[];
    ch35Specified: boolean;
    ch40Value: boolean;
    ch40ValueSpecified: boolean;
    ch40: boolean | null;
    ch6: number[];
    ch6Specified: boolean;
    ch8: number[];
    ch8Specified: boolean;
    code: number[];
    codeSpecified: boolean;
    commentCodeValue: boolean;
    commentCodeValueSpecified: boolean;
    commentCode: boolean | null;
    date: number[];
    dateSpecified: boolean;
    deathDateValue: boolean;
    deathDateValueSpecified: boolean;
    deathDate: boolean | null;
    draftNumberValue: boolean;
    draftNumberValueSpecified: boolean;
    draftNumber: boolean | null;
    editRecord: number[];
    editRecordSpecified: boolean;
    exceptionCodeValue: boolean;
    exceptionCodeValueSpecified: boolean;
    exceptionCode: boolean | null;
    excpItemAccountValue: boolean;
    excpItemAccountValueSpecified: boolean;
    excpItemAccount: boolean | null;
    excpTypeValue: boolean;
    excpTypeValueSpecified: boolean;
    excpType: boolean | null;
    extLoanAccountValue: boolean;
    extLoanAccountValueSpecified: boolean;
    extLoanAccount: boolean | null;
    foreignExcgIndValue: boolean;
    foreignExcgIndValueSpecified: boolean;
    foreignExcgInd: boolean | null;
    foreignExcgRefValue: boolean;
    foreignExcgRefValueSpecified: boolean;
    foreignExcgRef: boolean | null;
    foreignExcgRefIndValue: boolean;
    foreignExcgRefIndValueSpecified: boolean;
    foreignExcgRefInd: boolean | null;
    glAccountValue: boolean;
    glAccountValueSpecified: boolean;
    glAccount: boolean | null;
    glCategoryValue: boolean;
    glCategoryValueSpecified: boolean;
    glCategory: boolean | null;
    glCodeValue: boolean;
    glCodeValueSpecified: boolean;
    glCode: boolean | null;
    glCode1Value: boolean;
    glCode1ValueSpecified: boolean;
    glCode1: boolean | null;
    glCommentValue: boolean;
    glCommentValueSpecified: boolean;
    glComment: boolean | null;
    glReferenceValue: boolean;
    glReferenceValueSpecified: boolean;
    glReference: boolean | null;
    glReference1Value: boolean;
    glReference1ValueSpecified: boolean;
    glReference1: boolean | null;
    globalSequenceValue: boolean;
    globalSequenceValueSpecified: boolean;
    globalSequence: boolean | null;
    globalSequenceDateValue: boolean;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    idTypeValue: boolean;
    idTypeValueSpecified: boolean;
    idType: boolean | null;
    isoDestCountryValue: boolean;
    isoDestCountryValueSpecified: boolean;
    isoDestCountry: boolean | null;
    isoDestCurrencyValue: boolean;
    isoDestCurrencyValueSpecified: boolean;
    isoDestCurrency: boolean | null;
    isoOrigCurrencyValue: boolean;
    isoOrigCurrencyValueSpecified: boolean;
    isoOrigCurrency: boolean | null;
    memberBranchValue: boolean;
    memberBranchValueSpecified: boolean;
    memberBranch: boolean | null;
    originatorStatusValue: boolean;
    originatorStatusValueSpecified: boolean;
    originatorStatus: boolean | null;
    otherActionValue: boolean;
    otherActionValueSpecified: boolean;
    otherAction: boolean | null;
    otherIdValue: boolean;
    otherIdValueSpecified: boolean;
    otherId: boolean | null;
    otherIdTypeValue: boolean;
    otherIdTypeValueSpecified: boolean;
    otherIdType: boolean | null;
    postExcpDescrValue: boolean;
    postExcpDescrValueSpecified: boolean;
    postExcpDescr: boolean | null;
    processorAccountValue: boolean;
    processorAccountValueSpecified: boolean;
    processorAccount: boolean | null;
    rangeNumberValue: boolean;
    rangeNumberValueSpecified: boolean;
    rangeNumber: boolean | null;
    reasonCodeValue: boolean;
    reasonCodeValueSpecified: boolean;
    reasonCode: boolean | null;
    regCodeValue: boolean;
    regCodeValueSpecified: boolean;
    regCode: boolean | null;
    reviewStatusValue: boolean;
    reviewStatusValueSpecified: boolean;
    reviewStatus: boolean | null;
    subTranCodeValue: boolean;
    subTranCodeValueSpecified: boolean;
    subTranCode: boolean | null;
    subTranDescrValue: boolean;
    subTranDescrValueSpecified: boolean;
    subTranDescr: boolean | null;
    transactionCodeValue: boolean;
    transactionCodeValueSpecified: boolean;
    transactionCode: boolean | null;
    transferAccountValue: boolean;
    transferAccountValueSpecified: boolean;
    transferAccount: boolean | null;
    transferIdValue: boolean;
    transferIdValueSpecified: boolean;
    transferId: boolean | null;
    transferIdTypeValue: boolean;
    transferIdTypeValueSpecified: boolean;
    transferIdType: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}