import { ExternalLoanNameList } from "./externalLoanNameList";
import { ExternalLoanNoteList } from "./externalLoanNoteList";
import { ExternalLoanTrackingList } from "./externalLoanTrackingList";
import { ExternalLoanTransferList } from "./externalLoanTransferList";
import { ExternalLoanService } from "./externalLoanService";
import { ExternalLoanWarningCode } from "./externalLoanWarningCode";
import { ExternalLoanWarningExpiration } from "./externalLoanWarningExpiration";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ExternalLoan {
    accountNumber: string;
    activityDateValue: string;
    activityDateValueSpecified: boolean;
    activityDate: string | null;
    advanceValue: number;
    advanceValueSpecified: boolean;
    advance: number | null;
    availCreditValue: number;
    availCreditValueSpecified: boolean;
    availCredit: number | null;
    availableCashAdvanceValue: number;
    availableCashAdvanceValueSpecified: boolean;
    availableCashAdvance: number | null;
    balanceValue: number;
    balanceValueSpecified: boolean;
    balance: number | null;
    cashAdvanceLimitValue: number;
    cashAdvanceLimitValueSpecified: boolean;
    cashAdvanceLimit: number | null;
    closeDateValue: string;
    closeDateValueSpecified: boolean;
    closeDate: string | null;
    creditLimitValue: number;
    creditLimitValueSpecified: boolean;
    creditLimit: number | null;
    description: string;
    dueDateValue: string;
    dueDateValueSpecified: boolean;
    dueDate: string | null;
    escrowPaymentValue: number;
    escrowPaymentValueSpecified: boolean;
    escrowPayment: number | null;
    externalLoanNameList: ExternalLoanNameList;
    externalLoanNoteList: ExternalLoanNoteList;
    externalLoanTrackingList: ExternalLoanTrackingList;
    externalLoanTransferList: ExternalLoanTransferList;
    impoundPaymentValue: number;
    impoundPaymentValueSpecified: boolean;
    impoundPayment: number | null;
    lastAdvDateValue: string;
    lastAdvDateValueSpecified: boolean;
    lastAdvDate: string | null;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    lastTranDateValue: string;
    lastTranDateValueSpecified: boolean;
    lastTranDate: string | null;
    lastUpdateDateValue: string;
    lastUpdateDateValueSpecified: boolean;
    lastUpdateDate: string | null;
    lateChargeDueValue: number;
    lateChargeDueValueSpecified: boolean;
    lateChargeDue: number | null;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    nrtAvailCreditValue: number;
    nrtAvailCreditValueSpecified: boolean;
    nrtAvailCredit: number | null;
    nrtAvailableCashAdvanceValue: number;
    nrtAvailableCashAdvanceValueSpecified: boolean;
    nrtAvailableCashAdvance: number | null;
    nrtBalanceValue: number;
    nrtBalanceValueSpecified: boolean;
    nrtBalance: number | null;
    nrtCashAdvanceLimitValue: number;
    nrtCashAdvanceLimitValueSpecified: boolean;
    nrtCashAdvanceLimit: number | null;
    nrtCloseDateValue: string;
    nrtCloseDateValueSpecified: boolean;
    nrtCloseDate: string | null;
    nrtCreditLimitValue: number;
    nrtCreditLimitValueSpecified: boolean;
    nrtCreditLimit: number | null;
    nrtDueDateValue: string;
    nrtDueDateValueSpecified: boolean;
    nrtDueDate: string | null;
    nrtEscrowPaymentValue: number;
    nrtEscrowPaymentValueSpecified: boolean;
    nrtEscrowPayment: number | null;
    nrtImpoundPaymentValue: number;
    nrtImpoundPaymentValueSpecified: boolean;
    nrtImpoundPayment: number | null;
    nrtLastAdvDateValue: string;
    nrtLastAdvDateValueSpecified: boolean;
    nrtLastAdvDate: string | null;
    nrtLateChargeDueValue: number;
    nrtLateChargeDueValueSpecified: boolean;
    nrtLateChargeDue: number | null;
    nrtPaymentDueValue: number;
    nrtPaymentDueValueSpecified: boolean;
    nrtPaymentDue: number | null;
    nrtPrincIntPaymentValue: number;
    nrtPrincIntPaymentValueSpecified: boolean;
    nrtPrincIntPayment: number | null;
    nrtStatementDateValue: string;
    nrtStatementDateValueSpecified: boolean;
    nrtStatementDate: string | null;
    nrtStatementPrevDateValue: string;
    nrtStatementPrevDateValueSpecified: boolean;
    nrtStatementPrevDate: string | null;
    paymentDueValue: number;
    paymentDueValueSpecified: boolean;
    paymentDue: number | null;
    princIntPaymentValue: number;
    princIntPaymentValueSpecified: boolean;
    princIntPayment: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    service: ExternalLoanService[];
    serviceSpecified: boolean;
    statementDateValue: string;
    statementDateValueSpecified: boolean;
    statementDate: string | null;
    statementGroupValue: number;
    statementGroupValueSpecified: boolean;
    statementGroup: number | null;
    statementMailCodeValue: number;
    statementMailCodeValueSpecified: boolean;
    statementMailCode: number | null;
    statementPrevDateValue: string;
    statementPrevDateValueSpecified: boolean;
    statementPrevDate: string | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    warningCode: ExternalLoanWarningCode[];
    warningCodeSpecified: boolean;
    warningExpiration: ExternalLoanWarningExpiration[];
    warningExpirationSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}