import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ExtLoanFields {
    accountMaskValue: boolean;
    accountMaskValueSpecified: boolean;
    accountMask: boolean | null;
    activityDateUpdateValue: boolean;
    activityDateUpdateValueSpecified: boolean;
    activityDateUpdate: boolean | null;
    advanceTransactionGlCodeValue: boolean;
    advanceTransactionGlCodeValueSpecified: boolean;
    advanceTransactionGlCode: boolean | null;
    allowAdvancesValue: boolean;
    allowAdvancesValueSpecified: boolean;
    allowAdvances: boolean | null;
    allowFreezeUnfreezeofCardValue: boolean;
    allowFreezeUnfreezeofCardValueSpecified: boolean;
    allowFreezeUnfreezeofCard: boolean | null;
    allowPartialPaymentsValue: boolean;
    allowPartialPaymentsValueSpecified: boolean;
    allowPartialPayments: boolean | null;
    externalDataSourceNameValue: boolean;
    externalDataSourceNameValueSpecified: boolean;
    externalDataSourceName: boolean | null;
    externalLoanTrackingTypeValue: boolean;
    externalLoanTrackingTypeValueSpecified: boolean;
    externalLoanTrackingType: boolean | null;
    nearRealTimeRecordUpdateValue: boolean;
    nearRealTimeRecordUpdateValueSpecified: boolean;
    nearRealTimeRecordUpdate: boolean | null;
    onlineDbPasswordValue: boolean;
    onlineDbPasswordValueSpecified: boolean;
    onlineDbPassword: boolean | null;
    onlineDbUserIdValue: boolean;
    onlineDbUserIdValueSpecified: boolean;
    onlineDbUserId: boolean | null;
    onlineGlobalAppPasswdValue: boolean;
    onlineGlobalAppPasswdValueSpecified: boolean;
    onlineGlobalAppPasswd: boolean | null;
    onlineGlobalAppUserIdValue: boolean;
    onlineGlobalAppUserIdValueSpecified: boolean;
    onlineGlobalAppUserId: boolean | null;
    partialPaymentTranCodeValue: boolean;
    partialPaymentTranCodeValueSpecified: boolean;
    partialPaymentTranCode: boolean | null;
    paymentTransactionGlCodeValue: boolean;
    paymentTransactionGlCodeValueSpecified: boolean;
    paymentTransactionGlCode: boolean | null;
    processorValue: boolean;
    processorValueSpecified: boolean;
    processor: boolean | null;
    processorAbbreviationValue: boolean;
    processorAbbreviationValueSpecified: boolean;
    processorAbbreviation: boolean | null;
    processorAcctVerCodeValue: boolean;
    processorAcctVerCodeValueSpecified: boolean;
    processorAcctVerCode: boolean | null;
    processorCodeValue: boolean;
    processorCodeValueSpecified: boolean;
    processorCode: boolean | null;
    processorNameValue: boolean;
    processorNameValueSpecified: boolean;
    processorName: boolean | null;
    reportLostorStolenCardsValue: boolean;
    reportLostorStolenCardsValueSpecified: boolean;
    reportLostorStolenCards: boolean | null;
    tranCodeAdvDesc: number[];
    tranCodeAdvDescSpecified: boolean;
    tranCodeAdvance: number[];
    tranCodeAdvanceSpecified: boolean;
    tranCodePayment: number[];
    tranCodePaymentSpecified: boolean;
    tranCodePmtDesc: number[];
    tranCodePmtDescSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}