import { CollateralDocumentTrackingPagedListSelectFieldsResponse } from "./collateralDocumentTrackingPagedListSelectFieldsResponse";

export interface GetCollateralDocumentTrackingPagedListSelectFieldsResponse {
    pagedResponse: CollateralDocumentTrackingPagedListSelectFieldsResponse;
}