import { LoanBankruptcyPrepetitionBalPagedListSelectFieldsResponse } from "./loanBankruptcyPrepetitionBalPagedListSelectFieldsResponse";

export interface GetLoanBankruptcyPrepetitionBalPagedListSelectFieldsResponse {
    pagedResponse: LoanBankruptcyPrepetitionBalPagedListSelectFieldsResponse;
}