import { LoanBankruptcyPrepetitionBalPagedListSelectFieldsRequest } from "./loanBankruptcyPrepetitionBalPagedListSelectFieldsRequest";

export interface GetLoanBankruptcyPrepetitionBalPagedListSelectFields {
    request: LoanBankruptcyPrepetitionBalPagedListSelectFieldsRequest;
}