import { WireDrawdownDebitAcctAdvPagedListSelectFieldsResponse } from "./wireDrawdownDebitAcctAdvPagedListSelectFieldsResponse";

export interface GetWireDrawdownDebitAcctAdvPagedListSelectFieldsResponse {
    pagedResponse: WireDrawdownDebitAcctAdvPagedListSelectFieldsResponse;
}