import { VersionType } from "./versionType";

export interface GlAccountFields {
    balNextGlMonth: boolean | null;
    balance: boolean | null;
    balanceLastYear: boolean | null;
    balanceNextPeriod: boolean | null;
    balanceSheetColumn: boolean | null;
    balanceYtd: boolean | null;
    blankLineCode: boolean | null;
    branch: boolean | null;
    budget: number[];
    commentCode: boolean | null;
    dcRestrictionLevel: boolean | null;
    distributionCode: boolean | null;
    fmLastPurgeDate: boolean | null;
    fmLevel: boolean | null;
    formatType: boolean | null;
    historicalBalance: number[];
    indentationCode: boolean | null;
    iqLevel: boolean | null;
    lastFmDate: boolean | null;
    lastPurgeDate: boolean | null;
    lastTranDate: boolean | null;
    lookup: boolean | null;
    name: boolean | null;
    number: boolean | null;
    openCode: boolean | null;
    printingCode: boolean | null;
    recordChangeDate: boolean | null;
    restrictionLevel: boolean | null;
    subType: boolean | null;
    suffix: boolean | null;
    totalGlBudget: boolean | null;
    totalLevel: boolean | null;
    type: boolean | null;
    underscoreCode: boolean | null;
    usageType: boolean | null;
    version1: VersionType;
}