import { VersionType } from "./versionType";

export interface GlSubaccount {
    accrualAmount: number | null;
    accrualEffectDate: string | null;
    accrualPostDate: string | null;
    accrualPostThruDate: string | null;
    accrualStartDate: string | null;
    accruedAmount: number | null;
    accruedCount: number | null;
    acquisitionDate: string | null;
    commentOne: string;
    commentTwo: string;
    disposition: number | null;
    firstMonthMethod: number | null;
    glOffset: string;
    id: string;
    insMaturityDate: string | null;
    insTypeDescription: string;
    insuranceType: string;
    lastFmDate: string | null;
    maturityDate: string | null;
    method: number | null;
    name: string;
    process: number | null;
    rate: number | null;
    rateBase: number | null;
    recordChangeDate: string | null;
    saleAmount: number | null;
    saleDate: string | null;
    taxAmount: number | null;
    taxCategory: string;
    taxDate: string | null;
    taxDescription: string;
    taxLocation: string;
    termFrequency: number | null;
    termPeriod: number | null;
    type: number | null;
    version1: VersionType;
}