import { VersionType } from "./versionType";

export interface GlSubaccountFields {
    accrualAmount: boolean | null;
    accrualEffectDate: boolean | null;
    accrualPostDate: boolean | null;
    accrualPostThruDate: boolean | null;
    accrualStartDate: boolean | null;
    accruedAmount: boolean | null;
    accruedCount: boolean | null;
    acquisitionDate: boolean | null;
    commentOne: boolean | null;
    commentTwo: boolean | null;
    disposition: boolean | null;
    firstMonthMethod: boolean | null;
    glOffset: boolean | null;
    id: boolean | null;
    insMaturityDate: boolean | null;
    insTypeDescription: boolean | null;
    insuranceType: boolean | null;
    lastFmDate: boolean | null;
    maturityDate: boolean | null;
    method: boolean | null;
    name: boolean | null;
    process: boolean | null;
    rate: boolean | null;
    rateBase: boolean | null;
    recordChangeDate: boolean | null;
    saleAmount: boolean | null;
    saleDate: boolean | null;
    taxAmount: boolean | null;
    taxCategory: boolean | null;
    taxDate: boolean | null;
    taxDescription: boolean | null;
    taxLocation: boolean | null;
    termFrequency: boolean | null;
    termPeriod: boolean | null;
    type: boolean | null;
    version1: VersionType;
}