import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface InsTypeFields {
    consolidationCodeValue: boolean;
    consolidationCodeValueSpecified: boolean;
    consolidationCode: boolean | null;
    definedCodeValue: boolean;
    definedCodeValueSpecified: boolean;
    definedCode: boolean | null;
    disabilityInsuranceTableValue: boolean;
    disabilityInsuranceTableValueSpecified: boolean;
    disabilityInsuranceTable: boolean | null;
    insuranceTypeValue: boolean;
    insuranceTypeValueSpecified: boolean;
    insuranceType: boolean | null;
    lifeInsuranceTableValue: boolean;
    lifeInsuranceTableValueSpecified: boolean;
    lifeInsuranceTable: boolean | null;
    longDescriptionValue: boolean;
    longDescriptionValueSpecified: boolean;
    longDescription: boolean | null;
    maxDisDirectInsTypeValue: boolean;
    maxDisDirectInsTypeValueSpecified: boolean;
    maxDisDirectInsType: boolean | null;
    maxLifeDirectInsTypeValue: boolean;
    maxLifeDirectInsTypeValueSpecified: boolean;
    maxLifeDirectInsType: boolean | null;
    secondInsuredAsPrimeDisValue: boolean;
    secondInsuredAsPrimeDisValueSpecified: boolean;
    secondInsuredAsPrimeDis: boolean | null;
    secondInsuredAsPrimeLifeValue: boolean;
    secondInsuredAsPrimeLifeValueSpecified: boolean;
    secondInsuredAsPrimeLife: boolean | null;
    shortDescriptionValue: boolean;
    shortDescriptionValueSpecified: boolean;
    shortDescription: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}