import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface InventoryTypeFields {
    alternateDescriptionValue: boolean;
    alternateDescriptionValueSpecified: boolean;
    alternateDescription: boolean | null;
    commentCodeValue: boolean;
    commentCodeValueSpecified: boolean;
    commentCode: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    expenseGlCodeValue: boolean;
    expenseGlCodeValueSpecified: boolean;
    expenseGlCode: boolean | null;
    feeGlCodeValue: boolean;
    feeGlCodeValueSpecified: boolean;
    feeGlCode: boolean | null;
    idDefaultValue: boolean;
    idDefaultValueSpecified: boolean;
    idDefault: boolean | null;
    incomeGlCodeValue: boolean;
    incomeGlCodeValueSpecified: boolean;
    incomeGlCode: boolean | null;
    inventoryGlCodeValue: boolean;
    inventoryGlCodeValueSpecified: boolean;
    inventoryGlCode: boolean | null;
    inventoryTypeValue: boolean;
    inventoryTypeValueSpecified: boolean;
    inventoryType: boolean | null;
    multiplePromptValue: boolean;
    multiplePromptValueSpecified: boolean;
    multiplePrompt: boolean | null;
    negotiableInstrumentTrackingValue: boolean;
    negotiableInstrumentTrackingValueSpecified: boolean;
    negotiableInstrumentTracking: boolean | null;
    screenDefinitionTypeValue: boolean;
    screenDefinitionTypeValueSpecified: boolean;
    screenDefinitionType: boolean | null;
    serialNumberUsageValue: boolean;
    serialNumberUsageValueSpecified: boolean;
    serialNumberUsage: boolean | null;
    significantDigitsValue: boolean;
    significantDigitsValueSpecified: boolean;
    significantDigits: boolean | null;
    summaryCommentCodeValue: boolean;
    summaryCommentCodeValueSpecified: boolean;
    summaryCommentCode: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}