import { InvoiceCompletedActions } from "./invoiceCompletedActions";
import { InvoiceDueAmount } from "./invoiceDueAmount";
import { InvoiceDueDate } from "./invoiceDueDate";
import { InvoiceExpenseAmount } from "./invoiceExpenseAmount";
import { InvoiceExpenseTable } from "./invoiceExpenseTable";
import { InvoiceGlExpense } from "./invoiceGlExpense";
import { InvoiceGlNameExpense } from "./invoiceGlNameExpense";
import { InvoiceNoteList } from "./invoiceNoteList";
import { InvoicePaymentAmount } from "./invoicePaymentAmount";
import { InvoicePaymentCheck } from "./invoicePaymentCheck";
import { InvoicePaymentDate } from "./invoicePaymentDate";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Invoice {
    achAcknowledgeValue: number;
    achAcknowledgeValueSpecified: boolean;
    achAcknowledge: number | null;
    achGroupNumber: string;
    achTranCodeOutValue: number;
    achTranCodeOutValueSpecified: boolean;
    achTranCodeOut: number | null;
    additionalDesc: string;
    apPaymentTermsTypeValue: number;
    apPaymentTermsTypeValueSpecified: boolean;
    apPaymentTermsType: number | null;
    approval: string;
    completedActions: InvoiceCompletedActions[];
    completedActionsSpecified: boolean;
    createAddendaValue: number;
    createAddendaValueSpecified: boolean;
    createAddenda: number | null;
    description: string;
    dfiAccount: string;
    discountAmountValue: number;
    discountAmountValueSpecified: boolean;
    discountAmount: number | null;
    discountDateValue: string;
    discountDateValueSpecified: boolean;
    discountDate: string | null;
    discountTakenValue: number;
    discountTakenValueSpecified: boolean;
    discountTaken: number | null;
    dueAmount: InvoiceDueAmount[];
    dueAmountSpecified: boolean;
    dueDate: InvoiceDueDate[];
    dueDateSpecified: boolean;
    dueDateFinalValue: string;
    dueDateFinalValueSpecified: boolean;
    dueDateFinal: string | null;
    eventValue: number;
    eventValueSpecified: boolean;
    event: number | null;
    eventDateValue: string;
    eventDateValueSpecified: boolean;
    eventDate: string | null;
    expEffectiveDateValue: string;
    expEffectiveDateValueSpecified: boolean;
    expEffectiveDate: string | null;
    expPostDateValue: string;
    expPostDateValueSpecified: boolean;
    expPostDate: string | null;
    expenseAmount: InvoiceExpenseAmount[];
    expenseAmountSpecified: boolean;
    expenseTable: InvoiceExpenseTable[];
    expenseTableSpecified: boolean;
    glAcctsPay: string;
    glDiscount: string;
    glExpense: InvoiceGlExpense[];
    glExpenseSpecified: boolean;
    glNameAcctsPay: string;
    glNameDiscount: string;
    glNameExpense: InvoiceGlNameExpense[];
    glNameExpenseSpecified: boolean;
    imageId: string;
    invoiceDateValue: string;
    invoiceDateValueSpecified: boolean;
    invoiceDate: string | null;
    invoiceFrequencyValue: number;
    invoiceFrequencyValueSpecified: boolean;
    invoiceFrequency: number | null;
    invoiceNoteList: InvoiceNoteList;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    nextRecurInvoiceDateValue: string;
    nextRecurInvoiceDateValueSpecified: boolean;
    nextRecurInvoiceDate: string | null;
    number: string;
    originatingInvoiceNumber: string;
    paymentAmount: InvoicePaymentAmount[];
    paymentAmountSpecified: boolean;
    paymentCheck: InvoicePaymentCheck[];
    paymentCheckSpecified: boolean;
    paymentDate: InvoicePaymentDate[];
    paymentDateSpecified: boolean;
    paymentMethodValue: number;
    paymentMethodValueSpecified: boolean;
    paymentMethod: number | null;
    poNumber: string;
    preNoteDfiAccount: string;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    recurrenceDay1Value: number;
    recurrenceDay1ValueSpecified: boolean;
    recurrenceDay1: number | null;
    recurrenceDay2Value: number;
    recurrenceDay2ValueSpecified: boolean;
    recurrenceDay2: number | null;
    recurrenceEndDateValue: string;
    recurrenceEndDateValueSpecified: boolean;
    recurrenceEndDate: string | null;
    remainingRecurringInvoicesValue: number;
    remainingRecurringInvoicesValueSpecified: boolean;
    remainingRecurringInvoices: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    totalExpensesValue: number;
    totalExpensesValueSpecified: boolean;
    totalExpenses: number | null;
    totalInvoiceAmtDueValue: number;
    totalInvoiceAmtDueValueSpecified: boolean;
    totalInvoiceAmtDue: number | null;
    totalPaymentsValue: number;
    totalPaymentsValueSpecified: boolean;
    totalPayments: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    unpaidBalanceValue: number;
    unpaidBalanceValueSpecified: boolean;
    unpaidBalance: number | null;
    userValue: number;
    userValueSpecified: boolean;
    user: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}