import { InvoiceCompletedActions_2 } from "./invoiceCompletedActions_2";
import { InvoiceDueAmount_2 } from "./invoiceDueAmount_2";
import { InvoiceDueDate_2 } from "./invoiceDueDate_2";
import { InvoiceExpenseAmount_2 } from "./invoiceExpenseAmount_2";
import { InvoiceExpenseTable_2 } from "./invoiceExpenseTable_2";
import { InvoiceGlExpense_2 } from "./invoiceGlExpense_2";
import { InvoiceGlNameExpense_2 } from "./invoiceGlNameExpense_2";
import { InvoicePaymentAmount_2 } from "./invoicePaymentAmount_2";
import { InvoicePaymentCheck_2 } from "./invoicePaymentCheck_2";
import { InvoicePaymentDate_2 } from "./invoicePaymentDate_2";
import { VersionType } from "./versionType";

export interface Invoice_2 {
    achAcknowledge: number | null;
    achGroupNumber: string;
    achTranCodeOut: number | null;
    additionalDesc: string;
    apPaymentTermsType: number | null;
    approval: string;
    completedActions: InvoiceCompletedActions_2[];
    createAddenda: number | null;
    description: string;
    dfiAccount: string;
    discountAmount: number | null;
    discountDate: string | null;
    discountTaken: number | null;
    dueAmount: InvoiceDueAmount_2[];
    dueDate: InvoiceDueDate_2[];
    dueDateFinal: string | null;
    event: number | null;
    eventDate: string | null;
    expEffectiveDate: string | null;
    expPostDate: string | null;
    expenseAmount: InvoiceExpenseAmount_2[];
    expenseTable: InvoiceExpenseTable_2[];
    glAcctsPay: string;
    glDiscount: string;
    glExpense: InvoiceGlExpense_2[];
    glNameAcctsPay: string;
    glNameDiscount: string;
    glNameExpense: InvoiceGlNameExpense_2[];
    imageId: string;
    invoiceDate: string | null;
    invoiceFrequency: number | null;
    lastFmDate: string | null;
    locator: number | null;
    nextRecurInvoiceDate: string | null;
    number: string;
    originatingInvoiceNumber: string;
    paymentAmount: InvoicePaymentAmount_2[];
    paymentCheck: InvoicePaymentCheck_2[];
    paymentDate: InvoicePaymentDate_2[];
    paymentMethod: number | null;
    poNumber: string;
    preNoteDfiAccount: string;
    recordChangeDate: string | null;
    recurrenceDay1: number | null;
    recurrenceDay2: number | null;
    recurrenceEndDate: string | null;
    remainingRecurringInvoices: number | null;
    status: number | null;
    totalExpenses: number | null;
    totalInvoiceAmtDue: number | null;
    totalPayments: number | null;
    type: number | null;
    unpaidBalance: number | null;
    user: number | null;
    version1: VersionType;
}