import { IrsContrLastYear } from "./irsContrLastYear";
import { IrsContrThisYear } from "./irsContrThisYear";
import { IrsDistrLastYear } from "./irsDistrLastYear";
import { IrsDistrThisYear } from "./irsDistrThisYear";
import { IrsDistributionList } from "./irsDistributionList";
import { IrsNameList } from "./irsNameList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Irs {
    actualMaxContributionValue: number;
    actualMaxContributionValueSpecified: boolean;
    actualMaxContribution: number | null;
    contrLastYear: IrsContrLastYear[];
    contrLastYearSpecified: boolean;
    contrThisYear: IrsContrThisYear[];
    contrThisYearSpecified: boolean;
    contributionYearValue: number;
    contributionYearValueSpecified: boolean;
    contributionYear: number | null;
    distrLastYear: IrsDistrLastYear[];
    distrLastYearSpecified: boolean;
    distrThisYear: IrsDistrThisYear[];
    distrThisYearSpecified: boolean;
    fairMarketValueDeathValue: number;
    fairMarketValueDeathValueSpecified: boolean;
    fairMarketValueDeath: number | null;
    fairMarketValueLastYearValue: number;
    fairMarketValueLastYearValueSpecified: boolean;
    fairMarketValueLastYear: number | null;
    iraRmdValue: number;
    iraRmdValueSpecified: boolean;
    iraRmd: number | null;
    irsCodeValue: number;
    irsCodeValueSpecified: boolean;
    irsCode: number | null;
    irsDistributionList: IrsDistributionList;
    irsHolderBirthDateValue: string;
    irsHolderBirthDateValueSpecified: boolean;
    irsHolderBirthDate: string | null;
    irsHolderSpouseBirthDateValue: string;
    irsHolderSpouseBirthDateValueSpecified: boolean;
    irsHolderSpouseBirthDate: string | null;
    irsNameList: IrsNameList;
    irsPlanValue: number;
    irsPlanValueSpecified: boolean;
    irsPlan: number | null;
    lastDistribTypeValue: number;
    lastDistribTypeValueSpecified: boolean;
    lastDistribType: number | null;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    maxContributionValue: number;
    maxContributionValueSpecified: boolean;
    maxContribution: number | null;
    msaHolderCodeValue: number;
    msaHolderCodeValueSpecified: boolean;
    msaHolderCode: number | null;
    openDateValue: string;
    openDateValueSpecified: boolean;
    openDate: string | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rmdTableOptionValue: number;
    rmdTableOptionValueSpecified: boolean;
    rmdTableOption: number | null;
    ssn: string;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}