import { LoanDefaultPromoAdvanceCutoff_2 } from "./loanDefaultPromoAdvanceCutoff_2";
import { LoanDefaultPromoEffectDate_2 } from "./loanDefaultPromoEffectDate_2";
import { LoanDefaultPromoExpireDate_2 } from "./loanDefaultPromoExpireDate_2";
import { LoanDefaultPromoRate_2 } from "./loanDefaultPromoRate_2";
import { LoanDefaultPromoRateMax_2 } from "./loanDefaultPromoRateMax_2";
import { LoanDefaultPromoRateMin_2 } from "./loanDefaultPromoRateMin_2";
import { LoanDefaultPromoRateOffset_2 } from "./loanDefaultPromoRateOffset_2";
import { LoanDefaultPromoRateType_2 } from "./loanDefaultPromoRateType_2";
import { LoanDefaultPromoType_2 } from "./loanDefaultPromoType_2";
import { LoanDefaultService_2 } from "./loanDefaultService_2";
import { LoanDefaultWarningCode_2 } from "./loanDefaultWarningCode_2";
import { VersionType } from "./versionType";

export interface LoanDefault_2 {
    allowUnappliedPmt: number | null;
    amortizationSchd: number | null;
    amortizationSchdType: number | null;
    amortizationTerm: number | null;
    applyAsBilled: number | null;
    approvalCode: number | null;
    armNotice: number | null;
    availCreditCalc: number | null;
    billingDefaultDays: number | null;
    billingMethod: number | null;
    billingNotice: number | null;
    billingNoticeMin: number | null;
    btLimitMax: number | null;
    btPercent: number | null;
    caLimitMax: number | null;
    caPercent: number | null;
    callItemSchd: number | null;
    callItemSchdType: number | null;
    cancelable: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesCountCap: number | null;
    checkDigits: string;
    closeDate: string | null;
    collateralCode: number | null;
    combinedCaBtLimitMax: number | null;
    combinedCaBtPercent: number | null;
    comboLnSegmentMax: number | null;
    comboPmtOrderMeth: number | null;
    comboSeg0PmtOrder: number | null;
    corporateUserTransferCode: number | null;
    crIntTypeInd: string;
    credLimitExpiration: string | null;
    creditLimit: number | null;
    creditLimitGroup: number | null;
    creditReportingCode: number | null;
    cuTotalsUseCode: number | null;
    dealerCity: string;
    dealerCounty: string;
    dealerState: string;
    description: string;
    discountRate: number | null;
    dqCalculationMethod: number | null;
    dqNoticeNumber: number | null;
    dqNoticeType: number | null;
    dueDateAdvanceCode: number | null;
    dueDay1: number | null;
    dueDay2: number | null;
    ecoaCode: number | null;
    effectiveApr: number | null;
    exceedLevelPmtAmt: number | null;
    fasb91AlternateTerm: number | null;
    fasb91Code: number | null;
    feesChargesPostingOption: number | null;
    fixedDealerCityTaxRate: number | null;
    fixedDealerCountyTaxRate: number | null;
    fixedDealerStateTaxRate: number | null;
    fixedLesseeCityTaxRate: number | null;
    fixedLesseeCountyTaxRate: number | null;
    fixedLesseeStateTaxRate: number | null;
    glAccrualStatusOption: number | null;
    initialArmNotice: number | null;
    initialBcdSettingOption: number | null;
    insuranceMax: number | null;
    insuranceType: number | null;
    intPayoffCalc: number | null;
    interestRate: number | null;
    interestRateIndex: number | null;
    interestRateMargin: number | null;
    interestRateMarginSign: number | null;
    interestRateMax: number | null;
    interestRateMin: number | null;
    interestType: number | null;
    lateChargeType: number | null;
    leaseDispositionDate: string | null;
    leaseDispositionFee: number | null;
    leaseTerminateDate: string | null;
    leaseTerminateFee: number | null;
    lesseeCity: string;
    lesseeCounty: string;
    lesseeState: string;
    levelPaymentAmt: number | null;
    levelPrincipalAmt: number | null;
    loanCode: number | null;
    loanType: number | null;
    maxDueDateAdvancePeriod: number | null;
    memberUserTransferCode: number | null;
    mfoelId: number | null;
    minAdvance: number | null;
    minBalance: number | null;
    minimumPayment: number | null;
    newLoanDueDateCode: number | null;
    newSegCutoffDays: number | null;
    newSegCutoffOption: number | null;
    nickname: string;
    noteNumber: string;
    occupancyType: number | null;
    originalRate: number | null;
    ovlAuthFee: number | null;
    ovlOptIn: number | null;
    ovlPrevAuthFee: number | null;
    ovlStmtDisclFee: number | null;
    payment: number | null;
    paymentApplicationMethod: number | null;
    paymentCalcType: number | null;
    paymentCount: number | null;
    paymentFrequency: number | null;
    paymentMethod: number | null;
    paymentSkipStartDay: number | null;
    paymentSkips: number | null;
    paymentType: number | null;
    percentPrincipal: number | null;
    periodicCap: number | null;
    periodicFrequency: number | null;
    periodicStartDate: string | null;
    periodicStartRate: number | null;
    prepaymentPenalty: number | null;
    promoAdvanceCutoff: LoanDefaultPromoAdvanceCutoff_2[];
    promoEffectDate: LoanDefaultPromoEffectDate_2[];
    promoExpireDate: LoanDefaultPromoExpireDate_2[];
    promoRate: LoanDefaultPromoRate_2[];
    promoRateMax: LoanDefaultPromoRateMax_2[];
    promoRateMin: LoanDefaultPromoRateMin_2[];
    promoRateOffset: LoanDefaultPromoRateOffset_2[];
    promoRateType: LoanDefaultPromoRateType_2[];
    promoType: LoanDefaultPromoType_2[];
    propertyAddressType: number | null;
    purposeCode: number | null;
    putItemSchd: number | null;
    putItemSchdType: number | null;
    rateChangeCycleMonths: number | null;
    rateRoundingMethod: number | null;
    reference: string;
    refundPostCode: number | null;
    riskRate: number | null;
    roundRateTo: number | null;
    salesTaxCityIndicator: number | null;
    salesTaxCountyIndicator: number | null;
    salesTaxStateIndicator: number | null;
    securedCode: number | null;
    seg0Description: string;
    seg0LevelPrinPmt: number | null;
    seg0PaymentOrder: number | null;
    service: LoanDefaultService_2[];
    splitRate: number | null;
    splitRateBalance: number | null;
    statementGroup: number | null;
    statementMailCode: number | null;
    stmtMaxLateFee: number | null;
    stmtMaxPenaltyApr: number | null;
    studentLoanCode: number | null;
    type: number | null;
    unamortizedFees: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    variableRateIndicator: number | null;
    warningCode: LoanDefaultWarningCode_2[];
    version1: VersionType;
    investor: number | null;
    remittanceType: number | null;
    version2: VersionType;
}