import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanCheckOrderFields {
    accentValue: boolean;
    accentValueSpecified: boolean;
    accent: boolean | null;
    acctAddrInkColorValue: boolean;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: boolean | null;
    billingCodeValue: boolean;
    billingCodeValueSpecified: boolean;
    billingCode: boolean | null;
    bindingValue: boolean;
    bindingValueSpecified: boolean;
    binding: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    busBindingStyleValue: boolean;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: boolean | null;
    busCaptions: number[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: boolean;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: boolean | null;
    busVoucherNumberValue: boolean;
    busVoucherNumberValueSpecified: boolean;
    busVoucherNumber: boolean | null;
    businessSerialValue: boolean;
    businessSerialValueSpecified: boolean;
    businessSerial: boolean | null;
    chargeShippingValue: boolean;
    chargeShippingValueSpecified: boolean;
    chargeShipping: boolean | null;
    checkInitialsValue: boolean;
    checkInitialsValueSpecified: boolean;
    checkInitials: boolean | null;
    checkStyleValue: boolean;
    checkStyleValueSpecified: boolean;
    checkStyle: boolean | null;
    checkTypeValue: boolean;
    checkTypeValueSpecified: boolean;
    checkType: boolean | null;
    coverInitialsValue: boolean;
    coverInitialsValueSpecified: boolean;
    coverInitials: boolean | null;
    coverStyleValue: boolean;
    coverStyleValueSpecified: boolean;
    coverStyle: boolean | null;
    cutInkColorValue: boolean;
    cutInkColorValueSpecified: boolean;
    cutInkColor: boolean | null;
    cutNumberValue: boolean;
    cutNumberValueSpecified: boolean;
    cutNumber: boolean | null;
    designValue: boolean;
    designValueSpecified: boolean;
    design: boolean | null;
    imprintCityValue: boolean;
    imprintCityValueSpecified: boolean;
    imprintCity: boolean | null;
    imprintFontValue: boolean;
    imprintFontValueSpecified: boolean;
    imprintFont: boolean | null;
    imprintJustifyValue: boolean;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: boolean | null;
    imprintLine: number[];
    imprintLineSpecified: boolean;
    imprintLineSize: number[];
    imprintLineSizeSpecified: boolean;
    imprintPhoneValue: boolean;
    imprintPhoneValueSpecified: boolean;
    imprintPhone: boolean | null;
    imprintStateValue: boolean;
    imprintStateValueSpecified: boolean;
    imprintState: boolean | null;
    imprintUsage: number[];
    imprintUsageSpecified: boolean;
    imprintZipCodeValue: boolean;
    imprintZipCodeValueSpecified: boolean;
    imprintZipCode: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    lastFreeOrderValue: boolean;
    lastFreeOrderValueSpecified: boolean;
    lastFreeOrder: boolean | null;
    lastOrderDateValue: boolean;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: boolean | null;
    license: number[];
    licenseSpecified: boolean;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    mailAddress: number[];
    mailAddressSpecified: boolean;
    mailCityValue: boolean;
    mailCityValueSpecified: boolean;
    mailCity: boolean | null;
    mailStateValue: boolean;
    mailStateValueSpecified: boolean;
    mailState: boolean | null;
    mailZipCodeValue: boolean;
    mailZipCodeValueSpecified: boolean;
    mailZipCode: boolean | null;
    micrLineValue: boolean;
    micrLineValueSpecified: boolean;
    micrLine: boolean | null;
    numberSigLinesValue: boolean;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: boolean | null;
    openDateValue: boolean;
    openDateValueSpecified: boolean;
    openDate: boolean | null;
    overSigFontValue: boolean;
    overSigFontValueSpecified: boolean;
    overSigFont: boolean | null;
    overSigJustifyValue: boolean;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: boolean | null;
    overSigLine: number[];
    overSigLineSpecified: boolean;
    overSigLineSizeValue: boolean;
    overSigLineSizeValueSpecified: boolean;
    overSigLineSize: boolean | null;
    phantomValue: boolean;
    phantomValueSpecified: boolean;
    phantom: boolean | null;
    poNumberValue: boolean;
    poNumberValueSpecified: boolean;
    poNumber: boolean | null;
    processorValue: boolean;
    processorValueSpecified: boolean;
    processor: boolean | null;
    promoNumberValue: boolean;
    promoNumberValueSpecified: boolean;
    promoNumber: boolean | null;
    quantityValue: boolean;
    quantityValueSpecified: boolean;
    quantity: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    rerunReasonValue: boolean;
    rerunReasonValueSpecified: boolean;
    rerunReason: boolean | null;
    shipMethodValue: boolean;
    shipMethodValueSpecified: boolean;
    shipMethod: boolean | null;
    shipToValue: boolean;
    shipToValueSpecified: boolean;
    shipTo: boolean | null;
    sigFigureValue: boolean;
    sigFigureValueSpecified: boolean;
    sigFigure: boolean | null;
    specialInstr: number[];
    specialInstrSpecified: boolean;
    ssn: number[];
    ssnSpecified: boolean;
    startNumberValue: boolean;
    startNumberValueSpecified: boolean;
    startNumber: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    statusDateValue: boolean;
    statusDateValueSpecified: boolean;
    statusDate: boolean | null;
    taxExemptCodeValue: boolean;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: boolean | null;
    titleInkColorValue: boolean;
    titleInkColorValueSpecified: boolean;
    titleInkColor: boolean | null;
    userIdValue: boolean;
    userIdValueSpecified: boolean;
    userId: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}