import { LoanTransactionBalSegId } from "./loanTransactionBalSegId";
import { LoanTransactionBalSegPmtChangeDate } from "./loanTransactionBalSegPmtChangeDate";
import { LoanTransactionBalSegPrevFirstPmtDate } from "./loanTransactionBalSegPrevFirstPmtDate";
import { LoanTransactionStmtDesc } from "./loanTransactionStmtDesc";
import { VersionType } from "./versionType";

export interface LoanTransaction {
    accountNumber: string;
    actionCode: string;
    activityDate: string | null;
    adjustmentCode: number | null;
    balSegCount: number | null;
    balSegId: LoanTransactionBalSegId[];
    balSegPmtChangeDate: LoanTransactionBalSegPmtChangeDate[];
    balSegPrevFirstPmtDate: LoanTransactionBalSegPrevFirstPmtDate[];
    balanceChange: number | null;
    batchSequence: number | null;
    billedFeeAmount: number | null;
    branch: number | null;
    calcMicrRt: string;
    comment: string;
    commentCode: number | null;
    confirmationNumber: string;
    confirmationSeq: number | null;
    consoleNumber: number | null;
    description: string;
    dispositionFee: number | null;
    draftNumber: string;
    effectiveDate: string | null;
    escrowAmount: number | null;
    escrowAppliedBalChg: number | null;
    escrowUnpaidBalChg: number | null;
    feeAmount: number | null;
    feeCountBy: number | null;
    feeExmtCrtsyAmt: number | null;
    id: string;
    idType: number | null;
    intEffectDate: string | null;
    interest: number | null;
    lastTranDate: string | null;
    lateChgFieldsValid: number | null;
    lateChgUnpaidChgAmt: number | null;
    lateChgWaivedAmt: number | null;
    maturityLoanDueDate: string | null;
    memberBranch: string;
    micrAcctNum: string;
    micrRt: string;
    miscExpenseAmount: number | null;
    newBalance: number | null;
    postDate: string | null;
    postTime: number | null;
    prevAvailBalance: number | null;
    prevLateChgAccrued: number | null;
    prevLateChgDate: string | null;
    processorUser: number | null;
    recurringTran: number | null;
    regDCheckCode: number | null;
    regDTransferCode: number | null;
    regECode: number | null;
    salesTaxAmount: number | null;
    securityLevels: number | null;
    sequenceNumber: number | null;
    sourceCode: string;
    stmtDesc: LoanTransactionStmtDesc[];
    subActionCode: string;
    subSource: number | null;
    subSourceDescr: string;
    terminationFee: number | null;
    tracerNumber: string;
    tranAmount: number | null;
    transferCode: number | null;
    unappliedPartialPmtChg: number | null;
    userNumber: number | null;
    userOverride: number | null;
    voidCode: number | null;
    version1: VersionType;
}