import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanFields {
    accelerationAmtValue: boolean;
    accelerationAmtValueSpecified: boolean;
    accelerationAmt: boolean | null;
    accelerationGoodThruDateValue: boolean;
    accelerationGoodThruDateValueSpecified: boolean;
    accelerationGoodThruDate: boolean | null;
    accelerationStmtMsgCodeValue: boolean;
    accelerationStmtMsgCodeValueSpecified: boolean;
    accelerationStmtMsgCode: boolean | null;
    accrReinstatementDateValue: boolean;
    accrReinstatementDateValueSpecified: boolean;
    accrReinstatementDate: boolean | null;
    accrualStatusValue: boolean;
    accrualStatusValueSpecified: boolean;
    accrualStatus: boolean | null;
    acquisitionBalanceValue: boolean;
    acquisitionBalanceValueSpecified: boolean;
    acquisitionBalance: boolean | null;
    acquisitionDateValue: boolean;
    acquisitionDateValueSpecified: boolean;
    acquisitionDate: boolean | null;
    activityDateValue: boolean;
    activityDateValueSpecified: boolean;
    activityDate: boolean | null;
    advanceAmountValue: boolean;
    advanceAmountValueSpecified: boolean;
    advanceAmount: boolean | null;
    agencyAcctNumberValue: boolean;
    agencyAcctNumberValueSpecified: boolean;
    agencyAcctNumber: boolean | null;
    agencyIdentifierValue: boolean;
    agencyIdentifierValueSpecified: boolean;
    agencyIdentifier: boolean | null;
    allowUnappliedPmtValue: boolean;
    allowUnappliedPmtValueSpecified: boolean;
    allowUnappliedPmt: boolean | null;
    altPmtEffectiveValue: boolean;
    altPmtEffectiveValueSpecified: boolean;
    altPmtEffective: boolean | null;
    altPmtExpirationValue: boolean;
    altPmtExpirationValueSpecified: boolean;
    altPmtExpiration: boolean | null;
    alternateAddress: number[];
    alternateAddressSpecified: boolean;
    alternateNameLocatorValue: boolean;
    alternateNameLocatorValueSpecified: boolean;
    alternateNameLocator: boolean | null;
    alternateNameTypeValue: boolean;
    alternateNameTypeValueSpecified: boolean;
    alternateNameType: boolean | null;
    alternatePaymentValue: boolean;
    alternatePaymentValueSpecified: boolean;
    alternatePayment: boolean | null;
    alternatePhone: number[];
    alternatePhoneSpecified: boolean;
    amortizationSchdValue: boolean;
    amortizationSchdValueSpecified: boolean;
    amortizationSchd: boolean | null;
    amortizationSchdTypeValue: boolean;
    amortizationSchdTypeValueSpecified: boolean;
    amortizationSchdType: boolean | null;
    amortizationTermValue: boolean;
    amortizationTermValueSpecified: boolean;
    amortizationTerm: boolean | null;
    applicationIdValue: boolean;
    applicationIdValueSpecified: boolean;
    applicationId: boolean | null;
    applyAsBilledValue: boolean;
    applyAsBilledValueSpecified: boolean;
    applyAsBilled: boolean | null;
    approvalCodeValue: boolean;
    approvalCodeValueSpecified: boolean;
    approvalCode: boolean | null;
    approvalDateValue: boolean;
    approvalDateValueSpecified: boolean;
    approvalDate: boolean | null;
    aprValue: boolean;
    aprValueSpecified: boolean;
    apr: boolean | null;
    armNoticeValue: boolean;
    armNoticeValueSpecified: boolean;
    armNotice: boolean | null;
    assessorParcelNumberValue: boolean;
    assessorParcelNumberValueSpecified: boolean;
    assessorParcelNumber: boolean | null;
    availCreditCalcValue: boolean;
    availCreditCalcValueSpecified: boolean;
    availCreditCalc: boolean | null;
    availableBalanceTransferValue: boolean;
    availableBalanceTransferValueSpecified: boolean;
    availableBalanceTransfer: boolean | null;
    availableCashAdvanceValue: boolean;
    availableCashAdvanceValueSpecified: boolean;
    availableCashAdvance: boolean | null;
    availableCombinedCabtValue: boolean;
    availableCombinedCabtValueSpecified: boolean;
    availableCombinedCabt: boolean | null;
    availableCreditValue: boolean;
    availableCreditValueSpecified: boolean;
    availableCredit: boolean | null;
    avgWeightedIntRateValue: boolean;
    avgWeightedIntRateValueSpecified: boolean;
    avgWeightedIntRate: boolean | null;
    balXfrAvgBalance: number[];
    balXfrAvgBalanceSpecified: boolean;
    balXfrNewBalance: number[];
    balXfrNewBalanceSpecified: boolean;
    balXfrOldBalance: number[];
    balXfrOldBalanceSpecified: boolean;
    balanceValue: boolean;
    balanceValueSpecified: boolean;
    balance: boolean | null;
    balanceTransferLimitValue: boolean;
    balanceTransferLimitValueSpecified: boolean;
    balanceTransferLimit: boolean | null;
    balloonAmountValue: boolean;
    balloonAmountValueSpecified: boolean;
    balloonAmount: boolean | null;
    balloonDateValue: boolean;
    balloonDateValueSpecified: boolean;
    balloonDate: boolean | null;
    bcdDay1Value: boolean;
    bcdDay1ValueSpecified: boolean;
    bcdDay1: boolean | null;
    bcdDay2Value: boolean;
    bcdDay2ValueSpecified: boolean;
    bcdDay2: boolean | null;
    beginningCycleDateValue: boolean;
    beginningCycleDateValueSpecified: boolean;
    beginningCycleDate: boolean | null;
    beginningYearBalanceValue: boolean;
    beginningYearBalanceValueSpecified: boolean;
    beginningYearBalance: boolean | null;
    billedFeeBucketAmount: number[];
    billedFeeBucketAmountSpecified: boolean;
    billedFeeLastYearValue: boolean;
    billedFeeLastYearValueSpecified: boolean;
    billedFeeLastYear: boolean | null;
    billedFeeLstYrNoAdjValue: boolean;
    billedFeeLstYrNoAdjValueSpecified: boolean;
    billedFeeLstYrNoAdj: boolean | null;
    billedFeeUnpaidValue: boolean;
    billedFeeUnpaidValueSpecified: boolean;
    billedFeeUnpaid: boolean | null;
    billedFeeYtdValue: boolean;
    billedFeeYtdValueSpecified: boolean;
    billedFeeYtd: boolean | null;
    billedFeeYtdNoAdjValue: boolean;
    billedFeeYtdNoAdjValueSpecified: boolean;
    billedFeeYtdNoAdj: boolean | null;
    billingDefaultDaysValue: boolean;
    billingDefaultDaysValueSpecified: boolean;
    billingDefaultDays: boolean | null;
    billingMethodValue: boolean;
    billingMethodValueSpecified: boolean;
    billingMethod: boolean | null;
    billingNoticeValue: boolean;
    billingNoticeValueSpecified: boolean;
    billingNotice: boolean | null;
    billingNoticeMinValue: boolean;
    billingNoticeMinValueSpecified: boolean;
    billingNoticeMin: boolean | null;
    bkChapterReportedValue: boolean;
    bkChapterReportedValueSpecified: boolean;
    bkChapterReported: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    btAddOnSinceLastStmt: number[];
    btAddOnSinceLastStmtSpecified: boolean;
    btIntChargeValue: boolean;
    btIntChargeValueSpecified: boolean;
    btIntCharge: boolean | null;
    btLimitMaxValue: boolean;
    btLimitMaxValueSpecified: boolean;
    btLimitMax: boolean | null;
    btNewIntUnpaidValue: boolean;
    btNewIntUnpaidValueSpecified: boolean;
    btNewIntUnpaid: boolean | null;
    btOldIntUnpaidValue: boolean;
    btOldIntUnpaidValueSpecified: boolean;
    btOldIntUnpaid: boolean | null;
    btPercentValue: boolean;
    btPercentValueSpecified: boolean;
    btPercent: boolean | null;
    btPmtSinceLastStmt: number[];
    btPmtSinceLastStmtSpecified: boolean;
    btTransIntChargeValue: boolean;
    btTransIntChargeValueSpecified: boolean;
    btTransIntCharge: boolean | null;
    bureauScore: number[];
    bureauScoreSpecified: boolean;
    caAddOnSinceLastStmt: number[];
    caAddOnSinceLastStmtSpecified: boolean;
    caBtTransIntChargeBilledYtdValue: boolean;
    caBtTransIntChargeBilledYtdValueSpecified: boolean;
    caBtTransIntChargeBilledYtd: boolean | null;
    caIntChargeValue: boolean;
    caIntChargeValueSpecified: boolean;
    caIntCharge: boolean | null;
    caLimitMaxValue: boolean;
    caLimitMaxValueSpecified: boolean;
    caLimitMax: boolean | null;
    caNewIntUnpaidValue: boolean;
    caNewIntUnpaidValueSpecified: boolean;
    caNewIntUnpaid: boolean | null;
    caOldIntUnpaidValue: boolean;
    caOldIntUnpaidValueSpecified: boolean;
    caOldIntUnpaid: boolean | null;
    caPercentValue: boolean;
    caPercentValueSpecified: boolean;
    caPercent: boolean | null;
    caPmtSinceLastStmt: number[];
    caPmtSinceLastStmtSpecified: boolean;
    caTransIntChargeValue: boolean;
    caTransIntChargeValueSpecified: boolean;
    caTransIntCharge: boolean | null;
    callItemSchdValue: boolean;
    callItemSchdValueSpecified: boolean;
    callItemSchd: boolean | null;
    callItemSchdTypeValue: boolean;
    callItemSchdTypeValueSpecified: boolean;
    callItemSchdType: boolean | null;
    cancelableValue: boolean;
    cancelableValueSpecified: boolean;
    cancelable: boolean | null;
    cappedFeesAmountCapValue: boolean;
    cappedFeesAmountCapValueSpecified: boolean;
    cappedFeesAmountCap: boolean | null;
    cappedFeesAmtPeriodValue: boolean;
    cappedFeesAmtPeriodValueSpecified: boolean;
    cappedFeesAmtPeriod: boolean | null;
    cappedFeesCntPeriodValue: boolean;
    cappedFeesCntPeriodValueSpecified: boolean;
    cappedFeesCntPeriod: boolean | null;
    cappedFeesCountCapValue: boolean;
    cappedFeesCountCapValueSpecified: boolean;
    cappedFeesCountCap: boolean | null;
    cardActDeclChkAxsFeeEventDateValue: boolean;
    cardActDeclChkAxsFeeEventDateValueSpecified: boolean;
    cardActDeclChkAxsFeeEventDate: boolean | null;
    cardActLateFeeEventDateValue: boolean;
    cardActLateFeeEventDateValueSpecified: boolean;
    cardActLateFeeEventDate: boolean | null;
    cardActOverLimitFeeEventDateValue: boolean;
    cardActOverLimitFeeEventDateValueSpecified: boolean;
    cardActOverLimitFeeEventDate: boolean | null;
    cardActReturnItemFeeEventDateValue: boolean;
    cardActReturnItemFeeEventDateValueSpecified: boolean;
    cardActReturnItemFeeEventDate: boolean | null;
    cashAdvAvgBalance: number[];
    cashAdvAvgBalanceSpecified: boolean;
    cashAdvNewBalance: number[];
    cashAdvNewBalanceSpecified: boolean;
    cashAdvOldBalance: number[];
    cashAdvOldBalanceSpecified: boolean;
    cashAdvanceLimitValue: boolean;
    cashAdvanceLimitValueSpecified: boolean;
    cashAdvanceLimit: boolean | null;
    ccIntBilledLastYearValue: boolean;
    ccIntBilledLastYearValueSpecified: boolean;
    ccIntBilledLastYear: boolean | null;
    ccIntBilledYtdValue: boolean;
    ccIntBilledYtdValueSpecified: boolean;
    ccIntBilledYtd: boolean | null;
    ccPromoEffectDate: number[];
    ccPromoEffectDateSpecified: boolean;
    chargeOffAmountValue: boolean;
    chargeOffAmountValueSpecified: boolean;
    chargeOffAmount: boolean | null;
    chargeOffDateValue: boolean;
    chargeOffDateValueSpecified: boolean;
    chargeOffDate: boolean | null;
    chargeOffTypeValue: boolean;
    chargeOffTypeValueSpecified: boolean;
    chargeOffType: boolean | null;
    checkDigitsValue: boolean;
    checkDigitsValueSpecified: boolean;
    checkDigits: boolean | null;
    citySalesTaxRateValue: boolean;
    citySalesTaxRateValueSpecified: boolean;
    citySalesTaxRate: boolean | null;
    closeDateValue: boolean;
    closeDateValueSpecified: boolean;
    closeDate: boolean | null;
    cntySalesTaxRateValue: boolean;
    cntySalesTaxRateValueSpecified: boolean;
    cntySalesTaxRate: boolean | null;
    collateralCodeValue: boolean;
    collateralCodeValueSpecified: boolean;
    collateralCode: boolean | null;
    collateralDateValue: boolean;
    collateralDateValueSpecified: boolean;
    collateralDate: boolean | null;
    combinedCaBtLimitValue: boolean;
    combinedCaBtLimitValueSpecified: boolean;
    combinedCaBtLimit: boolean | null;
    combinedCaBtLimitMaxValue: boolean;
    combinedCaBtLimitMaxValueSpecified: boolean;
    combinedCaBtLimitMax: boolean | null;
    combinedCaBtPercentValue: boolean;
    combinedCaBtPercentValueSpecified: boolean;
    combinedCaBtPercent: boolean | null;
    comboLnSegmentMaxValue: boolean;
    comboLnSegmentMaxValueSpecified: boolean;
    comboLnSegmentMax: boolean | null;
    comboPmtOrderMethValue: boolean;
    comboPmtOrderMethValueSpecified: boolean;
    comboPmtOrderMeth: boolean | null;
    comboSeg0PmtOrderValue: boolean;
    comboSeg0PmtOrderValueSpecified: boolean;
    comboSeg0PmtOrder: boolean | null;
    corporateUserTransferCodeValue: boolean;
    corporateUserTransferCodeValueSpecified: boolean;
    corporateUserTransferCode: boolean | null;
    couponCodeValue: boolean;
    couponCodeValueSpecified: boolean;
    couponCode: boolean | null;
    crHighBalValue: boolean;
    crHighBalValueSpecified: boolean;
    crHighBal: boolean | null;
    crIntTypeIndValue: boolean;
    crIntTypeIndValueSpecified: boolean;
    crIntTypeInd: boolean | null;
    crPmtCurrentValue: boolean;
    crPmtCurrentValueSpecified: boolean;
    crPmtCurrent: boolean | null;
    crPmtHistory: number[];
    crPmtHistorySpecified: boolean;
    createdAtBranchValue: boolean;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: boolean | null;
    createdByUserValue: boolean;
    createdByUserValueSpecified: boolean;
    createdByUser: boolean | null;
    credLimitExpirationValue: boolean;
    credLimitExpirationValueSpecified: boolean;
    credLimitExpiration: boolean | null;
    creditLimitValue: boolean;
    creditLimitValueSpecified: boolean;
    creditLimit: boolean | null;
    creditLimitGroupValue: boolean;
    creditLimitGroupValueSpecified: boolean;
    creditLimitGroup: boolean | null;
    creditReportCommentValue: boolean;
    creditReportCommentValueSpecified: boolean;
    creditReportComment: boolean | null;
    creditReportComplianceValue: boolean;
    creditReportComplianceValueSpecified: boolean;
    creditReportCompliance: boolean | null;
    creditReportConsumerInfoValue: boolean;
    creditReportConsumerInfoValueSpecified: boolean;
    creditReportConsumerInfo: boolean | null;
    creditReportConsumerInfoDateValue: boolean;
    creditReportConsumerInfoDateValueSpecified: boolean;
    creditReportConsumerInfoDate: boolean | null;
    creditReportLastStatusValue: boolean;
    creditReportLastStatusValueSpecified: boolean;
    creditReportLastStatus: boolean | null;
    creditReportNumberValue: boolean;
    creditReportNumberValueSpecified: boolean;
    creditReportNumber: boolean | null;
    creditReportOccurDateValue: boolean;
    creditReportOccurDateValueSpecified: boolean;
    creditReportOccurDate: boolean | null;
    creditReportTransferDateValue: boolean;
    creditReportTransferDateValueSpecified: boolean;
    creditReportTransferDate: boolean | null;
    creditReportTransferIndicatorValue: boolean;
    creditReportTransferIndicatorValueSpecified: boolean;
    creditReportTransferIndicator: boolean | null;
    creditReportTransferNameValue: boolean;
    creditReportTransferNameValueSpecified: boolean;
    creditReportTransferName: boolean | null;
    creditReportingCodeValue: boolean;
    creditReportingCodeValueSpecified: boolean;
    creditReportingCode: boolean | null;
    creditRptDeferredPmtStartValue: boolean;
    creditRptDeferredPmtStartValueSpecified: boolean;
    creditRptDeferredPmtStart: boolean | null;
    creditScoreValue: boolean;
    creditScoreValueSpecified: boolean;
    creditScore: boolean | null;
    creditScoreTypeValue: boolean;
    creditScoreTypeValueSpecified: boolean;
    creditScoreType: boolean | null;
    cuTotalsUseCodeValue: boolean;
    cuTotalsUseCodeValueSpecified: boolean;
    cuTotalsUseCode: boolean | null;
    currIntPayableValue: boolean;
    currIntPayableValueSpecified: boolean;
    currIntPayable: boolean | null;
    currMonthPaidIntValue: boolean;
    currMonthPaidIntValueSpecified: boolean;
    currMonthPaidInt: boolean | null;
    currStmtFeesValue: boolean;
    currStmtFeesValueSpecified: boolean;
    currStmtFees: boolean | null;
    currStmtIntAccrdValue: boolean;
    currStmtIntAccrdValueSpecified: boolean;
    currStmtIntAccrd: boolean | null;
    currStmtLossMitAmtDueValue: boolean;
    currStmtLossMitAmtDueValueSpecified: boolean;
    currStmtLossMitAmtDue: boolean | null;
    dealerCityValue: boolean;
    dealerCityValueSpecified: boolean;
    dealerCity: boolean | null;
    dealerCodeValue: boolean;
    dealerCodeValueSpecified: boolean;
    dealerCode: boolean | null;
    dealerCountyValue: boolean;
    dealerCountyValueSpecified: boolean;
    dealerCounty: boolean | null;
    dealerReserveValue: boolean;
    dealerReserveValueSpecified: boolean;
    dealerReserve: boolean | null;
    dealerStateValue: boolean;
    dealerStateValueSpecified: boolean;
    dealerState: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    discountRateValue: boolean;
    discountRateValueSpecified: boolean;
    discountRate: boolean | null;
    dqCalculationMethodValue: boolean;
    dqCalculationMethodValueSpecified: boolean;
    dqCalculationMethod: boolean | null;
    dqCardDateValue: boolean;
    dqCardDateValueSpecified: boolean;
    dqCardDate: boolean | null;
    dqNoticeDateValue: boolean;
    dqNoticeDateValueSpecified: boolean;
    dqNoticeDate: boolean | null;
    dqNoticeNumberValue: boolean;
    dqNoticeNumberValueSpecified: boolean;
    dqNoticeNumber: boolean | null;
    dqNoticeTypeValue: boolean;
    dqNoticeTypeValueSpecified: boolean;
    dqNoticeType: boolean | null;
    dueDateValue: boolean;
    dueDateValueSpecified: boolean;
    dueDate: boolean | null;
    dueDateAdvanceCodeValue: boolean;
    dueDateAdvanceCodeValueSpecified: boolean;
    dueDateAdvanceCode: boolean | null;
    dueDay1Value: boolean;
    dueDay1ValueSpecified: boolean;
    dueDay1: boolean | null;
    dueDay2Value: boolean;
    dueDay2ValueSpecified: boolean;
    dueDay2: boolean | null;
    earlyIntervntnNoticeDateValue: boolean;
    earlyIntervntnNoticeDateValueSpecified: boolean;
    earlyIntervntnNoticeDate: boolean | null;
    ecoaCodeValue: boolean;
    ecoaCodeValueSpecified: boolean;
    ecoaCode: boolean | null;
    effectiveAprValue: boolean;
    effectiveAprValueSpecified: boolean;
    effectiveApr: boolean | null;
    effectiveBalanceValue: boolean;
    effectiveBalanceValueSpecified: boolean;
    effectiveBalance: boolean | null;
    escrowAmountValue: boolean;
    escrowAmountValueSpecified: boolean;
    escrowAmount: boolean | null;
    escrowAppliedValue: boolean;
    escrowAppliedValueSpecified: boolean;
    escrowApplied: boolean | null;
    escrowBucketAmount: number[];
    escrowBucketAmountSpecified: boolean;
    escrowIdValue: boolean;
    escrowIdValueSpecified: boolean;
    escrowId: boolean | null;
    escrowUnpaidValue: boolean;
    escrowUnpaidValueSpecified: boolean;
    escrowUnpaid: boolean | null;
    exceedLevelPmtAmtValue: boolean;
    exceedLevelPmtAmtValueSpecified: boolean;
    exceedLevelPmtAmt: boolean | null;
    fasb91AlternateTermValue: boolean;
    fasb91AlternateTermValueSpecified: boolean;
    fasb91AlternateTerm: boolean | null;
    fasb91CodeValue: boolean;
    fasb91CodeValueSpecified: boolean;
    fasb91Code: boolean | null;
    feeAddOnSinceLastStmtValue: boolean;
    feeAddOnSinceLastStmtValueSpecified: boolean;
    feeAddOnSinceLastStmt: boolean | null;
    feeBillingAmountValue: boolean;
    feeBillingAmountValueSpecified: boolean;
    feeBillingAmount: boolean | null;
    feeBillingDateValue: boolean;
    feeBillingDateValueSpecified: boolean;
    feeBillingDate: boolean | null;
    feeCount: number[];
    feeCountSpecified: boolean;
    feeNewBalanceValue: boolean;
    feeNewBalanceValueSpecified: boolean;
    feeNewBalance: boolean | null;
    feeOldBalanceValue: boolean;
    feeOldBalanceValueSpecified: boolean;
    feeOldBalance: boolean | null;
    feePmtSinceLastStmtValue: boolean;
    feePmtSinceLastStmtValueSpecified: boolean;
    feePmtSinceLastStmt: boolean | null;
    feesChargesPostingOptionValue: boolean;
    feesChargesPostingOptionValueSpecified: boolean;
    feesChargesPostingOption: boolean | null;
    feesLastYearValue: boolean;
    feesLastYearValueSpecified: boolean;
    feesLastYear: boolean | null;
    feesLastYrNoAdjValue: boolean;
    feesLastYrNoAdjValueSpecified: boolean;
    feesLastYrNoAdj: boolean | null;
    feesYtdValue: boolean;
    feesYtdValueSpecified: boolean;
    feesYtd: boolean | null;
    feesYtdNoAdjValue: boolean;
    feesYtdNoAdjValueSpecified: boolean;
    feesYtdNoAdj: boolean | null;
    finalChgOffStmtDateValue: boolean;
    finalChgOffStmtDateValueSpecified: boolean;
    finalChgOffStmtDate: boolean | null;
    finalChgOffStmtMsgCodeValue: boolean;
    finalChgOffStmtMsgCodeValueSpecified: boolean;
    finalChgOffStmtMsgCode: boolean | null;
    firstInsBirthDateValue: boolean;
    firstInsBirthDateValueSpecified: boolean;
    firstInsBirthDate: boolean | null;
    firstPaymentDateValue: boolean;
    firstPaymentDateValueSpecified: boolean;
    firstPaymentDate: boolean | null;
    fixedDealerCityTaxRateValue: boolean;
    fixedDealerCityTaxRateValueSpecified: boolean;
    fixedDealerCityTaxRate: boolean | null;
    fixedDealerCountyTaxRateValue: boolean;
    fixedDealerCountyTaxRateValueSpecified: boolean;
    fixedDealerCountyTaxRate: boolean | null;
    fixedDealerStateTaxRateValue: boolean;
    fixedDealerStateTaxRateValueSpecified: boolean;
    fixedDealerStateTaxRate: boolean | null;
    fixedLesseeCityTaxRateValue: boolean;
    fixedLesseeCityTaxRateValueSpecified: boolean;
    fixedLesseeCityTaxRate: boolean | null;
    fixedLesseeCountyTaxRateValue: boolean;
    fixedLesseeCountyTaxRateValueSpecified: boolean;
    fixedLesseeCountyTaxRate: boolean | null;
    fixedLesseeStateTaxRateValue: boolean;
    fixedLesseeStateTaxRateValueSpecified: boolean;
    fixedLesseeStateTaxRate: boolean | null;
    foreclosureEffectDateValue: boolean;
    foreclosureEffectDateValueSpecified: boolean;
    foreclosureEffectDate: boolean | null;
    foreclosureExpireDateValue: boolean;
    foreclosureExpireDateValueSpecified: boolean;
    foreclosureExpireDate: boolean | null;
    foreclosureStmtMsgCodeValue: boolean;
    foreclosureStmtMsgCodeValueSpecified: boolean;
    foreclosureStmtMsgCode: boolean | null;
    glAccrualStatusOptionValue: boolean;
    glAccrualStatusOptionValueSpecified: boolean;
    glAccrualStatusOption: boolean | null;
    highRiskCodeValue: boolean;
    highRiskCodeValueSpecified: boolean;
    highRiskCode: boolean | null;
    hmdaUniversalLoanIdentifier1Value: boolean;
    hmdaUniversalLoanIdentifier1ValueSpecified: boolean;
    hmdaUniversalLoanIdentifier1: boolean | null;
    hmdaUniversalLoanIdentifier2Value: boolean;
    hmdaUniversalLoanIdentifier2ValueSpecified: boolean;
    hmdaUniversalLoanIdentifier2: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    indirectDealerNumValue: boolean;
    indirectDealerNumValueSpecified: boolean;
    indirectDealerNum: boolean | null;
    indirectPlanIdValue: boolean;
    indirectPlanIdValueSpecified: boolean;
    indirectPlanId: boolean | null;
    initArmNoticeCreationDateValue: boolean;
    initArmNoticeCreationDateValueSpecified: boolean;
    initArmNoticeCreationDate: boolean | null;
    initialArmNoticeValue: boolean;
    initialArmNoticeValueSpecified: boolean;
    initialArmNotice: boolean | null;
    initialBcdSettingOptionValue: boolean;
    initialBcdSettingOptionValueSpecified: boolean;
    initialBcdSettingOption: boolean | null;
    insuranceBalanceValue: boolean;
    insuranceBalanceValueSpecified: boolean;
    insuranceBalance: boolean | null;
    insuranceLastYearValue: boolean;
    insuranceLastYearValueSpecified: boolean;
    insuranceLastYear: boolean | null;
    insuranceLstYrNoAdjValue: boolean;
    insuranceLstYrNoAdjValueSpecified: boolean;
    insuranceLstYrNoAdj: boolean | null;
    insuranceMaxValue: boolean;
    insuranceMaxValueSpecified: boolean;
    insuranceMax: boolean | null;
    insuranceTypeValue: boolean;
    insuranceTypeValueSpecified: boolean;
    insuranceType: boolean | null;
    insuranceYtdValue: boolean;
    insuranceYtdValueSpecified: boolean;
    insuranceYtd: boolean | null;
    insuranceYtdNoAdjValue: boolean;
    insuranceYtdNoAdjValueSpecified: boolean;
    insuranceYtdNoAdj: boolean | null;
    intPaidPartialDayAmtValue: boolean;
    intPaidPartialDayAmtValueSpecified: boolean;
    intPaidPartialDayAmt: boolean | null;
    intPaidToDateValue: boolean;
    intPaidToDateValueSpecified: boolean;
    intPaidToDate: boolean | null;
    intPayoffCalcValue: boolean;
    intPayoffCalcValueSpecified: boolean;
    intPayoffCalc: boolean | null;
    intUnpaidBilledValue: boolean;
    intUnpaidBilledValueSpecified: boolean;
    intUnpaidBilled: boolean | null;
    interestDateValue: boolean;
    interestDateValueSpecified: boolean;
    interestDate: boolean | null;
    interestDueValue: boolean;
    interestDueValueSpecified: boolean;
    interestDue: boolean | null;
    interestFromOpenValue: boolean;
    interestFromOpenValueSpecified: boolean;
    interestFromOpen: boolean | null;
    interestLastYearValue: boolean;
    interestLastYearValueSpecified: boolean;
    interestLastYear: boolean | null;
    interestRateValue: boolean;
    interestRateValueSpecified: boolean;
    interestRate: boolean | null;
    interestRateIndexValue: boolean;
    interestRateIndexValueSpecified: boolean;
    interestRateIndex: boolean | null;
    interestRateMarginValue: boolean;
    interestRateMarginValueSpecified: boolean;
    interestRateMargin: boolean | null;
    interestRateMarginSignValue: boolean;
    interestRateMarginSignValueSpecified: boolean;
    interestRateMarginSign: boolean | null;
    interestRateMaxValue: boolean;
    interestRateMaxValueSpecified: boolean;
    interestRateMax: boolean | null;
    interestRateMinValue: boolean;
    interestRateMinValueSpecified: boolean;
    interestRateMin: boolean | null;
    interestTypeValue: boolean;
    interestTypeValueSpecified: boolean;
    interestType: boolean | null;
    interestUnpaidValue: boolean;
    interestUnpaidValueSpecified: boolean;
    interestUnpaid: boolean | null;
    interestYtdValue: boolean;
    interestYtdValueSpecified: boolean;
    interestYtd: boolean | null;
    lastAccrReversalDateValue: boolean;
    lastAccrReversalDateValueSpecified: boolean;
    lastAccrReversalDate: boolean | null;
    lastAccrUpdateDateValue: boolean;
    lastAccrUpdateDateValueSpecified: boolean;
    lastAccrUpdateDate: boolean | null;
    lastAccrualReversalValue: boolean;
    lastAccrualReversalValueSpecified: boolean;
    lastAccrualReversal: boolean | null;
    lastAdvanceDateValue: boolean;
    lastAdvanceDateValueSpecified: boolean;
    lastAdvanceDate: boolean | null;
    lastArmNoticeCreationDateValue: boolean;
    lastArmNoticeCreationDateValueSpecified: boolean;
    lastArmNoticeCreationDate: boolean | null;
    lastCrReportDateValue: boolean;
    lastCrReportDateValueSpecified: boolean;
    lastCrReportDate: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    lastPaymentDateValue: boolean;
    lastPaymentDateValueSpecified: boolean;
    lastPaymentDate: boolean | null;
    lastPurgeDateValue: boolean;
    lastPurgeDateValueSpecified: boolean;
    lastPurgeDate: boolean | null;
    lastTranDateValue: boolean;
    lastTranDateValueSpecified: boolean;
    lastTranDate: boolean | null;
    lateChargeAccruedValue: boolean;
    lateChargeAccruedValueSpecified: boolean;
    lateChargeAccrued: boolean | null;
    lateChargeDateValue: boolean;
    lateChargeDateValueSpecified: boolean;
    lateChargeDate: boolean | null;
    lateChargeDueValue: boolean;
    lateChargeDueValueSpecified: boolean;
    lateChargeDue: boolean | null;
    lateChargeLastYearValue: boolean;
    lateChargeLastYearValueSpecified: boolean;
    lateChargeLastYear: boolean | null;
    lateChargeTypeValue: boolean;
    lateChargeTypeValueSpecified: boolean;
    lateChargeType: boolean | null;
    lateChargeUnpaidValue: boolean;
    lateChargeUnpaidValueSpecified: boolean;
    lateChargeUnpaid: boolean | null;
    lateChargeYtdValue: boolean;
    lateChargeYtdValueSpecified: boolean;
    lateChargeYtd: boolean | null;
    lateChgLastYrNoAdjValue: boolean;
    lateChgLastYrNoAdjValueSpecified: boolean;
    lateChgLastYrNoAdj: boolean | null;
    lateChgPdFromOpenValue: boolean;
    lateChgPdFromOpenValueSpecified: boolean;
    lateChgPdFromOpen: boolean | null;
    lateChgWaivedFromOpenValue: boolean;
    lateChgWaivedFromOpenValueSpecified: boolean;
    lateChgWaivedFromOpen: boolean | null;
    lateChgWaivedLastYearValue: boolean;
    lateChgWaivedLastYearValueSpecified: boolean;
    lateChgWaivedLastYear: boolean | null;
    lateChgWaivedYtdValue: boolean;
    lateChgWaivedYtdValueSpecified: boolean;
    lateChgWaivedYtd: boolean | null;
    lateChgYtdNoAdjValue: boolean;
    lateChgYtdNoAdjValueSpecified: boolean;
    lateChgYtdNoAdj: boolean | null;
    leaseDispositionDateValue: boolean;
    leaseDispositionDateValueSpecified: boolean;
    leaseDispositionDate: boolean | null;
    leaseDispositionFeeValue: boolean;
    leaseDispositionFeeValueSpecified: boolean;
    leaseDispositionFee: boolean | null;
    leaseTerminateDateValue: boolean;
    leaseTerminateDateValueSpecified: boolean;
    leaseTerminateDate: boolean | null;
    leaseTerminateFeeValue: boolean;
    leaseTerminateFeeValueSpecified: boolean;
    leaseTerminateFee: boolean | null;
    ledgerAccrualValue: boolean;
    ledgerAccrualValueSpecified: boolean;
    ledgerAccrual: boolean | null;
    ledgerAccrualDateValue: boolean;
    ledgerAccrualDateValueSpecified: boolean;
    ledgerAccrualDate: boolean | null;
    lesseeCityValue: boolean;
    lesseeCityValueSpecified: boolean;
    lesseeCity: boolean | null;
    lesseeCountyValue: boolean;
    lesseeCountyValueSpecified: boolean;
    lesseeCounty: boolean | null;
    lesseeStateValue: boolean;
    lesseeStateValueSpecified: boolean;
    lesseeState: boolean | null;
    levelPaymentAmtValue: boolean;
    levelPaymentAmtValueSpecified: boolean;
    levelPaymentAmt: boolean | null;
    levelPrincipalAmtValue: boolean;
    levelPrincipalAmtValueSpecified: boolean;
    levelPrincipalAmt: boolean | null;
    loanCodeValue: boolean;
    loanCodeValueSpecified: boolean;
    loanCode: boolean | null;
    lossMitEffectDateValue: boolean;
    lossMitEffectDateValueSpecified: boolean;
    lossMitEffectDate: boolean | null;
    lossMitExpireDateValue: boolean;
    lossMitExpireDateValueSpecified: boolean;
    lossMitExpireDate: boolean | null;
    lossMitPaymentValue: boolean;
    lossMitPaymentValueSpecified: boolean;
    lossMitPayment: boolean | null;
    lossMitPmtStmtMsgCodeValue: boolean;
    lossMitPmtStmtMsgCodeValueSpecified: boolean;
    lossMitPmtStmtMsgCode: boolean | null;
    lossMitStmtMsgCodeValue: boolean;
    lossMitStmtMsgCodeValueSpecified: boolean;
    lossMitStmtMsgCode: boolean | null;
    lrlnBalanceValue: boolean;
    lrlnBalanceValueSpecified: boolean;
    lrlnBalance: boolean | null;
    lrlnDateValue: boolean;
    lrlnDateValueSpecified: boolean;
    lrlnDate: boolean | null;
    maprCurrStmtIntAccrdValue: boolean;
    maprCurrStmtIntAccrdValueSpecified: boolean;
    maprCurrStmtIntAccrd: boolean | null;
    maturityDateValue: boolean;
    maturityDateValueSpecified: boolean;
    maturityDate: boolean | null;
    maxDueDateAdvancePeriodValue: boolean;
    maxDueDateAdvancePeriodValueSpecified: boolean;
    maxDueDateAdvancePeriod: boolean | null;
    maxLoanDueDateValue: boolean;
    maxLoanDueDateValueSpecified: boolean;
    maxLoanDueDate: boolean | null;
    memberUserTransferCodeValue: boolean;
    memberUserTransferCodeValueSpecified: boolean;
    memberUserTransferCode: boolean | null;
    mfoelIdValue: boolean;
    mfoelIdValueSpecified: boolean;
    mfoelId: boolean | null;
    micrAcctNumberValue: boolean;
    micrAcctNumberValueSpecified: boolean;
    micrAcctNumber: boolean | null;
    militaryAprLoanValue: boolean;
    militaryAprLoanValueSpecified: boolean;
    militaryAprLoan: boolean | null;
    minAdvanceValue: boolean;
    minAdvanceValueSpecified: boolean;
    minAdvance: boolean | null;
    minBalanceValue: boolean;
    minBalanceValueSpecified: boolean;
    minBalance: boolean | null;
    minimumPaymentValue: boolean;
    minimumPaymentValueSpecified: boolean;
    minimumPayment: boolean | null;
    mortgInsCollLastYrValue: boolean;
    mortgInsCollLastYrValueSpecified: boolean;
    mortgInsCollLastYr: boolean | null;
    mortgInsCollYtdValue: boolean;
    mortgInsCollYtdValueSpecified: boolean;
    mortgInsCollYtd: boolean | null;
    mortgageIdNumberValue: boolean;
    mortgageIdNumberValueSpecified: boolean;
    mortgageIdNumber: boolean | null;
    mtdAccruedIntValue: boolean;
    mtdAccruedIntValueSpecified: boolean;
    mtdAccruedInt: boolean | null;
    mtdAccumulatedIntValue: boolean;
    mtdAccumulatedIntValueSpecified: boolean;
    mtdAccumulatedInt: boolean | null;
    mtdPaidIntValue: boolean;
    mtdPaidIntValueSpecified: boolean;
    mtdPaidInt: boolean | null;
    mtdPriorRateAccrualValue: boolean;
    mtdPriorRateAccrualValueSpecified: boolean;
    mtdPriorRateAccrual: boolean | null;
    mtgNumPropValue: boolean;
    mtgNumPropValueSpecified: boolean;
    mtgNumProp: boolean | null;
    newLoanDueDateCodeValue: boolean;
    newLoanDueDateCodeValueSpecified: boolean;
    newLoanDueDateCode: boolean | null;
    newSegCutoffDaysValue: boolean;
    newSegCutoffDaysValueSpecified: boolean;
    newSegCutoffDays: boolean | null;
    newSegCutoffOptionValue: boolean;
    newSegCutoffOptionValueSpecified: boolean;
    newSegCutoffOption: boolean | null;
    nextRateChangeDateValue: boolean;
    nextRateChangeDateValueSpecified: boolean;
    nextRateChangeDate: boolean | null;
    nextStmtDateValue: boolean;
    nextStmtDateValueSpecified: boolean;
    nextStmtDate: boolean | null;
    nicknameValue: boolean;
    nicknameValueSpecified: boolean;
    nickname: boolean | null;
    noteNumberValue: boolean;
    noteNumberValueSpecified: boolean;
    noteNumber: boolean | null;
    nsfLastYearValue: boolean;
    nsfLastYearValueSpecified: boolean;
    nsfLastYear: boolean | null;
    nsfMonthToDateValue: boolean;
    nsfMonthToDateValueSpecified: boolean;
    nsfMonthToDate: boolean | null;
    nsfYtdValue: boolean;
    nsfYtdValueSpecified: boolean;
    nsfYtd: boolean | null;
    occupancyTypeValue: boolean;
    occupancyTypeValueSpecified: boolean;
    occupancyType: boolean | null;
    openDateValue: boolean;
    openDateValueSpecified: boolean;
    openDate: boolean | null;
    origInsuranceTypeValue: boolean;
    origInsuranceTypeValueSpecified: boolean;
    origInsuranceType: boolean | null;
    origRiskGradeValue: boolean;
    origRiskGradeValueSpecified: boolean;
    origRiskGrade: boolean | null;
    origUnamortizedFeesValue: boolean;
    origUnamortizedFeesValueSpecified: boolean;
    origUnamortizedFees: boolean | null;
    originalBalanceValue: boolean;
    originalBalanceValueSpecified: boolean;
    originalBalance: boolean | null;
    originalDateValue: boolean;
    originalDateValueSpecified: boolean;
    originalDate: boolean | null;
    originalRateValue: boolean;
    originalRateValueSpecified: boolean;
    originalRate: boolean | null;
    originationBalanceValue: boolean;
    originationBalanceValueSpecified: boolean;
    originationBalance: boolean | null;
    ovlAuthFeeValue: boolean;
    ovlAuthFeeValueSpecified: boolean;
    ovlAuthFee: boolean | null;
    ovlAuthFeeEffDateValue: boolean;
    ovlAuthFeeEffDateValueSpecified: boolean;
    ovlAuthFeeEffDate: boolean | null;
    ovlCycleCount: number[];
    ovlCycleCountSpecified: boolean;
    ovlOptInValue: boolean;
    ovlOptInValueSpecified: boolean;
    ovlOptIn: boolean | null;
    ovlPrevAuthFeeValue: boolean;
    ovlPrevAuthFeeValueSpecified: boolean;
    ovlPrevAuthFee: boolean | null;
    ovlStmtDisclFeeValue: boolean;
    ovlStmtDisclFeeValueSpecified: boolean;
    ovlStmtDisclFee: boolean | null;
    partialPaymentValue: boolean;
    partialPaymentValueSpecified: boolean;
    partialPayment: boolean | null;
    participationNumberValue: boolean;
    participationNumberValueSpecified: boolean;
    participationNumber: boolean | null;
    pastDueAmountValue: boolean;
    pastDueAmountValueSpecified: boolean;
    pastDueAmount: boolean | null;
    payeeLine: number[];
    payeeLineSpecified: boolean;
    payeeNameLocatorValue: boolean;
    payeeNameLocatorValueSpecified: boolean;
    payeeNameLocator: boolean | null;
    payeeNameTypeValue: boolean;
    payeeNameTypeValueSpecified: boolean;
    payeeNameType: boolean | null;
    payeePhone: number[];
    payeePhoneSpecified: boolean;
    paymentValue: boolean;
    paymentValueSpecified: boolean;
    payment: boolean | null;
    paymentApplicationMethodValue: boolean;
    paymentApplicationMethodValueSpecified: boolean;
    paymentApplicationMethod: boolean | null;
    paymentCalcTypeValue: boolean;
    paymentCalcTypeValueSpecified: boolean;
    paymentCalcType: boolean | null;
    paymentCountValue: boolean;
    paymentCountValueSpecified: boolean;
    paymentCount: boolean | null;
    paymentDueValue: boolean;
    paymentDueValueSpecified: boolean;
    paymentDue: boolean | null;
    paymentFrequencyValue: boolean;
    paymentFrequencyValueSpecified: boolean;
    paymentFrequency: boolean | null;
    paymentHistory: number[];
    paymentHistorySpecified: boolean;
    paymentMethodValue: boolean;
    paymentMethodValueSpecified: boolean;
    paymentMethod: boolean | null;
    paymentSkipStartDayValue: boolean;
    paymentSkipStartDayValueSpecified: boolean;
    paymentSkipStartDay: boolean | null;
    paymentSkipsValue: boolean;
    paymentSkipsValueSpecified: boolean;
    paymentSkips: boolean | null;
    paymentTypeValue: boolean;
    paymentTypeValueSpecified: boolean;
    paymentType: boolean | null;
    payoffAmountValue: boolean;
    payoffAmountValueSpecified: boolean;
    payoffAmount: boolean | null;
    percentPrincipalValue: boolean;
    percentPrincipalValueSpecified: boolean;
    percentPrincipal: boolean | null;
    periodicCapValue: boolean;
    periodicCapValueSpecified: boolean;
    periodicCap: boolean | null;
    periodicFrequencyValue: boolean;
    periodicFrequencyValueSpecified: boolean;
    periodicFrequency: boolean | null;
    periodicStartDateValue: boolean;
    periodicStartDateValueSpecified: boolean;
    periodicStartDate: boolean | null;
    periodicStartRateValue: boolean;
    periodicStartRateValueSpecified: boolean;
    periodicStartRate: boolean | null;
    pmiAppraisedValueValue: boolean;
    pmiAppraisedValueValueSpecified: boolean;
    pmiAppraisedValue: boolean | null;
    pmiLastYearValue: boolean;
    pmiLastYearValueSpecified: boolean;
    pmiLastYear: boolean | null;
    pmiLtvRatioValue: boolean;
    pmiLtvRatioValueSpecified: boolean;
    pmiLtvRatio: boolean | null;
    pmiOriginalValueValue: boolean;
    pmiOriginalValueValueSpecified: boolean;
    pmiOriginalValue: boolean | null;
    pmiPurchasePriceValue: boolean;
    pmiPurchasePriceValueSpecified: boolean;
    pmiPurchasePrice: boolean | null;
    pmiYtdValue: boolean;
    pmiYtdValueSpecified: boolean;
    pmiYtd: boolean | null;
    pmtBucketAmount: number[];
    pmtBucketAmountSpecified: boolean;
    pmtBucketDueDate: number[];
    pmtBucketDueDateSpecified: boolean;
    pointsLastYearValue: boolean;
    pointsLastYearValueSpecified: boolean;
    pointsLastYear: boolean | null;
    pointsYtdValue: boolean;
    pointsYtdValueSpecified: boolean;
    pointsYtd: boolean | null;
    positivePayDraftValue: boolean;
    positivePayDraftValueSpecified: boolean;
    positivePayDraft: boolean | null;
    preMthIntAccrued: number[];
    preMthIntAccruedSpecified: boolean;
    preMthIntAccumLtd: number[];
    preMthIntAccumLtdSpecified: boolean;
    preMthIntPaid: number[];
    preMthIntPaidSpecified: boolean;
    prepaidFinanceChgValue: boolean;
    prepaidFinanceChgValueSpecified: boolean;
    prepaidFinanceChg: boolean | null;
    prepaymentPenaltyValue: boolean;
    prepaymentPenaltyValueSpecified: boolean;
    prepaymentPenalty: boolean | null;
    prepaymentPenaltyExpDateValue: boolean;
    prepaymentPenaltyExpDateValueSpecified: boolean;
    prepaymentPenaltyExpDate: boolean | null;
    prevBeginningYearBalanceValue: boolean;
    prevBeginningYearBalanceValueSpecified: boolean;
    prevBeginningYearBalance: boolean | null;
    prevStmtFeesValue: boolean;
    prevStmtFeesValueSpecified: boolean;
    prevStmtFees: boolean | null;
    prevStmtIntAccrdValue: boolean;
    prevStmtIntAccrdValueSpecified: boolean;
    prevStmtIntAccrd: boolean | null;
    prevStmtLossMitAmtDueValue: boolean;
    prevStmtLossMitAmtDueValueSpecified: boolean;
    prevStmtLossMitAmtDue: boolean | null;
    prinPaidFromOpenValue: boolean;
    prinPaidFromOpenValueSpecified: boolean;
    prinPaidFromOpen: boolean | null;
    principalLastYearValue: boolean;
    principalLastYearValueSpecified: boolean;
    principalLastYear: boolean | null;
    principalYtdValue: boolean;
    principalYtdValueSpecified: boolean;
    principalYtd: boolean | null;
    promoAdvanceCutoff: number[];
    promoAdvanceCutoffSpecified: boolean;
    promoBalance: number[];
    promoBalanceSpecified: boolean;
    promoEffectDate: number[];
    promoEffectDateSpecified: boolean;
    promoExpireDate: number[];
    promoExpireDateSpecified: boolean;
    promoRate: number[];
    promoRateSpecified: boolean;
    promoRateMax: number[];
    promoRateMaxSpecified: boolean;
    promoRateMin: number[];
    promoRateMinSpecified: boolean;
    promoRateOffset: number[];
    promoRateOffsetSpecified: boolean;
    promoRateType: number[];
    promoRateTypeSpecified: boolean;
    promoTotalAdvances: number[];
    promoTotalAdvancesSpecified: boolean;
    promoType: number[];
    promoTypeSpecified: boolean;
    propertyAddressTypeValue: boolean;
    propertyAddressTypeValueSpecified: boolean;
    propertyAddressType: boolean | null;
    propertyJurisdictionValue: boolean;
    propertyJurisdictionValueSpecified: boolean;
    propertyJurisdiction: boolean | null;
    puAddOnSinceLastStmt: number[];
    puAddOnSinceLastStmtSpecified: boolean;
    puIntChargeValue: boolean;
    puIntChargeValueSpecified: boolean;
    puIntCharge: boolean | null;
    puNewIntUnpaidValue: boolean;
    puNewIntUnpaidValueSpecified: boolean;
    puNewIntUnpaid: boolean | null;
    puOldIntUnpaidValue: boolean;
    puOldIntUnpaidValueSpecified: boolean;
    puOldIntUnpaid: boolean | null;
    puPmtSinceLastStmt: number[];
    puPmtSinceLastStmtSpecified: boolean;
    purchAvgBalance: number[];
    purchAvgBalanceSpecified: boolean;
    purchNewBalance: number[];
    purchNewBalanceSpecified: boolean;
    purchOldBalance: number[];
    purchOldBalanceSpecified: boolean;
    purposeCodeValue: boolean;
    purposeCodeValueSpecified: boolean;
    purposeCode: boolean | null;
    putItemSchdValue: boolean;
    putItemSchdValueSpecified: boolean;
    putItemSchd: boolean | null;
    putItemSchdTypeValue: boolean;
    putItemSchdTypeValueSpecified: boolean;
    putItemSchdType: boolean | null;
    rateChangeCycleMonthsValue: boolean;
    rateChangeCycleMonthsValueSpecified: boolean;
    rateChangeCycleMonths: boolean | null;
    rateRoundingMethodValue: boolean;
    rateRoundingMethodValueSpecified: boolean;
    rateRoundingMethod: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    referenceValue: boolean;
    referenceValueSpecified: boolean;
    reference: boolean | null;
    refinanceBalanceValue: boolean;
    refinanceBalanceValueSpecified: boolean;
    refinanceBalance: boolean | null;
    refinanceCounterValue: boolean;
    refinanceCounterValueSpecified: boolean;
    refinanceCounter: boolean | null;
    refinanceDateValue: boolean;
    refinanceDateValueSpecified: boolean;
    refinanceDate: boolean | null;
    refundLastYearValue: boolean;
    refundLastYearValueSpecified: boolean;
    refundLastYear: boolean | null;
    refundPostCodeValue: boolean;
    refundPostCodeValueSpecified: boolean;
    refundPostCode: boolean | null;
    refundYtdValue: boolean;
    refundYtdValueSpecified: boolean;
    refundYtd: boolean | null;
    regECountValue: boolean;
    regECountValueSpecified: boolean;
    regECount: boolean | null;
    regPaymentsTmtMsgCodeValue: boolean;
    regPaymentsTmtMsgCodeValueSpecified: boolean;
    regPaymentsTmtMsgCode: boolean | null;
    reinstatementAmtValue: boolean;
    reinstatementAmtValueSpecified: boolean;
    reinstatementAmt: boolean | null;
    reinstatementGoodThruDateValue: boolean;
    reinstatementGoodThruDateValueSpecified: boolean;
    reinstatementGoodThruDate: boolean | null;
    reinstatementStmtMsgCodeValue: boolean;
    reinstatementStmtMsgCodeValueSpecified: boolean;
    reinstatementStmtMsgCode: boolean | null;
    riskRateValue: boolean;
    riskRateValueSpecified: boolean;
    riskRate: boolean | null;
    roundRateToValue: boolean;
    roundRateToValueSpecified: boolean;
    roundRateTo: boolean | null;
    salesTaxCityIndicatorValue: boolean;
    salesTaxCityIndicatorValueSpecified: boolean;
    salesTaxCityIndicator: boolean | null;
    salesTaxCountyIndicatorValue: boolean;
    salesTaxCountyIndicatorValueSpecified: boolean;
    salesTaxCountyIndicator: boolean | null;
    salesTaxDueValue: boolean;
    salesTaxDueValueSpecified: boolean;
    salesTaxDue: boolean | null;
    salesTaxPayoffValue: boolean;
    salesTaxPayoffValueSpecified: boolean;
    salesTaxPayoff: boolean | null;
    salesTaxRateValue: boolean;
    salesTaxRateValueSpecified: boolean;
    salesTaxRate: boolean | null;
    salesTaxStateIndicatorValue: boolean;
    salesTaxStateIndicatorValueSpecified: boolean;
    salesTaxStateIndicator: boolean | null;
    sbaGpNumberValue: boolean;
    sbaGpNumberValueSpecified: boolean;
    sbaGpNumber: boolean | null;
    schdPeriodStartDateValue: boolean;
    schdPeriodStartDateValueSpecified: boolean;
    schdPeriodStartDate: boolean | null;
    schdPeriodStartRateValue: boolean;
    schdPeriodStartRateValueSpecified: boolean;
    schdPeriodStartRate: boolean | null;
    schdRateValue: boolean;
    schdRateValueSpecified: boolean;
    schdRate: boolean | null;
    schdRateChangeDateValue: boolean;
    schdRateChangeDateValueSpecified: boolean;
    schdRateChangeDate: boolean | null;
    schdSplitBalanceValue: boolean;
    schdSplitBalanceValueSpecified: boolean;
    schdSplitBalance: boolean | null;
    schdSplitRateValue: boolean;
    schdSplitRateValueSpecified: boolean;
    schdSplitRate: boolean | null;
    secondInsBirthDateValue: boolean;
    secondInsBirthDateValueSpecified: boolean;
    secondInsBirthDate: boolean | null;
    securedAmountValue: boolean;
    securedAmountValueSpecified: boolean;
    securedAmount: boolean | null;
    securedCodeValue: boolean;
    securedCodeValueSpecified: boolean;
    securedCode: boolean | null;
    seg0BalanceValue: boolean;
    seg0BalanceValueSpecified: boolean;
    seg0Balance: boolean | null;
    seg0BeginningCycleDateValue: boolean;
    seg0BeginningCycleDateValueSpecified: boolean;
    seg0BeginningCycleDate: boolean | null;
    seg0CurrStmtIntAccrdValue: boolean;
    seg0CurrStmtIntAccrdValueSpecified: boolean;
    seg0CurrStmtIntAccrd: boolean | null;
    seg0DescriptionValue: boolean;
    seg0DescriptionValueSpecified: boolean;
    seg0Description: boolean | null;
    seg0IntUnpaidValue: boolean;
    seg0IntUnpaidValueSpecified: boolean;
    seg0IntUnpaid: boolean | null;
    seg0IntUnpaidBilledValue: boolean;
    seg0IntUnpaidBilledValueSpecified: boolean;
    seg0IntUnpaidBilled: boolean | null;
    seg0InterestLastYearValue: boolean;
    seg0InterestLastYearValueSpecified: boolean;
    seg0InterestLastYear: boolean | null;
    seg0InterestYtdValue: boolean;
    seg0InterestYtdValueSpecified: boolean;
    seg0InterestYtd: boolean | null;
    seg0LevelPrinPmtValue: boolean;
    seg0LevelPrinPmtValueSpecified: boolean;
    seg0LevelPrinPmt: boolean | null;
    seg0PartialPmtValue: boolean;
    seg0PartialPmtValueSpecified: boolean;
    seg0PartialPmt: boolean | null;
    seg0PaymentValue: boolean;
    seg0PaymentValueSpecified: boolean;
    seg0Payment: boolean | null;
    seg0PaymentDueValue: boolean;
    seg0PaymentDueValueSpecified: boolean;
    seg0PaymentDue: boolean | null;
    seg0PaymentOrderValue: boolean;
    seg0PaymentOrderValueSpecified: boolean;
    seg0PaymentOrder: boolean | null;
    seg0PayoffAmtValue: boolean;
    seg0PayoffAmtValueSpecified: boolean;
    seg0PayoffAmt: boolean | null;
    seg0PmtBucketAmt: number[];
    seg0PmtBucketAmtSpecified: boolean;
    seg0PrevStmtIntAccrdValue: boolean;
    seg0PrevStmtIntAccrdValueSpecified: boolean;
    seg0PrevStmtIntAccrd: boolean | null;
    sendFinalChgOffStmtValue: boolean;
    sendFinalChgOffStmtValueSpecified: boolean;
    sendFinalChgOffStmt: boolean | null;
    service: number[];
    serviceSpecified: boolean;
    singlePremiumDisabilityValue: boolean;
    singlePremiumDisabilityValueSpecified: boolean;
    singlePremiumDisability: boolean | null;
    singlePremiumLifeValue: boolean;
    singlePremiumLifeValueSpecified: boolean;
    singlePremiumLife: boolean | null;
    splitRateValue: boolean;
    splitRateValueSpecified: boolean;
    splitRate: boolean | null;
    splitRateBalanceValue: boolean;
    splitRateBalanceValueSpecified: boolean;
    splitRateBalance: boolean | null;
    stateSalesTaxRateValue: boolean;
    stateSalesTaxRateValueSpecified: boolean;
    stateSalesTaxRate: boolean | null;
    statementDateValue: boolean;
    statementDateValueSpecified: boolean;
    statementDate: boolean | null;
    statementGroupValue: boolean;
    statementGroupValueSpecified: boolean;
    statementGroup: boolean | null;
    statementMailCodeValue: boolean;
    statementMailCodeValueSpecified: boolean;
    statementMailCode: boolean | null;
    statementNewBalanceValue: boolean;
    statementNewBalanceValueSpecified: boolean;
    statementNewBalance: boolean | null;
    statementOldBalanceValue: boolean;
    statementOldBalanceValueSpecified: boolean;
    statementOldBalance: boolean | null;
    statementPrevDateValue: boolean;
    statementPrevDateValueSpecified: boolean;
    statementPrevDate: boolean | null;
    stmtCcIntBilledYtdValue: boolean;
    stmtCcIntBilledYtdValueSpecified: boolean;
    stmtCcIntBilledYtd: boolean | null;
    stmtEscrowUnpaidValue: boolean;
    stmtEscrowUnpaidValueSpecified: boolean;
    stmtEscrowUnpaid: boolean | null;
    stmtFeesLastYearValue: boolean;
    stmtFeesLastYearValueSpecified: boolean;
    stmtFeesLastYear: boolean | null;
    stmtFeesYtdValue: boolean;
    stmtFeesYtdValueSpecified: boolean;
    stmtFeesYtd: boolean | null;
    stmtIntFromOpenValue: boolean;
    stmtIntFromOpenValueSpecified: boolean;
    stmtIntFromOpen: boolean | null;
    stmtLateChargeLastYearValue: boolean;
    stmtLateChargeLastYearValueSpecified: boolean;
    stmtLateChargeLastYear: boolean | null;
    stmtLateChargeYtdValue: boolean;
    stmtLateChargeYtdValueSpecified: boolean;
    stmtLateChargeYtd: boolean | null;
    stmtLateChgUnpaidValue: boolean;
    stmtLateChgUnpaidValueSpecified: boolean;
    stmtLateChgUnpaid: boolean | null;
    stmtLtChgPdFrmOpnValue: boolean;
    stmtLtChgPdFrmOpnValueSpecified: boolean;
    stmtLtChgPdFrmOpn: boolean | null;
    stmtMaxLateFeeValue: boolean;
    stmtMaxLateFeeValueSpecified: boolean;
    stmtMaxLateFee: boolean | null;
    stmtMaxPenaltyAprValue: boolean;
    stmtMaxPenaltyAprValueSpecified: boolean;
    stmtMaxPenaltyApr: boolean | null;
    stmtNoteStartDateValue: boolean;
    stmtNoteStartDateValueSpecified: boolean;
    stmtNoteStartDate: boolean | null;
    stmtPrinPdFromOpenValue: boolean;
    stmtPrinPdFromOpenValueSpecified: boolean;
    stmtPrinPdFromOpen: boolean | null;
    stmtPrincipalLastYearValue: boolean;
    stmtPrincipalLastYearValueSpecified: boolean;
    stmtPrincipalLastYear: boolean | null;
    stmtPrincipalYtdValue: boolean;
    stmtPrincipalYtdValueSpecified: boolean;
    stmtPrincipalYtd: boolean | null;
    stmtUnappliedPartialPmtValue: boolean;
    stmtUnappliedPartialPmtValueSpecified: boolean;
    stmtUnappliedPartialPmt: boolean | null;
    studentCoveredPeriodEndValue: boolean;
    studentCoveredPeriodEndValueSpecified: boolean;
    studentCoveredPeriodEnd: boolean | null;
    studentLoanCapIntLastYearValue: boolean;
    studentLoanCapIntLastYearValueSpecified: boolean;
    studentLoanCapIntLastYear: boolean | null;
    studentLoanCapIntYtdValue: boolean;
    studentLoanCapIntYtdValueSpecified: boolean;
    studentLoanCapIntYtd: boolean | null;
    studentLoanCodeValue: boolean;
    studentLoanCodeValueSpecified: boolean;
    studentLoanCode: boolean | null;
    studentLoanOrigFeeLastYearValue: boolean;
    studentLoanOrigFeeLastYearValueSpecified: boolean;
    studentLoanOrigFeeLastYear: boolean | null;
    studentLoanOrigFeeYtdValue: boolean;
    studentLoanOrigFeeYtdValueSpecified: boolean;
    studentLoanOrigFeeYtd: boolean | null;
    thresholdPmtValue: boolean;
    thresholdPmtValueSpecified: boolean;
    thresholdPmt: boolean | null;
    totalAccrualReversalValue: boolean;
    totalAccrualReversalValueSpecified: boolean;
    totalAccrualReversal: boolean | null;
    totalBtBalanceToDateValue: boolean;
    totalBtBalanceToDateValueSpecified: boolean;
    totalBtBalanceToDate: boolean | null;
    totalCaBalanceToDateValue: boolean;
    totalCaBalanceToDateValueSpecified: boolean;
    totalCaBalanceToDate: boolean | null;
    totalFeeBalanceToDateValue: boolean;
    totalFeeBalanceToDateValueSpecified: boolean;
    totalFeeBalanceToDate: boolean | null;
    totalPuBalanceToDateValue: boolean;
    totalPuBalanceToDateValueSpecified: boolean;
    totalPuBalanceToDate: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    unAdjThresholdPmtValue: boolean;
    unAdjThresholdPmtValueSpecified: boolean;
    unAdjThresholdPmt: boolean | null;
    unAdjaPaymentDueValue: boolean;
    unAdjaPaymentDueValueSpecified: boolean;
    unAdjaPaymentDue: boolean | null;
    unamortizedFeesValue: boolean;
    unamortizedFeesValueSpecified: boolean;
    unamortizedFees: boolean | null;
    unappliedPartialPmtValue: boolean;
    unappliedPartialPmtValueSpecified: boolean;
    unappliedPartialPmt: boolean | null;
    userAmount1Value: boolean;
    userAmount1ValueSpecified: boolean;
    userAmount1: boolean | null;
    userAmount2Value: boolean;
    userAmount2ValueSpecified: boolean;
    userAmount2: boolean | null;
    userChar1Value: boolean;
    userChar1ValueSpecified: boolean;
    userChar1: boolean | null;
    userChar2Value: boolean;
    userChar2ValueSpecified: boolean;
    userChar2: boolean | null;
    userChar3Value: boolean;
    userChar3ValueSpecified: boolean;
    userChar3: boolean | null;
    userChar4Value: boolean;
    userChar4ValueSpecified: boolean;
    userChar4: boolean | null;
    userDate1Value: boolean;
    userDate1ValueSpecified: boolean;
    userDate1: boolean | null;
    userDate2Value: boolean;
    userDate2ValueSpecified: boolean;
    userDate2: boolean | null;
    variableRateIndicatorValue: boolean;
    variableRateIndicatorValueSpecified: boolean;
    variableRateIndicator: boolean | null;
    vinValue: boolean;
    vinValueSpecified: boolean;
    vin: boolean | null;
    warningCode: number[];
    warningCodeSpecified: boolean;
    warningExpiration: number[];
    warningExpirationSpecified: boolean;
    version1: VersionType;
    investorValue: boolean;
    investorValueSpecified: boolean;
    investor: boolean | null;
    remittanceTypeValue: boolean;
    remittanceTypeValueSpecified: boolean;
    remittanceType: boolean | null;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}