import { LoanPledgeNameIdentDocFlag_2 } from "./loanPledgeNameIdentDocFlag_2";
import { LoanPledgeNameIdentIdDescription_2 } from "./loanPledgeNameIdentIdDescription_2";
import { LoanPledgeNameIdentIdExpireDate_2 } from "./loanPledgeNameIdentIdExpireDate_2";
import { LoanPledgeNameIdentIdIssueDate_2 } from "./loanPledgeNameIdentIdIssueDate_2";
import { LoanPledgeNameIdentIdNumber_2 } from "./loanPledgeNameIdentIdNumber_2";
import { LoanPledgeNameIdentIdType_2 } from "./loanPledgeNameIdentIdType_2";
import { LoanPledgeNameIdentIdVerifyDate_2 } from "./loanPledgeNameIdentIdVerifyDate_2";
import { VersionType } from "./versionType";

export interface LoanPledgeName_2 {
    activeDuty: number | null;
    activeDutySeparationDate: string | null;
    activeDutyStartDate: string | null;
    activeDutyVerificationDate: string | null;
    addrCreateDate: string | null;
    addrDisconnectDate: string | null;
    addrExpDate: string | null;
    addrFmLastDate: string | null;
    addrFmLastPurgeDate: string | null;
    addrRecordChangeDate: string | null;
    addressType: number | null;
    altEmail: string;
    beneficialOwner: number | null;
    beneficialPercent: number | null;
    beneficiaryPercent: number | null;
    birthDate: string | null;
    carrierRoute: string;
    chapter4StatusCode: string;
    city: string;
    confidential: number | null;
    country: string;
    countryCode: string;
    crAddrChgDate: string | null;
    crNameChgDate: string | null;
    crSsnChgDate: string | null;
    creditReportAddrIndicator: string;
    creditReportAddrIndicatorDate: string | null;
    creditReportConsumerInfo: string;
    creditReportConsumerInfoDate: string | null;
    ctrExempt: number | null;
    currGrossMonthPay: number | null;
    currMonthPayChgDate: string | null;
    currNetMonthPay: number | null;
    dbaExtendedName: string;
    dbaFirst: string;
    dbaLast: string;
    dbaLongName: string;
    dbaMiddle: string;
    dbaNameFormat: number | null;
    dbaShortName: string;
    dbaSuffix: string;
    dbaTitle: string;
    deathDate: string | null;
    ecoaCode: number | null;
    effectiveDate: string | null;
    email: string;
    employerName: string;
    expirationDate: string | null;
    extendedName: string;
    extraAddress: string;
    extraInfo: string;
    first: string;
    fmLastPurgeDate: string | null;
    foreignTin: string;
    formW8OnFile: number | null;
    gIin: string;
    headquarters: number | null;
    homePhone: string;
    identDocFlag: LoanPledgeNameIdentDocFlag_2[];
    identIdDescription: LoanPledgeNameIdentIdDescription_2[];
    identIdExpireDate: LoanPledgeNameIdentIdExpireDate_2[];
    identIdIssueDate: LoanPledgeNameIdentIdIssueDate_2[];
    identIdNumber: LoanPledgeNameIdentIdNumber_2[];
    identIdType: LoanPledgeNameIdentIdType_2[];
    identIdVerifyDate: LoanPledgeNameIdentIdVerifyDate_2[];
    irs1042SAmendNum: number | null;
    irsCorrection: number | null;
    irsCountryCode: string;
    last: string;
    lastAddrChgDate: string | null;
    lastAddrVerifDate: string | null;
    lastFmDate: string | null;
    lei: string;
    license: string;
    lob: string;
    locator: number | null;
    longName: string;
    mailOverride: number | null;
    marketingAddress: number | null;
    mbrActivityDate: string | null;
    mbrAddrFileType: number | null;
    mbrAddrNumLink: string;
    mbrAddrNumLinkChgDate: string | null;
    mbrAddrNumber: string;
    mbrCreateDate: string | null;
    mbrDisconnectDate: string | null;
    mbrExpDate: string | null;
    mbrFileType: number | null;
    mbrFmLastDate: string | null;
    mbrFmLastPurgeDate: string | null;
    mbrRecordChangeDate: string | null;
    mbrStatus: number | null;
    mbrStatusFmDate: string | null;
    memberNumLink: string;
    memberNumLinkChgDate: string | null;
    memberNumber: string;
    middle: string;
    mobilePhone: string;
    mothersMaidenName: string;
    nameFormat: number | null;
    nonAcctNameNum: string;
    nraExemptionCode: string;
    nraTaxRate: number | null;
    occupation: string;
    pagerNumber: string;
    phoneType: number | null;
    preferredContact: string;
    preferredContactMethod: number | null;
    recordChangeDate: string | null;
    restrict: number | null;
    sex: string;
    shortName: string;
    ssn: string;
    ssnCertification: number | null;
    ssnOverride: number | null;
    ssnType: number | null;
    state: string;
    street: string;
    subType: number | null;
    substantialOwner: number | null;
    suffix: string;
    title: string;
    type: number | null;
    usPersonFlag: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    w8ExpirationDate: string | null;
    workPhone: string;
    workPhoneExtension: string;
    zipCode: string;
    version1: VersionType;
}