import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanAppFinance_2 {
    address: string;
    assetStatusValue: number;
    assetStatusValueSpecified: boolean;
    assetStatus: number | null;
    assetValueValue: number;
    assetValueValueSpecified: boolean;
    assetValue: number | null;
    creditLimitValue: number;
    creditLimitValueSpecified: boolean;
    creditLimit: number | null;
    debtRatioUseCodeValue: number;
    debtRatioUseCodeValueSpecified: boolean;
    debtRatioUseCode: number | null;
    description: string;
    interestRateValue: number;
    interestRateValueSpecified: boolean;
    interestRate: number | null;
    itemType: string;
    liabilityBalanceValue: number;
    liabilityBalanceValueSpecified: boolean;
    liabilityBalance: number | null;
    liabilityStatusValue: number;
    liabilityStatusValueSpecified: boolean;
    liabilityStatus: number | null;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    monthlyExpenseValue: number;
    monthlyExpenseValueSpecified: boolean;
    monthlyExpense: number | null;
    monthlyIncomeValue: number;
    monthlyIncomeValueSpecified: boolean;
    monthlyIncome: number | null;
    ownerCodeValue: number;
    ownerCodeValueSpecified: boolean;
    ownerCode: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    reference: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userPledgeCodeValue: number;
    userPledgeCodeValueSpecified: boolean;
    userPledgeCode: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}