import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanBillingFields {
    billedDateValue: boolean;
    billedDateValueSpecified: boolean;
    billedDate: boolean | null;
    dueDateValue: boolean;
    dueDateValueSpecified: boolean;
    dueDate: boolean | null;
    escrowBilledValue: boolean;
    escrowBilledValueSpecified: boolean;
    escrowBilled: boolean | null;
    escrowPeriodValue: boolean;
    escrowPeriodValueSpecified: boolean;
    escrowPeriod: boolean | null;
    escrowRemainValue: boolean;
    escrowRemainValueSpecified: boolean;
    escrowRemain: boolean | null;
    feesBilledValue: boolean;
    feesBilledValueSpecified: boolean;
    feesBilled: boolean | null;
    feesRemainValue: boolean;
    feesRemainValueSpecified: boolean;
    feesRemain: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    interestBilledValue: boolean;
    interestBilledValueSpecified: boolean;
    interestBilled: boolean | null;
    interestRemainValue: boolean;
    interestRemainValueSpecified: boolean;
    interestRemain: boolean | null;
    lastPaymentDateValue: boolean;
    lastPaymentDateValueSpecified: boolean;
    lastPaymentDate: boolean | null;
    lateChargeBilledValue: boolean;
    lateChargeBilledValueSpecified: boolean;
    lateChargeBilled: boolean | null;
    lateChargePeriodValue: boolean;
    lateChargePeriodValueSpecified: boolean;
    lateChargePeriod: boolean | null;
    lateChargeRemainValue: boolean;
    lateChargeRemainValueSpecified: boolean;
    lateChargeRemain: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    paymentValue: boolean;
    paymentValueSpecified: boolean;
    payment: boolean | null;
    princIntBilledValue: boolean;
    princIntBilledValueSpecified: boolean;
    princIntBilled: boolean | null;
    princIntRemainValue: boolean;
    princIntRemainValueSpecified: boolean;
    princIntRemain: boolean | null;
    principalBilledValue: boolean;
    principalBilledValueSpecified: boolean;
    principalBilled: boolean | null;
    principalRemainValue: boolean;
    principalRemainValueSpecified: boolean;
    principalRemain: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    salesTaxBilledValue: boolean;
    salesTaxBilledValueSpecified: boolean;
    salesTaxBilled: boolean | null;
    salesTaxRemainValue: boolean;
    salesTaxRemainValueSpecified: boolean;
    salesTaxRemain: boolean | null;
    seg0EscrowBilledValue: boolean;
    seg0EscrowBilledValueSpecified: boolean;
    seg0EscrowBilled: boolean | null;
    seg0EscrowRemainValue: boolean;
    seg0EscrowRemainValueSpecified: boolean;
    seg0EscrowRemain: boolean | null;
    seg0FeesBilledValue: boolean;
    seg0FeesBilledValueSpecified: boolean;
    seg0FeesBilled: boolean | null;
    seg0FeesRemainValue: boolean;
    seg0FeesRemainValueSpecified: boolean;
    seg0FeesRemain: boolean | null;
    seg0InterestBilledValue: boolean;
    seg0InterestBilledValueSpecified: boolean;
    seg0InterestBilled: boolean | null;
    seg0InterestRemainValue: boolean;
    seg0InterestRemainValueSpecified: boolean;
    seg0InterestRemain: boolean | null;
    seg0LateChargeBilledValue: boolean;
    seg0LateChargeBilledValueSpecified: boolean;
    seg0LateChargeBilled: boolean | null;
    seg0LateChargeRemainValue: boolean;
    seg0LateChargeRemainValueSpecified: boolean;
    seg0LateChargeRemain: boolean | null;
    seg0PaymentValue: boolean;
    seg0PaymentValueSpecified: boolean;
    seg0Payment: boolean | null;
    seg0PrincIntBilledValue: boolean;
    seg0PrincIntBilledValueSpecified: boolean;
    seg0PrincIntBilled: boolean | null;
    seg0PrincIntRemainValue: boolean;
    seg0PrincIntRemainValueSpecified: boolean;
    seg0PrincIntRemain: boolean | null;
    seg0PrincipalBilledValue: boolean;
    seg0PrincipalBilledValueSpecified: boolean;
    seg0PrincipalBilled: boolean | null;
    seg0PrincipalRemainValue: boolean;
    seg0PrincipalRemainValueSpecified: boolean;
    seg0PrincipalRemain: boolean | null;
    seg0SalesTaxBilledValue: boolean;
    seg0SalesTaxBilledValueSpecified: boolean;
    seg0SalesTaxBilled: boolean | null;
    seg0SalesTaxRemainValue: boolean;
    seg0SalesTaxRemainValueSpecified: boolean;
    seg0SalesTaxRemain: boolean | null;
    seg0TotalBilledValue: boolean;
    seg0TotalBilledValueSpecified: boolean;
    seg0TotalBilled: boolean | null;
    seg0TotalRemainValue: boolean;
    seg0TotalRemainValueSpecified: boolean;
    seg0TotalRemain: boolean | null;
    statusIndicatorValue: boolean;
    statusIndicatorValueSpecified: boolean;
    statusIndicator: boolean | null;
    totalBilledValue: boolean;
    totalBilledValueSpecified: boolean;
    totalBilled: boolean | null;
    totalRemainIngValue: boolean;
    totalRemainIngValueSpecified: boolean;
    totalRemainIng: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}