import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanBilling_2 {
    billedDateValue: string | null;
    billedDateValueSpecified: boolean;
    billedDate: string | null;
    dueDateValue: string | null;
    dueDateValueSpecified: boolean;
    dueDate: string | null;
    escrowBilledValue: number;
    escrowBilledValueSpecified: boolean;
    escrowBilled: number | null;
    escrowPeriodValue: number;
    escrowPeriodValueSpecified: boolean;
    escrowPeriod: number | null;
    escrowRemainValue: number;
    escrowRemainValueSpecified: boolean;
    escrowRemain: number | null;
    feesBilledValue: number;
    feesBilledValueSpecified: boolean;
    feesBilled: number | null;
    feesRemainValue: number;
    feesRemainValueSpecified: boolean;
    feesRemain: number | null;
    id: string;
    interestBilledValue: number;
    interestBilledValueSpecified: boolean;
    interestBilled: number | null;
    interestRemainValue: number;
    interestRemainValueSpecified: boolean;
    interestRemain: number | null;
    lastPaymentDateValue: string | null;
    lastPaymentDateValueSpecified: boolean;
    lastPaymentDate: string | null;
    lateChargeBilledValue: number;
    lateChargeBilledValueSpecified: boolean;
    lateChargeBilled: number | null;
    lateChargePeriodValue: number;
    lateChargePeriodValueSpecified: boolean;
    lateChargePeriod: number | null;
    lateChargeRemainValue: number;
    lateChargeRemainValueSpecified: boolean;
    lateChargeRemain: number | null;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    paymentValue: number;
    paymentValueSpecified: boolean;
    payment: number | null;
    princIntBilledValue: number;
    princIntBilledValueSpecified: boolean;
    princIntBilled: number | null;
    princIntRemainValue: number;
    princIntRemainValueSpecified: boolean;
    princIntRemain: number | null;
    principalBilledValue: number;
    principalBilledValueSpecified: boolean;
    principalBilled: number | null;
    principalRemainValue: number;
    principalRemainValueSpecified: boolean;
    principalRemain: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    salesTaxBilledValue: number;
    salesTaxBilledValueSpecified: boolean;
    salesTaxBilled: number | null;
    salesTaxRemainValue: number;
    salesTaxRemainValueSpecified: boolean;
    salesTaxRemain: number | null;
    seg0EscrowBilledValue: number;
    seg0EscrowBilledValueSpecified: boolean;
    seg0EscrowBilled: number | null;
    seg0EscrowRemainValue: number;
    seg0EscrowRemainValueSpecified: boolean;
    seg0EscrowRemain: number | null;
    seg0FeesBilledValue: number;
    seg0FeesBilledValueSpecified: boolean;
    seg0FeesBilled: number | null;
    seg0FeesRemainValue: number;
    seg0FeesRemainValueSpecified: boolean;
    seg0FeesRemain: number | null;
    seg0InterestBilledValue: number;
    seg0InterestBilledValueSpecified: boolean;
    seg0InterestBilled: number | null;
    seg0InterestRemainValue: number;
    seg0InterestRemainValueSpecified: boolean;
    seg0InterestRemain: number | null;
    seg0LateChargeBilledValue: number;
    seg0LateChargeBilledValueSpecified: boolean;
    seg0LateChargeBilled: number | null;
    seg0LateChargeRemainValue: number;
    seg0LateChargeRemainValueSpecified: boolean;
    seg0LateChargeRemain: number | null;
    seg0PaymentValue: number;
    seg0PaymentValueSpecified: boolean;
    seg0Payment: number | null;
    seg0PrincIntBilledValue: number;
    seg0PrincIntBilledValueSpecified: boolean;
    seg0PrincIntBilled: number | null;
    seg0PrincIntRemainValue: number;
    seg0PrincIntRemainValueSpecified: boolean;
    seg0PrincIntRemain: number | null;
    seg0PrincipalBilledValue: number;
    seg0PrincipalBilledValueSpecified: boolean;
    seg0PrincipalBilled: number | null;
    seg0PrincipalRemainValue: number;
    seg0PrincipalRemainValueSpecified: boolean;
    seg0PrincipalRemain: number | null;
    seg0SalesTaxBilledValue: number;
    seg0SalesTaxBilledValueSpecified: boolean;
    seg0SalesTaxBilled: number | null;
    seg0SalesTaxRemainValue: number;
    seg0SalesTaxRemainValueSpecified: boolean;
    seg0SalesTaxRemain: number | null;
    seg0TotalBilledValue: number;
    seg0TotalBilledValueSpecified: boolean;
    seg0TotalBilled: number | null;
    seg0TotalRemainValue: number;
    seg0TotalRemainValueSpecified: boolean;
    seg0TotalRemain: number | null;
    statusIndicatorValue: number;
    statusIndicatorValueSpecified: boolean;
    statusIndicator: number | null;
    totalBilledValue: number;
    totalBilledValueSpecified: boolean;
    totalBilled: number | null;
    totalRemainIngValue: number;
    totalRemainIngValueSpecified: boolean;
    totalRemainIng: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}