import { VersionType } from "./versionType";

export interface LoanAppPersonFields {
    accountNumber: boolean | null;
    activeDuty: boolean | null;
    activeDutySeparationDate: boolean | null;
    activeDutyStartDate: boolean | null;
    activeDutyVerificationDate: boolean | null;
    addressType: boolean | null;
    altEmail: boolean | null;
    bankruptcy: boolean | null;
    beneficialOwner: boolean | null;
    beneficialPercent: boolean | null;
    birthDate: boolean | null;
    citizenship: boolean | null;
    city: boolean | null;
    cosignForWhom: boolean | null;
    cosignOtherLoan: boolean | null;
    cosignToWhom: boolean | null;
    country: boolean | null;
    countryCode: boolean | null;
    county: boolean | null;
    currEmpAddress: boolean | null;
    currEmpEndDate: boolean | null;
    currEmpGrossMonthlyPay: boolean | null;
    currEmpMonthsEmp: boolean | null;
    currEmpName: boolean | null;
    currEmpNetMonthlyPay: boolean | null;
    currEmpOccupation: boolean | null;
    currEmpStartDate: boolean | null;
    currEmpSupervisor: boolean | null;
    currEmpYearsEmp: boolean | null;
    dependentAge: number[];
    dependentCount: boolean | null;
    derogExplanation: boolean | null;
    derogStatus: number[];
    driversLic: boolean | null;
    driversLicState: boolean | null;
    educationYears: boolean | null;
    email: boolean | null;
    empHoursPerWeek: boolean | null;
    employmentReturnDate: boolean | null;
    employmentStatus: boolean | null;
    extendedName: boolean | null;
    extraAddress: boolean | null;
    extraInfo: boolean | null;
    first: boolean | null;
    headquarters: boolean | null;
    hmdaAge: boolean | null;
    hmdaAppScoringModel: boolean | null;
    hmdaAppScoringModelOther: number[];
    hmdaCreditScore: boolean | null;
    hmdaEthnicity: number[];
    hmdaEthnicityOther: number[];
    hmdaEthnicityVisInd: boolean | null;
    hmdaRace: number[];
    hmdaRaceOther1: number[];
    hmdaRaceOther27: number[];
    hmdaRaceOther44: number[];
    hmdaRaceVisInd: boolean | null;
    hmdaSexInd: boolean | null;
    hmdaSexVisInd: boolean | null;
    homePhone: boolean | null;
    identDocFlag: number[];
    identIdDescription: number[];
    identIdExpireDate: number[];
    identIdIssueDate: number[];
    identIdNumber: number[];
    identIdType: number[];
    identIdVerifyDate: number[];
    incomeMayDecline: boolean | null;
    judgement: boolean | null;
    last: boolean | null;
    lei: boolean | null;
    locator: boolean | null;
    longName: boolean | null;
    maritalStatus: boolean | null;
    middle: boolean | null;
    mobilePhone: boolean | null;
    monthsCurrAddress: boolean | null;
    monthsPrevAddress: boolean | null;
    mothersMaidenName: boolean | null;
    nameFormat: boolean | null;
    otherCreditName: boolean | null;
    ownRentCurrAddress: boolean | null;
    ownRentPrevAddress: boolean | null;
    pagerNumber: boolean | null;
    partyInLawsuit: boolean | null;
    pastForeclosure: boolean | null;
    pastRepossession: boolean | null;
    personCode: boolean | null;
    phoneType: boolean | null;
    preferredContact: boolean | null;
    preferredContactMethod: boolean | null;
    prevEmpAddress: boolean | null;
    prevEmpEndDate: boolean | null;
    prevEmpGrossMonthlyPay: boolean | null;
    prevEmpMonthsEmp: boolean | null;
    prevEmpName: boolean | null;
    prevEmpOccupation: boolean | null;
    prevEmpStartDate: boolean | null;
    prevEmpSupervisor: boolean | null;
    prevEmpYearsEmp: boolean | null;
    previousAddress: boolean | null;
    recordChangeDate: boolean | null;
    ref1Address: boolean | null;
    ref1AddressType: boolean | null;
    ref1Code: boolean | null;
    ref1Name: boolean | null;
    ref1Phone: boolean | null;
    ref1Relationship: boolean | null;
    ref2Address: boolean | null;
    ref2AddressType: boolean | null;
    ref2Code: boolean | null;
    ref2Name: boolean | null;
    ref2Phone: boolean | null;
    ref2Relationship: boolean | null;
    ref3Address: boolean | null;
    ref3AddressType: boolean | null;
    ref3Code: boolean | null;
    ref3Name: boolean | null;
    ref3Phone: boolean | null;
    ref3Relationship: boolean | null;
    sex: boolean | null;
    shortName: boolean | null;
    ssn: boolean | null;
    state: boolean | null;
    street: boolean | null;
    suffix: boolean | null;
    title: boolean | null;
    type: boolean | null;
    usPersonFlag: boolean | null;
    workPhone: boolean | null;
    workPhoneExtension: boolean | null;
    zipCode: boolean | null;
    version1: VersionType;
}