import { LoanCheckOrderBusCaptions_2 } from "./loanCheckOrderBusCaptions_2";
import { LoanCheckOrderImprintLine_2 } from "./loanCheckOrderImprintLine_2";
import { LoanCheckOrderImprintLineSize_2 } from "./loanCheckOrderImprintLineSize_2";
import { LoanCheckOrderImprintUsage_2 } from "./loanCheckOrderImprintUsage_2";
import { LoanCheckOrderLicense_2 } from "./loanCheckOrderLicense_2";
import { LoanCheckOrderMailAddress_2 } from "./loanCheckOrderMailAddress_2";
import { LoanCheckOrderOverSigLine_2 } from "./loanCheckOrderOverSigLine_2";
import { LoanCheckOrderSpecialInstr_2 } from "./loanCheckOrderSpecialInstr_2";
import { LoanCheckOrderSsn_2 } from "./loanCheckOrderSsn_2";
import { VersionType } from "./versionType";

export interface LoanCheckOrder_2 {
    accent: string;
    acctAddrInkColor: number | null;
    billingCode: number | null;
    binding: string;
    branch: number | null;
    busBindingStyle: number | null;
    busCaptions: LoanCheckOrderBusCaptions_2[];
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFont: number | null;
    imprintJustify: number | null;
    imprintLine: LoanCheckOrderImprintLine_2[];
    imprintLineSize: LoanCheckOrderImprintLineSize_2[];
    imprintPhone: string;
    imprintState: string;
    imprintUsage: LoanCheckOrderImprintUsage_2[];
    imprintZipCode: string;
    lastFmDate: string | null;
    lastFreeOrder: string | null;
    lastOrderDate: string | null;
    license: LoanCheckOrderLicense_2[];
    locator: number | null;
    mailAddress: LoanCheckOrderMailAddress_2[];
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLines: number | null;
    openDate: string | null;
    overSigFont: number | null;
    overSigJustify: number | null;
    overSigLine: LoanCheckOrderOverSigLine_2[];
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processor: number | null;
    promoNumber: string;
    quantity: number | null;
    recordChangeDate: string | null;
    rerunReason: number | null;
    shipMethod: number | null;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: LoanCheckOrderSpecialInstr_2[];
    ssn: LoanCheckOrderSsn_2[];
    startNumber: number | null;
    status: number | null;
    statusDate: string | null;
    taxExemptCode: number | null;
    titleInkColor: number | null;
    userId: number | null;
    version1: VersionType;
}