import { LoanEscrowAnalysisNewEscrowPayment_2 } from "./loanEscrowAnalysisNewEscrowPayment_2";
import { LoanEscrowAnalysisNewPaymentDate_2 } from "./loanEscrowAnalysisNewPaymentDate_2";
import { LoanEscrowAnalysisPrevNewEscrowPmt_2 } from "./loanEscrowAnalysisPrevNewEscrowPmt_2";
import { LoanEscrowAnalysisPrevNewPmtDate_2 } from "./loanEscrowAnalysisPrevNewPmtDate_2";
import { VersionType } from "./versionType";

export interface LoanEscrowAnalysis_2 {
    actionDeficiency: number | null;
    actionShortage: number | null;
    actualInitialDiscl: string | null;
    amtAddedRounding: number | null;
    amtCoverDeficiency: number | null;
    amtCoverShortage: number | null;
    analysisGroup: number | null;
    analysisThruDate: string | null;
    changeEscrowPmt: number | null;
    closingRequest: number | null;
    currentBalance: number | null;
    currentDueDay1: number | null;
    currentDueDay2: number | null;
    currentPayment: number | null;
    currentPaymentFreq: number | null;
    cushion: number | null;
    dateAnalysisCalc: string | null;
    dateInitDisclNeed: string | null;
    deficiency: number | null;
    expectedBegStmtBal: number | null;
    finalAnalysisDate: string | null;
    forecastBegStmtBal: number | null;
    initialDisclThird: number | null;
    lastAnalysisProcessed: number | null;
    locator: number | null;
    newEscrowPayment: LoanEscrowAnalysisNewEscrowPayment_2[];
    newPaymentDate: LoanEscrowAnalysisNewPaymentDate_2[];
    nextAnalysisDate: string | null;
    nextPaymentDueDate: string | null;
    noticeClosingDate: string | null;
    noticeClosingFee: number | null;
    noticeDate: string | null;
    overage: number | null;
    overageRefunded: number | null;
    pmtReducedOverage: number | null;
    prevActionDefic: number | null;
    prevActionShortage: number | null;
    prevAmtAddedRound: number | null;
    prevAmtCoverDef: number | null;
    prevAmtCoverShort: number | null;
    prevAnalyThruDate: string | null;
    prevAnalysisDate: string | null;
    prevBalance: number | null;
    prevChgEscrowPmt: number | null;
    prevCushion: number | null;
    prevDateAnalyCalc: string | null;
    prevDeficiency: number | null;
    prevDueDay1: number | null;
    prevDueDay2: number | null;
    prevExpBegStmtBal: number | null;
    prevFcastBegStmtBl: number | null;
    prevNewEscrowPmt: LoanEscrowAnalysisPrevNewEscrowPmt_2[];
    prevNewPmtDate: LoanEscrowAnalysisPrevNewPmtDate_2[];
    prevOverRefunded: number | null;
    prevOverage: number | null;
    prevPayment: number | null;
    prevPaymentDueDate: string | null;
    prevPaymentFreq: number | null;
    prevPmtReducedOver: number | null;
    prevRequiredPmt: number | null;
    prevShortage: number | null;
    priorAnalysisSource: number | null;
    recordChangeDate: string | null;
    remainOpenOption: number | null;
    requiredNewPayment: number | null;
    shortage: number | null;
    version1: VersionType;
}