import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanEscrowAnalysisFields {
    actionDeficiencyValue: boolean;
    actionDeficiencyValueSpecified: boolean;
    actionDeficiency: boolean | null;
    actionShortageValue: boolean;
    actionShortageValueSpecified: boolean;
    actionShortage: boolean | null;
    actualInitialDisclValue: boolean;
    actualInitialDisclValueSpecified: boolean;
    actualInitialDiscl: boolean | null;
    amtAddedRoundingValue: boolean;
    amtAddedRoundingValueSpecified: boolean;
    amtAddedRounding: boolean | null;
    amtCoverDeficiencyValue: boolean;
    amtCoverDeficiencyValueSpecified: boolean;
    amtCoverDeficiency: boolean | null;
    amtCoverShortageValue: boolean;
    amtCoverShortageValueSpecified: boolean;
    amtCoverShortage: boolean | null;
    analysisGroupValue: boolean;
    analysisGroupValueSpecified: boolean;
    analysisGroup: boolean | null;
    analysisThruDateValue: boolean;
    analysisThruDateValueSpecified: boolean;
    analysisThruDate: boolean | null;
    changeEscrowPmtValue: boolean;
    changeEscrowPmtValueSpecified: boolean;
    changeEscrowPmt: boolean | null;
    closingRequestValue: boolean;
    closingRequestValueSpecified: boolean;
    closingRequest: boolean | null;
    currentBalanceValue: boolean;
    currentBalanceValueSpecified: boolean;
    currentBalance: boolean | null;
    currentDueDay1Value: boolean;
    currentDueDay1ValueSpecified: boolean;
    currentDueDay1: boolean | null;
    currentDueDay2Value: boolean;
    currentDueDay2ValueSpecified: boolean;
    currentDueDay2: boolean | null;
    currentPaymentValue: boolean;
    currentPaymentValueSpecified: boolean;
    currentPayment: boolean | null;
    currentPaymentFreqValue: boolean;
    currentPaymentFreqValueSpecified: boolean;
    currentPaymentFreq: boolean | null;
    cushionValue: boolean;
    cushionValueSpecified: boolean;
    cushion: boolean | null;
    dateAnalysisCalcValue: boolean;
    dateAnalysisCalcValueSpecified: boolean;
    dateAnalysisCalc: boolean | null;
    dateInitDisclNeedValue: boolean;
    dateInitDisclNeedValueSpecified: boolean;
    dateInitDisclNeed: boolean | null;
    deficiencyValue: boolean;
    deficiencyValueSpecified: boolean;
    deficiency: boolean | null;
    expectedBegStmtBalValue: boolean;
    expectedBegStmtBalValueSpecified: boolean;
    expectedBegStmtBal: boolean | null;
    finalAnalysisDateValue: boolean;
    finalAnalysisDateValueSpecified: boolean;
    finalAnalysisDate: boolean | null;
    forecastBegStmtBalValue: boolean;
    forecastBegStmtBalValueSpecified: boolean;
    forecastBegStmtBal: boolean | null;
    initialDisclThirdValue: boolean;
    initialDisclThirdValueSpecified: boolean;
    initialDisclThird: boolean | null;
    lastAnalysisProcessedValue: boolean;
    lastAnalysisProcessedValueSpecified: boolean;
    lastAnalysisProcessed: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    newEscrowPayment: number[];
    newEscrowPaymentSpecified: boolean;
    newPaymentDate: number[];
    newPaymentDateSpecified: boolean;
    nextAnalysisDateValue: boolean;
    nextAnalysisDateValueSpecified: boolean;
    nextAnalysisDate: boolean | null;
    nextPaymentDueDateValue: boolean;
    nextPaymentDueDateValueSpecified: boolean;
    nextPaymentDueDate: boolean | null;
    noticeClosingDateValue: boolean;
    noticeClosingDateValueSpecified: boolean;
    noticeClosingDate: boolean | null;
    noticeClosingFeeValue: boolean;
    noticeClosingFeeValueSpecified: boolean;
    noticeClosingFee: boolean | null;
    noticeDateValue: boolean;
    noticeDateValueSpecified: boolean;
    noticeDate: boolean | null;
    overageValue: boolean;
    overageValueSpecified: boolean;
    overage: boolean | null;
    overageRefundedValue: boolean;
    overageRefundedValueSpecified: boolean;
    overageRefunded: boolean | null;
    pmtReducedOverageValue: boolean;
    pmtReducedOverageValueSpecified: boolean;
    pmtReducedOverage: boolean | null;
    prevActionDeficValue: boolean;
    prevActionDeficValueSpecified: boolean;
    prevActionDefic: boolean | null;
    prevActionShortageValue: boolean;
    prevActionShortageValueSpecified: boolean;
    prevActionShortage: boolean | null;
    prevAmtAddedRoundValue: boolean;
    prevAmtAddedRoundValueSpecified: boolean;
    prevAmtAddedRound: boolean | null;
    prevAmtCoverDefValue: boolean;
    prevAmtCoverDefValueSpecified: boolean;
    prevAmtCoverDef: boolean | null;
    prevAmtCoverShortValue: boolean;
    prevAmtCoverShortValueSpecified: boolean;
    prevAmtCoverShort: boolean | null;
    prevAnalyThruDateValue: boolean;
    prevAnalyThruDateValueSpecified: boolean;
    prevAnalyThruDate: boolean | null;
    prevAnalysisDateValue: boolean;
    prevAnalysisDateValueSpecified: boolean;
    prevAnalysisDate: boolean | null;
    prevBalanceValue: boolean;
    prevBalanceValueSpecified: boolean;
    prevBalance: boolean | null;
    prevChgEscrowPmtValue: boolean;
    prevChgEscrowPmtValueSpecified: boolean;
    prevChgEscrowPmt: boolean | null;
    prevCushionValue: boolean;
    prevCushionValueSpecified: boolean;
    prevCushion: boolean | null;
    prevDateAnalyCalcValue: boolean;
    prevDateAnalyCalcValueSpecified: boolean;
    prevDateAnalyCalc: boolean | null;
    prevDeficiencyValue: boolean;
    prevDeficiencyValueSpecified: boolean;
    prevDeficiency: boolean | null;
    prevDueDay1Value: boolean;
    prevDueDay1ValueSpecified: boolean;
    prevDueDay1: boolean | null;
    prevDueDay2Value: boolean;
    prevDueDay2ValueSpecified: boolean;
    prevDueDay2: boolean | null;
    prevExpBegStmtBalValue: boolean;
    prevExpBegStmtBalValueSpecified: boolean;
    prevExpBegStmtBal: boolean | null;
    prevFcastBegStmtBlValue: boolean;
    prevFcastBegStmtBlValueSpecified: boolean;
    prevFcastBegStmtBl: boolean | null;
    prevNewEscrowPmt: number[];
    prevNewEscrowPmtSpecified: boolean;
    prevNewPmtDate: number[];
    prevNewPmtDateSpecified: boolean;
    prevOverRefundedValue: boolean;
    prevOverRefundedValueSpecified: boolean;
    prevOverRefunded: boolean | null;
    prevOverageValue: boolean;
    prevOverageValueSpecified: boolean;
    prevOverage: boolean | null;
    prevPaymentValue: boolean;
    prevPaymentValueSpecified: boolean;
    prevPayment: boolean | null;
    prevPaymentDueDateValue: boolean;
    prevPaymentDueDateValueSpecified: boolean;
    prevPaymentDueDate: boolean | null;
    prevPaymentFreqValue: boolean;
    prevPaymentFreqValueSpecified: boolean;
    prevPaymentFreq: boolean | null;
    prevPmtReducedOverValue: boolean;
    prevPmtReducedOverValueSpecified: boolean;
    prevPmtReducedOver: boolean | null;
    prevRequiredPmtValue: boolean;
    prevRequiredPmtValueSpecified: boolean;
    prevRequiredPmt: boolean | null;
    prevShortageValue: boolean;
    prevShortageValueSpecified: boolean;
    prevShortage: boolean | null;
    priorAnalysisSourceValue: boolean;
    priorAnalysisSourceValueSpecified: boolean;
    priorAnalysisSource: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    remainOpenOptionValue: boolean;
    remainOpenOptionValueSpecified: boolean;
    remainOpenOption: boolean | null;
    requiredNewPaymentValue: boolean;
    requiredNewPaymentValueSpecified: boolean;
    requiredNewPayment: boolean | null;
    shortageValue: boolean;
    shortageValueSpecified: boolean;
    shortage: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}