import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanAppEscrow_2 {
    day1Value: number;
    day1ValueSpecified: boolean;
    day1: number | null;
    day2Value: number;
    day2ValueSpecified: boolean;
    day2: number | null;
    distribFrequencyValue: number;
    distribFrequencyValueSpecified: boolean;
    distribFrequency: number | null;
    escrowTypeValue: number;
    escrowTypeValueSpecified: boolean;
    escrowType: number | null;
    expirationDateValue: string | null;
    expirationDateValueSpecified: boolean;
    expirationDate: string | null;
    floodInsTrackingValue: number;
    floodInsTrackingValueSpecified: boolean;
    floodInsTracking: number | null;
    forcedPlacedInsValue: number;
    forcedPlacedInsValueSpecified: boolean;
    forcedPlacedIns: number | null;
    invoiceNumber: string;
    lastAmtNeededPmtValue: number;
    lastAmtNeededPmtValueSpecified: boolean;
    lastAmtNeededPmt: number | null;
    lastDateAnaCalcValue: string | null;
    lastDateAnaCalcValueSpecified: boolean;
    lastDateAnaCalc: string | null;
    lastDisbursAmtValue: number;
    lastDisbursAmtValueSpecified: boolean;
    lastDisbursAmt: number | null;
    lastDisbursDateValue: string | null;
    lastDisbursDateValueSpecified: boolean;
    lastDisbursDate: string | null;
    lastDisbursFreqValue: number;
    lastDisbursFreqValueSpecified: boolean;
    lastDisbursFreq: number | null;
    lastDisburseDay1Value: number;
    lastDisburseDay1ValueSpecified: boolean;
    lastDisburseDay1: number | null;
    lastDisburseDay2Value: number;
    lastDisburseDay2ValueSpecified: boolean;
    lastDisburseDay2: number | null;
    lastDistribAmountValue: number;
    lastDistribAmountValueSpecified: boolean;
    lastDistribAmount: number | null;
    lastDistribDateValue: string | null;
    lastDistribDateValueSpecified: boolean;
    lastDistribDate: string | null;
    lastExpirationDateValue: string | null;
    lastExpirationDateValueSpecified: boolean;
    lastExpirationDate: string | null;
    lastMonthCushionValue: number;
    lastMonthCushionValueSpecified: boolean;
    lastMonthCushion: number | null;
    lastNbrPmtsDueValue: number;
    lastNbrPmtsDueValueSpecified: boolean;
    lastNbrPmtsDue: number | null;
    lastTotAnnDisbursValue: number;
    lastTotAnnDisbursValueSpecified: boolean;
    lastTotAnnDisburs: number | null;
    legalDescription: string;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    nextDistribAmountValue: number;
    nextDistribAmountValueSpecified: boolean;
    nextDistribAmount: number | null;
    nextDistribDateValue: string | null;
    nextDistribDateValueSpecified: boolean;
    nextDistribDate: string | null;
    parcelNumber: string;
    payDividendValue: number;
    payDividendValueSpecified: boolean;
    payDividend: number | null;
    paymentPortionValue: number;
    paymentPortionValueSpecified: boolean;
    paymentPortion: number | null;
    pmiCancelDateValue: string | null;
    pmiCancelDateValueSpecified: boolean;
    pmiCancelDate: string | null;
    pmiCancelNoticeValue: number;
    pmiCancelNoticeValueSpecified: boolean;
    pmiCancelNotice: number | null;
    pmiDisclosureDateValue: string | null;
    pmiDisclosureDateValueSpecified: boolean;
    pmiDisclosureDate: string | null;
    pmiEligNoticesValue: number;
    pmiEligNoticesValueSpecified: boolean;
    pmiEligNotices: number | null;
    pmiMidTermDateValue: string | null;
    pmiMidTermDateValueSpecified: boolean;
    pmiMidTermDate: string | null;
    pmiTermDateValue: string | null;
    pmiTermDateValueSpecified: boolean;
    pmiTermDate: string | null;
    policyAmountValue: number;
    policyAmountValueSpecified: boolean;
    policyAmount: number | null;
    policyExpireDateValue: string | null;
    policyExpireDateValueSpecified: boolean;
    policyExpireDate: string | null;
    policyNumber: string;
    policyOrigDateValue: string | null;
    policyOrigDateValueSpecified: boolean;
    policyOrigDate: string | null;
    policyOwner: string;
    prevAmtNeededPmtValue: number;
    prevAmtNeededPmtValueSpecified: boolean;
    prevAmtNeededPmt: number | null;
    prevDateAnaCalcValue: string | null;
    prevDateAnaCalcValueSpecified: boolean;
    prevDateAnaCalc: string | null;
    prevDisbursAmtValue: number;
    prevDisbursAmtValueSpecified: boolean;
    prevDisbursAmt: number | null;
    prevDisbursDateValue: string | null;
    prevDisbursDateValueSpecified: boolean;
    prevDisbursDate: string | null;
    prevDisbursFreqValue: number;
    prevDisbursFreqValueSpecified: boolean;
    prevDisbursFreq: number | null;
    prevDisburseDay1Value: number;
    prevDisburseDay1ValueSpecified: boolean;
    prevDisburseDay1: number | null;
    prevDisburseDay2Value: number;
    prevDisburseDay2ValueSpecified: boolean;
    prevDisburseDay2: number | null;
    prevExpirationDateValue: string | null;
    prevExpirationDateValueSpecified: boolean;
    prevExpirationDate: string | null;
    prevMonthCushionValue: number;
    prevMonthCushionValueSpecified: boolean;
    prevMonthCushion: number | null;
    prevNbrPmtsDueValue: number;
    prevNbrPmtsDueValueSpecified: boolean;
    prevNbrPmtsDue: number | null;
    prevTotAnnDisbursValue: number;
    prevTotAnnDisbursValueSpecified: boolean;
    prevTotAnnDisburs: number | null;
    printDistribNoticeValue: number;
    printDistribNoticeValueSpecified: boolean;
    printDistribNotice: number | null;
    realEstateOwner: string;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    savedAdjustPaymentValue: number;
    savedAdjustPaymentValueSpecified: boolean;
    savedAdjustPayment: number | null;
    taxRefNumber: string;
    trackingOnlyValue: number;
    trackingOnlyValueSpecified: boolean;
    trackingOnly: number | null;
    vendorName: string;
    vendorNumber: string;
    version1: VersionType;
    pmiCancelReasonValue: number;
    pmiCancelReasonValueSpecified: boolean;
    pmiCancelReason: number | null;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}