import { LoanAppBureauScore_2 } from "./loanAppBureauScore_2";
import { LoanAppCbiLocator_2 } from "./loanAppCbiLocator_2";
import { LoanAppCompletedActions_2 } from "./loanAppCompletedActions_2";
import { LoanAppCuTotalsAcctNumber_2 } from "./loanAppCuTotalsAcctNumber_2";
import { LoanAppDebtRatio_2 } from "./loanAppDebtRatio_2";
import { LoanAppDebtRatioType_2 } from "./loanAppDebtRatioType_2";
import { LoanAppDenialReason_2 } from "./loanAppDenialReason_2";
import { LoanAppHmdaAutoUnderwritingResOther_2 } from "./loanAppHmdaAutoUnderwritingResOther_2";
import { LoanAppHmdaAutoUnderwritingResult_2 } from "./loanAppHmdaAutoUnderwritingResult_2";
import { LoanAppHmdaAutoUnderwritingSys_2 } from "./loanAppHmdaAutoUnderwritingSys_2";
import { LoanAppHmdaAutoUnderwritingSysOther_2 } from "./loanAppHmdaAutoUnderwritingSysOther_2";
import { LoanAppHmdaDenialReasonOther_2 } from "./loanAppHmdaDenialReasonOther_2";
import { VersionType } from "./versionType";

export interface LoanApp_2 {
    accountType: number | null;
    amortizationSchd: number | null;
    amortizationSchdType: number | null;
    applicationDate: string | null;
    applyAsBilled: number | null;
    appraisalOffset: number | null;
    appraisedAmount: number | null;
    approvalAmount: number | null;
    approvalCode: number | null;
    approvalDate: string | null;
    apr: number | null;
    assessorParcelNumber: string;
    balloonAmount: number | null;
    balloonDate: string | null;
    billingDefaultDays: number | null;
    billingMethod: number | null;
    billingNotice: number | null;
    billingNoticeMin: number | null;
    borrowDate: string | null;
    branch: number | null;
    btLimitMax: number | null;
    btPercent: number | null;
    bureauScore: LoanAppBureauScore_2[];
    caLimitMax: number | null;
    caPercent: number | null;
    callItemSchd: number | null;
    callItemSchdType: number | null;
    cancellationDate: string | null;
    cbiLocator: LoanAppCbiLocator_2[];
    censusTract: string;
    citySalesTaxRate: number | null;
    closingDate: string | null;
    cntySalesTaxRate: number | null;
    collateralCode: number | null;
    collateralDate: string | null;
    combinedCaBtLimitMax: number | null;
    combinedCaBtPercent: number | null;
    comboLnSegmentMax: number | null;
    comboPmtOrderMeth: number | null;
    comboSeg0PmtOrder: number | null;
    completedActions: LoanAppCompletedActions_2[];
    counterOfferExpireDate: string | null;
    counteredOrigAmt: number | null;
    createdAtBranch: number | null;
    createdByUser: number | null;
    creationDate: string | null;
    creditBureau: number | null;
    creditLimit: number | null;
    creditScore: number | null;
    creditScoreType: number | null;
    cuTotalCertIras: number | null;
    cuTotalClosedEndLoans: number | null;
    cuTotalClosedEndPayments: number | null;
    cuTotalCredCardPayments: number | null;
    cuTotalCreditCardLoans: number | null;
    cuTotalCreditLimit: number | null;
    cuTotalDrafts: number | null;
    cuTotalLocLoans: number | null;
    cuTotalLocPayments: number | null;
    cuTotalOpenEndLoans: number | null;
    cuTotalOpenEndPayments: number | null;
    cuTotalShares: number | null;
    cuTotalsAcctNumber: LoanAppCuTotalsAcctNumber_2[];
    dealerCity: string;
    dealerCode: string;
    dealerCounty: string;
    dealerReserve: number | null;
    dealerState: string;
    debtRatio: LoanAppDebtRatio_2[];
    debtRatioType: LoanAppDebtRatioType_2[];
    decisionCode: number | null;
    decisionDate: string | null;
    denialDate: string | null;
    denialReason: LoanAppDenialReason_2[];
    discountRate: number | null;
    dqCalculationMethod: number | null;
    dueDateAdvanceCode: number | null;
    dueDay1: number | null;
    dueDay2: number | null;
    ecoaCode: number | null;
    effectiveApr: number | null;
    effectiveDate: string | null;
    escrowAmount: number | null;
    escrowId: string;
    event: number | null;
    eventDate: string | null;
    exceedLevelPmtAmt: number | null;
    existIngLoanBalance: number | null;
    existIngLoanId: string;
    expirationDate: string | null;
    fasb91Code: number | null;
    firstDueDate: string | null;
    firstInsBirthDate: string | null;
    fixedDealerCityTaxRate: number | null;
    fixedDealerCountyTaxRate: number | null;
    fixedDealerStateTaxRate: number | null;
    fixedLesseeCityTaxRate: number | null;
    fixedLesseeCountyTaxRate: number | null;
    fixedLesseeStateTaxRate: number | null;
    formType: number | null;
    grossMonthlyPay1: number | null;
    grossMonthlyPay2: number | null;
    highRiskCode: number | null;
    hmdaActionTaken: number | null;
    hmdaActionTakenDate: string | null;
    hmdaAnnualIncome: number | null;
    hmdaAnnualIncomeNa: number | null;
    hmdaApplicationDateNa: number | null;
    hmdaAutoUnderwritingResOther: LoanAppHmdaAutoUnderwritingResOther_2[];
    hmdaAutoUnderwritingResult: LoanAppHmdaAutoUnderwritingResult_2[];
    hmdaAutoUnderwritingSys: LoanAppHmdaAutoUnderwritingSys_2[];
    hmdaAutoUnderwritingSysOther: LoanAppHmdaAutoUnderwritingSysOther_2[];
    hmdaBusOrCommPurposeInd: number | null;
    hmdaCensusTract: string;
    hmdaCensusTractNa: number | null;
    hmdaConstructionMethod: number | null;
    hmdaDebtRationA: number | null;
    hmdaDenialReasonOther: LoanAppHmdaDenialReasonOther_2[];
    hmdaDiscountPoints: number | null;
    hmdaDiscountPointsNa: number | null;
    hmdaHoePastAtUs: number | null;
    hmdaInitPayableToInst: number | null;
    hmdaIntOnlyPmtInd: number | null;
    hmdaInterestRateNa: number | null;
    hmdaIntroRatePeriod: number | null;
    hmdaIntroRatePeriodNa: number | null;
    hmdaLenderCredits: number | null;
    hmdaLenderCreditsNa: number | null;
    hmdaLienStatus: number | null;
    hmdaLoanPurpose: number | null;
    hmdaLoanTermNa: number | null;
    hmdaLoanType: number | null;
    hmdaMfdHomeSecPropType: number | null;
    hmdaMfdHomelandPropInt: number | null;
    hmdaMultifamilyAffordUnits: number | null;
    hmdaMultifamilyAffordUnitsNa: number | null;
    hmdaNegAmortInd: number | null;
    hmdaNmlsrId: string;
    hmdaNmlsrIdNa: number | null;
    hmdaOccupancyType: number | null;
    hmdaOeLocInd: number | null;
    hmdaOriginationCharges: number | null;
    hmdaOriginationChargesNa: number | null;
    hmdaOtherNonAmortFeatures: number | null;
    hmdaPreapproval: number | null;
    hmdaPrepaymentPenaltyTerm: number | null;
    hmdaPrepaymentPenaltyTermNa: number | null;
    hmdaPropertyCity: string;
    hmdaPropertyCityNa: number | null;
    hmdaPropertyCounty: string;
    hmdaPropertyCountyNa: number | null;
    hmdaPropertyState: string;
    hmdaPropertyStateNa: number | null;
    hmdaPropertyStreetAddress: string;
    hmdaPropertyStreetAddressNa: number | null;
    hmdaPropertyZipCode: string;
    hmdaPropertyZipCodeNa: number | null;
    hmdaPurchaserType: number | null;
    hmdaRateSpread: number | null;
    hmdaRateSpreadNa: number | null;
    hmdaRateSpreadSign: number | null;
    hmdaRevMortInd: number | null;
    hmdaSubmissionOfApMethod: number | null;
    hmdaTotalLoanCosts: number | null;
    hmdaTotalLoanCostsNa: number | null;
    hmdaTotalPointsFees: number | null;
    hmdaTotalPointsFeesNa: number | null;
    hmdaTotalUnits: number | null;
    hmdaUniversalLoanIdentifier1: string;
    hmdaUniversalLoanIdentifier2: string;
    id: string;
    indirectDealerNum: string;
    indirectPlanId: string;
    infoRequestDate: string | null;
    initialBcdSettingOption: number | null;
    insurabilityCode: number | null;
    insurance1Chosen: number | null;
    insurance2Chosen: number | null;
    insurance3Chosen: number | null;
    insuranceMax: number | null;
    insuranceType: number | null;
    interestRate: number | null;
    interestType: number | null;
    lastFmDate: string | null;
    leaseDispositionDate: string | null;
    leaseDispositionFee: number | null;
    leaseTerminateDate: string | null;
    leaseTerminateFee: number | null;
    lesseeCity: string;
    lesseeCounty: string;
    lesseeState: string;
    levelPaymentAmt: number | null;
    levelPrincipalAmt: number | null;
    limitExpirationDate: string | null;
    loanAmount: number | null;
    loanCode: number | null;
    loanDescription: string;
    loanMaturityDate: string | null;
    loanReference: string;
    loanType: number | null;
    maxDueDateAdvancePeriod: number | null;
    militaryAprLoan: number | null;
    minimumPayment: number | null;
    mtgNumProp: number | null;
    netMonthlyPay1: number | null;
    netMonthlyPay2: number | null;
    newSegCutoffDays: number | null;
    newSegCutoffOption: number | null;
    notePurgeDate: string | null;
    origRiskGrade: string;
    originalRate: number | null;
    ovlAuthFee: number | null;
    ovlOptIn: number | null;
    payment: number | null;
    paymentCalcType: number | null;
    paymentFrequency: number | null;
    paymentMethod: number | null;
    paymentSkipStartDay: number | null;
    paymentSkips: number | null;
    paymentType: number | null;
    pendingDate: string | null;
    percentPrincipal: number | null;
    pmiLtvRatio: number | null;
    pmiPurchasePrice: number | null;
    prefLocator: number | null;
    prepaidFinanceChg: number | null;
    processorCode: number | null;
    propertyAddressType: number | null;
    propertyJurisdiction: string;
    purposeCode: number | null;
    putItemSchd: number | null;
    putItemSchdType: number | null;
    queue: number | null;
    queueDate: string | null;
    queuePriority: number | null;
    queueTime: number | null;
    recordChangeDate: string | null;
    riskRate: number | null;
    salesTaxCityIndicator: number | null;
    salesTaxCountyIndicator: number | null;
    salesTaxRate: number | null;
    salesTaxStateIndicator: number | null;
    secondAppPayment: number | null;
    secondAppRequest: string;
    secondAppRequestAmt: number | null;
    secondInsBirthDate: string | null;
    securedCode: number | null;
    seg0Description: string;
    seg0Payment: number | null;
    seg0PaymentOrder: number | null;
    singlePremiumDisability: number | null;
    singlePremiumLife: number | null;
    stateSalesTaxRate: number | null;
    subType: number | null;
    termMonths: number | null;
    thirdAppPayment: number | null;
    thirdAppRequest: string;
    thirdAppRequestAmt: number | null;
    totalAssets: number | null;
    totalCreditLimits: number | null;
    totalExpenses: number | null;
    totalIncome: number | null;
    totalLiabilities: number | null;
    transferAccountId: string;
    transferAccountNumber: string;
    type: number | null;
    unamortizedFees: number | null;
    userAmount1: number | null;
    userAmount10: number | null;
    userAmount2: number | null;
    userAmount3: number | null;
    userAmount4: number | null;
    userAmount5: number | null;
    userAmount6: number | null;
    userAmount7: number | null;
    userAmount8: number | null;
    userAmount9: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userCode1: number | null;
    userCode10: number | null;
    userCode2: number | null;
    userCode3: number | null;
    userCode4: number | null;
    userCode5: number | null;
    userCode6: number | null;
    userCode7: number | null;
    userCode8: number | null;
    userCode9: number | null;
    userDate1: string | null;
    userDate10: string | null;
    userDate2: string | null;
    userDate3: string | null;
    userDate4: string | null;
    userDate5: string | null;
    userDate6: string | null;
    userDate7: string | null;
    userDate8: string | null;
    userDate9: string | null;
    userNumber1: number | null;
    userNumber2: number | null;
    userQueue: number | null;
    userRate1: number | null;
    userRate2: number | null;
    vin: string;
    version1: VersionType;
}