import { VersionType } from "./versionType";

export interface LoanAppLnSegmentFields {
    applyAsBilled: boolean | null;
    balance: boolean | null;
    balloonAmount: boolean | null;
    balloonDate: boolean | null;
    beginningCycleDate: boolean | null;
    billingDefaultDays: boolean | null;
    billingMethod: boolean | null;
    closeDate: boolean | null;
    description: boolean | null;
    discountRate: boolean | null;
    exceedLevelPmtAmt: boolean | null;
    firstPaymentDate: boolean | null;
    id: boolean | null;
    intUnpaidBilled: boolean | null;
    intYtd: boolean | null;
    interestLastYear: boolean | null;
    interestRate: boolean | null;
    interestRateIndex: boolean | null;
    interestRateMargin: boolean | null;
    interestRateMarginSign: boolean | null;
    interestRateMax: boolean | null;
    interestRateMin: boolean | null;
    interestType: boolean | null;
    interestUnpaid: boolean | null;
    lastPaymentDate: boolean | null;
    levelPaymentAmt: boolean | null;
    levelPrincipalAmt: boolean | null;
    maturityDate: boolean | null;
    minimumPayment: boolean | null;
    openDate: boolean | null;
    originalBalance: boolean | null;
    originalDate: boolean | null;
    partialPayment: boolean | null;
    payment: boolean | null;
    paymentCalcType: boolean | null;
    paymentDue: boolean | null;
    paymentOrder: boolean | null;
    paymentType: boolean | null;
    payoffAmount: boolean | null;
    percentPrincipal: boolean | null;
    periodicCap: boolean | null;
    periodicFrequency: boolean | null;
    periodicStartDate: boolean | null;
    periodicStartRate: boolean | null;
    pmtBucketAmount: number[];
    recordChangeDate: boolean | null;
    riskRate: boolean | null;
    schdPeriodStartDate: boolean | null;
    schdPeriodStartRate: boolean | null;
    schdRate: boolean | null;
    schdRateChangeDate: boolean | null;
    type: boolean | null;
    variableRateIndicator: boolean | null;
    version1: VersionType;
}