import { LoanAppDefaultDebtRatioType } from "./loanAppDefaultDebtRatioType";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanAppDefault {
    accountTypeValue: number;
    accountTypeValueSpecified: boolean;
    accountType: number | null;
    applicationTypeValue: number;
    applicationTypeValueSpecified: boolean;
    applicationType: number | null;
    applyAsBilledValue: number;
    applyAsBilledValueSpecified: boolean;
    applyAsBilled: number | null;
    approvalCodeValue: number;
    approvalCodeValueSpecified: boolean;
    approvalCode: number | null;
    billingDefaultDaysValue: number;
    billingDefaultDaysValueSpecified: boolean;
    billingDefaultDays: number | null;
    billingMethodValue: number;
    billingMethodValueSpecified: boolean;
    billingMethod: number | null;
    billingNoticeValue: number;
    billingNoticeValueSpecified: boolean;
    billingNotice: number | null;
    billingNoticeMinValue: number;
    billingNoticeMinValueSpecified: boolean;
    billingNoticeMin: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    btLimitMaxValue: number;
    btLimitMaxValueSpecified: boolean;
    btLimitMax: number | null;
    btPercentValue: number;
    btPercentValueSpecified: boolean;
    btPercent: number | null;
    caLimitMaxValue: number;
    caLimitMaxValueSpecified: boolean;
    caLimitMax: number | null;
    caPercentValue: number;
    caPercentValueSpecified: boolean;
    caPercent: number | null;
    collateralCodeValue: number;
    collateralCodeValueSpecified: boolean;
    collateralCode: number | null;
    combinedCaBtLimitMaxValue: number;
    combinedCaBtLimitMaxValueSpecified: boolean;
    combinedCaBtLimitMax: number | null;
    combinedCaBtPercentValue: number;
    combinedCaBtPercentValueSpecified: boolean;
    combinedCaBtPercent: number | null;
    comboLnSegmentMaxValue: number;
    comboLnSegmentMaxValueSpecified: boolean;
    comboLnSegmentMax: number | null;
    comboPmtOrderMethValue: number;
    comboPmtOrderMethValueSpecified: boolean;
    comboPmtOrderMeth: number | null;
    comboSeg0PmtOrderValue: number;
    comboSeg0PmtOrderValueSpecified: boolean;
    comboSeg0PmtOrder: number | null;
    creationDateValue: string;
    creationDateValueSpecified: boolean;
    creationDate: string | null;
    creditBureauValue: number;
    creditBureauValueSpecified: boolean;
    creditBureau: number | null;
    creditLimitValue: number;
    creditLimitValueSpecified: boolean;
    creditLimit: number | null;
    creditScoreTypeValue: number;
    creditScoreTypeValueSpecified: boolean;
    creditScoreType: number | null;
    dealerCity: string;
    dealerCounty: string;
    dealerState: string;
    debtRatioType: LoanAppDefaultDebtRatioType[];
    debtRatioTypeSpecified: boolean;
    denialDateValue: string;
    denialDateValueSpecified: boolean;
    denialDate: string | null;
    discountRateValue: number;
    discountRateValueSpecified: boolean;
    discountRate: number | null;
    dqCalculationMethodValue: number;
    dqCalculationMethodValueSpecified: boolean;
    dqCalculationMethod: number | null;
    dueDateAdvanceCodeValue: number;
    dueDateAdvanceCodeValueSpecified: boolean;
    dueDateAdvanceCode: number | null;
    dueDay1Value: number;
    dueDay1ValueSpecified: boolean;
    dueDay1: number | null;
    dueDay2Value: number;
    dueDay2ValueSpecified: boolean;
    dueDay2: number | null;
    ecoaCodeValue: number;
    ecoaCodeValueSpecified: boolean;
    ecoaCode: number | null;
    effectiveAprValue: number;
    effectiveAprValueSpecified: boolean;
    effectiveApr: number | null;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    exceedLevelPmtAmtValue: number;
    exceedLevelPmtAmtValueSpecified: boolean;
    exceedLevelPmtAmt: number | null;
    expirationDateValue: string;
    expirationDateValueSpecified: boolean;
    expirationDate: string | null;
    fasb91CodeValue: number;
    fasb91CodeValueSpecified: boolean;
    fasb91Code: number | null;
    fixedDealerCityTaxRateValue: number;
    fixedDealerCityTaxRateValueSpecified: boolean;
    fixedDealerCityTaxRate: number | null;
    fixedDealerCountyTaxRateValue: number;
    fixedDealerCountyTaxRateValueSpecified: boolean;
    fixedDealerCountyTaxRate: number | null;
    fixedDealerStateTaxRateValue: number;
    fixedDealerStateTaxRateValueSpecified: boolean;
    fixedDealerStateTaxRate: number | null;
    fixedLesseeCityTaxRateValue: number;
    fixedLesseeCityTaxRateValueSpecified: boolean;
    fixedLesseeCityTaxRate: number | null;
    fixedLesseeCountyTaxRateValue: number;
    fixedLesseeCountyTaxRateValueSpecified: boolean;
    fixedLesseeCountyTaxRate: number | null;
    fixedLesseeStateTaxRateValue: number;
    fixedLesseeStateTaxRateValueSpecified: boolean;
    fixedLesseeStateTaxRate: number | null;
    formTypeValue: number;
    formTypeValueSpecified: boolean;
    formType: number | null;
    initialBcdSettingOptionValue: number;
    initialBcdSettingOptionValueSpecified: boolean;
    initialBcdSettingOption: number | null;
    insurabilityCodeValue: number;
    insurabilityCodeValueSpecified: boolean;
    insurabilityCode: number | null;
    insurance1ChosenValue: number;
    insurance1ChosenValueSpecified: boolean;
    insurance1Chosen: number | null;
    insurance2ChosenValue: number;
    insurance2ChosenValueSpecified: boolean;
    insurance2Chosen: number | null;
    insurance3ChosenValue: number;
    insurance3ChosenValueSpecified: boolean;
    insurance3Chosen: number | null;
    insuranceMaxValue: number;
    insuranceMaxValueSpecified: boolean;
    insuranceMax: number | null;
    insuranceTypeValue: number;
    insuranceTypeValueSpecified: boolean;
    insuranceType: number | null;
    interestRateValue: number;
    interestRateValueSpecified: boolean;
    interestRate: number | null;
    interestTypeValue: number;
    interestTypeValueSpecified: boolean;
    interestType: number | null;
    leaseDispositionDateValue: string;
    leaseDispositionDateValueSpecified: boolean;
    leaseDispositionDate: string | null;
    leaseDispositionFeeValue: number;
    leaseDispositionFeeValueSpecified: boolean;
    leaseDispositionFee: number | null;
    leaseTerminateDateValue: string;
    leaseTerminateDateValueSpecified: boolean;
    leaseTerminateDate: string | null;
    leaseTerminateFeeValue: number;
    leaseTerminateFeeValueSpecified: boolean;
    leaseTerminateFee: number | null;
    lesseeCity: string;
    lesseeCounty: string;
    lesseeState: string;
    levelPaymentAmtValue: number;
    levelPaymentAmtValueSpecified: boolean;
    levelPaymentAmt: number | null;
    levelPrincipalAmtValue: number;
    levelPrincipalAmtValueSpecified: boolean;
    levelPrincipalAmt: number | null;
    limitExpirationDateValue: string;
    limitExpirationDateValueSpecified: boolean;
    limitExpirationDate: string | null;
    loanCodeValue: number;
    loanCodeValueSpecified: boolean;
    loanCode: number | null;
    loanDescription: string;
    loanTypeValue: number;
    loanTypeValueSpecified: boolean;
    loanType: number | null;
    maxDueDateAdvancePeriodValue: number;
    maxDueDateAdvancePeriodValueSpecified: boolean;
    maxDueDateAdvancePeriod: number | null;
    minimumPaymentValue: number;
    minimumPaymentValueSpecified: boolean;
    minimumPayment: number | null;
    newSegCutoffDaysValue: number;
    newSegCutoffDaysValueSpecified: boolean;
    newSegCutoffDays: number | null;
    newSegCutoffOptionValue: number;
    newSegCutoffOptionValueSpecified: boolean;
    newSegCutoffOption: number | null;
    originalRateValue: number;
    originalRateValueSpecified: boolean;
    originalRate: number | null;
    ovlAuthFeeValue: number;
    ovlAuthFeeValueSpecified: boolean;
    ovlAuthFee: number | null;
    ovlOptInValue: number;
    ovlOptInValueSpecified: boolean;
    ovlOptIn: number | null;
    paymentCalcTypeValue: number;
    paymentCalcTypeValueSpecified: boolean;
    paymentCalcType: number | null;
    paymentFrequencyValue: number;
    paymentFrequencyValueSpecified: boolean;
    paymentFrequency: number | null;
    paymentMethodValue: number;
    paymentMethodValueSpecified: boolean;
    paymentMethod: number | null;
    paymentSkipStartDayValue: number;
    paymentSkipStartDayValueSpecified: boolean;
    paymentSkipStartDay: number | null;
    paymentSkipsValue: number;
    paymentSkipsValueSpecified: boolean;
    paymentSkips: number | null;
    paymentTypeValue: number;
    paymentTypeValueSpecified: boolean;
    paymentType: number | null;
    percentPrincipalValue: number;
    percentPrincipalValueSpecified: boolean;
    percentPrincipal: number | null;
    propertyAddressTypeValue: number;
    propertyAddressTypeValueSpecified: boolean;
    propertyAddressType: number | null;
    purposeCodeValue: number;
    purposeCodeValueSpecified: boolean;
    purposeCode: number | null;
    queuePriorityValue: number;
    queuePriorityValueSpecified: boolean;
    queuePriority: number | null;
    riskRateValue: number;
    riskRateValueSpecified: boolean;
    riskRate: number | null;
    salesTaxCityIndicatorValue: number;
    salesTaxCityIndicatorValueSpecified: boolean;
    salesTaxCityIndicator: number | null;
    salesTaxCountyIndicatorValue: number;
    salesTaxCountyIndicatorValueSpecified: boolean;
    salesTaxCountyIndicator: number | null;
    salesTaxStateIndicatorValue: number;
    salesTaxStateIndicatorValueSpecified: boolean;
    salesTaxStateIndicator: number | null;
    securedCodeValue: number;
    securedCodeValueSpecified: boolean;
    securedCode: number | null;
    seg0Description: string;
    seg0PaymentOrderValue: number;
    seg0PaymentOrderValueSpecified: boolean;
    seg0PaymentOrder: number | null;
    subTypeValue: number;
    subTypeValueSpecified: boolean;
    subType: number | null;
    termMonthsValue: number;
    termMonthsValueSpecified: boolean;
    termMonths: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    unamortizedFeesValue: number;
    unamortizedFeesValueSpecified: boolean;
    unamortizedFees: number | null;
    userAmount1Value: number;
    userAmount1ValueSpecified: boolean;
    userAmount1: number | null;
    userAmount10Value: number;
    userAmount10ValueSpecified: boolean;
    userAmount10: number | null;
    userAmount2Value: number;
    userAmount2ValueSpecified: boolean;
    userAmount2: number | null;
    userAmount3Value: number;
    userAmount3ValueSpecified: boolean;
    userAmount3: number | null;
    userAmount4Value: number;
    userAmount4ValueSpecified: boolean;
    userAmount4: number | null;
    userAmount5Value: number;
    userAmount5ValueSpecified: boolean;
    userAmount5: number | null;
    userAmount6Value: number;
    userAmount6ValueSpecified: boolean;
    userAmount6: number | null;
    userAmount7Value: number;
    userAmount7ValueSpecified: boolean;
    userAmount7: number | null;
    userAmount8Value: number;
    userAmount8ValueSpecified: boolean;
    userAmount8: number | null;
    userAmount9Value: number;
    userAmount9ValueSpecified: boolean;
    userAmount9: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userCode1Value: number;
    userCode1ValueSpecified: boolean;
    userCode1: number | null;
    userCode10Value: number;
    userCode10ValueSpecified: boolean;
    userCode10: number | null;
    userCode2Value: number;
    userCode2ValueSpecified: boolean;
    userCode2: number | null;
    userCode3Value: number;
    userCode3ValueSpecified: boolean;
    userCode3: number | null;
    userCode4Value: number;
    userCode4ValueSpecified: boolean;
    userCode4: number | null;
    userCode5Value: number;
    userCode5ValueSpecified: boolean;
    userCode5: number | null;
    userCode6Value: number;
    userCode6ValueSpecified: boolean;
    userCode6: number | null;
    userCode7Value: number;
    userCode7ValueSpecified: boolean;
    userCode7: number | null;
    userCode8Value: number;
    userCode8ValueSpecified: boolean;
    userCode8: number | null;
    userCode9Value: number;
    userCode9ValueSpecified: boolean;
    userCode9: number | null;
    userDate1Value: string;
    userDate1ValueSpecified: boolean;
    userDate1: string | null;
    userDate10Value: string;
    userDate10ValueSpecified: boolean;
    userDate10: string | null;
    userDate2Value: string;
    userDate2ValueSpecified: boolean;
    userDate2: string | null;
    userDate3Value: string;
    userDate3ValueSpecified: boolean;
    userDate3: string | null;
    userDate4Value: string;
    userDate4ValueSpecified: boolean;
    userDate4: string | null;
    userDate5Value: string;
    userDate5ValueSpecified: boolean;
    userDate5: string | null;
    userDate6Value: string;
    userDate6ValueSpecified: boolean;
    userDate6: string | null;
    userDate7Value: string;
    userDate7ValueSpecified: boolean;
    userDate7: string | null;
    userDate8Value: string;
    userDate8ValueSpecified: boolean;
    userDate8: string | null;
    userDate9Value: string;
    userDate9ValueSpecified: boolean;
    userDate9: string | null;
    userNumber1Value: number;
    userNumber1ValueSpecified: boolean;
    userNumber1: number | null;
    userNumber2Value: number;
    userNumber2ValueSpecified: boolean;
    userNumber2: number | null;
    userRate1Value: number;
    userRate1ValueSpecified: boolean;
    userRate1: number | null;
    userRate2Value: number;
    userRate2ValueSpecified: boolean;
    userRate2: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}