import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanLnSegmentBillingFields {
    billedDateValue: boolean;
    billedDateValueSpecified: boolean;
    billedDate: boolean | null;
    dueDateValue: boolean;
    dueDateValueSpecified: boolean;
    dueDate: boolean | null;
    escrowBilledValue: boolean;
    escrowBilledValueSpecified: boolean;
    escrowBilled: boolean | null;
    escrowPeriodValue: boolean;
    escrowPeriodValueSpecified: boolean;
    escrowPeriod: boolean | null;
    escrowRemainValue: boolean;
    escrowRemainValueSpecified: boolean;
    escrowRemain: boolean | null;
    feesBilledValue: boolean;
    feesBilledValueSpecified: boolean;
    feesBilled: boolean | null;
    feesRemainValue: boolean;
    feesRemainValueSpecified: boolean;
    feesRemain: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    interestBilledValue: boolean;
    interestBilledValueSpecified: boolean;
    interestBilled: boolean | null;
    interestRemainValue: boolean;
    interestRemainValueSpecified: boolean;
    interestRemain: boolean | null;
    lastPaymentDateValue: boolean;
    lastPaymentDateValueSpecified: boolean;
    lastPaymentDate: boolean | null;
    lateChargeBilledValue: boolean;
    lateChargeBilledValueSpecified: boolean;
    lateChargeBilled: boolean | null;
    lateChargePeriodValue: boolean;
    lateChargePeriodValueSpecified: boolean;
    lateChargePeriod: boolean | null;
    lateChargeRemainValue: boolean;
    lateChargeRemainValueSpecified: boolean;
    lateChargeRemain: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    paymentValue: boolean;
    paymentValueSpecified: boolean;
    payment: boolean | null;
    princIntBilledValue: boolean;
    princIntBilledValueSpecified: boolean;
    princIntBilled: boolean | null;
    princIntRemainValue: boolean;
    princIntRemainValueSpecified: boolean;
    princIntRemain: boolean | null;
    principalBilledValue: boolean;
    principalBilledValueSpecified: boolean;
    principalBilled: boolean | null;
    principalRemainValue: boolean;
    principalRemainValueSpecified: boolean;
    principalRemain: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    salesTaxBilledValue: boolean;
    salesTaxBilledValueSpecified: boolean;
    salesTaxBilled: boolean | null;
    salesTaxRemainValue: boolean;
    salesTaxRemainValueSpecified: boolean;
    salesTaxRemain: boolean | null;
    statusIndicatorValue: boolean;
    statusIndicatorValueSpecified: boolean;
    statusIndicator: boolean | null;
    totalBilledValue: boolean;
    totalBilledValueSpecified: boolean;
    totalBilled: boolean | null;
    totalRemainIngValue: boolean;
    totalRemainIngValueSpecified: boolean;
    totalRemainIng: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}