import { LoanAppPersonDependentAge_2 } from "./loanAppPersonDependentAge_2";
import { LoanAppPersonDerogStatus_2 } from "./loanAppPersonDerogStatus_2";
import { LoanAppPersonHmdaAppScoringModelOther_2 } from "./loanAppPersonHmdaAppScoringModelOther_2";
import { LoanAppPersonHmdaEthnicity_2 } from "./loanAppPersonHmdaEthnicity_2";
import { LoanAppPersonHmdaEthnicityOther_2 } from "./loanAppPersonHmdaEthnicityOther_2";
import { LoanAppPersonHmdaRace_2 } from "./loanAppPersonHmdaRace_2";
import { LoanAppPersonHmdaRaceOther1_2 } from "./loanAppPersonHmdaRaceOther1_2";
import { LoanAppPersonHmdaRaceOther27_2 } from "./loanAppPersonHmdaRaceOther27_2";
import { LoanAppPersonHmdaRaceOther44_2 } from "./loanAppPersonHmdaRaceOther44_2";
import { LoanAppPersonIdentDocFlag_2 } from "./loanAppPersonIdentDocFlag_2";
import { LoanAppPersonIdentIdDescription_2 } from "./loanAppPersonIdentIdDescription_2";
import { LoanAppPersonIdentIdExpireDate_2 } from "./loanAppPersonIdentIdExpireDate_2";
import { LoanAppPersonIdentIdIssueDate_2 } from "./loanAppPersonIdentIdIssueDate_2";
import { LoanAppPersonIdentIdNumber_2 } from "./loanAppPersonIdentIdNumber_2";
import { LoanAppPersonIdentIdType_2 } from "./loanAppPersonIdentIdType_2";
import { LoanAppPersonIdentIdVerifyDate_2 } from "./loanAppPersonIdentIdVerifyDate_2";
import { VersionType } from "./versionType";

export interface LoanAppPerson_2 {
    accountNumber: string;
    activeDuty: number | null;
    activeDutySeparationDate: string | null;
    activeDutyStartDate: string | null;
    activeDutyVerificationDate: string | null;
    addressType: number | null;
    altEmail: string;
    bankruptcy: number | null;
    beneficialOwner: number | null;
    beneficialPercent: number | null;
    birthDate: string | null;
    citizenship: number | null;
    city: string;
    cosignForWhom: string;
    cosignOtherLoan: number | null;
    cosignToWhom: string;
    country: string;
    countryCode: string;
    county: string;
    currEmpAddress: string;
    currEmpEndDate: string | null;
    currEmpGrossMonthlyPay: number | null;
    currEmpMonthsEmp: number | null;
    currEmpName: string;
    currEmpNetMonthlyPay: number | null;
    currEmpOccupation: string;
    currEmpStartDate: string | null;
    currEmpSupervisor: string;
    currEmpYearsEmp: number | null;
    dependentAge: LoanAppPersonDependentAge_2[];
    dependentCount: number | null;
    derogExplanation: string;
    derogStatus: LoanAppPersonDerogStatus_2[];
    driversLic: string;
    driversLicState: string;
    educationYears: number | null;
    email: string;
    empHoursPerWeek: number | null;
    employmentReturnDate: string | null;
    employmentStatus: number | null;
    extendedName: string;
    extraAddress: string;
    extraInfo: string;
    first: string;
    headquarters: number | null;
    hmdaAge: number | null;
    hmdaAppScoringModel: number | null;
    hmdaAppScoringModelOther: LoanAppPersonHmdaAppScoringModelOther_2[];
    hmdaCreditScore: number | null;
    hmdaEthnicity: LoanAppPersonHmdaEthnicity_2[];
    hmdaEthnicityOther: LoanAppPersonHmdaEthnicityOther_2[];
    hmdaEthnicityVisInd: number | null;
    hmdaRace: LoanAppPersonHmdaRace_2[];
    hmdaRaceOther1: LoanAppPersonHmdaRaceOther1_2[];
    hmdaRaceOther27: LoanAppPersonHmdaRaceOther27_2[];
    hmdaRaceOther44: LoanAppPersonHmdaRaceOther44_2[];
    hmdaRaceVisInd: number | null;
    hmdaSexInd: number | null;
    hmdaSexVisInd: number | null;
    homePhone: string;
    identDocFlag: LoanAppPersonIdentDocFlag_2[];
    identIdDescription: LoanAppPersonIdentIdDescription_2[];
    identIdExpireDate: LoanAppPersonIdentIdExpireDate_2[];
    identIdIssueDate: LoanAppPersonIdentIdIssueDate_2[];
    identIdNumber: LoanAppPersonIdentIdNumber_2[];
    identIdType: LoanAppPersonIdentIdType_2[];
    identIdVerifyDate: LoanAppPersonIdentIdVerifyDate_2[];
    incomeMayDecline: number | null;
    judgement: number | null;
    last: string;
    lei: string;
    locator: number | null;
    longName: string;
    maritalStatus: number | null;
    middle: string;
    mobilePhone: string;
    monthsCurrAddress: number | null;
    monthsPrevAddress: number | null;
    mothersMaidenName: string;
    nameFormat: number | null;
    otherCreditName: string;
    ownRentCurrAddress: number | null;
    ownRentPrevAddress: number | null;
    pagerNumber: string;
    partyInLawsuit: number | null;
    pastForeclosure: number | null;
    pastRepossession: number | null;
    personCode: number | null;
    phoneType: number | null;
    preferredContact: string;
    preferredContactMethod: number | null;
    prevEmpAddress: string;
    prevEmpEndDate: string | null;
    prevEmpGrossMonthlyPay: number | null;
    prevEmpMonthsEmp: number | null;
    prevEmpName: string;
    prevEmpOccupation: string;
    prevEmpStartDate: string | null;
    prevEmpSupervisor: string;
    prevEmpYearsEmp: number | null;
    previousAddress: string;
    recordChangeDate: string | null;
    ref1Address: string;
    ref1AddressType: number | null;
    ref1Code: number | null;
    ref1Name: string;
    ref1Phone: string;
    ref1Relationship: string;
    ref2Address: string;
    ref2AddressType: number | null;
    ref2Code: number | null;
    ref2Name: string;
    ref2Phone: string;
    ref2Relationship: string;
    ref3Address: string;
    ref3AddressType: number | null;
    ref3Code: number | null;
    ref3Name: string;
    ref3Phone: string;
    ref3Relationship: string;
    sex: string;
    shortName: string;
    ssn: string;
    state: string;
    street: string;
    suffix: string;
    title: string;
    type: number | null;
    usPersonFlag: number | null;
    workPhone: string;
    workPhoneExtension: string;
    zipCode: string;
    version1: VersionType;
}