import { LoanCheckOrderBusCaptions_2 } from "./loanCheckOrderBusCaptions_2";
import { LoanCheckOrderImprintLine_2 } from "./loanCheckOrderImprintLine_2";
import { LoanCheckOrderImprintLineSize_2 } from "./loanCheckOrderImprintLineSize_2";
import { LoanCheckOrderImprintUsage_2 } from "./loanCheckOrderImprintUsage_2";
import { LoanCheckOrderLicense_2 } from "./loanCheckOrderLicense_2";
import { LoanCheckOrderMailAddress_2 } from "./loanCheckOrderMailAddress_2";
import { LoanCheckOrderOverSigLine_2 } from "./loanCheckOrderOverSigLine_2";
import { LoanCheckOrderSpecialInstr_2 } from "./loanCheckOrderSpecialInstr_2";
import { LoanCheckOrderSsn_2 } from "./loanCheckOrderSsn_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanCheckOrder_2 {
    accent: string;
    acctAddrInkColorValue: number;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: number | null;
    billingCodeValue: number;
    billingCodeValueSpecified: boolean;
    billingCode: number | null;
    binding: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    busBindingStyleValue: number;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: number | null;
    busCaptions: LoanCheckOrderBusCaptions_2[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: number;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShippingValue: number;
    chargeShippingValueSpecified: boolean;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkTypeValue: number;
    checkTypeValueSpecified: boolean;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColorValue: number;
    cutInkColorValueSpecified: boolean;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFontValue: number;
    imprintFontValueSpecified: boolean;
    imprintFont: number | null;
    imprintJustifyValue: number;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: number | null;
    imprintLine: LoanCheckOrderImprintLine_2[];
    imprintLineSpecified: boolean;
    imprintLineSize: LoanCheckOrderImprintLineSize_2[];
    imprintLineSizeSpecified: boolean;
    imprintPhone: string;
    imprintState: string;
    imprintUsage: LoanCheckOrderImprintUsage_2[];
    imprintUsageSpecified: boolean;
    imprintZipCode: string;
    lastFmDateValue: string | null;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    lastFreeOrderValue: string | null;
    lastFreeOrderValueSpecified: boolean;
    lastFreeOrder: string | null;
    lastOrderDateValue: string | null;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: string | null;
    license: LoanCheckOrderLicense_2[];
    licenseSpecified: boolean;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    mailAddress: LoanCheckOrderMailAddress_2[];
    mailAddressSpecified: boolean;
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLinesValue: number;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: number | null;
    openDateValue: string | null;
    openDateValueSpecified: boolean;
    openDate: string | null;
    overSigFontValue: number;
    overSigFontValueSpecified: boolean;
    overSigFont: number | null;
    overSigJustifyValue: number;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: number | null;
    overSigLine: LoanCheckOrderOverSigLine_2[];
    overSigLineSpecified: boolean;
    overSigLineSizeValue: number;
    overSigLineSizeValueSpecified: boolean;
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processorValue: number;
    processorValueSpecified: boolean;
    processor: number | null;
    promoNumber: string;
    quantityValue: number;
    quantityValueSpecified: boolean;
    quantity: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rerunReasonValue: number;
    rerunReasonValueSpecified: boolean;
    rerunReason: number | null;
    shipMethodValue: number;
    shipMethodValueSpecified: boolean;
    shipMethod: number | null;
    shipToValue: number;
    shipToValueSpecified: boolean;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: LoanCheckOrderSpecialInstr_2[];
    specialInstrSpecified: boolean;
    ssn: LoanCheckOrderSsn_2[];
    ssnSpecified: boolean;
    startNumberValue: number;
    startNumberValueSpecified: boolean;
    startNumber: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    statusDateValue: string | null;
    statusDateValueSpecified: boolean;
    statusDate: string | null;
    taxExemptCodeValue: number;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: number | null;
    titleInkColorValue: number;
    titleInkColorValueSpecified: boolean;
    titleInkColor: number | null;
    userIdValue: number;
    userIdValueSpecified: boolean;
    userId: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}