import { LoanAppBureauScore } from "./loanAppBureauScore";
import { LoanAppCbiLocator } from "./loanAppCbiLocator";
import { LoanAppCompletedActions } from "./loanAppCompletedActions";
import { LoanAppCuTotalsAcctNumber } from "./loanAppCuTotalsAcctNumber";
import { LoanAppDebtRatio } from "./loanAppDebtRatio";
import { LoanAppDebtRatioType } from "./loanAppDebtRatioType";
import { LoanAppDenialReason } from "./loanAppDenialReason";
import { LoanAppHmdaAutoUnderwritingResOther } from "./loanAppHmdaAutoUnderwritingResOther";
import { LoanAppHmdaAutoUnderwritingResult } from "./loanAppHmdaAutoUnderwritingResult";
import { LoanAppHmdaAutoUnderwritingSys } from "./loanAppHmdaAutoUnderwritingSys";
import { LoanAppHmdaAutoUnderwritingSysOther } from "./loanAppHmdaAutoUnderwritingSysOther";
import { LoanAppHmdaDenialReasonOther } from "./loanAppHmdaDenialReasonOther";
import { LoanAppEscrowList } from "./loanAppEscrowList";
import { LoanAppEscrowAnalysisList } from "./loanAppEscrowAnalysisList";
import { LoanAppFinanceList } from "./loanAppFinanceList";
import { LoanAppLnSegmentList } from "./loanAppLnSegmentList";
import { LoanAppNoteList } from "./loanAppNoteList";
import { LoanAppPersonList } from "./loanAppPersonList";
import { LoanAppPledgeList } from "./loanAppPledgeList";
import { LoanAppScheduleList } from "./loanAppScheduleList";
import { LoanAppTrackingList } from "./loanAppTrackingList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanApp {
    accountTypeValue: number;
    accountTypeValueSpecified: boolean;
    accountType: number | null;
    amortizationSchdValue: number;
    amortizationSchdValueSpecified: boolean;
    amortizationSchd: number | null;
    amortizationSchdTypeValue: number;
    amortizationSchdTypeValueSpecified: boolean;
    amortizationSchdType: number | null;
    applicationDateValue: string;
    applicationDateValueSpecified: boolean;
    applicationDate: string | null;
    applyAsBilledValue: number;
    applyAsBilledValueSpecified: boolean;
    applyAsBilled: number | null;
    appraisalOffsetValue: number;
    appraisalOffsetValueSpecified: boolean;
    appraisalOffset: number | null;
    appraisedAmountValue: number;
    appraisedAmountValueSpecified: boolean;
    appraisedAmount: number | null;
    approvalAmountValue: number;
    approvalAmountValueSpecified: boolean;
    approvalAmount: number | null;
    approvalCodeValue: number;
    approvalCodeValueSpecified: boolean;
    approvalCode: number | null;
    approvalDateValue: string;
    approvalDateValueSpecified: boolean;
    approvalDate: string | null;
    aprValue: number;
    aprValueSpecified: boolean;
    apr: number | null;
    assessorParcelNumber: string;
    balloonAmountValue: number;
    balloonAmountValueSpecified: boolean;
    balloonAmount: number | null;
    balloonDateValue: string;
    balloonDateValueSpecified: boolean;
    balloonDate: string | null;
    billingDefaultDaysValue: number;
    billingDefaultDaysValueSpecified: boolean;
    billingDefaultDays: number | null;
    billingMethodValue: number;
    billingMethodValueSpecified: boolean;
    billingMethod: number | null;
    billingNoticeValue: number;
    billingNoticeValueSpecified: boolean;
    billingNotice: number | null;
    billingNoticeMinValue: number;
    billingNoticeMinValueSpecified: boolean;
    billingNoticeMin: number | null;
    borrowDateValue: string;
    borrowDateValueSpecified: boolean;
    borrowDate: string | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    btLimitMaxValue: number;
    btLimitMaxValueSpecified: boolean;
    btLimitMax: number | null;
    btPercentValue: number;
    btPercentValueSpecified: boolean;
    btPercent: number | null;
    bureauScore: LoanAppBureauScore[];
    bureauScoreSpecified: boolean;
    caLimitMaxValue: number;
    caLimitMaxValueSpecified: boolean;
    caLimitMax: number | null;
    caPercentValue: number;
    caPercentValueSpecified: boolean;
    caPercent: number | null;
    callItemSchdValue: number;
    callItemSchdValueSpecified: boolean;
    callItemSchd: number | null;
    callItemSchdTypeValue: number;
    callItemSchdTypeValueSpecified: boolean;
    callItemSchdType: number | null;
    cancellationDateValue: string;
    cancellationDateValueSpecified: boolean;
    cancellationDate: string | null;
    cbiLocator: LoanAppCbiLocator[];
    cbiLocatorSpecified: boolean;
    censusTract: string;
    citySalesTaxRateValue: number;
    citySalesTaxRateValueSpecified: boolean;
    citySalesTaxRate: number | null;
    closingDateValue: string;
    closingDateValueSpecified: boolean;
    closingDate: string | null;
    cntySalesTaxRateValue: number;
    cntySalesTaxRateValueSpecified: boolean;
    cntySalesTaxRate: number | null;
    collateralCodeValue: number;
    collateralCodeValueSpecified: boolean;
    collateralCode: number | null;
    collateralDateValue: string;
    collateralDateValueSpecified: boolean;
    collateralDate: string | null;
    combinedCaBtLimitMaxValue: number;
    combinedCaBtLimitMaxValueSpecified: boolean;
    combinedCaBtLimitMax: number | null;
    combinedCaBtPercentValue: number;
    combinedCaBtPercentValueSpecified: boolean;
    combinedCaBtPercent: number | null;
    comboLnSegmentMaxValue: number;
    comboLnSegmentMaxValueSpecified: boolean;
    comboLnSegmentMax: number | null;
    comboPmtOrderMethValue: number;
    comboPmtOrderMethValueSpecified: boolean;
    comboPmtOrderMeth: number | null;
    comboSeg0PmtOrderValue: number;
    comboSeg0PmtOrderValueSpecified: boolean;
    comboSeg0PmtOrder: number | null;
    completedActions: LoanAppCompletedActions[];
    completedActionsSpecified: boolean;
    counterOfferExpireDateValue: string;
    counterOfferExpireDateValueSpecified: boolean;
    counterOfferExpireDate: string | null;
    counteredOrigAmtValue: number;
    counteredOrigAmtValueSpecified: boolean;
    counteredOrigAmt: number | null;
    createdAtBranchValue: number;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: number | null;
    createdByUserValue: number;
    createdByUserValueSpecified: boolean;
    createdByUser: number | null;
    creationDateValue: string;
    creationDateValueSpecified: boolean;
    creationDate: string | null;
    creditBureauValue: number;
    creditBureauValueSpecified: boolean;
    creditBureau: number | null;
    creditLimitValue: number;
    creditLimitValueSpecified: boolean;
    creditLimit: number | null;
    creditScoreValue: number;
    creditScoreValueSpecified: boolean;
    creditScore: number | null;
    creditScoreTypeValue: number;
    creditScoreTypeValueSpecified: boolean;
    creditScoreType: number | null;
    cuTotalCertIrasValue: number;
    cuTotalCertIrasValueSpecified: boolean;
    cuTotalCertIras: number | null;
    cuTotalClosedEndLoansValue: number;
    cuTotalClosedEndLoansValueSpecified: boolean;
    cuTotalClosedEndLoans: number | null;
    cuTotalClosedEndPaymentsValue: number;
    cuTotalClosedEndPaymentsValueSpecified: boolean;
    cuTotalClosedEndPayments: number | null;
    cuTotalCredCardPaymentsValue: number;
    cuTotalCredCardPaymentsValueSpecified: boolean;
    cuTotalCredCardPayments: number | null;
    cuTotalCreditCardLoansValue: number;
    cuTotalCreditCardLoansValueSpecified: boolean;
    cuTotalCreditCardLoans: number | null;
    cuTotalCreditLimitValue: number;
    cuTotalCreditLimitValueSpecified: boolean;
    cuTotalCreditLimit: number | null;
    cuTotalDraftsValue: number;
    cuTotalDraftsValueSpecified: boolean;
    cuTotalDrafts: number | null;
    cuTotalLocLoansValue: number;
    cuTotalLocLoansValueSpecified: boolean;
    cuTotalLocLoans: number | null;
    cuTotalLocPaymentsValue: number;
    cuTotalLocPaymentsValueSpecified: boolean;
    cuTotalLocPayments: number | null;
    cuTotalOpenEndLoansValue: number;
    cuTotalOpenEndLoansValueSpecified: boolean;
    cuTotalOpenEndLoans: number | null;
    cuTotalOpenEndPaymentsValue: number;
    cuTotalOpenEndPaymentsValueSpecified: boolean;
    cuTotalOpenEndPayments: number | null;
    cuTotalSharesValue: number;
    cuTotalSharesValueSpecified: boolean;
    cuTotalShares: number | null;
    cuTotalsAcctNumber: LoanAppCuTotalsAcctNumber[];
    cuTotalsAcctNumberSpecified: boolean;
    dealerCity: string;
    dealerCode: string;
    dealerCounty: string;
    dealerReserveValue: number;
    dealerReserveValueSpecified: boolean;
    dealerReserve: number | null;
    dealerState: string;
    debtRatio: LoanAppDebtRatio[];
    debtRatioSpecified: boolean;
    debtRatioType: LoanAppDebtRatioType[];
    debtRatioTypeSpecified: boolean;
    decisionCodeValue: number;
    decisionCodeValueSpecified: boolean;
    decisionCode: number | null;
    decisionDateValue: string;
    decisionDateValueSpecified: boolean;
    decisionDate: string | null;
    denialDateValue: string;
    denialDateValueSpecified: boolean;
    denialDate: string | null;
    denialReason: LoanAppDenialReason[];
    denialReasonSpecified: boolean;
    discountRateValue: number;
    discountRateValueSpecified: boolean;
    discountRate: number | null;
    dqCalculationMethodValue: number;
    dqCalculationMethodValueSpecified: boolean;
    dqCalculationMethod: number | null;
    dueDateAdvanceCodeValue: number;
    dueDateAdvanceCodeValueSpecified: boolean;
    dueDateAdvanceCode: number | null;
    dueDay1Value: number;
    dueDay1ValueSpecified: boolean;
    dueDay1: number | null;
    dueDay2Value: number;
    dueDay2ValueSpecified: boolean;
    dueDay2: number | null;
    ecoaCodeValue: number;
    ecoaCodeValueSpecified: boolean;
    ecoaCode: number | null;
    effectiveAprValue: number;
    effectiveAprValueSpecified: boolean;
    effectiveApr: number | null;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    escrowAmountValue: number;
    escrowAmountValueSpecified: boolean;
    escrowAmount: number | null;
    escrowId: string;
    eventValue: number;
    eventValueSpecified: boolean;
    event: number | null;
    eventDateValue: string;
    eventDateValueSpecified: boolean;
    eventDate: string | null;
    exceedLevelPmtAmtValue: number;
    exceedLevelPmtAmtValueSpecified: boolean;
    exceedLevelPmtAmt: number | null;
    existIngLoanBalanceValue: number;
    existIngLoanBalanceValueSpecified: boolean;
    existIngLoanBalance: number | null;
    existIngLoanId: string;
    expirationDateValue: string;
    expirationDateValueSpecified: boolean;
    expirationDate: string | null;
    fasb91CodeValue: number;
    fasb91CodeValueSpecified: boolean;
    fasb91Code: number | null;
    firstDueDateValue: string;
    firstDueDateValueSpecified: boolean;
    firstDueDate: string | null;
    firstInsBirthDateValue: string;
    firstInsBirthDateValueSpecified: boolean;
    firstInsBirthDate: string | null;
    fixedDealerCityTaxRateValue: number;
    fixedDealerCityTaxRateValueSpecified: boolean;
    fixedDealerCityTaxRate: number | null;
    fixedDealerCountyTaxRateValue: number;
    fixedDealerCountyTaxRateValueSpecified: boolean;
    fixedDealerCountyTaxRate: number | null;
    fixedDealerStateTaxRateValue: number;
    fixedDealerStateTaxRateValueSpecified: boolean;
    fixedDealerStateTaxRate: number | null;
    fixedLesseeCityTaxRateValue: number;
    fixedLesseeCityTaxRateValueSpecified: boolean;
    fixedLesseeCityTaxRate: number | null;
    fixedLesseeCountyTaxRateValue: number;
    fixedLesseeCountyTaxRateValueSpecified: boolean;
    fixedLesseeCountyTaxRate: number | null;
    fixedLesseeStateTaxRateValue: number;
    fixedLesseeStateTaxRateValueSpecified: boolean;
    fixedLesseeStateTaxRate: number | null;
    formTypeValue: number;
    formTypeValueSpecified: boolean;
    formType: number | null;
    grossMonthlyPay1Value: number;
    grossMonthlyPay1ValueSpecified: boolean;
    grossMonthlyPay1: number | null;
    grossMonthlyPay2Value: number;
    grossMonthlyPay2ValueSpecified: boolean;
    grossMonthlyPay2: number | null;
    highRiskCodeValue: number;
    highRiskCodeValueSpecified: boolean;
    highRiskCode: number | null;
    hmdaActionTakenValue: number;
    hmdaActionTakenValueSpecified: boolean;
    hmdaActionTaken: number | null;
    hmdaActionTakenDateValue: string;
    hmdaActionTakenDateValueSpecified: boolean;
    hmdaActionTakenDate: string | null;
    hmdaAnnualIncomeValue: number;
    hmdaAnnualIncomeValueSpecified: boolean;
    hmdaAnnualIncome: number | null;
    hmdaAnnualIncomeNaValue: number;
    hmdaAnnualIncomeNaValueSpecified: boolean;
    hmdaAnnualIncomeNa: number | null;
    hmdaApplicationDateNaValue: number;
    hmdaApplicationDateNaValueSpecified: boolean;
    hmdaApplicationDateNa: number | null;
    hmdaAutoUnderwritingResOther: LoanAppHmdaAutoUnderwritingResOther[];
    hmdaAutoUnderwritingResOtherSpecified: boolean;
    hmdaAutoUnderwritingResult: LoanAppHmdaAutoUnderwritingResult[];
    hmdaAutoUnderwritingResultSpecified: boolean;
    hmdaAutoUnderwritingSys: LoanAppHmdaAutoUnderwritingSys[];
    hmdaAutoUnderwritingSysSpecified: boolean;
    hmdaAutoUnderwritingSysOther: LoanAppHmdaAutoUnderwritingSysOther[];
    hmdaAutoUnderwritingSysOtherSpecified: boolean;
    hmdaBusOrCommPurposeIndValue: number;
    hmdaBusOrCommPurposeIndValueSpecified: boolean;
    hmdaBusOrCommPurposeInd: number | null;
    hmdaCensusTract: string;
    hmdaCensusTractNaValue: number;
    hmdaCensusTractNaValueSpecified: boolean;
    hmdaCensusTractNa: number | null;
    hmdaConstructionMethodValue: number;
    hmdaConstructionMethodValueSpecified: boolean;
    hmdaConstructionMethod: number | null;
    hmdaDebtRationAValue: number;
    hmdaDebtRationAValueSpecified: boolean;
    hmdaDebtRationA: number | null;
    hmdaDenialReasonOther: LoanAppHmdaDenialReasonOther[];
    hmdaDenialReasonOtherSpecified: boolean;
    hmdaDiscountPointsValue: number;
    hmdaDiscountPointsValueSpecified: boolean;
    hmdaDiscountPoints: number | null;
    hmdaDiscountPointsNaValue: number;
    hmdaDiscountPointsNaValueSpecified: boolean;
    hmdaDiscountPointsNa: number | null;
    hmdaHoePastAtUsValue: number;
    hmdaHoePastAtUsValueSpecified: boolean;
    hmdaHoePastAtUs: number | null;
    hmdaInitPayableToInstValue: number;
    hmdaInitPayableToInstValueSpecified: boolean;
    hmdaInitPayableToInst: number | null;
    hmdaIntOnlyPmtIndValue: number;
    hmdaIntOnlyPmtIndValueSpecified: boolean;
    hmdaIntOnlyPmtInd: number | null;
    hmdaInterestRateNaValue: number;
    hmdaInterestRateNaValueSpecified: boolean;
    hmdaInterestRateNa: number | null;
    hmdaIntroRatePeriodValue: number;
    hmdaIntroRatePeriodValueSpecified: boolean;
    hmdaIntroRatePeriod: number | null;
    hmdaIntroRatePeriodNaValue: number;
    hmdaIntroRatePeriodNaValueSpecified: boolean;
    hmdaIntroRatePeriodNa: number | null;
    hmdaLenderCreditsValue: number;
    hmdaLenderCreditsValueSpecified: boolean;
    hmdaLenderCredits: number | null;
    hmdaLenderCreditsNaValue: number;
    hmdaLenderCreditsNaValueSpecified: boolean;
    hmdaLenderCreditsNa: number | null;
    hmdaLienStatusValue: number;
    hmdaLienStatusValueSpecified: boolean;
    hmdaLienStatus: number | null;
    hmdaLoanPurposeValue: number;
    hmdaLoanPurposeValueSpecified: boolean;
    hmdaLoanPurpose: number | null;
    hmdaLoanTermNaValue: number;
    hmdaLoanTermNaValueSpecified: boolean;
    hmdaLoanTermNa: number | null;
    hmdaLoanToValueNaValue: number;
    hmdaLoanToValueNaValueSpecified: boolean;
    hmdaLoanToValueNa: number | null;
    hmdaLoanTypeValue: number;
    hmdaLoanTypeValueSpecified: boolean;
    hmdaLoanType: number | null;
    hmdaMfdHomeSecPropTypeValue: number;
    hmdaMfdHomeSecPropTypeValueSpecified: boolean;
    hmdaMfdHomeSecPropType: number | null;
    hmdaMfdHomelandPropIntValue: number;
    hmdaMfdHomelandPropIntValueSpecified: boolean;
    hmdaMfdHomelandPropInt: number | null;
    hmdaMultifamilyAffordUnitsValue: number;
    hmdaMultifamilyAffordUnitsValueSpecified: boolean;
    hmdaMultifamilyAffordUnits: number | null;
    hmdaMultifamilyAffordUnitsNaValue: number;
    hmdaMultifamilyAffordUnitsNaValueSpecified: boolean;
    hmdaMultifamilyAffordUnitsNa: number | null;
    hmdaNegAmortIndValue: number;
    hmdaNegAmortIndValueSpecified: boolean;
    hmdaNegAmortInd: number | null;
    hmdaNmlsrId: string;
    hmdaNmlsrIdNaValue: number;
    hmdaNmlsrIdNaValueSpecified: boolean;
    hmdaNmlsrIdNa: number | null;
    hmdaOccupancyTypeValue: number;
    hmdaOccupancyTypeValueSpecified: boolean;
    hmdaOccupancyType: number | null;
    hmdaOeLocIndValue: number;
    hmdaOeLocIndValueSpecified: boolean;
    hmdaOeLocInd: number | null;
    hmdaOriginationChargesValue: number;
    hmdaOriginationChargesValueSpecified: boolean;
    hmdaOriginationCharges: number | null;
    hmdaOriginationChargesNaValue: number;
    hmdaOriginationChargesNaValueSpecified: boolean;
    hmdaOriginationChargesNa: number | null;
    hmdaOtherNonAmortFeaturesValue: number;
    hmdaOtherNonAmortFeaturesValueSpecified: boolean;
    hmdaOtherNonAmortFeatures: number | null;
    hmdaPreapprovalValue: number;
    hmdaPreapprovalValueSpecified: boolean;
    hmdaPreapproval: number | null;
    hmdaPrepaymentPenaltyTermValue: number;
    hmdaPrepaymentPenaltyTermValueSpecified: boolean;
    hmdaPrepaymentPenaltyTerm: number | null;
    hmdaPrepaymentPenaltyTermNaValue: number;
    hmdaPrepaymentPenaltyTermNaValueSpecified: boolean;
    hmdaPrepaymentPenaltyTermNa: number | null;
    hmdaPropertyCity: string;
    hmdaPropertyCityNaValue: number;
    hmdaPropertyCityNaValueSpecified: boolean;
    hmdaPropertyCityNa: number | null;
    hmdaPropertyCounty: string;
    hmdaPropertyCountyNaValue: number;
    hmdaPropertyCountyNaValueSpecified: boolean;
    hmdaPropertyCountyNa: number | null;
    hmdaPropertyState: string;
    hmdaPropertyStateNaValue: number;
    hmdaPropertyStateNaValueSpecified: boolean;
    hmdaPropertyStateNa: number | null;
    hmdaPropertyStreetAddress: string;
    hmdaPropertyStreetAddressNaValue: number;
    hmdaPropertyStreetAddressNaValueSpecified: boolean;
    hmdaPropertyStreetAddressNa: number | null;
    hmdaPropertyValueValue: number;
    hmdaPropertyValueValueSpecified: boolean;
    hmdaPropertyValue: number | null;
    hmdaPropertyValueNaValue: number;
    hmdaPropertyValueNaValueSpecified: boolean;
    hmdaPropertyValueNa: number | null;
    hmdaPropertyZipCode: string;
    hmdaPropertyZipCodeNaValue: number;
    hmdaPropertyZipCodeNaValueSpecified: boolean;
    hmdaPropertyZipCodeNa: number | null;
    hmdaPurchaserTypeValue: number;
    hmdaPurchaserTypeValueSpecified: boolean;
    hmdaPurchaserType: number | null;
    hmdaRateSpreadValue: number;
    hmdaRateSpreadValueSpecified: boolean;
    hmdaRateSpread: number | null;
    hmdaRateSpreadNaValue: number;
    hmdaRateSpreadNaValueSpecified: boolean;
    hmdaRateSpreadNa: number | null;
    hmdaRateSpreadSignValue: number;
    hmdaRateSpreadSignValueSpecified: boolean;
    hmdaRateSpreadSign: number | null;
    hmdaRevMortIndValue: number;
    hmdaRevMortIndValueSpecified: boolean;
    hmdaRevMortInd: number | null;
    hmdaSubmissionOfApMethodValue: number;
    hmdaSubmissionOfApMethodValueSpecified: boolean;
    hmdaSubmissionOfApMethod: number | null;
    hmdaTotalLoanCostsValue: number;
    hmdaTotalLoanCostsValueSpecified: boolean;
    hmdaTotalLoanCosts: number | null;
    hmdaTotalLoanCostsNaValue: number;
    hmdaTotalLoanCostsNaValueSpecified: boolean;
    hmdaTotalLoanCostsNa: number | null;
    hmdaTotalPointsFeesValue: number;
    hmdaTotalPointsFeesValueSpecified: boolean;
    hmdaTotalPointsFees: number | null;
    hmdaTotalPointsFeesNaValue: number;
    hmdaTotalPointsFeesNaValueSpecified: boolean;
    hmdaTotalPointsFeesNa: number | null;
    hmdaTotalUnitsValue: number;
    hmdaTotalUnitsValueSpecified: boolean;
    hmdaTotalUnits: number | null;
    hmdaUniversalLoanIdentifier1: string;
    hmdaUniversalLoanIdentifier2: string;
    id: string;
    indirectDealerNum: string;
    indirectPlanId: string;
    infoRequestDateValue: string;
    infoRequestDateValueSpecified: boolean;
    infoRequestDate: string | null;
    initialBcdSettingOptionValue: number;
    initialBcdSettingOptionValueSpecified: boolean;
    initialBcdSettingOption: number | null;
    insurabilityCodeValue: number;
    insurabilityCodeValueSpecified: boolean;
    insurabilityCode: number | null;
    insurance1ChosenValue: number;
    insurance1ChosenValueSpecified: boolean;
    insurance1Chosen: number | null;
    insurance2ChosenValue: number;
    insurance2ChosenValueSpecified: boolean;
    insurance2Chosen: number | null;
    insurance3ChosenValue: number;
    insurance3ChosenValueSpecified: boolean;
    insurance3Chosen: number | null;
    insuranceMaxValue: number;
    insuranceMaxValueSpecified: boolean;
    insuranceMax: number | null;
    insuranceTypeValue: number;
    insuranceTypeValueSpecified: boolean;
    insuranceType: number | null;
    interestRateValue: number;
    interestRateValueSpecified: boolean;
    interestRate: number | null;
    interestTypeValue: number;
    interestTypeValueSpecified: boolean;
    interestType: number | null;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    leaseDispositionDateValue: string;
    leaseDispositionDateValueSpecified: boolean;
    leaseDispositionDate: string | null;
    leaseDispositionFeeValue: number;
    leaseDispositionFeeValueSpecified: boolean;
    leaseDispositionFee: number | null;
    leaseTerminateDateValue: string;
    leaseTerminateDateValueSpecified: boolean;
    leaseTerminateDate: string | null;
    leaseTerminateFeeValue: number;
    leaseTerminateFeeValueSpecified: boolean;
    leaseTerminateFee: number | null;
    lesseeCity: string;
    lesseeCounty: string;
    lesseeState: string;
    levelPaymentAmtValue: number;
    levelPaymentAmtValueSpecified: boolean;
    levelPaymentAmt: number | null;
    levelPrincipalAmtValue: number;
    levelPrincipalAmtValueSpecified: boolean;
    levelPrincipalAmt: number | null;
    limitExpirationDateValue: string;
    limitExpirationDateValueSpecified: boolean;
    limitExpirationDate: string | null;
    loanAmountValue: number;
    loanAmountValueSpecified: boolean;
    loanAmount: number | null;
    loanAppEscrowList: LoanAppEscrowList;
    loanAppEscrowAnalysisList: LoanAppEscrowAnalysisList;
    loanAppFinanceList: LoanAppFinanceList;
    loanAppLnSegmentList: LoanAppLnSegmentList;
    loanAppNoteList: LoanAppNoteList;
    loanAppPersonList: LoanAppPersonList;
    loanAppPledgeList: LoanAppPledgeList;
    loanAppScheduleList: LoanAppScheduleList;
    loanAppTrackingList: LoanAppTrackingList;
    loanCodeValue: number;
    loanCodeValueSpecified: boolean;
    loanCode: number | null;
    loanDescription: string;
    loanMaturityDateValue: string;
    loanMaturityDateValueSpecified: boolean;
    loanMaturityDate: string | null;
    loanReference: string;
    loanToValueRatioValue: number;
    loanToValueRatioValueSpecified: boolean;
    loanToValueRatio: number | null;
    loanTypeValue: number;
    loanTypeValueSpecified: boolean;
    loanType: number | null;
    maxDueDateAdvancePeriodValue: number;
    maxDueDateAdvancePeriodValueSpecified: boolean;
    maxDueDateAdvancePeriod: number | null;
    militaryAprLoanValue: number;
    militaryAprLoanValueSpecified: boolean;
    militaryAprLoan: number | null;
    minimumPaymentValue: number;
    minimumPaymentValueSpecified: boolean;
    minimumPayment: number | null;
    mtgNumPropValue: number;
    mtgNumPropValueSpecified: boolean;
    mtgNumProp: number | null;
    netMonthlyPay1Value: number;
    netMonthlyPay1ValueSpecified: boolean;
    netMonthlyPay1: number | null;
    netMonthlyPay2Value: number;
    netMonthlyPay2ValueSpecified: boolean;
    netMonthlyPay2: number | null;
    newSegCutoffDaysValue: number;
    newSegCutoffDaysValueSpecified: boolean;
    newSegCutoffDays: number | null;
    newSegCutoffOptionValue: number;
    newSegCutoffOptionValueSpecified: boolean;
    newSegCutoffOption: number | null;
    notePurgeDateValue: string;
    notePurgeDateValueSpecified: boolean;
    notePurgeDate: string | null;
    origRiskGrade: string;
    originalRateValue: number;
    originalRateValueSpecified: boolean;
    originalRate: number | null;
    ovlAuthFeeValue: number;
    ovlAuthFeeValueSpecified: boolean;
    ovlAuthFee: number | null;
    ovlOptInValue: number;
    ovlOptInValueSpecified: boolean;
    ovlOptIn: number | null;
    paymentValue: number;
    paymentValueSpecified: boolean;
    payment: number | null;
    paymentCalcTypeValue: number;
    paymentCalcTypeValueSpecified: boolean;
    paymentCalcType: number | null;
    paymentFrequencyValue: number;
    paymentFrequencyValueSpecified: boolean;
    paymentFrequency: number | null;
    paymentMethodValue: number;
    paymentMethodValueSpecified: boolean;
    paymentMethod: number | null;
    paymentSkipStartDayValue: number;
    paymentSkipStartDayValueSpecified: boolean;
    paymentSkipStartDay: number | null;
    paymentSkipsValue: number;
    paymentSkipsValueSpecified: boolean;
    paymentSkips: number | null;
    paymentTypeValue: number;
    paymentTypeValueSpecified: boolean;
    paymentType: number | null;
    pendingDateValue: string;
    pendingDateValueSpecified: boolean;
    pendingDate: string | null;
    percentPrincipalValue: number;
    percentPrincipalValueSpecified: boolean;
    percentPrincipal: number | null;
    pmiAppraisedValueValue: number;
    pmiAppraisedValueValueSpecified: boolean;
    pmiAppraisedValue: number | null;
    pmiLtvRatioValue: number;
    pmiLtvRatioValueSpecified: boolean;
    pmiLtvRatio: number | null;
    pmiOriginalValueValue: number;
    pmiOriginalValueValueSpecified: boolean;
    pmiOriginalValue: number | null;
    pmiPurchasePriceValue: number;
    pmiPurchasePriceValueSpecified: boolean;
    pmiPurchasePrice: number | null;
    prefLocatorValue: number;
    prefLocatorValueSpecified: boolean;
    prefLocator: number | null;
    prepaidFinanceChgValue: number;
    prepaidFinanceChgValueSpecified: boolean;
    prepaidFinanceChg: number | null;
    processorCodeValue: number;
    processorCodeValueSpecified: boolean;
    processorCode: number | null;
    propertyAddressTypeValue: number;
    propertyAddressTypeValueSpecified: boolean;
    propertyAddressType: number | null;
    propertyJurisdiction: string;
    purposeCodeValue: number;
    purposeCodeValueSpecified: boolean;
    purposeCode: number | null;
    putItemSchdValue: number;
    putItemSchdValueSpecified: boolean;
    putItemSchd: number | null;
    putItemSchdTypeValue: number;
    putItemSchdTypeValueSpecified: boolean;
    putItemSchdType: number | null;
    queueValue: number;
    queueValueSpecified: boolean;
    queue: number | null;
    queueDateValue: string;
    queueDateValueSpecified: boolean;
    queueDate: string | null;
    queuePriorityValue: number;
    queuePriorityValueSpecified: boolean;
    queuePriority: number | null;
    queueTimeValue: number;
    queueTimeValueSpecified: boolean;
    queueTime: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    riskRateValue: number;
    riskRateValueSpecified: boolean;
    riskRate: number | null;
    salesTaxCityIndicatorValue: number;
    salesTaxCityIndicatorValueSpecified: boolean;
    salesTaxCityIndicator: number | null;
    salesTaxCountyIndicatorValue: number;
    salesTaxCountyIndicatorValueSpecified: boolean;
    salesTaxCountyIndicator: number | null;
    salesTaxRateValue: number;
    salesTaxRateValueSpecified: boolean;
    salesTaxRate: number | null;
    salesTaxStateIndicatorValue: number;
    salesTaxStateIndicatorValueSpecified: boolean;
    salesTaxStateIndicator: number | null;
    secondAppPaymentValue: number;
    secondAppPaymentValueSpecified: boolean;
    secondAppPayment: number | null;
    secondAppRequest: string;
    secondAppRequestAmtValue: number;
    secondAppRequestAmtValueSpecified: boolean;
    secondAppRequestAmt: number | null;
    secondInsBirthDateValue: string;
    secondInsBirthDateValueSpecified: boolean;
    secondInsBirthDate: string | null;
    securedCodeValue: number;
    securedCodeValueSpecified: boolean;
    securedCode: number | null;
    seg0Description: string;
    seg0PaymentValue: number;
    seg0PaymentValueSpecified: boolean;
    seg0Payment: number | null;
    seg0PaymentOrderValue: number;
    seg0PaymentOrderValueSpecified: boolean;
    seg0PaymentOrder: number | null;
    singlePremiumDisabilityValue: number;
    singlePremiumDisabilityValueSpecified: boolean;
    singlePremiumDisability: number | null;
    singlePremiumLifeValue: number;
    singlePremiumLifeValueSpecified: boolean;
    singlePremiumLife: number | null;
    stateSalesTaxRateValue: number;
    stateSalesTaxRateValueSpecified: boolean;
    stateSalesTaxRate: number | null;
    subTypeValue: number;
    subTypeValueSpecified: boolean;
    subType: number | null;
    termMonthsValue: number;
    termMonthsValueSpecified: boolean;
    termMonths: number | null;
    thirdAppPaymentValue: number;
    thirdAppPaymentValueSpecified: boolean;
    thirdAppPayment: number | null;
    thirdAppRequest: string;
    thirdAppRequestAmtValue: number;
    thirdAppRequestAmtValueSpecified: boolean;
    thirdAppRequestAmt: number | null;
    totalAssetsValue: number;
    totalAssetsValueSpecified: boolean;
    totalAssets: number | null;
    totalCreditLimitsValue: number;
    totalCreditLimitsValueSpecified: boolean;
    totalCreditLimits: number | null;
    totalExpensesValue: number;
    totalExpensesValueSpecified: boolean;
    totalExpenses: number | null;
    totalIncomeValue: number;
    totalIncomeValueSpecified: boolean;
    totalIncome: number | null;
    totalLiabilitiesValue: number;
    totalLiabilitiesValueSpecified: boolean;
    totalLiabilities: number | null;
    transferAccountId: string;
    transferAccountNumber: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    unamortizedFeesValue: number;
    unamortizedFeesValueSpecified: boolean;
    unamortizedFees: number | null;
    userAmount1Value: number;
    userAmount1ValueSpecified: boolean;
    userAmount1: number | null;
    userAmount10Value: number;
    userAmount10ValueSpecified: boolean;
    userAmount10: number | null;
    userAmount2Value: number;
    userAmount2ValueSpecified: boolean;
    userAmount2: number | null;
    userAmount3Value: number;
    userAmount3ValueSpecified: boolean;
    userAmount3: number | null;
    userAmount4Value: number;
    userAmount4ValueSpecified: boolean;
    userAmount4: number | null;
    userAmount5Value: number;
    userAmount5ValueSpecified: boolean;
    userAmount5: number | null;
    userAmount6Value: number;
    userAmount6ValueSpecified: boolean;
    userAmount6: number | null;
    userAmount7Value: number;
    userAmount7ValueSpecified: boolean;
    userAmount7: number | null;
    userAmount8Value: number;
    userAmount8ValueSpecified: boolean;
    userAmount8: number | null;
    userAmount9Value: number;
    userAmount9ValueSpecified: boolean;
    userAmount9: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userCode1Value: number;
    userCode1ValueSpecified: boolean;
    userCode1: number | null;
    userCode10Value: number;
    userCode10ValueSpecified: boolean;
    userCode10: number | null;
    userCode2Value: number;
    userCode2ValueSpecified: boolean;
    userCode2: number | null;
    userCode3Value: number;
    userCode3ValueSpecified: boolean;
    userCode3: number | null;
    userCode4Value: number;
    userCode4ValueSpecified: boolean;
    userCode4: number | null;
    userCode5Value: number;
    userCode5ValueSpecified: boolean;
    userCode5: number | null;
    userCode6Value: number;
    userCode6ValueSpecified: boolean;
    userCode6: number | null;
    userCode7Value: number;
    userCode7ValueSpecified: boolean;
    userCode7: number | null;
    userCode8Value: number;
    userCode8ValueSpecified: boolean;
    userCode8: number | null;
    userCode9Value: number;
    userCode9ValueSpecified: boolean;
    userCode9: number | null;
    userDate1Value: string;
    userDate1ValueSpecified: boolean;
    userDate1: string | null;
    userDate10Value: string;
    userDate10ValueSpecified: boolean;
    userDate10: string | null;
    userDate2Value: string;
    userDate2ValueSpecified: boolean;
    userDate2: string | null;
    userDate3Value: string;
    userDate3ValueSpecified: boolean;
    userDate3: string | null;
    userDate4Value: string;
    userDate4ValueSpecified: boolean;
    userDate4: string | null;
    userDate5Value: string;
    userDate5ValueSpecified: boolean;
    userDate5: string | null;
    userDate6Value: string;
    userDate6ValueSpecified: boolean;
    userDate6: string | null;
    userDate7Value: string;
    userDate7ValueSpecified: boolean;
    userDate7: string | null;
    userDate8Value: string;
    userDate8ValueSpecified: boolean;
    userDate8: string | null;
    userDate9Value: string;
    userDate9ValueSpecified: boolean;
    userDate9: string | null;
    userNumber1Value: number;
    userNumber1ValueSpecified: boolean;
    userNumber1: number | null;
    userNumber2Value: number;
    userNumber2ValueSpecified: boolean;
    userNumber2: number | null;
    userQueueValue: number;
    userQueueValueSpecified: boolean;
    userQueue: number | null;
    userRate1Value: number;
    userRate1ValueSpecified: boolean;
    userRate1: number | null;
    userRate2Value: number;
    userRate2ValueSpecified: boolean;
    userRate2: number | null;
    vin: string;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}