import { LoanAppMiscAdditionalInfoHeader } from "./loanAppMiscAdditionalInfoHeader";
import { LoanAppMiscAdditionalInfoJustify } from "./loanAppMiscAdditionalInfoJustify";
import { LoanAppMiscAppTypeMaritalStatus } from "./loanAppMiscAppTypeMaritalStatus";
import { LoanAppMiscCreditUnionNameTransunion } from "./loanAppMiscCreditUnionNameTransunion";
import { LoanAppMiscExcludeTrdItemsTransunion } from "./loanAppMiscExcludeTrdItemsTransunion";
import { BitMap } from "./bitMap";
import { LoanAppMiscNonMemberAccount } from "./loanAppMiscNonMemberAccount";
import { VersionType } from "./versionType";

export interface LoanAppMisc {
    account: boolean | null;
    accountType: boolean | null;
    additionalInfoHeader: LoanAppMiscAdditionalInfoHeader[];
    additionalInfoJustify: LoanAppMiscAdditionalInfoJustify[];
    additionalInfoSpecfileName: string;
    appTypeMaritalStatus: LoanAppMiscAppTypeMaritalStatus[];
    autoCalcDebtRatios: boolean | null;
    autoCalcTotals: boolean | null;
    autoCreateFinanceRecords: boolean | null;
    autoCreatePersonRecords: boolean | null;
    automateRetrievalofCredRpt: boolean | null;
    automateWorkflowSteps: boolean | null;
    clearReusedAppNotes: number | null;
    consolidateFinanceRecList: boolean | null;
    copyIncometoMemberRecord: boolean | null;
    copyMovetoNewExistingAcct: boolean | null;
    createNoteWhenForwarded: boolean | null;
    creditUnionNameTransunion: LoanAppMiscCreditUnionNameTransunion[];
    debtRatioExcludeCurrApp: boolean | null;
    debtRatioIncludeOtherApp: boolean | null;
    defaultBranch: boolean | null;
    disclosureSpecfileName: string;
    dlrRsrvAcctgTrackingType: number | null;
    excludeTrdItemsTransunion: LoanAppMiscExcludeTrdItemsTransunion[];
    fieldCtrlProjectionScreen: boolean | null;
    fundingSpecfileName: string;
    fundingTrackingType: number | null;
    loanApplicationId: boolean | null;
    loanCreationOption: number | null;
    masterApp: BitMap;
    membershipApplicationType: number | null;
    msgUserIds: BitMap;
    nonMemberAccount: LoanAppMiscNonMemberAccount[];
    restrictApplicationDate: boolean | null;
    restrictApplicationType: boolean | null;
    restrictApprovalAmount: boolean | null;
    restrictApprovalCode: boolean | null;
    restrictApprovalDate: boolean | null;
    restrictBalloonAmount: boolean | null;
    restrictBalloonDate: boolean | null;
    restrictCounterOffExpDate: boolean | null;
    restrictCounterOrigAmt: boolean | null;
    restrictCreationDate: boolean | null;
    restrictCuDraftBal: boolean | null;
    restrictCuLocLoanBal: boolean | null;
    restrictCuLocPmts: boolean | null;
    restrictCuOeLoanBal: boolean | null;
    restrictCuOePmts: boolean | null;
    restrictCuShareBal: boolean | null;
    restrictCuTotalCreditLim: boolean | null;
    restrictDebtRatio1: boolean | null;
    restrictDebtRatio2: boolean | null;
    restrictDebtRatio3: boolean | null;
    restrictDebtRatio4: boolean | null;
    restrictDebtRatio5: boolean | null;
    restrictDecisionCode: boolean | null;
    restrictDecisionDate: boolean | null;
    restrictInsuranceType: boolean | null;
    restrictInterestRate: boolean | null;
    restrictLoanAmount: boolean | null;
    restrictLoanCreditLimit: boolean | null;
    restrictLoanMaturityDate: boolean | null;
    restrictLoanTerminMo: boolean | null;
    restrictLoanType: boolean | null;
    restrictPaymentAmount: boolean | null;
    restrictPaymentFreq: boolean | null;
    restrictSglPremDis: boolean | null;
    restrictSglPremLife: boolean | null;
    scriptedLoanFunding: boolean | null;
    searchExistingCredRptsDays: number | null;
    trdItemFinSkpBlankDesc: boolean | null;
    trdItemFinSkpZero: number | null;
    trdItemMinPmtCutoff: number | null;
    trdItemMnthlyPmtRate: number | null;
    userIds: BitMap;
    validateLnInterestAmount: boolean | null;
    version1: VersionType;
}