import { LoanAppDefaultDebtRatioType } from "./loanAppDefaultDebtRatioType";
import { VersionType } from "./versionType";

export interface LoanAppDefault {
    accountType: number | null;
    applicationType: number | null;
    applyAsBilled: number | null;
    approvalCode: number | null;
    billingDefaultDays: number | null;
    billingMethod: number | null;
    billingNotice: number | null;
    billingNoticeMin: number | null;
    branch: number | null;
    btLimitMax: number | null;
    btPercent: number | null;
    caLimitMax: number | null;
    caPercent: number | null;
    collateralCode: number | null;
    combinedCaBtLimitMax: number | null;
    combinedCaBtPercent: number | null;
    comboLnSegmentMax: number | null;
    comboPmtOrderMeth: number | null;
    comboSeg0PmtOrder: number | null;
    creationDate: string | null;
    creditBureau: number | null;
    creditLimit: number | null;
    creditScoreType: number | null;
    dealerCity: string;
    dealerCounty: string;
    dealerState: string;
    debtRatioType: LoanAppDefaultDebtRatioType[];
    denialDate: string | null;
    discountRate: number | null;
    dqCalculationMethod: number | null;
    dueDateAdvanceCode: number | null;
    dueDay1: number | null;
    dueDay2: number | null;
    ecoaCode: number | null;
    effectiveApr: number | null;
    effectiveDate: string | null;
    exceedLevelPmtAmt: number | null;
    expirationDate: string | null;
    fasb91Code: number | null;
    fixedDealerCityTaxRate: number | null;
    fixedDealerCountyTaxRate: number | null;
    fixedDealerStateTaxRate: number | null;
    fixedLesseeCityTaxRate: number | null;
    fixedLesseeCountyTaxRate: number | null;
    fixedLesseeStateTaxRate: number | null;
    formType: number | null;
    initialBcdSettingOption: number | null;
    insurabilityCode: number | null;
    insurance1Chosen: number | null;
    insurance2Chosen: number | null;
    insurance3Chosen: number | null;
    insuranceMax: number | null;
    insuranceType: number | null;
    interestRate: number | null;
    interestType: number | null;
    leaseDispositionDate: string | null;
    leaseDispositionFee: number | null;
    leaseTerminateDate: string | null;
    leaseTerminateFee: number | null;
    lesseeCity: string;
    lesseeCounty: string;
    lesseeState: string;
    levelPaymentAmt: number | null;
    levelPrincipalAmt: number | null;
    limitExpirationDate: string | null;
    loanCode: number | null;
    loanDescription: string;
    loanType: number | null;
    maxDueDateAdvancePeriod: number | null;
    minimumPayment: number | null;
    newSegCutoffDays: number | null;
    newSegCutoffOption: number | null;
    originalRate: number | null;
    ovlAuthFee: number | null;
    ovlOptIn: number | null;
    paymentCalcType: number | null;
    paymentFrequency: number | null;
    paymentMethod: number | null;
    paymentSkipStartDay: number | null;
    paymentSkips: number | null;
    paymentType: number | null;
    percentPrincipal: number | null;
    propertyAddressType: number | null;
    purposeCode: number | null;
    queuePriority: number | null;
    riskRate: number | null;
    salesTaxCityIndicator: number | null;
    salesTaxCountyIndicator: number | null;
    salesTaxStateIndicator: number | null;
    securedCode: number | null;
    seg0Description: string;
    seg0PaymentOrder: number | null;
    subType: number | null;
    termMonths: number | null;
    type: number | null;
    unamortizedFees: number | null;
    userAmount1: number | null;
    userAmount10: number | null;
    userAmount2: number | null;
    userAmount3: number | null;
    userAmount4: number | null;
    userAmount5: number | null;
    userAmount6: number | null;
    userAmount7: number | null;
    userAmount8: number | null;
    userAmount9: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userCode1: number | null;
    userCode10: number | null;
    userCode2: number | null;
    userCode3: number | null;
    userCode4: number | null;
    userCode5: number | null;
    userCode6: number | null;
    userCode7: number | null;
    userCode8: number | null;
    userCode9: number | null;
    userDate1: string | null;
    userDate10: string | null;
    userDate2: string | null;
    userDate3: string | null;
    userDate4: string | null;
    userDate5: string | null;
    userDate6: string | null;
    userDate7: string | null;
    userDate8: string | null;
    userDate9: string | null;
    userNumber1: number | null;
    userNumber2: number | null;
    userRate1: number | null;
    userRate2: number | null;
    version1: VersionType;
}