import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanSchedule_2 {
    applyAsBilledValue: number;
    applyAsBilledValueSpecified: boolean;
    applyAsBilled: number | null;
    beginningDateValue: string | null;
    beginningDateValueSpecified: boolean;
    beginningDate: string | null;
    billingDefaultDaysValue: number;
    billingDefaultDaysValueSpecified: boolean;
    billingDefaultDays: number | null;
    billingMethodValue: number;
    billingMethodValueSpecified: boolean;
    billingMethod: number | null;
    billingNoticeValue: number;
    billingNoticeValueSpecified: boolean;
    billingNotice: number | null;
    billingNoticeMinValue: number;
    billingNoticeMinValueSpecified: boolean;
    billingNoticeMin: number | null;
    dqCalculationMethodValue: number;
    dqCalculationMethodValueSpecified: boolean;
    dqCalculationMethod: number | null;
    dueDay1Value: number;
    dueDay1ValueSpecified: boolean;
    dueDay1: number | null;
    dueDay2Value: number;
    dueDay2ValueSpecified: boolean;
    dueDay2: number | null;
    exceedLevelPmtAmtValue: number;
    exceedLevelPmtAmtValueSpecified: boolean;
    exceedLevelPmtAmt: number | null;
    expirationValue: string | null;
    expirationValueSpecified: boolean;
    expiration: string | null;
    id: string;
    interestTypeValue: number;
    interestTypeValueSpecified: boolean;
    interestType: number | null;
    levelPaymentAmtValue: number;
    levelPaymentAmtValueSpecified: boolean;
    levelPaymentAmt: number | null;
    levelPrincipalAmtValue: number;
    levelPrincipalAmtValueSpecified: boolean;
    levelPrincipalAmt: number | null;
    minimumPaymentValue: number;
    minimumPaymentValueSpecified: boolean;
    minimumPayment: number | null;
    paymentValue: number;
    paymentValueSpecified: boolean;
    payment: number | null;
    paymentCalcTypeValue: number;
    paymentCalcTypeValueSpecified: boolean;
    paymentCalcType: number | null;
    paymentDescription: string;
    paymentTypeValue: number;
    paymentTypeValueSpecified: boolean;
    paymentType: number | null;
    percentPrincipalValue: number;
    percentPrincipalValueSpecified: boolean;
    percentPrincipal: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    repeatCodeValue: number;
    repeatCodeValueSpecified: boolean;
    repeatCode: number | null;
    useRateChangeProcessIngValue: number;
    useRateChangeProcessIngValueSpecified: boolean;
    useRateChangeProcessIng: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}