import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanAppEscrowFields {
    day1Value: boolean;
    day1ValueSpecified: boolean;
    day1: boolean | null;
    day2Value: boolean;
    day2ValueSpecified: boolean;
    day2: boolean | null;
    distribFrequencyValue: boolean;
    distribFrequencyValueSpecified: boolean;
    distribFrequency: boolean | null;
    escrowTypeValue: boolean;
    escrowTypeValueSpecified: boolean;
    escrowType: boolean | null;
    expirationDateValue: boolean;
    expirationDateValueSpecified: boolean;
    expirationDate: boolean | null;
    floodInsTrackingValue: boolean;
    floodInsTrackingValueSpecified: boolean;
    floodInsTracking: boolean | null;
    forcedPlacedInsValue: boolean;
    forcedPlacedInsValueSpecified: boolean;
    forcedPlacedIns: boolean | null;
    invoiceNumberValue: boolean;
    invoiceNumberValueSpecified: boolean;
    invoiceNumber: boolean | null;
    lastAmtNeededPmtValue: boolean;
    lastAmtNeededPmtValueSpecified: boolean;
    lastAmtNeededPmt: boolean | null;
    lastDateAnaCalcValue: boolean;
    lastDateAnaCalcValueSpecified: boolean;
    lastDateAnaCalc: boolean | null;
    lastDisbursAmtValue: boolean;
    lastDisbursAmtValueSpecified: boolean;
    lastDisbursAmt: boolean | null;
    lastDisbursDateValue: boolean;
    lastDisbursDateValueSpecified: boolean;
    lastDisbursDate: boolean | null;
    lastDisbursFreqValue: boolean;
    lastDisbursFreqValueSpecified: boolean;
    lastDisbursFreq: boolean | null;
    lastDisburseDay1Value: boolean;
    lastDisburseDay1ValueSpecified: boolean;
    lastDisburseDay1: boolean | null;
    lastDisburseDay2Value: boolean;
    lastDisburseDay2ValueSpecified: boolean;
    lastDisburseDay2: boolean | null;
    lastDistribAmountValue: boolean;
    lastDistribAmountValueSpecified: boolean;
    lastDistribAmount: boolean | null;
    lastDistribDateValue: boolean;
    lastDistribDateValueSpecified: boolean;
    lastDistribDate: boolean | null;
    lastExpirationDateValue: boolean;
    lastExpirationDateValueSpecified: boolean;
    lastExpirationDate: boolean | null;
    lastMonthCushionValue: boolean;
    lastMonthCushionValueSpecified: boolean;
    lastMonthCushion: boolean | null;
    lastNbrPmtsDueValue: boolean;
    lastNbrPmtsDueValueSpecified: boolean;
    lastNbrPmtsDue: boolean | null;
    lastTotAnnDisbursValue: boolean;
    lastTotAnnDisbursValueSpecified: boolean;
    lastTotAnnDisburs: boolean | null;
    legalDescriptionValue: boolean;
    legalDescriptionValueSpecified: boolean;
    legalDescription: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    nextDistribAmountValue: boolean;
    nextDistribAmountValueSpecified: boolean;
    nextDistribAmount: boolean | null;
    nextDistribDateValue: boolean;
    nextDistribDateValueSpecified: boolean;
    nextDistribDate: boolean | null;
    parcelNumberValue: boolean;
    parcelNumberValueSpecified: boolean;
    parcelNumber: boolean | null;
    payDividendValue: boolean;
    payDividendValueSpecified: boolean;
    payDividend: boolean | null;
    paymentPortionValue: boolean;
    paymentPortionValueSpecified: boolean;
    paymentPortion: boolean | null;
    pmiCancelDateValue: boolean;
    pmiCancelDateValueSpecified: boolean;
    pmiCancelDate: boolean | null;
    pmiCancelNoticeValue: boolean;
    pmiCancelNoticeValueSpecified: boolean;
    pmiCancelNotice: boolean | null;
    pmiDisclosureDateValue: boolean;
    pmiDisclosureDateValueSpecified: boolean;
    pmiDisclosureDate: boolean | null;
    pmiEligNoticesValue: boolean;
    pmiEligNoticesValueSpecified: boolean;
    pmiEligNotices: boolean | null;
    pmiMidTermDateValue: boolean;
    pmiMidTermDateValueSpecified: boolean;
    pmiMidTermDate: boolean | null;
    pmiTermDateValue: boolean;
    pmiTermDateValueSpecified: boolean;
    pmiTermDate: boolean | null;
    policyAmountValue: boolean;
    policyAmountValueSpecified: boolean;
    policyAmount: boolean | null;
    policyExpireDateValue: boolean;
    policyExpireDateValueSpecified: boolean;
    policyExpireDate: boolean | null;
    policyNumberValue: boolean;
    policyNumberValueSpecified: boolean;
    policyNumber: boolean | null;
    policyOrigDateValue: boolean;
    policyOrigDateValueSpecified: boolean;
    policyOrigDate: boolean | null;
    policyOwnerValue: boolean;
    policyOwnerValueSpecified: boolean;
    policyOwner: boolean | null;
    prevAmtNeededPmtValue: boolean;
    prevAmtNeededPmtValueSpecified: boolean;
    prevAmtNeededPmt: boolean | null;
    prevDateAnaCalcValue: boolean;
    prevDateAnaCalcValueSpecified: boolean;
    prevDateAnaCalc: boolean | null;
    prevDisbursAmtValue: boolean;
    prevDisbursAmtValueSpecified: boolean;
    prevDisbursAmt: boolean | null;
    prevDisbursDateValue: boolean;
    prevDisbursDateValueSpecified: boolean;
    prevDisbursDate: boolean | null;
    prevDisbursFreqValue: boolean;
    prevDisbursFreqValueSpecified: boolean;
    prevDisbursFreq: boolean | null;
    prevDisburseDay1Value: boolean;
    prevDisburseDay1ValueSpecified: boolean;
    prevDisburseDay1: boolean | null;
    prevDisburseDay2Value: boolean;
    prevDisburseDay2ValueSpecified: boolean;
    prevDisburseDay2: boolean | null;
    prevExpirationDateValue: boolean;
    prevExpirationDateValueSpecified: boolean;
    prevExpirationDate: boolean | null;
    prevMonthCushionValue: boolean;
    prevMonthCushionValueSpecified: boolean;
    prevMonthCushion: boolean | null;
    prevNbrPmtsDueValue: boolean;
    prevNbrPmtsDueValueSpecified: boolean;
    prevNbrPmtsDue: boolean | null;
    prevTotAnnDisbursValue: boolean;
    prevTotAnnDisbursValueSpecified: boolean;
    prevTotAnnDisburs: boolean | null;
    printDistribNoticeValue: boolean;
    printDistribNoticeValueSpecified: boolean;
    printDistribNotice: boolean | null;
    realEstateOwnerValue: boolean;
    realEstateOwnerValueSpecified: boolean;
    realEstateOwner: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    savedAdjustPaymentValue: boolean;
    savedAdjustPaymentValueSpecified: boolean;
    savedAdjustPayment: boolean | null;
    taxRefNumberValue: boolean;
    taxRefNumberValueSpecified: boolean;
    taxRefNumber: boolean | null;
    trackingOnlyValue: boolean;
    trackingOnlyValueSpecified: boolean;
    trackingOnly: boolean | null;
    vendorNameValue: boolean;
    vendorNameValueSpecified: boolean;
    vendorName: boolean | null;
    vendorNumberValue: boolean;
    vendorNumberValueSpecified: boolean;
    vendorNumber: boolean | null;
    version1: VersionType;
    pmiCancelReasonValue: boolean;
    pmiCancelReasonValueSpecified: boolean;
    pmiCancelReason: boolean | null;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}