import { LoanIdType } from "./loanIdType";
import { AmountInformation } from "./amountInformation";
import { GlAccounts } from "./glAccounts";
import { GlCodes } from "./glCodes";
import { AuthorizationType } from "./authorizationType";
import { RemitInformation } from "./remitInformation";
import { LoanPaymentType } from "./loanPaymentType";
import { TransactionsBaseRequest } from "./transactionsBaseRequest";

export interface LoanPaymentRequest extends TransactionsBaseRequest {
    recipientAccountNumber: string;
    recipientId: string;
    recipientIdTypeValue: LoanIdType;
    recipientIdTypeValueSpecified: boolean;
    recipientIdType: LoanIdType | null;
    paymentAmounts: AmountInformation;
    comment: string;
    glAccounts: GlAccounts;
    glCodes: GlCodes;
    authorizationTypeValue: AuthorizationType;
    authorizationTypeValueSpecified: boolean;
    authorizationType: AuthorizationType | null;
    remitInformation: RemitInformation;
    forcePostRequestedValue: boolean;
    forcePostRequestedValueSpecified: boolean;
    forcePostRequested: boolean | null;
    principalAmountValue: number;
    principalAmountValueSpecified: boolean;
    principalAmount: number | null;
    sourceCode: string;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    commentCodeValue: number;
    commentCodeValueSpecified: boolean;
    commentCode: number | null;
    loanPaymentTypeValue: LoanPaymentType;
    loanPaymentTypeValueSpecified: boolean;
    loanPaymentType: LoanPaymentType | null;
    recurrenceRequestedValue: boolean;
    recurrenceRequestedValueSpecified: boolean;
    recurrenceRequested: boolean | null;
    glComment: string;
}