import { LoanTransactionBalSegId } from "./loanTransactionBalSegId";
import { LoanTransactionBalSegPmtChangeDate } from "./loanTransactionBalSegPmtChangeDate";
import { LoanTransactionBalSegPrevFirstPmtDate } from "./loanTransactionBalSegPrevFirstPmtDate";
import { LoanTransactionStmtDesc } from "./loanTransactionStmtDesc";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface LoanTransaction {
    accountNumber: string;
    actionCode: string;
    activityDateValue: string;
    activityDateValueSpecified: boolean;
    activityDate: string | null;
    adjustmentCodeValue: number;
    adjustmentCodeValueSpecified: boolean;
    adjustmentCode: number | null;
    balSegCountValue: number;
    balSegCountValueSpecified: boolean;
    balSegCount: number | null;
    balSegId: LoanTransactionBalSegId[];
    balSegIdSpecified: boolean;
    balSegPmtChangeDate: LoanTransactionBalSegPmtChangeDate[];
    balSegPmtChangeDateSpecified: boolean;
    balSegPrevFirstPmtDate: LoanTransactionBalSegPrevFirstPmtDate[];
    balSegPrevFirstPmtDateSpecified: boolean;
    balanceChangeValue: number;
    balanceChangeValueSpecified: boolean;
    balanceChange: number | null;
    batchSequenceValue: number;
    batchSequenceValueSpecified: boolean;
    batchSequence: number | null;
    billedFeeAmountValue: number;
    billedFeeAmountValueSpecified: boolean;
    billedFeeAmount: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    calcMicrRt: string;
    comment: string;
    commentCodeValue: number;
    commentCodeValueSpecified: boolean;
    commentCode: number | null;
    confirmationNumber: string;
    confirmationSeqValue: number;
    confirmationSeqValueSpecified: boolean;
    confirmationSeq: number | null;
    consoleNumberValue: number;
    consoleNumberValueSpecified: boolean;
    consoleNumber: number | null;
    description: string;
    dispositionFeeValue: number;
    dispositionFeeValueSpecified: boolean;
    dispositionFee: number | null;
    draftNumber: string;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    escrowAmountValue: number;
    escrowAmountValueSpecified: boolean;
    escrowAmount: number | null;
    escrowAppliedBalChgValue: number;
    escrowAppliedBalChgValueSpecified: boolean;
    escrowAppliedBalChg: number | null;
    escrowUnpaidBalChgValue: number;
    escrowUnpaidBalChgValueSpecified: boolean;
    escrowUnpaidBalChg: number | null;
    feeAmountValue: number;
    feeAmountValueSpecified: boolean;
    feeAmount: number | null;
    feeCountByValue: number;
    feeCountByValueSpecified: boolean;
    feeCountBy: number | null;
    feeExmtCrtsyAmtValue: number;
    feeExmtCrtsyAmtValueSpecified: boolean;
    feeExmtCrtsyAmt: number | null;
    id: string;
    idTypeValue: number;
    idTypeValueSpecified: boolean;
    idType: number | null;
    intEffectDateValue: string;
    intEffectDateValueSpecified: boolean;
    intEffectDate: string | null;
    interestValue: number;
    interestValueSpecified: boolean;
    interest: number | null;
    lastTranDateValue: string;
    lastTranDateValueSpecified: boolean;
    lastTranDate: string | null;
    lateChgFieldsValidValue: number;
    lateChgFieldsValidValueSpecified: boolean;
    lateChgFieldsValid: number | null;
    lateChgUnpaidChgAmtValue: number;
    lateChgUnpaidChgAmtValueSpecified: boolean;
    lateChgUnpaidChgAmt: number | null;
    lateChgWaivedAmtValue: number;
    lateChgWaivedAmtValueSpecified: boolean;
    lateChgWaivedAmt: number | null;
    maturityLoanDueDateValue: string;
    maturityLoanDueDateValueSpecified: boolean;
    maturityLoanDueDate: string | null;
    memberBranch: string;
    micrAcctNum: string;
    micrRt: string;
    miscExpenseAmountValue: number;
    miscExpenseAmountValueSpecified: boolean;
    miscExpenseAmount: number | null;
    newBalanceValue: number;
    newBalanceValueSpecified: boolean;
    newBalance: number | null;
    postDateValue: string;
    postDateValueSpecified: boolean;
    postDate: string | null;
    postTimeValue: number;
    postTimeValueSpecified: boolean;
    postTime: number | null;
    prevAvailBalanceValue: number;
    prevAvailBalanceValueSpecified: boolean;
    prevAvailBalance: number | null;
    prevLateChgAccruedValue: number;
    prevLateChgAccruedValueSpecified: boolean;
    prevLateChgAccrued: number | null;
    prevLateChgDateValue: string;
    prevLateChgDateValueSpecified: boolean;
    prevLateChgDate: string | null;
    processorUserValue: number;
    processorUserValueSpecified: boolean;
    processorUser: number | null;
    recurringTranValue: number;
    recurringTranValueSpecified: boolean;
    recurringTran: number | null;
    regDCheckCodeValue: number;
    regDCheckCodeValueSpecified: boolean;
    regDCheckCode: number | null;
    regDTransferCodeValue: number;
    regDTransferCodeValueSpecified: boolean;
    regDTransferCode: number | null;
    regECodeValue: number;
    regECodeValueSpecified: boolean;
    regECode: number | null;
    salesTaxAmountValue: number;
    salesTaxAmountValueSpecified: boolean;
    salesTaxAmount: number | null;
    securityLevelsValue: number;
    securityLevelsValueSpecified: boolean;
    securityLevels: number | null;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    sourceCode: string;
    stmtDesc: LoanTransactionStmtDesc[];
    stmtDescSpecified: boolean;
    subActionCode: string;
    subSourceValue: number;
    subSourceValueSpecified: boolean;
    subSource: number | null;
    subSourceDescr: string;
    terminationFeeValue: number;
    terminationFeeValueSpecified: boolean;
    terminationFee: number | null;
    tracerNumber: string;
    tranAmountValue: number;
    tranAmountValueSpecified: boolean;
    tranAmount: number | null;
    transferCodeValue: number;
    transferCodeValueSpecified: boolean;
    transferCode: number | null;
    unappliedPartialPmtChgValue: number;
    unappliedPartialPmtChgValueSpecified: boolean;
    unappliedPartialPmtChg: number | null;
    userNumberValue: number;
    userNumberValueSpecified: boolean;
    userNumber: number | null;
    userOverrideValue: number;
    userOverrideValueSpecified: boolean;
    userOverride: number | null;
    voidCodeValue: number;
    voidCodeValueSpecified: boolean;
    voidCode: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}