import { VersionType } from "./versionType";

export interface LoanAppEscrow_2 {
    day1: number | null;
    day2: number | null;
    distribFrequency: number | null;
    escrowType: number | null;
    expirationDate: string | null;
    floodInsTracking: number | null;
    forcedPlacedIns: number | null;
    invoiceNumber: string;
    lastAmtNeededPmt: number | null;
    lastDateAnaCalc: string | null;
    lastDisbursAmt: number | null;
    lastDisbursDate: string | null;
    lastDisbursFreq: number | null;
    lastDisburseDay1: number | null;
    lastDisburseDay2: number | null;
    lastDistribAmount: number | null;
    lastDistribDate: string | null;
    lastExpirationDate: string | null;
    lastMonthCushion: number | null;
    lastNbrPmtsDue: number | null;
    lastTotAnnDisburs: number | null;
    legalDescription: string;
    locator: number | null;
    nextDistribAmount: number | null;
    nextDistribDate: string | null;
    parcelNumber: string;
    payDividend: number | null;
    paymentPortion: number | null;
    pmiCancelDate: string | null;
    pmiCancelNotice: number | null;
    pmiDisclosureDate: string | null;
    pmiEligNotices: number | null;
    pmiMidTermDate: string | null;
    pmiTermDate: string | null;
    policyAmount: number | null;
    policyExpireDate: string | null;
    policyNumber: string;
    policyOrigDate: string | null;
    policyOwner: string;
    prevAmtNeededPmt: number | null;
    prevDateAnaCalc: string | null;
    prevDisbursAmt: number | null;
    prevDisbursDate: string | null;
    prevDisbursFreq: number | null;
    prevDisburseDay1: number | null;
    prevDisburseDay2: number | null;
    prevExpirationDate: string | null;
    prevMonthCushion: number | null;
    prevNbrPmtsDue: number | null;
    prevTotAnnDisburs: number | null;
    printDistribNotice: number | null;
    realEstateOwner: string;
    recordChangeDate: string | null;
    savedAdjustPayment: number | null;
    taxRefNumber: string;
    trackingOnly: number | null;
    vendorName: string;
    vendorNumber: string;
    version1: VersionType;
    pmiCancelReason: number | null;
    version2: VersionType;
}