import { LoanAppLnSegmentPmtBucketAmount } from "./loanAppLnSegmentPmtBucketAmount";
import { VersionType } from "./versionType";

export interface LoanAppLnSegment {
    applyAsBilled: number | null;
    balance: number | null;
    balloonAmount: number | null;
    balloonDate: string | null;
    beginningCycleDate: string | null;
    billingDefaultDays: number | null;
    billingMethod: number | null;
    closeDate: string | null;
    description: string;
    discountRate: number | null;
    exceedLevelPmtAmt: number | null;
    firstPaymentDate: string | null;
    id: string;
    intUnpaidBilled: number | null;
    intYtd: number | null;
    interestLastYear: number | null;
    interestRate: number | null;
    interestRateIndex: number | null;
    interestRateMargin: number | null;
    interestRateMarginSign: number | null;
    interestRateMax: number | null;
    interestRateMin: number | null;
    interestType: number | null;
    interestUnpaid: number | null;
    lastPaymentDate: string | null;
    levelPaymentAmt: number | null;
    levelPrincipalAmt: number | null;
    maturityDate: string | null;
    minimumPayment: number | null;
    openDate: string | null;
    originalBalance: number | null;
    originalDate: string | null;
    partialPayment: number | null;
    payment: number | null;
    paymentCalcType: number | null;
    paymentDue: number | null;
    paymentOrder: number | null;
    paymentType: number | null;
    payoffAmount: number | null;
    percentPrincipal: number | null;
    periodicCap: number | null;
    periodicFrequency: number | null;
    periodicStartDate: string | null;
    periodicStartRate: number | null;
    pmtBucketAmount: LoanAppLnSegmentPmtBucketAmount[];
    recordChangeDate: string | null;
    riskRate: number | null;
    schdPeriodStartDate: string | null;
    schdPeriodStartRate: number | null;
    schdRate: number | null;
    schdRateChangeDate: string | null;
    type: number | null;
    variableRateIndicator: number | null;
    version1: VersionType;
}