import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface MbrAddressFields {
    addrCreateDateValue: boolean;
    addrCreateDateValueSpecified: boolean;
    addrCreateDate: boolean | null;
    addrDisconnectDateValue: boolean;
    addrDisconnectDateValueSpecified: boolean;
    addrDisconnectDate: boolean | null;
    addrExpDateValue: boolean;
    addrExpDateValueSpecified: boolean;
    addrExpDate: boolean | null;
    addrFmLastDateValue: boolean;
    addrFmLastDateValueSpecified: boolean;
    addrFmLastDate: boolean | null;
    addrFmLastPurgeDateValue: boolean;
    addrFmLastPurgeDateValueSpecified: boolean;
    addrFmLastPurgeDate: boolean | null;
    addrRecordChangeDateValue: boolean;
    addrRecordChangeDateValueSpecified: boolean;
    addrRecordChangeDate: boolean | null;
    addressTypeValue: boolean;
    addressTypeValueSpecified: boolean;
    addressType: boolean | null;
    carrierRouteValue: boolean;
    carrierRouteValueSpecified: boolean;
    carrierRoute: boolean | null;
    cityValue: boolean;
    cityValueSpecified: boolean;
    city: boolean | null;
    countryValue: boolean;
    countryValueSpecified: boolean;
    country: boolean | null;
    countryCodeValue: boolean;
    countryCodeValueSpecified: boolean;
    countryCode: boolean | null;
    extraAddressValue: boolean;
    extraAddressValueSpecified: boolean;
    extraAddress: boolean | null;
    headquartersValue: boolean;
    headquartersValueSpecified: boolean;
    headquarters: boolean | null;
    mbrAddrFileTypeValue: boolean;
    mbrAddrFileTypeValueSpecified: boolean;
    mbrAddrFileType: boolean | null;
    mbrAddrNumberValue: boolean;
    mbrAddrNumberValueSpecified: boolean;
    mbrAddrNumber: boolean | null;
    stateValue: boolean;
    stateValueSpecified: boolean;
    state: boolean | null;
    streetValue: boolean;
    streetValueSpecified: boolean;
    street: boolean | null;
    zipCodeValue: boolean;
    zipCodeValueSpecified: boolean;
    zipCode: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}