import { MemberRecIdentDocFlag } from "./memberRecIdentDocFlag";
import { MemberRecIdentIdDescription } from "./memberRecIdentIdDescription";
import { MemberRecIdentIdExpireDate } from "./memberRecIdentIdExpireDate";
import { MemberRecIdentIdIssueDate } from "./memberRecIdentIdIssueDate";
import { MemberRecIdentIdNumber } from "./memberRecIdentIdNumber";
import { MemberRecIdentIdType } from "./memberRecIdentIdType";
import { MemberRecIdentIdVerifyDate } from "./memberRecIdentIdVerifyDate";
import { MemberRecFmHistoryList } from "./memberRecFmHistoryList";
import { VersionType } from "./versionType";

export interface MemberRec {
    activeDuty: number | null;
    activeDutySeparationDate: string | null;
    activeDutyStartDate: string | null;
    activeDutyVerificationDate: string | null;
    altEmail: string;
    birthDate: string | null;
    chapter4StatusCode: string;
    ctrExempt: number | null;
    currGrossMonthPay: number | null;
    currNetMonthPay: number | null;
    dbaExtendedName: string;
    dbaFirst: string;
    dbaLast: string;
    dbaLongName: string;
    dbaMiddle: string;
    dbaNameFormat: number | null;
    dbaShortName: string;
    dbaSuffix: string;
    dbaTitle: string;
    deathDate: string | null;
    email: string;
    employerName: string;
    extendedName: string;
    first: string;
    foreignTin: string;
    formW8OnFile: number | null;
    gIin: string;
    homePhone: string;
    identDocFlag: MemberRecIdentDocFlag[];
    identIdDescription: MemberRecIdentIdDescription[];
    identIdExpireDate: MemberRecIdentIdExpireDate[];
    identIdIssueDate: MemberRecIdentIdIssueDate[];
    identIdNumber: MemberRecIdentIdNumber[];
    identIdType: MemberRecIdentIdType[];
    identIdVerifyDate: MemberRecIdentIdVerifyDate[];
    irsCountryCode: string;
    last: string;
    lei: string;
    license: string;
    lob: string;
    longName: string;
    mbrActivityDate: string | null;
    mbrCreateDate: string | null;
    mbrCurrMthPayChgDate: string | null;
    mbrDisconnectDate: string | null;
    mbrExpDate: string | null;
    mbrFileType: number | null;
    mbrFmLastDate: string | null;
    mbrFmLastPurgeDate: string | null;
    mbrRecordChangeDate: string | null;
    mbrStatus: number | null;
    mbrStatusFmDate: string | null;
    memberNumber: string;
    memberRecFmHistoryList: MemberRecFmHistoryList;
    middle: string;
    mobilePhone: string;
    mothersMaidenName: string;
    nameFormat: number | null;
    nraExemptionCode: string;
    nraTaxRate: number | null;
    occupation: string;
    pagerNumber: string;
    phoneType: number | null;
    preferredContact: string;
    preferredContactMethod: number | null;
    restrict: number | null;
    sex: string;
    shortName: string;
    ssn: string;
    ssnType: number | null;
    substantialOwner: number | null;
    suffix: string;
    title: string;
    usPersonFlag: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    w8ExpirationDate: string | null;
    workPhone: string;
    workPhoneExtension: string;
    version1: VersionType;
}