import { MemberRecIdentDocFlag_2 } from "./memberRecIdentDocFlag_2";
import { MemberRecIdentIdDescription_2 } from "./memberRecIdentIdDescription_2";
import { MemberRecIdentIdExpireDate_2 } from "./memberRecIdentIdExpireDate_2";
import { MemberRecIdentIdIssueDate_2 } from "./memberRecIdentIdIssueDate_2";
import { MemberRecIdentIdNumber_2 } from "./memberRecIdentIdNumber_2";
import { MemberRecIdentIdType_2 } from "./memberRecIdentIdType_2";
import { MemberRecIdentIdVerifyDate_2 } from "./memberRecIdentIdVerifyDate_2";
import { VersionType } from "./versionType";

export interface MemberRec_2 {
    activeDuty: number | null;
    activeDutySeparationDate: string | null;
    activeDutyStartDate: string | null;
    activeDutyVerificationDate: string | null;
    altEmail: string;
    birthDate: string | null;
    chapter4StatusCode: string;
    ctrExempt: number | null;
    currGrossMonthPay: number | null;
    currNetMonthPay: number | null;
    dbaExtendedName: string;
    dbaFirst: string;
    dbaLast: string;
    dbaLongName: string;
    dbaMiddle: string;
    dbaNameFormat: number | null;
    dbaShortName: string;
    dbaSuffix: string;
    dbaTitle: string;
    deathDate: string | null;
    email: string;
    employerName: string;
    extendedName: string;
    first: string;
    foreignTin: string;
    formW8OnFile: number | null;
    gIin: string;
    homePhone: string;
    identDocFlag: MemberRecIdentDocFlag_2[];
    identIdDescription: MemberRecIdentIdDescription_2[];
    identIdExpireDate: MemberRecIdentIdExpireDate_2[];
    identIdIssueDate: MemberRecIdentIdIssueDate_2[];
    identIdNumber: MemberRecIdentIdNumber_2[];
    identIdType: MemberRecIdentIdType_2[];
    identIdVerifyDate: MemberRecIdentIdVerifyDate_2[];
    irsCountryCode: string;
    last: string;
    lei: string;
    license: string;
    lob: string;
    longName: string;
    mbrActivityDate: string | null;
    mbrCreateDate: string | null;
    mbrCurrMthPayChgDate: string | null;
    mbrDisconnectDate: string | null;
    mbrExpDate: string | null;
    mbrFileType: number | null;
    mbrFmLastDate: string | null;
    mbrFmLastPurgeDate: string | null;
    mbrRecordChangeDate: string | null;
    mbrStatus: number | null;
    mbrStatusFmDate: string | null;
    memberNumber: string;
    middle: string;
    mobilePhone: string;
    mothersMaidenName: string;
    nameFormat: number | null;
    nraExemptionCode: string;
    nraTaxRate: number | null;
    occupation: string;
    pagerNumber: string;
    phoneType: number | null;
    preferredContact: string;
    preferredContactMethod: number | null;
    restrict: number | null;
    sex: string;
    shortName: string;
    ssn: string;
    ssnType: number | null;
    substantialOwner: number | null;
    suffix: string;
    title: string;
    usPersonFlag: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    w8ExpirationDate: string | null;
    workPhone: string;
    workPhoneExtension: string;
    version1: VersionType;
}