import { MiscPmtAccountMask_2 } from "./miscPmtAccountMask_2";
import { MiscPmtFicsDataSourceName_2 } from "./miscPmtFicsDataSourceName_2";
import { MiscPmtMpQuestionFormat_2 } from "./miscPmtMpQuestionFormat_2";
import { MiscPmtOnlineDbPassword_2 } from "./miscPmtOnlineDbPassword_2";
import { MiscPmtOnlineDbUserId_2 } from "./miscPmtOnlineDbUserId_2";
import { MiscPmtOnlineGlobalAppPasswd_2 } from "./miscPmtOnlineGlobalAppPasswd_2";
import { MiscPmtOnlineGlobalAppUserId_2 } from "./miscPmtOnlineGlobalAppUserId_2";
import { MiscPmtProcTranCodePayment1_2 } from "./miscPmtProcTranCodePayment1_2";
import { MiscPmtProcTranCodePayment10_2 } from "./miscPmtProcTranCodePayment10_2";
import { MiscPmtProcTranCodePayment2_2 } from "./miscPmtProcTranCodePayment2_2";
import { MiscPmtProcTranCodePayment3_2 } from "./miscPmtProcTranCodePayment3_2";
import { MiscPmtProcTranCodePayment4_2 } from "./miscPmtProcTranCodePayment4_2";
import { MiscPmtProcTranCodePayment5_2 } from "./miscPmtProcTranCodePayment5_2";
import { MiscPmtProcTranCodePayment6_2 } from "./miscPmtProcTranCodePayment6_2";
import { MiscPmtProcTranCodePayment7_2 } from "./miscPmtProcTranCodePayment7_2";
import { MiscPmtProcTranCodePayment8_2 } from "./miscPmtProcTranCodePayment8_2";
import { MiscPmtProcTranCodePayment9_2 } from "./miscPmtProcTranCodePayment9_2";
import { MiscPmtProcTranCodePmtDesc1_2 } from "./miscPmtProcTranCodePmtDesc1_2";
import { MiscPmtProcTranCodePmtDesc10_2 } from "./miscPmtProcTranCodePmtDesc10_2";
import { MiscPmtProcTranCodePmtDesc2_2 } from "./miscPmtProcTranCodePmtDesc2_2";
import { MiscPmtProcTranCodePmtDesc3_2 } from "./miscPmtProcTranCodePmtDesc3_2";
import { MiscPmtProcTranCodePmtDesc4_2 } from "./miscPmtProcTranCodePmtDesc4_2";
import { MiscPmtProcTranCodePmtDesc5_2 } from "./miscPmtProcTranCodePmtDesc5_2";
import { MiscPmtProcTranCodePmtDesc6_2 } from "./miscPmtProcTranCodePmtDesc6_2";
import { MiscPmtProcTranCodePmtDesc7_2 } from "./miscPmtProcTranCodePmtDesc7_2";
import { MiscPmtProcTranCodePmtDesc8_2 } from "./miscPmtProcTranCodePmtDesc8_2";
import { MiscPmtProcTranCodePmtDesc9_2 } from "./miscPmtProcTranCodePmtDesc9_2";
import { MiscPmtProcessorAbbreviation_2 } from "./miscPmtProcessorAbbreviation_2";
import { MiscPmtProcessorAcctVerCode_2 } from "./miscPmtProcessorAcctVerCode_2";
import { MiscPmtProcessorCode_2 } from "./miscPmtProcessorCode_2";
import { MiscPmtProcessorName_2 } from "./miscPmtProcessorName_2";
import { MiscPmtTrackingTypes_2 } from "./miscPmtTrackingTypes_2";
import { MiscPmtTransactionGlCode_2 } from "./miscPmtTransactionGlCode_2";
import { VersionType } from "./versionType";

export interface MiscPmt_2 {
    accountMask: MiscPmtAccountMask_2[];
    ficsDataSourceName: MiscPmtFicsDataSourceName_2[];
    mpQuestionFormat: MiscPmtMpQuestionFormat_2[];
    onlineDbPassword: MiscPmtOnlineDbPassword_2[];
    onlineDbUserId: MiscPmtOnlineDbUserId_2[];
    onlineGlobalAppPasswd: MiscPmtOnlineGlobalAppPasswd_2[];
    onlineGlobalAppUserId: MiscPmtOnlineGlobalAppUserId_2[];
    procTranCodePayment1: MiscPmtProcTranCodePayment1_2[];
    procTranCodePayment10: MiscPmtProcTranCodePayment10_2[];
    procTranCodePayment2: MiscPmtProcTranCodePayment2_2[];
    procTranCodePayment3: MiscPmtProcTranCodePayment3_2[];
    procTranCodePayment4: MiscPmtProcTranCodePayment4_2[];
    procTranCodePayment5: MiscPmtProcTranCodePayment5_2[];
    procTranCodePayment6: MiscPmtProcTranCodePayment6_2[];
    procTranCodePayment7: MiscPmtProcTranCodePayment7_2[];
    procTranCodePayment8: MiscPmtProcTranCodePayment8_2[];
    procTranCodePayment9: MiscPmtProcTranCodePayment9_2[];
    procTranCodePmtDesc1: MiscPmtProcTranCodePmtDesc1_2[];
    procTranCodePmtDesc10: MiscPmtProcTranCodePmtDesc10_2[];
    procTranCodePmtDesc2: MiscPmtProcTranCodePmtDesc2_2[];
    procTranCodePmtDesc3: MiscPmtProcTranCodePmtDesc3_2[];
    procTranCodePmtDesc4: MiscPmtProcTranCodePmtDesc4_2[];
    procTranCodePmtDesc5: MiscPmtProcTranCodePmtDesc5_2[];
    procTranCodePmtDesc6: MiscPmtProcTranCodePmtDesc6_2[];
    procTranCodePmtDesc7: MiscPmtProcTranCodePmtDesc7_2[];
    procTranCodePmtDesc8: MiscPmtProcTranCodePmtDesc8_2[];
    procTranCodePmtDesc9: MiscPmtProcTranCodePmtDesc9_2[];
    processorAbbreviation: MiscPmtProcessorAbbreviation_2[];
    processorAcctVerCode: MiscPmtProcessorAcctVerCode_2[];
    processorCode: MiscPmtProcessorCode_2[];
    processorName: MiscPmtProcessorName_2[];
    processorPromptOrder: number | null;
    trackingTypes: MiscPmtTrackingTypes_2[];
    transactionGlCode: MiscPmtTransactionGlCode_2[];
    version1: VersionType;
}