import { VersionType } from "./versionType";

export interface MiscFields {
    acceptThresholdPmtinTllr: boolean | null;
    acceptUnappliedPmtinTlr: boolean | null;
    accountManagerSpecfile: boolean | null;
    acctVerifyOnIqFmMenus: boolean | null;
    acctVerifyonXfrDeposit: boolean | null;
    acsSys: boolean | null;
    addtoCheckPayeeLines: boolean | null;
    apAchPayments: boolean | null;
    audioAccessLen: boolean | null;
    audioLnApp: boolean | null;
    audioPinHbPwdAccess: boolean | null;
    autoBatch: boolean | null;
    availBalHoldTypeExclList: boolean | null;
    bankruptcy: boolean | null;
    batchOutputtoPrintControl: boolean | null;
    biodentify: boolean | null;
    bondsRequireMicrData: boolean | null;
    bulkDepHoldIncludesCash: boolean | null;
    bulkDepositHoldDays: boolean | null;
    bulkReconDays: boolean | null;
    cardActRounding: boolean | null;
    cardDisputeWarning: boolean | null;
    cardNumberMask: boolean | null;
    cardSwipeAuditFile: boolean | null;
    cashReportingGlCodes: boolean | null;
    ccBalanceTransfer: boolean | null;
    ccExpansion: boolean | null;
    cdmSys: boolean | null;
    certApyEarnedDisclosure: boolean | null;
    certPenaltybyPowerOn: boolean | null;
    certifiedExpirationDays: boolean | null;
    cfmCdmSys: boolean | null;
    chapter4TaxRate: boolean | null;
    chargeOffPaymentOrder: boolean | null;
    chargePartialCapFee: boolean | null;
    chargedOffLoanPmtOption: boolean | null;
    chargedOffLoanTypesList: boolean | null;
    chargedOffShareDepOption: boolean | null;
    chargedOffShareTypesList: boolean | null;
    checkDepTrack: boolean | null;
    checkFmHistoryControl: boolean | null;
    checkName: boolean | null;
    checkPrintFormat: boolean | null;
    checkValidatorUse: boolean | null;
    checkingName: boolean | null;
    checksRequireMicrData: boolean | null;
    chgAcctNumWizLookupType: boolean | null;
    chgAcctNumWizSpecfile: boolean | null;
    ckValidatorRtNumber: boolean | null;
    cmntByCdMoTcTrancodes: boolean | null;
    cmntByFdFrTrancodes: boolean | null;
    cmntByKcTrancode: boolean | null;
    cmntByKdKoKsTrancodes: boolean | null;
    cmntByKrTranCode: boolean | null;
    cmntByNsfAchAmount: boolean | null;
    cmntByNsfDraftAmount: boolean | null;
    cmntBySpTrancode: boolean | null;
    cmntbyCheckHold: boolean | null;
    cmntbyTellerTrnCodeFees: boolean | null;
    collateralSystem: boolean | null;
    combinationLoans: boolean | null;
    commentCode0Allowed: boolean | null;
    commentCodeRequired: boolean | null;
    confirmationSequence: boolean | null;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCode: boolean | null;
    createMemoExceptionItems: boolean | null;
    createRateChangeComment: boolean | null;
    credRepSys: boolean | null;
    creditCardLocAvailable: boolean | null;
    creditDebitCardTypeList: boolean | null;
    csTtInquiries: boolean | null;
    ctr: boolean | null;
    cuType: boolean | null;
    cusoInstitution: boolean | null;
    databaseEncryption: boolean | null;
    dbEvolution: number[];
    dbEvolutionReport: number[];
    dealerReserveAccounting: boolean | null;
    demandTranCheckReference: boolean | null;
    demandTranMaxLookbackDays: boolean | null;
    demandTranMerchVerHoldDays: boolean | null;
    disbursalTransactionTypes: boolean | null;
    displayAcctMgrFmHistory: boolean | null;
    displayMemberMgrFmHistory: boolean | null;
    displayRmtOvrAckMsg: boolean | null;
    displayRmtOvrAlertMsg: boolean | null;
    displayRmtOvrPrivBrList: boolean | null;
    displayRmtOvrPrivList: boolean | null;
    divPeriodStartMethod: boolean | null;
    dividendName: boolean | null;
    dividendRoundingMethod: boolean | null;
    dormancyDays: boolean | null;
    dormancyUseCorrespondDate: boolean | null;
    dqCardNoticeNumber: boolean | null;
    draftNumberofLookBackDays: boolean | null;
    draftPreauthorized: number[];
    draftStopDuplicates: boolean | null;
    driversLcnsSwipeAuditFile: boolean | null;
    employeePayroll: number[];
    enableTextMode: boolean | null;
    escrow: boolean | null;
    escrowShareTypeList: boolean | null;
    excessiveCheck: boolean | null;
    expandWarningCodes: boolean | null;
    externalAcct: boolean | null;
    externalLoan: boolean | null;
    feeTypesToCapList: boolean | null;
    fileRevision: boolean | null;
    finRepSequence: boolean | null;
    floats: boolean | null;
    fmHistoryControl: boolean | null;
    forcedCommentFormatList: boolean | null;
    glAccountantPreference: boolean | null;
    glCheckDisbursedPrompt: boolean | null;
    glCommentByPowerOn: boolean | null;
    glDailyAccrual: boolean | null;
    glMonth: boolean | null;
    glTranslationBranchAcctIng: boolean | null;
    glTranslationBranchLevel: boolean | null;
    glTranslationMaxBranch: boolean | null;
    glTranslationMaxUser: boolean | null;
    glYearStartMonth: boolean | null;
    globalSequence: boolean | null;
    guaranteedHoldTypeList: boolean | null;
    hbAudioPasswordHashCode: boolean | null;
    hbPasswordEnforceMixedCase: boolean | null;
    hbPasswordMaxAge: boolean | null;
    hbPasswordMaxRepeatChars: boolean | null;
    hbPasswordMaximumLength: boolean | null;
    hbPasswordMinAge: boolean | null;
    hbPasswordMinAlphaChars: boolean | null;
    hbPasswordMinDiffChars: boolean | null;
    hbPasswordMinNumericChars: boolean | null;
    hbPasswordMinOtherChars: boolean | null;
    hbPasswordMinSpecialChars: boolean | null;
    hbPasswordMinimumLength: boolean | null;
    hbPasswordMode: boolean | null;
    hbPasswordRecycleTimes: boolean | null;
    hbPwSpecialCharsAllowed: boolean | null;
    hbUsernameMaximumLength: boolean | null;
    hbUsernameMinimumLength: boolean | null;
    holdReuseDays: boolean | null;
    holdReuseMethod: boolean | null;
    idNumberMask: boolean | null;
    identificationLine: boolean | null;
    institution: boolean | null;
    insuranceUpdtsActivityDate: boolean | null;
    intAccrCmtLnTypes: boolean | null;
    irs1042SUfidLastUsed: boolean | null;
    itcAutoAcceptOnPrompts: boolean | null;
    itcAutomatedOnPosting: boolean | null;
    itcDefaultCheckHoldDays: boolean | null;
    itcDeviceEnabled: boolean | null;
    itcEndorsement: boolean | null;
    itcMicrLookupTypeList: boolean | null;
    itcModuleEnabled: boolean | null;
    kitingSuspectAmt: boolean | null;
    kitingSuspectDepositCount: boolean | null;
    kitingSuspectDepositDays: boolean | null;
    kitingSuspectWaiveWarning: boolean | null;
    lastSystemDate: boolean | null;
    lateChgAccrCmtLnTypes: boolean | null;
    leaseSys: boolean | null;
    legalEntityIdentifier: boolean | null;
    limitDeclChkAxsFeeChgDt: boolean | null;
    limitDeclChkAxsFeeFirst: boolean | null;
    limitDeclChkAxsFeeFolowng: boolean | null;
    limitLateFeeFirst: boolean | null;
    limitLateFeeFollowing: boolean | null;
    limitLateFeeMethodChgDate: boolean | null;
    limitOvlFeeFirst: boolean | null;
    limitOvlFeeFollowing: boolean | null;
    limitOvlFeeMethodChgDate: boolean | null;
    lnPmtHoldinAvailAmtCalc: boolean | null;
    loanAppSys: boolean | null;
    loanCommentbyPowerOn: boolean | null;
    loanExclusionWarnCodeList: boolean | null;
    loanInterestAccrual: boolean | null;
    loanPayoffIncludesInsurance: boolean | null;
    loanTypeList: boolean | null;
    logAccessEvents: boolean | null;
    maprCreditCardFeeTypes: boolean | null;
    maprNonBonaFideFeeTypes: boolean | null;
    maskCardTypes: boolean | null;
    maskLoanTypes: boolean | null;
    maskLoanappFinanceTypes: boolean | null;
    maskLookupTypes: boolean | null;
    maximumFutureEffectiveDays: boolean | null;
    maximumWdBelowAvailable: boolean | null;
    mbrInstLogins: boolean | null;
    militaryAprFeeTypes: boolean | null;
    minimumRetentionPercent: boolean | null;
    moneyPrintFormat: boolean | null;
    nameKeyExpansion: boolean | null;
    nameMerge: boolean | null;
    newBillingCalculations: boolean | null;
    newWireUscExtractCutoffTi: boolean | null;
    nextAccountNumber: boolean | null;
    nextAccountPrefix: boolean | null;
    nextAccountStep: boolean | null;
    nextBatchId: boolean | null;
    nextCollateralNumber: boolean | null;
    nextCollateralStep: boolean | null;
    nextDocumentNumber: boolean | null;
    nextDocumentStep: boolean | null;
    nextNoteNumber: boolean | null;
    nextNoteStep: boolean | null;
    noticeFormat: boolean | null;
    numberOfInvalidPinAttempts: boolean | null;
    odsProcessCount: boolean | null;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodes: boolean | null;
    ofacChecking: boolean | null;
    ofacCorpCheckSpecfile: boolean | null;
    ofacMatchAcceptedWoPriv: boolean | null;
    onUsDraftCommentCode: boolean | null;
    onUsOverdrawOption: boolean | null;
    onlineParameterOption: boolean | null;
    overdraftTol: boolean | null;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverride: boolean | null;
    overdrawNoticeSpecfile: boolean | null;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOption: boolean | null;
    overdrawTransferFeeGlCode: boolean | null;
    overdrawWithdrawalIncrement: boolean | null;
    passwordExpWarningDays: boolean | null;
    passwordHashing: boolean | null;
    passwordMaxInvalidAttempts: boolean | null;
    passwordMaximumAge: boolean | null;
    passwordMaximumRepeatChars: boolean | null;
    passwordMinimumAge: boolean | null;
    passwordMinimumAlphaChars: boolean | null;
    passwordMinimumDiffChars: boolean | null;
    passwordMinimumLength: boolean | null;
    passwordMinimumNumChars: boolean | null;
    passwordMinimumOtherChars: boolean | null;
    passwordRecycleTimes: boolean | null;
    passwordsCaseSensitive: boolean | null;
    paymentHistoryDayCutoff: number[];
    pinChangeDays: boolean | null;
    pinMask: boolean | null;
    positivePayDraft: boolean | null;
    powerOnControlDeluxeEditor: boolean | null;
    preAuthWireUscExtractCuto: boolean | null;
    primeShareTypeList: boolean | null;
    printInstitutiononNotice: boolean | null;
    printInstitutiononReceipt: boolean | null;
    printItcImages: boolean | null;
    promptForMicrInfoInDrOn: boolean | null;
    promptfor000CrtsyPayFee: boolean | null;
    promptfor000TransferFee: boolean | null;
    rateDecimalDigits: boolean | null;
    rcntTellerActWaiveWarning: boolean | null;
    rcntTllrActvtyCnslsList: boolean | null;
    rcntTllrActvtyCriteria: boolean | null;
    rcntTllrActvtyIncludeTllr: boolean | null;
    rcntTllrActvtyReqMultTllr: boolean | null;
    reactivateSecurityOvrMsg: boolean | null;
    receiptAddressPrint: boolean | null;
    receiptAlternateAddress: boolean | null;
    receiptBalancePrint: boolean | null;
    receiptOtherAccountOption: boolean | null;
    receiptPreviousBalance: boolean | null;
    receiptPrint: boolean | null;
    receiptReprintEnable: boolean | null;
    receiptSuppressXferAcct: boolean | null;
    recentTellerActivityDays: boolean | null;
    regDLimitingMethod: boolean | null;
    regDLimitingTypeList: boolean | null;
    regulationZFeeTypes: boolean | null;
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier6: number[];
    relCodeList: number[];
    relCourtesyPayFee1: number[];
    relCourtesyPayFee2: number[];
    relCourtesyPayFee3: number[];
    relCourtesyPayFee4: number[];
    relCourtesyPayFee5: number[];
    relCourtesyPayFee6: number[];
    relCourtesyPayTier1: number[];
    relCourtesyPayTier2: number[];
    relCourtesyPayTier3: number[];
    relCourtesyPayTier4: number[];
    relCourtesyPayTier5: number[];
    relCourtesyPayTier6: number[];
    relOverdrawAddonXfrFee: number[];
    relOverdrawComboXfrFee: number[];
    relOverdrawWdXfrFee: number[];
    reportSequenceNumberLength: boolean | null;
    rsaFiId: boolean | null;
    rtNumber: boolean | null;
    savingsName: boolean | null;
    sbaDistrRoundingMethod: boolean | null;
    sbaLoans: boolean | null;
    scopeofMembership: boolean | null;
    secureCardPins: boolean | null;
    shareApyEarnedDisclosure: boolean | null;
    shareCloseOption: boolean | null;
    shareCommentbyPowerOn: boolean | null;
    shareDividendAccrual: boolean | null;
    shareExclusionWarnCodeList: boolean | null;
    shareTypesForOnList: boolean | null;
    shareTypesForSwList: boolean | null;
    signatureLine: boolean | null;
    sourceCodeOptionAch: boolean | null;
    sourceCodeOptionBillPay: boolean | null;
    sourceCodeOptionCard: boolean | null;
    sourceCodeOptionHomeBank: boolean | null;
    sourceCodeOptionPos: boolean | null;
    sourceCodeOptionSharedBr: boolean | null;
    ssnTinMask: boolean | null;
    stateReporting: boolean | null;
    stopPayExpirationDays: boolean | null;
    stopPayExpirationMonths: boolean | null;
    stopPayTrancodeTypes: boolean | null;
    stopPreviousOverdrafts: boolean | null;
    storeFwdMode: boolean | null;
    svAnalysisSys: boolean | null;
    symConnectDialog: boolean | null;
    symFormEmailFormat: boolean | null;
    symFormImagingFormat: boolean | null;
    symFormRegLev: boolean | null;
    systemDate: boolean | null;
    tellerFeDecrOccurrenceCt: boolean | null;
    tellerFeDecreaseFeeCt: boolean | null;
    tellerFePromptFeeType: boolean | null;
    tellerTranRecapSlDesc: boolean | null;
    tellerTranSpecfile: boolean | null;
    tellerTrnNameDisplay: boolean | null;
    thirdPartyMfa: boolean | null;
    tllrActvtyUsersList: boolean | null;
    tllrTranAnalysisUpdateOpt: boolean | null;
    tranPostLockMethod: boolean | null;
    tranSequence: boolean | null;
    ttValidRg: boolean | null;
    typeLength: boolean | null;
    uiMaxRecsPerResponse: boolean | null;
    uncollectedFeeOption: boolean | null;
    updateExtLoanAddrRealTime: boolean | null;
    usCentralExtct: boolean | null;
    useBondRedemptionTable: boolean | null;
    useCdmForRecyclerVoid: boolean | null;
    useLrScreenDefinitions: boolean | null;
    userActivityControl: boolean | null;
    userDormancyDays: boolean | null;
    userTempPasswordExpHours: boolean | null;
    verbalStopExpirationDays: boolean | null;
    waiveLateChargeLnTypes: boolean | null;
    wdBelowAvailableOption: boolean | null;
    wdCountSourceList: boolean | null;
    wire: boolean | null;
    wireBatchDate: boolean | null;
    wireBatchNbr: boolean | null;
    wireHoldDays: boolean | null;
    withdrawalOverdrawOption: boolean | null;
    yellowHammer: boolean | null;
    version1: VersionType;
    misModuleEnableD: boolean | null;
    version2: VersionType;
}