import { MiscPmtAccountMask } from "./miscPmtAccountMask";
import { MiscPmtFicsDataSourceName } from "./miscPmtFicsDataSourceName";
import { MiscPmtMpQuestionFormat } from "./miscPmtMpQuestionFormat";
import { MiscPmtOnlineDbPassword } from "./miscPmtOnlineDbPassword";
import { MiscPmtOnlineDbUserId } from "./miscPmtOnlineDbUserId";
import { MiscPmtOnlineGlobalAppPasswd } from "./miscPmtOnlineGlobalAppPasswd";
import { MiscPmtOnlineGlobalAppUserId } from "./miscPmtOnlineGlobalAppUserId";
import { MiscPmtProcTranCodePayment1 } from "./miscPmtProcTranCodePayment1";
import { MiscPmtProcTranCodePayment10 } from "./miscPmtProcTranCodePayment10";
import { MiscPmtProcTranCodePayment2 } from "./miscPmtProcTranCodePayment2";
import { MiscPmtProcTranCodePayment3 } from "./miscPmtProcTranCodePayment3";
import { MiscPmtProcTranCodePayment4 } from "./miscPmtProcTranCodePayment4";
import { MiscPmtProcTranCodePayment5 } from "./miscPmtProcTranCodePayment5";
import { MiscPmtProcTranCodePayment6 } from "./miscPmtProcTranCodePayment6";
import { MiscPmtProcTranCodePayment7 } from "./miscPmtProcTranCodePayment7";
import { MiscPmtProcTranCodePayment8 } from "./miscPmtProcTranCodePayment8";
import { MiscPmtProcTranCodePayment9 } from "./miscPmtProcTranCodePayment9";
import { MiscPmtProcTranCodePmtDesc1 } from "./miscPmtProcTranCodePmtDesc1";
import { MiscPmtProcTranCodePmtDesc10 } from "./miscPmtProcTranCodePmtDesc10";
import { MiscPmtProcTranCodePmtDesc2 } from "./miscPmtProcTranCodePmtDesc2";
import { MiscPmtProcTranCodePmtDesc3 } from "./miscPmtProcTranCodePmtDesc3";
import { MiscPmtProcTranCodePmtDesc4 } from "./miscPmtProcTranCodePmtDesc4";
import { MiscPmtProcTranCodePmtDesc5 } from "./miscPmtProcTranCodePmtDesc5";
import { MiscPmtProcTranCodePmtDesc6 } from "./miscPmtProcTranCodePmtDesc6";
import { MiscPmtProcTranCodePmtDesc7 } from "./miscPmtProcTranCodePmtDesc7";
import { MiscPmtProcTranCodePmtDesc8 } from "./miscPmtProcTranCodePmtDesc8";
import { MiscPmtProcTranCodePmtDesc9 } from "./miscPmtProcTranCodePmtDesc9";
import { MiscPmtProcessorAbbreviation } from "./miscPmtProcessorAbbreviation";
import { MiscPmtProcessorAcctVerCode } from "./miscPmtProcessorAcctVerCode";
import { MiscPmtProcessorCode } from "./miscPmtProcessorCode";
import { MiscPmtProcessorName } from "./miscPmtProcessorName";
import { MiscPmtTrackingTypes } from "./miscPmtTrackingTypes";
import { MiscPmtTransactionGlCode } from "./miscPmtTransactionGlCode";
import { VersionType } from "./versionType";

export interface MiscPmt {
    accountMask: MiscPmtAccountMask[];
    ficsDataSourceName: MiscPmtFicsDataSourceName[];
    mpQuestionFormat: MiscPmtMpQuestionFormat[];
    onlineDbPassword: MiscPmtOnlineDbPassword[];
    onlineDbUserId: MiscPmtOnlineDbUserId[];
    onlineGlobalAppPasswd: MiscPmtOnlineGlobalAppPasswd[];
    onlineGlobalAppUserId: MiscPmtOnlineGlobalAppUserId[];
    procTranCodePayment1: MiscPmtProcTranCodePayment1[];
    procTranCodePayment10: MiscPmtProcTranCodePayment10[];
    procTranCodePayment2: MiscPmtProcTranCodePayment2[];
    procTranCodePayment3: MiscPmtProcTranCodePayment3[];
    procTranCodePayment4: MiscPmtProcTranCodePayment4[];
    procTranCodePayment5: MiscPmtProcTranCodePayment5[];
    procTranCodePayment6: MiscPmtProcTranCodePayment6[];
    procTranCodePayment7: MiscPmtProcTranCodePayment7[];
    procTranCodePayment8: MiscPmtProcTranCodePayment8[];
    procTranCodePayment9: MiscPmtProcTranCodePayment9[];
    procTranCodePmtDesc1: MiscPmtProcTranCodePmtDesc1[];
    procTranCodePmtDesc10: MiscPmtProcTranCodePmtDesc10[];
    procTranCodePmtDesc2: MiscPmtProcTranCodePmtDesc2[];
    procTranCodePmtDesc3: MiscPmtProcTranCodePmtDesc3[];
    procTranCodePmtDesc4: MiscPmtProcTranCodePmtDesc4[];
    procTranCodePmtDesc5: MiscPmtProcTranCodePmtDesc5[];
    procTranCodePmtDesc6: MiscPmtProcTranCodePmtDesc6[];
    procTranCodePmtDesc7: MiscPmtProcTranCodePmtDesc7[];
    procTranCodePmtDesc8: MiscPmtProcTranCodePmtDesc8[];
    procTranCodePmtDesc9: MiscPmtProcTranCodePmtDesc9[];
    processorAbbreviation: MiscPmtProcessorAbbreviation[];
    processorAcctVerCode: MiscPmtProcessorAcctVerCode[];
    processorCode: MiscPmtProcessorCode[];
    processorName: MiscPmtProcessorName[];
    processorPromptOrder: number | null;
    trackingTypes: MiscPmtTrackingTypes[];
    transactionGlCode: MiscPmtTransactionGlCode[];
    version1: VersionType;
}