import { MiscPmtAccountMask_2 } from "./miscPmtAccountMask_2";
import { MiscPmtFicsDataSourceName_2 } from "./miscPmtFicsDataSourceName_2";
import { MiscPmtMpQuestionFormat_2 } from "./miscPmtMpQuestionFormat_2";
import { MiscPmtOnlineDbPassword_2 } from "./miscPmtOnlineDbPassword_2";
import { MiscPmtOnlineDbUserId_2 } from "./miscPmtOnlineDbUserId_2";
import { MiscPmtOnlineGlobalAppPasswd_2 } from "./miscPmtOnlineGlobalAppPasswd_2";
import { MiscPmtOnlineGlobalAppUserId_2 } from "./miscPmtOnlineGlobalAppUserId_2";
import { MiscPmtProcTranCodePayment1_2 } from "./miscPmtProcTranCodePayment1_2";
import { MiscPmtProcTranCodePayment10_2 } from "./miscPmtProcTranCodePayment10_2";
import { MiscPmtProcTranCodePayment2_2 } from "./miscPmtProcTranCodePayment2_2";
import { MiscPmtProcTranCodePayment3_2 } from "./miscPmtProcTranCodePayment3_2";
import { MiscPmtProcTranCodePayment4_2 } from "./miscPmtProcTranCodePayment4_2";
import { MiscPmtProcTranCodePayment5_2 } from "./miscPmtProcTranCodePayment5_2";
import { MiscPmtProcTranCodePayment6_2 } from "./miscPmtProcTranCodePayment6_2";
import { MiscPmtProcTranCodePayment7_2 } from "./miscPmtProcTranCodePayment7_2";
import { MiscPmtProcTranCodePayment8_2 } from "./miscPmtProcTranCodePayment8_2";
import { MiscPmtProcTranCodePayment9_2 } from "./miscPmtProcTranCodePayment9_2";
import { MiscPmtProcTranCodePmtDesc1_2 } from "./miscPmtProcTranCodePmtDesc1_2";
import { MiscPmtProcTranCodePmtDesc10_2 } from "./miscPmtProcTranCodePmtDesc10_2";
import { MiscPmtProcTranCodePmtDesc2_2 } from "./miscPmtProcTranCodePmtDesc2_2";
import { MiscPmtProcTranCodePmtDesc3_2 } from "./miscPmtProcTranCodePmtDesc3_2";
import { MiscPmtProcTranCodePmtDesc4_2 } from "./miscPmtProcTranCodePmtDesc4_2";
import { MiscPmtProcTranCodePmtDesc5_2 } from "./miscPmtProcTranCodePmtDesc5_2";
import { MiscPmtProcTranCodePmtDesc6_2 } from "./miscPmtProcTranCodePmtDesc6_2";
import { MiscPmtProcTranCodePmtDesc7_2 } from "./miscPmtProcTranCodePmtDesc7_2";
import { MiscPmtProcTranCodePmtDesc8_2 } from "./miscPmtProcTranCodePmtDesc8_2";
import { MiscPmtProcTranCodePmtDesc9_2 } from "./miscPmtProcTranCodePmtDesc9_2";
import { MiscPmtProcessorAbbreviation_2 } from "./miscPmtProcessorAbbreviation_2";
import { MiscPmtProcessorAcctVerCode_2 } from "./miscPmtProcessorAcctVerCode_2";
import { MiscPmtProcessorCode_2 } from "./miscPmtProcessorCode_2";
import { MiscPmtProcessorName_2 } from "./miscPmtProcessorName_2";
import { MiscPmtTrackingTypes_2 } from "./miscPmtTrackingTypes_2";
import { MiscPmtTransactionGlCode_2 } from "./miscPmtTransactionGlCode_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface MiscPmt_2 {
    accountMask: MiscPmtAccountMask_2[];
    accountMaskSpecified: boolean;
    ficsDataSourceName: MiscPmtFicsDataSourceName_2[];
    ficsDataSourceNameSpecified: boolean;
    mpQuestionFormat: MiscPmtMpQuestionFormat_2[];
    mpQuestionFormatSpecified: boolean;
    onlineDbPassword: MiscPmtOnlineDbPassword_2[];
    onlineDbPasswordSpecified: boolean;
    onlineDbUserId: MiscPmtOnlineDbUserId_2[];
    onlineDbUserIdSpecified: boolean;
    onlineGlobalAppPasswd: MiscPmtOnlineGlobalAppPasswd_2[];
    onlineGlobalAppPasswdSpecified: boolean;
    onlineGlobalAppUserId: MiscPmtOnlineGlobalAppUserId_2[];
    onlineGlobalAppUserIdSpecified: boolean;
    procTranCodePayment1: MiscPmtProcTranCodePayment1_2[];
    procTranCodePayment1Specified: boolean;
    procTranCodePayment10: MiscPmtProcTranCodePayment10_2[];
    procTranCodePayment10Specified: boolean;
    procTranCodePayment2: MiscPmtProcTranCodePayment2_2[];
    procTranCodePayment2Specified: boolean;
    procTranCodePayment3: MiscPmtProcTranCodePayment3_2[];
    procTranCodePayment3Specified: boolean;
    procTranCodePayment4: MiscPmtProcTranCodePayment4_2[];
    procTranCodePayment4Specified: boolean;
    procTranCodePayment5: MiscPmtProcTranCodePayment5_2[];
    procTranCodePayment5Specified: boolean;
    procTranCodePayment6: MiscPmtProcTranCodePayment6_2[];
    procTranCodePayment6Specified: boolean;
    procTranCodePayment7: MiscPmtProcTranCodePayment7_2[];
    procTranCodePayment7Specified: boolean;
    procTranCodePayment8: MiscPmtProcTranCodePayment8_2[];
    procTranCodePayment8Specified: boolean;
    procTranCodePayment9: MiscPmtProcTranCodePayment9_2[];
    procTranCodePayment9Specified: boolean;
    procTranCodePmtDesc1: MiscPmtProcTranCodePmtDesc1_2[];
    procTranCodePmtDesc1Specified: boolean;
    procTranCodePmtDesc10: MiscPmtProcTranCodePmtDesc10_2[];
    procTranCodePmtDesc10Specified: boolean;
    procTranCodePmtDesc2: MiscPmtProcTranCodePmtDesc2_2[];
    procTranCodePmtDesc2Specified: boolean;
    procTranCodePmtDesc3: MiscPmtProcTranCodePmtDesc3_2[];
    procTranCodePmtDesc3Specified: boolean;
    procTranCodePmtDesc4: MiscPmtProcTranCodePmtDesc4_2[];
    procTranCodePmtDesc4Specified: boolean;
    procTranCodePmtDesc5: MiscPmtProcTranCodePmtDesc5_2[];
    procTranCodePmtDesc5Specified: boolean;
    procTranCodePmtDesc6: MiscPmtProcTranCodePmtDesc6_2[];
    procTranCodePmtDesc6Specified: boolean;
    procTranCodePmtDesc7: MiscPmtProcTranCodePmtDesc7_2[];
    procTranCodePmtDesc7Specified: boolean;
    procTranCodePmtDesc8: MiscPmtProcTranCodePmtDesc8_2[];
    procTranCodePmtDesc8Specified: boolean;
    procTranCodePmtDesc9: MiscPmtProcTranCodePmtDesc9_2[];
    procTranCodePmtDesc9Specified: boolean;
    processorAbbreviation: MiscPmtProcessorAbbreviation_2[];
    processorAbbreviationSpecified: boolean;
    processorAcctVerCode: MiscPmtProcessorAcctVerCode_2[];
    processorAcctVerCodeSpecified: boolean;
    processorCode: MiscPmtProcessorCode_2[];
    processorCodeSpecified: boolean;
    processorName: MiscPmtProcessorName_2[];
    processorNameSpecified: boolean;
    processorPromptOrderValue: number;
    processorPromptOrderValueSpecified: boolean;
    processorPromptOrder: number | null;
    trackingTypes: MiscPmtTrackingTypes_2[];
    trackingTypesSpecified: boolean;
    transactionGlCode: MiscPmtTransactionGlCode_2[];
    transactionGlCodeSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}