import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface Ncua5300Fields {
    accruedDividendsValue: boolean;
    accruedDividendsValueSpecified: boolean;
    accruedDividends: boolean | null;
    accruedInterestonInvestmentValue: boolean;
    accruedInterestonInvestmentValueSpecified: boolean;
    accruedInterestonInvestment: boolean | null;
    accruedInterestonLoansValue: boolean;
    accruedInterestonLoansValueSpecified: boolean;
    accruedInterestonLoans: boolean | null;
    accumGainsAvailSaleValue: boolean;
    accumGainsAvailSaleValueSpecified: boolean;
    accumGainsAvailSale: boolean | null;
    accumGainsCashFlowValue: boolean;
    accumGainsCashFlowValueSpecified: boolean;
    accumGainsCashFlow: boolean | null;
    agriculturalLoansValue: boolean;
    agriculturalLoansValueSpecified: boolean;
    agriculturalLoans: boolean | null;
    allBankruptcyWarnListValue: boolean;
    allBankruptcyWarnListValueSpecified: boolean;
    allBankruptcyWarnList: boolean | null;
    allOtherAssets: number[];
    allOtherAssetsSpecified: boolean;
    allOtherInvestmentsValue: boolean;
    allOtherInvestmentsValueSpecified: boolean;
    allOtherInvestments: boolean | null;
    allOtherInvestmtCcuValue: boolean;
    allOtherInvestmtCcuValueSpecified: boolean;
    allOtherInvestmtCcu: boolean | null;
    allOtherNonRealEstLoansValue: boolean;
    allOtherNonRealEstLoansValueSpecified: boolean;
    allOtherNonRealEstLoans: boolean | null;
    allOtherSharesValue: boolean;
    allOtherSharesValueSpecified: boolean;
    allOtherShares: boolean | null;
    allOtherUnsecLoansValue: boolean;
    allOtherUnsecLoansValueSpecified: boolean;
    allOtherUnsecLoans: boolean | null;
    allowanceLoanLeaseValue: boolean;
    allowanceLoanLeaseValueSpecified: boolean;
    allowanceLoanLease: boolean | null;
    apOtherLiabilitiesValue: boolean;
    apOtherLiabilitiesValueSpecified: boolean;
    apOtherLiabilities: boolean | null;
    appropNonConformInvstmValue: boolean;
    appropNonConformInvstmValueSpecified: boolean;
    appropNonConformInvstm: boolean | null;
    availforSaleSecuritiesValue: boolean;
    availforSaleSecuritiesValueSpecified: boolean;
    availforSaleSecurities: boolean | null;
    bankruptcy11WarnListValue: boolean;
    bankruptcy11WarnListValueSpecified: boolean;
    bankruptcy11WarnList: boolean | null;
    bankruptcy13WarnListValue: boolean;
    bankruptcy13WarnListValueSpecified: boolean;
    bankruptcy13WarnList: boolean | null;
    bankruptcy7WarnListValue: boolean;
    bankruptcy7WarnListValueSpecified: boolean;
    bankruptcy7WarnList: boolean | null;
    cashEquivalentsValue: boolean;
    cashEquivalentsValueSpecified: boolean;
    cashEquivalents: boolean | null;
    cashOnDepositCcuValue: boolean;
    cashOnDepositCcuValueSpecified: boolean;
    cashOnDepositCcu: boolean | null;
    cashOnDepositOtherFiValue: boolean;
    cashOnDepositOtherFiValueSpecified: boolean;
    cashOnDepositOtherFi: boolean | null;
    cashonHandValue: boolean;
    cashonHandValueSpecified: boolean;
    cashonHand: boolean | null;
    constructionLoansValue: boolean;
    constructionLoansValueSpecified: boolean;
    constructionLoans: boolean | null;
    depositsinBanksValue: boolean;
    depositsinBanksValueSpecified: boolean;
    depositsinBanks: boolean | null;
    dividendsonSharesValue: boolean;
    dividendsonSharesValueSpecified: boolean;
    dividendsonShares: boolean | null;
    dlrRsrvLoansOutsrcedLendValue: boolean;
    dlrRsrvLoansOutsrcedLendValueSpecified: boolean;
    dlrRsrvLoansOutsrcedLend: boolean | null;
    dlrRsrvLoansPointOfSaleValue: boolean;
    dlrRsrvLoansPointOfSaleValueSpecified: boolean;
    dlrRsrvLoansPointOfSale: boolean | null;
    drawsAgainstLinesofCreditValue: boolean;
    drawsAgainstLinesofCreditValueSpecified: boolean;
    drawsAgainstLinesofCredit: boolean | null;
    educationalPromoExpValue: boolean;
    educationalPromoExpValueSpecified: boolean;
    educationalPromoExp: boolean | null;
    employeeBenefitMemberSharesValue: boolean;
    employeeBenefitMemberSharesValueSpecified: boolean;
    employeeBenefitMemberShares: boolean | null;
    employeeBenefitNonMemberShrValue: boolean;
    employeeBenefitNonMemberShrValueSpecified: boolean;
    employeeBenefitNonMemberShr: boolean | null;
    employeeCompensationValue: boolean;
    employeeCompensationValueSpecified: boolean;
    employeeCompensation: boolean | null;
    feeIncomeValue: boolean;
    feeIncomeValueSpecified: boolean;
    feeIncome: boolean | null;
    field529PlanMemberDepositsValue: boolean;
    field529PlanMemberDepositsValueSpecified: boolean;
    field529PlanMemberDeposits: boolean | null;
    firstMortgOtherFixedValue: boolean;
    firstMortgOtherFixedValueSpecified: boolean;
    firstMortgOtherFixed: boolean | null;
    firstMortgageAdjustableValue: boolean;
    firstMortgageAdjustableValueSpecified: boolean;
    firstMortgageAdjustable: boolean | null;
    firstMortgageBalloonValue: boolean;
    firstMortgageBalloonValueSpecified: boolean;
    firstMortgageBalloon: boolean | null;
    firstMortgageFixedValue: boolean;
    firstMortgageFixedValueSpecified: boolean;
    firstMortgageFixed: boolean | null;
    firstMtgIntOnlyOptPaymentValue: boolean;
    firstMtgIntOnlyOptPaymentValueSpecified: boolean;
    firstMtgIntOnlyOptPayment: boolean | null;
    firstMtgResidentialConsLoansValue: boolean;
    firstMtgResidentialConsLoansValueSpecified: boolean;
    firstMtgResidentialConsLoans: boolean | null;
    foreclosedandRepoAutoValue: boolean;
    foreclosedandRepoAutoValueSpecified: boolean;
    foreclosedandRepoAuto: boolean | null;
    foreclosedandRepoOtherValue: boolean;
    foreclosedandRepoOtherValueSpecified: boolean;
    foreclosedandRepoOther: boolean | null;
    foreclosedandRepoRealEstValue: boolean;
    foreclosedandRepoRealEstValueSpecified: boolean;
    foreclosedandRepoRealEst: boolean | null;
    gainonDispositionValue: boolean;
    gainonDispositionValueSpecified: boolean;
    gainonDisposition: boolean | null;
    gainonInvestmentsValue: boolean;
    gainonInvestmentsValueSpecified: boolean;
    gainonInvestments: boolean | null;
    healthSavingsAccountsValue: boolean;
    healthSavingsAccountsValueSpecified: boolean;
    healthSavingsAccounts: boolean | null;
    heldToMatSecuritiesValue: boolean;
    heldToMatSecuritiesValueSpecified: boolean;
    heldToMatSecurities: boolean | null;
    incomefromInvestmentsValue: boolean;
    incomefromInvestmentsValueSpecified: boolean;
    incomefromInvestments: boolean | null;
    interestRefundedValue: boolean;
    interestRefundedValueSpecified: boolean;
    interestRefunded: boolean | null;
    interestonBorrowedValue: boolean;
    interestonBorrowedValueSpecified: boolean;
    interestonBorrowed: boolean | null;
    interestonDepositsValue: boolean;
    interestonDepositsValueSpecified: boolean;
    interestonDeposits: boolean | null;
    interestonLoansValue: boolean;
    interestonLoansValueSpecified: boolean;
    interestonLoans: boolean | null;
    iraKeoghAccountsValue: boolean;
    iraKeoghAccountsValueSpecified: boolean;
    iraKeoghAccounts: boolean | null;
    landandBuildingValue: boolean;
    landandBuildingValueSpecified: boolean;
    landandBuilding: boolean | null;
    leasesReceivableValue: boolean;
    leasesReceivableValueSpecified: boolean;
    leasesReceivable: boolean | null;
    lnsExclRealEstSoldInFullValue: boolean;
    lnsExclRealEstSoldInFullValueSpecified: boolean;
    lnsExclRealEstSoldInFull: boolean | null;
    loanServicingExpenseValue: boolean;
    loanServicingExpenseValueSpecified: boolean;
    loanServicingExpense: boolean | null;
    loansGrantedYtdValue: boolean;
    loansGrantedYtdValueSpecified: boolean;
    loansGrantedYtd: boolean | null;
    loansHeldforSaleValue: boolean;
    loansHeldforSaleValueSpecified: boolean;
    loansHeldforSale: boolean | null;
    loansOutstToCuOffValue: boolean;
    loansOutstToCuOffValueSpecified: boolean;
    loansOutstToCuOff: boolean | null;
    loansPurchasedOtherFiValue: boolean;
    loansPurchasedOtherFiValueSpecified: boolean;
    loansPurchasedOtherFi: boolean | null;
    loansToAndInvInNatPerCuValue: boolean;
    loansToAndInvInNatPerCuValueSpecified: boolean;
    loansToAndInvInNatPerCu: boolean | null;
    memberBusLoanExclAgrLoanValue: boolean;
    memberBusLoanExclAgrLoanValueSpecified: boolean;
    memberBusLoanExclAgrLoan: boolean | null;
    memberBusinessLoansValue: boolean;
    memberBusinessLoansValueSpecified: boolean;
    memberBusinessLoans: boolean | null;
    memberGovernmentDepositorsValue: boolean;
    memberGovernmentDepositorsValueSpecified: boolean;
    memberGovernmentDepositors: boolean | null;
    memberInsuranceValue: boolean;
    memberInsuranceValueSpecified: boolean;
    memberInsurance: boolean | null;
    membershipCapitalCcuValue: boolean;
    membershipCapitalCcuValueSpecified: boolean;
    membershipCapitalCcu: boolean | null;
    miscEquityValue: boolean;
    miscEquityValueSpecified: boolean;
    miscEquity: boolean | null;
    miscOperatingExpenseValue: boolean;
    miscOperatingExpenseValueSpecified: boolean;
    miscOperatingExpense: boolean | null;
    moneyMarketSharesValue: boolean;
    moneyMarketSharesValueSpecified: boolean;
    moneyMarketShares: boolean | null;
    ncuaShareInsuranceValue: boolean;
    ncuaShareInsuranceValueSpecified: boolean;
    ncuaShareInsurance: boolean | null;
    netIncomeValue: boolean;
    netIncomeValueSpecified: boolean;
    netIncome: boolean | null;
    newVehicleLoansValue: boolean;
    newVehicleLoansValueSpecified: boolean;
    newVehicleLoans: boolean | null;
    nonDollarDenominatedDepositValue: boolean;
    nonDollarDenominatedDepositValueSpecified: boolean;
    nonDollarDenominatedDeposit: boolean | null;
    nonMemberDepositsValue: boolean;
    nonMemberDepositsValueSpecified: boolean;
    nonMemberDeposits: boolean | null;
    nonmemberGovernmentDepositorValue: boolean;
    nonmemberGovernmentDepositorValueSpecified: boolean;
    nonmemberGovernmentDepositor: boolean | null;
    officeOccupancyExpValue: boolean;
    officeOccupancyExpValueSpecified: boolean;
    officeOccupancyExp: boolean | null;
    officeOperationsExpValue: boolean;
    officeOperationsExpValueSpecified: boolean;
    officeOperationsExp: boolean | null;
    operatingFeesValue: boolean;
    operatingFeesValueSpecified: boolean;
    operatingFees: boolean | null;
    otherComprIncomeValue: boolean;
    otherComprIncomeValueSpecified: boolean;
    otherComprIncome: boolean | null;
    otherFixedAssetsValue: boolean;
    otherFixedAssetsValueSpecified: boolean;
    otherFixedAssets: boolean | null;
    otherNonOperIncomeValue: boolean;
    otherNonOperIncomeValueSpecified: boolean;
    otherNonOperIncome: boolean | null;
    otherNotesValue: boolean;
    otherNotesValueSpecified: boolean;
    otherNotes: boolean | null;
    otherOperatingIncomeValue: boolean;
    otherOperatingIncomeValueSpecified: boolean;
    otherOperatingIncome: boolean | null;
    otherReClosedEndAdjValue: boolean;
    otherReClosedEndAdjValueSpecified: boolean;
    otherReClosedEndAdj: boolean | null;
    otherReClosedEndFixedValue: boolean;
    otherReClosedEndFixedValueSpecified: boolean;
    otherReClosedEndFixed: boolean | null;
    otherReOpenEndAdjValue: boolean;
    otherReOpenEndAdjValueSpecified: boolean;
    otherReOpenEndAdj: boolean | null;
    otherReOpenEndFixedValue: boolean;
    otherReOpenEndFixedValueSpecified: boolean;
    otherReOpenEndFixed: boolean | null;
    otherRealEstateValue: boolean;
    otherRealEstateValueSpecified: boolean;
    otherRealEstate: boolean | null;
    otherReservesValue: boolean;
    otherReservesValueSpecified: boolean;
    otherReserves: boolean | null;
    otherUninsdNonmemberSharesValue: boolean;
    otherUninsdNonmemberSharesValueSpecified: boolean;
    otherUninsdNonmemberShares: boolean | null;
    otherUninsuredMemberSharesValue: boolean;
    otherUninsuredMemberSharesValueSpecified: boolean;
    otherUninsuredMemberShares: boolean | null;
    paidInCapitalCcuValue: boolean;
    paidInCapitalCcuValueSpecified: boolean;
    paidInCapitalCcu: boolean | null;
    profOutsideServicesValue: boolean;
    profOutsideServicesValueSpecified: boolean;
    profOutsideServices: boolean | null;
    provisionForLlLossesValue: boolean;
    provisionForLlLossesValueSpecified: boolean;
    provisionForLlLosses: boolean | null;
    purchBusLoansMembersValue: boolean;
    purchBusLoansMembersValueSpecified: boolean;
    purchBusLoansMembers: boolean | null;
    purchBusLoansNonmbrsValue: boolean;
    purchBusLoansNonmbrsValueSpecified: boolean;
    purchBusLoansNonmbrs: boolean | null;
    regularReservesValue: boolean;
    regularReservesValueSpecified: boolean;
    regularReserves: boolean | null;
    regularSharesValue: boolean;
    regularSharesValueSpecified: boolean;
    regularShares: boolean | null;
    reverseRepurchAgreemValue: boolean;
    reverseRepurchAgreemValueSpecified: boolean;
    reverseRepurchAgreem: boolean | null;
    shareCertificatesValue: boolean;
    shareCertificatesValueSpecified: boolean;
    shareCertificates: boolean | null;
    shareDraftsValue: boolean;
    shareDraftsValueSpecified: boolean;
    shareDrafts: boolean | null;
    subordinatedDebtValue: boolean;
    subordinatedDebtValueSpecified: boolean;
    subordinatedDebt: boolean | null;
    tAggrCashOutlayInCuso: number[];
    tAggrCashOutlayInCusoSpecified: boolean;
    tAmountLoanedToCuso: number[];
    tAmountLoanedToCusoSpecified: boolean;
    tNameOfCuso: number[];
    tNameOfCusoSpecified: boolean;
    tValueOfInvInCuso: number[];
    tValueOfInvInCusoSpecified: boolean;
    totalAllOtherLoansValue: boolean;
    totalAllOtherLoansValueSpecified: boolean;
    totalAllOtherLoans: boolean | null;
    tradingProfitsValue: boolean;
    tradingProfitsValueSpecified: boolean;
    tradingProfits: boolean | null;
    tradingSecuritiesValue: boolean;
    tradingSecuritiesValueSpecified: boolean;
    tradingSecurities: boolean | null;
    transfertoRegReserveValue: boolean;
    transfertoRegReserveValueSpecified: boolean;
    transfertoRegReserve: boolean | null;
    travelandConfExpenseValue: boolean;
    travelandConfExpenseValueSpecified: boolean;
    travelandConfExpense: boolean | null;
    undividedEarningsValue: boolean;
    undividedEarningsValueSpecified: boolean;
    undividedEarnings: boolean | null;
    uninsSecondaryCapitalValue: boolean;
    uninsSecondaryCapitalValueSpecified: boolean;
    uninsSecondaryCapital: boolean | null;
    unsecuredBusinessLoansValue: boolean;
    unsecuredBusinessLoansValueSpecified: boolean;
    unsecuredBusinessLoans: boolean | null;
    unsecuredCcLoansValue: boolean;
    unsecuredCcLoansValueSpecified: boolean;
    unsecuredCcLoans: boolean | null;
    unsecuredCcLoansGlValue: boolean;
    unsecuredCcLoansGlValueSpecified: boolean;
    unsecuredCcLoansGl: boolean | null;
    usedVehicleLoansValue: boolean;
    usedVehicleLoansValueSpecified: boolean;
    usedVehicleLoans: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}