import { VersionType } from "./versionType";

export interface OnlineCardFields {
    activateOnFirstPinTran: boolean | null;
    aggregateLimitingCardTypes: boolean | null;
    alternateDraftAccount: boolean | null;
    alternateFundingAccount: boolean | null;
    alwaysPosttoFundingList: boolean | null;
    atmAmountLimitFields: boolean | null;
    atmAmountUsedFields: boolean | null;
    atmCountLimitFields: boolean | null;
    atmCountUsedFields: boolean | null;
    atmDepAmtLimitPerCard: boolean | null;
    atmDepositCountLimiting: boolean | null;
    billPaymentCategorization: boolean | null;
    bin: boolean | null;
    binType: boolean | null;
    bpAmountLimitFields: boolean | null;
    bpAmountUsedFields: boolean | null;
    bpCountLimitFields: boolean | null;
    bpCountUsedFields: boolean | null;
    cardLimitingOption: boolean | null;
    cardNumberLength: boolean | null;
    cardNumberinTranHistory: boolean | null;
    cardType: boolean | null;
    chargeMasterCardCcaFee: boolean | null;
    chargeMasterCardIcaFee: boolean | null;
    checkActivationDate: boolean | null;
    checkOnlineMsgExpDate: boolean | null;
    chgVisaMultiCrrncyIsaFee: boolean | null;
    chgVisasGlCrrncyIsaFee: boolean | null;
    creditFacility: boolean | null;
    deactivatePreviousCard: boolean | null;
    deactvPrevCardExclWarnCd: boolean | null;
    fundingAccount: boolean | null;
    idLogicOption: boolean | null;
    limitCustomCondition: number[];
    limitDescription: number[];
    limitMcc: number[];
    limitSourceCodes: number[];
    limitTransactionCodes: number[];
    limitTransactionSubTypes: number[];
    masterCardCcaRate: boolean | null;
    masterCardIcaRate: boolean | null;
    matchOnlineMsgExpDate: boolean | null;
    maxAfdApprForGreaterAmt: boolean | null;
    mccInTranHistory: boolean | null;
    odToleranceAvailBalList: boolean | null;
    odTransferAvailBalList: boolean | null;
    overdrawToleranceApprList: boolean | null;
    overdrawTransferApprList: boolean | null;
    pctOverLocAvailBalList: boolean | null;
    posAmountLimitFields: boolean | null;
    posAmountUsedFields: boolean | null;
    posCountLimitFields: boolean | null;
    posCountUsedFields: boolean | null;
    posttoAltDraftList: boolean | null;
    posttoAltFundingList: boolean | null;
    serviceAccessCode: boolean | null;
    sigAmountLimitFields: boolean | null;
    sigAmountUsedFields: boolean | null;
    sigCountLimitFields: boolean | null;
    sigCountUsedFields: boolean | null;
    signatureDescription: boolean | null;
    suffixPosition: boolean | null;
    uniqueCardNumber: boolean | null;
    useAccessEnableFlags: boolean | null;
    validateCheckDigit: boolean | null;
    visaMultiCurrencyIsaRate: boolean | null;
    visaSingleCurrencyIsaRate: boolean | null;
    version1: VersionType;
    merchantReturnAuths: boolean | null;
    version2: VersionType;
}