import { BitMap } from "./bitMap";
import { OnlineFeeRelationFeeAmount_2 } from "./onlineFeeRelationFeeAmount_2";
import { OnlineFeeRelationRelCodes_2 } from "./onlineFeeRelationRelCodes_2";
import { OnlineFeeRelationWaiveCount_2 } from "./onlineFeeRelationWaiveCount_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineFee_2 {
    accountTypes: BitMap;
    acquirerNetworkIds: string;
    cardAcceptorName: string;
    cardTypes: BitMap;
    coOpTransactionValue: number;
    coOpTransactionValueSpecified: boolean;
    coOpTransaction: number | null;
    customCriterionValue: number;
    customCriterionValueSpecified: boolean;
    customCriterion: number | null;
    excludeServiceCodes: BitMap;
    feeCountLevelValue: number;
    feeCountLevelValueSpecified: boolean;
    feeCountLevel: number | null;
    feeCountNumberValue: number;
    feeCountNumberValueSpecified: boolean;
    feeCountNumber: number | null;
    feeCountTotalsValue: number;
    feeCountTotalsValueSpecified: boolean;
    feeCountTotals: number | null;
    feeDescription: string;
    feeGlCodeValue: number;
    feeGlCodeValueSpecified: boolean;
    feeGlCode: number | null;
    feePostingOptionValue: number;
    feePostingOptionValueSpecified: boolean;
    feePostingOption: number | null;
    includeServiceCodes: BitMap;
    relationFeeAmount: OnlineFeeRelationFeeAmount_2[];
    relationFeeAmountSpecified: boolean;
    relationRelCodes: OnlineFeeRelationRelCodes_2[];
    relationRelCodesSpecified: boolean;
    relationWaiveCount: OnlineFeeRelationWaiveCount_2[];
    relationWaiveCountSpecified: boolean;
    ruleDescription: string;
    ruleOrdinalValue: number;
    ruleOrdinalValueSpecified: boolean;
    ruleOrdinal: number | null;
    rulePositionValue: number;
    rulePositionValueSpecified: boolean;
    rulePosition: number | null;
    shareLoanValue: number;
    shareLoanValueSpecified: boolean;
    shareLoan: number | null;
    shareLoanTypes: BitMap;
    terminalTableValue: number;
    terminalTableValueSpecified: boolean;
    terminalTable: number | null;
    transactionCodes: string;
    transactionTypes: string;
    warningCodeExclList: BitMap;
    warningCodeInclList: BitMap;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}