import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineSbAddOnFields {
    availBalApprExclListValue: boolean;
    availBalApprExclListValueSpecified: boolean;
    availBalApprExclList: boolean | null;
    availBalPostExclListValue: boolean;
    availBalPostExclListValueSpecified: boolean;
    availBalPostExclList: boolean | null;
    cardAcceptorLocationValue: boolean;
    cardAcceptorLocationValueSpecified: boolean;
    cardAcceptorLocation: boolean | null;
    cardAcceptorNameValue: boolean;
    cardAcceptorNameValueSpecified: boolean;
    cardAcceptorName: boolean | null;
    checkDepositHoldsValue: boolean;
    checkDepositHoldsValueSpecified: boolean;
    checkDepositHolds: boolean | null;
    customCriterionValue: boolean;
    customCriterionValueSpecified: boolean;
    customCriterion: boolean | null;
    depRestrictWarnListValue: boolean;
    depRestrictWarnListValueSpecified: boolean;
    depRestrictWarnList: boolean | null;
    glCodeValue: boolean;
    glCodeValueSpecified: boolean;
    glCode: boolean | null;
    lnExcludeTypeListValue: boolean;
    lnExcludeTypeListValueSpecified: boolean;
    lnExcludeTypeList: boolean | null;
    nonIrsCertTranAccessValue: boolean;
    nonIrsCertTranAccessValueSpecified: boolean;
    nonIrsCertTranAccess: boolean | null;
    nonIrsClubTranAccessValue: boolean;
    nonIrsClubTranAccessValueSpecified: boolean;
    nonIrsClubTranAccess: boolean | null;
    posConditionCodesValue: boolean;
    posConditionCodesValueSpecified: boolean;
    posConditionCodes: boolean | null;
    regDLimitingValue: boolean;
    regDLimitingValueSpecified: boolean;
    regDLimiting: boolean | null;
    restrictWarnListValue: boolean;
    restrictWarnListValueSpecified: boolean;
    restrictWarnList: boolean | null;
    ruleDescriptionValue: boolean;
    ruleDescriptionValueSpecified: boolean;
    ruleDescription: boolean | null;
    ruleOrdinalValue: boolean;
    ruleOrdinalValueSpecified: boolean;
    ruleOrdinal: boolean | null;
    rulePositionValue: boolean;
    rulePositionValueSpecified: boolean;
    rulePosition: boolean | null;
    svExcludeTypeListValue: boolean;
    svExcludeTypeListValueSpecified: boolean;
    svExcludeTypeList: boolean | null;
    transactionHistoryPrefixValue: boolean;
    transactionHistoryPrefixValueSpecified: boolean;
    transactionHistoryPrefix: boolean | null;
    transactionSourceCodeValue: boolean;
    transactionSourceCodeValueSpecified: boolean;
    transactionSourceCode: boolean | null;
    transactionSubTypeValue: boolean;
    transactionSubTypeValueSpecified: boolean;
    transactionSubType: boolean | null;
    wdRestrictWarnListValue: boolean;
    wdRestrictWarnListValueSpecified: boolean;
    wdRestrictWarnList: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}