import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineMainFields {
    acceptLoanThresholdPaymentValue: boolean;
    acceptLoanThresholdPaymentValueSpecified: boolean;
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmtValue: boolean;
    acceptUnappliedPartialPmtValueSpecified: boolean;
    acceptUnappliedPartialPmt: boolean | null;
    appendAtmTerminalIdValue: boolean;
    appendAtmTerminalIdValueSpecified: boolean;
    appendAtmTerminalId: boolean | null;
    atmAvailBalApprExclListValue: boolean;
    atmAvailBalApprExclListValueSpecified: boolean;
    atmAvailBalApprExclList: boolean | null;
    atmAvailBalPostExclListValue: boolean;
    atmAvailBalPostExclListValueSpecified: boolean;
    atmAvailBalPostExclList: boolean | null;
    atmFeeDescriptionValue: boolean;
    atmFeeDescriptionValueSpecified: boolean;
    atmFeeDescription: boolean | null;
    atmWarningCodeListValue: boolean;
    atmWarningCodeListValueSpecified: boolean;
    atmWarningCodeList: boolean | null;
    avsActionValue: boolean;
    avsActionValueSpecified: boolean;
    avsAction: boolean | null;
    avsMethodValue: boolean;
    avsMethodValueSpecified: boolean;
    avsMethod: boolean | null;
    billPayFeeDescriptionValue: boolean;
    billPayFeeDescriptionValueSpecified: boolean;
    billPayFeeDescription: boolean | null;
    bpAvailBalApprExclListValue: boolean;
    bpAvailBalApprExclListValueSpecified: boolean;
    bpAvailBalApprExclList: boolean | null;
    bpAvailBalPostExclListValue: boolean;
    bpAvailBalPostExclListValueSpecified: boolean;
    bpAvailBalPostExclList: boolean | null;
    bpWarningCodeListValue: boolean;
    bpWarningCodeListValueSpecified: boolean;
    bpWarningCodeList: boolean | null;
    cardinHistoryDigitCountValue: boolean;
    cardinHistoryDigitCountValueSpecified: boolean;
    cardinHistoryDigitCount: boolean | null;
    cashMccTypesValue: boolean;
    cashMccTypesValueSpecified: boolean;
    cashMccTypes: boolean | null;
    chargePartialCapFeeValue: boolean;
    chargePartialCapFeeValueSpecified: boolean;
    chargePartialCapFee: boolean | null;
    checkWarningCodeListValue: boolean;
    checkWarningCodeListValueSpecified: boolean;
    checkWarningCodeList: boolean | null;
    chng1GasAuthHoldAmountValue: boolean;
    chng1GasAuthHoldAmountValueSpecified: boolean;
    chng1GasAuthHoldAmount: boolean | null;
    clearingGlCodeValue: boolean;
    clearingGlCodeValueSpecified: boolean;
    clearingGlCode: boolean | null;
    courtesyNoticesValue: boolean;
    courtesyNoticesValueSpecified: boolean;
    courtesyNotices: boolean | null;
    courtesyPayCommentCodeValue: boolean;
    courtesyPayCommentCodeValueSpecified: boolean;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescriptionValue: boolean;
    courtesyPayFeeDescriptionValueSpecified: boolean;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCodeValue: boolean;
    courtesyPayFeeGlCodeValueSpecified: boolean;
    courtesyPayFeeGlCode: boolean | null;
    createExceptionItemsValue: boolean;
    createExceptionItemsValueSpecified: boolean;
    createExceptionItems: boolean | null;
    creditCardFeeDescriptionValue: boolean;
    creditCardFeeDescriptionValueSpecified: boolean;
    creditCardFeeDescription: boolean | null;
    cuAtmCheckDepHoldDaysValue: boolean;
    cuAtmCheckDepHoldDaysValueSpecified: boolean;
    cuAtmCheckDepHoldDays: boolean | null;
    cuAtmEnvDepHoldDaysValue: boolean;
    cuAtmEnvDepHoldDaysValueSpecified: boolean;
    cuAtmEnvDepHoldDays: boolean | null;
    cuAtmUseRegCcPolicyValue: boolean;
    cuAtmUseRegCcPolicyValueSpecified: boolean;
    cuAtmUseRegCcPolicy: boolean | null;
    debitCardFeeDescriptionValue: boolean;
    debitCardFeeDescriptionValueSpecified: boolean;
    debitCardFeeDescription: boolean | null;
    depWarningCodeListValue: boolean;
    depWarningCodeListValueSpecified: boolean;
    depWarningCodeList: boolean | null;
    dqGraceDaysForAddonValue: boolean;
    dqGraceDaysForAddonValueSpecified: boolean;
    dqGraceDaysForAddon: boolean | null;
    dqGraceDaysForWdValue: boolean;
    dqGraceDaysForWdValueSpecified: boolean;
    dqGraceDaysForWd: boolean | null;
    dqWarningCodeListValue: boolean;
    dqWarningCodeListValueSpecified: boolean;
    dqWarningCodeList: boolean | null;
    duplicateKeyPurgeTimeValue: boolean;
    duplicateKeyPurgeTimeValueSpecified: boolean;
    duplicateKeyPurgeTime: boolean | null;
    duplicateKeyRetentionDaysValue: boolean;
    duplicateKeyRetentionDaysValueSpecified: boolean;
    duplicateKeyRetentionDays: boolean | null;
    envWarningCodeListValue: boolean;
    envWarningCodeListValueSpecified: boolean;
    envWarningCodeList: boolean | null;
    feeTypeToCapValue: boolean;
    feeTypeToCapValueSpecified: boolean;
    feeTypeToCap: boolean | null;
    frgnAtmCheckDepHoldDaysValue: boolean;
    frgnAtmCheckDepHoldDaysValueSpecified: boolean;
    frgnAtmCheckDepHoldDays: boolean | null;
    frgnAtmEnvDepHoldDaysValue: boolean;
    frgnAtmEnvDepHoldDaysValueSpecified: boolean;
    frgnAtmEnvDepHoldDays: boolean | null;
    frgnAtmUseRegCcPolicyValue: boolean;
    frgnAtmUseRegCcPolicyValueSpecified: boolean;
    frgnAtmUseRegCcPolicy: boolean | null;
    glCategoryValue: boolean;
    glCategoryValueSpecified: boolean;
    glCategory: boolean | null;
    graceAmountforCashPaymentsValue: boolean;
    graceAmountforCashPaymentsValueSpecified: boolean;
    graceAmountforCashPayments: boolean | null;
    groupMccHoldTime: number[];
    groupMccHoldTimeSpecified: boolean;
    groupMccHoldUnits: number[];
    groupMccHoldUnitsSpecified: boolean;
    groupMccSourceCodes: number[];
    groupMccSourceCodesSpecified: boolean;
    holdWarningCodeListValue: boolean;
    holdWarningCodeListValueSpecified: boolean;
    holdWarningCodeList: boolean | null;
    includeOnlineFeesinApprValue: boolean;
    includeOnlineFeesinApprValueSpecified: boolean;
    includeOnlineFeesinAppr: boolean | null;
    institutionNameValue: boolean;
    institutionNameValueSpecified: boolean;
    institutionName: boolean | null;
    masterCardCcaFeeGlCodeValue: boolean;
    masterCardCcaFeeGlCodeValueSpecified: boolean;
    masterCardCcaFeeGlCode: boolean | null;
    masterCardIcaFeeGlCodeValue: boolean;
    masterCardIcaFeeGlCodeValueSpecified: boolean;
    masterCardIcaFeeGlCode: boolean | null;
    maxInvalidPinAttemptsValue: boolean;
    maxInvalidPinAttemptsValueSpecified: boolean;
    maxInvalidPinAttempts: boolean | null;
    maximumAddonOverLocValue: boolean;
    maximumAddonOverLocValueSpecified: boolean;
    maximumAddonOverLoc: boolean | null;
    maximumWdBelowAvailableValue: boolean;
    maximumWdBelowAvailableValueSpecified: boolean;
    maximumWdBelowAvailable: boolean | null;
    mccTypes: number[];
    mccTypesSpecified: boolean;
    minimumLineofCreditAddonValue: boolean;
    minimumLineofCreditAddonValueSpecified: boolean;
    minimumLineofCreditAddon: boolean | null;
    noticesPrinterTypeValue: boolean;
    noticesPrinterTypeValueSpecified: boolean;
    noticesPrinterType: boolean | null;
    nsfFeeDescIfNotPaidValue: boolean;
    nsfFeeDescIfNotPaidValueSpecified: boolean;
    nsfFeeDescIfNotPaid: boolean | null;
    nsfFeeDescIfPaidValue: boolean;
    nsfFeeDescIfPaidValueSpecified: boolean;
    nsfFeeDescIfPaid: boolean | null;
    nsfFeeForUncollectedFundsValue: boolean;
    nsfFeeForUncollectedFundsValueSpecified: boolean;
    nsfFeeForUncollectedFunds: boolean | null;
    nsfFeeGlCodeValue: boolean;
    nsfFeeGlCodeValueSpecified: boolean;
    nsfFeeGlCode: boolean | null;
    nsfNoticesValue: boolean;
    nsfNoticesValueSpecified: boolean;
    nsfNotices: boolean | null;
    odTransferFeeCalcOptionValue: boolean;
    odTransferFeeCalcOptionValueSpecified: boolean;
    odTransferFeeCalcOption: boolean | null;
    odtAuthFeeOvrSrcCodesValue: boolean;
    odtAuthFeeOvrSrcCodesValueSpecified: boolean;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodesValue: boolean;
    odtAuthFeeRecurSrcCodesValueSpecified: boolean;
    odtAuthFeeRecurSrcCodes: boolean | null;
    onlyLoanTransferNoticesValue: boolean;
    onlyLoanTransferNoticesValueSpecified: boolean;
    onlyLoanTransferNotices: boolean | null;
    overdrawAddonDqGraceDaysValue: boolean;
    overdrawAddonDqGraceDaysValueSpecified: boolean;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrementValue: boolean;
    overdrawAddonIncrementValueSpecified: boolean;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLocValue: boolean;
    overdrawAddonMaxOverLocValueSpecified: boolean;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLocValue: boolean;
    overdrawAddonPctOverLocValueSpecified: boolean;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOptionValue: boolean;
    overdrawFeeOptionValueSpecified: boolean;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverrideValue: boolean;
    overdrawIncrementOverrideValueSpecified: boolean;
    overdrawIncrementOverride: boolean | null;
    overdrawNoticesfor2NdAcctValue: boolean;
    overdrawNoticesfor2NdAcctValueSpecified: boolean;
    overdrawNoticesfor2NdAcct: boolean | null;
    overdrawOptionValue: boolean;
    overdrawOptionValueSpecified: boolean;
    overdrawOption: boolean | null;
    overdrawRegDLimitingValue: boolean;
    overdrawRegDLimitingValueSpecified: boolean;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOptionValue: boolean;
    overdrawTierOptionValueSpecified: boolean;
    overdrawTierOption: boolean | null;
    overdrawTransferFeeGlCodeValue: boolean;
    overdrawTransferFeeGlCodeValueSpecified: boolean;
    overdrawTransferFeeGlCode: boolean | null;
    overdrawTransferNoticesValue: boolean;
    overdrawTransferNoticesValueSpecified: boolean;
    overdrawTransferNotices: boolean | null;
    overdrawWithdrawalIncrementValue: boolean;
    overdrawWithdrawalIncrementValueSpecified: boolean;
    overdrawWithdrawalIncrement: boolean | null;
    ovlFeeDescIfNotPaidValue: boolean;
    ovlFeeDescIfNotPaidValueSpecified: boolean;
    ovlFeeDescIfNotPaid: boolean | null;
    ovlFeeDescIfPaidValue: boolean;
    ovlFeeDescIfPaidValueSpecified: boolean;
    ovlFeeDescIfPaid: boolean | null;
    ovlFeeForUncollectedFundsValue: boolean;
    ovlFeeForUncollectedFundsValueSpecified: boolean;
    ovlFeeForUncollectedFunds: boolean | null;
    ovlFeeGlCodeValue: boolean;
    ovlFeeGlCodeValueSpecified: boolean;
    ovlFeeGlCode: boolean | null;
    ovlNoticesValue: boolean;
    ovlNoticesValueSpecified: boolean;
    ovlNotices: boolean | null;
    percentOverLineofCreditValue: boolean;
    percentOverLineofCreditValueSpecified: boolean;
    percentOverLineofCredit: boolean | null;
    pinPreAuthGasHoldTimeValue: boolean;
    pinPreAuthGasHoldTimeValueSpecified: boolean;
    pinPreAuthGasHoldTime: boolean | null;
    pinPreAuthGasHoldUnitsValue: boolean;
    pinPreAuthGasHoldUnitsValueSpecified: boolean;
    pinPreAuthGasHoldUnits: boolean | null;
    posAvailBalAuthExclListValue: boolean;
    posAvailBalAuthExclListValueSpecified: boolean;
    posAvailBalAuthExclList: boolean | null;
    posAvailBalPostExclListValue: boolean;
    posAvailBalPostExclListValueSpecified: boolean;
    posAvailBalPostExclList: boolean | null;
    posFeeDescriptionValue: boolean;
    posFeeDescriptionValueSpecified: boolean;
    posFeeDescription: boolean | null;
    posWarningCodeListValue: boolean;
    posWarningCodeListValueSpecified: boolean;
    posWarningCodeList: boolean | null;
    postAtmBalanceInquiriesValue: boolean;
    postAtmBalanceInquiriesValueSpecified: boolean;
    postAtmBalanceInquiries: boolean | null;
    postAtmStatementsValue: boolean;
    postAtmStatementsValueSpecified: boolean;
    postAtmStatements: boolean | null;
    preAuthExpHoldMatchDaysValue: boolean;
    preAuthExpHoldMatchDaysValueSpecified: boolean;
    preAuthExpHoldMatchDays: boolean | null;
    preAuthFmHistoryOptionValue: boolean;
    preAuthFmHistoryOptionValueSpecified: boolean;
    preAuthFmHistoryOption: boolean | null;
    preAuthHoldTimeValue: boolean;
    preAuthHoldTimeValueSpecified: boolean;
    preAuthHoldTime: boolean | null;
    preAuthHoldUnitsValue: boolean;
    preAuthHoldUnitsValueSpecified: boolean;
    preAuthHoldUnits: boolean | null;
    preAuthMatchVarianceValue: boolean;
    preAuthMatchVarianceValueSpecified: boolean;
    preAuthMatchVariance: boolean | null;
    preAuthMaxHoldDaysValue: boolean;
    preAuthMaxHoldDaysValueSpecified: boolean;
    preAuthMaxHoldDays: boolean | null;
    preAuthTeHoldTimeValue: boolean;
    preAuthTeHoldTimeValueSpecified: boolean;
    preAuthTeHoldTime: boolean | null;
    preAuthTeHoldUnitsValue: boolean;
    preAuthTeHoldUnitsValueSpecified: boolean;
    preAuthTeHoldUnits: boolean | null;
    prependRegECommentsValue: boolean;
    prependRegECommentsValueSpecified: boolean;
    prependRegEComments: boolean | null;
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee1Specified: boolean;
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee2Specified: boolean;
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee3Specified: boolean;
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee4Specified: boolean;
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee5Specified: boolean;
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayFee6Specified: boolean;
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier1Specified: boolean;
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier2Specified: boolean;
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier3Specified: boolean;
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier4Specified: boolean;
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier5Specified: boolean;
    relAltCourtesyPayTier6: number[];
    relAltCourtesyPayTier6Specified: boolean;
    relCodeList: number[];
    relCodeListSpecified: boolean;
    relCourtesyPayFee1: number[];
    relCourtesyPayFee1Specified: boolean;
    relCourtesyPayFee2: number[];
    relCourtesyPayFee2Specified: boolean;
    relCourtesyPayFee3: number[];
    relCourtesyPayFee3Specified: boolean;
    relCourtesyPayFee4: number[];
    relCourtesyPayFee4Specified: boolean;
    relCourtesyPayFee5: number[];
    relCourtesyPayFee5Specified: boolean;
    relCourtesyPayFee6: number[];
    relCourtesyPayFee6Specified: boolean;
    relCourtesyPayTier1: number[];
    relCourtesyPayTier1Specified: boolean;
    relCourtesyPayTier2: number[];
    relCourtesyPayTier2Specified: boolean;
    relCourtesyPayTier3: number[];
    relCourtesyPayTier3Specified: boolean;
    relCourtesyPayTier4: number[];
    relCourtesyPayTier4Specified: boolean;
    relCourtesyPayTier5: number[];
    relCourtesyPayTier5Specified: boolean;
    relCourtesyPayTier6: number[];
    relCourtesyPayTier6Specified: boolean;
    relNsfFee: number[];
    relNsfFeeSpecified: boolean;
    relOverdrawAddonXfrFee: number[];
    relOverdrawAddonXfrFeeSpecified: boolean;
    relOverdrawComboXfrFee: number[];
    relOverdrawComboXfrFeeSpecified: boolean;
    relOverdrawWdXfrFee: number[];
    relOverdrawWdXfrFeeSpecified: boolean;
    relOvlFee: number[];
    relOvlFeeSpecified: boolean;
    reportTitleValue: boolean;
    reportTitleValueSpecified: boolean;
    reportTitle: boolean | null;
    sigAvailBalAuthExclListValue: boolean;
    sigAvailBalAuthExclListValueSpecified: boolean;
    sigAvailBalAuthExclList: boolean | null;
    sigAvailBalPostExclListValue: boolean;
    sigAvailBalPostExclListValueSpecified: boolean;
    sigAvailBalPostExclList: boolean | null;
    sigPreAuthGasHoldTimeValue: boolean;
    sigPreAuthGasHoldTimeValueSpecified: boolean;
    sigPreAuthGasHoldTime: boolean | null;
    sigPreAuthGasHoldUnitsValue: boolean;
    sigPreAuthGasHoldUnitsValueSpecified: boolean;
    sigPreAuthGasHoldUnits: boolean | null;
    sigWarningCodeListValue: boolean;
    sigWarningCodeListValueSpecified: boolean;
    sigWarningCodeList: boolean | null;
    useFeeStatusfromAuthValue: boolean;
    useFeeStatusfromAuthValueSpecified: boolean;
    useFeeStatusfromAuth: boolean | null;
    useLowQualMatchFeeStatusValue: boolean;
    useLowQualMatchFeeStatusValueSpecified: boolean;
    useLowQualMatchFeeStatus: boolean | null;
    useNetworkPreAuthHoldTimeValue: boolean;
    useNetworkPreAuthHoldTimeValueSpecified: boolean;
    useNetworkPreAuthHoldTime: boolean | null;
    usePostExclListonFinReqValue: boolean;
    usePostExclListonFinReqValueSpecified: boolean;
    usePostExclListonFinReq: boolean | null;
    visaMultiCrrncyIsaFeeGlValue: boolean;
    visaMultiCrrncyIsaFeeGlValueSpecified: boolean;
    visaMultiCrrncyIsaFeeGl: boolean | null;
    visaSglCrrncyIsaFeeGlValue: boolean;
    visaSglCrrncyIsaFeeGlValueSpecified: boolean;
    visaSglCrrncyIsaFeeGl: boolean | null;
    waiveFeeforAuthAdviceValue: boolean;
    waiveFeeforAuthAdviceValueSpecified: boolean;
    waiveFeeforAuthAdvice: boolean | null;
    waiveFeeonNoHoldMatchValue: boolean;
    waiveFeeonNoHoldMatchValueSpecified: boolean;
    waiveFeeonNoHoldMatch: boolean | null;
    waiveFeeonNoHoldRecurValue: boolean;
    waiveFeeonNoHoldRecurValueSpecified: boolean;
    waiveFeeonNoHoldRecur: boolean | null;
    wdBelowAvailableOptionValue: boolean;
    wdBelowAvailableOptionValueSpecified: boolean;
    wdBelowAvailableOption: boolean | null;
    wdWarningCodeListValue: boolean;
    wdWarningCodeListValueSpecified: boolean;
    wdWarningCodeList: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}