import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineCardFields {
    activateOnFirstPinTranValue: boolean;
    activateOnFirstPinTranValueSpecified: boolean;
    activateOnFirstPinTran: boolean | null;
    aggregateLimitingCardTypesValue: boolean;
    aggregateLimitingCardTypesValueSpecified: boolean;
    aggregateLimitingCardTypes: boolean | null;
    alternateDraftAccountValue: boolean;
    alternateDraftAccountValueSpecified: boolean;
    alternateDraftAccount: boolean | null;
    alternateFundingAccountValue: boolean;
    alternateFundingAccountValueSpecified: boolean;
    alternateFundingAccount: boolean | null;
    alwaysPosttoFundingListValue: boolean;
    alwaysPosttoFundingListValueSpecified: boolean;
    alwaysPosttoFundingList: boolean | null;
    atmAmountLimitFieldsValue: boolean;
    atmAmountLimitFieldsValueSpecified: boolean;
    atmAmountLimitFields: boolean | null;
    atmAmountUsedFieldsValue: boolean;
    atmAmountUsedFieldsValueSpecified: boolean;
    atmAmountUsedFields: boolean | null;
    atmCountLimitFieldsValue: boolean;
    atmCountLimitFieldsValueSpecified: boolean;
    atmCountLimitFields: boolean | null;
    atmCountUsedFieldsValue: boolean;
    atmCountUsedFieldsValueSpecified: boolean;
    atmCountUsedFields: boolean | null;
    atmDepAmtLimitPerCardValue: boolean;
    atmDepAmtLimitPerCardValueSpecified: boolean;
    atmDepAmtLimitPerCard: boolean | null;
    atmDepositCountLimitingValue: boolean;
    atmDepositCountLimitingValueSpecified: boolean;
    atmDepositCountLimiting: boolean | null;
    billPaymentCategorizationValue: boolean;
    billPaymentCategorizationValueSpecified: boolean;
    billPaymentCategorization: boolean | null;
    binValue: boolean;
    binValueSpecified: boolean;
    bin: boolean | null;
    binTypeValue: boolean;
    binTypeValueSpecified: boolean;
    binType: boolean | null;
    bpAmountLimitFieldsValue: boolean;
    bpAmountLimitFieldsValueSpecified: boolean;
    bpAmountLimitFields: boolean | null;
    bpAmountUsedFieldsValue: boolean;
    bpAmountUsedFieldsValueSpecified: boolean;
    bpAmountUsedFields: boolean | null;
    bpCountLimitFieldsValue: boolean;
    bpCountLimitFieldsValueSpecified: boolean;
    bpCountLimitFields: boolean | null;
    bpCountUsedFieldsValue: boolean;
    bpCountUsedFieldsValueSpecified: boolean;
    bpCountUsedFields: boolean | null;
    cardLimitingOptionValue: boolean;
    cardLimitingOptionValueSpecified: boolean;
    cardLimitingOption: boolean | null;
    cardNumberLengthValue: boolean;
    cardNumberLengthValueSpecified: boolean;
    cardNumberLength: boolean | null;
    cardNumberinTranHistoryValue: boolean;
    cardNumberinTranHistoryValueSpecified: boolean;
    cardNumberinTranHistory: boolean | null;
    cardTypeValue: boolean;
    cardTypeValueSpecified: boolean;
    cardType: boolean | null;
    chargeMasterCardCcaFeeValue: boolean;
    chargeMasterCardCcaFeeValueSpecified: boolean;
    chargeMasterCardCcaFee: boolean | null;
    chargeMasterCardIcaFeeValue: boolean;
    chargeMasterCardIcaFeeValueSpecified: boolean;
    chargeMasterCardIcaFee: boolean | null;
    checkActivationDateValue: boolean;
    checkActivationDateValueSpecified: boolean;
    checkActivationDate: boolean | null;
    checkOnlineMsgExpDateValue: boolean;
    checkOnlineMsgExpDateValueSpecified: boolean;
    checkOnlineMsgExpDate: boolean | null;
    chgVisaMultiCrrncyIsaFeeValue: boolean;
    chgVisaMultiCrrncyIsaFeeValueSpecified: boolean;
    chgVisaMultiCrrncyIsaFee: boolean | null;
    chgVisasGlCrrncyIsaFeeValue: boolean;
    chgVisasGlCrrncyIsaFeeValueSpecified: boolean;
    chgVisasGlCrrncyIsaFee: boolean | null;
    creditFacilityValue: boolean;
    creditFacilityValueSpecified: boolean;
    creditFacility: boolean | null;
    deactivatePreviousCardValue: boolean;
    deactivatePreviousCardValueSpecified: boolean;
    deactivatePreviousCard: boolean | null;
    deactvPrevCardExclWarnCdValue: boolean;
    deactvPrevCardExclWarnCdValueSpecified: boolean;
    deactvPrevCardExclWarnCd: boolean | null;
    fundingAccountValue: boolean;
    fundingAccountValueSpecified: boolean;
    fundingAccount: boolean | null;
    idLogicOptionValue: boolean;
    idLogicOptionValueSpecified: boolean;
    idLogicOption: boolean | null;
    limitCustomCondition: number[];
    limitCustomConditionSpecified: boolean;
    limitDescription: number[];
    limitDescriptionSpecified: boolean;
    limitMcc: number[];
    limitMccSpecified: boolean;
    limitSourceCodes: number[];
    limitSourceCodesSpecified: boolean;
    limitTransactionCodes: number[];
    limitTransactionCodesSpecified: boolean;
    limitTransactionSubTypes: number[];
    limitTransactionSubTypesSpecified: boolean;
    masterCardCcaRateValue: boolean;
    masterCardCcaRateValueSpecified: boolean;
    masterCardCcaRate: boolean | null;
    masterCardIcaRateValue: boolean;
    masterCardIcaRateValueSpecified: boolean;
    masterCardIcaRate: boolean | null;
    matchOnlineMsgExpDateValue: boolean;
    matchOnlineMsgExpDateValueSpecified: boolean;
    matchOnlineMsgExpDate: boolean | null;
    maxAfdApprForGreaterAmtValue: boolean;
    maxAfdApprForGreaterAmtValueSpecified: boolean;
    maxAfdApprForGreaterAmt: boolean | null;
    mccInTranHistoryValue: boolean;
    mccInTranHistoryValueSpecified: boolean;
    mccInTranHistory: boolean | null;
    odToleranceAvailBalListValue: boolean;
    odToleranceAvailBalListValueSpecified: boolean;
    odToleranceAvailBalList: boolean | null;
    odTransferAvailBalListValue: boolean;
    odTransferAvailBalListValueSpecified: boolean;
    odTransferAvailBalList: boolean | null;
    overdrawToleranceApprListValue: boolean;
    overdrawToleranceApprListValueSpecified: boolean;
    overdrawToleranceApprList: boolean | null;
    overdrawTransferApprListValue: boolean;
    overdrawTransferApprListValueSpecified: boolean;
    overdrawTransferApprList: boolean | null;
    pctOverLocAvailBalListValue: boolean;
    pctOverLocAvailBalListValueSpecified: boolean;
    pctOverLocAvailBalList: boolean | null;
    posAmountLimitFieldsValue: boolean;
    posAmountLimitFieldsValueSpecified: boolean;
    posAmountLimitFields: boolean | null;
    posAmountUsedFieldsValue: boolean;
    posAmountUsedFieldsValueSpecified: boolean;
    posAmountUsedFields: boolean | null;
    posCountLimitFieldsValue: boolean;
    posCountLimitFieldsValueSpecified: boolean;
    posCountLimitFields: boolean | null;
    posCountUsedFieldsValue: boolean;
    posCountUsedFieldsValueSpecified: boolean;
    posCountUsedFields: boolean | null;
    posttoAltDraftListValue: boolean;
    posttoAltDraftListValueSpecified: boolean;
    posttoAltDraftList: boolean | null;
    posttoAltFundingListValue: boolean;
    posttoAltFundingListValueSpecified: boolean;
    posttoAltFundingList: boolean | null;
    serviceAccessCodeValue: boolean;
    serviceAccessCodeValueSpecified: boolean;
    serviceAccessCode: boolean | null;
    sigAmountLimitFieldsValue: boolean;
    sigAmountLimitFieldsValueSpecified: boolean;
    sigAmountLimitFields: boolean | null;
    sigAmountUsedFieldsValue: boolean;
    sigAmountUsedFieldsValueSpecified: boolean;
    sigAmountUsedFields: boolean | null;
    sigCountLimitFieldsValue: boolean;
    sigCountLimitFieldsValueSpecified: boolean;
    sigCountLimitFields: boolean | null;
    sigCountUsedFieldsValue: boolean;
    sigCountUsedFieldsValueSpecified: boolean;
    sigCountUsedFields: boolean | null;
    signatureDescriptionValue: boolean;
    signatureDescriptionValueSpecified: boolean;
    signatureDescription: boolean | null;
    suffixPositionValue: boolean;
    suffixPositionValueSpecified: boolean;
    suffixPosition: boolean | null;
    uniqueCardNumberValue: boolean;
    uniqueCardNumberValueSpecified: boolean;
    uniqueCardNumber: boolean | null;
    useAccessEnableFlagsValue: boolean;
    useAccessEnableFlagsValueSpecified: boolean;
    useAccessEnableFlags: boolean | null;
    validateCheckDigitValue: boolean;
    validateCheckDigitValueSpecified: boolean;
    validateCheckDigit: boolean | null;
    visaMultiCurrencyIsaRateValue: boolean;
    visaMultiCurrencyIsaRateValueSpecified: boolean;
    visaMultiCurrencyIsaRate: boolean | null;
    visaSingleCurrencyIsaRateValue: boolean;
    visaSingleCurrencyIsaRateValueSpecified: boolean;
    visaSingleCurrencyIsaRate: boolean | null;
    version1: VersionType;
    merchantReturnAuthsValue: boolean;
    merchantReturnAuthsValueSpecified: boolean;
    merchantReturnAuths: boolean | null;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}