import { BitMap } from "./bitMap";
import { OnlineMainGroupMccHoldTime } from "./onlineMainGroupMccHoldTime";
import { OnlineMainGroupMccHoldUnits } from "./onlineMainGroupMccHoldUnits";
import { OnlineMainGroupMccSourceCodes } from "./onlineMainGroupMccSourceCodes";
import { OnlineMainMccTypes } from "./onlineMainMccTypes";
import { OnlineMainRelAltCourtesyPayFee1 } from "./onlineMainRelAltCourtesyPayFee1";
import { OnlineMainRelAltCourtesyPayFee2 } from "./onlineMainRelAltCourtesyPayFee2";
import { OnlineMainRelAltCourtesyPayFee3 } from "./onlineMainRelAltCourtesyPayFee3";
import { OnlineMainRelAltCourtesyPayFee4 } from "./onlineMainRelAltCourtesyPayFee4";
import { OnlineMainRelAltCourtesyPayFee5 } from "./onlineMainRelAltCourtesyPayFee5";
import { OnlineMainRelAltCourtesyPayFee6 } from "./onlineMainRelAltCourtesyPayFee6";
import { OnlineMainRelAltCourtesyPayTier1 } from "./onlineMainRelAltCourtesyPayTier1";
import { OnlineMainRelAltCourtesyPayTier2 } from "./onlineMainRelAltCourtesyPayTier2";
import { OnlineMainRelAltCourtesyPayTier3 } from "./onlineMainRelAltCourtesyPayTier3";
import { OnlineMainRelAltCourtesyPayTier4 } from "./onlineMainRelAltCourtesyPayTier4";
import { OnlineMainRelAltCourtesyPayTier5 } from "./onlineMainRelAltCourtesyPayTier5";
import { OnlineMainRelAltCourtesyPayTier6 } from "./onlineMainRelAltCourtesyPayTier6";
import { OnlineMainRelCodeList } from "./onlineMainRelCodeList";
import { OnlineMainRelCourtesyPayFee1 } from "./onlineMainRelCourtesyPayFee1";
import { OnlineMainRelCourtesyPayFee2 } from "./onlineMainRelCourtesyPayFee2";
import { OnlineMainRelCourtesyPayFee3 } from "./onlineMainRelCourtesyPayFee3";
import { OnlineMainRelCourtesyPayFee4 } from "./onlineMainRelCourtesyPayFee4";
import { OnlineMainRelCourtesyPayFee5 } from "./onlineMainRelCourtesyPayFee5";
import { OnlineMainRelCourtesyPayFee6 } from "./onlineMainRelCourtesyPayFee6";
import { OnlineMainRelCourtesyPayTier1 } from "./onlineMainRelCourtesyPayTier1";
import { OnlineMainRelCourtesyPayTier2 } from "./onlineMainRelCourtesyPayTier2";
import { OnlineMainRelCourtesyPayTier3 } from "./onlineMainRelCourtesyPayTier3";
import { OnlineMainRelCourtesyPayTier4 } from "./onlineMainRelCourtesyPayTier4";
import { OnlineMainRelCourtesyPayTier5 } from "./onlineMainRelCourtesyPayTier5";
import { OnlineMainRelCourtesyPayTier6 } from "./onlineMainRelCourtesyPayTier6";
import { OnlineMainRelNsfFee } from "./onlineMainRelNsfFee";
import { OnlineMainRelOverdrawAddonXfrFee } from "./onlineMainRelOverdrawAddonXfrFee";
import { OnlineMainRelOverdrawComboXfrFee } from "./onlineMainRelOverdrawComboXfrFee";
import { OnlineMainRelOverdrawWdXfrFee } from "./onlineMainRelOverdrawWdXfrFee";
import { OnlineMainRelOvlFee } from "./onlineMainRelOvlFee";
import { VersionType } from "./versionType";

export interface OnlineMain {
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmt: boolean | null;
    appendAtmTerminalId: boolean | null;
    atmAvailBalApprExclList: BitMap;
    atmAvailBalPostExclList: BitMap;
    atmFeeDescription: string;
    atmWarningCodeList: BitMap;
    avsAction: number | null;
    avsMethod: number | null;
    billPayFeeDescription: string;
    bpAvailBalApprExclList: BitMap;
    bpAvailBalPostExclList: BitMap;
    bpWarningCodeList: BitMap;
    cardinHistoryDigitCount: number | null;
    cashMccTypes: BitMap;
    chargePartialCapFee: boolean | null;
    checkWarningCodeList: BitMap;
    chng1GasAuthHoldAmount: number | null;
    clearingGlCode: number | null;
    courtesyNotices: number | null;
    courtesyPayCommentCode: number | null;
    courtesyPayFeeDescription: string;
    courtesyPayFeeGlCode: number | null;
    createExceptionItems: boolean | null;
    creditCardFeeDescription: string;
    cuAtmCheckDepHoldDays: number | null;
    cuAtmEnvDepHoldDays: number | null;
    cuAtmUseRegCcPolicy: boolean | null;
    debitCardFeeDescription: string;
    depWarningCodeList: BitMap;
    dqGraceDaysForAddon: number | null;
    dqGraceDaysForWd: number | null;
    dqWarningCodeList: BitMap;
    duplicateKeyPurgeTime: number | null;
    duplicateKeyRetentionDays: number | null;
    envWarningCodeList: BitMap;
    feeTypeToCap: BitMap;
    frgnAtmCheckDepHoldDays: number | null;
    frgnAtmEnvDepHoldDays: number | null;
    frgnAtmUseRegCcPolicy: boolean | null;
    glCategory: number | null;
    graceAmountforCashPayments: number | null;
    groupMccHoldTime: OnlineMainGroupMccHoldTime[];
    groupMccHoldUnits: OnlineMainGroupMccHoldUnits[];
    groupMccSourceCodes: OnlineMainGroupMccSourceCodes[];
    holdWarningCodeList: BitMap;
    includeOnlineFeesinAppr: boolean | null;
    institutionName: string;
    masterCardCcaFeeGlCode: number | null;
    masterCardIcaFeeGlCode: number | null;
    maxInvalidPinAttempts: number | null;
    maximumAddonOverLoc: number | null;
    maximumWdBelowAvailable: number | null;
    mccTypes: OnlineMainMccTypes[];
    minimumLineofCreditAddon: number | null;
    noticesPrinterType: number | null;
    nsfFeeDescIfNotPaid: string;
    nsfFeeDescIfPaid: string;
    nsfFeeForUncollectedFunds: boolean | null;
    nsfFeeGlCode: number | null;
    nsfNotices: boolean | null;
    odTransferFeeCalcOption: number | null;
    odtAuthFeeOvrSrcCodes: string;
    odtAuthFeeRecurSrcCodes: string;
    onlyLoanTransferNotices: boolean | null;
    overdrawAddonDqGraceDays: number | null;
    overdrawAddonIncrement: number | null;
    overdrawAddonMaxOverLoc: number | null;
    overdrawAddonPctOverLoc: number | null;
    overdrawFeeOption: number | null;
    overdrawIncrementOverride: number | null;
    overdrawNoticesfor2NdAcct: boolean | null;
    overdrawOption: number | null;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOption: number | null;
    overdrawTransferFeeGlCode: number | null;
    overdrawTransferNotices: number | null;
    overdrawWithdrawalIncrement: number | null;
    ovlFeeDescIfNotPaid: string;
    ovlFeeDescIfPaid: string;
    ovlFeeForUncollectedFunds: boolean | null;
    ovlFeeGlCode: number | null;
    ovlNotices: boolean | null;
    percentOverLineofCredit: number | null;
    pinPreAuthGasHoldTime: number | null;
    pinPreAuthGasHoldUnits: number | null;
    posAvailBalAuthExclList: BitMap;
    posAvailBalPostExclList: BitMap;
    posFeeDescription: string;
    posWarningCodeList: BitMap;
    postAtmBalanceInquiries: boolean | null;
    postAtmStatements: boolean | null;
    preAuthExpHoldMatchDays: number | null;
    preAuthFmHistoryOption: number | null;
    preAuthHoldTime: number | null;
    preAuthHoldUnits: number | null;
    preAuthMatchVariance: number | null;
    preAuthMaxHoldDays: number | null;
    preAuthTeHoldTime: number | null;
    preAuthTeHoldUnits: number | null;
    prependRegEComments: boolean | null;
    relAltCourtesyPayFee1: OnlineMainRelAltCourtesyPayFee1[];
    relAltCourtesyPayFee2: OnlineMainRelAltCourtesyPayFee2[];
    relAltCourtesyPayFee3: OnlineMainRelAltCourtesyPayFee3[];
    relAltCourtesyPayFee4: OnlineMainRelAltCourtesyPayFee4[];
    relAltCourtesyPayFee5: OnlineMainRelAltCourtesyPayFee5[];
    relAltCourtesyPayFee6: OnlineMainRelAltCourtesyPayFee6[];
    relAltCourtesyPayTier1: OnlineMainRelAltCourtesyPayTier1[];
    relAltCourtesyPayTier2: OnlineMainRelAltCourtesyPayTier2[];
    relAltCourtesyPayTier3: OnlineMainRelAltCourtesyPayTier3[];
    relAltCourtesyPayTier4: OnlineMainRelAltCourtesyPayTier4[];
    relAltCourtesyPayTier5: OnlineMainRelAltCourtesyPayTier5[];
    relAltCourtesyPayTier6: OnlineMainRelAltCourtesyPayTier6[];
    relCodeList: OnlineMainRelCodeList[];
    relCourtesyPayFee1: OnlineMainRelCourtesyPayFee1[];
    relCourtesyPayFee2: OnlineMainRelCourtesyPayFee2[];
    relCourtesyPayFee3: OnlineMainRelCourtesyPayFee3[];
    relCourtesyPayFee4: OnlineMainRelCourtesyPayFee4[];
    relCourtesyPayFee5: OnlineMainRelCourtesyPayFee5[];
    relCourtesyPayFee6: OnlineMainRelCourtesyPayFee6[];
    relCourtesyPayTier1: OnlineMainRelCourtesyPayTier1[];
    relCourtesyPayTier2: OnlineMainRelCourtesyPayTier2[];
    relCourtesyPayTier3: OnlineMainRelCourtesyPayTier3[];
    relCourtesyPayTier4: OnlineMainRelCourtesyPayTier4[];
    relCourtesyPayTier5: OnlineMainRelCourtesyPayTier5[];
    relCourtesyPayTier6: OnlineMainRelCourtesyPayTier6[];
    relNsfFee: OnlineMainRelNsfFee[];
    relOverdrawAddonXfrFee: OnlineMainRelOverdrawAddonXfrFee[];
    relOverdrawComboXfrFee: OnlineMainRelOverdrawComboXfrFee[];
    relOverdrawWdXfrFee: OnlineMainRelOverdrawWdXfrFee[];
    relOvlFee: OnlineMainRelOvlFee[];
    reportTitle: string;
    sigAvailBalAuthExclList: BitMap;
    sigAvailBalPostExclList: BitMap;
    sigPreAuthGasHoldTime: number | null;
    sigPreAuthGasHoldUnits: number | null;
    sigWarningCodeList: BitMap;
    useFeeStatusfromAuth: string;
    useLowQualMatchFeeStatus: string;
    useNetworkPreAuthHoldTime: boolean | null;
    usePostExclListonFinReq: string;
    visaMultiCrrncyIsaFeeGl: number | null;
    visaSglCrrncyIsaFeeGl: number | null;
    waiveFeeforAuthAdvice: string;
    waiveFeeonNoHoldMatch: string;
    waiveFeeonNoHoldRecur: string;
    wdBelowAvailableOption: number | null;
    wdWarningCodeList: BitMap;
    version1: VersionType;
}