import { BitMap } from "./bitMap";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineSbAddOn {
    availBalApprExclList: BitMap;
    availBalPostExclList: BitMap;
    cardAcceptorLocation: string;
    cardAcceptorName: string;
    checkDepositHoldsValue: number;
    checkDepositHoldsValueSpecified: boolean;
    checkDepositHolds: number | null;
    customCriterionValue: number;
    customCriterionValueSpecified: boolean;
    customCriterion: number | null;
    depRestrictWarnList: BitMap;
    glCodeValue: number;
    glCodeValueSpecified: boolean;
    glCode: number | null;
    lnExcludeTypeList: BitMap;
    nonIrsCertTranAccessValue: boolean;
    nonIrsCertTranAccessValueSpecified: boolean;
    nonIrsCertTranAccess: boolean | null;
    nonIrsClubTranAccessValue: boolean;
    nonIrsClubTranAccessValueSpecified: boolean;
    nonIrsClubTranAccess: boolean | null;
    posConditionCodes: string;
    regDLimitingValue: boolean;
    regDLimitingValueSpecified: boolean;
    regDLimiting: boolean | null;
    restrictWarnList: BitMap;
    ruleDescription: string;
    ruleOrdinalValue: number;
    ruleOrdinalValueSpecified: boolean;
    ruleOrdinal: number | null;
    rulePositionValue: number;
    rulePositionValueSpecified: boolean;
    rulePosition: number | null;
    svExcludeTypeList: BitMap;
    transactionHistoryPrefix: string;
    transactionSourceCode: string;
    transactionSubTypeValue: number;
    transactionSubTypeValueSpecified: boolean;
    transactionSubType: number | null;
    wdRestrictWarnList: BitMap;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}