import { BitMap } from "./bitMap";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface OnlineNet_2 {
    acquirerProcessorId: string;
    acquirerProcessorValue: string;
    acquirerSecurityCode: string;
    acquirerSettlementTime: string;
    clientId: string;
    dataProcessingCenter: string;
    financialInstitutionId: string;
    forcePostFinTrnLimitUsage: string;
    glCodeValue: number;
    glCodeValueSpecified: boolean;
    glCode: number | null;
    holdMatchWeightValue: number;
    holdMatchWeightValueSpecified: boolean;
    holdMatchWeight: number | null;
    holdMatchWeightIncrementalsValue: number;
    holdMatchWeightIncrementalsValueSpecified: boolean;
    holdMatchWeightIncrementals: number | null;
    issuerProcessorValue: string;
    issuerSecurityCode: string;
    issuerSettlementTime: string;
    logicalNetwork: string;
    masterCardCcaFeeComment: string;
    masterCardCcaFeeGlCodeValue: number;
    masterCardCcaFeeGlCodeValueSpecified: boolean;
    masterCardCcaFeeGlCode: number | null;
    masterCardIcaFeeComment: string;
    masterCardIcaFeeGlCodeValue: number;
    masterCardIcaFeeGlCodeValueSpecified: boolean;
    masterCardIcaFeeGlCode: number | null;
    networkManagesPreAuthHoldsValue: boolean;
    networkManagesPreAuthHoldsValueSpecified: boolean;
    networkManagesPreAuthHolds: boolean | null;
    networkMessageFormatValue: number;
    networkMessageFormatValueSpecified: boolean;
    networkMessageFormat: number | null;
    otherAccountMiscIdValue: number;
    otherAccountMiscIdValueSpecified: boolean;
    otherAccountMiscId: number | null;
    otherAccountTypeValue: number;
    otherAccountTypeValueSpecified: boolean;
    otherAccountType: number | null;
    partialApprovalCardTypes: BitMap;
    password: string;
    pinPartialApprovalOptionValue: number;
    pinPartialApprovalOptionValueSpecified: boolean;
    pinPartialApprovalOption: number | null;
    postAdministrativeMessagesValue: boolean;
    postAdministrativeMessagesValueSpecified: boolean;
    postAdministrativeMessages: boolean | null;
    principalId: string;
    requestAdvicePairsValue: boolean;
    requestAdvicePairsValueSpecified: boolean;
    requestAdvicePairs: boolean | null;
    returnBalOnNonAtmTrans: BitMap;
    returnedBalancesValue: number;
    returnedBalancesValueSpecified: boolean;
    returnedBalances: number | null;
    routingTransitNumber: string;
    sigPartialApprovalOptionValue: number;
    sigPartialApprovalOptionValueSpecified: boolean;
    sigPartialApprovalOption: number | null;
    systemId: string;
    terminalIdOptionValue: number;
    terminalIdOptionValueSpecified: boolean;
    terminalIdOption: number | null;
    tokenizationNoteCodeValue: number;
    tokenizationNoteCodeValueSpecified: boolean;
    tokenizationNoteCode: number | null;
    updateCardStatusReasonValue: boolean;
    updateCardStatusReasonValueSpecified: boolean;
    updateCardStatusReason: boolean | null;
    useAcctsinOnlineMessageValue: boolean;
    useAcctsinOnlineMessageValueSpecified: boolean;
    useAcctsinOnlineMessage: boolean | null;
    validateOnlineMsgAcctValue: boolean;
    validateOnlineMsgAcctValueSpecified: boolean;
    validateOnlineMsgAcct: boolean | null;
    visaMultiCrrncyIsaFeeCmnt: string;
    visaMultiCrrncyIsaFeeGlValue: number;
    visaMultiCrrncyIsaFeeGlValueSpecified: boolean;
    visaMultiCrrncyIsaFeeGl: number | null;
    visaSglCrrncyIsaFeeCmnt: string;
    visaSglCrrncyIsaFeeGlValue: number;
    visaSglCrrncyIsaFeeGlValueSpecified: boolean;
    visaSglCrrncyIsaFeeGl: number | null;
    warnonOverdrawValue: boolean;
    warnonOverdrawValueSpecified: boolean;
    warnonOverdraw: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}