import { ParameterFields } from "./parameterFields";
import { AccountDefaultSelectableFields } from "./accountDefaultSelectableFields";
import { AccountFieldNameSelectableFields } from "./accountFieldNameSelectableFields";
import { AcctLimitSelectableFields } from "./acctLimitSelectableFields";
import { AcctMembGrpDescSelectableFields } from "./acctMembGrpDescSelectableFields";
import { AcctRelCodeDescSelectableFields } from "./acctRelCodeDescSelectableFields";
import { AcctTrackingTypeSelectableFields } from "./acctTrackingTypeSelectableFields";
import { AcctTypeNameSelectableFields } from "./acctTypeNameSelectableFields";
import { AcsGlobalSelectableFields } from "./acsGlobalSelectableFields";
import { AcsServiceSelectableFields } from "./acsServiceSelectableFields";
import { ActivityFmSelectableFields } from "./activityFmSelectableFields";
import { AnalysisFloatSelectableFields } from "./analysisFloatSelectableFields";
import { AnalysisGlobalSelectableFields } from "./analysisGlobalSelectableFields";
import { AnalysisPlanSelectableFields } from "./analysisPlanSelectableFields";
import { ApMiscSelectableFields } from "./apMiscSelectableFields";
import { ApPmtTermsTableSelectableFields } from "./apPmtTermsTableSelectableFields";
import { ApWorkFlowSelectableFields } from "./apWorkFlowSelectableFields";
import { AtmSelectableFields } from "./atmSelectableFields";
import { AudioSelectableFields } from "./audioSelectableFields";
import { BatchRcSelectableFields } from "./batchRcSelectableFields";
import { CardDefaultSelectableFields } from "./cardDefaultSelectableFields";
import { CardWizSelectableFields } from "./cardWizSelectableFields";
import { CashOrderVendorSelectableFields } from "./cashOrderVendorSelectableFields";
import { CdmSelectableFields } from "./cdmSelectableFields";
import { CdmCommonSelectableFields } from "./cdmCommonSelectableFields";
import { CheckOrderDefaultSelectableFields } from "./checkOrderDefaultSelectableFields";
import { CollateralTypeSelectableFields } from "./collateralTypeSelectableFields";
import { CollatrlTrackingTypeSelectableFields } from "./collatrlTrackingTypeSelectableFields";
import { CommentSelectableFields } from "./commentSelectableFields";
import { ConsoleFmSelectableFields } from "./consoleFmSelectableFields";
import { CorpTransferSelectableFields } from "./corpTransferSelectableFields";
import { CpLetterSelectableFields } from "./cpLetterSelectableFields";
import { CpWorkCardSelectableFields } from "./cpWorkCardSelectableFields";
import { CreditReportSelectableFields } from "./creditReportSelectableFields";
import { CrsSelectableFields } from "./crsSelectableFields";
import { CurrencyCtrlSelectableFields } from "./currencyCtrlSelectableFields";
import { DailyPostSelectableFields } from "./dailyPostSelectableFields";
import { DealerStatementSelectableFields } from "./dealerStatementSelectableFields";
import { DebtRatioSelectableFields } from "./debtRatioSelectableFields";
import { DisclosureSelectableFields } from "./disclosureSelectableFields";
import { DivIndexGlobalSelectableFields } from "./divIndexGlobalSelectableFields";
import { DivIndexLocalSelectableFields } from "./divIndexLocalSelectableFields";
import { DivTableSelectableFields } from "./divTableSelectableFields";
import { DocExcpNoticeSelectableFields } from "./docExcpNoticeSelectableFields";
import { DocTypeDefaultSelectableFields } from "./docTypeDefaultSelectableFields";
import { DocumentNumberSelectableFields } from "./documentNumberSelectableFields";
import { EpisysDbExtractSelectableFields } from "./episysDbExtractSelectableFields";
import { EscrowAnalysisSelectableFields } from "./escrowAnalysisSelectableFields";
import { EscrowTypeSelectableFields } from "./escrowTypeSelectableFields";
import { ExtLoanSelectableFields } from "./extLoanSelectableFields";
import { GlCategorySelectableFields } from "./glCategorySelectableFields";
import { GlCodeSelectableFields } from "./glCodeSelectableFields";
import { GlTableSelectableFields } from "./glTableSelectableFields";
import { GlTrackingTypeSelectableFields } from "./glTrackingTypeSelectableFields";
import { GlxLateSelectableFields } from "./glxLateSelectableFields";
import { IdentIdTypeDescSelectableFields } from "./identIdTypeDescSelectableFields";
import { ImagingSelectableFields } from "./imagingSelectableFields";
import { InqDefinitionSelectableFields } from "./inqDefinitionSelectableFields";
import { InsTableSelectableFields } from "./insTableSelectableFields";
import { InsTypeSelectableFields } from "./insTypeSelectableFields";
import { InstitutionSelectableFields } from "./institutionSelectableFields";
import { IntIndexSelectableFields } from "./intIndexSelectableFields";
import { IntTypeSelectableFields } from "./intTypeSelectableFields";
import { InventoryCopiedFldsSelectableFields } from "./inventoryCopiedFldsSelectableFields";
import { InventoryDefaultSelectableFields } from "./inventoryDefaultSelectableFields";
import { InventoryFieldNameSelectableFields } from "./inventoryFieldNameSelectableFields";
import { InventoryGeneralSelectableFields } from "./inventoryGeneralSelectableFields";
import { InventoryTypeSelectableFields } from "./inventoryTypeSelectableFields";
import { IrsBkupWithholdSelectableFields } from "./irsBkupWithholdSelectableFields";
import { IrsContriLimitSelectableFields } from "./irsContriLimitSelectableFields";
import { ItcFraudSelectableFields } from "./itcFraudSelectableFields";
import { ItcInstallationSelectableFields } from "./itcInstallationSelectableFields";
import { LateChgSelectableFields } from "./lateChgSelectableFields";
import { LnSegmentDefaultSelectableFields } from "./lnSegmentDefaultSelectableFields";
import { LoanAppCopiedFldsSelectableFields } from "./loanAppCopiedFldsSelectableFields";
import { LoanAppDefaultSelectableFields } from "./loanAppDefaultSelectableFields";
import { LoanAppDenialSelectableFields } from "./loanAppDenialSelectableFields";
import { LoanAppFieldNameSelectableFields } from "./loanAppFieldNameSelectableFields";
import { LoanAppFormPktSelectableFields } from "./loanAppFormPktSelectableFields";
import { LoanAppMiscSelectableFields } from "./loanAppMiscSelectableFields";
import { LoanAppPrintAppSelectableFields } from "./loanAppPrintAppSelectableFields";
import { LoanAppReusedFldsSelectableFields } from "./loanAppReusedFldsSelectableFields";
import { LoanAppVerFormSelectableFields } from "./loanAppVerFormSelectableFields";
import { LoanAppViewAppSelectableFields } from "./loanAppViewAppSelectableFields";
import { LoanAppWorkFlowSelectableFields } from "./loanAppWorkFlowSelectableFields";
import { LoanDefaultSelectableFields } from "./loanDefaultSelectableFields";
import { LoanFieldNameSelectableFields } from "./loanFieldNameSelectableFields";
import { LoanTypeIdRangeSelectableFields } from "./loanTypeIdRangeSelectableFields";
import { LookupTypeNameSelectableFields } from "./lookupTypeNameSelectableFields";
import { MiscSelectableFields } from "./miscSelectableFields";
import { MiscPmtSelectableFields } from "./miscPmtSelectableFields";
import { MoProductSelectableFields } from "./moProductSelectableFields";
import { NameFieldNameSelectableFields } from "./nameFieldNameSelectableFields";
import { Ncua5300SelectableFields } from "./ncua5300SelectableFields";
import { NonRegCcSelectableFields } from "./nonRegCcSelectableFields";
import { NoticeSelectableFields } from "./noticeSelectableFields";
import { OnlineBlockSelectableFields } from "./onlineBlockSelectableFields";
import { OnlineCardSelectableFields } from "./onlineCardSelectableFields";
import { OnlineFeeSelectableFields } from "./onlineFeeSelectableFields";
import { OnlineFileSelectableFields } from "./onlineFileSelectableFields";
import { OnlineFileMgrSelectableFields } from "./onlineFileMgrSelectableFields";
import { OnlineMainSelectableFields } from "./onlineMainSelectableFields";
import { OnlineNetSelectableFields } from "./onlineNetSelectableFields";
import { OnlineOutletSelectableFields } from "./onlineOutletSelectableFields";
import { OnlineSbAddOnSelectableFields } from "./onlineSbAddOnSelectableFields";
import { OnlineSbaSelectableFields } from "./onlineSbaSelectableFields";
import { OnlineSbiSelectableFields } from "./onlineSbiSelectableFields";
import { Param360ViewSelectableFields } from "./param360ViewSelectableFields";
import { PartStatementSelectableFields } from "./partStatementSelectableFields";
import { PartTrackingTypeSelectableFields } from "./partTrackingTypeSelectableFields";
import { ParticipantFieldNameSelectableFields } from "./participantFieldNameSelectableFields";
import { PayCalcSelectableFields } from "./payCalcSelectableFields";
import { PeriodicMtgSelectableFields } from "./periodicMtgSelectableFields";
import { PlanDefaultSelectableFields } from "./planDefaultSelectableFields";
import { PlanFieldNameSelectableFields } from "./planFieldNameSelectableFields";
import { PmtAppMethodSelectableFields } from "./pmtAppMethodSelectableFields";
import { PositivePaySelectableFields } from "./positivePaySelectableFields";
import { PreferenceDefaultSelectableFields } from "./preferenceDefaultSelectableFields";
import { PrivGroupSelectableFields } from "./privGroupSelectableFields";
import { RegCcSelectableFields } from "./regCcSelectableFields";
import { ScreenDefinitionSelectableFields } from "./screenDefinitionSelectableFields";
import { SecFieldSelectableFields } from "./secFieldSelectableFields";
import { SecuritySelectableFields } from "./securitySelectableFields";
import { ShareDefaultSelectableFields } from "./shareDefaultSelectableFields";
import { ShareFieldNameSelectableFields } from "./shareFieldNameSelectableFields";
import { StatementSelectableFields } from "./statementSelectableFields";
import { StmtMailNameSelectableFields } from "./stmtMailNameSelectableFields";
import { StmtMessagesSelectableFields } from "./stmtMessagesSelectableFields";
import { StockSelectableFields } from "./stockSelectableFields";
import { SycClientSelectableFields } from "./sycClientSelectableFields";
import { SycGeneralSelectableFields } from "./sycGeneralSelectableFields";
import { SymXClientSelectableFields } from "./symXClientSelectableFields";
import { SymXDeviceMapSelectableFields } from "./symXDeviceMapSelectableFields";
import { SymXGeneralSelectableFields } from "./symXGeneralSelectableFields";
import { SymXInstanceSelectableFields } from "./symXInstanceSelectableFields";
import { SynapsysMrmSelectableFields } from "./synapsysMrmSelectableFields";
import { TcProductSelectableFields } from "./tcProductSelectableFields";
import { TellerFeeSelectableFields } from "./tellerFeeSelectableFields";
import { TellerTranFeeSelectableFields } from "./tellerTranFeeSelectableFields";
import { TellerTranValidateSelectableFields } from "./tellerTranValidateSelectableFields";
import { TptSelectableFields } from "./tptSelectableFields";
import { TrackingCodeSelectableFields } from "./trackingCodeSelectableFields";
import { UserFmSelectableFields } from "./userFmSelectableFields";
import { UserTrackingFmSelectableFields } from "./userTrackingFmSelectableFields";
import { UserTrackingTypeSelectableFields } from "./userTrackingTypeSelectableFields";
import { WarningsSelectableFields } from "./warningsSelectableFields";
import { WdFeeSelectableFields } from "./wdFeeSelectableFields";
import { WestUnCommCodeSelectableFields } from "./westUnCommCodeSelectableFields";
import { WireBfcSelectableFields } from "./wireBfcSelectableFields";
import { WireCorpVerSelectableFields } from "./wireCorpVerSelectableFields";
import { WireIdCodeSelectableFields } from "./wireIdCodeSelectableFields";
import { WireInCmtCodeSelectableFields } from "./wireInCmtCodeSelectableFields";
import { WireMiscSelectableFields } from "./wireMiscSelectableFields";
import { WireOutCmtCodeSelectableFields } from "./wireOutCmtCodeSelectableFields";
import { WireTypeCodeSelectableFields } from "./wireTypeCodeSelectableFields";
import { WorkFlowRepGenSelectableFields } from "./workFlowRepGenSelectableFields";
import { YellowHammerSelectableFields } from "./yellowHammerSelectableFields";
import { VersionType } from "./versionType";

export interface ParameterSelectableFields {
    includeAllParameterFields: boolean | null;
    parameterFields: ParameterFields;
    accountDefaultSelectableFields: AccountDefaultSelectableFields;
    accountFieldNameSelectableFields: AccountFieldNameSelectableFields;
    acctLimitSelectableFields: AcctLimitSelectableFields;
    acctMembGrpDescSelectableFields: AcctMembGrpDescSelectableFields;
    acctRelCodeDescSelectableFields: AcctRelCodeDescSelectableFields;
    acctTrackingTypeSelectableFields: AcctTrackingTypeSelectableFields;
    acctTypeNameSelectableFields: AcctTypeNameSelectableFields;
    acsGlobalSelectableFields: AcsGlobalSelectableFields;
    acsServiceSelectableFields: AcsServiceSelectableFields;
    activityFmSelectableFields: ActivityFmSelectableFields;
    analysisFloatSelectableFields: AnalysisFloatSelectableFields;
    analysisGlobalSelectableFields: AnalysisGlobalSelectableFields;
    analysisPlanSelectableFields: AnalysisPlanSelectableFields;
    apMiscSelectableFields: ApMiscSelectableFields;
    apPmtTermsTableSelectableFields: ApPmtTermsTableSelectableFields;
    apWorkFlowSelectableFields: ApWorkFlowSelectableFields;
    atmSelectableFields: AtmSelectableFields;
    audioSelectableFields: AudioSelectableFields;
    batchRcSelectableFields: BatchRcSelectableFields;
    cardDefaultSelectableFields: CardDefaultSelectableFields;
    cardWizSelectableFields: CardWizSelectableFields;
    cashOrderVendorSelectableFields: CashOrderVendorSelectableFields;
    cdmSelectableFields: CdmSelectableFields;
    cdmCommonSelectableFields: CdmCommonSelectableFields;
    checkOrderDefaultSelectableFields: CheckOrderDefaultSelectableFields;
    collateralTypeSelectableFields: CollateralTypeSelectableFields;
    collatrlTrackingTypeSelectableFields: CollatrlTrackingTypeSelectableFields;
    commentSelectableFields: CommentSelectableFields;
    consoleFmSelectableFields: ConsoleFmSelectableFields;
    corpTransferSelectableFields: CorpTransferSelectableFields;
    cpLetterSelectableFields: CpLetterSelectableFields;
    cpWorkCardSelectableFields: CpWorkCardSelectableFields;
    creditReportSelectableFields: CreditReportSelectableFields;
    crsSelectableFields: CrsSelectableFields;
    currencyCtrlSelectableFields: CurrencyCtrlSelectableFields;
    dailyPostSelectableFields: DailyPostSelectableFields;
    dealerStatementSelectableFields: DealerStatementSelectableFields;
    debtRatioSelectableFields: DebtRatioSelectableFields;
    disclosureSelectableFields: DisclosureSelectableFields;
    divIndexGlobalSelectableFields: DivIndexGlobalSelectableFields;
    divIndexLocalSelectableFields: DivIndexLocalSelectableFields;
    divTableSelectableFields: DivTableSelectableFields;
    docExcpNoticeSelectableFields: DocExcpNoticeSelectableFields;
    docTypeDefaultSelectableFields: DocTypeDefaultSelectableFields;
    documentNumberSelectableFields: DocumentNumberSelectableFields;
    episysDbExtractSelectableFields: EpisysDbExtractSelectableFields;
    escrowAnalysisSelectableFields: EscrowAnalysisSelectableFields;
    escrowTypeSelectableFields: EscrowTypeSelectableFields;
    extLoanSelectableFields: ExtLoanSelectableFields;
    glCategorySelectableFields: GlCategorySelectableFields;
    glCodeSelectableFields: GlCodeSelectableFields;
    glTableSelectableFields: GlTableSelectableFields;
    glTrackingTypeSelectableFields: GlTrackingTypeSelectableFields;
    glxLateSelectableFields: GlxLateSelectableFields;
    identIdTypeDescSelectableFields: IdentIdTypeDescSelectableFields;
    imagingSelectableFields: ImagingSelectableFields;
    inqDefinitionSelectableFields: InqDefinitionSelectableFields;
    insTableSelectableFields: InsTableSelectableFields;
    insTypeSelectableFields: InsTypeSelectableFields;
    institutionSelectableFields: InstitutionSelectableFields;
    intIndexSelectableFields: IntIndexSelectableFields;
    intTypeSelectableFields: IntTypeSelectableFields;
    inventoryCopiedFldsSelectableFields: InventoryCopiedFldsSelectableFields;
    inventoryDefaultSelectableFields: InventoryDefaultSelectableFields;
    inventoryFieldNameSelectableFields: InventoryFieldNameSelectableFields;
    inventoryGeneralSelectableFields: InventoryGeneralSelectableFields;
    inventoryTypeSelectableFields: InventoryTypeSelectableFields;
    irsBkupWithholdSelectableFields: IrsBkupWithholdSelectableFields;
    irsContriLimitSelectableFields: IrsContriLimitSelectableFields;
    itcFraudSelectableFields: ItcFraudSelectableFields;
    itcInstallationSelectableFields: ItcInstallationSelectableFields;
    lateChgSelectableFields: LateChgSelectableFields;
    lnSegmentDefaultSelectableFields: LnSegmentDefaultSelectableFields;
    loanAppCopiedFldsSelectableFields: LoanAppCopiedFldsSelectableFields;
    loanAppDefaultSelectableFields: LoanAppDefaultSelectableFields;
    loanAppDenialSelectableFields: LoanAppDenialSelectableFields;
    loanAppFieldNameSelectableFields: LoanAppFieldNameSelectableFields;
    loanAppFormPktSelectableFields: LoanAppFormPktSelectableFields;
    loanAppMiscSelectableFields: LoanAppMiscSelectableFields;
    loanAppPrintAppSelectableFields: LoanAppPrintAppSelectableFields;
    loanAppReusedFldsSelectableFields: LoanAppReusedFldsSelectableFields;
    loanAppVerFormSelectableFields: LoanAppVerFormSelectableFields;
    loanAppViewAppSelectableFields: LoanAppViewAppSelectableFields;
    loanAppWorkFlowSelectableFields: LoanAppWorkFlowSelectableFields;
    loanDefaultSelectableFields: LoanDefaultSelectableFields;
    loanFieldNameSelectableFields: LoanFieldNameSelectableFields;
    loanTypeIdRangeSelectableFields: LoanTypeIdRangeSelectableFields;
    lookupTypeNameSelectableFields: LookupTypeNameSelectableFields;
    miscSelectableFields: MiscSelectableFields;
    miscPmtSelectableFields: MiscPmtSelectableFields;
    moProductSelectableFields: MoProductSelectableFields;
    nameFieldNameSelectableFields: NameFieldNameSelectableFields;
    ncua5300SelectableFields: Ncua5300SelectableFields;
    nonRegCcSelectableFields: NonRegCcSelectableFields;
    noticeSelectableFields: NoticeSelectableFields;
    onlineBlockSelectableFields: OnlineBlockSelectableFields;
    onlineCardSelectableFields: OnlineCardSelectableFields;
    onlineFeeSelectableFields: OnlineFeeSelectableFields;
    onlineFileSelectableFields: OnlineFileSelectableFields;
    onlineFileMgrSelectableFields: OnlineFileMgrSelectableFields;
    onlineMainSelectableFields: OnlineMainSelectableFields;
    onlineNetSelectableFields: OnlineNetSelectableFields;
    onlineOutletSelectableFields: OnlineOutletSelectableFields;
    onlineSbAddOnSelectableFields: OnlineSbAddOnSelectableFields;
    onlineSbaSelectableFields: OnlineSbaSelectableFields;
    onlineSbiSelectableFields: OnlineSbiSelectableFields;
    param360ViewSelectableFields: Param360ViewSelectableFields;
    partStatementSelectableFields: PartStatementSelectableFields;
    partTrackingTypeSelectableFields: PartTrackingTypeSelectableFields;
    participantFieldNameSelectableFields: ParticipantFieldNameSelectableFields;
    payCalcSelectableFields: PayCalcSelectableFields;
    periodicMtgSelectableFields: PeriodicMtgSelectableFields;
    planDefaultSelectableFields: PlanDefaultSelectableFields;
    planFieldNameSelectableFields: PlanFieldNameSelectableFields;
    pmtAppMethodSelectableFields: PmtAppMethodSelectableFields;
    positivePaySelectableFields: PositivePaySelectableFields;
    preferenceDefaultSelectableFields: PreferenceDefaultSelectableFields;
    privGroupSelectableFields: PrivGroupSelectableFields;
    regCcSelectableFields: RegCcSelectableFields;
    screenDefinitionSelectableFields: ScreenDefinitionSelectableFields;
    secFieldSelectableFields: SecFieldSelectableFields;
    securitySelectableFields: SecuritySelectableFields;
    shareDefaultSelectableFields: ShareDefaultSelectableFields;
    shareFieldNameSelectableFields: ShareFieldNameSelectableFields;
    statementSelectableFields: StatementSelectableFields;
    stmtMailNameSelectableFields: StmtMailNameSelectableFields;
    stmtMessagesSelectableFields: StmtMessagesSelectableFields;
    stockSelectableFields: StockSelectableFields;
    sycClientSelectableFields: SycClientSelectableFields;
    sycGeneralSelectableFields: SycGeneralSelectableFields;
    symXClientSelectableFields: SymXClientSelectableFields;
    symXDeviceMapSelectableFields: SymXDeviceMapSelectableFields;
    symXGeneralSelectableFields: SymXGeneralSelectableFields;
    symXInstanceSelectableFields: SymXInstanceSelectableFields;
    synapsysMrmSelectableFields: SynapsysMrmSelectableFields;
    tcProductSelectableFields: TcProductSelectableFields;
    tellerFeeSelectableFields: TellerFeeSelectableFields;
    tellerTranFeeSelectableFields: TellerTranFeeSelectableFields;
    tellerTranValidateSelectableFields: TellerTranValidateSelectableFields;
    tptSelectableFields: TptSelectableFields;
    trackingCodeSelectableFields: TrackingCodeSelectableFields;
    userFmSelectableFields: UserFmSelectableFields;
    userTrackingFmSelectableFields: UserTrackingFmSelectableFields;
    userTrackingTypeSelectableFields: UserTrackingTypeSelectableFields;
    warningsSelectableFields: WarningsSelectableFields;
    wdFeeSelectableFields: WdFeeSelectableFields;
    westUnCommCodeSelectableFields: WestUnCommCodeSelectableFields;
    wireBfcSelectableFields: WireBfcSelectableFields;
    wireCorpVerSelectableFields: WireCorpVerSelectableFields;
    wireIdCodeSelectableFields: WireIdCodeSelectableFields;
    wireInCmtCodeSelectableFields: WireInCmtCodeSelectableFields;
    wireMiscSelectableFields: WireMiscSelectableFields;
    wireOutCmtCodeSelectableFields: WireOutCmtCodeSelectableFields;
    wireTypeCodeSelectableFields: WireTypeCodeSelectableFields;
    workFlowRepGenSelectableFields: WorkFlowRepGenSelectableFields;
    yellowHammerSelectableFields: YellowHammerSelectableFields;
    version1: VersionType;
}