import { VersionType } from "./versionType";

export interface Param360ViewFields {
    accountStmtMailCodeList: boolean | null;
    accountTrackingTypeList: boolean | null;
    achOrigEftGroupList: boolean | null;
    allLnsAcctNameTypeList: boolean | null;
    allShrsAcctNameTypeList: boolean | null;
    audioResponseDescription: boolean | null;
    billPayAcctTrackTypeList: boolean | null;
    billPayEftGroupList: boolean | null;
    billPaymentDescription: boolean | null;
    cardTypeList: number[];
    cardTypeListDescription: number[];
    checkAudioAccessCode: boolean | null;
    checkEstatementEnableFlag: boolean | null;
    checkHbPwdAndAudioAccess: boolean | null;
    displayMemberGroupDesc: boolean | null;
    enableAcsPaneIn360View: boolean | null;
    enableTellerTran360View: boolean | null;
    estatementsDescription: boolean | null;
    excludeSsnTin: number[];
    excludeSsnTinType: number[];
    inventoryTypeList: boolean | null;
    loanNameTypeList: boolean | null;
    loanServiceCodeList: boolean | null;
    loanStmtMailCodeList: boolean | null;
    nonStandardTrackingTypeList: boolean | null;
    onlineBankingDescription: boolean | null;
    otherSvcTrackingTypeList: boolean | null;
    safeDepositBoxDescription: boolean | null;
    shareNameTypeList: boolean | null;
    shareServiceCodeList: boolean | null;
    shareStmtMailCodeList: boolean | null;
    standardTrackingTypeList: boolean | null;
    trackingTypeList: number[];
    trackingTypeListDesc: number[];
    warningCodeList: boolean | null;
    version1: VersionType;
}