import { ParticipantBuckets } from "./participantBuckets";
import { ParticipantFmHistoryList } from "./participantFmHistoryList";
import { ParticipantNoteList } from "./participantNoteList";
import { ParticipantTransactionList } from "./participantTransactionList";
import { VersionType } from "./versionType";

export interface Participant {
    achTranCodeOut: number | null;
    active: number | null;
    adjLs: number | null;
    balance: number | null;
    beginningBalLs: number | null;
    branch: number | null;
    buckets: ParticipantBuckets[];
    chargeOffBalance: number | null;
    chargebackBalance: number | null;
    chargebackLs: number | null;
    chgOffLoanCount: number | null;
    closeDate: string | null;
    dealerAvailBalance: number | null;
    dealerTotalBalance: number | null;
    feesLs: number | null;
    fmLastPurgeDate: string | null;
    holdbackLs: number | null;
    lastDisbursalDate: string | null;
    lastFmDate: string | null;
    lastPurgeDate: string | null;
    legacyCode: string;
    loanBalanceSlp: number | null;
    loanCount: number | null;
    loanCountSlp: number | null;
    name: string;
    number: string;
    openDate: string | null;
    participantFmHistoryList: ParticipantFmHistoryList;
    participantNoteList: ParticipantNoteList;
    participantTransactionList: ParticipantTransactionList;
    paymentMethod: number | null;
    paymentsLtd: number | null;
    paymentsLastYear: number | null;
    paymentsYtd: number | null;
    recordChangeDate: string | null;
    reservePaymentMethod: number | null;
    statementDate: string | null;
    statementGroup: number | null;
    statementPrevDate: string | null;
    subType: number | null;
    totalEarnedReserve: number | null;
    totalHoldbackAmount: number | null;
    totalLoanBalance: number | null;
    totalReserveAccrual: number | null;
    totalUnearnedReserve: number | null;
    totalUpFrontReserve: number | null;
    ttlERsvNoChgD: number | null;
    ttlERsvNoClsD: number | null;
    ttlUeRsvNoChgD: number | null;
    ttlUeRsvNoClsD: number | null;
    ttlUfRsvNoChgD: number | null;
    ttlUfRsvNoClsD: number | null;
    type: number | null;
    unpaidUpFrontReserve: number | null;
    upFrontRsrvLs: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userCode1: number | null;
    userDate1: string | null;
    userNumber1: number | null;
    userRate1: number | null;
    vendorAltEmail: string;
    vendorCity: string;
    vendorContact: string;
    vendorContact2: string;
    vendorContact2Description: string;
    vendorContact2Phone: string;
    vendorContact2PhoneExt: string;
    vendorContactDescription: string;
    vendorEmail: string;
    vendorExtraAddress: string;
    vendorFax: string;
    vendorName: string;
    vendorNumber: string;
    vendorPhone: string;
    vendorPhoneExt: string;
    vendorState: string;
    vendorStreet: string;
    vendorZipCode: string;
    version1: VersionType;
}