import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ParticipantTransaction {
    actionCode: string;
    activityDateValue: string;
    activityDateValueSpecified: boolean;
    activityDate: string | null;
    adjustmentFlagValue: number;
    adjustmentFlagValueSpecified: boolean;
    adjustmentFlag: number | null;
    agId: string;
    balanceChangeValue: number;
    balanceChangeValueSpecified: boolean;
    balanceChange: number | null;
    batchSequenceValue: number;
    batchSequenceValueSpecified: boolean;
    batchSequence: number | null;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    comment: string;
    commentFlagValue: number;
    commentFlagValueSpecified: boolean;
    commentFlag: number | null;
    consoleNumberValue: number;
    consoleNumberValueSpecified: boolean;
    consoleNumber: number | null;
    description: string;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    loanId: string;
    memberBranch: string;
    newBalanceValue: number;
    newBalanceValueSpecified: boolean;
    newBalance: number | null;
    participantNumber: string;
    participantTypeValue: number;
    participantTypeValueSpecified: boolean;
    participantType: number | null;
    poolNumber: string;
    postDateValue: string;
    postDateValueSpecified: boolean;
    postDate: string | null;
    postTimeValue: number;
    postTimeValueSpecified: boolean;
    postTime: number | null;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    sourceCode: string;
    subActionCode: string;
    userNumberValue: number;
    userNumberValueSpecified: boolean;
    userNumber: number | null;
    userOverrideValue: number;
    userOverrideValueSpecified: boolean;
    userOverride: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}