import { VersionType } from "./versionType";

export interface PreferenceFields {
    audLastLogonDate: boolean | null;
    audLastLogonTime: boolean | null;
    audioAccess: boolean | null;
    audioAccess2: boolean | null;
    audioAccessMode: boolean | null;
    audioAccessMode2: boolean | null;
    audioCallCount: boolean | null;
    audioCallMinutes: boolean | null;
    audioEnable: boolean | null;
    billPayAmount: boolean | null;
    billPayCount: boolean | null;
    billPayCountLimit: boolean | null;
    billPayLimit: boolean | null;
    billPayMax: boolean | null;
    businessFax: boolean | null;
    depAmount: boolean | null;
    depCount: boolean | null;
    depCountLimit: boolean | null;
    depLimit: boolean | null;
    depMax: boolean | null;
    emailAddrChgDate: boolean | null;
    emailAddrChgTime: boolean | null;
    emailAddress: boolean | null;
    hbCallCount: boolean | null;
    hbCallMinutes: boolean | null;
    hbEnable: boolean | null;
    hbLastLogonDate: boolean | null;
    hbLastLogonTime: boolean | null;
    hbMode: boolean | null;
    hbPassword: boolean | null;
    hbPassword2: boolean | null;
    hbPasswordMode: boolean | null;
    hbPasswordMode2: boolean | null;
    hbUsername: boolean | null;
    homeFax: boolean | null;
    interactMode: boolean | null;
    invalidPwdAttmpts: boolean | null;
    language: boolean | null;
    lastAccessChangeDate: boolean | null;
    lastHbPwChangeDate: boolean | null;
    lastLogonDate: boolean | null;
    lastLogonTime: boolean | null;
    lastTranDate: boolean | null;
    listTransactions: boolean | null;
    locator: boolean | null;
    lockCount: boolean | null;
    locked: boolean | null;
    prevHbPassword: number[];
    prevHbPasswordHash2: number[];
    prevHbPasswordHash3: number[];
    prevHbPasswordHash4: number[];
    prevHbPasswordMode: number[];
    pwdResetDate: boolean | null;
    pwdResetProbation: boolean | null;
    pwdResetRqstDate: boolean | null;
    pwdResetRqstNotice: boolean | null;
    pwdResetRqstTime: boolean | null;
    pwdResetime: boolean | null;
    recordChangeDate: boolean | null;
    reference: boolean | null;
    securityAnswer: boolean | null;
    securityQuestion: boolean | null;
    tranCodes: boolean | null;
    type: boolean | null;
    userCode: boolean | null;
    wdCashAmount: boolean | null;
    wdCashCount: boolean | null;
    wdCashCountLimit: boolean | null;
    wdCashLimit: boolean | null;
    wdCashMax: boolean | null;
    wdCheckAmount: boolean | null;
    wdCheckCount: boolean | null;
    wdCheckCountLimit: boolean | null;
    wdCheckLimit: boolean | null;
    wdCheckMax: boolean | null;
    xferAmount: boolean | null;
    xferCount: boolean | null;
    xferCountLimit: boolean | null;
    xferLimit: boolean | null;
    xferMax: boolean | null;
    version1: VersionType;
}