import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface PreferenceDefault_2 {
    audioAccess: string;
    audioAccess2: string;
    audioEnableValue: number;
    audioEnableValueSpecified: boolean;
    audioEnable: number | null;
    billPayCountLimitValue: number;
    billPayCountLimitValueSpecified: boolean;
    billPayCountLimit: number | null;
    billPayLimitValue: number;
    billPayLimitValueSpecified: boolean;
    billPayLimit: number | null;
    billPayMaxValue: number;
    billPayMaxValueSpecified: boolean;
    billPayMax: number | null;
    depCountLimitValue: number;
    depCountLimitValueSpecified: boolean;
    depCountLimit: number | null;
    depLimitValue: number;
    depLimitValueSpecified: boolean;
    depLimit: number | null;
    depMaxValue: number;
    depMaxValueSpecified: boolean;
    depMax: number | null;
    hbEnableValue: number;
    hbEnableValueSpecified: boolean;
    hbEnable: number | null;
    hbModeValue: number;
    hbModeValueSpecified: boolean;
    hbMode: number | null;
    interactModeValue: number;
    interactModeValueSpecified: boolean;
    interactMode: number | null;
    languageValue: number;
    languageValueSpecified: boolean;
    language: number | null;
    listTransactionsValue: number;
    listTransactionsValueSpecified: boolean;
    listTransactions: number | null;
    reference: string;
    tranCodes: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userCodeValue: number;
    userCodeValueSpecified: boolean;
    userCode: number | null;
    wdCashCountLimitValue: number;
    wdCashCountLimitValueSpecified: boolean;
    wdCashCountLimit: number | null;
    wdCashLimitValue: number;
    wdCashLimitValueSpecified: boolean;
    wdCashLimit: number | null;
    wdCashMaxValue: number;
    wdCashMaxValueSpecified: boolean;
    wdCashMax: number | null;
    wdCheckCountLimitValue: number;
    wdCheckCountLimitValueSpecified: boolean;
    wdCheckCountLimit: number | null;
    wdCheckLimitValue: number;
    wdCheckLimitValueSpecified: boolean;
    wdCheckLimit: number | null;
    wdCheckMaxValue: number;
    wdCheckMaxValueSpecified: boolean;
    wdCheckMax: number | null;
    xferCountLimitValue: number;
    xferCountLimitValueSpecified: boolean;
    xferCountLimit: number | null;
    xferLimitValue: number;
    xferLimitValueSpecified: boolean;
    xferLimit: number | null;
    xferMaxValue: number;
    xferMaxValueSpecified: boolean;
    xferMax: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}