import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface PreferenceDefaultFields {
    audioAccessValue: boolean;
    audioAccessValueSpecified: boolean;
    audioAccess: boolean | null;
    audioAccess2Value: boolean;
    audioAccess2ValueSpecified: boolean;
    audioAccess2: boolean | null;
    audioEnableValue: boolean;
    audioEnableValueSpecified: boolean;
    audioEnable: boolean | null;
    billPayCountLimitValue: boolean;
    billPayCountLimitValueSpecified: boolean;
    billPayCountLimit: boolean | null;
    billPayLimitValue: boolean;
    billPayLimitValueSpecified: boolean;
    billPayLimit: boolean | null;
    billPayMaxValue: boolean;
    billPayMaxValueSpecified: boolean;
    billPayMax: boolean | null;
    depCountLimitValue: boolean;
    depCountLimitValueSpecified: boolean;
    depCountLimit: boolean | null;
    depLimitValue: boolean;
    depLimitValueSpecified: boolean;
    depLimit: boolean | null;
    depMaxValue: boolean;
    depMaxValueSpecified: boolean;
    depMax: boolean | null;
    hbEnableValue: boolean;
    hbEnableValueSpecified: boolean;
    hbEnable: boolean | null;
    hbModeValue: boolean;
    hbModeValueSpecified: boolean;
    hbMode: boolean | null;
    interactModeValue: boolean;
    interactModeValueSpecified: boolean;
    interactMode: boolean | null;
    languageValue: boolean;
    languageValueSpecified: boolean;
    language: boolean | null;
    listTransactionsValue: boolean;
    listTransactionsValueSpecified: boolean;
    listTransactions: boolean | null;
    referenceValue: boolean;
    referenceValueSpecified: boolean;
    reference: boolean | null;
    tranCodesValue: boolean;
    tranCodesValueSpecified: boolean;
    tranCodes: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    userCodeValue: boolean;
    userCodeValueSpecified: boolean;
    userCode: boolean | null;
    wdCashCountLimitValue: boolean;
    wdCashCountLimitValueSpecified: boolean;
    wdCashCountLimit: boolean | null;
    wdCashLimitValue: boolean;
    wdCashLimitValueSpecified: boolean;
    wdCashLimit: boolean | null;
    wdCashMaxValue: boolean;
    wdCashMaxValueSpecified: boolean;
    wdCashMax: boolean | null;
    wdCheckCountLimitValue: boolean;
    wdCheckCountLimitValueSpecified: boolean;
    wdCheckCountLimit: boolean | null;
    wdCheckLimitValue: boolean;
    wdCheckLimitValueSpecified: boolean;
    wdCheckLimit: boolean | null;
    wdCheckMaxValue: boolean;
    wdCheckMaxValueSpecified: boolean;
    wdCheckMax: boolean | null;
    xferCountLimitValue: boolean;
    xferCountLimitValueSpecified: boolean;
    xferCountLimit: boolean | null;
    xferLimitValue: boolean;
    xferLimitValueSpecified: boolean;
    xferLimit: boolean | null;
    xferMaxValue: boolean;
    xferMaxValueSpecified: boolean;
    xferMax: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}