import { ReceivedItemDisposition } from "./receivedItemDisposition";
import { ReceivedItemFraudCode } from "./receivedItemFraudCode";
import { ReceivedItemFraudDescription } from "./receivedItemFraudDescription";
import { ReceivedItemFraudSeverity } from "./receivedItemFraudSeverity";
import { ReceivedItemFraudVendor } from "./receivedItemFraudVendor";
import { ReceivedItemResubmitDate } from "./receivedItemResubmitDate";
import { ReceivedItemReturnDate } from "./receivedItemReturnDate";
import { ReceivedItemReturnReason } from "./receivedItemReturnReason";
import { ReceivedItemTranSeqNumberAll } from "./receivedItemTranSeqNumberAll";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ReceivedItem {
    assocAccountNumber: string;
    assocId: string;
    assocIdTypeValue: number;
    assocIdTypeValueSpecified: boolean;
    assocIdType: number | null;
    bondDenominationValue: number;
    bondDenominationValueSpecified: boolean;
    bondDenomination: number | null;
    bondInterestValue: number;
    bondInterestValueSpecified: boolean;
    bondInterest: number | null;
    bondPrincipalValue: number;
    bondPrincipalValueSpecified: boolean;
    bondPrincipal: number | null;
    bondRecpCity: string;
    bondRecpName: string;
    bondRecpSsn: string;
    bondRecpState: string;
    bondRecpStreet: string;
    bondRecpZipCode: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    chargeOffDateValue: string;
    chargeOffDateValueSpecified: boolean;
    chargeOffDate: string | null;
    collectedDateValue: string;
    collectedDateValueSpecified: boolean;
    collectedDate: string | null;
    collectionDateValue: string;
    collectionDateValueSpecified: boolean;
    collectionDate: string | null;
    consoleNumberValue: number;
    consoleNumberValueSpecified: boolean;
    consoleNumber: number | null;
    disposition: ReceivedItemDisposition[];
    dispositionSpecified: boolean;
    fraudCode: ReceivedItemFraudCode[];
    fraudCodeSpecified: boolean;
    fraudDescription: ReceivedItemFraudDescription[];
    fraudDescriptionSpecified: boolean;
    fraudSeverity: ReceivedItemFraudSeverity[];
    fraudSeveritySpecified: boolean;
    fraudVendor: ReceivedItemFraudVendor[];
    fraudVendorSpecified: boolean;
    globalSequenceValue: number;
    globalSequenceValueSpecified: boolean;
    globalSequence: number | null;
    globalSequenceDateValue: string;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: string | null;
    inputSourceValue: number;
    inputSourceValueSpecified: boolean;
    inputSource: number | null;
    itcForeignItemValue: number;
    itcForeignItemValueSpecified: boolean;
    itcForeignItem: number | null;
    itcReportedValue: number;
    itcReportedValueSpecified: boolean;
    itcReported: number | null;
    itcStatusCodeValue: number;
    itcStatusCodeValueSpecified: boolean;
    itcStatusCode: number | null;
    itemAcctNumber: string;
    itemAmountValue: number;
    itemAmountValueSpecified: boolean;
    itemAmount: number | null;
    itemCheckNumber: string;
    itemId: string;
    micr1: string;
    micr2: string;
    micrAmount: string;
    micrAuxOnUs: string;
    micrEpc: string;
    micrOnUs: string;
    micrTransit: string;
    onUsValue: number;
    onUsValueSpecified: boolean;
    onUs: number | null;
    onUsAcctNumber: string;
    onUsId: string;
    onUsIdTypeValue: number;
    onUsIdTypeValueSpecified: boolean;
    onUsIdType: number | null;
    postDateValue: string;
    postDateValueSpecified: boolean;
    postDate: string | null;
    postTimeValue: number;
    postTimeValueSpecified: boolean;
    postTime: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rejectDateValue: string;
    rejectDateValueSpecified: boolean;
    rejectDate: string | null;
    reportDateValue: string;
    reportDateValueSpecified: boolean;
    reportDate: string | null;
    resubmitDate: ReceivedItemResubmitDate[];
    resubmitDateSpecified: boolean;
    returnDate: ReceivedItemReturnDate[];
    returnDateSpecified: boolean;
    returnReason: ReceivedItemReturnReason[];
    returnReasonSpecified: boolean;
    sbFlagValue: number;
    sbFlagValueSpecified: boolean;
    sbFlag: number | null;
    sbTranSequenceNumberValue: number;
    sbTranSequenceNumberValueSpecified: boolean;
    sbTranSequenceNumber: number | null;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    tranSeqNumberAll: ReceivedItemTranSeqNumberAll[];
    tranSeqNumberAllSpecified: boolean;
    tranSetId: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userNumberValue: number;
    userNumberValueSpecified: boolean;
    userNumber: number | null;
    voidDateValue: string;
    voidDateValueSpecified: boolean;
    voidDate: string | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}