import { ReceivedItemDisposition } from "./receivedItemDisposition";
import { ReceivedItemFraudCode } from "./receivedItemFraudCode";
import { ReceivedItemFraudDescription } from "./receivedItemFraudDescription";
import { ReceivedItemFraudSeverity } from "./receivedItemFraudSeverity";
import { ReceivedItemFraudVendor } from "./receivedItemFraudVendor";
import { ReceivedItemResubmitDate } from "./receivedItemResubmitDate";
import { ReceivedItemReturnDate } from "./receivedItemReturnDate";
import { ReceivedItemReturnReason } from "./receivedItemReturnReason";
import { ReceivedItemTranSeqNumberAll } from "./receivedItemTranSeqNumberAll";
import { VersionType } from "./versionType";

export interface ReceivedItem {
    assocAccountNumber: string;
    assocId: string;
    assocIdType: number | null;
    bondDenomination: number | null;
    bondInterest: number | null;
    bondPrincipal: number | null;
    bondRecpCity: string;
    bondRecpName: string;
    bondRecpSsn: string;
    bondRecpState: string;
    bondRecpStreet: string;
    bondRecpZipCode: string;
    branch: number | null;
    chargeOffDate: string | null;
    collectedDate: string | null;
    collectionDate: string | null;
    consoleNumber: number | null;
    disposition: ReceivedItemDisposition[];
    fraudCode: ReceivedItemFraudCode[];
    fraudDescription: ReceivedItemFraudDescription[];
    fraudSeverity: ReceivedItemFraudSeverity[];
    fraudVendor: ReceivedItemFraudVendor[];
    globalSequence: number | null;
    globalSequenceDate: string | null;
    inputSource: number | null;
    itcForeignItem: number | null;
    itcReported: number | null;
    itcStatusCode: number | null;
    itemAcctNumber: string;
    itemAmount: number | null;
    itemCheckNumber: string;
    itemId: string;
    micr1: string;
    micr2: string;
    micrAmount: string;
    micrAuxOnUs: string;
    micrEpc: string;
    micrOnUs: string;
    micrTransit: string;
    onUs: number | null;
    onUsAcctNumber: string;
    onUsId: string;
    onUsIdType: number | null;
    postDate: string | null;
    postTime: number | null;
    recordChangeDate: string | null;
    rejectDate: string | null;
    reportDate: string | null;
    resubmitDate: ReceivedItemResubmitDate[];
    returnDate: ReceivedItemReturnDate[];
    returnReason: ReceivedItemReturnReason[];
    sbFlag: number | null;
    sbTranSequenceNumber: number | null;
    sequenceNumber: number | null;
    status: number | null;
    tranSeqNumberAll: ReceivedItemTranSeqNumberAll[];
    tranSetId: string;
    type: number | null;
    userNumber: number | null;
    voidDate: string | null;
    version1: VersionType;
}