import { ReceivedItemDisposition_2 } from "./receivedItemDisposition_2";
import { ReceivedItemFraudCode_2 } from "./receivedItemFraudCode_2";
import { ReceivedItemFraudDescription_2 } from "./receivedItemFraudDescription_2";
import { ReceivedItemFraudSeverity_2 } from "./receivedItemFraudSeverity_2";
import { ReceivedItemFraudVendor_2 } from "./receivedItemFraudVendor_2";
import { ReceivedItemResubmitDate_2 } from "./receivedItemResubmitDate_2";
import { ReceivedItemReturnDate_2 } from "./receivedItemReturnDate_2";
import { ReceivedItemReturnReason_2 } from "./receivedItemReturnReason_2";
import { ReceivedItemTranSeqNumberAll_2 } from "./receivedItemTranSeqNumberAll_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ReceivedItem_2 {
    assocAccountNumber: string;
    assocId: string;
    assocIdTypeValue: number;
    assocIdTypeValueSpecified: boolean;
    assocIdType: number | null;
    bondDenominationValue: number;
    bondDenominationValueSpecified: boolean;
    bondDenomination: number | null;
    bondInterestValue: number;
    bondInterestValueSpecified: boolean;
    bondInterest: number | null;
    bondPrincipalValue: number;
    bondPrincipalValueSpecified: boolean;
    bondPrincipal: number | null;
    bondRecpCity: string;
    bondRecpName: string;
    bondRecpSsn: string;
    bondRecpState: string;
    bondRecpStreet: string;
    bondRecpZipCode: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    chargeOffDateValue: string | null;
    chargeOffDateValueSpecified: boolean;
    chargeOffDate: string | null;
    collectedDateValue: string | null;
    collectedDateValueSpecified: boolean;
    collectedDate: string | null;
    collectionDateValue: string | null;
    collectionDateValueSpecified: boolean;
    collectionDate: string | null;
    consoleNumberValue: number;
    consoleNumberValueSpecified: boolean;
    consoleNumber: number | null;
    disposition: ReceivedItemDisposition_2[];
    dispositionSpecified: boolean;
    fraudCode: ReceivedItemFraudCode_2[];
    fraudCodeSpecified: boolean;
    fraudDescription: ReceivedItemFraudDescription_2[];
    fraudDescriptionSpecified: boolean;
    fraudSeverity: ReceivedItemFraudSeverity_2[];
    fraudSeveritySpecified: boolean;
    fraudVendor: ReceivedItemFraudVendor_2[];
    fraudVendorSpecified: boolean;
    globalSequenceValue: number;
    globalSequenceValueSpecified: boolean;
    globalSequence: number | null;
    globalSequenceDateValue: string | null;
    globalSequenceDateValueSpecified: boolean;
    globalSequenceDate: string | null;
    inputSourceValue: number;
    inputSourceValueSpecified: boolean;
    inputSource: number | null;
    itcForeignItemValue: number;
    itcForeignItemValueSpecified: boolean;
    itcForeignItem: number | null;
    itcReportedValue: number;
    itcReportedValueSpecified: boolean;
    itcReported: number | null;
    itcStatusCodeValue: number;
    itcStatusCodeValueSpecified: boolean;
    itcStatusCode: number | null;
    itemAcctNumber: string;
    itemAmountValue: number;
    itemAmountValueSpecified: boolean;
    itemAmount: number | null;
    itemCheckNumber: string;
    itemId: string;
    micr1: string;
    micr2: string;
    micrAmount: string;
    micrAuxOnUs: string;
    micrEpc: string;
    micrOnUs: string;
    micrTransit: string;
    onUsValue: number;
    onUsValueSpecified: boolean;
    onUs: number | null;
    onUsAcctNumber: string;
    onUsId: string;
    onUsIdTypeValue: number;
    onUsIdTypeValueSpecified: boolean;
    onUsIdType: number | null;
    postDateValue: string | null;
    postDateValueSpecified: boolean;
    postDate: string | null;
    postTimeValue: number;
    postTimeValueSpecified: boolean;
    postTime: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rejectDateValue: string | null;
    rejectDateValueSpecified: boolean;
    rejectDate: string | null;
    reportDateValue: string | null;
    reportDateValueSpecified: boolean;
    reportDate: string | null;
    resubmitDate: ReceivedItemResubmitDate_2[];
    resubmitDateSpecified: boolean;
    returnDate: ReceivedItemReturnDate_2[];
    returnDateSpecified: boolean;
    returnReason: ReceivedItemReturnReason_2[];
    returnReasonSpecified: boolean;
    sbFlagValue: number;
    sbFlagValueSpecified: boolean;
    sbFlag: number | null;
    sbTranSequenceNumberValue: number;
    sbTranSequenceNumberValueSpecified: boolean;
    sbTranSequenceNumber: number | null;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    tranSeqNumberAll: ReceivedItemTranSeqNumberAll_2[];
    tranSeqNumberAllSpecified: boolean;
    tranSetId: string;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    userNumberValue: number;
    userNumberValueSpecified: boolean;
    userNumber: number | null;
    voidDateValue: string | null;
    voidDateValueSpecified: boolean;
    voidDate: string | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}