import { BitMap } from "./bitMap";
import { RegCcFederalReserveHoliday } from "./regCcFederalReserveHoliday";
import { RegCcRoutingNumberHoldDays } from "./regCcRoutingNumberHoldDays";
import { RegCcRoutingNumberPrefix } from "./regCcRoutingNumberPrefix";
import { VersionType } from "./versionType";

export interface RegCc {
    aggregateException: number | null;
    bankingDay: string | null;
    bankingDaysOption: number | null;
    branch: number | null;
    branchReference: number | null;
    branchValidCode: number | null;
    businessDays: string;
    excpWarningCodeList: BitMap;
    federalReserveHoliday: RegCcFederalReserveHoliday[];
    foreignItemHoldDays: number | null;
    holdPolicy: number | null;
    holdWarningCodeList: BitMap;
    krHoldBaseAmtOption: number | null;
    krHoldBaseOption: number | null;
    largeDepositExceptionHold: number | null;
    lastDayAvailable: number | null;
    localAggrgtExcpHoldDays: number | null;
    localExceptionHoldDays: number | null;
    localHoldDays: number | null;
    maxHoldCalendarDays: number | null;
    newAccountHoldDays: number | null;
    newAccountWarningCode: number | null;
    nextDayAvailExcpRsnList: BitMap;
    nextDayAvailable: number | null;
    nextDayDays: number | null;
    nonLocalAggrgtExcpHoldDay: number | null;
    nonLocalExceptionHoldDays: number | null;
    nonlocalHoldDays: number | null;
    repeatedNsfWarningCode: number | null;
    routingNumberHoldDays: RegCcRoutingNumberHoldDays[];
    routingNumberPrefix: RegCcRoutingNumberPrefix[];
    savingsPolicy: number | null;
    useMicrRtPrefix: boolean | null;
    version1: VersionType;
}