import { BitMap } from "./bitMap";
import { RegCcFederalReserveHoliday_2 } from "./regCcFederalReserveHoliday_2";
import { RegCcRoutingNumberHoldDays_2 } from "./regCcRoutingNumberHoldDays_2";
import { RegCcRoutingNumberPrefix_2 } from "./regCcRoutingNumberPrefix_2";
import { VersionType } from "./versionType";

export interface RegCc_2 {
    aggregateException: number | null;
    bankingDay: string | null;
    bankingDaysOption: number | null;
    branch: number | null;
    branchReference: number | null;
    branchValidCode: number | null;
    businessDays: string;
    excpWarningCodeList: BitMap;
    federalReserveHoliday: RegCcFederalReserveHoliday_2[];
    foreignItemHoldDays: number | null;
    holdPolicy: number | null;
    holdWarningCodeList: BitMap;
    krHoldBaseAmtOption: number | null;
    krHoldBaseOption: number | null;
    largeDepositExceptionHold: number | null;
    lastDayAvailable: number | null;
    localAggrgtExcpHoldDays: number | null;
    localExceptionHoldDays: number | null;
    localHoldDays: number | null;
    maxHoldCalendarDays: number | null;
    newAccountHoldDays: number | null;
    newAccountWarningCode: number | null;
    nextDayAvailExcpRsnList: BitMap;
    nextDayAvailable: number | null;
    nextDayDays: number | null;
    nonLocalAggrgtExcpHoldDay: number | null;
    nonLocalExceptionHoldDays: number | null;
    nonlocalHoldDays: number | null;
    repeatedNsfWarningCode: number | null;
    routingNumberHoldDays: RegCcRoutingNumberHoldDays_2[];
    routingNumberPrefix: RegCcRoutingNumberPrefix_2[];
    savingsPolicy: number | null;
    useMicrRtPrefix: boolean | null;
    version1: VersionType;
}