import { ReservePlanLoanList } from "./reservePlanLoanList";
import { ReservePlanTrackingList } from "./reservePlanTrackingList";
import { ReservePlanTransactionList } from "./reservePlanTransactionList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ReservePlan {
    activeValue: number;
    activeValueSpecified: boolean;
    active: number | null;
    balanceValue: number;
    balanceValueSpecified: boolean;
    balance: number | null;
    chargeOffBalanceValue: number;
    chargeOffBalanceValueSpecified: boolean;
    chargeOffBalance: number | null;
    chargeOffDaysValue: number;
    chargeOffDaysValueSpecified: boolean;
    chargeOffDays: number | null;
    chargeOffLoanCountValue: number;
    chargeOffLoanCountValueSpecified: boolean;
    chargeOffLoanCount: number | null;
    chargeOffPmtsValue: number;
    chargeOffPmtsValueSpecified: boolean;
    chargeOffPmts: number | null;
    chargebackBalanceValue: number;
    chargebackBalanceValueSpecified: boolean;
    chargebackBalance: number | null;
    chargebackCoOptionValue: number;
    chargebackCoOptionValueSpecified: boolean;
    chargebackCoOption: number | null;
    chargebackPoOptionValue: number;
    chargebackPoOptionValueSpecified: boolean;
    chargebackPoOption: number | null;
    closeDateValue: string;
    closeDateValueSpecified: boolean;
    closeDate: string | null;
    description: string;
    earlyPayoffDaysValue: number;
    earlyPayoffDaysValueSpecified: boolean;
    earlyPayoffDays: number | null;
    earlyPayoffPmtsValue: number;
    earlyPayoffPmtsValueSpecified: boolean;
    earlyPayoffPmts: number | null;
    effectiveDateValue: string;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    expirationDateValue: string;
    expirationDateValueSpecified: boolean;
    expirationDate: string | null;
    holdbackAmountValue: number;
    holdbackAmountValueSpecified: boolean;
    holdbackAmount: number | null;
    holdbackBalanceValue: number;
    holdbackBalanceValueSpecified: boolean;
    holdbackBalance: number | null;
    holdbackBalanceLsValue: number;
    holdbackBalanceLsValueSpecified: boolean;
    holdbackBalanceLs: number | null;
    holdbackPercentValue: number;
    holdbackPercentValueSpecified: boolean;
    holdbackPercent: number | null;
    id: string;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    loanBalanceSlpValue: number;
    loanBalanceSlpValueSpecified: boolean;
    loanBalanceSlp: number | null;
    loanCountValue: number;
    loanCountValueSpecified: boolean;
    loanCount: number | null;
    loanCountSlpValue: number;
    loanCountSlpValueSpecified: boolean;
    loanCountSlp: number | null;
    mbrFeeAmountValue: number;
    mbrFeeAmountValueSpecified: boolean;
    mbrFeeAmount: number | null;
    memberFeeValue: number;
    memberFeeValueSpecified: boolean;
    memberFee: number | null;
    openDateValue: string;
    openDateValueSpecified: boolean;
    openDate: string | null;
    planAvailBalanceValue: number;
    planAvailBalanceValueSpecified: boolean;
    planAvailBalance: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    recourseValue: number;
    recourseValueSpecified: boolean;
    recourse: number | null;
    reservePlanLoanList: ReservePlanLoanList;
    reservePlanTrackingList: ReservePlanTrackingList;
    reservePlanTransactionList: ReservePlanTransactionList;
    totalAmortReserveValue: number;
    totalAmortReserveValueSpecified: boolean;
    totalAmortReserve: number | null;
    totalEarnedReserveValue: number;
    totalEarnedReserveValueSpecified: boolean;
    totalEarnedReserve: number | null;
    totalLoanBalanceValue: number;
    totalLoanBalanceValueSpecified: boolean;
    totalLoanBalance: number | null;
    totalUnearnedReserveValue: number;
    totalUnearnedReserveValueSpecified: boolean;
    totalUnearnedReserve: number | null;
    totalUpFrontReserveValue: number;
    totalUpFrontReserveValueSpecified: boolean;
    totalUpFrontReserve: number | null;
    tranPurgeDateValue: string;
    tranPurgeDateValueSpecified: boolean;
    tranPurgeDate: string | null;
    ttlERsvNoChgDValue: number;
    ttlERsvNoChgDValueSpecified: boolean;
    ttlERsvNoChgD: number | null;
    ttlERsvNoClsDValue: number;
    ttlERsvNoClsDValueSpecified: boolean;
    ttlERsvNoClsD: number | null;
    ttlUeRsvNoChgDValue: number;
    ttlUeRsvNoChgDValueSpecified: boolean;
    ttlUeRsvNoChgD: number | null;
    ttlUeRsvNoClsDValue: number;
    ttlUeRsvNoClsDValueSpecified: boolean;
    ttlUeRsvNoClsD: number | null;
    ttlUfRsvNoChgDValue: number;
    ttlUfRsvNoChgDValueSpecified: boolean;
    ttlUfRsvNoChgD: number | null;
    ttlUfRsvNoClsDValue: number;
    ttlUfRsvNoClsDValueSpecified: boolean;
    ttlUfRsvNoClsD: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    unpaidUpFrontReserveValue: number;
    unpaidUpFrontReserveValueSpecified: boolean;
    unpaidUpFrontReserve: number | null;
    upFrontReserveAmtValue: number;
    upFrontReserveAmtValueSpecified: boolean;
    upFrontReserveAmt: number | null;
    upFrontReservePercentValue: number;
    upFrontReservePercentValueSpecified: boolean;
    upFrontReservePercent: number | null;
    userAmount1Value: number;
    userAmount1ValueSpecified: boolean;
    userAmount1: number | null;
    userAmount2Value: number;
    userAmount2ValueSpecified: boolean;
    userAmount2: number | null;
    userAmount3Value: number;
    userAmount3ValueSpecified: boolean;
    userAmount3: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userCode1Value: number;
    userCode1ValueSpecified: boolean;
    userCode1: number | null;
    userDate1Value: string;
    userDate1ValueSpecified: boolean;
    userDate1: string | null;
    userNumber1Value: number;
    userNumber1ValueSpecified: boolean;
    userNumber1: number | null;
    userNumber2Value: number;
    userNumber2ValueSpecified: boolean;
    userNumber2: number | null;
    userRate1Value: number;
    userRate1ValueSpecified: boolean;
    userRate1: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}