import { LoanBankruptcyPrepetitionBalSearchPagedSelectFieldsResponse } from "./loanBankruptcyPrepetitionBalSearchPagedSelectFieldsResponse";

export interface SearchLoanBankruptcyPrepetitionBalPagedSelectFieldsResponse {
    pagedResponse: LoanBankruptcyPrepetitionBalSearchPagedSelectFieldsResponse;
}