import { LoanBankruptcyPrepetitionBalSearchPagedSelectFieldsRequest } from "./loanBankruptcyPrepetitionBalSearchPagedSelectFieldsRequest";

export interface SearchLoanBankruptcyPrepetitionBalPagedSelectFields {
    request: LoanBankruptcyPrepetitionBalSearchPagedSelectFieldsRequest;
}