import { ShareCheckOrderBusCaptions } from "./shareCheckOrderBusCaptions";
import { ShareCheckOrderImprintLine } from "./shareCheckOrderImprintLine";
import { ShareCheckOrderImprintLineSize } from "./shareCheckOrderImprintLineSize";
import { ShareCheckOrderImprintUsage } from "./shareCheckOrderImprintUsage";
import { ShareCheckOrderLicense } from "./shareCheckOrderLicense";
import { ShareCheckOrderMailAddress } from "./shareCheckOrderMailAddress";
import { ShareCheckOrderOverSigLine } from "./shareCheckOrderOverSigLine";
import { ShareCheckOrderSpecialInstr } from "./shareCheckOrderSpecialInstr";
import { ShareCheckOrderSsn } from "./shareCheckOrderSsn";
import { VersionType } from "./versionType";

export interface ShareCheckOrder {
    accent: string;
    acctAddrInkColor: number | null;
    billingCode: number | null;
    binding: string;
    branch: number | null;
    busBindingStyle: number | null;
    busCaptions: ShareCheckOrderBusCaptions[];
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFont: number | null;
    imprintJustify: number | null;
    imprintLine: ShareCheckOrderImprintLine[];
    imprintLineSize: ShareCheckOrderImprintLineSize[];
    imprintPhone: string;
    imprintState: string;
    imprintUsage: ShareCheckOrderImprintUsage[];
    imprintZipCode: string;
    lastFmDate: string | null;
    lastFreeOrder: string | null;
    lastOrderDate: string | null;
    license: ShareCheckOrderLicense[];
    locator: number | null;
    mailAddress: ShareCheckOrderMailAddress[];
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLines: number | null;
    openDate: string | null;
    overSigFont: number | null;
    overSigJustify: number | null;
    overSigLine: ShareCheckOrderOverSigLine[];
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processor: number | null;
    promoNumber: string;
    quantity: number | null;
    recordChangeDate: string | null;
    rerunReason: number | null;
    shipMethod: number | null;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: ShareCheckOrderSpecialInstr[];
    ssn: ShareCheckOrderSsn[];
    startNumber: number | null;
    status: number | null;
    statusDate: string | null;
    taxExemptCode: number | null;
    titleInkColor: number | null;
    userId: number | null;
    version1: VersionType;
}