import { ShareCheckOrderBusCaptions } from "./shareCheckOrderBusCaptions";
import { ShareCheckOrderImprintLine } from "./shareCheckOrderImprintLine";
import { ShareCheckOrderImprintLineSize } from "./shareCheckOrderImprintLineSize";
import { ShareCheckOrderImprintUsage } from "./shareCheckOrderImprintUsage";
import { ShareCheckOrderLicense } from "./shareCheckOrderLicense";
import { ShareCheckOrderMailAddress } from "./shareCheckOrderMailAddress";
import { ShareCheckOrderOverSigLine } from "./shareCheckOrderOverSigLine";
import { ShareCheckOrderSpecialInstr } from "./shareCheckOrderSpecialInstr";
import { ShareCheckOrderSsn } from "./shareCheckOrderSsn";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ShareCheckOrder {
    accent: string;
    acctAddrInkColorValue: number;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: number | null;
    billingCodeValue: number;
    billingCodeValueSpecified: boolean;
    billingCode: number | null;
    binding: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    busBindingStyleValue: number;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: number | null;
    busCaptions: ShareCheckOrderBusCaptions[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: number;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShippingValue: number;
    chargeShippingValueSpecified: boolean;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkTypeValue: number;
    checkTypeValueSpecified: boolean;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColorValue: number;
    cutInkColorValueSpecified: boolean;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFontValue: number;
    imprintFontValueSpecified: boolean;
    imprintFont: number | null;
    imprintJustifyValue: number;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: number | null;
    imprintLine: ShareCheckOrderImprintLine[];
    imprintLineSpecified: boolean;
    imprintLineSize: ShareCheckOrderImprintLineSize[];
    imprintLineSizeSpecified: boolean;
    imprintPhone: string;
    imprintState: string;
    imprintUsage: ShareCheckOrderImprintUsage[];
    imprintUsageSpecified: boolean;
    imprintZipCode: string;
    lastFmDateValue: string;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    lastFreeOrderValue: string;
    lastFreeOrderValueSpecified: boolean;
    lastFreeOrder: string | null;
    lastOrderDateValue: string;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: string | null;
    license: ShareCheckOrderLicense[];
    licenseSpecified: boolean;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    mailAddress: ShareCheckOrderMailAddress[];
    mailAddressSpecified: boolean;
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLinesValue: number;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: number | null;
    openDateValue: string;
    openDateValueSpecified: boolean;
    openDate: string | null;
    overSigFontValue: number;
    overSigFontValueSpecified: boolean;
    overSigFont: number | null;
    overSigJustifyValue: number;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: number | null;
    overSigLine: ShareCheckOrderOverSigLine[];
    overSigLineSpecified: boolean;
    overSigLineSizeValue: number;
    overSigLineSizeValueSpecified: boolean;
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processorValue: number;
    processorValueSpecified: boolean;
    processor: number | null;
    promoNumber: string;
    quantityValue: number;
    quantityValueSpecified: boolean;
    quantity: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rerunReasonValue: number;
    rerunReasonValueSpecified: boolean;
    rerunReason: number | null;
    shipMethodValue: number;
    shipMethodValueSpecified: boolean;
    shipMethod: number | null;
    shipToValue: number;
    shipToValueSpecified: boolean;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: ShareCheckOrderSpecialInstr[];
    specialInstrSpecified: boolean;
    ssn: ShareCheckOrderSsn[];
    ssnSpecified: boolean;
    startNumberValue: number;
    startNumberValueSpecified: boolean;
    startNumber: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    statusDateValue: string;
    statusDateValueSpecified: boolean;
    statusDate: string | null;
    taxExemptCodeValue: number;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: number | null;
    titleInkColorValue: number;
    titleInkColorValueSpecified: boolean;
    titleInkColor: number | null;
    userIdValue: number;
    userIdValueSpecified: boolean;
    userId: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}