import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ShareFields {
    activityDateValue: boolean;
    activityDateValueSpecified: boolean;
    activityDate: boolean | null;
    alternateAddress: number[];
    alternateAddressSpecified: boolean;
    alternateNameLocatorValue: boolean;
    alternateNameLocatorValueSpecified: boolean;
    alternateNameLocator: boolean | null;
    alternateNameTypeValue: boolean;
    alternateNameTypeValueSpecified: boolean;
    alternateNameType: boolean | null;
    alternatePhone: number[];
    alternatePhoneSpecified: boolean;
    amortizationSchdValue: boolean;
    amortizationSchdValueSpecified: boolean;
    amortizationSchd: boolean | null;
    amortizationSchdTypeValue: boolean;
    amortizationSchdTypeValueSpecified: boolean;
    amortizationSchdType: boolean | null;
    analysisGroupPrimaryAcctValue: boolean;
    analysisGroupPrimaryAcctValueSpecified: boolean;
    analysisGroupPrimaryAcct: boolean | null;
    analysisGroupPrimaryIdValue: boolean;
    analysisGroupPrimaryIdValueSpecified: boolean;
    analysisGroupPrimaryId: boolean | null;
    analysisPmtAcctValue: boolean;
    analysisPmtAcctValueSpecified: boolean;
    analysisPmtAcct: boolean | null;
    analysisPmtIdTypeValue: boolean;
    analysisPmtIdTypeValueSpecified: boolean;
    analysisPmtIdType: boolean | null;
    analysisPmtSlIdValue: boolean;
    analysisPmtSlIdValueSpecified: boolean;
    analysisPmtSlId: boolean | null;
    authFeeOption: number[];
    authFeeOptionSpecified: boolean;
    availableBalanceValue: boolean;
    availableBalanceValueSpecified: boolean;
    availableBalance: boolean | null;
    balanceValue: boolean;
    balanceValueSpecified: boolean;
    balance: boolean | null;
    bondIntLastYearValue: boolean;
    bondIntLastYearValueSpecified: boolean;
    bondIntLastYear: boolean | null;
    bondIntYtdValue: boolean;
    bondIntYtdValueSpecified: boolean;
    bondIntYtd: boolean | null;
    branchValue: boolean;
    branchValueSpecified: boolean;
    branch: boolean | null;
    bumpEffectiveDateValue: boolean;
    bumpEffectiveDateValueSpecified: boolean;
    bumpEffectiveDate: boolean | null;
    bumpExpirationDateValue: boolean;
    bumpExpirationDateValueSpecified: boolean;
    bumpExpirationDate: boolean | null;
    bumpRateValue: boolean;
    bumpRateValueSpecified: boolean;
    bumpRate: boolean | null;
    callItemSchdValue: boolean;
    callItemSchdValueSpecified: boolean;
    callItemSchd: boolean | null;
    callItemSchdTypeValue: boolean;
    callItemSchdTypeValueSpecified: boolean;
    callItemSchdType: boolean | null;
    cappedFeesAmountCapValue: boolean;
    cappedFeesAmountCapValueSpecified: boolean;
    cappedFeesAmountCap: boolean | null;
    cappedFeesAmtPeriodValue: boolean;
    cappedFeesAmtPeriodValueSpecified: boolean;
    cappedFeesAmtPeriod: boolean | null;
    cappedFeesCntPeriodValue: boolean;
    cappedFeesCntPeriodValueSpecified: boolean;
    cappedFeesCntPeriod: boolean | null;
    cappedFeesCountCapValue: boolean;
    cappedFeesCountCapValueSpecified: boolean;
    cappedFeesCountCap: boolean | null;
    cddivAccrLastYrValue: boolean;
    cddivAccrLastYrValueSpecified: boolean;
    cddivAccrLastYr: boolean | null;
    cddivAccrYtdValue: boolean;
    cddivAccrYtdValueSpecified: boolean;
    cddivAccrYtd: boolean | null;
    certificateNumberValue: boolean;
    certificateNumberValueSpecified: boolean;
    certificateNumber: boolean | null;
    chapter4WithheldLstYrValue: boolean;
    chapter4WithheldLstYrValueSpecified: boolean;
    chapter4WithheldLstYr: boolean | null;
    chapter4WithheldYtdValue: boolean;
    chapter4WithheldYtdValueSpecified: boolean;
    chapter4WithheldYtd: boolean | null;
    chapter4WithholdingCodeValue: boolean;
    chapter4WithholdingCodeValueSpecified: boolean;
    chapter4WithholdingCode: boolean | null;
    chargeOffAmountValue: boolean;
    chargeOffAmountValueSpecified: boolean;
    chargeOffAmount: boolean | null;
    chargeOffDateValue: boolean;
    chargeOffDateValueSpecified: boolean;
    chargeOffDate: boolean | null;
    chargeOffTypeValue: boolean;
    chargeOffTypeValueSpecified: boolean;
    chargeOffType: boolean | null;
    checkDigitsValue: boolean;
    checkDigitsValueSpecified: boolean;
    checkDigits: boolean | null;
    closeDateValue: boolean;
    closeDateValueSpecified: boolean;
    closeDate: boolean | null;
    corporateUserTransferCodeValue: boolean;
    corporateUserTransferCodeValueSpecified: boolean;
    corporateUserTransferCode: boolean | null;
    courtesyFeeLyValue: boolean;
    courtesyFeeLyValueSpecified: boolean;
    courtesyFeeLy: boolean | null;
    courtesyFeeMtdValue: boolean;
    courtesyFeeMtdValueSpecified: boolean;
    courtesyFeeMtd: boolean | null;
    courtesyFeeYtdValue: boolean;
    courtesyFeeYtdValueSpecified: boolean;
    courtesyFeeYtd: boolean | null;
    courtesyPayLastYearValue: boolean;
    courtesyPayLastYearValueSpecified: boolean;
    courtesyPayLastYear: boolean | null;
    courtesyPayMonthToDateValue: boolean;
    courtesyPayMonthToDateValueSpecified: boolean;
    courtesyPayMonthToDate: boolean | null;
    courtesyPayYtdValue: boolean;
    courtesyPayYtdValueSpecified: boolean;
    courtesyPayYtd: boolean | null;
    createdAtBranchValue: boolean;
    createdAtBranchValueSpecified: boolean;
    createdAtBranch: boolean | null;
    createdByUserValue: boolean;
    createdByUserValueSpecified: boolean;
    createdByUser: boolean | null;
    creditReportCommentValue: boolean;
    creditReportCommentValueSpecified: boolean;
    creditReportComment: boolean | null;
    creditReportComplianceValue: boolean;
    creditReportComplianceValueSpecified: boolean;
    creditReportCompliance: boolean | null;
    creditReportConsumerInfoValue: boolean;
    creditReportConsumerInfoValueSpecified: boolean;
    creditReportConsumerInfo: boolean | null;
    creditReportConsumerInfoDateValue: boolean;
    creditReportConsumerInfoDateValueSpecified: boolean;
    creditReportConsumerInfoDate: boolean | null;
    creditReportLastStatusValue: boolean;
    creditReportLastStatusValueSpecified: boolean;
    creditReportLastStatus: boolean | null;
    creditReportNumberValue: boolean;
    creditReportNumberValueSpecified: boolean;
    creditReportNumber: boolean | null;
    creditReportOccurDateValue: boolean;
    creditReportOccurDateValueSpecified: boolean;
    creditReportOccurDate: boolean | null;
    creditReportOriginalAmountRptdValue: boolean;
    creditReportOriginalAmountRptdValueSpecified: boolean;
    creditReportOriginalAmountRptd: boolean | null;
    creditReportingCodeValue: boolean;
    creditReportingCodeValueSpecified: boolean;
    creditReportingCode: boolean | null;
    cuTotalsUseCodeValue: boolean;
    cuTotalsUseCodeValueSpecified: boolean;
    cuTotalsUseCode: boolean | null;
    currDivPayableValue: boolean;
    currDivPayableValueSpecified: boolean;
    currDivPayable: boolean | null;
    currMonthPaidDivValue: boolean;
    currMonthPaidDivValueSpecified: boolean;
    currMonthPaidDiv: boolean | null;
    descriptionValue: boolean;
    descriptionValueSpecified: boolean;
    description: boolean | null;
    divAccrualValue: boolean;
    divAccrualValueSpecified: boolean;
    divAccrual: boolean | null;
    divAccrualDateValue: boolean;
    divAccrualDateValueSpecified: boolean;
    divAccrualDate: boolean | null;
    divDisbUpdtActvtyDValue: boolean;
    divDisbUpdtActvtyDValueSpecified: boolean;
    divDisbUpdtActvtyD: boolean | null;
    divFromOpenValue: boolean;
    divFromOpenValueSpecified: boolean;
    divFromOpen: boolean | null;
    divLastYearValue: boolean;
    divLastYearValueSpecified: boolean;
    divLastYear: boolean | null;
    divPeriodBalDaysValue: boolean;
    divPeriodBalDaysValueSpecified: boolean;
    divPeriodBalDays: boolean | null;
    divPeriodStartValue: boolean;
    divPeriodStartValueSpecified: boolean;
    divPeriodStart: boolean | null;
    divPostCodeValue: boolean;
    divPostCodeValueSpecified: boolean;
    divPostCode: boolean | null;
    divRateValue: boolean;
    divRateValueSpecified: boolean;
    divRate: boolean | null;
    divTypeValue: boolean;
    divTypeValueSpecified: boolean;
    divType: boolean | null;
    divYtdValue: boolean;
    divYtdValueSpecified: boolean;
    divYtd: boolean | null;
    dividendDueValue: boolean;
    dividendDueValueSpecified: boolean;
    dividendDue: boolean | null;
    dividendRateMarginValue: boolean;
    dividendRateMarginValueSpecified: boolean;
    dividendRateMargin: boolean | null;
    dividendRateMarginSignValue: boolean;
    dividendRateMarginSignValueSpecified: boolean;
    dividendRateMarginSign: boolean | null;
    dividendRateMaxValue: boolean;
    dividendRateMaxValueSpecified: boolean;
    dividendRateMax: boolean | null;
    dividendRateMinValue: boolean;
    dividendRateMinValueSpecified: boolean;
    dividendRateMin: boolean | null;
    dividendRatePeriodDateValue: boolean;
    dividendRatePeriodDateValueSpecified: boolean;
    dividendRatePeriodDate: boolean | null;
    dividendRatePeriodFreqValue: boolean;
    dividendRatePeriodFreqValueSpecified: boolean;
    dividendRatePeriodFreq: boolean | null;
    escrowLastYearValue: boolean;
    escrowLastYearValueSpecified: boolean;
    escrowLastYear: boolean | null;
    escrowYtdValue: boolean;
    escrowYtdValueSpecified: boolean;
    escrowYtd: boolean | null;
    escrowedLoanIdValue: boolean;
    escrowedLoanIdValueSpecified: boolean;
    escrowedLoanId: boolean | null;
    extAchXfrDailyLimitInValue: boolean;
    extAchXfrDailyLimitInValueSpecified: boolean;
    extAchXfrDailyLimitIn: boolean | null;
    extAchXfrDailyLimitOutValue: boolean;
    extAchXfrDailyLimitOutValueSpecified: boolean;
    extAchXfrDailyLimitOut: boolean | null;
    feeCount: number[];
    feeCountSpecified: boolean;
    feeExemptCrtsyBalValue: boolean;
    feeExemptCrtsyBalValueSpecified: boolean;
    feeExemptCrtsyBal: boolean | null;
    idValue: boolean;
    idValueSpecified: boolean;
    id: boolean | null;
    insuranceBalanceAge: number[];
    insuranceBalanceAgeSpecified: boolean;
    insuranceMaximumValue: boolean;
    insuranceMaximumValueSpecified: boolean;
    insuranceMaximum: boolean | null;
    insuranceTypeValue: boolean;
    insuranceTypeValueSpecified: boolean;
    insuranceType: boolean | null;
    irs1042SUfidValue: boolean;
    irs1042SUfidValueSpecified: boolean;
    irs1042SUfid: boolean | null;
    irsCodeValue: boolean;
    irsCodeValueSpecified: boolean;
    irsCode: boolean | null;
    irsPlanValue: boolean;
    irsPlanValueSpecified: boolean;
    irsPlan: boolean | null;
    lastAccrualUpdateDateValue: boolean;
    lastAccrualUpdateDateValueSpecified: boolean;
    lastAccrualUpdateDate: boolean | null;
    lastCrReportDateValue: boolean;
    lastCrReportDateValueSpecified: boolean;
    lastCrReportDate: boolean | null;
    lastDirectDepAmtValue: boolean;
    lastDirectDepAmtValueSpecified: boolean;
    lastDirectDepAmt: boolean | null;
    lastDirectDepDateValue: boolean;
    lastDirectDepDateValueSpecified: boolean;
    lastDirectDepDate: boolean | null;
    lastDivAmountValue: boolean;
    lastDivAmountValueSpecified: boolean;
    lastDivAmount: boolean | null;
    lastDivDateValue: boolean;
    lastDivDateValueSpecified: boolean;
    lastDivDate: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    lastPurgeDateValue: boolean;
    lastPurgeDateValueSpecified: boolean;
    lastPurgeDate: boolean | null;
    lastTranDateValue: boolean;
    lastTranDateValueSpecified: boolean;
    lastTranDate: boolean | null;
    ledgerAccrualValue: boolean;
    ledgerAccrualValueSpecified: boolean;
    ledgerAccrual: boolean | null;
    ledgerAccrualDateValue: boolean;
    ledgerAccrualDateValueSpecified: boolean;
    ledgerAccrualDate: boolean | null;
    loanPaymentHoldValue: boolean;
    loanPaymentHoldValueSpecified: boolean;
    loanPaymentHold: boolean | null;
    maturityDateValue: boolean;
    maturityDateValueSpecified: boolean;
    maturityDate: boolean | null;
    maturityPostCodeValue: boolean;
    maturityPostCodeValueSpecified: boolean;
    maturityPostCode: boolean | null;
    mcDivLastYearValue: boolean;
    mcDivLastYearValueSpecified: boolean;
    mcDivLastYear: boolean | null;
    mcDivYtdValue: boolean;
    mcDivYtdValueSpecified: boolean;
    mcDivYtd: boolean | null;
    memberBranchSupportValue: boolean;
    memberBranchSupportValueSpecified: boolean;
    memberBranchSupport: boolean | null;
    memberUserTransferCodeValue: boolean;
    memberUserTransferCodeValueSpecified: boolean;
    memberUserTransferCode: boolean | null;
    micrAcctNumberValue: boolean;
    micrAcctNumberValueSpecified: boolean;
    micrAcctNumber: boolean | null;
    minimumBalanceValue: boolean;
    minimumBalanceValueSpecified: boolean;
    minimumBalance: boolean | null;
    minimumDepositValue: boolean;
    minimumDepositValueSpecified: boolean;
    minimumDeposit: boolean | null;
    minimumWithdrawalValue: boolean;
    minimumWithdrawalValueSpecified: boolean;
    minimumWithdrawal: boolean | null;
    mtdAccruedDivsValue: boolean;
    mtdAccruedDivsValueSpecified: boolean;
    mtdAccruedDivs: boolean | null;
    mtdEarnedDivsValue: boolean;
    mtdEarnedDivsValueSpecified: boolean;
    mtdEarnedDivs: boolean | null;
    mtdPaidDivsValue: boolean;
    mtdPaidDivsValueSpecified: boolean;
    mtdPaidDivs: boolean | null;
    mtdPriorRateAccrualValue: boolean;
    mtdPriorRateAccrualValueSpecified: boolean;
    mtdPriorRateAccrual: boolean | null;
    negativeBalanceDateValue: boolean;
    negativeBalanceDateValueSpecified: boolean;
    negativeBalanceDate: boolean | null;
    negativeBalanceNoticeDateValue: boolean;
    negativeBalanceNoticeDateValueSpecified: boolean;
    negativeBalanceNoticeDate: boolean | null;
    negativeBalanceNoticeNumberValue: boolean;
    negativeBalanceNoticeNumberValueSpecified: boolean;
    negativeBalanceNoticeNumber: boolean | null;
    negativeBalanceNoticeTypeValue: boolean;
    negativeBalanceNoticeTypeValueSpecified: boolean;
    negativeBalanceNoticeType: boolean | null;
    nicknameValue: boolean;
    nicknameValueSpecified: boolean;
    nickname: boolean | null;
    nsfFeeLyValue: boolean;
    nsfFeeLyValueSpecified: boolean;
    nsfFeeLy: boolean | null;
    nsfFeeMtdValue: boolean;
    nsfFeeMtdValueSpecified: boolean;
    nsfFeeMtd: boolean | null;
    nsfFeeYtdValue: boolean;
    nsfFeeYtdValueSpecified: boolean;
    nsfFeeYtd: boolean | null;
    nsfLastYearValue: boolean;
    nsfLastYearValueSpecified: boolean;
    nsfLastYear: boolean | null;
    nsfMonthToDateValue: boolean;
    nsfMonthToDateValueSpecified: boolean;
    nsfMonthToDate: boolean | null;
    nsfYtdValue: boolean;
    nsfYtdValueSpecified: boolean;
    nsfYtd: boolean | null;
    odtAuthFeeSrcCodeList: number[];
    odtAuthFeeSrcCodeListSpecified: boolean;
    openDateValue: boolean;
    openDateValueSpecified: boolean;
    openDate: boolean | null;
    originalBalanceValue: boolean;
    originalBalanceValueSpecified: boolean;
    originalBalance: boolean | null;
    originalDepositValue: boolean;
    originalDepositValueSpecified: boolean;
    originalDeposit: boolean | null;
    originalDepositDateValue: boolean;
    originalDepositDateValueSpecified: boolean;
    originalDepositDate: boolean | null;
    overdraftFeeLastYrValue: boolean;
    overdraftFeeLastYrValueSpecified: boolean;
    overdraftFeeLastYr: boolean | null;
    overdraftFeeYtdValue: boolean;
    overdraftFeeYtdValueSpecified: boolean;
    overdraftFeeYtd: boolean | null;
    overdraftToleranceValue: boolean;
    overdraftToleranceValueSpecified: boolean;
    overdraftTolerance: boolean | null;
    payeeLine: number[];
    payeeLineSpecified: boolean;
    payeeNameLocatorValue: boolean;
    payeeNameLocatorValueSpecified: boolean;
    payeeNameLocator: boolean | null;
    payeeNameTypeValue: boolean;
    payeeNameTypeValueSpecified: boolean;
    payeeNameType: boolean | null;
    payeePhone: number[];
    payeePhoneSpecified: boolean;
    penaltyLastYearValue: boolean;
    penaltyLastYearValueSpecified: boolean;
    penaltyLastYear: boolean | null;
    penaltyTypeValue: boolean;
    penaltyTypeValueSpecified: boolean;
    penaltyType: boolean | null;
    penaltyYtdValue: boolean;
    penaltyYtdValueSpecified: boolean;
    penaltyYtd: boolean | null;
    periodicCapValue: boolean;
    periodicCapValueSpecified: boolean;
    periodicCap: boolean | null;
    periodicStartRateValue: boolean;
    periodicStartRateValueSpecified: boolean;
    periodicStartRate: boolean | null;
    positivePayDraftValue: boolean;
    positivePayDraftValueSpecified: boolean;
    positivePayDraft: boolean | null;
    preMthDivAccrued: number[];
    preMthDivAccruedSpecified: boolean;
    preMthDivEarned: number[];
    preMthDivEarnedSpecified: boolean;
    preMthDivPaid: number[];
    preMthDivPaidSpecified: boolean;
    putItemSchdValue: boolean;
    putItemSchdValueSpecified: boolean;
    putItemSchd: boolean | null;
    putItemSchdTypeValue: boolean;
    putItemSchdTypeValueSpecified: boolean;
    putItemSchdType: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    referenceValue: boolean;
    referenceValueSpecified: boolean;
    reference: boolean | null;
    regDCheckCountValue: boolean;
    regDCheckCountValueSpecified: boolean;
    regDCheckCount: boolean | null;
    regDCtrStartDayValue: boolean;
    regDCtrStartDayValueSpecified: boolean;
    regDCtrStartDay: boolean | null;
    regDTransferCountValue: boolean;
    regDTransferCountValueSpecified: boolean;
    regDTransferCount: boolean | null;
    regECountValue: boolean;
    regECountValueSpecified: boolean;
    regECount: boolean | null;
    renewShareTypeValue: boolean;
    renewShareTypeValueSpecified: boolean;
    renewShareType: boolean | null;
    renewTermFreqValue: boolean;
    renewTermFreqValueSpecified: boolean;
    renewTermFreq: boolean | null;
    renewTermPeriodValue: boolean;
    renewTermPeriodValueSpecified: boolean;
    renewTermPeriod: boolean | null;
    service: number[];
    serviceSpecified: boolean;
    shareCodeValue: boolean;
    shareCodeValueSpecified: boolean;
    shareCode: boolean | null;
    stateWithholdingCodeValue: boolean;
    stateWithholdingCodeValueSpecified: boolean;
    stateWithholdingCode: boolean | null;
    stateWithholdingLastQtrValue: boolean;
    stateWithholdingLastQtrValueSpecified: boolean;
    stateWithholdingLastQtr: boolean | null;
    stateWithholdingLastYearValue: boolean;
    stateWithholdingLastYearValueSpecified: boolean;
    stateWithholdingLastYear: boolean | null;
    stateWithholdingQtdValue: boolean;
    stateWithholdingQtdValueSpecified: boolean;
    stateWithholdingQtd: boolean | null;
    stateWithholdingYtdValue: boolean;
    stateWithholdingYtdValueSpecified: boolean;
    stateWithholdingYtd: boolean | null;
    statementDateValue: boolean;
    statementDateValueSpecified: boolean;
    statementDate: boolean | null;
    statementGroupValue: boolean;
    statementGroupValueSpecified: boolean;
    statementGroup: boolean | null;
    statementMailCodeValue: boolean;
    statementMailCodeValueSpecified: boolean;
    statementMailCode: boolean | null;
    statementPrevDateValue: boolean;
    statementPrevDateValueSpecified: boolean;
    statementPrevDate: boolean | null;
    sweepBalanceTypeValue: boolean;
    sweepBalanceTypeValueSpecified: boolean;
    sweepBalanceType: boolean | null;
    sweepPriorityValue: boolean;
    sweepPriorityValueSpecified: boolean;
    sweepPriority: boolean | null;
    sweepTargetMaximumValue: boolean;
    sweepTargetMaximumValueSpecified: boolean;
    sweepTargetMaximum: boolean | null;
    sweepTargetMinimumValue: boolean;
    sweepTargetMinimumValueSpecified: boolean;
    sweepTargetMinimum: boolean | null;
    termFrequencyValue: boolean;
    termFrequencyValueSpecified: boolean;
    termFrequency: boolean | null;
    termPeriodValue: boolean;
    termPeriodValueSpecified: boolean;
    termPeriod: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    unpaidFeeLastYearValue: boolean;
    unpaidFeeLastYearValueSpecified: boolean;
    unpaidFeeLastYear: boolean | null;
    unpaidFeeYtdValue: boolean;
    unpaidFeeYtdValueSpecified: boolean;
    unpaidFeeYtd: boolean | null;
    userAmount1Value: boolean;
    userAmount1ValueSpecified: boolean;
    userAmount1: boolean | null;
    userAmount2Value: boolean;
    userAmount2ValueSpecified: boolean;
    userAmount2: boolean | null;
    userChar1Value: boolean;
    userChar1ValueSpecified: boolean;
    userChar1: boolean | null;
    userChar2Value: boolean;
    userChar2ValueSpecified: boolean;
    userChar2: boolean | null;
    userChar3Value: boolean;
    userChar3ValueSpecified: boolean;
    userChar3: boolean | null;
    userChar4Value: boolean;
    userChar4ValueSpecified: boolean;
    userChar4: boolean | null;
    userDate1Value: boolean;
    userDate1ValueSpecified: boolean;
    userDate1: boolean | null;
    userDate2Value: boolean;
    userDate2ValueSpecified: boolean;
    userDate2: boolean | null;
    warningCode: number[];
    warningCodeSpecified: boolean;
    warningExpiration: number[];
    warningExpirationSpecified: boolean;
    withdrawalCountValue: boolean;
    withdrawalCountValueSpecified: boolean;
    withdrawalCount: boolean | null;
    withdrawalFeeCountValue: boolean;
    withdrawalFeeCountValueSpecified: boolean;
    withdrawalFeeCount: boolean | null;
    withdrawalFeeTypeValue: boolean;
    withdrawalFeeTypeValueSpecified: boolean;
    withdrawalFeeType: boolean | null;
    withdrawalLimitValue: boolean;
    withdrawalLimitValueSpecified: boolean;
    withdrawalLimit: boolean | null;
    withdrawnFromOpenValue: boolean;
    withdrawnFromOpenValueSpecified: boolean;
    withdrawnFromOpen: boolean | null;
    withholdingCodeValue: boolean;
    withholdingCodeValueSpecified: boolean;
    withholdingCode: boolean | null;
    withholdingLastYearValue: boolean;
    withholdingLastYearValueSpecified: boolean;
    withholdingLastYear: boolean | null;
    withholdingYtdValue: boolean;
    withholdingYtdValueSpecified: boolean;
    withholdingYtd: boolean | null;
    xfrLastYearValue: boolean;
    xfrLastYearValueSpecified: boolean;
    xfrLastYear: boolean | null;
    xfrMonthToDateValue: boolean;
    xfrMonthToDateValueSpecified: boolean;
    xfrMonthToDate: boolean | null;
    xfrYtdValue: boolean;
    xfrYtdValueSpecified: boolean;
    xfrYtd: boolean | null;
    yearEndBalanceValue: boolean;
    yearEndBalanceValueSpecified: boolean;
    yearEndBalance: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}