import { ShareDefaultAuthFeeOption_2 } from "./shareDefaultAuthFeeOption_2";
import { ShareDefaultOdtAuthFeeSrcCodeList_2 } from "./shareDefaultOdtAuthFeeSrcCodeList_2";
import { ShareDefaultService_2 } from "./shareDefaultService_2";
import { ShareDefaultWarningCode_2 } from "./shareDefaultWarningCode_2";
import { VersionType } from "./versionType";

export interface ShareDefault_2 {
    amortizationSchd: number | null;
    amortizationSchdType: number | null;
    authFeeOption: ShareDefaultAuthFeeOption_2[];
    bumpEffectiveDate: string | null;
    bumpExpirationDate: string | null;
    bumpRate: number | null;
    callItemSchd: number | null;
    callItemSchdType: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesCountCap: number | null;
    certificateNumber: string;
    chapter4WithholdingCode: number | null;
    checkDigits: string;
    closeDate: string | null;
    corporateUserTransferCode: number | null;
    creditReportingCode: number | null;
    cuTotalsUseCode: number | null;
    description: string;
    divDisbUpdtActvtyD: number | null;
    divPostCode: number | null;
    divRate: number | null;
    divType: number | null;
    dividendRateMargin: number | null;
    dividendRateMarginSign: number | null;
    dividendRateMax: number | null;
    dividendRateMin: number | null;
    dividendRatePeriodDate: string | null;
    dividendRatePeriodFreq: number | null;
    extAchXfrDailyLimitIn: number | null;
    extAchXfrDailyLimitOut: number | null;
    insuranceMaximum: number | null;
    insuranceType: number | null;
    irsCode: number | null;
    irsPlan: number | null;
    maturityDate: string | null;
    maturityPostCode: number | null;
    memberBranchSupport: number | null;
    memberUserTransferCode: number | null;
    minimumBalance: number | null;
    minimumDeposit: number | null;
    minimumWithdrawal: number | null;
    negativeBalanceNoticeNumber: number | null;
    negativeBalanceNoticeType: number | null;
    nickname: string;
    odtAuthFeeSrcCodeList: ShareDefaultOdtAuthFeeSrcCodeList_2[];
    overdraftTolerance: number | null;
    penaltyType: number | null;
    periodicCap: number | null;
    periodicStartRate: number | null;
    putItemSchd: number | null;
    putItemSchdType: number | null;
    reference: string;
    regDCtrStartDay: number | null;
    renewShareType: number | null;
    renewTermFreq: number | null;
    renewTermPeriod: number | null;
    service: ShareDefaultService_2[];
    shareCode: number | null;
    shareType: number | null;
    stateWithholdingCode: number | null;
    statementGroup: number | null;
    statementMailCode: number | null;
    sweepBalanceType: number | null;
    sweepPriority: number | null;
    sweepTargetMaximum: number | null;
    sweepTargetMinimum: number | null;
    termFrequency: number | null;
    termPeriod: number | null;
    type: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    warningCode: ShareDefaultWarningCode_2[];
    withdrawalFeeType: number | null;
    withdrawalLimit: number | null;
    withholdingCode: number | null;
    version1: VersionType;
}