import { ShareAlternateAddress_2 } from "./shareAlternateAddress_2";
import { ShareAlternatePhone_2 } from "./shareAlternatePhone_2";
import { ShareAuthFeeOption_2 } from "./shareAuthFeeOption_2";
import { ShareFeeCount_2 } from "./shareFeeCount_2";
import { ShareInsuranceBalanceAge_2 } from "./shareInsuranceBalanceAge_2";
import { ShareOdtAuthFeeSrcCodeList_2 } from "./shareOdtAuthFeeSrcCodeList_2";
import { SharePayeeLine_2 } from "./sharePayeeLine_2";
import { SharePayeePhone_2 } from "./sharePayeePhone_2";
import { SharePreMthDivAccrued_2 } from "./sharePreMthDivAccrued_2";
import { SharePreMthDivEarned_2 } from "./sharePreMthDivEarned_2";
import { SharePreMthDivPaid_2 } from "./sharePreMthDivPaid_2";
import { ShareService_2 } from "./shareService_2";
import { ShareWarningCode_2 } from "./shareWarningCode_2";
import { ShareWarningExpiration_2 } from "./shareWarningExpiration_2";
import { VersionType } from "./versionType";

export interface Share_2 {
    activityDate: string | null;
    alternateAddress: ShareAlternateAddress_2[];
    alternateNameLocator: number | null;
    alternateNameType: number | null;
    alternatePhone: ShareAlternatePhone_2[];
    amortizationSchd: number | null;
    amortizationSchdType: number | null;
    analysisGroupPrimaryAcct: string;
    analysisGroupPrimaryId: string;
    analysisPmtAcct: string;
    analysisPmtIdType: number | null;
    analysisPmtSlId: string;
    authFeeOption: ShareAuthFeeOption_2[];
    availableBalance: number | null;
    balance: number | null;
    bondIntLastYear: number | null;
    bondIntYtd: number | null;
    branch: number | null;
    bumpEffectiveDate: string | null;
    bumpExpirationDate: string | null;
    bumpRate: number | null;
    callItemSchd: number | null;
    callItemSchdType: number | null;
    cappedFeesAmountCap: number | null;
    cappedFeesAmtPeriod: number | null;
    cappedFeesCntPeriod: number | null;
    cappedFeesCountCap: number | null;
    cddivAccrLastYr: number | null;
    cddivAccrYtd: number | null;
    certificateNumber: string;
    chapter4WithheldLstYr: number | null;
    chapter4WithheldYtd: number | null;
    chapter4WithholdingCode: number | null;
    chargeOffAmount: number | null;
    chargeOffDate: string | null;
    chargeOffType: number | null;
    checkDigits: string;
    closeDate: string | null;
    corporateUserTransferCode: number | null;
    courtesyFeeLy: number | null;
    courtesyFeeMtd: number | null;
    courtesyFeeYtd: number | null;
    courtesyPayLastYear: number | null;
    courtesyPayMonthToDate: number | null;
    courtesyPayYtd: number | null;
    createdAtBranch: number | null;
    createdByUser: number | null;
    creditReportComment: string;
    creditReportCompliance: string;
    creditReportConsumerInfo: string;
    creditReportConsumerInfoDate: string | null;
    creditReportLastStatus: number | null;
    creditReportNumber: string;
    creditReportOccurDate: string | null;
    creditReportOriginalAmountRptd: number | null;
    creditReportingCode: number | null;
    cuTotalsUseCode: number | null;
    currDivPayable: number | null;
    currMonthPaidDiv: number | null;
    description: string;
    divAccrual: number | null;
    divAccrualDate: string | null;
    divDisbUpdtActvtyD: number | null;
    divFromOpen: number | null;
    divLastYear: number | null;
    divPeriodBalDays: number | null;
    divPeriodStart: string | null;
    divPostCode: number | null;
    divRate: number | null;
    divType: number | null;
    divYtd: number | null;
    dividendDue: number | null;
    dividendRateMargin: number | null;
    dividendRateMarginSign: number | null;
    dividendRateMax: number | null;
    dividendRateMin: number | null;
    dividendRatePeriodDate: string | null;
    dividendRatePeriodFreq: number | null;
    escrowLastYear: number | null;
    escrowYtd: number | null;
    escrowedLoanId: string;
    extAchXfrDailyLimitIn: number | null;
    extAchXfrDailyLimitOut: number | null;
    feeCount: ShareFeeCount_2[];
    feeExemptCrtsyBal: number | null;
    id: string;
    insuranceBalanceAge: ShareInsuranceBalanceAge_2[];
    insuranceMaximum: number | null;
    insuranceType: number | null;
    irs1042SUfid: number | null;
    irsCode: number | null;
    irsPlan: number | null;
    lastAccrualUpdateDate: string | null;
    lastCrReportDate: string | null;
    lastDirectDepAmt: number | null;
    lastDirectDepDate: string | null;
    lastDivAmount: number | null;
    lastDivDate: string | null;
    lastFmDate: string | null;
    lastPurgeDate: string | null;
    lastTranDate: string | null;
    ledgerAccrual: number | null;
    ledgerAccrualDate: string | null;
    loanPaymentHold: number | null;
    maturityDate: string | null;
    maturityPostCode: number | null;
    mcDivLastYear: number | null;
    mcDivYtd: number | null;
    memberBranchSupport: number | null;
    memberUserTransferCode: number | null;
    micrAcctNumber: string;
    minimumBalance: number | null;
    minimumDeposit: number | null;
    minimumWithdrawal: number | null;
    mtdAccruedDivs: number | null;
    mtdEarnedDivs: number | null;
    mtdPaidDivs: number | null;
    mtdPriorRateAccrual: number | null;
    negativeBalanceDate: string | null;
    negativeBalanceNoticeDate: string | null;
    negativeBalanceNoticeNumber: number | null;
    negativeBalanceNoticeType: number | null;
    nickname: string;
    nsfFeeLy: number | null;
    nsfFeeMtd: number | null;
    nsfFeeYtd: number | null;
    nsfLastYear: number | null;
    nsfMonthToDate: number | null;
    nsfYtd: number | null;
    odtAuthFeeSrcCodeList: ShareOdtAuthFeeSrcCodeList_2[];
    openDate: string | null;
    originalBalance: number | null;
    originalDeposit: number | null;
    originalDepositDate: string | null;
    overdraftFeeLastYr: number | null;
    overdraftFeeYtd: number | null;
    overdraftTolerance: number | null;
    payeeLine: SharePayeeLine_2[];
    payeeNameLocator: number | null;
    payeeNameType: number | null;
    payeePhone: SharePayeePhone_2[];
    penaltyLastYear: number | null;
    penaltyType: number | null;
    penaltyYtd: number | null;
    periodicCap: number | null;
    periodicStartRate: number | null;
    positivePayDraft: number | null;
    preMthDivAccrued: SharePreMthDivAccrued_2[];
    preMthDivEarned: SharePreMthDivEarned_2[];
    preMthDivPaid: SharePreMthDivPaid_2[];
    putItemSchd: number | null;
    putItemSchdType: number | null;
    recordChangeDate: string | null;
    reference: string;
    regDCheckCount: number | null;
    regDCtrStartDay: number | null;
    regDTransferCount: number | null;
    regECount: number | null;
    renewShareType: number | null;
    renewTermFreq: number | null;
    renewTermPeriod: number | null;
    service: ShareService_2[];
    shareCode: number | null;
    stateWithholdingCode: number | null;
    stateWithholdingLastQtr: number | null;
    stateWithholdingLastYear: number | null;
    stateWithholdingQtd: number | null;
    stateWithholdingYtd: number | null;
    statementDate: string | null;
    statementGroup: number | null;
    statementMailCode: number | null;
    statementPrevDate: string | null;
    sweepBalanceType: number | null;
    sweepPriority: number | null;
    sweepTargetMaximum: number | null;
    sweepTargetMinimum: number | null;
    termFrequency: number | null;
    termPeriod: number | null;
    type: number | null;
    unpaidFeeLastYear: number | null;
    unpaidFeeYtd: number | null;
    userAmount1: number | null;
    userAmount2: number | null;
    userChar1: string;
    userChar2: string;
    userChar3: string;
    userChar4: string;
    userDate1: string | null;
    userDate2: string | null;
    warningCode: ShareWarningCode_2[];
    warningExpiration: ShareWarningExpiration_2[];
    withdrawalCount: number | null;
    withdrawalFeeCount: number | null;
    withdrawalFeeType: number | null;
    withdrawalLimit: number | null;
    withdrawnFromOpen: number | null;
    withholdingCode: number | null;
    withholdingLastYear: number | null;
    withholdingYtd: number | null;
    xfrLastYear: number | null;
    xfrMonthToDate: number | null;
    xfrYtd: number | null;
    yearEndBalance: number | null;
    version1: VersionType;
}