import { ShareCheckOrderBusCaptions_2 } from "./shareCheckOrderBusCaptions_2";
import { ShareCheckOrderImprintLine_2 } from "./shareCheckOrderImprintLine_2";
import { ShareCheckOrderImprintLineSize_2 } from "./shareCheckOrderImprintLineSize_2";
import { ShareCheckOrderImprintUsage_2 } from "./shareCheckOrderImprintUsage_2";
import { ShareCheckOrderLicense_2 } from "./shareCheckOrderLicense_2";
import { ShareCheckOrderMailAddress_2 } from "./shareCheckOrderMailAddress_2";
import { ShareCheckOrderOverSigLine_2 } from "./shareCheckOrderOverSigLine_2";
import { ShareCheckOrderSpecialInstr_2 } from "./shareCheckOrderSpecialInstr_2";
import { ShareCheckOrderSsn_2 } from "./shareCheckOrderSsn_2";
import { VersionType } from "./versionType";

export interface ShareCheckOrder_2 {
    accent: string;
    acctAddrInkColor: number | null;
    billingCode: number | null;
    binding: string;
    branch: number | null;
    busBindingStyle: number | null;
    busCaptions: ShareCheckOrderBusCaptions_2[];
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFont: number | null;
    imprintJustify: number | null;
    imprintLine: ShareCheckOrderImprintLine_2[];
    imprintLineSize: ShareCheckOrderImprintLineSize_2[];
    imprintPhone: string;
    imprintState: string;
    imprintUsage: ShareCheckOrderImprintUsage_2[];
    imprintZipCode: string;
    lastFmDate: string | null;
    lastFreeOrder: string | null;
    lastOrderDate: string | null;
    license: ShareCheckOrderLicense_2[];
    locator: number | null;
    mailAddress: ShareCheckOrderMailAddress_2[];
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLines: number | null;
    openDate: string | null;
    overSigFont: number | null;
    overSigJustify: number | null;
    overSigLine: ShareCheckOrderOverSigLine_2[];
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processor: number | null;
    promoNumber: string;
    quantity: number | null;
    recordChangeDate: string | null;
    rerunReason: number | null;
    shipMethod: number | null;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: ShareCheckOrderSpecialInstr_2[];
    ssn: ShareCheckOrderSsn_2[];
    startNumber: number | null;
    status: number | null;
    statusDate: string | null;
    taxExemptCode: number | null;
    titleInkColor: number | null;
    userId: number | null;
    version1: VersionType;
}