import { ShareCheckOrderBusCaptions_2 } from "./shareCheckOrderBusCaptions_2";
import { ShareCheckOrderImprintLine_2 } from "./shareCheckOrderImprintLine_2";
import { ShareCheckOrderImprintLineSize_2 } from "./shareCheckOrderImprintLineSize_2";
import { ShareCheckOrderImprintUsage_2 } from "./shareCheckOrderImprintUsage_2";
import { ShareCheckOrderLicense_2 } from "./shareCheckOrderLicense_2";
import { ShareCheckOrderMailAddress_2 } from "./shareCheckOrderMailAddress_2";
import { ShareCheckOrderOverSigLine_2 } from "./shareCheckOrderOverSigLine_2";
import { ShareCheckOrderSpecialInstr_2 } from "./shareCheckOrderSpecialInstr_2";
import { ShareCheckOrderSsn_2 } from "./shareCheckOrderSsn_2";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface ShareCheckOrder_2 {
    accent: string;
    acctAddrInkColorValue: number;
    acctAddrInkColorValueSpecified: boolean;
    acctAddrInkColor: number | null;
    billingCodeValue: number;
    billingCodeValueSpecified: boolean;
    billingCode: number | null;
    binding: string;
    branchValue: number;
    branchValueSpecified: boolean;
    branch: number | null;
    busBindingStyleValue: number;
    busBindingStyleValueSpecified: boolean;
    busBindingStyle: number | null;
    busCaptions: ShareCheckOrderBusCaptions_2[];
    busCaptionsSpecified: boolean;
    busNumCopiesValue: number;
    busNumCopiesValueSpecified: boolean;
    busNumCopies: number | null;
    busVoucherNumber: string;
    businessSerial: string;
    chargeShippingValue: number;
    chargeShippingValueSpecified: boolean;
    chargeShipping: number | null;
    checkInitials: string;
    checkStyle: string;
    checkTypeValue: number;
    checkTypeValueSpecified: boolean;
    checkType: number | null;
    coverInitials: string;
    coverStyle: string;
    cutInkColorValue: number;
    cutInkColorValueSpecified: boolean;
    cutInkColor: number | null;
    cutNumber: string;
    design: string;
    imprintCity: string;
    imprintFontValue: number;
    imprintFontValueSpecified: boolean;
    imprintFont: number | null;
    imprintJustifyValue: number;
    imprintJustifyValueSpecified: boolean;
    imprintJustify: number | null;
    imprintLine: ShareCheckOrderImprintLine_2[];
    imprintLineSpecified: boolean;
    imprintLineSize: ShareCheckOrderImprintLineSize_2[];
    imprintLineSizeSpecified: boolean;
    imprintPhone: string;
    imprintState: string;
    imprintUsage: ShareCheckOrderImprintUsage_2[];
    imprintUsageSpecified: boolean;
    imprintZipCode: string;
    lastFmDateValue: string | null;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    lastFreeOrderValue: string | null;
    lastFreeOrderValueSpecified: boolean;
    lastFreeOrder: string | null;
    lastOrderDateValue: string | null;
    lastOrderDateValueSpecified: boolean;
    lastOrderDate: string | null;
    license: ShareCheckOrderLicense_2[];
    licenseSpecified: boolean;
    locatorValue: number;
    locatorValueSpecified: boolean;
    locator: number | null;
    mailAddress: ShareCheckOrderMailAddress_2[];
    mailAddressSpecified: boolean;
    mailCity: string;
    mailState: string;
    mailZipCode: string;
    micrLine: string;
    numberSigLinesValue: number;
    numberSigLinesValueSpecified: boolean;
    numberSigLines: number | null;
    openDateValue: string | null;
    openDateValueSpecified: boolean;
    openDate: string | null;
    overSigFontValue: number;
    overSigFontValueSpecified: boolean;
    overSigFont: number | null;
    overSigJustifyValue: number;
    overSigJustifyValueSpecified: boolean;
    overSigJustify: number | null;
    overSigLine: ShareCheckOrderOverSigLine_2[];
    overSigLineSpecified: boolean;
    overSigLineSizeValue: number;
    overSigLineSizeValueSpecified: boolean;
    overSigLineSize: number | null;
    phantom: string;
    poNumber: string;
    processorValue: number;
    processorValueSpecified: boolean;
    processor: number | null;
    promoNumber: string;
    quantityValue: number;
    quantityValueSpecified: boolean;
    quantity: number | null;
    recordChangeDateValue: string | null;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    rerunReasonValue: number;
    rerunReasonValueSpecified: boolean;
    rerunReason: number | null;
    shipMethodValue: number;
    shipMethodValueSpecified: boolean;
    shipMethod: number | null;
    shipToValue: number;
    shipToValueSpecified: boolean;
    shipTo: number | null;
    sigFigure: string;
    specialInstr: ShareCheckOrderSpecialInstr_2[];
    specialInstrSpecified: boolean;
    ssn: ShareCheckOrderSsn_2[];
    ssnSpecified: boolean;
    startNumberValue: number;
    startNumberValueSpecified: boolean;
    startNumber: number | null;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    statusDateValue: string | null;
    statusDateValueSpecified: boolean;
    statusDate: string | null;
    taxExemptCodeValue: number;
    taxExemptCodeValueSpecified: boolean;
    taxExemptCode: number | null;
    titleInkColorValue: number;
    titleInkColorValueSpecified: boolean;
    titleInkColor: number | null;
    userIdValue: number;
    userIdValueSpecified: boolean;
    userId: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}