import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface SiteFields {
    cityValue: boolean;
    cityValueSpecified: boolean;
    city: boolean | null;
    closeDateValue: boolean;
    closeDateValueSpecified: boolean;
    closeDate: boolean | null;
    contactPhoneValue: boolean;
    contactPhoneValueSpecified: boolean;
    contactPhone: boolean | null;
    extraAddressValue: boolean;
    extraAddressValueSpecified: boolean;
    extraAddress: boolean | null;
    faxPhoneValue: boolean;
    faxPhoneValueSpecified: boolean;
    faxPhone: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    siteContactNameValue: boolean;
    siteContactNameValueSpecified: boolean;
    siteContactName: boolean | null;
    siteIdValue: boolean;
    siteIdValueSpecified: boolean;
    siteId: boolean | null;
    siteNameValue: boolean;
    siteNameValueSpecified: boolean;
    siteName: boolean | null;
    siteNumberValue: boolean;
    siteNumberValueSpecified: boolean;
    siteNumber: boolean | null;
    siteSettleShareIdValue: boolean;
    siteSettleShareIdValueSpecified: boolean;
    siteSettleShareId: boolean | null;
    stateValue: boolean;
    stateValueSpecified: boolean;
    state: boolean | null;
    streetValue: boolean;
    streetValueSpecified: boolean;
    street: boolean | null;
    zipCodeValue: boolean;
    zipCodeValueSpecified: boolean;
    zipCode: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}