import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface SiteCashOrderTypeFields {
    activeFlagValue: boolean;
    activeFlagValueSpecified: boolean;
    activeFlag: boolean | null;
    applyHandlingFeeValue: boolean;
    applyHandlingFeeValueSpecified: boolean;
    applyHandlingFee: boolean | null;
    cashOrderTypeCoinBag: number[];
    cashOrderTypeCoinBagSpecified: boolean;
    cashOrderTypeCoinRoll: number[];
    cashOrderTypeCoinRollSpecified: boolean;
    cashOrderTypeComment: number[];
    cashOrderTypeCommentSpecified: boolean;
    cashOrderTypeCurrFit: number[];
    cashOrderTypeCurrFitSpecified: boolean;
    cashOrderTypeCurrNew: number[];
    cashOrderTypeCurrNewSpecified: boolean;
    cashOrderTypeDelChargeValue: boolean;
    cashOrderTypeDelChargeValueSpecified: boolean;
    cashOrderTypeDelCharge: boolean | null;
    cashOrderTypeMaxOrderValue: boolean;
    cashOrderTypeMaxOrderValueSpecified: boolean;
    cashOrderTypeMaxOrder: boolean | null;
    cashOrderTypeMinOrderValue: boolean;
    cashOrderTypeMinOrderValueSpecified: boolean;
    cashOrderTypeMinOrder: boolean | null;
    cashOrderTypeNameValue: boolean;
    cashOrderTypeNameValueSpecified: boolean;
    cashOrderTypeName: boolean | null;
    cashOrderTypeSpecDelChargeValue: boolean;
    cashOrderTypeSpecDelChargeValueSpecified: boolean;
    cashOrderTypeSpecDelCharge: boolean | null;
    closeDateValue: boolean;
    closeDateValueSpecified: boolean;
    closeDate: boolean | null;
    delFrequencyValue: boolean;
    delFrequencyValueSpecified: boolean;
    delFrequency: boolean | null;
    deliveryDays: number[];
    deliveryDaysSpecified: boolean;
    locationCodeValue: boolean;
    locationCodeValueSpecified: boolean;
    locationCode: boolean | null;
    locatorValue: boolean;
    locatorValueSpecified: boolean;
    locator: boolean | null;
    orderLimitingValue: boolean;
    orderLimitingValueSpecified: boolean;
    orderLimiting: boolean | null;
    recordChangeDateValue: boolean;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: boolean | null;
    specHandlingFeeValue: boolean;
    specHandlingFeeValueSpecified: boolean;
    specHandlingFee: boolean | null;
    vendorNumberValue: boolean;
    vendorNumberValueSpecified: boolean;
    vendorNumber: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}