import { VersionType } from "./versionType";

export interface SymXClientFields {
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmt: boolean | null;
    addonPastDueDays: boolean | null;
    administrativePassword: boolean | null;
    advFeeDescription: boolean | null;
    advFeeGlCode: boolean | null;
    allowAllIrsContributions: boolean | null;
    allowHsaToNonHsaDistrib: boolean | null;
    allowPinFm: boolean | null;
    allowUserAuthentication: boolean | null;
    allowUserCredentials: boolean | null;
    allowUserFileAccess: boolean | null;
    availBalHoldTypeExclList: boolean | null;
    billPayGlCode: boolean | null;
    billPaymentOverdrawOption: boolean | null;
    billPmtUsesSrcCodeB: boolean | null;
    cardActivationTypeList: boolean | null;
    cardBlockingTypeList: boolean | null;
    certificateTypeList: boolean | null;
    chargePartialCapFee: boolean | null;
    chargedOffLoanPmtOption: boolean | null;
    chargedOffLoanTypesList: boolean | null;
    chargedOffShareDepOption: boolean | null;
    chargedOffShareTypesList: boolean | null;
    checkPrinter: boolean | null;
    checkReference: boolean | null;
    checkingTypeList: boolean | null;
    chkDisbGlCode: boolean | null;
    clearingGlCode: boolean | null;
    clientCheckingAcctCode: boolean | null;
    clientSystemName: boolean | null;
    clientSystemUserNumber: boolean | null;
    clubTypeList: boolean | null;
    courtesyNotices: boolean | null;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCode: boolean | null;
    creditCardMaskingMethod: boolean | null;
    depFeeDescription: boolean | null;
    depFeeGlCode: boolean | null;
    disp0CountUserTotals: boolean | null;
    enhancedUserPrivilegeCheck: boolean | null;
    feeTypesToCap: boolean | null;
    ficsAppPassword: boolean | null;
    ficsAppUserId: boolean | null;
    ficsDataSourceName: boolean | null;
    ficsDbPassword: boolean | null;
    ficsDbUserId: boolean | null;
    firstPrtyCksPayeeInfoLoans: boolean | null;
    firstPrtyCksPayeeInfoShare: boolean | null;
    fmInPostingJournal: boolean | null;
    glCategory: boolean | null;
    graceAmountForCashDepPmts: boolean | null;
    groupNumber: boolean | null;
    guaranteedHoldTypeList: boolean | null;
    holdDaysForCashDepPmts: boolean | null;
    inactivityCheckMinutes: boolean | null;
    instanceId: boolean | null;
    invAttemptsBeforeFrozen: boolean | null;
    loanDraftTypeList: boolean | null;
    loanExclusionWarnCodeList: boolean | null;
    loanFeeGlCode: boolean | null;
    logAdAlertMessages: boolean | null;
    logAdBalanceMessages: boolean | null;
    logAdFmMessages: boolean | null;
    logAdInquiryMessages: boolean | null;
    logAdShortNameRefMessages: boolean | null;
    logAdSpecfileType: boolean | null;
    logAdSsnRefMessages: boolean | null;
    logAdTotalMessages: boolean | null;
    logAdUserNameRefMessages: boolean | null;
    logAdVerifyUserNameMessages: boolean | null;
    logFmMessages: boolean | null;
    logIqmessages: boolean | null;
    logSpecfileMessages: boolean | null;
    logTrMessages: boolean | null;
    loginMethod: boolean | null;
    maxCcLoanOverPmtAmount: boolean | null;
    maxHistoryLookBackCount: boolean | null;
    maxHistoryLookBackDays: boolean | null;
    maximumAddonOverLoc: boolean | null;
    maximumAllFieldCount: boolean | null;
    maximumMicroAmount: boolean | null;
    maximumResponseFields: boolean | null;
    maximumSpecfileLines: boolean | null;
    maximumWdBelowAvailable: boolean | null;
    merchantVerHoldDays: boolean | null;
    microGlCode: boolean | null;
    microIdType: boolean | null;
    minimumCheckAmount: boolean | null;
    minimumLineOfCreditAddon: boolean | null;
    minimumMicroAmount: boolean | null;
    numberinCollectList: boolean | null;
    numbertoAuthenticate: boolean | null;
    numbertoCollect: boolean | null;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodes: boolean | null;
    onDemandGroup: boolean | null;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverride: boolean | null;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOption: boolean | null;
    overdrawTransferNotices: boolean | null;
    overdrawWithdrawalIncrement: boolean | null;
    overdrawXfrFeeGlCode: boolean | null;
    overpaymentLoanTypesList: boolean | null;
    paymentPastDueDays: boolean | null;
    pmtFeeDescription: boolean | null;
    pmtFeeGlCode: boolean | null;
    regDLimiting: boolean | null;
    relAdvFee: number[];
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier6: number[];
    relCodeList: number[];
    relCourtesyPayFee1: number[];
    relCourtesyPayFee2: number[];
    relCourtesyPayFee3: number[];
    relCourtesyPayFee4: number[];
    relCourtesyPayFee5: number[];
    relCourtesyPayFee6: number[];
    relCourtesyPayTier1: number[];
    relCourtesyPayTier2: number[];
    relCourtesyPayTier3: number[];
    relCourtesyPayTier4: number[];
    relCourtesyPayTier5: number[];
    relCourtesyPayTier6: number[];
    relDepFee: number[];
    relOverdrawAddonXfrFee: number[];
    relOverdrawComboXfrFee: number[];
    relOverdrawWdXfrFee: number[];
    relPmtFee: number[];
    relWdFee: number[];
    relXfrFee: number[];
    reportTitle: boolean | null;
    returnHashedPasswords: boolean | null;
    rsaProxyUrl: boolean | null;
    rsaProxyUrl2: boolean | null;
    rsaTimeOut: boolean | null;
    savingsTypeList: boolean | null;
    secondPasswordEffDate: boolean | null;
    secondPasswordVerification: boolean | null;
    servicesforDeposit: boolean | null;
    servicesforTransferIn: boolean | null;
    servicesforTransferOut: boolean | null;
    servicesforWithdrawal: boolean | null;
    shareExclusionWarnCodeList: boolean | null;
    shareFeeGlCode: boolean | null;
    ssnAccountNameTypeList: boolean | null;
    ssnLoanNameTypeList: boolean | null;
    ssnShareNameTypeList: boolean | null;
    symXClientNumber: boolean | null;
    totalDescription: number[];
    totalsTimeFrameHigh: number[];
    totalsTimeFrameLow: number[];
    transAcctTypeList: boolean | null;
    transactionSourceCode: boolean | null;
    transferOverdrawOption: boolean | null;
    useBillPmtLimits: boolean | null;
    useCashWithdrawalLimits: boolean | null;
    useCheckWithdrawalLimits: boolean | null;
    useDepositLimits: boolean | null;
    useHbPassword: boolean | null;
    useStandardCardLookup: boolean | null;
    useTransferLimits: boolean | null;
    verificationCount: boolean | null;
    verificationExpirationDays: boolean | null;
    verificationMethod: boolean | null;
    wdAvailableAmtCalculation: boolean | null;
    wdBelowAvailableOption: boolean | null;
    wdFeeDescription: boolean | null;
    wdFeeGlCode: boolean | null;
    withdrawalOverdrawOption: boolean | null;
    withdrawalPastDueDays: boolean | null;
    xfrFeeDescription: boolean | null;
    xfrFeeGlCode: boolean | null;
    version1: VersionType;
}