import { BitMap } from "./bitMap";
import { SymXClientRelAdvFee_2 } from "./symXClientRelAdvFee_2";
import { SymXClientRelAltCourtesyPayFee1_2 } from "./symXClientRelAltCourtesyPayFee1_2";
import { SymXClientRelAltCourtesyPayFee2_2 } from "./symXClientRelAltCourtesyPayFee2_2";
import { SymXClientRelAltCourtesyPayFee3_2 } from "./symXClientRelAltCourtesyPayFee3_2";
import { SymXClientRelAltCourtesyPayFee4_2 } from "./symXClientRelAltCourtesyPayFee4_2";
import { SymXClientRelAltCourtesyPayFee5_2 } from "./symXClientRelAltCourtesyPayFee5_2";
import { SymXClientRelAltCourtesyPayFee6_2 } from "./symXClientRelAltCourtesyPayFee6_2";
import { SymXClientRelAltCourtesyPayTier1_2 } from "./symXClientRelAltCourtesyPayTier1_2";
import { SymXClientRelAltCourtesyPayTier2_2 } from "./symXClientRelAltCourtesyPayTier2_2";
import { SymXClientRelAltCourtesyPayTier3_2 } from "./symXClientRelAltCourtesyPayTier3_2";
import { SymXClientRelAltCourtesyPayTier4_2 } from "./symXClientRelAltCourtesyPayTier4_2";
import { SymXClientRelAltCourtesyPayTier5_2 } from "./symXClientRelAltCourtesyPayTier5_2";
import { SymXClientRelAltCourtesyPayTier6_2 } from "./symXClientRelAltCourtesyPayTier6_2";
import { SymXClientRelCodeList_2 } from "./symXClientRelCodeList_2";
import { SymXClientRelCourtesyPayFee1_2 } from "./symXClientRelCourtesyPayFee1_2";
import { SymXClientRelCourtesyPayFee2_2 } from "./symXClientRelCourtesyPayFee2_2";
import { SymXClientRelCourtesyPayFee3_2 } from "./symXClientRelCourtesyPayFee3_2";
import { SymXClientRelCourtesyPayFee4_2 } from "./symXClientRelCourtesyPayFee4_2";
import { SymXClientRelCourtesyPayFee5_2 } from "./symXClientRelCourtesyPayFee5_2";
import { SymXClientRelCourtesyPayFee6_2 } from "./symXClientRelCourtesyPayFee6_2";
import { SymXClientRelCourtesyPayTier1_2 } from "./symXClientRelCourtesyPayTier1_2";
import { SymXClientRelCourtesyPayTier2_2 } from "./symXClientRelCourtesyPayTier2_2";
import { SymXClientRelCourtesyPayTier3_2 } from "./symXClientRelCourtesyPayTier3_2";
import { SymXClientRelCourtesyPayTier4_2 } from "./symXClientRelCourtesyPayTier4_2";
import { SymXClientRelCourtesyPayTier5_2 } from "./symXClientRelCourtesyPayTier5_2";
import { SymXClientRelCourtesyPayTier6_2 } from "./symXClientRelCourtesyPayTier6_2";
import { SymXClientRelDepFee_2 } from "./symXClientRelDepFee_2";
import { SymXClientRelOverdrawAddonXfrFee_2 } from "./symXClientRelOverdrawAddonXfrFee_2";
import { SymXClientRelOverdrawComboXfrFee_2 } from "./symXClientRelOverdrawComboXfrFee_2";
import { SymXClientRelOverdrawWdXfrFee_2 } from "./symXClientRelOverdrawWdXfrFee_2";
import { SymXClientRelPmtFee_2 } from "./symXClientRelPmtFee_2";
import { SymXClientRelWdFee_2 } from "./symXClientRelWdFee_2";
import { SymXClientRelXfrFee_2 } from "./symXClientRelXfrFee_2";
import { SymXClientTotalDescription_2 } from "./symXClientTotalDescription_2";
import { SymXClientTotalsTimeFrameHigh_2 } from "./symXClientTotalsTimeFrameHigh_2";
import { SymXClientTotalsTimeFrameLow_2 } from "./symXClientTotalsTimeFrameLow_2";
import { VersionType } from "./versionType";

export interface SymXClient_2 {
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmt: boolean | null;
    addonPastDueDays: number | null;
    administrativePassword: string;
    advFeeDescription: string;
    advFeeGlCode: number | null;
    allowAllIrsContributions: boolean | null;
    allowHsaToNonHsaDistrib: boolean | null;
    allowPinFm: boolean | null;
    allowUserAuthentication: boolean | null;
    allowUserCredentials: boolean | null;
    allowUserFileAccess: boolean | null;
    availBalHoldTypeExclList: BitMap;
    billPayGlCode: number | null;
    billPaymentOverdrawOption: number | null;
    billPmtUsesSrcCodeB: boolean | null;
    cardActivationTypeList: string;
    cardBlockingTypeList: string;
    certificateTypeList: string;
    chargePartialCapFee: boolean | null;
    chargedOffLoanPmtOption: number | null;
    chargedOffLoanTypesList: BitMap;
    chargedOffShareDepOption: number | null;
    chargedOffShareTypesList: BitMap;
    checkPrinter: number | null;
    checkReference: string;
    checkingTypeList: string;
    chkDisbGlCode: number | null;
    clearingGlCode: number | null;
    clientCheckingAcctCode: number | null;
    clientSystemName: string;
    clientSystemUserNumber: number | null;
    clubTypeList: string;
    courtesyNotices: number | null;
    courtesyPayCommentCode: number | null;
    courtesyPayFeeDescription: string;
    courtesyPayFeeGlCode: number | null;
    creditCardMaskingMethod: number | null;
    depFeeDescription: string;
    depFeeGlCode: number | null;
    disp0CountUserTotals: boolean | null;
    enhancedUserPrivilegeCheck: boolean | null;
    feeTypesToCap: BitMap;
    ficsAppPassword: string;
    ficsAppUserId: string;
    ficsDataSourceName: string;
    ficsDbPassword: string;
    ficsDbUserId: string;
    firstPrtyCksPayeeInfoLoans: number | null;
    firstPrtyCksPayeeInfoShare: number | null;
    fmInPostingJournal: boolean | null;
    glCategory: number | null;
    graceAmountForCashDepPmts: number | null;
    groupNumber: string;
    guaranteedHoldTypeList: BitMap;
    holdDaysForCashDepPmts: number | null;
    inactivityCheckMinutes: number | null;
    instanceId: number | null;
    invAttemptsBeforeFrozen: number | null;
    loanDraftTypeList: string;
    loanExclusionWarnCodeList: BitMap;
    loanFeeGlCode: number | null;
    logAdAlertMessages: number | null;
    logAdBalanceMessages: number | null;
    logAdFmMessages: number | null;
    logAdInquiryMessages: number | null;
    logAdShortNameRefMessages: number | null;
    logAdSpecfileType: number | null;
    logAdSsnRefMessages: number | null;
    logAdTotalMessages: number | null;
    logAdUserNameRefMessages: number | null;
    logAdVerifyUserNameMessages: number | null;
    logFmMessages: number | null;
    logIqmessages: number | null;
    logSpecfileMessages: number | null;
    logTrMessages: number | null;
    loginMethod: number | null;
    maxCcLoanOverPmtAmount: number | null;
    maxHistoryLookBackCount: number | null;
    maxHistoryLookBackDays: number | null;
    maximumAddonOverLoc: number | null;
    maximumAllFieldCount: number | null;
    maximumMicroAmount: number | null;
    maximumResponseFields: number | null;
    maximumSpecfileLines: number | null;
    maximumWdBelowAvailable: number | null;
    merchantVerHoldDays: number | null;
    microGlCode: number | null;
    microIdType: number | null;
    minimumCheckAmount: number | null;
    minimumLineOfCreditAddon: number | null;
    minimumMicroAmount: number | null;
    numberinCollectList: number | null;
    numbertoAuthenticate: number | null;
    numbertoCollect: number | null;
    odtAuthFeeOvrSrcCodes: string;
    odtAuthFeeRecurSrcCodes: string;
    onDemandGroup: string;
    overdrawAddonDqGraceDays: number | null;
    overdrawAddonIncrement: number | null;
    overdrawAddonMaxOverLoc: number | null;
    overdrawAddonPctOverLoc: number | null;
    overdrawFeeOption: number | null;
    overdrawIncrementOverride: number | null;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOption: number | null;
    overdrawTransferNotices: number | null;
    overdrawWithdrawalIncrement: number | null;
    overdrawXfrFeeGlCode: number | null;
    overpaymentLoanTypesList: BitMap;
    paymentPastDueDays: number | null;
    pmtFeeDescription: string;
    pmtFeeGlCode: number | null;
    regDLimiting: boolean | null;
    relAdvFee: SymXClientRelAdvFee_2[];
    relAltCourtesyPayFee1: SymXClientRelAltCourtesyPayFee1_2[];
    relAltCourtesyPayFee2: SymXClientRelAltCourtesyPayFee2_2[];
    relAltCourtesyPayFee3: SymXClientRelAltCourtesyPayFee3_2[];
    relAltCourtesyPayFee4: SymXClientRelAltCourtesyPayFee4_2[];
    relAltCourtesyPayFee5: SymXClientRelAltCourtesyPayFee5_2[];
    relAltCourtesyPayFee6: SymXClientRelAltCourtesyPayFee6_2[];
    relAltCourtesyPayTier1: SymXClientRelAltCourtesyPayTier1_2[];
    relAltCourtesyPayTier2: SymXClientRelAltCourtesyPayTier2_2[];
    relAltCourtesyPayTier3: SymXClientRelAltCourtesyPayTier3_2[];
    relAltCourtesyPayTier4: SymXClientRelAltCourtesyPayTier4_2[];
    relAltCourtesyPayTier5: SymXClientRelAltCourtesyPayTier5_2[];
    relAltCourtesyPayTier6: SymXClientRelAltCourtesyPayTier6_2[];
    relCodeList: SymXClientRelCodeList_2[];
    relCourtesyPayFee1: SymXClientRelCourtesyPayFee1_2[];
    relCourtesyPayFee2: SymXClientRelCourtesyPayFee2_2[];
    relCourtesyPayFee3: SymXClientRelCourtesyPayFee3_2[];
    relCourtesyPayFee4: SymXClientRelCourtesyPayFee4_2[];
    relCourtesyPayFee5: SymXClientRelCourtesyPayFee5_2[];
    relCourtesyPayFee6: SymXClientRelCourtesyPayFee6_2[];
    relCourtesyPayTier1: SymXClientRelCourtesyPayTier1_2[];
    relCourtesyPayTier2: SymXClientRelCourtesyPayTier2_2[];
    relCourtesyPayTier3: SymXClientRelCourtesyPayTier3_2[];
    relCourtesyPayTier4: SymXClientRelCourtesyPayTier4_2[];
    relCourtesyPayTier5: SymXClientRelCourtesyPayTier5_2[];
    relCourtesyPayTier6: SymXClientRelCourtesyPayTier6_2[];
    relDepFee: SymXClientRelDepFee_2[];
    relOverdrawAddonXfrFee: SymXClientRelOverdrawAddonXfrFee_2[];
    relOverdrawComboXfrFee: SymXClientRelOverdrawComboXfrFee_2[];
    relOverdrawWdXfrFee: SymXClientRelOverdrawWdXfrFee_2[];
    relPmtFee: SymXClientRelPmtFee_2[];
    relWdFee: SymXClientRelWdFee_2[];
    relXfrFee: SymXClientRelXfrFee_2[];
    reportTitle: string;
    returnHashedPasswords: boolean | null;
    rsaProxyUrl: string;
    rsaProxyUrl2: string;
    rsaTimeOut: number | null;
    savingsTypeList: string;
    secondPasswordEffDate: string | null;
    secondPasswordVerification: number | null;
    servicesforDeposit: string;
    servicesforTransferIn: string;
    servicesforTransferOut: string;
    servicesforWithdrawal: string;
    shareExclusionWarnCodeList: BitMap;
    shareFeeGlCode: number | null;
    ssnAccountNameTypeList: string;
    ssnLoanNameTypeList: string;
    ssnShareNameTypeList: string;
    symXClientNumber: number | null;
    totalDescription: SymXClientTotalDescription_2[];
    totalsTimeFrameHigh: SymXClientTotalsTimeFrameHigh_2[];
    totalsTimeFrameLow: SymXClientTotalsTimeFrameLow_2[];
    transAcctTypeList: string;
    transactionSourceCode: string;
    transferOverdrawOption: number | null;
    useBillPmtLimits: boolean | null;
    useCashWithdrawalLimits: boolean | null;
    useCheckWithdrawalLimits: boolean | null;
    useDepositLimits: boolean | null;
    useHbPassword: boolean | null;
    useStandardCardLookup: boolean | null;
    useTransferLimits: boolean | null;
    verificationCount: number | null;
    verificationExpirationDays: number | null;
    verificationMethod: number | null;
    wdAvailableAmtCalculation: number | null;
    wdBelowAvailableOption: number | null;
    wdFeeDescription: string;
    wdFeeGlCode: number | null;
    withdrawalOverdrawOption: number | null;
    withdrawalPastDueDays: number | null;
    xfrFeeDescription: string;
    xfrFeeGlCode: number | null;
    version1: VersionType;
}