import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface SymXClientFields {
    acceptLoanThresholdPaymentValue: boolean;
    acceptLoanThresholdPaymentValueSpecified: boolean;
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmtValue: boolean;
    acceptUnappliedPartialPmtValueSpecified: boolean;
    acceptUnappliedPartialPmt: boolean | null;
    addonPastDueDaysValue: boolean;
    addonPastDueDaysValueSpecified: boolean;
    addonPastDueDays: boolean | null;
    administrativePasswordValue: boolean;
    administrativePasswordValueSpecified: boolean;
    administrativePassword: boolean | null;
    advFeeDescriptionValue: boolean;
    advFeeDescriptionValueSpecified: boolean;
    advFeeDescription: boolean | null;
    advFeeGlCodeValue: boolean;
    advFeeGlCodeValueSpecified: boolean;
    advFeeGlCode: boolean | null;
    allowAllIrsContributionsValue: boolean;
    allowAllIrsContributionsValueSpecified: boolean;
    allowAllIrsContributions: boolean | null;
    allowHsaToNonHsaDistribValue: boolean;
    allowHsaToNonHsaDistribValueSpecified: boolean;
    allowHsaToNonHsaDistrib: boolean | null;
    allowPinFmValue: boolean;
    allowPinFmValueSpecified: boolean;
    allowPinFm: boolean | null;
    allowUserAuthenticationValue: boolean;
    allowUserAuthenticationValueSpecified: boolean;
    allowUserAuthentication: boolean | null;
    allowUserCredentialsValue: boolean;
    allowUserCredentialsValueSpecified: boolean;
    allowUserCredentials: boolean | null;
    allowUserFileAccessValue: boolean;
    allowUserFileAccessValueSpecified: boolean;
    allowUserFileAccess: boolean | null;
    availBalHoldTypeExclListValue: boolean;
    availBalHoldTypeExclListValueSpecified: boolean;
    availBalHoldTypeExclList: boolean | null;
    billPayGlCodeValue: boolean;
    billPayGlCodeValueSpecified: boolean;
    billPayGlCode: boolean | null;
    billPaymentOverdrawOptionValue: boolean;
    billPaymentOverdrawOptionValueSpecified: boolean;
    billPaymentOverdrawOption: boolean | null;
    billPmtUsesSrcCodeBValue: boolean;
    billPmtUsesSrcCodeBValueSpecified: boolean;
    billPmtUsesSrcCodeB: boolean | null;
    cardActivationTypeListValue: boolean;
    cardActivationTypeListValueSpecified: boolean;
    cardActivationTypeList: boolean | null;
    cardBlockingTypeListValue: boolean;
    cardBlockingTypeListValueSpecified: boolean;
    cardBlockingTypeList: boolean | null;
    certificateTypeListValue: boolean;
    certificateTypeListValueSpecified: boolean;
    certificateTypeList: boolean | null;
    chargePartialCapFeeValue: boolean;
    chargePartialCapFeeValueSpecified: boolean;
    chargePartialCapFee: boolean | null;
    chargedOffLoanPmtOptionValue: boolean;
    chargedOffLoanPmtOptionValueSpecified: boolean;
    chargedOffLoanPmtOption: boolean | null;
    chargedOffLoanTypesListValue: boolean;
    chargedOffLoanTypesListValueSpecified: boolean;
    chargedOffLoanTypesList: boolean | null;
    chargedOffShareDepOptionValue: boolean;
    chargedOffShareDepOptionValueSpecified: boolean;
    chargedOffShareDepOption: boolean | null;
    chargedOffShareTypesListValue: boolean;
    chargedOffShareTypesListValueSpecified: boolean;
    chargedOffShareTypesList: boolean | null;
    checkPrinterValue: boolean;
    checkPrinterValueSpecified: boolean;
    checkPrinter: boolean | null;
    checkReferenceValue: boolean;
    checkReferenceValueSpecified: boolean;
    checkReference: boolean | null;
    checkingTypeListValue: boolean;
    checkingTypeListValueSpecified: boolean;
    checkingTypeList: boolean | null;
    chkDisbGlCodeValue: boolean;
    chkDisbGlCodeValueSpecified: boolean;
    chkDisbGlCode: boolean | null;
    clearingGlCodeValue: boolean;
    clearingGlCodeValueSpecified: boolean;
    clearingGlCode: boolean | null;
    clientCheckingAcctCodeValue: boolean;
    clientCheckingAcctCodeValueSpecified: boolean;
    clientCheckingAcctCode: boolean | null;
    clientSystemNameValue: boolean;
    clientSystemNameValueSpecified: boolean;
    clientSystemName: boolean | null;
    clientSystemUserNumberValue: boolean;
    clientSystemUserNumberValueSpecified: boolean;
    clientSystemUserNumber: boolean | null;
    clubTypeListValue: boolean;
    clubTypeListValueSpecified: boolean;
    clubTypeList: boolean | null;
    courtesyNoticesValue: boolean;
    courtesyNoticesValueSpecified: boolean;
    courtesyNotices: boolean | null;
    courtesyPayCommentCodeValue: boolean;
    courtesyPayCommentCodeValueSpecified: boolean;
    courtesyPayCommentCode: boolean | null;
    courtesyPayFeeDescriptionValue: boolean;
    courtesyPayFeeDescriptionValueSpecified: boolean;
    courtesyPayFeeDescription: boolean | null;
    courtesyPayFeeGlCodeValue: boolean;
    courtesyPayFeeGlCodeValueSpecified: boolean;
    courtesyPayFeeGlCode: boolean | null;
    creditCardMaskingMethodValue: boolean;
    creditCardMaskingMethodValueSpecified: boolean;
    creditCardMaskingMethod: boolean | null;
    depFeeDescriptionValue: boolean;
    depFeeDescriptionValueSpecified: boolean;
    depFeeDescription: boolean | null;
    depFeeGlCodeValue: boolean;
    depFeeGlCodeValueSpecified: boolean;
    depFeeGlCode: boolean | null;
    disp0CountUserTotalsValue: boolean;
    disp0CountUserTotalsValueSpecified: boolean;
    disp0CountUserTotals: boolean | null;
    enhancedUserPrivilegeCheckValue: boolean;
    enhancedUserPrivilegeCheckValueSpecified: boolean;
    enhancedUserPrivilegeCheck: boolean | null;
    feeTypesToCapValue: boolean;
    feeTypesToCapValueSpecified: boolean;
    feeTypesToCap: boolean | null;
    ficsAppPasswordValue: boolean;
    ficsAppPasswordValueSpecified: boolean;
    ficsAppPassword: boolean | null;
    ficsAppUserIdValue: boolean;
    ficsAppUserIdValueSpecified: boolean;
    ficsAppUserId: boolean | null;
    ficsDataSourceNameValue: boolean;
    ficsDataSourceNameValueSpecified: boolean;
    ficsDataSourceName: boolean | null;
    ficsDbPasswordValue: boolean;
    ficsDbPasswordValueSpecified: boolean;
    ficsDbPassword: boolean | null;
    ficsDbUserIdValue: boolean;
    ficsDbUserIdValueSpecified: boolean;
    ficsDbUserId: boolean | null;
    firstPrtyCksPayeeInfoLoansValue: boolean;
    firstPrtyCksPayeeInfoLoansValueSpecified: boolean;
    firstPrtyCksPayeeInfoLoans: boolean | null;
    firstPrtyCksPayeeInfoShareValue: boolean;
    firstPrtyCksPayeeInfoShareValueSpecified: boolean;
    firstPrtyCksPayeeInfoShare: boolean | null;
    fmInPostingJournalValue: boolean;
    fmInPostingJournalValueSpecified: boolean;
    fmInPostingJournal: boolean | null;
    glCategoryValue: boolean;
    glCategoryValueSpecified: boolean;
    glCategory: boolean | null;
    graceAmountForCashDepPmtsValue: boolean;
    graceAmountForCashDepPmtsValueSpecified: boolean;
    graceAmountForCashDepPmts: boolean | null;
    groupNumberValue: boolean;
    groupNumberValueSpecified: boolean;
    groupNumber: boolean | null;
    guaranteedHoldTypeListValue: boolean;
    guaranteedHoldTypeListValueSpecified: boolean;
    guaranteedHoldTypeList: boolean | null;
    holdDaysForCashDepPmtsValue: boolean;
    holdDaysForCashDepPmtsValueSpecified: boolean;
    holdDaysForCashDepPmts: boolean | null;
    inactivityCheckMinutesValue: boolean;
    inactivityCheckMinutesValueSpecified: boolean;
    inactivityCheckMinutes: boolean | null;
    instanceIdValue: boolean;
    instanceIdValueSpecified: boolean;
    instanceId: boolean | null;
    invAttemptsBeforeFrozenValue: boolean;
    invAttemptsBeforeFrozenValueSpecified: boolean;
    invAttemptsBeforeFrozen: boolean | null;
    loanDraftTypeListValue: boolean;
    loanDraftTypeListValueSpecified: boolean;
    loanDraftTypeList: boolean | null;
    loanExclusionWarnCodeListValue: boolean;
    loanExclusionWarnCodeListValueSpecified: boolean;
    loanExclusionWarnCodeList: boolean | null;
    loanFeeGlCodeValue: boolean;
    loanFeeGlCodeValueSpecified: boolean;
    loanFeeGlCode: boolean | null;
    logAdAlertMessagesValue: boolean;
    logAdAlertMessagesValueSpecified: boolean;
    logAdAlertMessages: boolean | null;
    logAdBalanceMessagesValue: boolean;
    logAdBalanceMessagesValueSpecified: boolean;
    logAdBalanceMessages: boolean | null;
    logAdFmMessagesValue: boolean;
    logAdFmMessagesValueSpecified: boolean;
    logAdFmMessages: boolean | null;
    logAdInquiryMessagesValue: boolean;
    logAdInquiryMessagesValueSpecified: boolean;
    logAdInquiryMessages: boolean | null;
    logAdShortNameRefMessagesValue: boolean;
    logAdShortNameRefMessagesValueSpecified: boolean;
    logAdShortNameRefMessages: boolean | null;
    logAdSpecfileTypeValue: boolean;
    logAdSpecfileTypeValueSpecified: boolean;
    logAdSpecfileType: boolean | null;
    logAdSsnRefMessagesValue: boolean;
    logAdSsnRefMessagesValueSpecified: boolean;
    logAdSsnRefMessages: boolean | null;
    logAdTotalMessagesValue: boolean;
    logAdTotalMessagesValueSpecified: boolean;
    logAdTotalMessages: boolean | null;
    logAdUserNameRefMessagesValue: boolean;
    logAdUserNameRefMessagesValueSpecified: boolean;
    logAdUserNameRefMessages: boolean | null;
    logAdVerifyUserNameMessagesValue: boolean;
    logAdVerifyUserNameMessagesValueSpecified: boolean;
    logAdVerifyUserNameMessages: boolean | null;
    logFmMessagesValue: boolean;
    logFmMessagesValueSpecified: boolean;
    logFmMessages: boolean | null;
    logIqmessagesValue: boolean;
    logIqmessagesValueSpecified: boolean;
    logIqmessages: boolean | null;
    logSpecfileMessagesValue: boolean;
    logSpecfileMessagesValueSpecified: boolean;
    logSpecfileMessages: boolean | null;
    logTrMessagesValue: boolean;
    logTrMessagesValueSpecified: boolean;
    logTrMessages: boolean | null;
    loginMethodValue: boolean;
    loginMethodValueSpecified: boolean;
    loginMethod: boolean | null;
    maxCcLoanOverPmtAmountValue: boolean;
    maxCcLoanOverPmtAmountValueSpecified: boolean;
    maxCcLoanOverPmtAmount: boolean | null;
    maxHistoryLookBackCountValue: boolean;
    maxHistoryLookBackCountValueSpecified: boolean;
    maxHistoryLookBackCount: boolean | null;
    maxHistoryLookBackDaysValue: boolean;
    maxHistoryLookBackDaysValueSpecified: boolean;
    maxHistoryLookBackDays: boolean | null;
    maximumAddonOverLocValue: boolean;
    maximumAddonOverLocValueSpecified: boolean;
    maximumAddonOverLoc: boolean | null;
    maximumAllFieldCountValue: boolean;
    maximumAllFieldCountValueSpecified: boolean;
    maximumAllFieldCount: boolean | null;
    maximumMicroAmountValue: boolean;
    maximumMicroAmountValueSpecified: boolean;
    maximumMicroAmount: boolean | null;
    maximumResponseFieldsValue: boolean;
    maximumResponseFieldsValueSpecified: boolean;
    maximumResponseFields: boolean | null;
    maximumSpecfileLinesValue: boolean;
    maximumSpecfileLinesValueSpecified: boolean;
    maximumSpecfileLines: boolean | null;
    maximumWdBelowAvailableValue: boolean;
    maximumWdBelowAvailableValueSpecified: boolean;
    maximumWdBelowAvailable: boolean | null;
    merchantVerHoldDaysValue: boolean;
    merchantVerHoldDaysValueSpecified: boolean;
    merchantVerHoldDays: boolean | null;
    microGlCodeValue: boolean;
    microGlCodeValueSpecified: boolean;
    microGlCode: boolean | null;
    microIdTypeValue: boolean;
    microIdTypeValueSpecified: boolean;
    microIdType: boolean | null;
    minimumCheckAmountValue: boolean;
    minimumCheckAmountValueSpecified: boolean;
    minimumCheckAmount: boolean | null;
    minimumLineOfCreditAddonValue: boolean;
    minimumLineOfCreditAddonValueSpecified: boolean;
    minimumLineOfCreditAddon: boolean | null;
    minimumMicroAmountValue: boolean;
    minimumMicroAmountValueSpecified: boolean;
    minimumMicroAmount: boolean | null;
    numberinCollectListValue: boolean;
    numberinCollectListValueSpecified: boolean;
    numberinCollectList: boolean | null;
    numbertoAuthenticateValue: boolean;
    numbertoAuthenticateValueSpecified: boolean;
    numbertoAuthenticate: boolean | null;
    numbertoCollectValue: boolean;
    numbertoCollectValueSpecified: boolean;
    numbertoCollect: boolean | null;
    odtAuthFeeOvrSrcCodesValue: boolean;
    odtAuthFeeOvrSrcCodesValueSpecified: boolean;
    odtAuthFeeOvrSrcCodes: boolean | null;
    odtAuthFeeRecurSrcCodesValue: boolean;
    odtAuthFeeRecurSrcCodesValueSpecified: boolean;
    odtAuthFeeRecurSrcCodes: boolean | null;
    onDemandGroupValue: boolean;
    onDemandGroupValueSpecified: boolean;
    onDemandGroup: boolean | null;
    overdrawAddonDqGraceDaysValue: boolean;
    overdrawAddonDqGraceDaysValueSpecified: boolean;
    overdrawAddonDqGraceDays: boolean | null;
    overdrawAddonIncrementValue: boolean;
    overdrawAddonIncrementValueSpecified: boolean;
    overdrawAddonIncrement: boolean | null;
    overdrawAddonMaxOverLocValue: boolean;
    overdrawAddonMaxOverLocValueSpecified: boolean;
    overdrawAddonMaxOverLoc: boolean | null;
    overdrawAddonPctOverLocValue: boolean;
    overdrawAddonPctOverLocValueSpecified: boolean;
    overdrawAddonPctOverLoc: boolean | null;
    overdrawFeeOptionValue: boolean;
    overdrawFeeOptionValueSpecified: boolean;
    overdrawFeeOption: boolean | null;
    overdrawIncrementOverrideValue: boolean;
    overdrawIncrementOverrideValueSpecified: boolean;
    overdrawIncrementOverride: boolean | null;
    overdrawRegDLimitingValue: boolean;
    overdrawRegDLimitingValueSpecified: boolean;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOptionValue: boolean;
    overdrawTierOptionValueSpecified: boolean;
    overdrawTierOption: boolean | null;
    overdrawTransferNoticesValue: boolean;
    overdrawTransferNoticesValueSpecified: boolean;
    overdrawTransferNotices: boolean | null;
    overdrawWithdrawalIncrementValue: boolean;
    overdrawWithdrawalIncrementValueSpecified: boolean;
    overdrawWithdrawalIncrement: boolean | null;
    overdrawXfrFeeGlCodeValue: boolean;
    overdrawXfrFeeGlCodeValueSpecified: boolean;
    overdrawXfrFeeGlCode: boolean | null;
    overpaymentLoanTypesListValue: boolean;
    overpaymentLoanTypesListValueSpecified: boolean;
    overpaymentLoanTypesList: boolean | null;
    paymentPastDueDaysValue: boolean;
    paymentPastDueDaysValueSpecified: boolean;
    paymentPastDueDays: boolean | null;
    pmtFeeDescriptionValue: boolean;
    pmtFeeDescriptionValueSpecified: boolean;
    pmtFeeDescription: boolean | null;
    pmtFeeGlCodeValue: boolean;
    pmtFeeGlCodeValueSpecified: boolean;
    pmtFeeGlCode: boolean | null;
    regDLimitingValue: boolean;
    regDLimitingValueSpecified: boolean;
    regDLimiting: boolean | null;
    relAdvFee: number[];
    relAdvFeeSpecified: boolean;
    relAltCourtesyPayFee1: number[];
    relAltCourtesyPayFee1Specified: boolean;
    relAltCourtesyPayFee2: number[];
    relAltCourtesyPayFee2Specified: boolean;
    relAltCourtesyPayFee3: number[];
    relAltCourtesyPayFee3Specified: boolean;
    relAltCourtesyPayFee4: number[];
    relAltCourtesyPayFee4Specified: boolean;
    relAltCourtesyPayFee5: number[];
    relAltCourtesyPayFee5Specified: boolean;
    relAltCourtesyPayFee6: number[];
    relAltCourtesyPayFee6Specified: boolean;
    relAltCourtesyPayTier1: number[];
    relAltCourtesyPayTier1Specified: boolean;
    relAltCourtesyPayTier2: number[];
    relAltCourtesyPayTier2Specified: boolean;
    relAltCourtesyPayTier3: number[];
    relAltCourtesyPayTier3Specified: boolean;
    relAltCourtesyPayTier4: number[];
    relAltCourtesyPayTier4Specified: boolean;
    relAltCourtesyPayTier5: number[];
    relAltCourtesyPayTier5Specified: boolean;
    relAltCourtesyPayTier6: number[];
    relAltCourtesyPayTier6Specified: boolean;
    relCodeList: number[];
    relCodeListSpecified: boolean;
    relCourtesyPayFee1: number[];
    relCourtesyPayFee1Specified: boolean;
    relCourtesyPayFee2: number[];
    relCourtesyPayFee2Specified: boolean;
    relCourtesyPayFee3: number[];
    relCourtesyPayFee3Specified: boolean;
    relCourtesyPayFee4: number[];
    relCourtesyPayFee4Specified: boolean;
    relCourtesyPayFee5: number[];
    relCourtesyPayFee5Specified: boolean;
    relCourtesyPayFee6: number[];
    relCourtesyPayFee6Specified: boolean;
    relCourtesyPayTier1: number[];
    relCourtesyPayTier1Specified: boolean;
    relCourtesyPayTier2: number[];
    relCourtesyPayTier2Specified: boolean;
    relCourtesyPayTier3: number[];
    relCourtesyPayTier3Specified: boolean;
    relCourtesyPayTier4: number[];
    relCourtesyPayTier4Specified: boolean;
    relCourtesyPayTier5: number[];
    relCourtesyPayTier5Specified: boolean;
    relCourtesyPayTier6: number[];
    relCourtesyPayTier6Specified: boolean;
    relDepFee: number[];
    relDepFeeSpecified: boolean;
    relOverdrawAddonXfrFee: number[];
    relOverdrawAddonXfrFeeSpecified: boolean;
    relOverdrawComboXfrFee: number[];
    relOverdrawComboXfrFeeSpecified: boolean;
    relOverdrawWdXfrFee: number[];
    relOverdrawWdXfrFeeSpecified: boolean;
    relPmtFee: number[];
    relPmtFeeSpecified: boolean;
    relWdFee: number[];
    relWdFeeSpecified: boolean;
    relXfrFee: number[];
    relXfrFeeSpecified: boolean;
    reportTitleValue: boolean;
    reportTitleValueSpecified: boolean;
    reportTitle: boolean | null;
    returnHashedPasswordsValue: boolean;
    returnHashedPasswordsValueSpecified: boolean;
    returnHashedPasswords: boolean | null;
    rsaProxyUrlValue: boolean;
    rsaProxyUrlValueSpecified: boolean;
    rsaProxyUrl: boolean | null;
    rsaProxyUrl2Value: boolean;
    rsaProxyUrl2ValueSpecified: boolean;
    rsaProxyUrl2: boolean | null;
    rsaTimeOutValue: boolean;
    rsaTimeOutValueSpecified: boolean;
    rsaTimeOut: boolean | null;
    savingsTypeListValue: boolean;
    savingsTypeListValueSpecified: boolean;
    savingsTypeList: boolean | null;
    secondPasswordEffDateValue: boolean;
    secondPasswordEffDateValueSpecified: boolean;
    secondPasswordEffDate: boolean | null;
    secondPasswordVerificationValue: boolean;
    secondPasswordVerificationValueSpecified: boolean;
    secondPasswordVerification: boolean | null;
    servicesforDepositValue: boolean;
    servicesforDepositValueSpecified: boolean;
    servicesforDeposit: boolean | null;
    servicesforTransferInValue: boolean;
    servicesforTransferInValueSpecified: boolean;
    servicesforTransferIn: boolean | null;
    servicesforTransferOutValue: boolean;
    servicesforTransferOutValueSpecified: boolean;
    servicesforTransferOut: boolean | null;
    servicesforWithdrawalValue: boolean;
    servicesforWithdrawalValueSpecified: boolean;
    servicesforWithdrawal: boolean | null;
    shareExclusionWarnCodeListValue: boolean;
    shareExclusionWarnCodeListValueSpecified: boolean;
    shareExclusionWarnCodeList: boolean | null;
    shareFeeGlCodeValue: boolean;
    shareFeeGlCodeValueSpecified: boolean;
    shareFeeGlCode: boolean | null;
    ssnAccountNameTypeListValue: boolean;
    ssnAccountNameTypeListValueSpecified: boolean;
    ssnAccountNameTypeList: boolean | null;
    ssnLoanNameTypeListValue: boolean;
    ssnLoanNameTypeListValueSpecified: boolean;
    ssnLoanNameTypeList: boolean | null;
    ssnShareNameTypeListValue: boolean;
    ssnShareNameTypeListValueSpecified: boolean;
    ssnShareNameTypeList: boolean | null;
    symXClientNumberValue: boolean;
    symXClientNumberValueSpecified: boolean;
    symXClientNumber: boolean | null;
    totalDescription: number[];
    totalDescriptionSpecified: boolean;
    totalsTimeFrameHigh: number[];
    totalsTimeFrameHighSpecified: boolean;
    totalsTimeFrameLow: number[];
    totalsTimeFrameLowSpecified: boolean;
    transAcctTypeListValue: boolean;
    transAcctTypeListValueSpecified: boolean;
    transAcctTypeList: boolean | null;
    transactionSourceCodeValue: boolean;
    transactionSourceCodeValueSpecified: boolean;
    transactionSourceCode: boolean | null;
    transferOverdrawOptionValue: boolean;
    transferOverdrawOptionValueSpecified: boolean;
    transferOverdrawOption: boolean | null;
    useBillPmtLimitsValue: boolean;
    useBillPmtLimitsValueSpecified: boolean;
    useBillPmtLimits: boolean | null;
    useCashWithdrawalLimitsValue: boolean;
    useCashWithdrawalLimitsValueSpecified: boolean;
    useCashWithdrawalLimits: boolean | null;
    useCheckWithdrawalLimitsValue: boolean;
    useCheckWithdrawalLimitsValueSpecified: boolean;
    useCheckWithdrawalLimits: boolean | null;
    useDepositLimitsValue: boolean;
    useDepositLimitsValueSpecified: boolean;
    useDepositLimits: boolean | null;
    useHbPasswordValue: boolean;
    useHbPasswordValueSpecified: boolean;
    useHbPassword: boolean | null;
    useStandardCardLookupValue: boolean;
    useStandardCardLookupValueSpecified: boolean;
    useStandardCardLookup: boolean | null;
    useTransferLimitsValue: boolean;
    useTransferLimitsValueSpecified: boolean;
    useTransferLimits: boolean | null;
    verificationCountValue: boolean;
    verificationCountValueSpecified: boolean;
    verificationCount: boolean | null;
    verificationExpirationDaysValue: boolean;
    verificationExpirationDaysValueSpecified: boolean;
    verificationExpirationDays: boolean | null;
    verificationMethodValue: boolean;
    verificationMethodValueSpecified: boolean;
    verificationMethod: boolean | null;
    wdAvailableAmtCalculationValue: boolean;
    wdAvailableAmtCalculationValueSpecified: boolean;
    wdAvailableAmtCalculation: boolean | null;
    wdBelowAvailableOptionValue: boolean;
    wdBelowAvailableOptionValueSpecified: boolean;
    wdBelowAvailableOption: boolean | null;
    wdFeeDescriptionValue: boolean;
    wdFeeDescriptionValueSpecified: boolean;
    wdFeeDescription: boolean | null;
    wdFeeGlCodeValue: boolean;
    wdFeeGlCodeValueSpecified: boolean;
    wdFeeGlCode: boolean | null;
    withdrawalOverdrawOptionValue: boolean;
    withdrawalOverdrawOptionValueSpecified: boolean;
    withdrawalOverdrawOption: boolean | null;
    withdrawalPastDueDaysValue: boolean;
    withdrawalPastDueDaysValueSpecified: boolean;
    withdrawalPastDueDays: boolean | null;
    xfrFeeDescriptionValue: boolean;
    xfrFeeDescriptionValueSpecified: boolean;
    xfrFeeDescription: boolean | null;
    xfrFeeGlCodeValue: boolean;
    xfrFeeGlCodeValueSpecified: boolean;
    xfrFeeGlCode: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}