import { BitMap } from "./bitMap";
import { SymXClientRelAdvFee } from "./symXClientRelAdvFee";
import { SymXClientRelAltCourtesyPayFee1 } from "./symXClientRelAltCourtesyPayFee1";
import { SymXClientRelAltCourtesyPayFee2 } from "./symXClientRelAltCourtesyPayFee2";
import { SymXClientRelAltCourtesyPayFee3 } from "./symXClientRelAltCourtesyPayFee3";
import { SymXClientRelAltCourtesyPayFee4 } from "./symXClientRelAltCourtesyPayFee4";
import { SymXClientRelAltCourtesyPayFee5 } from "./symXClientRelAltCourtesyPayFee5";
import { SymXClientRelAltCourtesyPayFee6 } from "./symXClientRelAltCourtesyPayFee6";
import { SymXClientRelAltCourtesyPayTier1 } from "./symXClientRelAltCourtesyPayTier1";
import { SymXClientRelAltCourtesyPayTier2 } from "./symXClientRelAltCourtesyPayTier2";
import { SymXClientRelAltCourtesyPayTier3 } from "./symXClientRelAltCourtesyPayTier3";
import { SymXClientRelAltCourtesyPayTier4 } from "./symXClientRelAltCourtesyPayTier4";
import { SymXClientRelAltCourtesyPayTier5 } from "./symXClientRelAltCourtesyPayTier5";
import { SymXClientRelAltCourtesyPayTier6 } from "./symXClientRelAltCourtesyPayTier6";
import { SymXClientRelCodeList } from "./symXClientRelCodeList";
import { SymXClientRelCourtesyPayFee1 } from "./symXClientRelCourtesyPayFee1";
import { SymXClientRelCourtesyPayFee2 } from "./symXClientRelCourtesyPayFee2";
import { SymXClientRelCourtesyPayFee3 } from "./symXClientRelCourtesyPayFee3";
import { SymXClientRelCourtesyPayFee4 } from "./symXClientRelCourtesyPayFee4";
import { SymXClientRelCourtesyPayFee5 } from "./symXClientRelCourtesyPayFee5";
import { SymXClientRelCourtesyPayFee6 } from "./symXClientRelCourtesyPayFee6";
import { SymXClientRelCourtesyPayTier1 } from "./symXClientRelCourtesyPayTier1";
import { SymXClientRelCourtesyPayTier2 } from "./symXClientRelCourtesyPayTier2";
import { SymXClientRelCourtesyPayTier3 } from "./symXClientRelCourtesyPayTier3";
import { SymXClientRelCourtesyPayTier4 } from "./symXClientRelCourtesyPayTier4";
import { SymXClientRelCourtesyPayTier5 } from "./symXClientRelCourtesyPayTier5";
import { SymXClientRelCourtesyPayTier6 } from "./symXClientRelCourtesyPayTier6";
import { SymXClientRelDepFee } from "./symXClientRelDepFee";
import { SymXClientRelOverdrawAddonXfrFee } from "./symXClientRelOverdrawAddonXfrFee";
import { SymXClientRelOverdrawComboXfrFee } from "./symXClientRelOverdrawComboXfrFee";
import { SymXClientRelOverdrawWdXfrFee } from "./symXClientRelOverdrawWdXfrFee";
import { SymXClientRelPmtFee } from "./symXClientRelPmtFee";
import { SymXClientRelWdFee } from "./symXClientRelWdFee";
import { SymXClientRelXfrFee } from "./symXClientRelXfrFee";
import { SymXClientTotalDescription } from "./symXClientTotalDescription";
import { SymXClientTotalsTimeFrameHigh } from "./symXClientTotalsTimeFrameHigh";
import { SymXClientTotalsTimeFrameLow } from "./symXClientTotalsTimeFrameLow";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface SymXClient {
    acceptLoanThresholdPaymentValue: boolean;
    acceptLoanThresholdPaymentValueSpecified: boolean;
    acceptLoanThresholdPayment: boolean | null;
    acceptUnappliedPartialPmtValue: boolean;
    acceptUnappliedPartialPmtValueSpecified: boolean;
    acceptUnappliedPartialPmt: boolean | null;
    addonPastDueDaysValue: number;
    addonPastDueDaysValueSpecified: boolean;
    addonPastDueDays: number | null;
    administrativePassword: string;
    advFeeDescription: string;
    advFeeGlCodeValue: number;
    advFeeGlCodeValueSpecified: boolean;
    advFeeGlCode: number | null;
    allowAllIrsContributionsValue: boolean;
    allowAllIrsContributionsValueSpecified: boolean;
    allowAllIrsContributions: boolean | null;
    allowHsaToNonHsaDistribValue: boolean;
    allowHsaToNonHsaDistribValueSpecified: boolean;
    allowHsaToNonHsaDistrib: boolean | null;
    allowPinFmValue: boolean;
    allowPinFmValueSpecified: boolean;
    allowPinFm: boolean | null;
    allowUserAuthenticationValue: boolean;
    allowUserAuthenticationValueSpecified: boolean;
    allowUserAuthentication: boolean | null;
    allowUserCredentialsValue: boolean;
    allowUserCredentialsValueSpecified: boolean;
    allowUserCredentials: boolean | null;
    allowUserFileAccessValue: boolean;
    allowUserFileAccessValueSpecified: boolean;
    allowUserFileAccess: boolean | null;
    availBalHoldTypeExclList: BitMap;
    billPayGlCodeValue: number;
    billPayGlCodeValueSpecified: boolean;
    billPayGlCode: number | null;
    billPaymentOverdrawOptionValue: number;
    billPaymentOverdrawOptionValueSpecified: boolean;
    billPaymentOverdrawOption: number | null;
    billPmtUsesSrcCodeBValue: boolean;
    billPmtUsesSrcCodeBValueSpecified: boolean;
    billPmtUsesSrcCodeB: boolean | null;
    cardActivationTypeList: string;
    cardBlockingTypeList: string;
    certificateTypeList: string;
    chargePartialCapFeeValue: boolean;
    chargePartialCapFeeValueSpecified: boolean;
    chargePartialCapFee: boolean | null;
    chargedOffLoanPmtOptionValue: number;
    chargedOffLoanPmtOptionValueSpecified: boolean;
    chargedOffLoanPmtOption: number | null;
    chargedOffLoanTypesList: BitMap;
    chargedOffShareDepOptionValue: number;
    chargedOffShareDepOptionValueSpecified: boolean;
    chargedOffShareDepOption: number | null;
    chargedOffShareTypesList: BitMap;
    checkPrinterValue: number;
    checkPrinterValueSpecified: boolean;
    checkPrinter: number | null;
    checkReference: string;
    checkingTypeList: string;
    chkDisbGlCodeValue: number;
    chkDisbGlCodeValueSpecified: boolean;
    chkDisbGlCode: number | null;
    clearingGlCodeValue: number;
    clearingGlCodeValueSpecified: boolean;
    clearingGlCode: number | null;
    clientCheckingAcctCodeValue: number;
    clientCheckingAcctCodeValueSpecified: boolean;
    clientCheckingAcctCode: number | null;
    clientSystemName: string;
    clientSystemUserNumberValue: number;
    clientSystemUserNumberValueSpecified: boolean;
    clientSystemUserNumber: number | null;
    clubTypeList: string;
    courtesyNoticesValue: number;
    courtesyNoticesValueSpecified: boolean;
    courtesyNotices: number | null;
    courtesyPayCommentCodeValue: number;
    courtesyPayCommentCodeValueSpecified: boolean;
    courtesyPayCommentCode: number | null;
    courtesyPayFeeDescription: string;
    courtesyPayFeeGlCodeValue: number;
    courtesyPayFeeGlCodeValueSpecified: boolean;
    courtesyPayFeeGlCode: number | null;
    creditCardMaskingMethodValue: number;
    creditCardMaskingMethodValueSpecified: boolean;
    creditCardMaskingMethod: number | null;
    depFeeDescription: string;
    depFeeGlCodeValue: number;
    depFeeGlCodeValueSpecified: boolean;
    depFeeGlCode: number | null;
    disp0CountUserTotalsValue: boolean;
    disp0CountUserTotalsValueSpecified: boolean;
    disp0CountUserTotals: boolean | null;
    enhancedUserPrivilegeCheckValue: boolean;
    enhancedUserPrivilegeCheckValueSpecified: boolean;
    enhancedUserPrivilegeCheck: boolean | null;
    feeTypesToCap: BitMap;
    ficsAppPassword: string;
    ficsAppUserId: string;
    ficsDataSourceName: string;
    ficsDbPassword: string;
    ficsDbUserId: string;
    firstPrtyCksPayeeInfoLoansValue: number;
    firstPrtyCksPayeeInfoLoansValueSpecified: boolean;
    firstPrtyCksPayeeInfoLoans: number | null;
    firstPrtyCksPayeeInfoShareValue: number;
    firstPrtyCksPayeeInfoShareValueSpecified: boolean;
    firstPrtyCksPayeeInfoShare: number | null;
    fmInPostingJournalValue: boolean;
    fmInPostingJournalValueSpecified: boolean;
    fmInPostingJournal: boolean | null;
    glCategoryValue: number;
    glCategoryValueSpecified: boolean;
    glCategory: number | null;
    graceAmountForCashDepPmtsValue: number;
    graceAmountForCashDepPmtsValueSpecified: boolean;
    graceAmountForCashDepPmts: number | null;
    groupNumber: string;
    guaranteedHoldTypeList: BitMap;
    holdDaysForCashDepPmtsValue: number;
    holdDaysForCashDepPmtsValueSpecified: boolean;
    holdDaysForCashDepPmts: number | null;
    inactivityCheckMinutesValue: number;
    inactivityCheckMinutesValueSpecified: boolean;
    inactivityCheckMinutes: number | null;
    instanceIdValue: number;
    instanceIdValueSpecified: boolean;
    instanceId: number | null;
    invAttemptsBeforeFrozenValue: number;
    invAttemptsBeforeFrozenValueSpecified: boolean;
    invAttemptsBeforeFrozen: number | null;
    loanDraftTypeList: string;
    loanExclusionWarnCodeList: BitMap;
    loanFeeGlCodeValue: number;
    loanFeeGlCodeValueSpecified: boolean;
    loanFeeGlCode: number | null;
    logAdAlertMessagesValue: number;
    logAdAlertMessagesValueSpecified: boolean;
    logAdAlertMessages: number | null;
    logAdBalanceMessagesValue: number;
    logAdBalanceMessagesValueSpecified: boolean;
    logAdBalanceMessages: number | null;
    logAdFmMessagesValue: number;
    logAdFmMessagesValueSpecified: boolean;
    logAdFmMessages: number | null;
    logAdInquiryMessagesValue: number;
    logAdInquiryMessagesValueSpecified: boolean;
    logAdInquiryMessages: number | null;
    logAdShortNameRefMessagesValue: number;
    logAdShortNameRefMessagesValueSpecified: boolean;
    logAdShortNameRefMessages: number | null;
    logAdSpecfileTypeValue: number;
    logAdSpecfileTypeValueSpecified: boolean;
    logAdSpecfileType: number | null;
    logAdSsnRefMessagesValue: number;
    logAdSsnRefMessagesValueSpecified: boolean;
    logAdSsnRefMessages: number | null;
    logAdTotalMessagesValue: number;
    logAdTotalMessagesValueSpecified: boolean;
    logAdTotalMessages: number | null;
    logAdUserNameRefMessagesValue: number;
    logAdUserNameRefMessagesValueSpecified: boolean;
    logAdUserNameRefMessages: number | null;
    logAdVerifyUserNameMessagesValue: number;
    logAdVerifyUserNameMessagesValueSpecified: boolean;
    logAdVerifyUserNameMessages: number | null;
    logFmMessagesValue: number;
    logFmMessagesValueSpecified: boolean;
    logFmMessages: number | null;
    logIqmessagesValue: number;
    logIqmessagesValueSpecified: boolean;
    logIqmessages: number | null;
    logSpecfileMessagesValue: number;
    logSpecfileMessagesValueSpecified: boolean;
    logSpecfileMessages: number | null;
    logTrMessagesValue: number;
    logTrMessagesValueSpecified: boolean;
    logTrMessages: number | null;
    loginMethodValue: number;
    loginMethodValueSpecified: boolean;
    loginMethod: number | null;
    maxCcLoanOverPmtAmountValue: number;
    maxCcLoanOverPmtAmountValueSpecified: boolean;
    maxCcLoanOverPmtAmount: number | null;
    maxHistoryLookBackCountValue: number;
    maxHistoryLookBackCountValueSpecified: boolean;
    maxHistoryLookBackCount: number | null;
    maxHistoryLookBackDaysValue: number;
    maxHistoryLookBackDaysValueSpecified: boolean;
    maxHistoryLookBackDays: number | null;
    maximumAddonOverLocValue: number;
    maximumAddonOverLocValueSpecified: boolean;
    maximumAddonOverLoc: number | null;
    maximumAllFieldCountValue: number;
    maximumAllFieldCountValueSpecified: boolean;
    maximumAllFieldCount: number | null;
    maximumMicroAmountValue: number;
    maximumMicroAmountValueSpecified: boolean;
    maximumMicroAmount: number | null;
    maximumResponseFieldsValue: number;
    maximumResponseFieldsValueSpecified: boolean;
    maximumResponseFields: number | null;
    maximumSpecfileLinesValue: number;
    maximumSpecfileLinesValueSpecified: boolean;
    maximumSpecfileLines: number | null;
    maximumWdBelowAvailableValue: number;
    maximumWdBelowAvailableValueSpecified: boolean;
    maximumWdBelowAvailable: number | null;
    merchantVerHoldDaysValue: number;
    merchantVerHoldDaysValueSpecified: boolean;
    merchantVerHoldDays: number | null;
    microGlCodeValue: number;
    microGlCodeValueSpecified: boolean;
    microGlCode: number | null;
    microIdTypeValue: number;
    microIdTypeValueSpecified: boolean;
    microIdType: number | null;
    minimumCheckAmountValue: number;
    minimumCheckAmountValueSpecified: boolean;
    minimumCheckAmount: number | null;
    minimumLineOfCreditAddonValue: number;
    minimumLineOfCreditAddonValueSpecified: boolean;
    minimumLineOfCreditAddon: number | null;
    minimumMicroAmountValue: number;
    minimumMicroAmountValueSpecified: boolean;
    minimumMicroAmount: number | null;
    numberinCollectListValue: number;
    numberinCollectListValueSpecified: boolean;
    numberinCollectList: number | null;
    numbertoAuthenticateValue: number;
    numbertoAuthenticateValueSpecified: boolean;
    numbertoAuthenticate: number | null;
    numbertoCollectValue: number;
    numbertoCollectValueSpecified: boolean;
    numbertoCollect: number | null;
    odtAuthFeeOvrSrcCodes: string;
    odtAuthFeeRecurSrcCodes: string;
    onDemandGroup: string;
    overdrawAddonDqGraceDaysValue: number;
    overdrawAddonDqGraceDaysValueSpecified: boolean;
    overdrawAddonDqGraceDays: number | null;
    overdrawAddonIncrementValue: number;
    overdrawAddonIncrementValueSpecified: boolean;
    overdrawAddonIncrement: number | null;
    overdrawAddonMaxOverLocValue: number;
    overdrawAddonMaxOverLocValueSpecified: boolean;
    overdrawAddonMaxOverLoc: number | null;
    overdrawAddonPctOverLocValue: number;
    overdrawAddonPctOverLocValueSpecified: boolean;
    overdrawAddonPctOverLoc: number | null;
    overdrawFeeOptionValue: number;
    overdrawFeeOptionValueSpecified: boolean;
    overdrawFeeOption: number | null;
    overdrawIncrementOverrideValue: number;
    overdrawIncrementOverrideValueSpecified: boolean;
    overdrawIncrementOverride: number | null;
    overdrawRegDLimitingValue: boolean;
    overdrawRegDLimitingValueSpecified: boolean;
    overdrawRegDLimiting: boolean | null;
    overdrawTierOptionValue: number;
    overdrawTierOptionValueSpecified: boolean;
    overdrawTierOption: number | null;
    overdrawTransferNoticesValue: number;
    overdrawTransferNoticesValueSpecified: boolean;
    overdrawTransferNotices: number | null;
    overdrawWithdrawalIncrementValue: number;
    overdrawWithdrawalIncrementValueSpecified: boolean;
    overdrawWithdrawalIncrement: number | null;
    overdrawXfrFeeGlCodeValue: number;
    overdrawXfrFeeGlCodeValueSpecified: boolean;
    overdrawXfrFeeGlCode: number | null;
    overpaymentLoanTypesList: BitMap;
    paymentPastDueDaysValue: number;
    paymentPastDueDaysValueSpecified: boolean;
    paymentPastDueDays: number | null;
    pmtFeeDescription: string;
    pmtFeeGlCodeValue: number;
    pmtFeeGlCodeValueSpecified: boolean;
    pmtFeeGlCode: number | null;
    regDLimitingValue: boolean;
    regDLimitingValueSpecified: boolean;
    regDLimiting: boolean | null;
    relAdvFee: SymXClientRelAdvFee[];
    relAdvFeeSpecified: boolean;
    relAltCourtesyPayFee1: SymXClientRelAltCourtesyPayFee1[];
    relAltCourtesyPayFee1Specified: boolean;
    relAltCourtesyPayFee2: SymXClientRelAltCourtesyPayFee2[];
    relAltCourtesyPayFee2Specified: boolean;
    relAltCourtesyPayFee3: SymXClientRelAltCourtesyPayFee3[];
    relAltCourtesyPayFee3Specified: boolean;
    relAltCourtesyPayFee4: SymXClientRelAltCourtesyPayFee4[];
    relAltCourtesyPayFee4Specified: boolean;
    relAltCourtesyPayFee5: SymXClientRelAltCourtesyPayFee5[];
    relAltCourtesyPayFee5Specified: boolean;
    relAltCourtesyPayFee6: SymXClientRelAltCourtesyPayFee6[];
    relAltCourtesyPayFee6Specified: boolean;
    relAltCourtesyPayTier1: SymXClientRelAltCourtesyPayTier1[];
    relAltCourtesyPayTier1Specified: boolean;
    relAltCourtesyPayTier2: SymXClientRelAltCourtesyPayTier2[];
    relAltCourtesyPayTier2Specified: boolean;
    relAltCourtesyPayTier3: SymXClientRelAltCourtesyPayTier3[];
    relAltCourtesyPayTier3Specified: boolean;
    relAltCourtesyPayTier4: SymXClientRelAltCourtesyPayTier4[];
    relAltCourtesyPayTier4Specified: boolean;
    relAltCourtesyPayTier5: SymXClientRelAltCourtesyPayTier5[];
    relAltCourtesyPayTier5Specified: boolean;
    relAltCourtesyPayTier6: SymXClientRelAltCourtesyPayTier6[];
    relAltCourtesyPayTier6Specified: boolean;
    relCodeList: SymXClientRelCodeList[];
    relCodeListSpecified: boolean;
    relCourtesyPayFee1: SymXClientRelCourtesyPayFee1[];
    relCourtesyPayFee1Specified: boolean;
    relCourtesyPayFee2: SymXClientRelCourtesyPayFee2[];
    relCourtesyPayFee2Specified: boolean;
    relCourtesyPayFee3: SymXClientRelCourtesyPayFee3[];
    relCourtesyPayFee3Specified: boolean;
    relCourtesyPayFee4: SymXClientRelCourtesyPayFee4[];
    relCourtesyPayFee4Specified: boolean;
    relCourtesyPayFee5: SymXClientRelCourtesyPayFee5[];
    relCourtesyPayFee5Specified: boolean;
    relCourtesyPayFee6: SymXClientRelCourtesyPayFee6[];
    relCourtesyPayFee6Specified: boolean;
    relCourtesyPayTier1: SymXClientRelCourtesyPayTier1[];
    relCourtesyPayTier1Specified: boolean;
    relCourtesyPayTier2: SymXClientRelCourtesyPayTier2[];
    relCourtesyPayTier2Specified: boolean;
    relCourtesyPayTier3: SymXClientRelCourtesyPayTier3[];
    relCourtesyPayTier3Specified: boolean;
    relCourtesyPayTier4: SymXClientRelCourtesyPayTier4[];
    relCourtesyPayTier4Specified: boolean;
    relCourtesyPayTier5: SymXClientRelCourtesyPayTier5[];
    relCourtesyPayTier5Specified: boolean;
    relCourtesyPayTier6: SymXClientRelCourtesyPayTier6[];
    relCourtesyPayTier6Specified: boolean;
    relDepFee: SymXClientRelDepFee[];
    relDepFeeSpecified: boolean;
    relOverdrawAddonXfrFee: SymXClientRelOverdrawAddonXfrFee[];
    relOverdrawAddonXfrFeeSpecified: boolean;
    relOverdrawComboXfrFee: SymXClientRelOverdrawComboXfrFee[];
    relOverdrawComboXfrFeeSpecified: boolean;
    relOverdrawWdXfrFee: SymXClientRelOverdrawWdXfrFee[];
    relOverdrawWdXfrFeeSpecified: boolean;
    relPmtFee: SymXClientRelPmtFee[];
    relPmtFeeSpecified: boolean;
    relWdFee: SymXClientRelWdFee[];
    relWdFeeSpecified: boolean;
    relXfrFee: SymXClientRelXfrFee[];
    relXfrFeeSpecified: boolean;
    reportTitle: string;
    returnHashedPasswordsValue: boolean;
    returnHashedPasswordsValueSpecified: boolean;
    returnHashedPasswords: boolean | null;
    rsaProxyUrl: string;
    rsaProxyUrl2: string;
    rsaTimeOutValue: number;
    rsaTimeOutValueSpecified: boolean;
    rsaTimeOut: number | null;
    savingsTypeList: string;
    secondPasswordEffDateValue: string;
    secondPasswordEffDateValueSpecified: boolean;
    secondPasswordEffDate: string | null;
    secondPasswordVerificationValue: number;
    secondPasswordVerificationValueSpecified: boolean;
    secondPasswordVerification: number | null;
    servicesforDeposit: string;
    servicesforTransferIn: string;
    servicesforTransferOut: string;
    servicesforWithdrawal: string;
    shareExclusionWarnCodeList: BitMap;
    shareFeeGlCodeValue: number;
    shareFeeGlCodeValueSpecified: boolean;
    shareFeeGlCode: number | null;
    ssnAccountNameTypeList: string;
    ssnLoanNameTypeList: string;
    ssnShareNameTypeList: string;
    symXClientNumberValue: number;
    symXClientNumberValueSpecified: boolean;
    symXClientNumber: number | null;
    totalDescription: SymXClientTotalDescription[];
    totalDescriptionSpecified: boolean;
    totalsTimeFrameHigh: SymXClientTotalsTimeFrameHigh[];
    totalsTimeFrameHighSpecified: boolean;
    totalsTimeFrameLow: SymXClientTotalsTimeFrameLow[];
    totalsTimeFrameLowSpecified: boolean;
    transAcctTypeList: string;
    transactionSourceCode: string;
    transferOverdrawOptionValue: number;
    transferOverdrawOptionValueSpecified: boolean;
    transferOverdrawOption: number | null;
    useBillPmtLimitsValue: boolean;
    useBillPmtLimitsValueSpecified: boolean;
    useBillPmtLimits: boolean | null;
    useCashWithdrawalLimitsValue: boolean;
    useCashWithdrawalLimitsValueSpecified: boolean;
    useCashWithdrawalLimits: boolean | null;
    useCheckWithdrawalLimitsValue: boolean;
    useCheckWithdrawalLimitsValueSpecified: boolean;
    useCheckWithdrawalLimits: boolean | null;
    useDepositLimitsValue: boolean;
    useDepositLimitsValueSpecified: boolean;
    useDepositLimits: boolean | null;
    useHbPasswordValue: boolean;
    useHbPasswordValueSpecified: boolean;
    useHbPassword: boolean | null;
    useStandardCardLookupValue: boolean;
    useStandardCardLookupValueSpecified: boolean;
    useStandardCardLookup: boolean | null;
    useTransferLimitsValue: boolean;
    useTransferLimitsValueSpecified: boolean;
    useTransferLimits: boolean | null;
    verificationCountValue: number;
    verificationCountValueSpecified: boolean;
    verificationCount: number | null;
    verificationExpirationDaysValue: number;
    verificationExpirationDaysValueSpecified: boolean;
    verificationExpirationDays: number | null;
    verificationMethodValue: number;
    verificationMethodValueSpecified: boolean;
    verificationMethod: number | null;
    wdAvailableAmtCalculationValue: number;
    wdAvailableAmtCalculationValueSpecified: boolean;
    wdAvailableAmtCalculation: number | null;
    wdBelowAvailableOptionValue: number;
    wdBelowAvailableOptionValueSpecified: boolean;
    wdBelowAvailableOption: number | null;
    wdFeeDescription: string;
    wdFeeGlCodeValue: number;
    wdFeeGlCodeValueSpecified: boolean;
    wdFeeGlCode: number | null;
    withdrawalOverdrawOptionValue: number;
    withdrawalOverdrawOptionValueSpecified: boolean;
    withdrawalOverdrawOption: number | null;
    withdrawalPastDueDaysValue: number;
    withdrawalPastDueDaysValueSpecified: boolean;
    withdrawalPastDueDays: number | null;
    xfrFeeDescription: string;
    xfrFeeGlCodeValue: number;
    xfrFeeGlCodeValueSpecified: boolean;
    xfrFeeGlCode: number | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}