import { UserFmDisplayItem } from "./userFmDisplayItem";
import { UserFmFunctions } from "./userFmFunctions";
import { UserFmNote2 } from "./userFmNote2";
import { UserFmPreviousPasswordHash1 } from "./userFmPreviousPasswordHash1";
import { UserFmPreviousPasswordHash2 } from "./userFmPreviousPasswordHash2";
import { UserFmPreviousPasswordHash3 } from "./userFmPreviousPasswordHash3";
import { UserFmPreviousPasswordHash4 } from "./userFmPreviousPasswordHash4";
import { UserFmPreviousPasswordMode } from "./userFmPreviousPasswordMode";
import { UserFmPriorDayTapeTotal } from "./userFmPriorDayTapeTotal";
import { UserFmPrivilege } from "./userFmPrivilege";
import { UserFmPrivilegeGroup } from "./userFmPrivilegeGroup";
import { UserFmRestrictedAccounts } from "./userFmRestrictedAccounts";
import { UserFmSecurityAmount } from "./userFmSecurityAmount";
import { UserFmSecurityCode } from "./userFmSecurityCode";
import { UserFmTapeTotal } from "./userFmTapeTotal";
import { UserFmWorkList } from "./userFmWorkList";
import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface UserFm {
    accountVerificationValue: number;
    accountVerificationValueSpecified: boolean;
    accountVerification: number | null;
    activPurgeDateValue: string;
    activPurgeDateValueSpecified: boolean;
    activPurgeDate: string | null;
    activeModeValue: number;
    activeModeValueSpecified: boolean;
    activeMode: number | null;
    archiveDateValue: string;
    archiveDateValueSpecified: boolean;
    archiveDate: string | null;
    assignedBranchValue: number;
    assignedBranchValueSpecified: boolean;
    assignedBranch: number | null;
    casTrackingCodeValue: number;
    casTrackingCodeValueSpecified: boolean;
    casTrackingCode: number | null;
    checkTapeColsValue: number;
    checkTapeColsValueSpecified: boolean;
    checkTapeCols: number | null;
    configurationGroupValue: number;
    configurationGroupValueSpecified: boolean;
    configurationGroup: number | null;
    deptName: string;
    directory: string;
    displayItem: UserFmDisplayItem[];
    displayItemSpecified: boolean;
    email: string;
    extension: string;
    functions: UserFmFunctions[];
    functionsSpecified: boolean;
    invalidPasswordAttemptCountValue: number;
    invalidPasswordAttemptCountValueSpecified: boolean;
    invalidPasswordAttemptCount: number | null;
    invalidPinAttemptCountValue: number;
    invalidPinAttemptCountValueSpecified: boolean;
    invalidPinAttemptCount: number | null;
    jobFunction: string;
    jobTitle: string;
    lastCheckSeqValue: number;
    lastCheckSeqValueSpecified: boolean;
    lastCheckSeq: number | null;
    lastConsoleValue: number;
    lastConsoleValueSpecified: boolean;
    lastConsole: number | null;
    lastInvalidPasswordDateValue: string;
    lastInvalidPasswordDateValueSpecified: boolean;
    lastInvalidPasswordDate: string | null;
    lastInvalidPasswordTimeValue: number;
    lastInvalidPasswordTimeValueSpecified: boolean;
    lastInvalidPasswordTime: number | null;
    lastInvalidPinDateValue: string;
    lastInvalidPinDateValueSpecified: boolean;
    lastInvalidPinDate: string | null;
    lastInvalidPinTimeValue: number;
    lastInvalidPinTimeValueSpecified: boolean;
    lastInvalidPinTime: number | null;
    lastLogonDateValue: string;
    lastLogonDateValueSpecified: boolean;
    lastLogonDate: string | null;
    lastLogonTimeValue: number;
    lastLogonTimeValueSpecified: boolean;
    lastLogonTime: number | null;
    location: string;
    managersName: string;
    name: string;
    note2: UserFmNote2[];
    note2Specified: boolean;
    numberValue: number;
    numberValueSpecified: boolean;
    number: number | null;
    onlineAccessValue: number;
    onlineAccessValueSpecified: boolean;
    onlineAccess: number | null;
    passwordChgDateValue: string;
    passwordChgDateValueSpecified: boolean;
    passwordChgDate: string | null;
    passwordHash1: string;
    passwordHash2: string;
    passwordHash3: string;
    passwordHash4: string;
    passwordModeValue: number;
    passwordModeValueSpecified: boolean;
    passwordMode: number | null;
    phone: string;
    pin: string;
    pinActiveModeValue: number;
    pinActiveModeValueSpecified: boolean;
    pinActiveMode: number | null;
    pinChangeDateValue: string;
    pinChangeDateValueSpecified: boolean;
    pinChangeDate: string | null;
    previousLogOnTimeValue: number;
    previousLogOnTimeValueSpecified: boolean;
    previousLogOnTime: number | null;
    previousLogonDateValue: string;
    previousLogonDateValueSpecified: boolean;
    previousLogonDate: string | null;
    previousPasswordHash1: UserFmPreviousPasswordHash1[];
    previousPasswordHash1Specified: boolean;
    previousPasswordHash2: UserFmPreviousPasswordHash2[];
    previousPasswordHash2Specified: boolean;
    previousPasswordHash3: UserFmPreviousPasswordHash3[];
    previousPasswordHash3Specified: boolean;
    previousPasswordHash4: UserFmPreviousPasswordHash4[];
    previousPasswordHash4Specified: boolean;
    previousPasswordMode: UserFmPreviousPasswordMode[];
    previousPasswordModeSpecified: boolean;
    priorDayTapeTotal: UserFmPriorDayTapeTotal[];
    priorDayTapeTotalSpecified: boolean;
    privilege: UserFmPrivilege[];
    privilegeSpecified: boolean;
    privilegeGroup: UserFmPrivilegeGroup[];
    privilegeGroupSpecified: boolean;
    prtCheckIndexValue: number;
    prtCheckIndexValueSpecified: boolean;
    prtCheckIndex: number | null;
    recordChangeDateValue: string;
    recordChangeDateValueSpecified: boolean;
    recordChangeDate: string | null;
    restrictedAccounts: UserFmRestrictedAccounts[];
    restrictedAccountsSpecified: boolean;
    secondaryId: string;
    securityAmount: UserFmSecurityAmount[];
    securityAmountSpecified: boolean;
    securityCode: UserFmSecurityCode[];
    securityCodeSpecified: boolean;
    ssoDomainUserSub1: string;
    ssoDomainUserSub2: string;
    ssoDomainUserSub3: string;
    ssoDomainUserSub4: string;
    tapeTotal: UserFmTapeTotal[];
    tapeTotalSpecified: boolean;
    tempPasswordExpirationDateValue: string;
    tempPasswordExpirationDateValueSpecified: boolean;
    tempPasswordExpirationDate: string | null;
    tempPasswordExpirationTimeValue: number;
    tempPasswordExpirationTimeValueSpecified: boolean;
    tempPasswordExpirationTime: number | null;
    temporaryPasswordValue: boolean;
    temporaryPasswordValueSpecified: boolean;
    temporaryPassword: boolean | null;
    temporaryPinValue: boolean;
    temporaryPinValueSpecified: boolean;
    temporaryPin: boolean | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    workList: UserFmWorkList[];
    workListSpecified: boolean;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}