import { VersionType } from "./versionType";

export interface UserTracking_2 {
    creationDate: string | null;
    creationTime: number | null;
    expireDate: string | null;
    fmLastDate: string | null;
    idType: number | null;
    locator: number | null;
    recordChangeDate: string | null;
    trackingCode: number | null;
    type: number | null;
    userAmount1: number | null;
    userAmount10: number | null;
    userAmount11: number | null;
    userAmount12: number | null;
    userAmount13: number | null;
    userAmount14: number | null;
    userAmount15: number | null;
    userAmount16: number | null;
    userAmount17: number | null;
    userAmount18: number | null;
    userAmount19: number | null;
    userAmount2: number | null;
    userAmount20: number | null;
    userAmount3: number | null;
    userAmount4: number | null;
    userAmount5: number | null;
    userAmount6: number | null;
    userAmount7: number | null;
    userAmount8: number | null;
    userAmount9: number | null;
    userChar1: string;
    userChar10: string;
    userChar11: string;
    userChar12: string;
    userChar13: string;
    userChar14: string;
    userChar15: string;
    userChar16: string;
    userChar17: string;
    userChar18: string;
    userChar19: string;
    userChar2: string;
    userChar20: string;
    userChar3: string;
    userChar4: string;
    userChar5: string;
    userChar6: string;
    userChar7: string;
    userChar8: string;
    userChar9: string;
    userCode1: number | null;
    userCode10: number | null;
    userCode11: number | null;
    userCode12: number | null;
    userCode13: number | null;
    userCode14: number | null;
    userCode15: number | null;
    userCode16: number | null;
    userCode17: number | null;
    userCode18: number | null;
    userCode19: number | null;
    userCode2: number | null;
    userCode20: number | null;
    userCode3: number | null;
    userCode4: number | null;
    userCode5: number | null;
    userCode6: number | null;
    userCode7: number | null;
    userCode8: number | null;
    userCode9: number | null;
    userDate1: string | null;
    userDate10: string | null;
    userDate11: string | null;
    userDate12: string | null;
    userDate13: string | null;
    userDate14: string | null;
    userDate15: string | null;
    userDate16: string | null;
    userDate17: string | null;
    userDate18: string | null;
    userDate19: string | null;
    userDate2: string | null;
    userDate20: string | null;
    userDate3: string | null;
    userDate4: string | null;
    userDate5: string | null;
    userDate6: string | null;
    userDate7: string | null;
    userDate8: string | null;
    userDate9: string | null;
    userId: number | null;
    userNumber1: number | null;
    userNumber10: number | null;
    userNumber11: number | null;
    userNumber12: number | null;
    userNumber13: number | null;
    userNumber14: number | null;
    userNumber15: number | null;
    userNumber16: number | null;
    userNumber17: number | null;
    userNumber18: number | null;
    userNumber19: number | null;
    userNumber2: number | null;
    userNumber20: number | null;
    userNumber3: number | null;
    userNumber4: number | null;
    userNumber5: number | null;
    userNumber6: number | null;
    userNumber7: number | null;
    userNumber8: number | null;
    userNumber9: number | null;
    userRate1: number | null;
    userRate10: number | null;
    userRate11: number | null;
    userRate12: number | null;
    userRate13: number | null;
    userRate14: number | null;
    userRate15: number | null;
    userRate16: number | null;
    userRate17: number | null;
    userRate18: number | null;
    userRate19: number | null;
    userRate2: number | null;
    userRate20: number | null;
    userRate3: number | null;
    userRate4: number | null;
    userRate5: number | null;
    userRate6: number | null;
    userRate7: number | null;
    userRate8: number | null;
    userRate9: number | null;
    version1: VersionType;
}