import { ActivityList } from "./activityList";
import { UserDisplayItem } from "./userDisplayItem";
import { UserFunctions } from "./userFunctions";
import { UserNote2 } from "./userNote2";
import { UserPreviousPasswordMode } from "./userPreviousPasswordMode";
import { UserPriorDayTapeTotal } from "./userPriorDayTapeTotal";
import { UserPrivilege } from "./userPrivilege";
import { UserPrivilegeGroup } from "./userPrivilegeGroup";
import { UserRestrictedAccounts } from "./userRestrictedAccounts";
import { UserSecurityAmount } from "./userSecurityAmount";
import { UserSecurityCode } from "./userSecurityCode";
import { UserTapeTotal } from "./userTapeTotal";
import { UserTrackingList } from "./userTrackingList";
import { UserWorkList } from "./userWorkList";
import { VersionType } from "./versionType";

export interface User {
    accountVerification: number | null;
    activPurgeDate: string | null;
    activeMode: number | null;
    activityList: ActivityList;
    archiveDate: string | null;
    assignedBranch: number | null;
    casTrackingCode: number | null;
    checkTapeCols: number | null;
    configurationGroup: number | null;
    deptName: string;
    directory: string;
    displayItem: UserDisplayItem[];
    email: string;
    extension: string;
    functions: UserFunctions[];
    invalidPasswordAttemptCount: number | null;
    invalidPinAttemptCount: number | null;
    jobFunction: string;
    jobTitle: string;
    lastCheckSeq: number | null;
    lastConsole: number | null;
    lastInvalidPasswordDate: string | null;
    lastInvalidPasswordTime: number | null;
    lastInvalidPinDate: string | null;
    lastInvalidPinTime: number | null;
    lastLogonDate: string | null;
    lastLogonTime: number | null;
    location: string;
    managersName: string;
    name: string;
    note2: UserNote2[];
    number: number | null;
    onlineAccess: number | null;
    passwordChgDate: string | null;
    passwordMode: number | null;
    phone: string;
    pinActiveMode: number | null;
    pinChangeDate: string | null;
    previousLogOnTime: number | null;
    previousLogonDate: string | null;
    previousPasswordMode: UserPreviousPasswordMode[];
    priorDayTapeTotal: UserPriorDayTapeTotal[];
    privilege: UserPrivilege[];
    privilegeGroup: UserPrivilegeGroup[];
    prtCheckIndex: number | null;
    recordChangeDate: string | null;
    restrictedAccounts: UserRestrictedAccounts[];
    secondaryId: string;
    securityAmount: UserSecurityAmount[];
    securityCode: UserSecurityCode[];
    ssoDomainUser: string;
    ssoDomainUserSub1: string;
    ssoDomainUserSub2: string;
    ssoDomainUserSub3: string;
    ssoDomainUserSub4: string;
    tapeTotal: UserTapeTotal[];
    tempPasswordExpirationDate: string | null;
    tempPasswordExpirationTime: number | null;
    temporaryPassword: number | null;
    temporaryPin: number | null;
    type: number | null;
    userTrackingList: UserTrackingList;
    workList: UserWorkList[];
    version1: VersionType;
}