import { UserFmDisplayItem } from "./userFmDisplayItem";
import { UserFmFunctions } from "./userFmFunctions";
import { UserFmNote2 } from "./userFmNote2";
import { UserFmPreviousPasswordHash1 } from "./userFmPreviousPasswordHash1";
import { UserFmPreviousPasswordHash2 } from "./userFmPreviousPasswordHash2";
import { UserFmPreviousPasswordHash3 } from "./userFmPreviousPasswordHash3";
import { UserFmPreviousPasswordHash4 } from "./userFmPreviousPasswordHash4";
import { UserFmPreviousPasswordMode } from "./userFmPreviousPasswordMode";
import { UserFmPriorDayTapeTotal } from "./userFmPriorDayTapeTotal";
import { UserFmPrivilege } from "./userFmPrivilege";
import { UserFmPrivilegeGroup } from "./userFmPrivilegeGroup";
import { UserFmRestrictedAccounts } from "./userFmRestrictedAccounts";
import { UserFmSecurityAmount } from "./userFmSecurityAmount";
import { UserFmSecurityCode } from "./userFmSecurityCode";
import { UserFmTapeTotal } from "./userFmTapeTotal";
import { UserFmWorkList } from "./userFmWorkList";
import { VersionType } from "./versionType";

export interface UserFm {
    accountVerification: number | null;
    activPurgeDate: string | null;
    activeMode: number | null;
    archiveDate: string | null;
    assignedBranch: number | null;
    casTrackingCode: number | null;
    checkTapeCols: number | null;
    configurationGroup: number | null;
    deptName: string;
    directory: string;
    displayItem: UserFmDisplayItem[];
    email: string;
    extension: string;
    functions: UserFmFunctions[];
    invalidPasswordAttemptCount: number | null;
    invalidPinAttemptCount: number | null;
    jobFunction: string;
    jobTitle: string;
    lastCheckSeq: number | null;
    lastConsole: number | null;
    lastInvalidPasswordDate: string | null;
    lastInvalidPasswordTime: number | null;
    lastInvalidPinDate: string | null;
    lastInvalidPinTime: number | null;
    lastLogonDate: string | null;
    lastLogonTime: number | null;
    location: string;
    managersName: string;
    name: string;
    note2: UserFmNote2[];
    number: number | null;
    onlineAccess: number | null;
    passwordChgDate: string | null;
    passwordHash1: string;
    passwordHash2: string;
    passwordHash3: string;
    passwordHash4: string;
    passwordMode: number | null;
    phone: string;
    pin: string;
    pinActiveMode: number | null;
    pinChangeDate: string | null;
    previousLogOnTime: number | null;
    previousLogonDate: string | null;
    previousPasswordHash1: UserFmPreviousPasswordHash1[];
    previousPasswordHash2: UserFmPreviousPasswordHash2[];
    previousPasswordHash3: UserFmPreviousPasswordHash3[];
    previousPasswordHash4: UserFmPreviousPasswordHash4[];
    previousPasswordMode: UserFmPreviousPasswordMode[];
    priorDayTapeTotal: UserFmPriorDayTapeTotal[];
    privilege: UserFmPrivilege[];
    privilegeGroup: UserFmPrivilegeGroup[];
    prtCheckIndex: number | null;
    recordChangeDate: string | null;
    restrictedAccounts: UserFmRestrictedAccounts[];
    secondaryId: string;
    securityAmount: UserFmSecurityAmount[];
    securityCode: UserFmSecurityCode[];
    ssoDomainUserSub1: string;
    ssoDomainUserSub2: string;
    ssoDomainUserSub3: string;
    ssoDomainUserSub4: string;
    tapeTotal: UserFmTapeTotal[];
    tempPasswordExpirationDate: string | null;
    tempPasswordExpirationTime: number | null;
    temporaryPassword: boolean | null;
    temporaryPin: boolean | null;
    type: number | null;
    workList: UserFmWorkList[];
    version1: VersionType;
}