import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface WireMiscFields {
    defaultBusinessFunctionCodeValue: boolean;
    defaultBusinessFunctionCodeValueSpecified: boolean;
    defaultBusinessFunctionCode: boolean | null;
    fedFormatValue: boolean;
    fedFormatValueSpecified: boolean;
    fedFormat: boolean | null;
    incomingCorpWireGlOffsetValue: boolean;
    incomingCorpWireGlOffsetValueSpecified: boolean;
    incomingCorpWireGlOffset: boolean | null;
    incomingMemberWireGlOffsetValue: boolean;
    incomingMemberWireGlOffsetValueSpecified: boolean;
    incomingMemberWireGlOffset: boolean | null;
    incomingWireDepServiceCodeValue: boolean;
    incomingWireDepServiceCodeValueSpecified: boolean;
    incomingWireDepServiceCode: boolean | null;
    newWireCutoffTimeValue: boolean;
    newWireCutoffTimeValueSpecified: boolean;
    newWireCutoffTime: boolean | null;
    outgoingCorpWireGlOffsetValue: boolean;
    outgoingCorpWireGlOffsetValueSpecified: boolean;
    outgoingCorpWireGlOffset: boolean | null;
    outgoingMemberWireGlOffsetValue: boolean;
    outgoingMemberWireGlOffsetValueSpecified: boolean;
    outgoingMemberWireGlOffset: boolean | null;
    outgoingWesternUnionGlOffsValue: boolean;
    outgoingWesternUnionGlOffsValueSpecified: boolean;
    outgoingWesternUnionGlOffs: boolean | null;
    outgoingWireListSrvcCodeValue: boolean;
    outgoingWireListSrvcCodeValueSpecified: boolean;
    outgoingWireListSrvcCode: boolean | null;
    outgoingWireWdServiceCodeValue: boolean;
    outgoingWireWdServiceCodeValueSpecified: boolean;
    outgoingWireWdServiceCode: boolean | null;
    preAuthWireCutoffTimeValue: boolean;
    preAuthWireCutoffTimeValueSpecified: boolean;
    preAuthWireCutoffTime: boolean | null;
    senderFiValue: boolean;
    senderFiValueSpecified: boolean;
    senderFi: boolean | null;
    senderNameValue: boolean;
    senderNameValueSpecified: boolean;
    senderName: boolean | null;
    thresholdValue: boolean;
    thresholdValueSpecified: boolean;
    threshold: boolean | null;
    westernUnionXferCutoffTimeValue: boolean;
    westernUnionXferCutoffTimeValueSpecified: boolean;
    westernUnionXferCutoffTime: boolean | null;
    version1: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}