import { WireBeneficiaryAddress_2 } from "./wireBeneficiaryAddress_2";
import { WireBeneficiaryFiAddress_2 } from "./wireBeneficiaryFiAddress_2";
import { WireChargesCurrencyCode_2 } from "./wireChargesCurrencyCode_2";
import { WireDrawdownDebitAccountAddress_2 } from "./wireDrawdownDebitAccountAddress_2";
import { WireInstructIngFiAddress_2 } from "./wireInstructIngFiAddress_2";
import { WireIntermediaryFiAddress_2 } from "./wireIntermediaryFiAddress_2";
import { WireOriginatorAddress_2 } from "./wireOriginatorAddress_2";
import { WireOriginatorFiAddress_2 } from "./wireOriginatorFiAddress_2";
import { WireOriginatorLineCodeF_2 } from "./wireOriginatorLineCodeF_2";
import { WireOriginatorLineF_2 } from "./wireOriginatorLineF_2";
import { WireOriginatorToBeneficiaryInfo_2 } from "./wireOriginatorToBeneficiaryInfo_2";
import { WireSenderCharges_2 } from "./wireSenderCharges_2";
import { VersionType } from "./versionType";
import { WireCdtrAcctName_2 } from "./wireCdtrAcctName_2";
import { WireCdtrAcctProxyId_2 } from "./wireCdtrAcctProxyId_2";
import { WireCdtrAgtAcctName_2 } from "./wireCdtrAgtAcctName_2";
import { WireCdtrAgtAcctProxyId_2 } from "./wireCdtrAgtAcctProxyId_2";
import { WireChargeAgent1Department_2 } from "./wireChargeAgent1Department_2";
import { WireChargeAgent1Floor_2 } from "./wireChargeAgent1Floor_2";
import { WireChargeAgent1Name_2 } from "./wireChargeAgent1Name_2";
import { WireChargeAgent1Room_2 } from "./wireChargeAgent1Room_2";
import { WireChargeAgent1StreetName_2 } from "./wireChargeAgent1StreetName_2";
import { WireChargeAgent1Subdepartment_2 } from "./wireChargeAgent1Subdepartment_2";
import { WireChargeAgent2Department_2 } from "./wireChargeAgent2Department_2";
import { WireChargeAgent2Floor_2 } from "./wireChargeAgent2Floor_2";
import { WireChargeAgent2Name_2 } from "./wireChargeAgent2Name_2";
import { WireChargeAgent2Room_2 } from "./wireChargeAgent2Room_2";
import { WireChargeAgent2StreetName_2 } from "./wireChargeAgent2StreetName_2";
import { WireChargeAgent2Subdepartment_2 } from "./wireChargeAgent2Subdepartment_2";
import { WireChargeAgent3Department_2 } from "./wireChargeAgent3Department_2";
import { WireChargeAgent3Floor_2 } from "./wireChargeAgent3Floor_2";
import { WireChargeAgent3Name_2 } from "./wireChargeAgent3Name_2";
import { WireChargeAgent3Room_2 } from "./wireChargeAgent3Room_2";
import { WireChargeAgent3StreetName_2 } from "./wireChargeAgent3StreetName_2";
import { WireChargeAgent3Subdepartment_2 } from "./wireChargeAgent3Subdepartment_2";
import { WireChargeAgent4Department_2 } from "./wireChargeAgent4Department_2";
import { WireChargeAgent4Floor_2 } from "./wireChargeAgent4Floor_2";
import { WireChargeAgent4Name_2 } from "./wireChargeAgent4Name_2";
import { WireChargeAgent4Room_2 } from "./wireChargeAgent4Room_2";
import { WireChargeAgent4StreetName_2 } from "./wireChargeAgent4StreetName_2";
import { WireChargeAgent4Subdepartment_2 } from "./wireChargeAgent4Subdepartment_2";
import { WireCreditorAgentDepartment_2 } from "./wireCreditorAgentDepartment_2";
import { WireCreditorAgentFiName_2 } from "./wireCreditorAgentFiName_2";
import { WireCreditorAgentFloor_2 } from "./wireCreditorAgentFloor_2";
import { WireCreditorAgentRoom_2 } from "./wireCreditorAgentRoom_2";
import { WireCreditorAgentStreetName_2 } from "./wireCreditorAgentStreetName_2";
import { WireCreditorAgentSubdepartment_2 } from "./wireCreditorAgentSubdepartment_2";
import { WireCreditorDepartment_2 } from "./wireCreditorDepartment_2";
import { WireCreditorFloor_2 } from "./wireCreditorFloor_2";
import { WireCreditorName_2 } from "./wireCreditorName_2";
import { WireCreditorRoom_2 } from "./wireCreditorRoom_2";
import { WireCreditorStreetName_2 } from "./wireCreditorStreetName_2";
import { WireCreditorSubdepartment_2 } from "./wireCreditorSubdepartment_2";
import { WireDbtrAgtAcctName_2 } from "./wireDbtrAgtAcctName_2";
import { WireDbtrAgtAcctProxyId_2 } from "./wireDbtrAgtAcctProxyId_2";
import { WireDebtorAcctName_2 } from "./wireDebtorAcctName_2";
import { WireDebtorAcctProxyId_2 } from "./wireDebtorAcctProxyId_2";
import { WireDebtorAgentDepartment_2 } from "./wireDebtorAgentDepartment_2";
import { WireDebtorAgentFloor_2 } from "./wireDebtorAgentFloor_2";
import { WireDebtorAgentName_2 } from "./wireDebtorAgentName_2";
import { WireDebtorAgentRoom_2 } from "./wireDebtorAgentRoom_2";
import { WireDebtorAgentStreetName_2 } from "./wireDebtorAgentStreetName_2";
import { WireDebtorAgentSubdepartment_2 } from "./wireDebtorAgentSubdepartment_2";
import { WireDebtorDepartment_2 } from "./wireDebtorDepartment_2";
import { WireDebtorFloor_2 } from "./wireDebtorFloor_2";
import { WireDebtorName_2 } from "./wireDebtorName_2";
import { WireDebtorRoom_2 } from "./wireDebtorRoom_2";
import { WireDebtorStreetName_2 } from "./wireDebtorStreetName_2";
import { WireDebtorSubdepartment_2 } from "./wireDebtorSubdepartment_2";
import { WireInitgPtyDepartment_2 } from "./wireInitgPtyDepartment_2";
import { WireInitgPtyFloor_2 } from "./wireInitgPtyFloor_2";
import { WireInitgPtyName_2 } from "./wireInitgPtyName_2";
import { WireInitgPtyRoom_2 } from "./wireInitgPtyRoom_2";
import { WireInitgPtyStreetName_2 } from "./wireInitgPtyStreetName_2";
import { WireInitgPtySubdepartment_2 } from "./wireInitgPtySubdepartment_2";
import { WireInstr1ForCdtrAgtInfo_2 } from "./wireInstr1ForCdtrAgtInfo_2";
import { WireInstr2ForCdtrAgtInfo_2 } from "./wireInstr2ForCdtrAgtInfo_2";
import { WireIntermedFiDepartment_2 } from "./wireIntermedFiDepartment_2";
import { WireIntermedFiFloor_2 } from "./wireIntermedFiFloor_2";
import { WireIntermedFiRoom_2 } from "./wireIntermedFiRoom_2";
import { WireIntermedFiStreetName_2 } from "./wireIntermedFiStreetName_2";
import { WireIntermedFiSubdepartment_2 } from "./wireIntermedFiSubdepartment_2";
import { WireIntrmyAgt1AcctName_2 } from "./wireIntrmyAgt1AcctName_2";
import { WireIntrmyAgt1AcctProxyId_2 } from "./wireIntrmyAgt1AcctProxyId_2";
import { WirePrevInstrAgentAcctName_2 } from "./wirePrevInstrAgentAcctName_2";
import { WirePrevInstrAgentAcctProxyId_2 } from "./wirePrevInstrAgentAcctProxyId_2";
import { WirePrevInstrAgentDepartment_2 } from "./wirePrevInstrAgentDepartment_2";
import { WirePrevInstrAgentFloor_2 } from "./wirePrevInstrAgentFloor_2";
import { WirePrevInstrAgentRoom_2 } from "./wirePrevInstrAgentRoom_2";
import { WirePrevInstrAgentStreetName_2 } from "./wirePrevInstrAgentStreetName_2";
import { WirePrevInstrAgentSubdepartment_2 } from "./wirePrevInstrAgentSubdepartment_2";
import { WireUltmtCdtrDepartment_2 } from "./wireUltmtCdtrDepartment_2";
import { WireUltmtCdtrFloor_2 } from "./wireUltmtCdtrFloor_2";
import { WireUltmtCdtrName_2 } from "./wireUltmtCdtrName_2";
import { WireUltmtCdtrRoom_2 } from "./wireUltmtCdtrRoom_2";
import { WireUltmtCdtrStreetName_2 } from "./wireUltmtCdtrStreetName_2";
import { WireUltmtCdtrSubdepartment_2 } from "./wireUltmtCdtrSubdepartment_2";
import { WireUltmtDbtrDepartment_2 } from "./wireUltmtDbtrDepartment_2";
import { WireUltmtDbtrFloor_2 } from "./wireUltmtDbtrFloor_2";
import { WireUltmtDbtrName_2 } from "./wireUltmtDbtrName_2";
import { WireUltmtDbtrRoom_2 } from "./wireUltmtDbtrRoom_2";
import { WireUltmtDbtrStreetName_2 } from "./wireUltmtDbtrStreetName_2";
import { WireUltmtDbtrSubdepartment_2 } from "./wireUltmtDbtrSubdepartment_2";
import { XmlElement } from "./xmlElement";

export interface Wire_2 {
    acceptanceDate: string;
    acceptanceTime: string;
    accountNumber: string;
    adjustmentDate: string;
    adjustmentReason: string;
    amountValue: number;
    amountValueSpecified: boolean;
    amount: number | null;
    applicationId: string;
    batchNumberValue: number;
    batchNumberValueSpecified: boolean;
    batchNumber: number | null;
    batchNumberChar: string;
    beneficiaryAddress: WireBeneficiaryAddress_2[];
    beneficiaryAddressSpecified: boolean;
    beneficiaryAdviceValue: number;
    beneficiaryAdviceValueSpecified: boolean;
    beneficiaryAdvice: number | null;
    beneficiaryAdviceCode: string;
    beneficiaryFiAddress: WireBeneficiaryFiAddress_2[];
    beneficiaryFiAddressSpecified: boolean;
    beneficiaryFiAdviceValue: number;
    beneficiaryFiAdviceValueSpecified: boolean;
    beneficiaryFiAdvice: number | null;
    beneficiaryFiAdviceCode: string;
    beneficiaryFiId: string;
    beneficiaryFiIdCode: string;
    beneficiaryFiInfoValue: number;
    beneficiaryFiInfoValueSpecified: boolean;
    beneficiaryFiInfo: number | null;
    beneficiaryFiIntrnatlId: string;
    beneficiaryFiName: string;
    beneficiaryId: string;
    beneficiaryIdCode: string;
    beneficiaryInfoValue: number;
    beneficiaryInfoValueSpecified: boolean;
    beneficiaryInfo: number | null;
    beneficiaryName: string;
    beneficiaryReference: string;
    businessFunctionCode: string;
    chargesCurrencyCode: WireChargesCurrencyCode_2[];
    chargesCurrencyCodeSpecified: boolean;
    commentCodeValue: number;
    commentCodeValueSpecified: boolean;
    commentCode: number | null;
    destinationValue: number;
    destinationValueSpecified: boolean;
    destination: number | null;
    detailOfCharges: string;
    directionValue: number;
    directionValueSpecified: boolean;
    direction: number | null;
    drawdownCreditAccount: string;
    drawdownDebitAccountAddress: WireDrawdownDebitAccountAddress_2[];
    drawdownDebitAccountAddressSpecified: boolean;
    drawdownDebitAccountId: string;
    drawdownDebitAccountIdCode: string;
    drawdownDebitAccountName: string;
    drawdownDebitAcctAdviceValue: number;
    drawdownDebitAcctAdviceValueSpecified: boolean;
    drawdownDebitAcctAdvice: number | null;
    drawdownDebitAcctAdviceCode: string;
    effectiveDateValue: string | null;
    effectiveDateValueSpecified: boolean;
    effectiveDate: string | null;
    enteredByCorporateUserValue: number;
    enteredByCorporateUserValueSpecified: boolean;
    enteredByCorporateUser: number | null;
    enteredByCorporateUserName: string;
    enteredByMemberUserValue: number;
    enteredByMemberUserValueSpecified: boolean;
    enteredByMemberUser: number | null;
    enteredByMemberUserName: string;
    enteredDateValue: string | null;
    enteredDateValueSpecified: boolean;
    enteredDate: string | null;
    enteredTimeValue: number;
    enteredTimeValueSpecified: boolean;
    enteredTime: number | null;
    enteredValidationMethod: string;
    errorCategory: string;
    errorCode: string;
    errorDescription: string;
    exchangeRate: string;
    extractDestinationValue: number;
    extractDestinationValueSpecified: boolean;
    extractDestination: number | null;
    extractedByCorporateUserValue: number;
    extractedByCorporateUserValueSpecified: boolean;
    extractedByCorporateUser: number | null;
    extractedByCorporateUserName: string;
    extractedDateValue: string | null;
    extractedDateValueSpecified: boolean;
    extractedDate: string | null;
    extractedTimeValue: number;
    extractedTimeValueSpecified: boolean;
    extractedTime: number | null;
    fiToFiInfoValue: number;
    fiToFiInfoValueSpecified: boolean;
    fiToFiInfo: number | null;
    fmLastPurgeDateValue: string | null;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: string | null;
    formatVersion: string;
    glAccount: string;
    glCommentAddlInfo: string;
    glOffset: string;
    imad: string;
    instructIngFiAddress: WireInstructIngFiAddress_2[];
    instructIngFiAddressSpecified: boolean;
    instructIngFiId: string;
    instructIngFiIdCode: string;
    instructedAmount: string;
    instructedAmtCurrencyCode: string;
    instructingFiName: string;
    intermediaryFiAddress: WireIntermediaryFiAddress_2[];
    intermediaryFiAddressSpecified: boolean;
    intermediaryFiAdviceValue: number;
    intermediaryFiAdviceValueSpecified: boolean;
    intermediaryFiAdvice: number | null;
    intermediaryFiAdviceCode: string;
    intermediaryFiId: string;
    intermediaryFiIdCode: string;
    intermediaryFiInfoValue: number;
    intermediaryFiInfoValueSpecified: boolean;
    intermediaryFiInfo: number | null;
    intermediaryFiName: string;
    lastFmDateValue: string | null;
    lastFmDateValueSpecified: boolean;
    lastFmDate: string | null;
    messageDuplicationCode: string;
    messageStatusIndicator: string;
    notificationDateValue: string | null;
    notificationDateValueSpecified: boolean;
    notificationDate: string | null;
    notificationMethodValue: number;
    notificationMethodValueSpecified: boolean;
    notificationMethod: number | null;
    notificationStatusValue: number;
    notificationStatusValueSpecified: boolean;
    notificationStatus: number | null;
    notificationTimeValue: number;
    notificationTimeValueSpecified: boolean;
    notificationTime: number | null;
    notificationUser: string;
    ofacDetailsValue: number;
    ofacDetailsValueSpecified: boolean;
    ofacDetails: number | null;
    ofacStatusValue: number;
    ofacStatusValueSpecified: boolean;
    ofacStatus: number | null;
    omad: string;
    originatorAddress: WireOriginatorAddress_2[];
    originatorAddressSpecified: boolean;
    originatorFiAddress: WireOriginatorFiAddress_2[];
    originatorFiAddressSpecified: boolean;
    originatorFiId: string;
    originatorFiIdCode: string;
    originatorFiName: string;
    originatorId: string;
    originatorIdCode: string;
    originatorIdF: string;
    originatorLineCodeF: WireOriginatorLineCodeF_2[];
    originatorLineCodeFSpecified: boolean;
    originatorLineF: WireOriginatorLineF_2[];
    originatorLineFSpecified: boolean;
    originatorName: string;
    originatorNameF: string;
    originatorPartyIdF: string;
    originatorToBeneficiaryInfo: WireOriginatorToBeneficiaryInfo_2[];
    originatorToBeneficiaryInfoSpecified: boolean;
    otherAddLinFo: string;
    paymentLimitation: string;
    paymentMethod: string;
    paymentMethodCode: string;
    postingError: string;
    preAuthTemplateName: string;
    preAuthTemplateNumberValue: number;
    preAuthTemplateNumberValueSpecified: boolean;
    preAuthTemplateNumber: number | null;
    previousMessageImad: string;
    receiverFi: string;
    receiverFiInfoValue: number;
    receiverFiInfoValueSpecified: boolean;
    receiverFiInfo: number | null;
    receiverName: string;
    regETranValue: number;
    regETranValueSpecified: boolean;
    regETran: number | null;
    releasedByCorporateUserValue: number;
    releasedByCorporateUserValueSpecified: boolean;
    releasedByCorporateUser: number | null;
    releasedByCorporateUserName: string;
    releasedDateValue: string | null;
    releasedDateValueSpecified: boolean;
    releasedDate: string | null;
    releasedReason: string;
    releasedTimeValue: number;
    releasedTimeValueSpecified: boolean;
    releasedTime: number | null;
    returnRejectByCorpUserValue: number;
    returnRejectByCorpUserValueSpecified: boolean;
    returnRejectByCorpUser: number | null;
    returnRejectByCorpUserName: string;
    returnRejectDateValue: string | null;
    returnRejectDateValueSpecified: boolean;
    returnRejectDate: string | null;
    returnRejectReason: string;
    returnRejectTimeValue: number;
    returnRejectTimeValueSpecified: boolean;
    returnRejectTime: number | null;
    senderCharges: WireSenderCharges_2[];
    senderChargesSpecified: boolean;
    senderFi: string;
    senderName: string;
    senderReferenceNumber: string;
    sequenceNumberValue: number;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: number | null;
    serviceMessageValue: number;
    serviceMessageValueSpecified: boolean;
    serviceMessage: number | null;
    shareId: string;
    statementDescription: string;
    statusValue: number;
    statusValueSpecified: boolean;
    status: number | null;
    testProductionCode: string;
    tranTypeCode: string;
    transactionSequenceNumChar: string;
    transactionSequenceNumberValue: number;
    transactionSequenceNumberValueSpecified: boolean;
    transactionSequenceNumber: number | null;
    typeValue: number;
    typeValueSpecified: boolean;
    type: number | null;
    typeCode: string;
    upLoadedTimeValue: number;
    upLoadedTimeValueSpecified: boolean;
    upLoadedTime: number | null;
    uploadedDateValue: string | null;
    uploadedDateValueSpecified: boolean;
    uploadedDate: string | null;
    urcData: string;
    uscAuditTrailInfoValue: number;
    uscAuditTrailInfoValueSpecified: boolean;
    uscAuditTrailInfo: number | null;
    verificationMemberContactValue: number;
    verificationMemberContactValueSpecified: boolean;
    verificationMemberContact: number | null;
    verificationMemberContactName: string;
    verifiedByCorpUserValue: number;
    verifiedByCorpUserValueSpecified: boolean;
    verifiedByCorpUser: number | null;
    verifiedByCorpUserName: string;
    verifiedByMemberUserValue: number;
    verifiedByMemberUserValueSpecified: boolean;
    verifiedByMemberUser: number | null;
    verifiedByMemberUserName: string;
    verifiedDateValue: string | null;
    verifiedDateValueSpecified: boolean;
    verifiedDate: string | null;
    verifiedTimeValue: number;
    verifiedTimeValueSpecified: boolean;
    verifiedTime: number | null;
    verifiedValidationMethod: string;
    verifiedValidationReason: string;
    wireFor: string;
    version1: VersionType;
    cdtrAcctCurrency: string;
    cdtrAcctIban: string;
    cdtrAcctId: string;
    cdtrAcctIdCode: string;
    cdtrAcctIdIssuer: string;
    cdtrAcctIdProprietary: string;
    cdtrAcctName: WireCdtrAcctName_2[];
    cdtrAcctNameSpecified: boolean;
    cdtrAcctProxyCode: string;
    cdtrAcctProxyId: WireCdtrAcctProxyId_2[];
    cdtrAcctProxyIdSpecified: boolean;
    cdtrAcctProxyProprietary: string;
    cdtrAcctTypeCode: string;
    cdtrAcctTypeProprietary: string;
    cdtrAgtAcctCurrency: string;
    cdtrAgtAcctIban: string;
    cdtrAgtAcctId: string;
    cdtrAgtAcctIdCode: string;
    cdtrAgtAcctIdIssuer: string;
    cdtrAgtAcctIdProprietary: string;
    cdtrAgtAcctName: WireCdtrAgtAcctName_2[];
    cdtrAgtAcctNameSpecified: boolean;
    cdtrAgtAcctProxyCode: string;
    cdtrAgtAcctProxyId: WireCdtrAgtAcctProxyId_2[];
    cdtrAgtAcctProxyIdSpecified: boolean;
    cdtrAgtAcctProxyProprietary: string;
    cdtrAgtAcctTypeCode: string;
    cdtrAgtAcctTypeProprietary: string;
    chargeAgent1Bic: string;
    chargeAgent1BuildingName: string;
    chargeAgent1BuildingNum: string;
    chargeAgent1ClrSysMemId: string;
    chargeAgent1ClrSysMemIdCode: string;
    chargeAgent1Country: string;
    chargeAgent1CountrySubDiv: string;
    chargeAgent1Department: WireChargeAgent1Department_2[];
    chargeAgent1DepartmentSpecified: boolean;
    chargeAgent1DistrictName: string;
    chargeAgent1Floor: WireChargeAgent1Floor_2[];
    chargeAgent1FloorSpecified: boolean;
    chargeAgent1Lei: string;
    chargeAgent1Name: WireChargeAgent1Name_2[];
    chargeAgent1NameSpecified: boolean;
    chargeAgent1PostBox: string;
    chargeAgent1PostCode: string;
    chargeAgent1Room: WireChargeAgent1Room_2[];
    chargeAgent1RoomSpecified: boolean;
    chargeAgent1StreetName: WireChargeAgent1StreetName_2[];
    chargeAgent1StreetNameSpecified: boolean;
    chargeAgent1Subdepartment: WireChargeAgent1Subdepartment_2[];
    chargeAgent1SubdepartmentSpecified: boolean;
    chargeAgent1TownLocationName: string;
    chargeAgent1TownName: string;
    chargeAgent2Bic: string;
    chargeAgent2BuildingName: string;
    chargeAgent2BuildingNum: string;
    chargeAgent2ClrSysMemId: string;
    chargeAgent2ClrSysMemIdCode: string;
    chargeAgent2Country: string;
    chargeAgent2CountrySubDiv: string;
    chargeAgent2Department: WireChargeAgent2Department_2[];
    chargeAgent2DepartmentSpecified: boolean;
    chargeAgent2DistrictName: string;
    chargeAgent2Floor: WireChargeAgent2Floor_2[];
    chargeAgent2FloorSpecified: boolean;
    chargeAgent2Lei: string;
    chargeAgent2Name: WireChargeAgent2Name_2[];
    chargeAgent2NameSpecified: boolean;
    chargeAgent2PostBox: string;
    chargeAgent2PostCode: string;
    chargeAgent2Room: WireChargeAgent2Room_2[];
    chargeAgent2RoomSpecified: boolean;
    chargeAgent2StreetName: WireChargeAgent2StreetName_2[];
    chargeAgent2StreetNameSpecified: boolean;
    chargeAgent2Subdepartment: WireChargeAgent2Subdepartment_2[];
    chargeAgent2SubdepartmentSpecified: boolean;
    chargeAgent2TownLocationName: string;
    chargeAgent2TownName: string;
    chargeAgent3Bic: string;
    chargeAgent3BuildingName: string;
    chargeAgent3BuildingNum: string;
    chargeAgent3ClrSysMemId: string;
    chargeAgent3ClrSysMemIdCode: string;
    chargeAgent3Country: string;
    chargeAgent3CountrySubDiv: string;
    chargeAgent3Department: WireChargeAgent3Department_2[];
    chargeAgent3DepartmentSpecified: boolean;
    chargeAgent3DistrictName: string;
    chargeAgent3Floor: WireChargeAgent3Floor_2[];
    chargeAgent3FloorSpecified: boolean;
    chargeAgent3Lei: string;
    chargeAgent3Name: WireChargeAgent3Name_2[];
    chargeAgent3NameSpecified: boolean;
    chargeAgent3PostBox: string;
    chargeAgent3PostCode: string;
    chargeAgent3Room: WireChargeAgent3Room_2[];
    chargeAgent3RoomSpecified: boolean;
    chargeAgent3StreetName: WireChargeAgent3StreetName_2[];
    chargeAgent3StreetNameSpecified: boolean;
    chargeAgent3Subdepartment: WireChargeAgent3Subdepartment_2[];
    chargeAgent3SubdepartmentSpecified: boolean;
    chargeAgent3TownLocationName: string;
    chargeAgent3TownName: string;
    chargeAgent4Bic: string;
    chargeAgent4BuildingName: string;
    chargeAgent4BuildingNum: string;
    chargeAgent4ClrSysMemId: string;
    chargeAgent4ClrSysMemIdCode: string;
    chargeAgent4Country: string;
    chargeAgent4CountrySubDiv: string;
    chargeAgent4Department: WireChargeAgent4Department_2[];
    chargeAgent4DepartmentSpecified: boolean;
    chargeAgent4DistrictName: string;
    chargeAgent4Floor: WireChargeAgent4Floor_2[];
    chargeAgent4FloorSpecified: boolean;
    chargeAgent4Lei: string;
    chargeAgent4Name: WireChargeAgent4Name_2[];
    chargeAgent4NameSpecified: boolean;
    chargeAgent4PostBox: string;
    chargeAgent4PostCode: string;
    chargeAgent4Room: WireChargeAgent4Room_2[];
    chargeAgent4RoomSpecified: boolean;
    chargeAgent4StreetName: WireChargeAgent4StreetName_2[];
    chargeAgent4StreetNameSpecified: boolean;
    chargeAgent4Subdepartment: WireChargeAgent4Subdepartment_2[];
    chargeAgent4SubdepartmentSpecified: boolean;
    chargeAgent4TownLocationName: string;
    chargeAgent4TownName: string;
    chargeBearerValue: number;
    chargeBearerValueSpecified: boolean;
    chargeBearer: number | null;
    creationDateTime: string;
    creditorAgentBuildingName: string;
    creditorAgentBuildingNum: string;
    creditorAgentClrSysMemId: string;
    creditorAgentClrSysMemIdCode: string;
    creditorAgentCountry: string;
    creditorAgentCountrySubDiv: string;
    creditorAgentDepartment: WireCreditorAgentDepartment_2[];
    creditorAgentDepartmentSpecified: boolean;
    creditorAgentDistrictName: string;
    creditorAgentFiBic: string;
    creditorAgentFiLei: string;
    creditorAgentFiName: WireCreditorAgentFiName_2[];
    creditorAgentFiNameSpecified: boolean;
    creditorAgentFloor: WireCreditorAgentFloor_2[];
    creditorAgentFloorSpecified: boolean;
    creditorAgentPostBox: string;
    creditorAgentPostCode: string;
    creditorAgentRoom: WireCreditorAgentRoom_2[];
    creditorAgentRoomSpecified: boolean;
    creditorAgentStreetName: WireCreditorAgentStreetName_2[];
    creditorAgentStreetNameSpecified: boolean;
    creditorAgentSubdepartment: WireCreditorAgentSubdepartment_2[];
    creditorAgentSubdepartmentSpecified: boolean;
    creditorAgentTownLocationName: string;
    creditorAgentTownName: string;
    creditorBic: string;
    creditorBuildingName: string;
    creditorBuildingNum: string;
    creditorCountry: string;
    creditorCountrySubDiv: string;
    creditorDepartment: WireCreditorDepartment_2[];
    creditorDepartmentSpecified: boolean;
    creditorDistrictName: string;
    creditorFloor: WireCreditorFloor_2[];
    creditorFloorSpecified: boolean;
    creditorId: string;
    creditorIdSchemeCode: string;
    creditorIdSchemeName: string;
    creditorIssuer: string;
    creditorLei: string;
    creditorName: WireCreditorName_2[];
    creditorNameSpecified: boolean;
    creditorPostBox: string;
    creditorPostCode: string;
    creditorRoom: WireCreditorRoom_2[];
    creditorRoomSpecified: boolean;
    creditorStreetName: WireCreditorStreetName_2[];
    creditorStreetNameSpecified: boolean;
    creditorSubdepartment: WireCreditorSubdepartment_2[];
    creditorSubdepartmentSpecified: boolean;
    creditorTownLocationName: string;
    creditorTownName: string;
    dbtrAgtAcctCurrency: string;
    dbtrAgtAcctIban: string;
    dbtrAgtAcctId: string;
    dbtrAgtAcctIdCode: string;
    dbtrAgtAcctIdIssuer: string;
    dbtrAgtAcctIdProprietary: string;
    dbtrAgtAcctName: WireDbtrAgtAcctName_2[];
    dbtrAgtAcctNameSpecified: boolean;
    dbtrAgtAcctProxyCode: string;
    dbtrAgtAcctProxyId: WireDbtrAgtAcctProxyId_2[];
    dbtrAgtAcctProxyIdSpecified: boolean;
    dbtrAgtAcctProxyProprietary: string;
    dbtrAgtAcctTypeCode: string;
    dbtrAgtAcctTypeProprietary: string;
    debtorAcctCurrency: string;
    debtorAcctIban: string;
    debtorAcctId: string;
    debtorAcctIdCode: string;
    debtorAcctIdIssuer: string;
    debtorAcctIdProprietary: string;
    debtorAcctName: WireDebtorAcctName_2[];
    debtorAcctNameSpecified: boolean;
    debtorAcctProxyCode: string;
    debtorAcctProxyId: WireDebtorAcctProxyId_2[];
    debtorAcctProxyIdSpecified: boolean;
    debtorAcctProxyProprietary: string;
    debtorAcctTypeCode: string;
    debtorAcctTypeProprietary: string;
    debtorAgentBic: string;
    debtorAgentBuildingName: string;
    debtorAgentBuildingNum: string;
    debtorAgentClrSysMemId: string;
    debtorAgentClrSysMemIdCode: string;
    debtorAgentCountry: string;
    debtorAgentCountrySubDiv: string;
    debtorAgentDepartment: WireDebtorAgentDepartment_2[];
    debtorAgentDepartmentSpecified: boolean;
    debtorAgentDistrictName: string;
    debtorAgentFloor: WireDebtorAgentFloor_2[];
    debtorAgentFloorSpecified: boolean;
    debtorAgentLei: string;
    debtorAgentName: WireDebtorAgentName_2[];
    debtorAgentNameSpecified: boolean;
    debtorAgentPostBox: string;
    debtorAgentPostCode: string;
    debtorAgentRoom: WireDebtorAgentRoom_2[];
    debtorAgentRoomSpecified: boolean;
    debtorAgentStreetName: WireDebtorAgentStreetName_2[];
    debtorAgentStreetNameSpecified: boolean;
    debtorAgentSubdepartment: WireDebtorAgentSubdepartment_2[];
    debtorAgentSubdepartmentSpecified: boolean;
    debtorAgentTownLocationName: string;
    debtorAgentTownName: string;
    debtorBic: string;
    debtorBuildingName: string;
    debtorBuildingNum: string;
    debtorCountry: string;
    debtorCountrySubDiv: string;
    debtorDepartment: WireDebtorDepartment_2[];
    debtorDepartmentSpecified: boolean;
    debtorDistrictName: string;
    debtorFloor: WireDebtorFloor_2[];
    debtorFloorSpecified: boolean;
    debtorId: string;
    debtorIdSchemeCode: string;
    debtorIdSchemeName: string;
    debtorIssuer: string;
    debtorLei: string;
    debtorName: WireDebtorName_2[];
    debtorNameSpecified: boolean;
    debtorPostBox: string;
    debtorPostCode: string;
    debtorRoom: WireDebtorRoom_2[];
    debtorRoomSpecified: boolean;
    debtorStreetName: WireDebtorStreetName_2[];
    debtorStreetNameSpecified: boolean;
    debtorSubdepartment: WireDebtorSubdepartment_2[];
    debtorSubdepartmentSpecified: boolean;
    debtorTownLocationName: string;
    debtorTownName: string;
    initgPtyBuildingName: string;
    initgPtyBuildingNum: string;
    initgPtyCountry: string;
    initgPtyCountrySubDiv: string;
    initgPtyCtryOfRes: string;
    initgPtyDepartment: WireInitgPtyDepartment_2[];
    initgPtyDepartmentSpecified: boolean;
    initgPtyDistrictName: string;
    initgPtyFloor: WireInitgPtyFloor_2[];
    initgPtyFloorSpecified: boolean;
    initgPtyName: WireInitgPtyName_2[];
    initgPtyNameSpecified: boolean;
    initgPtyOrgId: string;
    initgPtyOrgIdBic: string;
    initgPtyOrgIdIssuer: string;
    initgPtyOrgIdLei: string;
    initgPtyOrgIdSchemeCode: string;
    initgPtyOrgIdSchemePrtry: string;
    initgPtyPostBox: string;
    initgPtyPostCode: string;
    initgPtyPrvtIdBirthDt: string;
    initgPtyPrvtIdCityOfBirth: string;
    initgPtyPrvtIdCtryOfBirth: string;
    initgPtyPrvtIdId: string;
    initgPtyPrvtIdIdIssuer: string;
    initgPtyPrvtIdIdSchemeCode: string;
    initgPtyPrvtIdIdSchemePrtry: string;
    initgPtyPrvtIdPrvcOfBirth: string;
    initgPtyRoom: WireInitgPtyRoom_2[];
    initgPtyRoomSpecified: boolean;
    initgPtyStreetName: WireInitgPtyStreetName_2[];
    initgPtyStreetNameSpecified: boolean;
    initgPtySubdepartment: WireInitgPtySubdepartment_2[];
    initgPtySubdepartmentSpecified: boolean;
    initgPtyTownLocationName: string;
    initgPtyTownName: string;
    instr1ForCdtrAgtCodeValue: number;
    instr1ForCdtrAgtCodeValueSpecified: boolean;
    instr1ForCdtrAgtCode: number | null;
    instr1ForCdtrAgtInfo: WireInstr1ForCdtrAgtInfo_2[];
    instr1ForCdtrAgtInfoSpecified: boolean;
    instr2ForCdtrAgtCodeValue: number;
    instr2ForCdtrAgtCodeValueSpecified: boolean;
    instr2ForCdtrAgtCode: number | null;
    instr2ForCdtrAgtInfo: WireInstr2ForCdtrAgtInfo_2[];
    instr2ForCdtrAgtInfoSpecified: boolean;
    instructingFiName2: string;
    instructingFiName3: string;
    instructingFiName4: string;
    intermedFiBic: string;
    intermedFiBuildingName: string;
    intermedFiBuildingNum: string;
    intermedFiClrSysMemIdCode: string;
    intermedFiCountry: string;
    intermedFiCountrySubDiv: string;
    intermedFiDepartment: WireIntermedFiDepartment_2[];
    intermedFiDepartmentSpecified: boolean;
    intermedFiDistrictName: string;
    intermedFiFloor: WireIntermedFiFloor_2[];
    intermedFiFloorSpecified: boolean;
    intermedFiLei: string;
    intermedFiPostBox: string;
    intermedFiPostCode: string;
    intermedFiRoom: WireIntermedFiRoom_2[];
    intermedFiRoomSpecified: boolean;
    intermedFiStreetName: WireIntermedFiStreetName_2[];
    intermedFiStreetNameSpecified: boolean;
    intermedFiSubdepartment: WireIntermedFiSubdepartment_2[];
    intermedFiSubdepartmentSpecified: boolean;
    intermedFiTownLocationName: string;
    intermedFiTownName: string;
    intermediaryFiName2: string;
    intermediaryFiName3: string;
    intermediaryFiName4: string;
    intrmyAgt1AcctCurrency: string;
    intrmyAgt1AcctIban: string;
    intrmyAgt1AcctId: string;
    intrmyAgt1AcctIdCode: string;
    intrmyAgt1AcctIdIssuer: string;
    intrmyAgt1AcctIdProprietary: string;
    intrmyAgt1AcctName: WireIntrmyAgt1AcctName_2[];
    intrmyAgt1AcctNameSpecified: boolean;
    intrmyAgt1AcctProxyCode: string;
    intrmyAgt1AcctProxyId: WireIntrmyAgt1AcctProxyId_2[];
    intrmyAgt1AcctProxyIdSpecified: boolean;
    intrmyAgt1AcctProxyProprietary: string;
    intrmyAgt1AcctTypeCode: string;
    intrmyAgt1AcctTypeProprietary: string;
    messageTypeValue: number;
    messageTypeValueSpecified: boolean;
    messageType: number | null;
    prevInstrAgentAcctCurrency: string;
    prevInstrAgentAcctIban: string;
    prevInstrAgentAcctId: string;
    prevInstrAgentAcctIdCode: string;
    prevInstrAgentAcctIdIssuer: string;
    prevInstrAgentAcctIdProprietary: string;
    prevInstrAgentAcctName: WirePrevInstrAgentAcctName_2[];
    prevInstrAgentAcctNameSpecified: boolean;
    prevInstrAgentAcctProxyCode: string;
    prevInstrAgentAcctProxyId: WirePrevInstrAgentAcctProxyId_2[];
    prevInstrAgentAcctProxyIdSpecified: boolean;
    prevInstrAgentAcctProxyPrtry: string;
    prevInstrAgentAcctTypeCode: string;
    prevInstrAgentAcctTypePrtry: string;
    prevInstrAgentBuildingName: string;
    prevInstrAgentBuildingNum: string;
    prevInstrAgentCountry: string;
    prevInstrAgentCountrySubDiv: string;
    prevInstrAgentDepartment: WirePrevInstrAgentDepartment_2[];
    prevInstrAgentDepartmentSpecified: boolean;
    prevInstrAgentDistrictName: string;
    prevInstrAgentFloor: WirePrevInstrAgentFloor_2[];
    prevInstrAgentFloorSpecified: boolean;
    prevInstrAgentPostBox: string;
    prevInstrAgentPostCode: string;
    prevInstrAgentRoom: WirePrevInstrAgentRoom_2[];
    prevInstrAgentRoomSpecified: boolean;
    prevInstrAgentStreetName: WirePrevInstrAgentStreetName_2[];
    prevInstrAgentStreetNameSpecified: boolean;
    prevInstrAgentSubdepartment: WirePrevInstrAgentSubdepartment_2[];
    prevInstrAgentSubdepartmentSpecified: boolean;
    prevInstrAgentTownName: string;
    prevInstrAgtTownLocationName: string;
    prevInstructAgentBic: string;
    prevInstructAgentClrSysMemIdCode: string;
    prevInstructAgentLei: string;
    prevMsgCreationDateTime: string;
    prevMsgNameId: string;
    returnReasonCode: string;
    transactionId: string;
    uetr: string;
    ultmtCdtrBuildingName: string;
    ultmtCdtrBuildingNum: string;
    ultmtCdtrCountry: string;
    ultmtCdtrCountrySubDiv: string;
    ultmtCdtrCtryOfRes: string;
    ultmtCdtrDepartment: WireUltmtCdtrDepartment_2[];
    ultmtCdtrDepartmentSpecified: boolean;
    ultmtCdtrDistrictName: string;
    ultmtCdtrFloor: WireUltmtCdtrFloor_2[];
    ultmtCdtrFloorSpecified: boolean;
    ultmtCdtrName: WireUltmtCdtrName_2[];
    ultmtCdtrNameSpecified: boolean;
    ultmtCdtrOrgId: string;
    ultmtCdtrOrgIdBic: string;
    ultmtCdtrOrgIdIssuer: string;
    ultmtCdtrOrgIdLei: string;
    ultmtCdtrOrgIdSchemeCode: string;
    ultmtCdtrOrgIdSchemePrtry: string;
    ultmtCdtrPostBox: string;
    ultmtCdtrPostCode: string;
    ultmtCdtrPrvtIdBirthDt: string;
    ultmtCdtrPrvtIdCityOfBirth: string;
    ultmtCdtrPrvtIdCtryOfBirth: string;
    ultmtCdtrPrvtIdId: string;
    ultmtCdtrPrvtIdIdIssuer: string;
    ultmtCdtrPrvtIdIdSchemeCode: string;
    ultmtCdtrPrvtIdIdSchemePrtry: string;
    ultmtCdtrPrvtIdPrvcOfBirth: string;
    ultmtCdtrRoom: WireUltmtCdtrRoom_2[];
    ultmtCdtrRoomSpecified: boolean;
    ultmtCdtrStreetName: WireUltmtCdtrStreetName_2[];
    ultmtCdtrStreetNameSpecified: boolean;
    ultmtCdtrSubdepartment: WireUltmtCdtrSubdepartment_2[];
    ultmtCdtrSubdepartmentSpecified: boolean;
    ultmtCdtrTownLocationName: string;
    ultmtCdtrTownName: string;
    ultmtDbtrBuildingName: string;
    ultmtDbtrBuildingNum: string;
    ultmtDbtrCountry: string;
    ultmtDbtrCountrySubDiv: string;
    ultmtDbtrCtryOfRes: string;
    ultmtDbtrDepartment: WireUltmtDbtrDepartment_2[];
    ultmtDbtrDepartmentSpecified: boolean;
    ultmtDbtrDistrictName: string;
    ultmtDbtrFloor: WireUltmtDbtrFloor_2[];
    ultmtDbtrFloorSpecified: boolean;
    ultmtDbtrName: WireUltmtDbtrName_2[];
    ultmtDbtrNameSpecified: boolean;
    ultmtDbtrOrgId: string;
    ultmtDbtrOrgIdBic: string;
    ultmtDbtrOrgIdIssuer: string;
    ultmtDbtrOrgIdLei: string;
    ultmtDbtrOrgIdSchemeCode: string;
    ultmtDbtrOrgIdSchemePrtry: string;
    ultmtDbtrPostBox: string;
    ultmtDbtrPostCode: string;
    ultmtDbtrPrvtIdBirthDt: string;
    ultmtDbtrPrvtIdCityOfBirth: string;
    ultmtDbtrPrvtIdCtryOfBirth: string;
    ultmtDbtrPrvtIdId: string;
    ultmtDbtrPrvtIdIdIssuer: string;
    ultmtDbtrPrvtIdIdSchemeCode: string;
    ultmtDbtrPrvtIdIdSchemePrtry: string;
    ultmtDbtrPrvtIdPrvcOfBirth: string;
    ultmtDbtrRoom: WireUltmtDbtrRoom_2[];
    ultmtDbtrRoomSpecified: boolean;
    ultmtDbtrStreetName: WireUltmtDbtrStreetName_2[];
    ultmtDbtrStreetNameSpecified: boolean;
    ultmtDbtrSubdepartment: WireUltmtDbtrSubdepartment_2[];
    ultmtDbtrSubdepartmentSpecified: boolean;
    ultmtDbtrTownLocationName: string;
    ultmtDbtrTownName: string;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}