import { VersionType } from "./versionType";

export interface WireFields {
    acceptanceDate: boolean | null;
    acceptanceTime: boolean | null;
    accountNumber: boolean | null;
    adjustmentDate: boolean | null;
    adjustmentReason: boolean | null;
    amount: boolean | null;
    applicationId: boolean | null;
    batchNumber: boolean | null;
    batchNumberChar: boolean | null;
    beneficiaryAddress: number[];
    beneficiaryAdvice: boolean | null;
    beneficiaryAdviceCode: boolean | null;
    beneficiaryFiAddress: number[];
    beneficiaryFiAdvice: boolean | null;
    beneficiaryFiAdviceCode: boolean | null;
    beneficiaryFiId: boolean | null;
    beneficiaryFiIdCode: boolean | null;
    beneficiaryFiInfo: boolean | null;
    beneficiaryFiIntrnatlId: boolean | null;
    beneficiaryFiName: boolean | null;
    beneficiaryId: boolean | null;
    beneficiaryIdCode: boolean | null;
    beneficiaryInfo: boolean | null;
    beneficiaryName: boolean | null;
    beneficiaryReference: boolean | null;
    businessFunctionCode: boolean | null;
    chargesCurrencyCode: number[];
    commentCode: boolean | null;
    destination: boolean | null;
    detailOfCharges: boolean | null;
    direction: boolean | null;
    drawdownCreditAccount: boolean | null;
    drawdownDebitAccountAddress: number[];
    drawdownDebitAccountId: boolean | null;
    drawdownDebitAccountIdCode: boolean | null;
    drawdownDebitAccountName: boolean | null;
    drawdownDebitAcctAdvice: boolean | null;
    drawdownDebitAcctAdviceCode: boolean | null;
    effectiveDate: boolean | null;
    enteredByCorporateUser: boolean | null;
    enteredByCorporateUserName: boolean | null;
    enteredByMemberUser: boolean | null;
    enteredByMemberUserName: boolean | null;
    enteredDate: boolean | null;
    enteredTime: boolean | null;
    enteredValidationMethod: boolean | null;
    errorCategory: boolean | null;
    errorCode: boolean | null;
    errorDescription: boolean | null;
    exchangeRate: boolean | null;
    extractDestination: boolean | null;
    extractedByCorporateUser: boolean | null;
    extractedByCorporateUserName: boolean | null;
    extractedDate: boolean | null;
    extractedTime: boolean | null;
    fiToFiInfo: boolean | null;
    fmLastPurgeDate: boolean | null;
    formatVersion: boolean | null;
    glAccount: boolean | null;
    glCommentAddlInfo: boolean | null;
    glOffset: boolean | null;
    imad: boolean | null;
    instructIngFiAddress: number[];
    instructIngFiId: boolean | null;
    instructIngFiIdCode: boolean | null;
    instructedAmount: boolean | null;
    instructedAmtCurrencyCode: boolean | null;
    instructingFiName: boolean | null;
    intermediaryFiAddress: number[];
    intermediaryFiAdvice: boolean | null;
    intermediaryFiAdviceCode: boolean | null;
    intermediaryFiId: boolean | null;
    intermediaryFiIdCode: boolean | null;
    intermediaryFiInfo: boolean | null;
    intermediaryFiName: boolean | null;
    lastFmDate: boolean | null;
    messageDuplicationCode: boolean | null;
    messageStatusIndicator: boolean | null;
    notificationDate: boolean | null;
    notificationMethod: boolean | null;
    notificationStatus: boolean | null;
    notificationTime: boolean | null;
    notificationUser: boolean | null;
    ofacDetails: boolean | null;
    ofacStatus: boolean | null;
    omad: boolean | null;
    originatorAddress: number[];
    originatorFiAddress: number[];
    originatorFiId: boolean | null;
    originatorFiIdCode: boolean | null;
    originatorFiName: boolean | null;
    originatorId: boolean | null;
    originatorIdCode: boolean | null;
    originatorIdF: boolean | null;
    originatorLineCodeF: number[];
    originatorLineF: number[];
    originatorName: boolean | null;
    originatorNameF: boolean | null;
    originatorPartyIdF: boolean | null;
    originatorToBeneficiaryInfo: number[];
    otherAddLinFo: boolean | null;
    paymentLimitation: boolean | null;
    paymentMethod: boolean | null;
    paymentMethodCode: boolean | null;
    postingError: boolean | null;
    preAuthTemplateName: boolean | null;
    preAuthTemplateNumber: boolean | null;
    previousMessageImad: boolean | null;
    receiverFi: boolean | null;
    receiverFiInfo: boolean | null;
    receiverName: boolean | null;
    regETran: boolean | null;
    releasedByCorporateUser: boolean | null;
    releasedByCorporateUserName: boolean | null;
    releasedDate: boolean | null;
    releasedReason: boolean | null;
    releasedTime: boolean | null;
    returnRejectByCorpUser: boolean | null;
    returnRejectByCorpUserName: boolean | null;
    returnRejectDate: boolean | null;
    returnRejectReason: boolean | null;
    returnRejectTime: boolean | null;
    senderCharges: number[];
    senderFi: boolean | null;
    senderName: boolean | null;
    senderReferenceNumber: boolean | null;
    sequenceNumber: boolean | null;
    serviceMessage: boolean | null;
    shareId: boolean | null;
    statementDescription: boolean | null;
    status: boolean | null;
    testProductionCode: boolean | null;
    tranTypeCode: boolean | null;
    transactionSequenceNumChar: boolean | null;
    transactionSequenceNumber: boolean | null;
    type: boolean | null;
    typeCode: boolean | null;
    upLoadedTime: boolean | null;
    uploadedDate: boolean | null;
    urcData: boolean | null;
    uscAuditTrailInfo: boolean | null;
    verificationMemberContact: boolean | null;
    verificationMemberContactName: boolean | null;
    verifiedByCorpUser: boolean | null;
    verifiedByCorpUserName: boolean | null;
    verifiedByMemberUser: boolean | null;
    verifiedByMemberUserName: boolean | null;
    verifiedDate: boolean | null;
    verifiedTime: boolean | null;
    verifiedValidationMethod: boolean | null;
    verifiedValidationReason: boolean | null;
    wireFor: boolean | null;
    version1: VersionType;
    cdtrAcctCurrency: boolean | null;
    cdtrAcctIban: boolean | null;
    cdtrAcctId: boolean | null;
    cdtrAcctIdCode: boolean | null;
    cdtrAcctIdIssuer: boolean | null;
    cdtrAcctIdProprietary: boolean | null;
    cdtrAcctName: number[];
    cdtrAcctProxyCode: boolean | null;
    cdtrAcctProxyId: number[];
    cdtrAcctProxyProprietary: boolean | null;
    cdtrAcctTypeCode: boolean | null;
    cdtrAcctTypeProprietary: boolean | null;
    cdtrAgtAcctCurrency: boolean | null;
    cdtrAgtAcctIban: boolean | null;
    cdtrAgtAcctId: boolean | null;
    cdtrAgtAcctIdCode: boolean | null;
    cdtrAgtAcctIdIssuer: boolean | null;
    cdtrAgtAcctIdProprietary: boolean | null;
    cdtrAgtAcctName: number[];
    cdtrAgtAcctProxyCode: boolean | null;
    cdtrAgtAcctProxyId: number[];
    cdtrAgtAcctProxyProprietary: boolean | null;
    cdtrAgtAcctTypeCode: boolean | null;
    cdtrAgtAcctTypeProprietary: boolean | null;
    chargeAgent1Bic: boolean | null;
    chargeAgent1BuildingName: boolean | null;
    chargeAgent1BuildingNum: boolean | null;
    chargeAgent1ClrSysMemId: boolean | null;
    chargeAgent1ClrSysMemIdCode: boolean | null;
    chargeAgent1Country: boolean | null;
    chargeAgent1CountrySubDiv: boolean | null;
    chargeAgent1Department: number[];
    chargeAgent1DistrictName: boolean | null;
    chargeAgent1Floor: number[];
    chargeAgent1Lei: boolean | null;
    chargeAgent1Name: number[];
    chargeAgent1PostBox: boolean | null;
    chargeAgent1PostCode: boolean | null;
    chargeAgent1Room: number[];
    chargeAgent1StreetName: number[];
    chargeAgent1Subdepartment: number[];
    chargeAgent1TownLocationName: boolean | null;
    chargeAgent1TownName: boolean | null;
    chargeAgent2Bic: boolean | null;
    chargeAgent2BuildingName: boolean | null;
    chargeAgent2BuildingNum: boolean | null;
    chargeAgent2ClrSysMemId: boolean | null;
    chargeAgent2ClrSysMemIdCode: boolean | null;
    chargeAgent2Country: boolean | null;
    chargeAgent2CountrySubDiv: boolean | null;
    chargeAgent2Department: number[];
    chargeAgent2DistrictName: boolean | null;
    chargeAgent2Floor: number[];
    chargeAgent2Lei: boolean | null;
    chargeAgent2Name: number[];
    chargeAgent2PostBox: boolean | null;
    chargeAgent2PostCode: boolean | null;
    chargeAgent2Room: number[];
    chargeAgent2StreetName: number[];
    chargeAgent2Subdepartment: number[];
    chargeAgent2TownLocationName: boolean | null;
    chargeAgent2TownName: boolean | null;
    chargeAgent3Bic: boolean | null;
    chargeAgent3BuildingName: boolean | null;
    chargeAgent3BuildingNum: boolean | null;
    chargeAgent3ClrSysMemId: boolean | null;
    chargeAgent3ClrSysMemIdCode: boolean | null;
    chargeAgent3Country: boolean | null;
    chargeAgent3CountrySubDiv: boolean | null;
    chargeAgent3Department: number[];
    chargeAgent3DistrictName: boolean | null;
    chargeAgent3Floor: number[];
    chargeAgent3Lei: boolean | null;
    chargeAgent3Name: number[];
    chargeAgent3PostBox: boolean | null;
    chargeAgent3PostCode: boolean | null;
    chargeAgent3Room: number[];
    chargeAgent3StreetName: number[];
    chargeAgent3Subdepartment: number[];
    chargeAgent3TownLocationName: boolean | null;
    chargeAgent3TownName: boolean | null;
    chargeAgent4Bic: boolean | null;
    chargeAgent4BuildingName: boolean | null;
    chargeAgent4BuildingNum: boolean | null;
    chargeAgent4ClrSysMemId: boolean | null;
    chargeAgent4ClrSysMemIdCode: boolean | null;
    chargeAgent4Country: boolean | null;
    chargeAgent4CountrySubDiv: boolean | null;
    chargeAgent4Department: number[];
    chargeAgent4DistrictName: boolean | null;
    chargeAgent4Floor: number[];
    chargeAgent4Lei: boolean | null;
    chargeAgent4Name: number[];
    chargeAgent4PostBox: boolean | null;
    chargeAgent4PostCode: boolean | null;
    chargeAgent4Room: number[];
    chargeAgent4StreetName: number[];
    chargeAgent4Subdepartment: number[];
    chargeAgent4TownLocationName: boolean | null;
    chargeAgent4TownName: boolean | null;
    chargeBearer: boolean | null;
    creationDateTime: boolean | null;
    creditorAgentBuildingName: boolean | null;
    creditorAgentBuildingNum: boolean | null;
    creditorAgentClrSysMemId: boolean | null;
    creditorAgentClrSysMemIdCode: boolean | null;
    creditorAgentCountry: boolean | null;
    creditorAgentCountrySubDiv: boolean | null;
    creditorAgentDepartment: number[];
    creditorAgentDistrictName: boolean | null;
    creditorAgentFiBic: boolean | null;
    creditorAgentFiLei: boolean | null;
    creditorAgentFiName: number[];
    creditorAgentFloor: number[];
    creditorAgentPostBox: boolean | null;
    creditorAgentPostCode: boolean | null;
    creditorAgentRoom: number[];
    creditorAgentStreetName: number[];
    creditorAgentSubdepartment: number[];
    creditorAgentTownLocationName: boolean | null;
    creditorAgentTownName: boolean | null;
    creditorBic: boolean | null;
    creditorBuildingName: boolean | null;
    creditorBuildingNum: boolean | null;
    creditorCountry: boolean | null;
    creditorCountrySubDiv: boolean | null;
    creditorDepartment: number[];
    creditorDistrictName: boolean | null;
    creditorFloor: number[];
    creditorId: boolean | null;
    creditorIdSchemeCode: boolean | null;
    creditorIdSchemeName: boolean | null;
    creditorIssuer: boolean | null;
    creditorLei: boolean | null;
    creditorName: number[];
    creditorPostBox: boolean | null;
    creditorPostCode: boolean | null;
    creditorRoom: number[];
    creditorStreetName: number[];
    creditorSubdepartment: number[];
    creditorTownLocationName: boolean | null;
    creditorTownName: boolean | null;
    dbtrAgtAcctCurrency: boolean | null;
    dbtrAgtAcctIban: boolean | null;
    dbtrAgtAcctId: boolean | null;
    dbtrAgtAcctIdCode: boolean | null;
    dbtrAgtAcctIdIssuer: boolean | null;
    dbtrAgtAcctIdProprietary: boolean | null;
    dbtrAgtAcctName: number[];
    dbtrAgtAcctProxyCode: boolean | null;
    dbtrAgtAcctProxyId: number[];
    dbtrAgtAcctProxyProprietary: boolean | null;
    dbtrAgtAcctTypeCode: boolean | null;
    dbtrAgtAcctTypeProprietary: boolean | null;
    debtorAcctCurrency: boolean | null;
    debtorAcctIban: boolean | null;
    debtorAcctId: boolean | null;
    debtorAcctIdCode: boolean | null;
    debtorAcctIdIssuer: boolean | null;
    debtorAcctIdProprietary: boolean | null;
    debtorAcctName: number[];
    debtorAcctProxyCode: boolean | null;
    debtorAcctProxyId: number[];
    debtorAcctProxyProprietary: boolean | null;
    debtorAcctTypeCode: boolean | null;
    debtorAcctTypeProprietary: boolean | null;
    debtorAgentBic: boolean | null;
    debtorAgentBuildingName: boolean | null;
    debtorAgentBuildingNum: boolean | null;
    debtorAgentClrSysMemId: boolean | null;
    debtorAgentClrSysMemIdCode: boolean | null;
    debtorAgentCountry: boolean | null;
    debtorAgentCountrySubDiv: boolean | null;
    debtorAgentDepartment: number[];
    debtorAgentDistrictName: boolean | null;
    debtorAgentFloor: number[];
    debtorAgentLei: boolean | null;
    debtorAgentName: number[];
    debtorAgentPostBox: boolean | null;
    debtorAgentPostCode: boolean | null;
    debtorAgentRoom: number[];
    debtorAgentStreetName: number[];
    debtorAgentSubdepartment: number[];
    debtorAgentTownLocationName: boolean | null;
    debtorAgentTownName: boolean | null;
    debtorBic: boolean | null;
    debtorBuildingName: boolean | null;
    debtorBuildingNum: boolean | null;
    debtorCountry: boolean | null;
    debtorCountrySubDiv: boolean | null;
    debtorDepartment: number[];
    debtorDistrictName: boolean | null;
    debtorFloor: number[];
    debtorId: boolean | null;
    debtorIdSchemeCode: boolean | null;
    debtorIdSchemeName: boolean | null;
    debtorIssuer: boolean | null;
    debtorLei: boolean | null;
    debtorName: number[];
    debtorPostBox: boolean | null;
    debtorPostCode: boolean | null;
    debtorRoom: number[];
    debtorStreetName: number[];
    debtorSubdepartment: number[];
    debtorTownLocationName: boolean | null;
    debtorTownName: boolean | null;
    initgPtyBuildingName: boolean | null;
    initgPtyBuildingNum: boolean | null;
    initgPtyCountry: boolean | null;
    initgPtyCountrySubDiv: boolean | null;
    initgPtyCtryOfRes: boolean | null;
    initgPtyDepartment: number[];
    initgPtyDistrictName: boolean | null;
    initgPtyFloor: number[];
    initgPtyName: number[];
    initgPtyOrgId: boolean | null;
    initgPtyOrgIdBic: boolean | null;
    initgPtyOrgIdIssuer: boolean | null;
    initgPtyOrgIdLei: boolean | null;
    initgPtyOrgIdSchemeCode: boolean | null;
    initgPtyOrgIdSchemePrtry: boolean | null;
    initgPtyPostBox: boolean | null;
    initgPtyPostCode: boolean | null;
    initgPtyPrvtIdBirthDt: boolean | null;
    initgPtyPrvtIdCityOfBirth: boolean | null;
    initgPtyPrvtIdCtryOfBirth: boolean | null;
    initgPtyPrvtIdId: boolean | null;
    initgPtyPrvtIdIdIssuer: boolean | null;
    initgPtyPrvtIdIdSchemeCode: boolean | null;
    initgPtyPrvtIdIdSchemePrtry: boolean | null;
    initgPtyPrvtIdPrvcOfBirth: boolean | null;
    initgPtyRoom: number[];
    initgPtyStreetName: number[];
    initgPtySubdepartment: number[];
    initgPtyTownLocationName: boolean | null;
    initgPtyTownName: boolean | null;
    instr1ForCdtrAgtCode: boolean | null;
    instr1ForCdtrAgtInfo: number[];
    instr2ForCdtrAgtCode: boolean | null;
    instr2ForCdtrAgtInfo: number[];
    instructingFiName2: boolean | null;
    instructingFiName3: boolean | null;
    instructingFiName4: boolean | null;
    intermedFiBic: boolean | null;
    intermedFiBuildingName: boolean | null;
    intermedFiBuildingNum: boolean | null;
    intermedFiClrSysMemIdCode: boolean | null;
    intermedFiCountry: boolean | null;
    intermedFiCountrySubDiv: boolean | null;
    intermedFiDepartment: number[];
    intermedFiDistrictName: boolean | null;
    intermedFiFloor: number[];
    intermedFiLei: boolean | null;
    intermedFiPostBox: boolean | null;
    intermedFiPostCode: boolean | null;
    intermedFiRoom: number[];
    intermedFiStreetName: number[];
    intermedFiSubdepartment: number[];
    intermedFiTownLocationName: boolean | null;
    intermedFiTownName: boolean | null;
    intermediaryFiName2: boolean | null;
    intermediaryFiName3: boolean | null;
    intermediaryFiName4: boolean | null;
    intrmyAgt1AcctCurrency: boolean | null;
    intrmyAgt1AcctIban: boolean | null;
    intrmyAgt1AcctId: boolean | null;
    intrmyAgt1AcctIdCode: boolean | null;
    intrmyAgt1AcctIdIssuer: boolean | null;
    intrmyAgt1AcctIdProprietary: boolean | null;
    intrmyAgt1AcctName: number[];
    intrmyAgt1AcctProxyCode: boolean | null;
    intrmyAgt1AcctProxyId: number[];
    intrmyAgt1AcctProxyProprietary: boolean | null;
    intrmyAgt1AcctTypeCode: boolean | null;
    intrmyAgt1AcctTypeProprietary: boolean | null;
    messageType: boolean | null;
    prevInstrAgentAcctCurrency: boolean | null;
    prevInstrAgentAcctIban: boolean | null;
    prevInstrAgentAcctId: boolean | null;
    prevInstrAgentAcctIdCode: boolean | null;
    prevInstrAgentAcctIdIssuer: boolean | null;
    prevInstrAgentAcctIdProprietary: boolean | null;
    prevInstrAgentAcctName: number[];
    prevInstrAgentAcctProxyCode: boolean | null;
    prevInstrAgentAcctProxyId: number[];
    prevInstrAgentAcctProxyPrtry: boolean | null;
    prevInstrAgentAcctTypeCode: boolean | null;
    prevInstrAgentAcctTypePrtry: boolean | null;
    prevInstrAgentBuildingName: boolean | null;
    prevInstrAgentBuildingNum: boolean | null;
    prevInstrAgentCountry: boolean | null;
    prevInstrAgentCountrySubDiv: boolean | null;
    prevInstrAgentDepartment: number[];
    prevInstrAgentDistrictName: boolean | null;
    prevInstrAgentFloor: number[];
    prevInstrAgentPostBox: boolean | null;
    prevInstrAgentPostCode: boolean | null;
    prevInstrAgentRoom: number[];
    prevInstrAgentStreetName: number[];
    prevInstrAgentSubdepartment: number[];
    prevInstrAgentTownName: boolean | null;
    prevInstrAgtTownLocationName: boolean | null;
    prevInstructAgentBic: boolean | null;
    prevInstructAgentClrSysMemIdCode: boolean | null;
    prevInstructAgentLei: boolean | null;
    prevMsgCreationDateTime: boolean | null;
    prevMsgNameId: boolean | null;
    returnReasonCode: boolean | null;
    transactionId: boolean | null;
    uetr: boolean | null;
    ultmtCdtrBuildingName: boolean | null;
    ultmtCdtrBuildingNum: boolean | null;
    ultmtCdtrCountry: boolean | null;
    ultmtCdtrCountrySubDiv: boolean | null;
    ultmtCdtrCtryOfRes: boolean | null;
    ultmtCdtrDepartment: number[];
    ultmtCdtrDistrictName: boolean | null;
    ultmtCdtrFloor: number[];
    ultmtCdtrName: number[];
    ultmtCdtrOrgId: boolean | null;
    ultmtCdtrOrgIdBic: boolean | null;
    ultmtCdtrOrgIdIssuer: boolean | null;
    ultmtCdtrOrgIdLei: boolean | null;
    ultmtCdtrOrgIdSchemeCode: boolean | null;
    ultmtCdtrOrgIdSchemePrtry: boolean | null;
    ultmtCdtrPostBox: boolean | null;
    ultmtCdtrPostCode: boolean | null;
    ultmtCdtrPrvtIdBirthDt: boolean | null;
    ultmtCdtrPrvtIdCityOfBirth: boolean | null;
    ultmtCdtrPrvtIdCtryOfBirth: boolean | null;
    ultmtCdtrPrvtIdId: boolean | null;
    ultmtCdtrPrvtIdIdIssuer: boolean | null;
    ultmtCdtrPrvtIdIdSchemeCode: boolean | null;
    ultmtCdtrPrvtIdIdSchemePrtry: boolean | null;
    ultmtCdtrPrvtIdPrvcOfBirth: boolean | null;
    ultmtCdtrRoom: number[];
    ultmtCdtrStreetName: number[];
    ultmtCdtrSubdepartment: number[];
    ultmtCdtrTownLocationName: boolean | null;
    ultmtCdtrTownName: boolean | null;
    ultmtDbtrBuildingName: boolean | null;
    ultmtDbtrBuildingNum: boolean | null;
    ultmtDbtrCountry: boolean | null;
    ultmtDbtrCountrySubDiv: boolean | null;
    ultmtDbtrCtryOfRes: boolean | null;
    ultmtDbtrDepartment: number[];
    ultmtDbtrDistrictName: boolean | null;
    ultmtDbtrFloor: number[];
    ultmtDbtrName: number[];
    ultmtDbtrOrgId: boolean | null;
    ultmtDbtrOrgIdBic: boolean | null;
    ultmtDbtrOrgIdIssuer: boolean | null;
    ultmtDbtrOrgIdLei: boolean | null;
    ultmtDbtrOrgIdSchemeCode: boolean | null;
    ultmtDbtrOrgIdSchemePrtry: boolean | null;
    ultmtDbtrPostBox: boolean | null;
    ultmtDbtrPostCode: boolean | null;
    ultmtDbtrPrvtIdBirthDt: boolean | null;
    ultmtDbtrPrvtIdCityOfBirth: boolean | null;
    ultmtDbtrPrvtIdCtryOfBirth: boolean | null;
    ultmtDbtrPrvtIdId: boolean | null;
    ultmtDbtrPrvtIdIdIssuer: boolean | null;
    ultmtDbtrPrvtIdIdSchemeCode: boolean | null;
    ultmtDbtrPrvtIdIdSchemePrtry: boolean | null;
    ultmtDbtrPrvtIdPrvcOfBirth: boolean | null;
    ultmtDbtrRoom: number[];
    ultmtDbtrStreetName: number[];
    ultmtDbtrSubdepartment: number[];
    ultmtDbtrTownLocationName: boolean | null;
    ultmtDbtrTownName: boolean | null;
    version2: VersionType;
}