import { VersionType } from "./versionType";
import { XmlElement } from "./xmlElement";

export interface WireFields {
    acceptanceDateValue: boolean;
    acceptanceDateValueSpecified: boolean;
    acceptanceDate: boolean | null;
    acceptanceTimeValue: boolean;
    acceptanceTimeValueSpecified: boolean;
    acceptanceTime: boolean | null;
    accountNumberValue: boolean;
    accountNumberValueSpecified: boolean;
    accountNumber: boolean | null;
    adjustmentDateValue: boolean;
    adjustmentDateValueSpecified: boolean;
    adjustmentDate: boolean | null;
    adjustmentReasonValue: boolean;
    adjustmentReasonValueSpecified: boolean;
    adjustmentReason: boolean | null;
    amountValue: boolean;
    amountValueSpecified: boolean;
    amount: boolean | null;
    applicationIdValue: boolean;
    applicationIdValueSpecified: boolean;
    applicationId: boolean | null;
    batchNumberValue: boolean;
    batchNumberValueSpecified: boolean;
    batchNumber: boolean | null;
    batchNumberCharValue: boolean;
    batchNumberCharValueSpecified: boolean;
    batchNumberChar: boolean | null;
    beneficiaryAddress: number[];
    beneficiaryAddressSpecified: boolean;
    beneficiaryAdviceValue: boolean;
    beneficiaryAdviceValueSpecified: boolean;
    beneficiaryAdvice: boolean | null;
    beneficiaryAdviceCodeValue: boolean;
    beneficiaryAdviceCodeValueSpecified: boolean;
    beneficiaryAdviceCode: boolean | null;
    beneficiaryFiAddress: number[];
    beneficiaryFiAddressSpecified: boolean;
    beneficiaryFiAdviceValue: boolean;
    beneficiaryFiAdviceValueSpecified: boolean;
    beneficiaryFiAdvice: boolean | null;
    beneficiaryFiAdviceCodeValue: boolean;
    beneficiaryFiAdviceCodeValueSpecified: boolean;
    beneficiaryFiAdviceCode: boolean | null;
    beneficiaryFiIdValue: boolean;
    beneficiaryFiIdValueSpecified: boolean;
    beneficiaryFiId: boolean | null;
    beneficiaryFiIdCodeValue: boolean;
    beneficiaryFiIdCodeValueSpecified: boolean;
    beneficiaryFiIdCode: boolean | null;
    beneficiaryFiInfoValue: boolean;
    beneficiaryFiInfoValueSpecified: boolean;
    beneficiaryFiInfo: boolean | null;
    beneficiaryFiIntrnatlIdValue: boolean;
    beneficiaryFiIntrnatlIdValueSpecified: boolean;
    beneficiaryFiIntrnatlId: boolean | null;
    beneficiaryFiNameValue: boolean;
    beneficiaryFiNameValueSpecified: boolean;
    beneficiaryFiName: boolean | null;
    beneficiaryIdValue: boolean;
    beneficiaryIdValueSpecified: boolean;
    beneficiaryId: boolean | null;
    beneficiaryIdCodeValue: boolean;
    beneficiaryIdCodeValueSpecified: boolean;
    beneficiaryIdCode: boolean | null;
    beneficiaryInfoValue: boolean;
    beneficiaryInfoValueSpecified: boolean;
    beneficiaryInfo: boolean | null;
    beneficiaryNameValue: boolean;
    beneficiaryNameValueSpecified: boolean;
    beneficiaryName: boolean | null;
    beneficiaryReferenceValue: boolean;
    beneficiaryReferenceValueSpecified: boolean;
    beneficiaryReference: boolean | null;
    businessFunctionCodeValue: boolean;
    businessFunctionCodeValueSpecified: boolean;
    businessFunctionCode: boolean | null;
    chargesCurrencyCode: number[];
    chargesCurrencyCodeSpecified: boolean;
    commentCodeValue: boolean;
    commentCodeValueSpecified: boolean;
    commentCode: boolean | null;
    destinationValue: boolean;
    destinationValueSpecified: boolean;
    destination: boolean | null;
    detailOfChargesValue: boolean;
    detailOfChargesValueSpecified: boolean;
    detailOfCharges: boolean | null;
    directionValue: boolean;
    directionValueSpecified: boolean;
    direction: boolean | null;
    drawdownCreditAccountValue: boolean;
    drawdownCreditAccountValueSpecified: boolean;
    drawdownCreditAccount: boolean | null;
    drawdownDebitAccountAddress: number[];
    drawdownDebitAccountAddressSpecified: boolean;
    drawdownDebitAccountIdValue: boolean;
    drawdownDebitAccountIdValueSpecified: boolean;
    drawdownDebitAccountId: boolean | null;
    drawdownDebitAccountIdCodeValue: boolean;
    drawdownDebitAccountIdCodeValueSpecified: boolean;
    drawdownDebitAccountIdCode: boolean | null;
    drawdownDebitAccountNameValue: boolean;
    drawdownDebitAccountNameValueSpecified: boolean;
    drawdownDebitAccountName: boolean | null;
    drawdownDebitAcctAdviceValue: boolean;
    drawdownDebitAcctAdviceValueSpecified: boolean;
    drawdownDebitAcctAdvice: boolean | null;
    drawdownDebitAcctAdviceCodeValue: boolean;
    drawdownDebitAcctAdviceCodeValueSpecified: boolean;
    drawdownDebitAcctAdviceCode: boolean | null;
    effectiveDateValue: boolean;
    effectiveDateValueSpecified: boolean;
    effectiveDate: boolean | null;
    enteredByCorporateUserValue: boolean;
    enteredByCorporateUserValueSpecified: boolean;
    enteredByCorporateUser: boolean | null;
    enteredByCorporateUserNameValue: boolean;
    enteredByCorporateUserNameValueSpecified: boolean;
    enteredByCorporateUserName: boolean | null;
    enteredByMemberUserValue: boolean;
    enteredByMemberUserValueSpecified: boolean;
    enteredByMemberUser: boolean | null;
    enteredByMemberUserNameValue: boolean;
    enteredByMemberUserNameValueSpecified: boolean;
    enteredByMemberUserName: boolean | null;
    enteredDateValue: boolean;
    enteredDateValueSpecified: boolean;
    enteredDate: boolean | null;
    enteredTimeValue: boolean;
    enteredTimeValueSpecified: boolean;
    enteredTime: boolean | null;
    enteredValidationMethodValue: boolean;
    enteredValidationMethodValueSpecified: boolean;
    enteredValidationMethod: boolean | null;
    errorCategoryValue: boolean;
    errorCategoryValueSpecified: boolean;
    errorCategory: boolean | null;
    errorCodeValue: boolean;
    errorCodeValueSpecified: boolean;
    errorCode: boolean | null;
    errorDescriptionValue: boolean;
    errorDescriptionValueSpecified: boolean;
    errorDescription: boolean | null;
    exchangeRateValue: boolean;
    exchangeRateValueSpecified: boolean;
    exchangeRate: boolean | null;
    extractDestinationValue: boolean;
    extractDestinationValueSpecified: boolean;
    extractDestination: boolean | null;
    extractedByCorporateUserValue: boolean;
    extractedByCorporateUserValueSpecified: boolean;
    extractedByCorporateUser: boolean | null;
    extractedByCorporateUserNameValue: boolean;
    extractedByCorporateUserNameValueSpecified: boolean;
    extractedByCorporateUserName: boolean | null;
    extractedDateValue: boolean;
    extractedDateValueSpecified: boolean;
    extractedDate: boolean | null;
    extractedTimeValue: boolean;
    extractedTimeValueSpecified: boolean;
    extractedTime: boolean | null;
    fiToFiInfoValue: boolean;
    fiToFiInfoValueSpecified: boolean;
    fiToFiInfo: boolean | null;
    fmLastPurgeDateValue: boolean;
    fmLastPurgeDateValueSpecified: boolean;
    fmLastPurgeDate: boolean | null;
    formatVersionValue: boolean;
    formatVersionValueSpecified: boolean;
    formatVersion: boolean | null;
    glAccountValue: boolean;
    glAccountValueSpecified: boolean;
    glAccount: boolean | null;
    glCommentAddlInfoValue: boolean;
    glCommentAddlInfoValueSpecified: boolean;
    glCommentAddlInfo: boolean | null;
    glOffsetValue: boolean;
    glOffsetValueSpecified: boolean;
    glOffset: boolean | null;
    imadValue: boolean;
    imadValueSpecified: boolean;
    imad: boolean | null;
    instructIngFiAddress: number[];
    instructIngFiAddressSpecified: boolean;
    instructIngFiIdValue: boolean;
    instructIngFiIdValueSpecified: boolean;
    instructIngFiId: boolean | null;
    instructIngFiIdCodeValue: boolean;
    instructIngFiIdCodeValueSpecified: boolean;
    instructIngFiIdCode: boolean | null;
    instructedAmountValue: boolean;
    instructedAmountValueSpecified: boolean;
    instructedAmount: boolean | null;
    instructedAmtCurrencyCodeValue: boolean;
    instructedAmtCurrencyCodeValueSpecified: boolean;
    instructedAmtCurrencyCode: boolean | null;
    instructingFiNameValue: boolean;
    instructingFiNameValueSpecified: boolean;
    instructingFiName: boolean | null;
    intermediaryFiAddress: number[];
    intermediaryFiAddressSpecified: boolean;
    intermediaryFiAdviceValue: boolean;
    intermediaryFiAdviceValueSpecified: boolean;
    intermediaryFiAdvice: boolean | null;
    intermediaryFiAdviceCodeValue: boolean;
    intermediaryFiAdviceCodeValueSpecified: boolean;
    intermediaryFiAdviceCode: boolean | null;
    intermediaryFiIdValue: boolean;
    intermediaryFiIdValueSpecified: boolean;
    intermediaryFiId: boolean | null;
    intermediaryFiIdCodeValue: boolean;
    intermediaryFiIdCodeValueSpecified: boolean;
    intermediaryFiIdCode: boolean | null;
    intermediaryFiInfoValue: boolean;
    intermediaryFiInfoValueSpecified: boolean;
    intermediaryFiInfo: boolean | null;
    intermediaryFiNameValue: boolean;
    intermediaryFiNameValueSpecified: boolean;
    intermediaryFiName: boolean | null;
    lastFmDateValue: boolean;
    lastFmDateValueSpecified: boolean;
    lastFmDate: boolean | null;
    messageDuplicationCodeValue: boolean;
    messageDuplicationCodeValueSpecified: boolean;
    messageDuplicationCode: boolean | null;
    messageStatusIndicatorValue: boolean;
    messageStatusIndicatorValueSpecified: boolean;
    messageStatusIndicator: boolean | null;
    notificationDateValue: boolean;
    notificationDateValueSpecified: boolean;
    notificationDate: boolean | null;
    notificationMethodValue: boolean;
    notificationMethodValueSpecified: boolean;
    notificationMethod: boolean | null;
    notificationStatusValue: boolean;
    notificationStatusValueSpecified: boolean;
    notificationStatus: boolean | null;
    notificationTimeValue: boolean;
    notificationTimeValueSpecified: boolean;
    notificationTime: boolean | null;
    notificationUserValue: boolean;
    notificationUserValueSpecified: boolean;
    notificationUser: boolean | null;
    ofacDetailsValue: boolean;
    ofacDetailsValueSpecified: boolean;
    ofacDetails: boolean | null;
    ofacStatusValue: boolean;
    ofacStatusValueSpecified: boolean;
    ofacStatus: boolean | null;
    omadValue: boolean;
    omadValueSpecified: boolean;
    omad: boolean | null;
    originatorAddress: number[];
    originatorAddressSpecified: boolean;
    originatorFiAddress: number[];
    originatorFiAddressSpecified: boolean;
    originatorFiIdValue: boolean;
    originatorFiIdValueSpecified: boolean;
    originatorFiId: boolean | null;
    originatorFiIdCodeValue: boolean;
    originatorFiIdCodeValueSpecified: boolean;
    originatorFiIdCode: boolean | null;
    originatorFiNameValue: boolean;
    originatorFiNameValueSpecified: boolean;
    originatorFiName: boolean | null;
    originatorIdValue: boolean;
    originatorIdValueSpecified: boolean;
    originatorId: boolean | null;
    originatorIdCodeValue: boolean;
    originatorIdCodeValueSpecified: boolean;
    originatorIdCode: boolean | null;
    originatorIdFValue: boolean;
    originatorIdFValueSpecified: boolean;
    originatorIdF: boolean | null;
    originatorLineCodeF: number[];
    originatorLineCodeFSpecified: boolean;
    originatorLineF: number[];
    originatorLineFSpecified: boolean;
    originatorNameValue: boolean;
    originatorNameValueSpecified: boolean;
    originatorName: boolean | null;
    originatorNameFValue: boolean;
    originatorNameFValueSpecified: boolean;
    originatorNameF: boolean | null;
    originatorPartyIdFValue: boolean;
    originatorPartyIdFValueSpecified: boolean;
    originatorPartyIdF: boolean | null;
    originatorToBeneficiaryInfo: number[];
    originatorToBeneficiaryInfoSpecified: boolean;
    otherAddLinFoValue: boolean;
    otherAddLinFoValueSpecified: boolean;
    otherAddLinFo: boolean | null;
    paymentLimitationValue: boolean;
    paymentLimitationValueSpecified: boolean;
    paymentLimitation: boolean | null;
    paymentMethodValue: boolean;
    paymentMethodValueSpecified: boolean;
    paymentMethod: boolean | null;
    paymentMethodCodeValue: boolean;
    paymentMethodCodeValueSpecified: boolean;
    paymentMethodCode: boolean | null;
    postingErrorValue: boolean;
    postingErrorValueSpecified: boolean;
    postingError: boolean | null;
    preAuthTemplateNameValue: boolean;
    preAuthTemplateNameValueSpecified: boolean;
    preAuthTemplateName: boolean | null;
    preAuthTemplateNumberValue: boolean;
    preAuthTemplateNumberValueSpecified: boolean;
    preAuthTemplateNumber: boolean | null;
    previousMessageImadValue: boolean;
    previousMessageImadValueSpecified: boolean;
    previousMessageImad: boolean | null;
    receiverFiValue: boolean;
    receiverFiValueSpecified: boolean;
    receiverFi: boolean | null;
    receiverFiInfoValue: boolean;
    receiverFiInfoValueSpecified: boolean;
    receiverFiInfo: boolean | null;
    receiverNameValue: boolean;
    receiverNameValueSpecified: boolean;
    receiverName: boolean | null;
    regETranValue: boolean;
    regETranValueSpecified: boolean;
    regETran: boolean | null;
    releasedByCorporateUserValue: boolean;
    releasedByCorporateUserValueSpecified: boolean;
    releasedByCorporateUser: boolean | null;
    releasedByCorporateUserNameValue: boolean;
    releasedByCorporateUserNameValueSpecified: boolean;
    releasedByCorporateUserName: boolean | null;
    releasedDateValue: boolean;
    releasedDateValueSpecified: boolean;
    releasedDate: boolean | null;
    releasedReasonValue: boolean;
    releasedReasonValueSpecified: boolean;
    releasedReason: boolean | null;
    releasedTimeValue: boolean;
    releasedTimeValueSpecified: boolean;
    releasedTime: boolean | null;
    returnRejectByCorpUserValue: boolean;
    returnRejectByCorpUserValueSpecified: boolean;
    returnRejectByCorpUser: boolean | null;
    returnRejectByCorpUserNameValue: boolean;
    returnRejectByCorpUserNameValueSpecified: boolean;
    returnRejectByCorpUserName: boolean | null;
    returnRejectDateValue: boolean;
    returnRejectDateValueSpecified: boolean;
    returnRejectDate: boolean | null;
    returnRejectReasonValue: boolean;
    returnRejectReasonValueSpecified: boolean;
    returnRejectReason: boolean | null;
    returnRejectTimeValue: boolean;
    returnRejectTimeValueSpecified: boolean;
    returnRejectTime: boolean | null;
    senderCharges: number[];
    senderChargesSpecified: boolean;
    senderFiValue: boolean;
    senderFiValueSpecified: boolean;
    senderFi: boolean | null;
    senderNameValue: boolean;
    senderNameValueSpecified: boolean;
    senderName: boolean | null;
    senderReferenceNumberValue: boolean;
    senderReferenceNumberValueSpecified: boolean;
    senderReferenceNumber: boolean | null;
    sequenceNumberValue: boolean;
    sequenceNumberValueSpecified: boolean;
    sequenceNumber: boolean | null;
    serviceMessageValue: boolean;
    serviceMessageValueSpecified: boolean;
    serviceMessage: boolean | null;
    shareIdValue: boolean;
    shareIdValueSpecified: boolean;
    shareId: boolean | null;
    statementDescriptionValue: boolean;
    statementDescriptionValueSpecified: boolean;
    statementDescription: boolean | null;
    statusValue: boolean;
    statusValueSpecified: boolean;
    status: boolean | null;
    testProductionCodeValue: boolean;
    testProductionCodeValueSpecified: boolean;
    testProductionCode: boolean | null;
    tranTypeCodeValue: boolean;
    tranTypeCodeValueSpecified: boolean;
    tranTypeCode: boolean | null;
    transactionSequenceNumCharValue: boolean;
    transactionSequenceNumCharValueSpecified: boolean;
    transactionSequenceNumChar: boolean | null;
    transactionSequenceNumberValue: boolean;
    transactionSequenceNumberValueSpecified: boolean;
    transactionSequenceNumber: boolean | null;
    typeValue: boolean;
    typeValueSpecified: boolean;
    type: boolean | null;
    typeCodeValue: boolean;
    typeCodeValueSpecified: boolean;
    typeCode: boolean | null;
    upLoadedTimeValue: boolean;
    upLoadedTimeValueSpecified: boolean;
    upLoadedTime: boolean | null;
    uploadedDateValue: boolean;
    uploadedDateValueSpecified: boolean;
    uploadedDate: boolean | null;
    urcDataValue: boolean;
    urcDataValueSpecified: boolean;
    urcData: boolean | null;
    uscAuditTrailInfoValue: boolean;
    uscAuditTrailInfoValueSpecified: boolean;
    uscAuditTrailInfo: boolean | null;
    verificationMemberContactValue: boolean;
    verificationMemberContactValueSpecified: boolean;
    verificationMemberContact: boolean | null;
    verificationMemberContactNameValue: boolean;
    verificationMemberContactNameValueSpecified: boolean;
    verificationMemberContactName: boolean | null;
    verifiedByCorpUserValue: boolean;
    verifiedByCorpUserValueSpecified: boolean;
    verifiedByCorpUser: boolean | null;
    verifiedByCorpUserNameValue: boolean;
    verifiedByCorpUserNameValueSpecified: boolean;
    verifiedByCorpUserName: boolean | null;
    verifiedByMemberUserValue: boolean;
    verifiedByMemberUserValueSpecified: boolean;
    verifiedByMemberUser: boolean | null;
    verifiedByMemberUserNameValue: boolean;
    verifiedByMemberUserNameValueSpecified: boolean;
    verifiedByMemberUserName: boolean | null;
    verifiedDateValue: boolean;
    verifiedDateValueSpecified: boolean;
    verifiedDate: boolean | null;
    verifiedTimeValue: boolean;
    verifiedTimeValueSpecified: boolean;
    verifiedTime: boolean | null;
    verifiedValidationMethodValue: boolean;
    verifiedValidationMethodValueSpecified: boolean;
    verifiedValidationMethod: boolean | null;
    verifiedValidationReasonValue: boolean;
    verifiedValidationReasonValueSpecified: boolean;
    verifiedValidationReason: boolean | null;
    wireForValue: boolean;
    wireForValueSpecified: boolean;
    wireFor: boolean | null;
    version1: VersionType;
    cdtrAcctCurrencyValue: boolean;
    cdtrAcctCurrencyValueSpecified: boolean;
    cdtrAcctCurrency: boolean | null;
    cdtrAcctIbanValue: boolean;
    cdtrAcctIbanValueSpecified: boolean;
    cdtrAcctIban: boolean | null;
    cdtrAcctIdValue: boolean;
    cdtrAcctIdValueSpecified: boolean;
    cdtrAcctId: boolean | null;
    cdtrAcctIdCodeValue: boolean;
    cdtrAcctIdCodeValueSpecified: boolean;
    cdtrAcctIdCode: boolean | null;
    cdtrAcctIdIssuerValue: boolean;
    cdtrAcctIdIssuerValueSpecified: boolean;
    cdtrAcctIdIssuer: boolean | null;
    cdtrAcctIdProprietaryValue: boolean;
    cdtrAcctIdProprietaryValueSpecified: boolean;
    cdtrAcctIdProprietary: boolean | null;
    cdtrAcctName: number[];
    cdtrAcctNameSpecified: boolean;
    cdtrAcctProxyCodeValue: boolean;
    cdtrAcctProxyCodeValueSpecified: boolean;
    cdtrAcctProxyCode: boolean | null;
    cdtrAcctProxyId: number[];
    cdtrAcctProxyIdSpecified: boolean;
    cdtrAcctProxyProprietaryValue: boolean;
    cdtrAcctProxyProprietaryValueSpecified: boolean;
    cdtrAcctProxyProprietary: boolean | null;
    cdtrAcctTypeCodeValue: boolean;
    cdtrAcctTypeCodeValueSpecified: boolean;
    cdtrAcctTypeCode: boolean | null;
    cdtrAcctTypeProprietaryValue: boolean;
    cdtrAcctTypeProprietaryValueSpecified: boolean;
    cdtrAcctTypeProprietary: boolean | null;
    cdtrAgtAcctCurrencyValue: boolean;
    cdtrAgtAcctCurrencyValueSpecified: boolean;
    cdtrAgtAcctCurrency: boolean | null;
    cdtrAgtAcctIbanValue: boolean;
    cdtrAgtAcctIbanValueSpecified: boolean;
    cdtrAgtAcctIban: boolean | null;
    cdtrAgtAcctIdValue: boolean;
    cdtrAgtAcctIdValueSpecified: boolean;
    cdtrAgtAcctId: boolean | null;
    cdtrAgtAcctIdCodeValue: boolean;
    cdtrAgtAcctIdCodeValueSpecified: boolean;
    cdtrAgtAcctIdCode: boolean | null;
    cdtrAgtAcctIdIssuerValue: boolean;
    cdtrAgtAcctIdIssuerValueSpecified: boolean;
    cdtrAgtAcctIdIssuer: boolean | null;
    cdtrAgtAcctIdProprietaryValue: boolean;
    cdtrAgtAcctIdProprietaryValueSpecified: boolean;
    cdtrAgtAcctIdProprietary: boolean | null;
    cdtrAgtAcctName: number[];
    cdtrAgtAcctNameSpecified: boolean;
    cdtrAgtAcctProxyCodeValue: boolean;
    cdtrAgtAcctProxyCodeValueSpecified: boolean;
    cdtrAgtAcctProxyCode: boolean | null;
    cdtrAgtAcctProxyId: number[];
    cdtrAgtAcctProxyIdSpecified: boolean;
    cdtrAgtAcctProxyProprietaryValue: boolean;
    cdtrAgtAcctProxyProprietaryValueSpecified: boolean;
    cdtrAgtAcctProxyProprietary: boolean | null;
    cdtrAgtAcctTypeCodeValue: boolean;
    cdtrAgtAcctTypeCodeValueSpecified: boolean;
    cdtrAgtAcctTypeCode: boolean | null;
    cdtrAgtAcctTypeProprietaryValue: boolean;
    cdtrAgtAcctTypeProprietaryValueSpecified: boolean;
    cdtrAgtAcctTypeProprietary: boolean | null;
    chargeAgent1BicValue: boolean;
    chargeAgent1BicValueSpecified: boolean;
    chargeAgent1Bic: boolean | null;
    chargeAgent1BuildingNameValue: boolean;
    chargeAgent1BuildingNameValueSpecified: boolean;
    chargeAgent1BuildingName: boolean | null;
    chargeAgent1BuildingNumValue: boolean;
    chargeAgent1BuildingNumValueSpecified: boolean;
    chargeAgent1BuildingNum: boolean | null;
    chargeAgent1ClrSysMemIdValue: boolean;
    chargeAgent1ClrSysMemIdValueSpecified: boolean;
    chargeAgent1ClrSysMemId: boolean | null;
    chargeAgent1ClrSysMemIdCodeValue: boolean;
    chargeAgent1ClrSysMemIdCodeValueSpecified: boolean;
    chargeAgent1ClrSysMemIdCode: boolean | null;
    chargeAgent1CountryValue: boolean;
    chargeAgent1CountryValueSpecified: boolean;
    chargeAgent1Country: boolean | null;
    chargeAgent1CountrySubDivValue: boolean;
    chargeAgent1CountrySubDivValueSpecified: boolean;
    chargeAgent1CountrySubDiv: boolean | null;
    chargeAgent1Department: number[];
    chargeAgent1DepartmentSpecified: boolean;
    chargeAgent1DistrictNameValue: boolean;
    chargeAgent1DistrictNameValueSpecified: boolean;
    chargeAgent1DistrictName: boolean | null;
    chargeAgent1Floor: number[];
    chargeAgent1FloorSpecified: boolean;
    chargeAgent1LeiValue: boolean;
    chargeAgent1LeiValueSpecified: boolean;
    chargeAgent1Lei: boolean | null;
    chargeAgent1Name: number[];
    chargeAgent1NameSpecified: boolean;
    chargeAgent1PostBoxValue: boolean;
    chargeAgent1PostBoxValueSpecified: boolean;
    chargeAgent1PostBox: boolean | null;
    chargeAgent1PostCodeValue: boolean;
    chargeAgent1PostCodeValueSpecified: boolean;
    chargeAgent1PostCode: boolean | null;
    chargeAgent1Room: number[];
    chargeAgent1RoomSpecified: boolean;
    chargeAgent1StreetName: number[];
    chargeAgent1StreetNameSpecified: boolean;
    chargeAgent1Subdepartment: number[];
    chargeAgent1SubdepartmentSpecified: boolean;
    chargeAgent1TownLocationNameValue: boolean;
    chargeAgent1TownLocationNameValueSpecified: boolean;
    chargeAgent1TownLocationName: boolean | null;
    chargeAgent1TownNameValue: boolean;
    chargeAgent1TownNameValueSpecified: boolean;
    chargeAgent1TownName: boolean | null;
    chargeAgent2BicValue: boolean;
    chargeAgent2BicValueSpecified: boolean;
    chargeAgent2Bic: boolean | null;
    chargeAgent2BuildingNameValue: boolean;
    chargeAgent2BuildingNameValueSpecified: boolean;
    chargeAgent2BuildingName: boolean | null;
    chargeAgent2BuildingNumValue: boolean;
    chargeAgent2BuildingNumValueSpecified: boolean;
    chargeAgent2BuildingNum: boolean | null;
    chargeAgent2ClrSysMemIdValue: boolean;
    chargeAgent2ClrSysMemIdValueSpecified: boolean;
    chargeAgent2ClrSysMemId: boolean | null;
    chargeAgent2ClrSysMemIdCodeValue: boolean;
    chargeAgent2ClrSysMemIdCodeValueSpecified: boolean;
    chargeAgent2ClrSysMemIdCode: boolean | null;
    chargeAgent2CountryValue: boolean;
    chargeAgent2CountryValueSpecified: boolean;
    chargeAgent2Country: boolean | null;
    chargeAgent2CountrySubDivValue: boolean;
    chargeAgent2CountrySubDivValueSpecified: boolean;
    chargeAgent2CountrySubDiv: boolean | null;
    chargeAgent2Department: number[];
    chargeAgent2DepartmentSpecified: boolean;
    chargeAgent2DistrictNameValue: boolean;
    chargeAgent2DistrictNameValueSpecified: boolean;
    chargeAgent2DistrictName: boolean | null;
    chargeAgent2Floor: number[];
    chargeAgent2FloorSpecified: boolean;
    chargeAgent2LeiValue: boolean;
    chargeAgent2LeiValueSpecified: boolean;
    chargeAgent2Lei: boolean | null;
    chargeAgent2Name: number[];
    chargeAgent2NameSpecified: boolean;
    chargeAgent2PostBoxValue: boolean;
    chargeAgent2PostBoxValueSpecified: boolean;
    chargeAgent2PostBox: boolean | null;
    chargeAgent2PostCodeValue: boolean;
    chargeAgent2PostCodeValueSpecified: boolean;
    chargeAgent2PostCode: boolean | null;
    chargeAgent2Room: number[];
    chargeAgent2RoomSpecified: boolean;
    chargeAgent2StreetName: number[];
    chargeAgent2StreetNameSpecified: boolean;
    chargeAgent2Subdepartment: number[];
    chargeAgent2SubdepartmentSpecified: boolean;
    chargeAgent2TownLocationNameValue: boolean;
    chargeAgent2TownLocationNameValueSpecified: boolean;
    chargeAgent2TownLocationName: boolean | null;
    chargeAgent2TownNameValue: boolean;
    chargeAgent2TownNameValueSpecified: boolean;
    chargeAgent2TownName: boolean | null;
    chargeAgent3BicValue: boolean;
    chargeAgent3BicValueSpecified: boolean;
    chargeAgent3Bic: boolean | null;
    chargeAgent3BuildingNameValue: boolean;
    chargeAgent3BuildingNameValueSpecified: boolean;
    chargeAgent3BuildingName: boolean | null;
    chargeAgent3BuildingNumValue: boolean;
    chargeAgent3BuildingNumValueSpecified: boolean;
    chargeAgent3BuildingNum: boolean | null;
    chargeAgent3ClrSysMemIdValue: boolean;
    chargeAgent3ClrSysMemIdValueSpecified: boolean;
    chargeAgent3ClrSysMemId: boolean | null;
    chargeAgent3ClrSysMemIdCodeValue: boolean;
    chargeAgent3ClrSysMemIdCodeValueSpecified: boolean;
    chargeAgent3ClrSysMemIdCode: boolean | null;
    chargeAgent3CountryValue: boolean;
    chargeAgent3CountryValueSpecified: boolean;
    chargeAgent3Country: boolean | null;
    chargeAgent3CountrySubDivValue: boolean;
    chargeAgent3CountrySubDivValueSpecified: boolean;
    chargeAgent3CountrySubDiv: boolean | null;
    chargeAgent3Department: number[];
    chargeAgent3DepartmentSpecified: boolean;
    chargeAgent3DistrictNameValue: boolean;
    chargeAgent3DistrictNameValueSpecified: boolean;
    chargeAgent3DistrictName: boolean | null;
    chargeAgent3Floor: number[];
    chargeAgent3FloorSpecified: boolean;
    chargeAgent3LeiValue: boolean;
    chargeAgent3LeiValueSpecified: boolean;
    chargeAgent3Lei: boolean | null;
    chargeAgent3Name: number[];
    chargeAgent3NameSpecified: boolean;
    chargeAgent3PostBoxValue: boolean;
    chargeAgent3PostBoxValueSpecified: boolean;
    chargeAgent3PostBox: boolean | null;
    chargeAgent3PostCodeValue: boolean;
    chargeAgent3PostCodeValueSpecified: boolean;
    chargeAgent3PostCode: boolean | null;
    chargeAgent3Room: number[];
    chargeAgent3RoomSpecified: boolean;
    chargeAgent3StreetName: number[];
    chargeAgent3StreetNameSpecified: boolean;
    chargeAgent3Subdepartment: number[];
    chargeAgent3SubdepartmentSpecified: boolean;
    chargeAgent3TownLocationNameValue: boolean;
    chargeAgent3TownLocationNameValueSpecified: boolean;
    chargeAgent3TownLocationName: boolean | null;
    chargeAgent3TownNameValue: boolean;
    chargeAgent3TownNameValueSpecified: boolean;
    chargeAgent3TownName: boolean | null;
    chargeAgent4BicValue: boolean;
    chargeAgent4BicValueSpecified: boolean;
    chargeAgent4Bic: boolean | null;
    chargeAgent4BuildingNameValue: boolean;
    chargeAgent4BuildingNameValueSpecified: boolean;
    chargeAgent4BuildingName: boolean | null;
    chargeAgent4BuildingNumValue: boolean;
    chargeAgent4BuildingNumValueSpecified: boolean;
    chargeAgent4BuildingNum: boolean | null;
    chargeAgent4ClrSysMemIdValue: boolean;
    chargeAgent4ClrSysMemIdValueSpecified: boolean;
    chargeAgent4ClrSysMemId: boolean | null;
    chargeAgent4ClrSysMemIdCodeValue: boolean;
    chargeAgent4ClrSysMemIdCodeValueSpecified: boolean;
    chargeAgent4ClrSysMemIdCode: boolean | null;
    chargeAgent4CountryValue: boolean;
    chargeAgent4CountryValueSpecified: boolean;
    chargeAgent4Country: boolean | null;
    chargeAgent4CountrySubDivValue: boolean;
    chargeAgent4CountrySubDivValueSpecified: boolean;
    chargeAgent4CountrySubDiv: boolean | null;
    chargeAgent4Department: number[];
    chargeAgent4DepartmentSpecified: boolean;
    chargeAgent4DistrictNameValue: boolean;
    chargeAgent4DistrictNameValueSpecified: boolean;
    chargeAgent4DistrictName: boolean | null;
    chargeAgent4Floor: number[];
    chargeAgent4FloorSpecified: boolean;
    chargeAgent4LeiValue: boolean;
    chargeAgent4LeiValueSpecified: boolean;
    chargeAgent4Lei: boolean | null;
    chargeAgent4Name: number[];
    chargeAgent4NameSpecified: boolean;
    chargeAgent4PostBoxValue: boolean;
    chargeAgent4PostBoxValueSpecified: boolean;
    chargeAgent4PostBox: boolean | null;
    chargeAgent4PostCodeValue: boolean;
    chargeAgent4PostCodeValueSpecified: boolean;
    chargeAgent4PostCode: boolean | null;
    chargeAgent4Room: number[];
    chargeAgent4RoomSpecified: boolean;
    chargeAgent4StreetName: number[];
    chargeAgent4StreetNameSpecified: boolean;
    chargeAgent4Subdepartment: number[];
    chargeAgent4SubdepartmentSpecified: boolean;
    chargeAgent4TownLocationNameValue: boolean;
    chargeAgent4TownLocationNameValueSpecified: boolean;
    chargeAgent4TownLocationName: boolean | null;
    chargeAgent4TownNameValue: boolean;
    chargeAgent4TownNameValueSpecified: boolean;
    chargeAgent4TownName: boolean | null;
    chargeBearerValue: boolean;
    chargeBearerValueSpecified: boolean;
    chargeBearer: boolean | null;
    creationDateTimeValue: boolean;
    creationDateTimeValueSpecified: boolean;
    creationDateTime: boolean | null;
    creditorAgentBuildingNameValue: boolean;
    creditorAgentBuildingNameValueSpecified: boolean;
    creditorAgentBuildingName: boolean | null;
    creditorAgentBuildingNumValue: boolean;
    creditorAgentBuildingNumValueSpecified: boolean;
    creditorAgentBuildingNum: boolean | null;
    creditorAgentClrSysMemIdValue: boolean;
    creditorAgentClrSysMemIdValueSpecified: boolean;
    creditorAgentClrSysMemId: boolean | null;
    creditorAgentClrSysMemIdCodeValue: boolean;
    creditorAgentClrSysMemIdCodeValueSpecified: boolean;
    creditorAgentClrSysMemIdCode: boolean | null;
    creditorAgentCountryValue: boolean;
    creditorAgentCountryValueSpecified: boolean;
    creditorAgentCountry: boolean | null;
    creditorAgentCountrySubDivValue: boolean;
    creditorAgentCountrySubDivValueSpecified: boolean;
    creditorAgentCountrySubDiv: boolean | null;
    creditorAgentDepartment: number[];
    creditorAgentDepartmentSpecified: boolean;
    creditorAgentDistrictNameValue: boolean;
    creditorAgentDistrictNameValueSpecified: boolean;
    creditorAgentDistrictName: boolean | null;
    creditorAgentFiBicValue: boolean;
    creditorAgentFiBicValueSpecified: boolean;
    creditorAgentFiBic: boolean | null;
    creditorAgentFiLeiValue: boolean;
    creditorAgentFiLeiValueSpecified: boolean;
    creditorAgentFiLei: boolean | null;
    creditorAgentFiName: number[];
    creditorAgentFiNameSpecified: boolean;
    creditorAgentFloor: number[];
    creditorAgentFloorSpecified: boolean;
    creditorAgentPostBoxValue: boolean;
    creditorAgentPostBoxValueSpecified: boolean;
    creditorAgentPostBox: boolean | null;
    creditorAgentPostCodeValue: boolean;
    creditorAgentPostCodeValueSpecified: boolean;
    creditorAgentPostCode: boolean | null;
    creditorAgentRoom: number[];
    creditorAgentRoomSpecified: boolean;
    creditorAgentStreetName: number[];
    creditorAgentStreetNameSpecified: boolean;
    creditorAgentSubdepartment: number[];
    creditorAgentSubdepartmentSpecified: boolean;
    creditorAgentTownLocationNameValue: boolean;
    creditorAgentTownLocationNameValueSpecified: boolean;
    creditorAgentTownLocationName: boolean | null;
    creditorAgentTownNameValue: boolean;
    creditorAgentTownNameValueSpecified: boolean;
    creditorAgentTownName: boolean | null;
    creditorBicValue: boolean;
    creditorBicValueSpecified: boolean;
    creditorBic: boolean | null;
    creditorBuildingNameValue: boolean;
    creditorBuildingNameValueSpecified: boolean;
    creditorBuildingName: boolean | null;
    creditorBuildingNumValue: boolean;
    creditorBuildingNumValueSpecified: boolean;
    creditorBuildingNum: boolean | null;
    creditorCountryValue: boolean;
    creditorCountryValueSpecified: boolean;
    creditorCountry: boolean | null;
    creditorCountrySubDivValue: boolean;
    creditorCountrySubDivValueSpecified: boolean;
    creditorCountrySubDiv: boolean | null;
    creditorDepartment: number[];
    creditorDepartmentSpecified: boolean;
    creditorDistrictNameValue: boolean;
    creditorDistrictNameValueSpecified: boolean;
    creditorDistrictName: boolean | null;
    creditorFloor: number[];
    creditorFloorSpecified: boolean;
    creditorIdValue: boolean;
    creditorIdValueSpecified: boolean;
    creditorId: boolean | null;
    creditorIdSchemeCodeValue: boolean;
    creditorIdSchemeCodeValueSpecified: boolean;
    creditorIdSchemeCode: boolean | null;
    creditorIdSchemeNameValue: boolean;
    creditorIdSchemeNameValueSpecified: boolean;
    creditorIdSchemeName: boolean | null;
    creditorIssuerValue: boolean;
    creditorIssuerValueSpecified: boolean;
    creditorIssuer: boolean | null;
    creditorLeiValue: boolean;
    creditorLeiValueSpecified: boolean;
    creditorLei: boolean | null;
    creditorName: number[];
    creditorNameSpecified: boolean;
    creditorPostBoxValue: boolean;
    creditorPostBoxValueSpecified: boolean;
    creditorPostBox: boolean | null;
    creditorPostCodeValue: boolean;
    creditorPostCodeValueSpecified: boolean;
    creditorPostCode: boolean | null;
    creditorRoom: number[];
    creditorRoomSpecified: boolean;
    creditorStreetName: number[];
    creditorStreetNameSpecified: boolean;
    creditorSubdepartment: number[];
    creditorSubdepartmentSpecified: boolean;
    creditorTownLocationNameValue: boolean;
    creditorTownLocationNameValueSpecified: boolean;
    creditorTownLocationName: boolean | null;
    creditorTownNameValue: boolean;
    creditorTownNameValueSpecified: boolean;
    creditorTownName: boolean | null;
    dbtrAgtAcctCurrencyValue: boolean;
    dbtrAgtAcctCurrencyValueSpecified: boolean;
    dbtrAgtAcctCurrency: boolean | null;
    dbtrAgtAcctIbanValue: boolean;
    dbtrAgtAcctIbanValueSpecified: boolean;
    dbtrAgtAcctIban: boolean | null;
    dbtrAgtAcctIdValue: boolean;
    dbtrAgtAcctIdValueSpecified: boolean;
    dbtrAgtAcctId: boolean | null;
    dbtrAgtAcctIdCodeValue: boolean;
    dbtrAgtAcctIdCodeValueSpecified: boolean;
    dbtrAgtAcctIdCode: boolean | null;
    dbtrAgtAcctIdIssuerValue: boolean;
    dbtrAgtAcctIdIssuerValueSpecified: boolean;
    dbtrAgtAcctIdIssuer: boolean | null;
    dbtrAgtAcctIdProprietaryValue: boolean;
    dbtrAgtAcctIdProprietaryValueSpecified: boolean;
    dbtrAgtAcctIdProprietary: boolean | null;
    dbtrAgtAcctName: number[];
    dbtrAgtAcctNameSpecified: boolean;
    dbtrAgtAcctProxyCodeValue: boolean;
    dbtrAgtAcctProxyCodeValueSpecified: boolean;
    dbtrAgtAcctProxyCode: boolean | null;
    dbtrAgtAcctProxyId: number[];
    dbtrAgtAcctProxyIdSpecified: boolean;
    dbtrAgtAcctProxyProprietaryValue: boolean;
    dbtrAgtAcctProxyProprietaryValueSpecified: boolean;
    dbtrAgtAcctProxyProprietary: boolean | null;
    dbtrAgtAcctTypeCodeValue: boolean;
    dbtrAgtAcctTypeCodeValueSpecified: boolean;
    dbtrAgtAcctTypeCode: boolean | null;
    dbtrAgtAcctTypeProprietaryValue: boolean;
    dbtrAgtAcctTypeProprietaryValueSpecified: boolean;
    dbtrAgtAcctTypeProprietary: boolean | null;
    debtorAcctCurrencyValue: boolean;
    debtorAcctCurrencyValueSpecified: boolean;
    debtorAcctCurrency: boolean | null;
    debtorAcctIbanValue: boolean;
    debtorAcctIbanValueSpecified: boolean;
    debtorAcctIban: boolean | null;
    debtorAcctIdValue: boolean;
    debtorAcctIdValueSpecified: boolean;
    debtorAcctId: boolean | null;
    debtorAcctIdCodeValue: boolean;
    debtorAcctIdCodeValueSpecified: boolean;
    debtorAcctIdCode: boolean | null;
    debtorAcctIdIssuerValue: boolean;
    debtorAcctIdIssuerValueSpecified: boolean;
    debtorAcctIdIssuer: boolean | null;
    debtorAcctIdProprietaryValue: boolean;
    debtorAcctIdProprietaryValueSpecified: boolean;
    debtorAcctIdProprietary: boolean | null;
    debtorAcctName: number[];
    debtorAcctNameSpecified: boolean;
    debtorAcctProxyCodeValue: boolean;
    debtorAcctProxyCodeValueSpecified: boolean;
    debtorAcctProxyCode: boolean | null;
    debtorAcctProxyId: number[];
    debtorAcctProxyIdSpecified: boolean;
    debtorAcctProxyProprietaryValue: boolean;
    debtorAcctProxyProprietaryValueSpecified: boolean;
    debtorAcctProxyProprietary: boolean | null;
    debtorAcctTypeCodeValue: boolean;
    debtorAcctTypeCodeValueSpecified: boolean;
    debtorAcctTypeCode: boolean | null;
    debtorAcctTypeProprietaryValue: boolean;
    debtorAcctTypeProprietaryValueSpecified: boolean;
    debtorAcctTypeProprietary: boolean | null;
    debtorAgentBicValue: boolean;
    debtorAgentBicValueSpecified: boolean;
    debtorAgentBic: boolean | null;
    debtorAgentBuildingNameValue: boolean;
    debtorAgentBuildingNameValueSpecified: boolean;
    debtorAgentBuildingName: boolean | null;
    debtorAgentBuildingNumValue: boolean;
    debtorAgentBuildingNumValueSpecified: boolean;
    debtorAgentBuildingNum: boolean | null;
    debtorAgentClrSysMemIdValue: boolean;
    debtorAgentClrSysMemIdValueSpecified: boolean;
    debtorAgentClrSysMemId: boolean | null;
    debtorAgentClrSysMemIdCodeValue: boolean;
    debtorAgentClrSysMemIdCodeValueSpecified: boolean;
    debtorAgentClrSysMemIdCode: boolean | null;
    debtorAgentCountryValue: boolean;
    debtorAgentCountryValueSpecified: boolean;
    debtorAgentCountry: boolean | null;
    debtorAgentCountrySubDivValue: boolean;
    debtorAgentCountrySubDivValueSpecified: boolean;
    debtorAgentCountrySubDiv: boolean | null;
    debtorAgentDepartment: number[];
    debtorAgentDepartmentSpecified: boolean;
    debtorAgentDistrictNameValue: boolean;
    debtorAgentDistrictNameValueSpecified: boolean;
    debtorAgentDistrictName: boolean | null;
    debtorAgentFloor: number[];
    debtorAgentFloorSpecified: boolean;
    debtorAgentLeiValue: boolean;
    debtorAgentLeiValueSpecified: boolean;
    debtorAgentLei: boolean | null;
    debtorAgentName: number[];
    debtorAgentNameSpecified: boolean;
    debtorAgentPostBoxValue: boolean;
    debtorAgentPostBoxValueSpecified: boolean;
    debtorAgentPostBox: boolean | null;
    debtorAgentPostCodeValue: boolean;
    debtorAgentPostCodeValueSpecified: boolean;
    debtorAgentPostCode: boolean | null;
    debtorAgentRoom: number[];
    debtorAgentRoomSpecified: boolean;
    debtorAgentStreetName: number[];
    debtorAgentStreetNameSpecified: boolean;
    debtorAgentSubdepartment: number[];
    debtorAgentSubdepartmentSpecified: boolean;
    debtorAgentTownLocationNameValue: boolean;
    debtorAgentTownLocationNameValueSpecified: boolean;
    debtorAgentTownLocationName: boolean | null;
    debtorAgentTownNameValue: boolean;
    debtorAgentTownNameValueSpecified: boolean;
    debtorAgentTownName: boolean | null;
    debtorBicValue: boolean;
    debtorBicValueSpecified: boolean;
    debtorBic: boolean | null;
    debtorBuildingNameValue: boolean;
    debtorBuildingNameValueSpecified: boolean;
    debtorBuildingName: boolean | null;
    debtorBuildingNumValue: boolean;
    debtorBuildingNumValueSpecified: boolean;
    debtorBuildingNum: boolean | null;
    debtorCountryValue: boolean;
    debtorCountryValueSpecified: boolean;
    debtorCountry: boolean | null;
    debtorCountrySubDivValue: boolean;
    debtorCountrySubDivValueSpecified: boolean;
    debtorCountrySubDiv: boolean | null;
    debtorDepartment: number[];
    debtorDepartmentSpecified: boolean;
    debtorDistrictNameValue: boolean;
    debtorDistrictNameValueSpecified: boolean;
    debtorDistrictName: boolean | null;
    debtorFloor: number[];
    debtorFloorSpecified: boolean;
    debtorIdValue: boolean;
    debtorIdValueSpecified: boolean;
    debtorId: boolean | null;
    debtorIdSchemeCodeValue: boolean;
    debtorIdSchemeCodeValueSpecified: boolean;
    debtorIdSchemeCode: boolean | null;
    debtorIdSchemeNameValue: boolean;
    debtorIdSchemeNameValueSpecified: boolean;
    debtorIdSchemeName: boolean | null;
    debtorIssuerValue: boolean;
    debtorIssuerValueSpecified: boolean;
    debtorIssuer: boolean | null;
    debtorLeiValue: boolean;
    debtorLeiValueSpecified: boolean;
    debtorLei: boolean | null;
    debtorName: number[];
    debtorNameSpecified: boolean;
    debtorPostBoxValue: boolean;
    debtorPostBoxValueSpecified: boolean;
    debtorPostBox: boolean | null;
    debtorPostCodeValue: boolean;
    debtorPostCodeValueSpecified: boolean;
    debtorPostCode: boolean | null;
    debtorRoom: number[];
    debtorRoomSpecified: boolean;
    debtorStreetName: number[];
    debtorStreetNameSpecified: boolean;
    debtorSubdepartment: number[];
    debtorSubdepartmentSpecified: boolean;
    debtorTownLocationNameValue: boolean;
    debtorTownLocationNameValueSpecified: boolean;
    debtorTownLocationName: boolean | null;
    debtorTownNameValue: boolean;
    debtorTownNameValueSpecified: boolean;
    debtorTownName: boolean | null;
    initgPtyBuildingNameValue: boolean;
    initgPtyBuildingNameValueSpecified: boolean;
    initgPtyBuildingName: boolean | null;
    initgPtyBuildingNumValue: boolean;
    initgPtyBuildingNumValueSpecified: boolean;
    initgPtyBuildingNum: boolean | null;
    initgPtyCountryValue: boolean;
    initgPtyCountryValueSpecified: boolean;
    initgPtyCountry: boolean | null;
    initgPtyCountrySubDivValue: boolean;
    initgPtyCountrySubDivValueSpecified: boolean;
    initgPtyCountrySubDiv: boolean | null;
    initgPtyCtryOfResValue: boolean;
    initgPtyCtryOfResValueSpecified: boolean;
    initgPtyCtryOfRes: boolean | null;
    initgPtyDepartment: number[];
    initgPtyDepartmentSpecified: boolean;
    initgPtyDistrictNameValue: boolean;
    initgPtyDistrictNameValueSpecified: boolean;
    initgPtyDistrictName: boolean | null;
    initgPtyFloor: number[];
    initgPtyFloorSpecified: boolean;
    initgPtyName: number[];
    initgPtyNameSpecified: boolean;
    initgPtyOrgIdValue: boolean;
    initgPtyOrgIdValueSpecified: boolean;
    initgPtyOrgId: boolean | null;
    initgPtyOrgIdBicValue: boolean;
    initgPtyOrgIdBicValueSpecified: boolean;
    initgPtyOrgIdBic: boolean | null;
    initgPtyOrgIdIssuerValue: boolean;
    initgPtyOrgIdIssuerValueSpecified: boolean;
    initgPtyOrgIdIssuer: boolean | null;
    initgPtyOrgIdLeiValue: boolean;
    initgPtyOrgIdLeiValueSpecified: boolean;
    initgPtyOrgIdLei: boolean | null;
    initgPtyOrgIdSchemeCodeValue: boolean;
    initgPtyOrgIdSchemeCodeValueSpecified: boolean;
    initgPtyOrgIdSchemeCode: boolean | null;
    initgPtyOrgIdSchemePrtryValue: boolean;
    initgPtyOrgIdSchemePrtryValueSpecified: boolean;
    initgPtyOrgIdSchemePrtry: boolean | null;
    initgPtyPostBoxValue: boolean;
    initgPtyPostBoxValueSpecified: boolean;
    initgPtyPostBox: boolean | null;
    initgPtyPostCodeValue: boolean;
    initgPtyPostCodeValueSpecified: boolean;
    initgPtyPostCode: boolean | null;
    initgPtyPrvtIdBirthDtValue: boolean;
    initgPtyPrvtIdBirthDtValueSpecified: boolean;
    initgPtyPrvtIdBirthDt: boolean | null;
    initgPtyPrvtIdCityOfBirthValue: boolean;
    initgPtyPrvtIdCityOfBirthValueSpecified: boolean;
    initgPtyPrvtIdCityOfBirth: boolean | null;
    initgPtyPrvtIdCtryOfBirthValue: boolean;
    initgPtyPrvtIdCtryOfBirthValueSpecified: boolean;
    initgPtyPrvtIdCtryOfBirth: boolean | null;
    initgPtyPrvtIdIdValue: boolean;
    initgPtyPrvtIdIdValueSpecified: boolean;
    initgPtyPrvtIdId: boolean | null;
    initgPtyPrvtIdIdIssuerValue: boolean;
    initgPtyPrvtIdIdIssuerValueSpecified: boolean;
    initgPtyPrvtIdIdIssuer: boolean | null;
    initgPtyPrvtIdIdSchemeCodeValue: boolean;
    initgPtyPrvtIdIdSchemeCodeValueSpecified: boolean;
    initgPtyPrvtIdIdSchemeCode: boolean | null;
    initgPtyPrvtIdIdSchemePrtryValue: boolean;
    initgPtyPrvtIdIdSchemePrtryValueSpecified: boolean;
    initgPtyPrvtIdIdSchemePrtry: boolean | null;
    initgPtyPrvtIdPrvcOfBirthValue: boolean;
    initgPtyPrvtIdPrvcOfBirthValueSpecified: boolean;
    initgPtyPrvtIdPrvcOfBirth: boolean | null;
    initgPtyRoom: number[];
    initgPtyRoomSpecified: boolean;
    initgPtyStreetName: number[];
    initgPtyStreetNameSpecified: boolean;
    initgPtySubdepartment: number[];
    initgPtySubdepartmentSpecified: boolean;
    initgPtyTownLocationNameValue: boolean;
    initgPtyTownLocationNameValueSpecified: boolean;
    initgPtyTownLocationName: boolean | null;
    initgPtyTownNameValue: boolean;
    initgPtyTownNameValueSpecified: boolean;
    initgPtyTownName: boolean | null;
    instr1ForCdtrAgtCodeValue: boolean;
    instr1ForCdtrAgtCodeValueSpecified: boolean;
    instr1ForCdtrAgtCode: boolean | null;
    instr1ForCdtrAgtInfo: number[];
    instr1ForCdtrAgtInfoSpecified: boolean;
    instr2ForCdtrAgtCodeValue: boolean;
    instr2ForCdtrAgtCodeValueSpecified: boolean;
    instr2ForCdtrAgtCode: boolean | null;
    instr2ForCdtrAgtInfo: number[];
    instr2ForCdtrAgtInfoSpecified: boolean;
    instructingFiName2Value: boolean;
    instructingFiName2ValueSpecified: boolean;
    instructingFiName2: boolean | null;
    instructingFiName3Value: boolean;
    instructingFiName3ValueSpecified: boolean;
    instructingFiName3: boolean | null;
    instructingFiName4Value: boolean;
    instructingFiName4ValueSpecified: boolean;
    instructingFiName4: boolean | null;
    intermedFiBicValue: boolean;
    intermedFiBicValueSpecified: boolean;
    intermedFiBic: boolean | null;
    intermedFiBuildingNameValue: boolean;
    intermedFiBuildingNameValueSpecified: boolean;
    intermedFiBuildingName: boolean | null;
    intermedFiBuildingNumValue: boolean;
    intermedFiBuildingNumValueSpecified: boolean;
    intermedFiBuildingNum: boolean | null;
    intermedFiClrSysMemIdCodeValue: boolean;
    intermedFiClrSysMemIdCodeValueSpecified: boolean;
    intermedFiClrSysMemIdCode: boolean | null;
    intermedFiCountryValue: boolean;
    intermedFiCountryValueSpecified: boolean;
    intermedFiCountry: boolean | null;
    intermedFiCountrySubDivValue: boolean;
    intermedFiCountrySubDivValueSpecified: boolean;
    intermedFiCountrySubDiv: boolean | null;
    intermedFiDepartment: number[];
    intermedFiDepartmentSpecified: boolean;
    intermedFiDistrictNameValue: boolean;
    intermedFiDistrictNameValueSpecified: boolean;
    intermedFiDistrictName: boolean | null;
    intermedFiFloor: number[];
    intermedFiFloorSpecified: boolean;
    intermedFiLeiValue: boolean;
    intermedFiLeiValueSpecified: boolean;
    intermedFiLei: boolean | null;
    intermedFiPostBoxValue: boolean;
    intermedFiPostBoxValueSpecified: boolean;
    intermedFiPostBox: boolean | null;
    intermedFiPostCodeValue: boolean;
    intermedFiPostCodeValueSpecified: boolean;
    intermedFiPostCode: boolean | null;
    intermedFiRoom: number[];
    intermedFiRoomSpecified: boolean;
    intermedFiStreetName: number[];
    intermedFiStreetNameSpecified: boolean;
    intermedFiSubdepartment: number[];
    intermedFiSubdepartmentSpecified: boolean;
    intermedFiTownLocationNameValue: boolean;
    intermedFiTownLocationNameValueSpecified: boolean;
    intermedFiTownLocationName: boolean | null;
    intermedFiTownNameValue: boolean;
    intermedFiTownNameValueSpecified: boolean;
    intermedFiTownName: boolean | null;
    intermediaryFiName2Value: boolean;
    intermediaryFiName2ValueSpecified: boolean;
    intermediaryFiName2: boolean | null;
    intermediaryFiName3Value: boolean;
    intermediaryFiName3ValueSpecified: boolean;
    intermediaryFiName3: boolean | null;
    intermediaryFiName4Value: boolean;
    intermediaryFiName4ValueSpecified: boolean;
    intermediaryFiName4: boolean | null;
    intrmyAgt1AcctCurrencyValue: boolean;
    intrmyAgt1AcctCurrencyValueSpecified: boolean;
    intrmyAgt1AcctCurrency: boolean | null;
    intrmyAgt1AcctIbanValue: boolean;
    intrmyAgt1AcctIbanValueSpecified: boolean;
    intrmyAgt1AcctIban: boolean | null;
    intrmyAgt1AcctIdValue: boolean;
    intrmyAgt1AcctIdValueSpecified: boolean;
    intrmyAgt1AcctId: boolean | null;
    intrmyAgt1AcctIdCodeValue: boolean;
    intrmyAgt1AcctIdCodeValueSpecified: boolean;
    intrmyAgt1AcctIdCode: boolean | null;
    intrmyAgt1AcctIdIssuerValue: boolean;
    intrmyAgt1AcctIdIssuerValueSpecified: boolean;
    intrmyAgt1AcctIdIssuer: boolean | null;
    intrmyAgt1AcctIdProprietaryValue: boolean;
    intrmyAgt1AcctIdProprietaryValueSpecified: boolean;
    intrmyAgt1AcctIdProprietary: boolean | null;
    intrmyAgt1AcctName: number[];
    intrmyAgt1AcctNameSpecified: boolean;
    intrmyAgt1AcctProxyCodeValue: boolean;
    intrmyAgt1AcctProxyCodeValueSpecified: boolean;
    intrmyAgt1AcctProxyCode: boolean | null;
    intrmyAgt1AcctProxyId: number[];
    intrmyAgt1AcctProxyIdSpecified: boolean;
    intrmyAgt1AcctProxyProprietaryValue: boolean;
    intrmyAgt1AcctProxyProprietaryValueSpecified: boolean;
    intrmyAgt1AcctProxyProprietary: boolean | null;
    intrmyAgt1AcctTypeCodeValue: boolean;
    intrmyAgt1AcctTypeCodeValueSpecified: boolean;
    intrmyAgt1AcctTypeCode: boolean | null;
    intrmyAgt1AcctTypeProprietaryValue: boolean;
    intrmyAgt1AcctTypeProprietaryValueSpecified: boolean;
    intrmyAgt1AcctTypeProprietary: boolean | null;
    messageTypeValue: boolean;
    messageTypeValueSpecified: boolean;
    messageType: boolean | null;
    prevInstrAgentAcctCurrencyValue: boolean;
    prevInstrAgentAcctCurrencyValueSpecified: boolean;
    prevInstrAgentAcctCurrency: boolean | null;
    prevInstrAgentAcctIbanValue: boolean;
    prevInstrAgentAcctIbanValueSpecified: boolean;
    prevInstrAgentAcctIban: boolean | null;
    prevInstrAgentAcctIdValue: boolean;
    prevInstrAgentAcctIdValueSpecified: boolean;
    prevInstrAgentAcctId: boolean | null;
    prevInstrAgentAcctIdCodeValue: boolean;
    prevInstrAgentAcctIdCodeValueSpecified: boolean;
    prevInstrAgentAcctIdCode: boolean | null;
    prevInstrAgentAcctIdIssuerValue: boolean;
    prevInstrAgentAcctIdIssuerValueSpecified: boolean;
    prevInstrAgentAcctIdIssuer: boolean | null;
    prevInstrAgentAcctIdProprietaryValue: boolean;
    prevInstrAgentAcctIdProprietaryValueSpecified: boolean;
    prevInstrAgentAcctIdProprietary: boolean | null;
    prevInstrAgentAcctName: number[];
    prevInstrAgentAcctNameSpecified: boolean;
    prevInstrAgentAcctProxyCodeValue: boolean;
    prevInstrAgentAcctProxyCodeValueSpecified: boolean;
    prevInstrAgentAcctProxyCode: boolean | null;
    prevInstrAgentAcctProxyId: number[];
    prevInstrAgentAcctProxyIdSpecified: boolean;
    prevInstrAgentAcctProxyPrtryValue: boolean;
    prevInstrAgentAcctProxyPrtryValueSpecified: boolean;
    prevInstrAgentAcctProxyPrtry: boolean | null;
    prevInstrAgentAcctTypeCodeValue: boolean;
    prevInstrAgentAcctTypeCodeValueSpecified: boolean;
    prevInstrAgentAcctTypeCode: boolean | null;
    prevInstrAgentAcctTypePrtryValue: boolean;
    prevInstrAgentAcctTypePrtryValueSpecified: boolean;
    prevInstrAgentAcctTypePrtry: boolean | null;
    prevInstrAgentBuildingNameValue: boolean;
    prevInstrAgentBuildingNameValueSpecified: boolean;
    prevInstrAgentBuildingName: boolean | null;
    prevInstrAgentBuildingNumValue: boolean;
    prevInstrAgentBuildingNumValueSpecified: boolean;
    prevInstrAgentBuildingNum: boolean | null;
    prevInstrAgentCountryValue: boolean;
    prevInstrAgentCountryValueSpecified: boolean;
    prevInstrAgentCountry: boolean | null;
    prevInstrAgentCountrySubDivValue: boolean;
    prevInstrAgentCountrySubDivValueSpecified: boolean;
    prevInstrAgentCountrySubDiv: boolean | null;
    prevInstrAgentDepartment: number[];
    prevInstrAgentDepartmentSpecified: boolean;
    prevInstrAgentDistrictNameValue: boolean;
    prevInstrAgentDistrictNameValueSpecified: boolean;
    prevInstrAgentDistrictName: boolean | null;
    prevInstrAgentFloor: number[];
    prevInstrAgentFloorSpecified: boolean;
    prevInstrAgentPostBoxValue: boolean;
    prevInstrAgentPostBoxValueSpecified: boolean;
    prevInstrAgentPostBox: boolean | null;
    prevInstrAgentPostCodeValue: boolean;
    prevInstrAgentPostCodeValueSpecified: boolean;
    prevInstrAgentPostCode: boolean | null;
    prevInstrAgentRoom: number[];
    prevInstrAgentRoomSpecified: boolean;
    prevInstrAgentStreetName: number[];
    prevInstrAgentStreetNameSpecified: boolean;
    prevInstrAgentSubdepartment: number[];
    prevInstrAgentSubdepartmentSpecified: boolean;
    prevInstrAgentTownNameValue: boolean;
    prevInstrAgentTownNameValueSpecified: boolean;
    prevInstrAgentTownName: boolean | null;
    prevInstrAgtTownLocationNameValue: boolean;
    prevInstrAgtTownLocationNameValueSpecified: boolean;
    prevInstrAgtTownLocationName: boolean | null;
    prevInstructAgentBicValue: boolean;
    prevInstructAgentBicValueSpecified: boolean;
    prevInstructAgentBic: boolean | null;
    prevInstructAgentClrSysMemIdCodeValue: boolean;
    prevInstructAgentClrSysMemIdCodeValueSpecified: boolean;
    prevInstructAgentClrSysMemIdCode: boolean | null;
    prevInstructAgentLeiValue: boolean;
    prevInstructAgentLeiValueSpecified: boolean;
    prevInstructAgentLei: boolean | null;
    prevMsgCreationDateTimeValue: boolean;
    prevMsgCreationDateTimeValueSpecified: boolean;
    prevMsgCreationDateTime: boolean | null;
    prevMsgNameIdValue: boolean;
    prevMsgNameIdValueSpecified: boolean;
    prevMsgNameId: boolean | null;
    returnReasonCodeValue: boolean;
    returnReasonCodeValueSpecified: boolean;
    returnReasonCode: boolean | null;
    transactionIdValue: boolean;
    transactionIdValueSpecified: boolean;
    transactionId: boolean | null;
    uetrValue: boolean;
    uetrValueSpecified: boolean;
    uetr: boolean | null;
    ultmtCdtrBuildingNameValue: boolean;
    ultmtCdtrBuildingNameValueSpecified: boolean;
    ultmtCdtrBuildingName: boolean | null;
    ultmtCdtrBuildingNumValue: boolean;
    ultmtCdtrBuildingNumValueSpecified: boolean;
    ultmtCdtrBuildingNum: boolean | null;
    ultmtCdtrCountryValue: boolean;
    ultmtCdtrCountryValueSpecified: boolean;
    ultmtCdtrCountry: boolean | null;
    ultmtCdtrCountrySubDivValue: boolean;
    ultmtCdtrCountrySubDivValueSpecified: boolean;
    ultmtCdtrCountrySubDiv: boolean | null;
    ultmtCdtrCtryOfResValue: boolean;
    ultmtCdtrCtryOfResValueSpecified: boolean;
    ultmtCdtrCtryOfRes: boolean | null;
    ultmtCdtrDepartment: number[];
    ultmtCdtrDepartmentSpecified: boolean;
    ultmtCdtrDistrictNameValue: boolean;
    ultmtCdtrDistrictNameValueSpecified: boolean;
    ultmtCdtrDistrictName: boolean | null;
    ultmtCdtrFloor: number[];
    ultmtCdtrFloorSpecified: boolean;
    ultmtCdtrName: number[];
    ultmtCdtrNameSpecified: boolean;
    ultmtCdtrOrgIdValue: boolean;
    ultmtCdtrOrgIdValueSpecified: boolean;
    ultmtCdtrOrgId: boolean | null;
    ultmtCdtrOrgIdBicValue: boolean;
    ultmtCdtrOrgIdBicValueSpecified: boolean;
    ultmtCdtrOrgIdBic: boolean | null;
    ultmtCdtrOrgIdIssuerValue: boolean;
    ultmtCdtrOrgIdIssuerValueSpecified: boolean;
    ultmtCdtrOrgIdIssuer: boolean | null;
    ultmtCdtrOrgIdLeiValue: boolean;
    ultmtCdtrOrgIdLeiValueSpecified: boolean;
    ultmtCdtrOrgIdLei: boolean | null;
    ultmtCdtrOrgIdSchemeCodeValue: boolean;
    ultmtCdtrOrgIdSchemeCodeValueSpecified: boolean;
    ultmtCdtrOrgIdSchemeCode: boolean | null;
    ultmtCdtrOrgIdSchemePrtryValue: boolean;
    ultmtCdtrOrgIdSchemePrtryValueSpecified: boolean;
    ultmtCdtrOrgIdSchemePrtry: boolean | null;
    ultmtCdtrPostBoxValue: boolean;
    ultmtCdtrPostBoxValueSpecified: boolean;
    ultmtCdtrPostBox: boolean | null;
    ultmtCdtrPostCodeValue: boolean;
    ultmtCdtrPostCodeValueSpecified: boolean;
    ultmtCdtrPostCode: boolean | null;
    ultmtCdtrPrvtIdBirthDtValue: boolean;
    ultmtCdtrPrvtIdBirthDtValueSpecified: boolean;
    ultmtCdtrPrvtIdBirthDt: boolean | null;
    ultmtCdtrPrvtIdCityOfBirthValue: boolean;
    ultmtCdtrPrvtIdCityOfBirthValueSpecified: boolean;
    ultmtCdtrPrvtIdCityOfBirth: boolean | null;
    ultmtCdtrPrvtIdCtryOfBirthValue: boolean;
    ultmtCdtrPrvtIdCtryOfBirthValueSpecified: boolean;
    ultmtCdtrPrvtIdCtryOfBirth: boolean | null;
    ultmtCdtrPrvtIdIdValue: boolean;
    ultmtCdtrPrvtIdIdValueSpecified: boolean;
    ultmtCdtrPrvtIdId: boolean | null;
    ultmtCdtrPrvtIdIdIssuerValue: boolean;
    ultmtCdtrPrvtIdIdIssuerValueSpecified: boolean;
    ultmtCdtrPrvtIdIdIssuer: boolean | null;
    ultmtCdtrPrvtIdIdSchemeCodeValue: boolean;
    ultmtCdtrPrvtIdIdSchemeCodeValueSpecified: boolean;
    ultmtCdtrPrvtIdIdSchemeCode: boolean | null;
    ultmtCdtrPrvtIdIdSchemePrtryValue: boolean;
    ultmtCdtrPrvtIdIdSchemePrtryValueSpecified: boolean;
    ultmtCdtrPrvtIdIdSchemePrtry: boolean | null;
    ultmtCdtrPrvtIdPrvcOfBirthValue: boolean;
    ultmtCdtrPrvtIdPrvcOfBirthValueSpecified: boolean;
    ultmtCdtrPrvtIdPrvcOfBirth: boolean | null;
    ultmtCdtrRoom: number[];
    ultmtCdtrRoomSpecified: boolean;
    ultmtCdtrStreetName: number[];
    ultmtCdtrStreetNameSpecified: boolean;
    ultmtCdtrSubdepartment: number[];
    ultmtCdtrSubdepartmentSpecified: boolean;
    ultmtCdtrTownLocationNameValue: boolean;
    ultmtCdtrTownLocationNameValueSpecified: boolean;
    ultmtCdtrTownLocationName: boolean | null;
    ultmtCdtrTownNameValue: boolean;
    ultmtCdtrTownNameValueSpecified: boolean;
    ultmtCdtrTownName: boolean | null;
    ultmtDbtrBuildingNameValue: boolean;
    ultmtDbtrBuildingNameValueSpecified: boolean;
    ultmtDbtrBuildingName: boolean | null;
    ultmtDbtrBuildingNumValue: boolean;
    ultmtDbtrBuildingNumValueSpecified: boolean;
    ultmtDbtrBuildingNum: boolean | null;
    ultmtDbtrCountryValue: boolean;
    ultmtDbtrCountryValueSpecified: boolean;
    ultmtDbtrCountry: boolean | null;
    ultmtDbtrCountrySubDivValue: boolean;
    ultmtDbtrCountrySubDivValueSpecified: boolean;
    ultmtDbtrCountrySubDiv: boolean | null;
    ultmtDbtrCtryOfResValue: boolean;
    ultmtDbtrCtryOfResValueSpecified: boolean;
    ultmtDbtrCtryOfRes: boolean | null;
    ultmtDbtrDepartment: number[];
    ultmtDbtrDepartmentSpecified: boolean;
    ultmtDbtrDistrictNameValue: boolean;
    ultmtDbtrDistrictNameValueSpecified: boolean;
    ultmtDbtrDistrictName: boolean | null;
    ultmtDbtrFloor: number[];
    ultmtDbtrFloorSpecified: boolean;
    ultmtDbtrName: number[];
    ultmtDbtrNameSpecified: boolean;
    ultmtDbtrOrgIdValue: boolean;
    ultmtDbtrOrgIdValueSpecified: boolean;
    ultmtDbtrOrgId: boolean | null;
    ultmtDbtrOrgIdBicValue: boolean;
    ultmtDbtrOrgIdBicValueSpecified: boolean;
    ultmtDbtrOrgIdBic: boolean | null;
    ultmtDbtrOrgIdIssuerValue: boolean;
    ultmtDbtrOrgIdIssuerValueSpecified: boolean;
    ultmtDbtrOrgIdIssuer: boolean | null;
    ultmtDbtrOrgIdLeiValue: boolean;
    ultmtDbtrOrgIdLeiValueSpecified: boolean;
    ultmtDbtrOrgIdLei: boolean | null;
    ultmtDbtrOrgIdSchemeCodeValue: boolean;
    ultmtDbtrOrgIdSchemeCodeValueSpecified: boolean;
    ultmtDbtrOrgIdSchemeCode: boolean | null;
    ultmtDbtrOrgIdSchemePrtryValue: boolean;
    ultmtDbtrOrgIdSchemePrtryValueSpecified: boolean;
    ultmtDbtrOrgIdSchemePrtry: boolean | null;
    ultmtDbtrPostBoxValue: boolean;
    ultmtDbtrPostBoxValueSpecified: boolean;
    ultmtDbtrPostBox: boolean | null;
    ultmtDbtrPostCodeValue: boolean;
    ultmtDbtrPostCodeValueSpecified: boolean;
    ultmtDbtrPostCode: boolean | null;
    ultmtDbtrPrvtIdBirthDtValue: boolean;
    ultmtDbtrPrvtIdBirthDtValueSpecified: boolean;
    ultmtDbtrPrvtIdBirthDt: boolean | null;
    ultmtDbtrPrvtIdCityOfBirthValue: boolean;
    ultmtDbtrPrvtIdCityOfBirthValueSpecified: boolean;
    ultmtDbtrPrvtIdCityOfBirth: boolean | null;
    ultmtDbtrPrvtIdCtryOfBirthValue: boolean;
    ultmtDbtrPrvtIdCtryOfBirthValueSpecified: boolean;
    ultmtDbtrPrvtIdCtryOfBirth: boolean | null;
    ultmtDbtrPrvtIdIdValue: boolean;
    ultmtDbtrPrvtIdIdValueSpecified: boolean;
    ultmtDbtrPrvtIdId: boolean | null;
    ultmtDbtrPrvtIdIdIssuerValue: boolean;
    ultmtDbtrPrvtIdIdIssuerValueSpecified: boolean;
    ultmtDbtrPrvtIdIdIssuer: boolean | null;
    ultmtDbtrPrvtIdIdSchemeCodeValue: boolean;
    ultmtDbtrPrvtIdIdSchemeCodeValueSpecified: boolean;
    ultmtDbtrPrvtIdIdSchemeCode: boolean | null;
    ultmtDbtrPrvtIdIdSchemePrtryValue: boolean;
    ultmtDbtrPrvtIdIdSchemePrtryValueSpecified: boolean;
    ultmtDbtrPrvtIdIdSchemePrtry: boolean | null;
    ultmtDbtrPrvtIdPrvcOfBirthValue: boolean;
    ultmtDbtrPrvtIdPrvcOfBirthValueSpecified: boolean;
    ultmtDbtrPrvtIdPrvcOfBirth: boolean | null;
    ultmtDbtrRoom: number[];
    ultmtDbtrRoomSpecified: boolean;
    ultmtDbtrStreetName: number[];
    ultmtDbtrStreetNameSpecified: boolean;
    ultmtDbtrSubdepartment: number[];
    ultmtDbtrSubdepartmentSpecified: boolean;
    ultmtDbtrTownLocationNameValue: boolean;
    ultmtDbtrTownLocationNameValueSpecified: boolean;
    ultmtDbtrTownLocationName: boolean | null;
    ultmtDbtrTownNameValue: boolean;
    ultmtDbtrTownNameValueSpecified: boolean;
    ultmtDbtrTownName: boolean | null;
    version2: VersionType;
    any: XmlElement[];
    anySpecified: boolean;
}